### ISSUE TITLE
cephfs client side quotas

### ISSUE THREAD

**Issue by laggeduout** [nfs-ganesha/nfs-ganesha#100]
Ceph quotas are configured using virtual extended attributes:

  ceph.quota.max_files – file limit
  ceph.quota.max_bytes – byte limit

If the attributes appear on a directory inode that means a quota is configured there. If they are not present then no quota is set on that directory (although one may still be configured on a parent directory).

It seems that the ceph FSAL does not use this attribute and in turn quotas are ignored.

**Comment by ffilz** [comment]
Ganesha quotas definitely need some work, I'm not surprised here.

**Comment by ajarr** [comment]
This issue has been reported here as well http://tracker.ceph.com/issues/16526

As mentioned in http://tracker.ceph.com/issues/16526 I didn't face this issue with latest ganesha, and Ceph (Jewel) with `client quota = true` conf option set in the ceph.conf file used by ganesha.

@laggeduout  can you check?

**Comment by ffilz** [comment]
Can we close this issue?
