### ISSUE TITLE
NFS-Ganesha version 5.5.3 for FSAL Lizardfs build got failed at 98%

### ISSUE THREAD

**Issue by RajkumarKesavan** [nfs-ganesha/nfs-ganesha#1001]
Got an exception as mentioned below while executing "sudo make" command. 

Exception
[96%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/ds.c.o
nfs-ganesha/src/FSAL/FSAL_LIZARDFS/ds.c: In function ‘lzfs_int_clear_fileinfo_cache’
nfs-ganesha/src/FSAL/FSAL_LIZARDFS/ds.c:38:2: error: ‘for’ loop initial declarations are only allowed in C99 mode 

The above build is ran on Oracle Linux 7.9 and Ganesha Version 5.5.3

Tried couple of work around as mentioned below. But no luck. Looking for the solution to resolve the same.

Work Around 1
Added below line for setting C_FLAGS in LINUX if block under the file nfs-ganesha/src/CMakeLists.txt 

if (LINUX)
         set(PLATFORM "LINUX")
         set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
         
Work Around 2
sudo make CFLAGS="-std=c99"

**Comment by dang** [comment]
Something is wrong with the compiler installed on your system.  The default for GCC is -std=gnu17.  Ganesha definitely requires C99, and probably C11, and maybe C17.

**Comment by RajkumarKesavan** [comment]
@dang 

Thanks for your quick response. I have resolved the issue with gnu99 GCC but not with the c99 GCC. I have also found the CFlag which i should add for Lizardfs FSAL during the cmake phase. The below CFLAG found in the src/FSAL/FSAL_LIZARDFS/CMakeLists.txt line number 24.

-DLIZARDFS_CFLAGS="-std=gnu99"  

Now the Build completed with 100%.

Scanning dependencies of target fsalproxy_v4
[ 93%] Building C object FSAL/FSAL_PROXY_V4/CMakeFiles/fsalproxy_v4.dir/handle.c.o
[ 93%] Building C object FSAL/FSAL_PROXY_V4/CMakeFiles/fsalproxy_v4.dir/main.c.o
[ 94%] Building C object FSAL/FSAL_PROXY_V4/CMakeFiles/fsalproxy_v4.dir/export.c.o
[ 94%] Building C object FSAL/FSAL_PROXY_V4/CMakeFiles/fsalproxy_v4.dir/xattrs.c.o
Linking C shared module libfsalproxy_v4.so
[ 94%] Built target fsalproxy_v4
Scanning dependencies of target fsalproxy_v3
[ 95%] Building C object FSAL/FSAL_PROXY_V3/CMakeFiles/fsalproxy_v3.dir/main.c.o
[ 95%] Building C object FSAL/FSAL_PROXY_V3/CMakeFiles/fsalproxy_v3.dir/nlm.c.o
[ 95%] Building C object FSAL/FSAL_PROXY_V3/CMakeFiles/fsalproxy_v3.dir/rpc.c.o
[ 96%] Building C object FSAL/FSAL_PROXY_V3/CMakeFiles/fsalproxy_v3.dir/utils.c.o
Linking C shared module libfsalproxy_v3.so
[ 96%] Built target fsalproxy_v3
Scanning dependencies of target fsallizardfs
[ 97%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/context_wrap.c.o
[ 97%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/ds.c.o
[ 97%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/export.c.o
[ 98%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/handle.c.o
[ 98%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/lzfs_acl.c.o
[ 98%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/lzfs_internal.c.o
[ 98%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/main.c.o
[100%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/mds_export.c.o
[100%] Building C object FSAL/FSAL_LIZARDFS/CMakeFiles/fsallizardfs.dir/mds_handle.c.o
Linking C shared module libfsallizardfs.so
[100%] Built target fsallizardfs
