### ISSUE TITLE
Compilation error on 5.5 and 5.5.3 - need ntirpc pullup

### ISSUE THREAD

**Issue by DUOLabs333** [nfs-ganesha/nfs-ganesha#1002]
I get `error: implicit declaration of function ‘assert’`. This from a git checkout.

**Comment by DUOLabs333** [comment]
You need `-DCMAKE_BUILD_TYPE=Release` for it to be a warning.

**Comment by DUOLabs333** [comment]
This was fixed in ntirpc, but the repo wasn't updated. I had to force pull to get the missing commit(s).

**Comment by ffilz** [comment]
Yes, this will be fixed when we do an ntirpc pullup for V5.6
