### ISSUE TITLE
Failed to get output of ganesha_stats with json option for few commands

### ISSUE THREAD

**Issue by tshete1** [nfs-ganesha/nfs-ganesha#1003]
ganesha_stats utility has an option "json" which provides the output of commands in json format. 
For the list_clients command for json option, we get AssertionError: 
 
[root@nsds1 Ganesha]# ganesha_stats json list_clients
Traceback (most recent call last):
  File "/usr/bin/ganesha_stats", line 196, in <module>
    print(result.json()) if output_json else print(result)
  File "/usr/lib/python3.6/site-packages/Ganesha/glib_dbus_stats.py", line 55, in json
    output = self.report()
  File "/usr/lib/python3.6/site-packages/Ganesha/glib_dbus_stats.py", line 63, in report
    self.fill_report(report)
  File "/usr/lib/python3.6/site-packages/Ganesha/glib_dbus_stats.py", line 295, in fill_report
    'nlmv4_stats': dbus_to_std(client.nlmv4_stats_avail),
  File "/usr/lib/python3.6/site-packages/Ganesha/glib_dbus_stats.py", line 43, in dbus_to_std
    assert ctor is not None, "{}".format(v.__class__.__name__)
AssertionError: int

For a few commands like iov3, iov4 etc. we were getting the wrong values for writes:
[root@nsds1 /]# ganesha_stats  iov4
EXPORT 10:
                requested       transferred          total          errors         latency
READv4:                0               0               0               0               0               0
WRITEv4:           40960           40960               1               0         2798398               0

[root@nsds1 /]# ganesha_stats json iov4
[{"status": {"time": "2023-09-07T06:49:30Z"}, "id": 10, "read": {"requested": 0, "transferred": 0, "total": 0, "errors": 0, "latency": 0}, "write": {"requested": 0, "transferred": 0, "total": 0, "errors": 0, "latency": 0}}]

Need to resolve these json option related issues.

Patch to come.

**Comment by tshete1** [comment]
Patches: 
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1169860
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1169859

**Comment by ffilz** [comment]
Thanks for the patches.

**Comment by tshete1** [comment]
After the fix below are the outputs for ganesha_stats json option:

[root@nsds1 /]# ganesha_stats json list_clients
{"status": {"time": "2023-09-22T14:53:03Z"}, "clients": [{"addr": "::ffff:10.36.80.157", "nfsv3_stats": 0, "nfsv40_stats": 1, "nfsv41_stats": 0, "nfsv42_stats": 0, "mnt_stats": 1, "nlmv4_stats": 0, "rquota_stats": 0, "9p_stats": 0}, {"addr": "::ffff:172.16.5.157", "nfsv3_stats": 0, "nfsv40_stats": 1, "nfsv41_stats": 0, "nfsv42_stats": 0, "mnt_stats": 1, "nlmv4_stats": 0, "rquota_stats": 0, "9p_stats": 0}, {"addr": "::ffff:172.16.6.157", "nfsv3_stats": 0, "nfsv40_stats": 1, "nfsv41_stats": 0, "nfsv42_stats": 0, "mnt_stats": 0, "nlmv4_stats": 0, "rquota_stats": 0, "9p_stats": 0}]}

[root@nsds1 /]# ganesha_stats json iov4
[{"status": {"time": "2023-09-07T06:49:30Z"}, "id": 10, "read": {"requested": 0, "transferred": 0, "total": 0, "errors": 0, "latency": 0}, "write": {"requested": 40960, "transferred": 40960, "total": 1, "errors": 0, "latency": 2798398}}, {"status": {"time": "2023-09-07T06:49:30Z"}, "id": 10, "read": {"requested": 0, "transferred": 0, "total": 0, "errors": 0, "latency": 0}, "write": {"requested": 40960, "transferred": 40960, "total": 1, "errors": 0, "latency": 2798398}}]

**Comment by ffilz** [comment]
Let's not close this until the patch is merged and verified after merge,

**Comment by tshete1** [comment]
> Let's not close this until the patch is merged and verified after merge,

Ok sure. I will keep it open
