### ISSUE TITLE
Changes on host takes time to show up on client

### ISSUE THREAD

**Issue by DUOLabs333** [nfs-ganesha/nfs-ganesha#1005]
If I do `echo e >hello` on the server, the client will see `e`. However, if I then do `echo f > hello`, the client will still see `e`, until some time later.

**Comment by ffilz** [comment]
That is a client caching issue. You can try mount -onoac and should see the changes immediately. The disadvantage of this setting is the client needs to constantly poll the server. Additionally, if you are making these changes from a server process other than Ganesha (i.e. local process or some other server such as Samba) you would need to disable Ganesha's attribute caching.

**Comment by DUOLabs333** [comment]
I disabled attribute caching and I did `sudo mount -t nfs -o noac`. The problem still occurs.

**Comment by DUOLabs333** [comment]
I found that the only way to really prevent this is by clearing the pagecache.

**Comment by DUOLabs333** [comment]
Actually, I found that just this: `Attr_Expiration_Time = 0;` in the Export block works the best. Thanks for the hint!

**Comment by DUOLabs333** [comment]
However, I have found that if you stop the server, and a client mounts, it takes some time (similar in time to the original problem), for the first read to complete. Subsequent reads are as fast as expected.

**Comment by ffilz** [comment]
> However, I have found that if you stop the server, and a mounts, it takes some time (similar in time to the original problem), for the first read to complete. Subsequent reads are as fast as expected.

That's the grace period that delays I/O until the grace period is over. If you use NFS v4.1 you might observe this taking less time as once all clients have indicated they have finished reclaiming open and lock state, grace period can be ended.

**Comment by DUOLabs333** [comment]
Is there a way to shrink this time, or is this unavoidable?

**Comment by ffilz** [comment]
It can be configured, but it is not advised to reduce it too much if your workload includes byte range locks. If your workload truly only requires opening files it could be trimmed shorter, however, the client may also throw errors if it is unable to reclaim opens after a server reboot.

NFSV4 {} parameter block:

Grace_Period (in seconds, can be 0, default 90)
Lease_Lifetime (in seconds, should be shorter than grace, default 60)

**Comment by DUOLabs333** [comment]
`Grace_Period=0` worked perfectly.
