### ISSUE TITLE
Poor streaming performance

### ISSUE THREAD

**Issue by DUOLabs333** [nfs-ganesha/nfs-ganesha#1006]
I noticed that streaming (videos or other files) is quite slow to seek. This might be due to my choice of media player (VLC Android), or something else.

Trying to increase `MaxRead` to `100*1024*1024` (the number, not the actual expression) causes ganesha to not mount that export.

**Comment by ffilz** [comment]
The highest MaxRead can go is 64*1024*1024 (see the man pages or src/config_samples/config.txt)

What FSAL are you using, and if FSAL_VFS, what back end filesystem?

**Comment by DUOLabs333** [comment]
Oh, I thought that was the default, not the maximum. I'm using VFS on ext4.

**Comment by DUOLabs333** [comment]
However, I tried Kodi, and NFS seeking is much faster there, so maybe it's just VLC.
