### ISSUE TITLE
NFSv4.1 session expiry causing delay to Read IOs - implement courteous server

### ISSUE THREAD

**Issue by rojingeorge** [nfs-ganesha/nfs-ganesha#1007]
While running certain storage benchmarking framework like MLPerf, seen that there are at times delay in READ IOs. The delay is because of NFSv4.1 session expiry in the middle of the test.

**For repro this behaviour -** 
On a distributed share, had set up two mounts - one to the root of the share and a submount to top level directory, present on another node. The expiry happens to the root. However, it affects the submount too. The client does not send any requests during the recovery.
Some findings of this test...
1. The test completes if both top level directory and share root are on the same node.
2. The test completes if a periodic request is sent to the root of the share (ex: "ls" on the root)
3. The test completes if data is under a top level directory that is on the same node as the share root.

```
[root@bdaa688 NFS_Non_Owner]$ cat ../read.sh
#!/bin/bash

for ii in {1..10000};
do
        start=$(date +%s);
        dd if=test/file$ii of=test/temp count=1024 bs=1024 status=none;
        end=$(date +%s);
        timeElapsed=$(($end-$start))
        if [ $timeElapsed -gt 1 ]; then
                echo "File$ii - Read elapsed Time: $timeElapsed seconds"
        fi
done
[root@bdaa688 NFS_Non_Owner]$ sh ./../read.sh
File1462 - Read elapsed Time: 25 seconds
^@File3200 - Read elapsed Time: 25 seconds
^@File4490 - Read elapsed Time: 7 seconds
[root@bdaa688 NFS_Non_Owner]$ sh ./../read.sh
File592 - Read elapsed Time: 26 seconds
^@File1086 - Read elapsed Time: 26 seconds
File1635 - Read elapsed Time: 3 seconds
^@^@File5436 - Read elapsed Time: 26 seconds
^@^@File7279 - Read elapsed Time: 26 seconds
^@File8417 - Read elapsed Time: 26 seconds
```

Also, did an experiment with Kernel NFS server and the issue does not reproduce. It looks like kernel NFS server does not expire clients unless the number of unresponsive clients go over a limit.

**Comment by rojingeorge** [comment]
One potential fix could be to follow what knfsd does and keep the expired sessions in memory. i.e. 
NFSv4 "Courteous Server" as part of Linux 5.19 NFSD.
https://www.phoronix.com/news/Linux-5.19-NFSD-Courteous

With the current Ganesha code design, solution for this issue would be to keep expired clients until the number of expired clients is within some limits (like knfsd does). 
1. We need to keep track of all expired clients in LRU fashion.
2. Pick the oldest expired clients when the number of clients exceeds the max limit, and clean them up
3. Also, if required, may need to keep track of the amount of state the client owns. If it has large number of opened files, we may not want to hold the memory for a client that has gone away.

**Comment by ffilz** [comment]
Hmm, this actually sounds like a client bug that happens to be masked by the kernel's Courteous Server implementation.

I do want to get Courteous Server implemented sometime, but we have limited resources for Ganesha development.

Not expiring clients without a Courteous Server implementation however is not a good solution. Another client would be prevented from acquiring conflicting state (locks and opens) while an unexpired (but hasn't renewed in time) client holds state.

**Comment by rojingeorge** [comment]
Yeah, agree...
In continuation with the solution discussed above, with our Ganesha code/design we should as well, be able get the above logic of granting states to new client(conflicting with the expired client)...Will spend some time on it...

**Comment by rojingeorge** [comment]
Have implemented the courteous server features by keeping the expired client in memory and avoiding expiring clients post lease period, unless the number of unresponsive clients go over a limit. Ganesha keeps track of all expired clients in LRU fashion and picks the oldest expired client when the number of clients exceeds the max limit. This allows Ganesha to retain the open & lock state and thereby helping certain client workloads like MLPerf to run smoothly, even after a network partition or client bugs...

Also with this courteous server implementation, a client would be allowed acquiring conflicting state (locks and opens) while an unexpired (but hasn't renewed in time) client holds state...

Have verified above mentioned scenarios of avoiding expiring client retaining the open & lock states, then expiring then after reaching threshold and also conflicting access from another clients...

Posting the patch for review : https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1169897

**Comment by ffilz** [comment]
Merged in V6-dev.2, closing
