### ISSUE TITLE
How can I  get subdir's  available and total space with df ?

### ISSUE THREAD

**Issue by itfanr** [nfs-ganesha/nfs-ganesha#101]
For example , there are 10 subdirectories in my root file system,each given 10T.
Then I  mountted  one to local file system:

```
mount -t nfs  host11:/dir1  /mnt/nfs -o vers=3 
```

But, I got 100T total space using df.

My question is if the NFSv3 protocol can only support root filehandle during the nfs3_fsstat?
If so,what about NFSv4?

How can I make it without modifying the  nfs-utils code  in kernel?

Thanks.

**Comment by ffilz** [comment]
df works on filesystems. The Linux client mounts a client side filesystem for each exported filesystem from the server (whether that is via a single export with the nohide option, or multiple exports).

If you want to determine the space used by a sub-directory on a filesystem, use the du command.

**Comment by itfanr** [comment]
@ffilz Thank you .I have made it  by the infomation from Inode which contains the stat info.
