### ISSUE TITLE
Can directory export support spell in Chinese？

### ISSUE THREAD

**Issue by bear-Zhao178** [nfs-ganesha/nfs-ganesha#1014]
We have a requirement for NFS-Ganesha to support exporting directories with Chinese names. However, when I tried to change the exported directory to a Chinese name, I encountered an error as shown in the logs. I would like to confirm if Ganesha supports Chinese directories.

18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] main :NFS STARTUP :CRIT :Error (token scan) while parsing (/etc/ganesha/ganesha.conf)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Unexpected character (æ)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Unexpected character (µ)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Unexpected character (<8b>)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Unexpected character (è)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Unexpected character (¯)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Unexpected character (<95>)
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Syntax error in statement
18/10/2023 17:55:52 : epoch 652faba8 : node127 : ganesha.nfsd-1291889[main] main :NFS STARTUP :FATAL :Fatal errors.  Server exiting...

**Comment by ffilz** [comment]
Did you try using quotes around the name? I'm looking at the parsing code trying to determine what it does with quoted strings.

**Comment by bear-Zhao178** [comment]
the conf like this:

export {
   path = /data/nfs0;
   k8s_flag = False;
   mode = 0777;
   uid = 0;
   gid = 0;
   export_id = 1;
   pseudo = /NAS/CAPFS/data/目录0;
   Filesystem_id = 0x93fb7b52737e5a80.0xbafbdb208c81c613;
   DisableReaddirPlus = False;
   Enable_Irwxugo = False;
   FSAL {
       name = CEPH;
   }
 client {
       clients = *;
       Access_Type = RW;
       Squash = No_Root_Squash;
   }
}

Can Chinese characters not be parsed?

**Comment by ffilz** [comment]
Try putting that pseudo path in quotes (double or single). If the file is UTF-8 I think it will work (if not, I'll have to delve into the parser and understand why not, but with UTF-8 each character is made of bytes with the high bit set, so they won't match any normal ASCII character that would have special meaning to the parser.

**Comment by ffilz** [comment]
so like

Pseudo = "/NAS/CAPFS/data/目录0";

**Comment by bear-Zhao178** [comment]
OK, I'll try, thanks a lot.

**Comment by bear-Zhao178** [comment]
It works, thank you~

**Comment by ffilz** [comment]
Glad that works. I expected it to, but I personally have never done any testing with non-ASCII characters.

I will update the documentation to make it clear path strings and such should be quoted, especially if they might include special characters where they must be quoted. It's sort of a short cut that ASCII path strings and such can be used without quotes, but that can also fail if the string happens to be a keyword.
