### ISSUE TITLE
nfs4 bypass mdcache

### ISSUE THREAD

**Issue by Bingo0203** [nfs-ganesha/nfs-ganesha#1015]
How to bypass mdcache for nfs4_op process in NFSv4 version?

Thanks to gentleman

**Comment by dang** [comment]
You cannot bypass mdcache.  It is the handle cache, and is necessary to make NFS work properly.  If you don't want it to cache metadata, you can set attr_expiration_time to 0 in the export (or export_defaults).  This will not bypass mdcache, but it will cause it to do calls for all metadata.

**Comment by Bingo0203** [comment]
OK, I 'll try, thanks a lot

**Comment by ffilz** [comment]
Closing as answered
