### ISSUE TITLE
exporting share from exfat USB drive

### ISSUE THREAD

**Issue by premax** [nfs-ganesha/nfs-ganesha#1023]
Hello

I have successfully managed to export directory from exfat drive on Ubuntu Server 20.04. Recently I have upgraded Ubuntu to 22.04 LTS and also upgraded Ganesha to newest v5.  And now I cannot export from exfat drive, got the following error message: 

```
vfs_lookup_path :FSAL :CRIT :Could not get handle for path /ARCH/veeam-br-arch-01, error Operation not supported
init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=1 Path=/ARCH/veeam-br-arch-01 FSAL_ERROR=(Operation not supported,95)
```

I am using VFS FSAL, here is my config:

```
EXPORT
{
        ## Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 1;

        ## Exported path (mandatory)
        Path = /ARCH/veeam-br-arch-01;

        ## Pseudo Path (required for NFSv4 or if mount_path_pseudo = true)
        #Pseudo = /nonexistent;

        ## Restrict the protocols that may use this export.  This cannot allow
        ## access that is denied in NFS_CORE_PARAM.
        Protocols = 3;

        ## Access type for clients.  Default is None, so some access must be
        ## given. It can be here, in the EXPORT_DEFAULTS, or in a CLIENT block
        #Access_Type = RW;

        ## Whether to squash various users.
        #Squash = root_squash;

        ## Allowed security types for this export
        #Sectype = sys,krb5,krb5i,krb5p;

        ## Exporting FSAL
        FSAL {
                Name = VFS;
        }

         CLIENT {
                clients = 172.30.200.218;
                access_type = RW;
        }
}
```
In Ubuntu 22.04 the package exfat-fuse is gone. I have installed exfatprogs instead, but it does not help.

Regards
PP

**Comment by dang** [comment]
The NFS protocol depends on the ability to open a file from a handle.  On linux, we use open_by_handle_at(2) to do this.  However, this syscall requires filesystem support to work, so it doesn't work on all filesystems.  Best guess is that the exfat FUSE driver did support it, but the replacement exfat driver does not.

**Comment by ffilz** [comment]
Yup, exfat doesn't support name_to_handle_at. Here are the kernel filesystems that implement encode_fh which is what ultimately implements name_to_handle_at:

fs/btrfs/export.c <global> 289 .encode_fh = btrfs_encode_fh,
fs/ceph/export.c <global> 599 .encode_fh = ceph_encode_fh,
fs/fat/nfs.c <global> 288 .encode_fh = fat_encode_fh_nostale,
fs/fuse/inode.c <global> 1066 .encode_fh = fuse_encode_fh,
fs/gfs2/export.c <global> 190 .encode_fh = gfs2_encode_fh,
fs/isofs/export.c <global> 189 .encode_fh = isofs_export_encode_fh,
fs/kernfs/mount.c <global> 155 .encode_fh = kernfs_encode_fh,
fs/nfs/export.c <global> 149 .encode_fh = nfs_encode_fh,
fs/nilfs2/namei.c <global> 569 .encode_fh = nilfs_encode_fh,
fs/ocfs2/export.c <global> 279 .encode_fh = ocfs2_encode_fh,
fs/orangefs/super.c <global> 390 .encode_fh = orangefs_encode_fh,
fs/overlayfs/export.c <global> 882 .encode_fh = ovl_encode_fh,
fs/overlayfs/export.c <global> 891 .encode_fh = ovl_encode_fh,
fs/reiserfs/super.c <global> 864 .encode_fh = reiserfs_encode_fh,
fs/udf/namei.c <global> 1000 .encode_fh = udf_encode_fh,
fs/xfs/xfs_export.c <global> 241 .encode_fh = xfs_fs_encode_fh,
mm/shmem.c <global> 3826 .encode_fh = shmem_encode_fh,

**Comment by ffilz** [comment]
Wiki Documentation updated:

https://github.com/nfs-ganesha/nfs-ganesha/wiki/VFS

**Comment by ffilz** [comment]
Closing since the wiki has been updated
