### ISSUE TITLE
[question] Use of Recovery directory

### ISSUE THREAD

**Issue by aureq** [nfs-ganesha/nfs-ganesha#1027]
Hi,

I'm learning how to use NFS Ganesha and the Recovery parameters have caught my attention.
Looking at the [documentation](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-core-config.rst), I'm struggling to under what it's used for and setting some expectations.

What information is stored in the recovery directory?
What is it used for?
How big this directory could become?
What would happen if removed or lost?

**Comment by dang** [comment]
The recovery DB stores client info that is used to recover after a crash or restart (the NFS Grace system).  It doesn't store much info, and scales with the number of clients.  If it's removed, then Ganesha cannot recover after a crash or restart, and any outstanding data clients have not yet written will be lost, possibly corrupting exported data.

**Comment by ffilz** [comment]
To add a bit more, the recovery directory has an entry for each NFSv4.x client. When Ganesha restarts, a list of clients is derived from this directory and only those clients are allowed to reclaim state (opens, locks, delegations, layouts). It is similar in purpose to the directory rpc.statd uses for NFSv3 lock clients.

Ganesha supports the directory via a plug in module, and it is possible to store the records in a database (rados for example).

**Comment by aureq** [comment]
Thanks you both for taking the time to explain and the clarity of your answers.
