### ISSUE TITLE
Could not create export for (/cephfs) to (/)

### ISSUE THREAD

**Issue by 47295743** [nfs-ganesha/nfs-ganesha#1033]
I'm having an error running nfs-ganesha on centos 8.5, I can't quite figure out what I'm doing wrong.

Here's what I've got installed:
nfs-ganesha + nfs-ganesha-ceph
ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable)
nfs-ganesha version:V3.5-stable
centos 8.5.2111

anything else that came with the nfs-ganesha package.

Here's the error as recorded by /var/log/ganesha/ganesha.log:

06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5290[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 3.5
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] load_rados_config :CONFIG :WARN :Missing RADOS URLs backend library
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] create_export :FSAL :CRIT :Unable to init Ceph handle for /.
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL Ceph
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/cephfs) to (/)
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:25): 1 validation errors in block FSAL
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:25): Errors processing block (FSAL)
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:14): 1 validation errors in block EXPORT
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:14): Errors processing block (EXPORT)
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore+ep
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/var/run/ganesha) already exists
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:2)
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
06/12/2023 00:58:53 : epoch 657037cd : k8s-test161 : ganesha.nfsd-5291[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------

my ceph user id and key ：
[root@k8s-162 ~]# ceph auth print-key client.admin
AQAmhm1lcN3iAxAABPBJnVwIsTMucVFnXtws2Q==

my cephfs ：
[root@k8s-test161 ~]# ceph fs ls
name: cephfs, metadata pool: cephfs_metadata, data pools: [cephfs_data ]

Here's the contents of my ganesha.conf as well:

`EXPORT
{
        Export_ID=1;
        Path = /;
        Pseudo = /cephfs;
        Access_Type = RW;
        protocols = 3, 4;
        transports = "UDP", "TCP";
        Squash = no_root_squash;
        FSAL {
                secret_access_key = "AQAmhm1lcN3iAxAABPBJnVwIsTMucVFnXtws2Q==";   
                user_id = "client.admin";  
                name = "CEPH";  
                filesystem = "cephfs";  
        }        
}

CEPH
{
	# Path to a ceph.conf file for this ceph cluster.
	Ceph_Conf = /etc/ceph/ceph.conf;

	# User file-creation mask. These bits will be masked off from the unix
	# permissions on newly-created inodes.
	umask = 0;
}

LOG {                         
        Facility {
                name = FILE;  
                destination = "/var/log/ganesha/ganesha.log";  
                enable = active;  
        }
}`

**Comment by dang** [comment]
ceph_init() failed.  This appears to set up basic communication with the cluster (connecting to the monitors, getting the MonMap, etc.)  You will need to check the ceph logs to find out the actual error, but it's likely a permissions error, or a bad ceph.conf.

**Comment by YukiLauuu** [comment]
Have you solved this problem yet? I met a similar situation.

**Comment by ffilz** [comment]
We need more information to be able to analyze what is going on.

Can you share your configs and scan the ceph logs for errors?

**Comment by YukiLauuu** [comment]
> We need more information to be able to analyze what is going on.
> 
> Can you share your configs and scan the ceph logs for errors?

I've solved this problem. It was due to a typo in the config file.

**Comment by ffilz** [comment]
OK, closing.
