### ISSUE TITLE
Some update_share_counters_locked call sites seem broken (taking directory's handle versus file's handle)

### ISSUE THREAD

**Issue by drieber** [nfs-ganesha/nfs-ganesha#1040]
I am surprised by some of the calls to update_share_counters_locked. As far as I can tell, vfs_open2, ceph_fsal_open2 and rgw_fsal_open2 are all calling update_share_counters_locked when state != NULL, but passing the directory's fsal_obj_handle!

I would expect update_share_counters_locked to get the file's handle.

**Comment by ffilz** [comment]
I need to look at that more closely, you might be right. If so, it should be using (*newobj) (at least for vfs_open2).

**Comment by ffilz** [comment]
Ceph was actually correct, it used &hdl->handle which is the new object. FSAL_MEM and FSAL_GLUSTER were also wrong.

**Comment by ffilz** [comment]
Patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1173817?usp=search

**Comment by ffilz** [comment]
Merged in V6-dev.2, closing
