### ISSUE TITLE
Can we use softer way rather than exit nfs-ganesha when refcount error ？

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#1049]
In the second while loop in nfs_client_id_expire, if refcount greater than 1,  we [LogFatal](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/SAL/nfs4_clientid.c#L1266). And this happen in our environment, when ganesha crash by LogFatal, all the clients were affected by the bad client. So we wonder whether exist softer way to handle this, rather than crash ganesha directly ?

**Comment by ffilz** [comment]
Note the comment at the top of the loop about a refcount bug...

We need to find why you are getting an open owner with a refcount higher than 1.

Any other solution is going to leak memory and may leave a dangling pointer somewhere.
