### ISSUE TITLE
[Question] add `recovery_start()` in `struct nfs4_recovery_backend`

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1052]
In our case using nfs-ganesha abount recovery, recovery_init() starts a recovery server to serve ReleaseIP()/TakeIP() RPC request from other nodes.  However, when recovery_init() is called,  some data structures such as client_id related `ht_confirmed_client_id` is not initialized, which will be initialized in `nfs_init()`.  nfs-ganesha will crash because of `Segmentation Fault` when serving ReleaseIP()/TakeIP() RPC requests.

**Is it possible to add a new method like `recovery_start()`  into `struct nfs4_recovery_backend`?**  If so, we can call recovery_start() to start a recovery server after the related data structures have been initialized.

```
struct nfs4_recovery_backend {
	int (*recovery_init)(void);
        // int (*recovery_start)(void);
	void (*recovery_shutdown)(void);
        ...
};
```

**Comment by ffilz** [comment]
We could do that, but before doing that, can we just move when the recovery backend is initialized?

**Comment by zhitaoli-6** [comment]
Now we temporarily fix this issue by checking `nfs_init_complete` when recovery_server handles ReleaseIP/TakeIP requests. 

And new function like `recovery_start()` in `struct nfs4_recovery_backend` is preferred. I can submit a patch about this if    it is necessary :)

**Comment by ffilz** [comment]
We have several places that check for init_complete. I don't really want to add more callouts. Can the recovery server just call nfs_init_wait?

**Comment by zhitaoli-6** [comment]
It is ok to call nfs_init_wait() in recovery_server.  We prefer adding new function like `recovery_start()` in `struct nfs4_recovery_backend`, then the order will be very clear:
1. recovery_init()
2. nfs_init()
3. recovery_start(),  which will start recovery server.

**Comment by zhitaoli-6** [comment]
What is your opinion if I submit a patch with above change? @ffilz

**Comment by ffilz** [comment]
I would very much prefer not to add another synchronization call. Increasing the synchronization complexity just increases the possibility of introducing synchronization errors. Ultimately, any thread that does work that should not commence until initialization is complete should call nfs_init_wait(). Then everyone is synchronized in the same way.

**Comment by zhitaoli-6** [comment]
That's ok. Thanks for your reply.
