### ISSUE TITLE
nfs-ganesha hangs when LRU reaper closes active fd

### ISSUE THREAD

**Issue by aepotapov** [nfs-ganesha/nfs-ganesha#1054]
When the LRU reaper is turned on in nfs-ganesha v5.6, the reaper may close an active file descriptor, then hang while trying to begin new I/O on it.

The root cause is `close_fsal_fd` failing to decrement `fd_work` counter for the descriptor if `fsal_start_fd_work` returns an error (e.g. `EBUSY`).

**Comment by ffilz** [comment]
I believe we have another patch submitted to address this issue:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1174224?usp=search

You submitted patch which may be redundant:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1174673?usp=search

**Comment by aepotapov** [comment]
I confirm that this patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1174224?usp=search resolves my issue.
