### ISSUE TITLE
IO Hung post Read Delegation Recalls, upon writes

### ISSUE THREAD

**Issue by rojingeorge** [nfs-ganesha/nfs-ganesha#1055]
During parallel reads & writes from multiple clients it was seen that the involved delegation logics causes hung, as client indefinitely gets busy from FSAL layer upon performing update/rename/delete operations...
We can repro such a race condition with two directories - source and target
              1. 7 clients reading in a loop from target
              2. 1 client rsync to target
Could start seeing that rsync gets slower and eventually hangs, due the above mentioned indefinite retrials...

Post repro, in the logs could see the loop keep on going in which renames from the client was failing with DELAY and client was retrying...indefinitely

```
12/01/2024 12:19:35Z : 39984[::ffff:10.53.95.155] [io_27]  check_resp_room :NFS4 :F_DBG :Status of OP_RENAME in position 4 is ok so far, op response size = 56 total response size would be = 168 out of max 1049480/3428
12/01/2024 12:19:35Z : 39984[::ffff:10.53.95.155] [io_27] fsal_rename :FSAL :F_DBG :about to call FSAL rename
12/01/2024 12:19:35Z : 39984[::ffff:10.53.95.155] [io_27] state_deleg_conflict_impl :STATE :DEBUG :While trying to perform a write op, found a conflicting READ delegation 
...
12/01/2024 12:19:35Z : 39984[::ffff:10.53.95.155] [io_27] fsal_rename :FSAL :F_DBG :returned from FSAL rename
12/01/2024 12:19:35Z : 39984[::ffff:10.53.95.155] [io_27] fsal_rename :FSAL :F_DBG :FSAL rename failed with File busy, retry
...
12/01/2024 12:19:35Z : 39984[::ffff:10.53.95.155] [io_27] complete_op :NFS4 :DEBUG :Status of OP_RENAME in position 4 = NFS4ERR_DELAY, op response size is 4 total response size is 108

```

Upon dumping the core we could see the deleg stats going wrong...found that the object handle which claims to have been delegated with read, doesn't have any state but, it's deleg stats tells otherwise...showing fds_deleg_type = OPEN_DELEGATE_READ with one curr delegation even though there is no state

```
(gdb) p ((struct fsal_obj_handle *)0x7f4bd26d5638)->state_hdl->file
$3 = {
  obj = 0x7f4bd26d5638,
  list_of_states = {
    next = 0x7f4bd26d58f0,
    prev = 0x7f4bd26d58f0
  },
  layoutrecall_list = {
    next = 0x7f4bd26d5900,
    prev = 0x7f4bd26d5900
  },
  lock_list = {
    next = 0x7f4bd26d5910,
    prev = 0x7f4bd26d5910
  },
  nlm_share_list = {
    next = 0x7f4bd26d5920,
    prev = 0x7f4bd26d5920
  },
  write_delegated = false,
  write_deleg_client = 0x0,
  fdeleg_stats = {
    fds_curr_delegations = 1,
    fds_deleg_type = OPEN_DELEGATE_READ,
    fds_delegation_count = 429,
    fds_recall_count = 429,
    fds_avg_hold = 0,
    fds_last_delegation = 1705061529,
    fds_last_recall = 1705061530,
    fds_num_opens = 429,
    fds_first_open = 1705060487,
    fds_num_write_opens = 0
  },
```

**Comment by ffilz** [comment]
Patch https://github.com/ffilz/nfs-ganesha/commit/a9eae958b553bfc3805b799616314716f780764b
