### ISSUE TITLE
Fails to grant Read Delegation after writing and closing the file

### ISSUE THREAD

**Issue by rojingeorge** [nfs-ganesha/nfs-ganesha#1056]
After writing and closing the file, when tried to read the file we fail to grant the delegation to the client

```
09/01/2024 05:43:52Z : [::ffff:10.53.93.144] [io_2] _state_add_impl :STATE :F_DBG :Add State: 0x7fb16420a540: OTHER=0x050000002200000001000000 {{CLIENTID Epoch=0x00000022 Counter=0x00000005} StateIdCounter=0x00000001}
09/01/2024 05:43:52Z : [::ffff:10.53.93.144] [io_2] should_we_grant_deleg :STATE :DEBUG :Checking if we should grant delegation.
09/01/2024 05:43:52Z : [::ffff:10.53.93.144] [io_2] nfs4_op_open :STATE :F_DBG :NFS4 OPEN returning NFS4_OK
09/01/2024 05:43:52Z : [::ffff:10.53.93.144] [io_2] update_stateid :STATE :DEBUG :Update OPEN stateid to OTHER=0x050000002200000001000000 {{CLIENTID Epoch=0x00000022 Counter=0x00000005} StateIdCounter=0x00000001} seqid=1 for response 
```
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/SAL/state_deleg.c#L390

On checking further the code changes, saw that this was happening because of the counter going negative
```
(gdb) p args->share_access
$1 = 1
(gdb) p file_stats->fds_num_write_opens
$2 = 4294967295 
``` 

Reason being that both _state_del_locked and nfs4_op_close, were decrementing the counter in CLOSE op path, there by leading to this issue

**Comment by ffilz** [comment]
Patch submitted: https://github.com/ffilz/nfs-ganesha/commit/312a2a8048a5a3cd019d348559b71f5c31b74a8d
