### ISSUE TITLE
Question： Which .so file should I replace to make it effect If I changed FSAL_CEPH/handle.c ?

### ISSUE THREAD

**Issue by bear-Zhao178** [nfs-ganesha/nfs-ganesha#1059]
Our ganesha version is v3.2.
Recently, we recgnized a unlock the problem that did not lunlock the rdlock if find_cephfd failed in ceph_fsal_lock_op2 .
We fixed that, and replaced the libganesha_nfsd.so, but it seems didn't work.
Which one of .so file should I replace to make sure the code work ?

**Comment by bear-Zhao178** [comment]
The problem like this:
Many thread(named A) is waitting for obj->state_hdl->state_lock in state_deleg_confict , and the nlm4_Granted_Res(named B) is waitting for my_fd->fdlock with holding the obj->state_hdl->state_lock,  there is one reader on fdlock. The thread(name C) which held the fdlock had already exit.
Thread A:
(gdb) t 184
[Switching to thread 184 (Thread 0x7f86adde5700 (LWP 2461297))]
#0  0x00007f86c079439e in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f86c079439e in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00007f86c2906107 in state_deleg_conflict (obj=0x7f86994b9438, write=false) at /xys44060/NFS-Ganesha-3.2/src/SAL/state_deleg.c:601
#2  0x00007f86c29ed0c1 in nlm4_Lock (args=0x7f85f789b010, req=0x7f85f789a800, res=0x7f85f782b080) at /xys44060/NFS-Ganesha-3.2/src/Protocols/NLM/nlm_Lock.c:132
#3  0x00007f86c2891245 in nfs_rpc_process_request (reqdata=0x7f85f789a800) at /xys44060/NFS-Ganesha-3.2/src/MainNFSD/nfs_worker_thread.c:1563
#4  0x00007f86c289178e in nfs_rpc_valid_NLM (req=0x7f85f789a800) at /xys44060/NFS-Ganesha-3.2/src/MainNFSD/nfs_worker_thread.c:1748
#5  0x00007f86c2625bae in svc_vc_decode (req=0x7f85f789a800) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_vc.c:935
#6  0x00007f86c26217ad in svc_request (xprt=0x7f85f781a100, xdrs=0x7f85f788f180) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_rqst.c:1325
#7  0x00007f86c2625ab7 in svc_vc_recv (xprt=0x7f85f781a100, is_xprt_ref=0x7f86adde3657) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_vc.c:908
#8  0x00007f86c2621650 in svc_rqst_xprt_task_recv (wpe=0x7f85f781a360) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_rqst.c:1289
#9  0x00007f86c26222c4 in svc_rqst_epoll_loop (wpe=0x7f86b1f6f318) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_rqst.c:1690
#10 0x00007f86c262ec48 in work_pool_thread (arg=0x7f85f8c0e020) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/work_pool.c:184
#11 0x00007f86c0790ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f86b6e1fb8d in clone () from /lib64/libc.so.6
(gdb) f 1
#1  0x00007f86c2906107 in state_deleg_conflict (obj=0x7f86994b9438, write=false) at /xys44060/NFS-Ganesha-3.2/src/SAL/state_deleg.c:601
601     /xys44060/NFS-Ganesha-3.2/src/SAL/state_deleg.c: No such file or directory.
(gdb) p obj->state_hdl->state_lock
$1 = {__data = {__lock = 0, __nr_readers = 0, __readers_wakeup = 0, __writer_wakeup = 7458, __nr_readers_queued = 0, __nr_writers_queued = 258, **__writer = 2461319**, __shared = 0, __pad1 = 0,
    __pad2 = 0, __flags = 0}, __size = '\000' <repeats 12 times>, "\"\035\000\000\000\000\000\000\002\001\000\000\207\216%", '\000' <repeats 28 times>, __align = 0}
(gdb) t f 2461319
Thread 196 has target id 'Thread 0x7f86aa1fc700 (LWP 2461319)'

Thread B:
(gdb) t 196
[Switching to thread 196 (Thread 0x7f86aa1fc700 (LWP 2461319))]
#0  0x00007f86c079439e in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f86c079439e in pthread_rwlock_wrlock () from /lib64/libpthread.so.0
#1  0x00007f86addf384b in ceph_fsal_close2 (obj_hdl=0x7f8699461300, state=0x7f86560f1140) at /tmp/NFS-Ganesha-3.2/src/FSAL/FSAL_CEPH/handle.c:2658
#2  0x00007f86c29c83a1 in mdcache_close2 (obj_hdl=0x7f86994b9438, state=0x7f86560f1140) at /xys44060/NFS-Ganesha-3.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:871
#3  0x00007f86c2928947 in dec_nlm_state_ref (state=0x7f86560f1140) at /xys44060/NFS-Ganesha-3.2/src/SAL/nlm_state.c:319
#4  0x00007f86c28f3d42 in dec_state_t_ref (state=0x7f86560f1140) at /xys44060/NFS-Ganesha-3.2/src/include/sal_functions.h:410
#5  0x00007f86c28f60cc in remove_from_locklist (lock_entry=0x7f869b8ccde0) at /xys44060/NFS-Ganesha-3.2/src/SAL/state_lock.c:722
#6  0x00007f86c28f8537 in try_to_grant_lock (lock_entry=0x7f869b8ccde0) at /xys44060/NFS-Ganesha-3.2/src/SAL/state_lock.c:1769
#7  0x00007f86c28f88d4 in grant_blocked_locks (ostate=0x7f86994b9798) at /xys44060/NFS-Ganesha-3.2/src/SAL/state_lock.c:1830
#8  0x00007f86c28f804b in state_complete_grant (cookie_entry=0x7f863c035140) at /xys44060/NFS-Ganesha-3.2/src/SAL/state_lock.c:1688
#9  0x00007f86c29ecb81 in nlm4_Granted_Res (args=0x7f86a8cba010, req=0x7f86a8cb9800, res=0x7f86a8cb4d80) at /xys44060/NFS-Ganesha-3.2/src/Protocols/NLM/nlm_Granted_Res.c:101
#10 0x00007f86c2891245 in nfs_rpc_process_request (reqdata=0x7f86a8cb9800) at /xys44060/NFS-Ganesha-3.2/src/MainNFSD/nfs_worker_thread.c:1563
#11 0x00007f86c289178e in nfs_rpc_valid_NLM (req=0x7f86a8cb9800) at /xys44060/NFS-Ganesha-3.2/src/MainNFSD/nfs_worker_thread.c:1748
#12 0x00007f86c2625bae in svc_vc_decode (req=0x7f86a8cb9800) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_vc.c:935
#13 0x00007f86c26217ad in svc_request (xprt=0x7f85f8860100, xdrs=0x7f866782d300) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_rqst.c:1325
#14 0x00007f86c2625ab7 in svc_vc_recv (xprt=0x7f85f8860100, is_xprt_ref=0x7f86aa1fa6c7) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_vc.c:908
#15 0x00007f86c2621650 in svc_rqst_xprt_task_recv (wpe=0x7f85f8860360) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/svc_rqst.c:1289
#16 0x00007f86c262ec48 in work_pool_thread (arg=0x7f86ac41b020) at /xys44060/NFS-Ganesha-3.2/src/libntirpc/src/work_pool.c:184
#17 0x00007f86c0790ea5 in start_thread () from /lib64/libpthread.so.0
#18 0x00007f86b6e1fb8d in clone () from /lib64/libc.so.6
(gdb) f 1
#1  0x00007f86addf384b in ceph_fsal_close2 (obj_hdl=0x7f8699461300, state=0x7f86560f1140) at /tmp/NFS-Ganesha-3.2/src/FSAL/FSAL_CEPH/handle.c:2658
2658    /tmp/NFS-Ganesha-3.2/src/FSAL/FSAL_CEPH/handle.c: No such file or directory.
(gdb) p my_fd->fdlock
$2 = {__data = {__lock = 0, **__nr_readers = 1**, __readers_wakeup = 0, __writer_wakeup = 0, __nr_readers_queued = 0, __nr_writers_queued = 1, __writer = 0, __shared = 0, __pad1 = 0, __pad2 = 0,
    __flags = 0}, __size = "\000\000\000\000\001", '\000' <repeats 15 times>, "\001", '\000' <repeats 34 times>, __align = 4294967296}

the log of abnormal return：
17/01/2024 16:00:34 : epoch 65a787d2 : node20 : ganesha.nfsd-2460042[svc_11] fsal_find_fd :FSAL :CRIT :Open for locking failed for access Read/Write
17/01/2024 16:00:34 : epoch 65a787d2 : node20 : ganesha.nfsd-2460042[svc_11] ceph_fsal_lock_op2 :FSAL :CRIT :Unable to find fd for lock operation
17/01/2024 16:00:34 : epoch 65a787d2 : node20 : ganesha.nfsd-2460042[svc_11] state_add_grant_cookie :STATE :MAJ :Unable to lock FSAL for GRANTING       lock, error=STATE_LOCK_CONFLICT

**Comment by dang** [comment]
If you rebuild after code changes, you should replace all the .so files.  If, for some reason, you must only replace one, then the FSALs live in their own .so files, and are loaded when you configure the FSAL.   So FSAL_CEPH lives in libfsalceph.so

**Comment by ffilz** [comment]
Also, you're on a pretty old version of Ganesha.

**Comment by bear-Zhao178** [comment]
OK, thanks a lot for your answer. Please close this issue.
