### ISSUE TITLE
NFSv4 pseudo root mount does not show new exports until something is removed

### ISSUE THREAD

**Issue by jswoodward** [nfs-ganesha/nfs-ganesha#1060]
I'm testing nfs-ganesha with dynamic exports by starting with a configuration like:

```sh
FSAL_LIST { Name = VFS; }
LOG { COMPONENTS { EXPORT=FULL_DEBUG; FSAL=FULL_DEBUG; } }
NFS_CORE_PARAM { Protocols = 4; Enable_RQUOTA = false; Mount_Path_Pseudo = true; fsid_device = true; }
NFSV4 { RecoveryBackend = "fs_ng"; RecoveryRoot = /storage/ganesha/; }
EXPORT_DEFAULTS { Access_Type = RW; Squash = no_root_squash; }
VFS { link_support = false; symlink_support = true; }
```

Then adding exports on demand later with a SIGHUP. 

```
EXPORT { Export_id = 1; Path = /storage/ganesha/exports/e1; Pseudo = /e1; FSAL { Name = VFS; } }                                                                                                                                                                                              
```

I noticed that a client mounting the initial empty PSEUDO root will not see a new export unless I add another one and then remove it.  I'm not 100% sure but I see `nfs4_readdir_callback` calls kickoff only after removing that second export.

Is this a bug or am I missing a configuration hint beyond just appending a new export and SIGHUP'ing?

Attaching the debug logging annotated with `-------------- <>` lines showing configuration changes and client perspective.
[ganeshadebug.log](https://github.com/nfs-ganesha/nfs-ganesha/files/14013944/ganeshadebug.log)

**Comment by jswoodward** [comment]
I should note that the exports /are/ there as in I can get to them if I know the subdir path.

**Comment by jswoodward** [comment]
Appears client side caching is at play here... Forcing a `/proc/sys/vm/drop_caches` sorts it out.

**Comment by ffilz** [comment]
Ah, OK. I was worried FSAL_PSEUDO wasn't updating mtime and ctime on directories...

Too bad there isn't a way to hint to the client that a handle belongs to a pseudofs and it should consider handling caching differently.

**Comment by ffilz** [comment]
OH, crap, actually it doesn't...

**Comment by ffilz** [comment]
FSAL_PSEUDO needs to update mtime, ctime, and change when creating directories (it does for removing).

**Comment by jswoodward** [comment]
```
diff --git a/src/FSAL/FSAL_PSEUDO/handle.c b/src/FSAL/FSAL_PSEUDO/handle.c
index 54f2ddad6..2dccf2db1 100644
--- a/src/FSAL/FSAL_PSEUDO/handle.c
+++ b/src/FSAL/FSAL_PSEUDO/handle.c
@@ -439,6 +439,11 @@ static fsal_status_t makedir(struct fsal_obj_handle *dir_hdl,
        if (attrs_out != NULL)
                fsal_copy_attrs(attrs_out, &hdl->attributes, false);
 
+       now(&myself->attributes.mtime);
+       myself->attributes.ctime = myself->attributes.mtime;
+       myself->attributes.change = timespec_to_nsecs(
+                                       &myself->attributes.mtime);
+
        return fsalstat(ERR_FSAL_NO_ERROR, 0);
 }
 
```

Ah thanks for the hint. This seems to fix it for me.

**Comment by ffilz** [comment]
Yep, that looks like the fix. Could you submit a patch to gerrithub?

**Comment by jswoodward** [comment]
Sure thing, Frank. Pushed to https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1175826

**Comment by ffilz** [comment]
Thanks. I have a review comment.

**Comment by jswoodward** [comment]
Thanks, updated.
