### ISSUE TITLE
anyone ever compiled and ran on Alpine linux?

### ISSUE THREAD

**Issue by ehudkaldor** [nfs-ganesha/nfs-ganesha#107]
or any other musl-based system?
i'm trying to create a Docker image with a userspace NFS server, but having a hard time compiling on Alpine Linux, which is a tiny image for containers, based on musl instead of libc.

any help is appreciated.

**Comment by ffilz** [comment]
Dan G. has been working on Ganesha/Docker. I don't know what he has done to make it work, there may be patches in next, and I assume he has some config options and such.

**Comment by dang** [comment]
On 08/29/2016 12:34 AM, Frank Filz wrote:
> Dan G. has been working on Ganesha/Docker. I don't know what he has done
> to make it work, there may be patches in next, and I assume he has some
> config options and such.
>

I'm working on Fedora, RHEL, and Ubuntu, so all glibc based systems.

Daniel

**Comment by ehudkaldor** [comment]
@dang : any plan to get to musl? 
i am trying to set up a NFS server with Docker, but i do not want to use the kernel NFS, as it requires the container be privileged. and Ganesha is the only userspace NFS server still maintained, it seems.
i cannot find any base image as small as Alpine (it is 10x smaller than Ubuntu), so i would much rather keep using it than switch to a larger image. this is going to be running on Raspberry PI.

**Comment by dang** [comment]
I don't have any current plans, I'm sorry.  My day job pays for this (I work for Red Hat), but they pay me to work on primarily Fedora and RHEL.  I'm somewhat interested in small containers, however, so I'll try and take a look at this when I get a chance.

**Comment by gautaz** [comment]
I'm also trying to build for [Alpine Linux](https://alpinelinux.org/) by following the [BuildingV2](https://github.com/nfs-ganesha/nfs-ganesha/wiki/BuildingV2) guide.

For now `cmake` fails on:
```
/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:3:24: fatal error: libzfswrap.h: No such file or directory
```

So I'm trying to build and install the `libzfswrap` part in `contrib` which seems to provide `libzfswrap.h`.

I'm currently stuck on this later build which fails on:

```
In file included from /usr/include/sys/resource.h:9:0,
                 from /usr/include/sys/param.h:31,
                 from ../../lib/libsolcompat/include/sys/param.h:30,
                 from ../../lib/libsolcompat/include/sys/sysmacros.h:33,
                 from /usr/include/sys/types.h:72,
                 from ../../lib/libsolcompat/include/sys/types.h:32,
                 from avl.c:90:
../../lib/libsolcompat/include/sys/time.h:38:9: error: unknown type name 'longlong_t'
 typedef longlong_t hrtime_t;
         ^
In file included from avl.c:90:0:
../../lib/libsolcompat/include/sys/types.h:36:24: fatal error: bits/types.h: No such file or directory
```

Which seems to be glibc specific headers and types.

Is there a way to build `nfs-ganesha` without the support for `libzfswrap`?

**Comment by ffilz** [comment]
If you don't need FSAL_ZFS, you can put -DUSE_FSAL_ZFS=OFF on your cmake command line.

**Comment by gautaz** [comment]
Thanks @ffilz, I have made some progress, now I'm hitting:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBNSL
    linked by target "ntirpc" in directory /ganesha/src/src/libntirpc/src
```

Which is related to NIS if I'm right and I cannot find anything related to that in [Alpine packages](https://pkgs.alpinelinux.org).

This seems needed by ntirpc, is there a fallback or a workaround?

**Comment by dang** [comment]
No, libNSL is part of glibc.  There is no fallback.

**Comment by gautaz** [comment]
Thanks @dang for pointing this.
I was hoping to still get something from [Linux NIS/NIS+](http://www.linux-nis.org/) but I'm a bit short of time now.
Well, let say this will be for the record ;-).

**Comment by gautaz** [comment]
For the record, the current `Dockerfile` which fails on `LIBNSL`:

```
FROM alpine:3.4
RUN \
apk add --no-cache git build-base cmake bison flex krb5-dev libcap-dev samba-dev xfsprogs-dev && \
mkdir /ganesha && \
git clone --recursive git://github.com/nfs-ganesha/nfs-ganesha.git /ganesha/git && \
cd /ganesha/git && \
git checkout V2.4.1 && \
git submodule update --init && \
mkdir /ganesha/build && \
cd /ganesha/build && \
cmake -DUSE_FSAL_ZFS=OFF -DUSE_FSAL_CEPHFS=OFF /ganesha/git/src/
```

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
