### ISSUE TITLE
Chunked readdir holding on to directory->content lock for too long - blocking any other ops on a huge directory 

### ISSUE THREAD

**Issue by deepakaru** [nfs-ganesha/nfs-ganesha#1074]
Some background info -
(1) libnfs by default seems to use a higher value for readdirplus.maxcount - 1 MB when compared to linux kernel clients - the ones we have experimented with set it to 16KB. Ganeshas default value for this seems to be 64 MB.
(2) We have a directory with 600k + files.

when this libnfs client tries to do a readdirplus on this huge directory - the corresponding thread seems to acquire directory->content_lock and doesn't release it for > 3 minutes - this means no other clients ops can progress during the time.

The reason we are not releasing the lock is because we never hit tracker->mem_avail limit in nfs3_readdir_callback which is 1 MB and we keep trying to fill more chunks.

We have two ideas on how to resolve this,
(1) Reduce the server side max to 16 KB which is what the linux clients use or something lower than 1 MB.
(2) Do uncached readdir for large directories. Here large might be anything greater than 600k files. @ffilz i remember based on our past discussions you are not a fan of doing uncached readdir since some FSALs don't fare well with that. But 600k is a lot of files and our default values for Entries_hwmark and chunks_hwark are 100k and 1000 respectively. So 600k wouldn't even fit in the cache and FSALs might end up going to the file system each time anyway and it might even be benificial to performance to do a uncached readdir in those cases. Maybe we factor in Entries_hwmark and chunks_hwmark when deciding when to do a uncached readdir

@dang , @ffilz thoughts on which approach would be preferrable. i can start working on a patch based on your feedback - can also provide more data/logs if needed

**Comment by ffilz** [comment]
I think reducing the Readdir_Max_Count would be the better option. The chunking was specifically to deal with large directories, but if the client is requesting more than is reasonable in one go, that's a problem.

You could try configuring it with a smaller value to check it out.

**Comment by pradeepthomas** [comment]
Hi Frank, What we have seen in customer environments is that very large directories typically don't fit into cache causing a miss. This is very costly when other operations (like gettattr, lookup) are going on in parallel in the same directory. In this scenario, cached readdir performs poorly compared to uncached readdir. In contrast, with a lot of small directories there is a huge benefit from readdir cache - with workloads like build/make where NFS mount is used as toolchain and artifact destination, and hundreds of users doing builds in parallel. Hence the thought of disabling cache selectively, or perhaps give an option for FSAL to decide?

**Comment by deepakaru** [comment]
Pending review here https://gerrithub.io/c/ffilz/nfs-ganesha/+/1176782

**Comment by ffilz** [comment]
Closing as done with 6.0 release.
