### ISSUE TITLE
nfs4_State_Get_Pointer hashtable lock contention

### ISSUE THREAD

**Issue by JonKohler** [nfs-ganesha/nfs-ganesha#1075]
nfs4_State_Get_Pointer suffers from writer lock contention on the hashtable_getlatch() calls, as it uses may_write == true to procure the latch and subsequently increment the state_t refcount. This lock contention appears to get worse with the glibc libpthread implementation in el8 and higher; however, this contention points out an opportunity for optimization.

nfs4_State_Get_Pointer is not mutating set or delete into the hashtable data structures but rather using that as a means to do an atomic increment on the state_t reference. state_t reference has its own thread safety design, since increments and decrements are atomic.

I've got a patch in hand, I will submit for review

**Comment by JonKohler** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1176505 use may_write == false in nfs4_State_Get_Pointer

**Comment by ffilz** [comment]
Thanks

**Comment by JonKohler** [comment]
@ffilz - now that these are merged into next branch, should I close this? or is there a process to close this as completed? I didn't want to overstep if there was some formal way (such as waiting for it to come to a release branch, etc)?

ref https://github.com/nfs-ganesha/nfs-ganesha/commit/be2ab20ce2d4a381763208634801d1c2d0994c29

**Comment by ffilz** [comment]
Once the reporter is satisfied, it's fine with me to close it. Generally I would assume the reporter verified it after a merge but I'm not much of a stickler. I eventually close all the ones that have been merged,

**Comment by JonKohler** [comment]
Thanks @ffilz - we've already backported this to our source and tested it works as advertised. Fixed in https://github.com/nfs-ganesha/nfs-ganesha/commit/be2ab20ce2d4a381763208634801d1c2d0994c29

Cheers,
Jon
