### ISSUE TITLE
LOG_EXPORT critical path overhead

### ISSUE THREAD

**Issue by JonKohler** [nfs-ganesha/nfs-ganesha#1076]
LOG_EXPORT macro was added by 80fa5e56e79 ("Add some EXPORT debug") which adds calls to log_an_export in the critical path in release binaries. This shows up as expensive when flamegraphing process under load.

I've got a patch in hand, I'll submit for review

<img width="1190" alt="Screenshot 2024-02-06 at 11 00 14 AM" src="https://github.com/nfs-ganesha/nfs-ganesha/assets/21041006/3fa2519e-b152-4dd6-b10a-73729cb5fbfd">

**Comment by JonKohler** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1176508 Fix log_an_export critical path overhead

**Comment by ffilz** [comment]
Thanks

**Comment by rojingeorge** [comment]
@ffilz - Patch has been updated, similar to that done in other logger macros...please check and approve :-)
This avoids the critical path logging overheads and also allows logs to be turned on, when required to debug...

cc: @JonKohler @pradeepthomas

**Comment by JonKohler** [comment]
Fixed on https://github.com/nfs-ganesha/nfs-ganesha/commit/b1b96787c461030bf94842ea434ce7ce83d397c1
