### ISSUE TITLE
where is the config file description

### ISSUE THREAD

**Issue by ancienter** [nfs-ganesha/nfs-ganesha#1079]
where is the config file description?
how to config all glusterfs hostname in FSAL? 
i need ha
but it say "ganesha.nfsd-4140[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:99): Hostname can have only one option.  First one is (192.168.1.51)"
my config is:
  FSAL {
    Name = GLUSTER;
    Hostname = 192.168.1.51,192.168.1.52,192.168.1.53;
    Volume = volumes;
  }

**Comment by dang** [comment]
Config is documented in man pages in the source.  The FSAL_GLUSTER docs are here:
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-gluster-config.rst
It looks like you can't put multiple hostnames.

**Comment by ancienter** [comment]
That doesn't solve my problem，My question is whether it will affect the normal use of my NFS if this address crashes when only one hostname can be specified

**Comment by dang** [comment]
I'm not sure, it's been a long time since I used Gluster.  But my memory is that the configured address is just a point of contact, and that after you're connected you get the list of all the addresses.  So if that server goes down, you won't be able to make a new connection, but an existing connection will continue.  I may be wrong about that, though.

**Comment by ancienter** [comment]
That's right. But let's imagine a scenario like this ，a Cluster of Glusterfs with 3 node，hosta、hostb、hostc，then NFS-Ganesha point to hosta，now hosta crashes ，then you reboot NFS-Ganesha will never working ，because hosta is crashed.
This means I have to give a vip to the glusterfs cluster，It might be a good idea to give NFS-Ganesha a list of addresses to try to connect to.

**Comment by kalebskeithley** [comment]
glusterfs fuse mounts have the ability to set an optional backup-volfile-server if the primary can't be reached. But libgfapi has no equivalent, and to be frank, there is no new development going on in glusterfs, so it's unlikely to be added.

**Comment by ffilz** [comment]
I've tagged this wontfix because realistically I see no resources to address this issue, If someone would like to take it on, I'd be happy to keep it open, otherwise, we should close it.
