### ISSUE TITLE
nfs-ganesha worker threads are stuck in the waiting work_cond in the wait_to_start_io()

### ISSUE THREAD

**Issue by Haroldll** [nfs-ganesha/nfs-ganesha#1088]
My version of nfs-ganesha is 5.6, use NFS v3.

I use vdbench to read and write files for testing, a network abnormality may have occurred during the test, but it recovered later.

However, at some point, the NFS client's mount directory suddenly got stuck and it was unable to cd to the mount directory.

At this point, the server seems to be unable to handle the client's request. All ganesha's working threads are stuck, waiting for work_cond. The stacks of Thread 92 to 287 are:
```
Thread 287 (Thread 0x7fa6dce64700 (LWP 1332884)):
#0  0x00007fa725e0e61c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fa7291b066e in wait_to_start_io (obj_hdl=0x73ec0180, fsal_fd=0x73ec0210, openflags=2, may_open=true, may_reopen=true) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/FSAL/commonlib.c:2228
#2  0x00007fa7291b15a9 in fsal_start_global_io (out_fd=0x7fa6dce62c98, obj_hdl=0x73ec0180, my_fd=0x73ec0210, tmp_fd=0x7fa6dce62bf0, openflags=2, bypass=true, share=0x73ec02dc) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/FSAL/commonlib.c:2456
#3  0x00007fa7291b1d04 in fsal_start_io (out_fd=0x7fa6dce62c98, obj_hdl=0x73ec0180, obj_fd=0x73ec0210, tmp_fd=0x7fa6dce62bf0, state=0x0, openflags=2, open_for_locks=false, reusing_open_state_fd=0x0, bypass=true, share=0x73ec02dc) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/FSAL/commonlib.c:2736
#4  0x00007fa72944dde7 in ceph_fsal_write2 (obj_hdl=0x73ec0180, bypass=true, done_cb=0x7fa7292ff52b <mdc_write_cb>, write_arg=0x988a3b40, caller_arg=0x96da2ee0) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/FSAL/FSAL_CEPH/handle.c:2131
#5  0x00007fa7292ff6a4 in mdcache_write2 (obj_hdl=0x74948038, bypass=true, done_cb=0x7fa7292e7118 <nfs3_write_cb>, write_arg=0x988a3b40, caller_arg=0x988a3b20) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:710
#6  0x00007fa7292e7966 in nfs3_write (arg=0x67fb4830, req=0x67fb4000, res=0xe3e2a500) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/Protocols/NFS/nfs3_write.c:379
#7  0x00007fa7291e7356 in nfs_rpc_process_request (reqdata=0x67fb4000, retry=false) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/MainNFSD/nfs_worker_thread.c:1517
#8  0x00007fa7291e7970 in nfs_rpc_valid_NFS (req=0x67fb4000) at /usr/src/debug/nfs-ganesha-5.6-0.1.x86_64/MainNFSD/nfs_worker_thread.c:1742
#9  0x00007fa7295eb5ab in svc_vc_decode () from /lib64/libntirpc.so.5.0
#10 0x00007fa7295e6ac9 in svc_request () from /lib64/libntirpc.so.5.0
#11 0x00007fa7295eb4b0 in svc_vc_recv () from /lib64/libntirpc.so.5.0
#12 0x00007fa7295e6a49 in svc_rqst_xprt_task_recv () from /lib64/libntirpc.so.5.0
#13 0x00007fa7295e75dd in svc_rqst_epoll_loop () from /lib64/libntirpc.so.5.0
#14 0x00007fa7295f2aa4 in work_pool_thread () from /lib64/libntirpc.so.5.0
#15 0x00007fa725e082ff in start_thread () from /lib64/libpthread.so.0
#16 0x00007fa725239dd3 in clone () from /lib64/libc.so.6
```
Of the 200 maximum working threads set, 196 are stuck, and the remaining 4 seem to be no longer providing services.

Some errors can be seen in the log：
```
ganesha.nfsd-1057089[svc_9] rpc :TIRPC :EVENT :svc_ioq_flushv: 0x80bcc00 fd 132 msg_iov 0x7fa7269fdd70 sendmsg remaining 32896 result -1 error Connection reset by peer (104)
ganesha.nfsd-1057089[svc_9] rpc :TIRPC :EVENT :svc_ioq_flushv: 0x92a1600 fd 231 msg_iov 0x7fa7269fddf0 sendmsg remaining 136 result -1 error Connection reset by peer (104)
ganesha.nfsd-1057089[svc_9] rpc :TIRPC :EVENT :svc_ioq_flushv: 0x80bb080 fd 232 msg_iov 0x7fa7269fdd70 sendmsg remaining 32896 result -1 error Connection reset by peer (104)
ganesha.nfsd-1057089[svc_9] rpc :TIRPC :EVENT :svc_ioq_flushv: 0x92a2680 fd 233 msg_iov 0x7fa7269fddf0 sendmsg remaining 136 result -1 error Connection reset by peer (104)
ganesha.nfsd-1057089[svc_9] rpc :TIRPC :EVENT :svc_ioq_flushv: 0x80bbb80 fd 234 msg_iov 0x7fa7269fdd70 sendmsg remaining 32896 result -1 error Connection reset by peer (104)
```

From the code:
```
		while (atomic_fetch_int32_t(&fsal_fd->fd_work) != 0) {
			LogFullDebug(COMPONENT_FSAL,
				     "%p wait for fd work - io_work = %"PRIi32
				     " fd_work = %"PRIi32,
				     fsal_fd,
				     atomic_fetch_int32_t(&fsal_fd->io_work),
				     atomic_fetch_int32_t(&fsal_fd->fd_work));

			PTHREAD_COND_wait(&fsal_fd->work_cond,
					  &fsal_fd->work_mutex);
		}
```
Analyze the code, such as fsal_fd->fd_work count is wrong, causing every thread to wait.
So is it possible that there are some abnormal scenarios where this count is not operated correctly?
In the close_fsal_fd function, if fsal_start_fd_work returns an error, the count does not seem to be reduced by one.
```
fsal_status_t close_fsal_fd(struct fsal_obj_handle *obj_hdl,
			    struct fsal_fd *fsal_fd,
			    bool is_reclaiming)
{
	fsal_status_t status;
	bool is_globalfd = fsal_fd->fd_type == FSAL_FD_GLOBAL;

	/* Assure that is_reclaiming is only set when it's a global fd */
	assert(is_reclaiming ? is_globalfd : true);

	/* Indicate we want to do fd work */
	status = fsal_start_fd_work(fsal_fd, is_reclaiming);

	if (FSAL_IS_ERROR(status)) {
		LogFullDebug(COMPONENT_FSAL,
			 "fsal_start_fd_work returned %s",
			 fsal_err_txt(status));
		return status;
	}
```
If return here, it seems that fsal_complete_fd_work will not be called.

I don't know what causes these threads to be stuck for a long time and cannot be recovered. 
Have you ever encountered this kind of problem or have any ideas? Thanks！

**Comment by rojingeorge** [comment]
@Haroldll Yeah, we have faced this...Please cherry pick this patch...
https://gerrithub.io/c/ffilz/nfs-ganesha/+/1174224

**Comment by Haroldll** [comment]
> @Haroldll Yeah, we have faced this...Please cherry pick this patch... https://gerrithub.io/c/ffilz/nfs-ganesha/+/1174224

Thank you. It looks great. I'll try cherry pick this patch and test it again.

**Comment by Haroldll** [comment]
> @Haroldll是的，我们遇到了这个...请修复这些补丁... [https://gerrithub.io/c/filz/nfs-ganesha/+/1174224](https://gerrithub.io/c/ffilz/nfs-ganesha/+/1174224)

After merging for a period of time, this problem still occurred, but the probability became smaller. I think there are other reasons.

see:
Thread 82 (Thread 0x7f153b5ff700 (LWP 118)):
#0  0x00007f153840e61c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f153bc8b5ea in wait_to_start_io () from /lib64/libganesha_nfsd.so.5.6
#2  0x00007f153bc8c525 in fsal_start_global_io () from /lib64/libganesha_nfsd.so.5.6
#3  0x00007f153bc8cc80 in fsal_start_io () from /lib64/libganesha_nfsd.so.5.6
#4  0x00007f153befade7 in ceph_fsal_write2 () from /usr/lib64/ganesha/libfsalclove.so
#5  0x00007f153bdd5025 in mdcache_write2 () from /lib64/libganesha_nfsd.so.5.6
#6  0x00007f153bdbd125 in nfs3_write () from /lib64/libganesha_nfsd.so.5.6
#7  0x00007f153bcc21b3 in nfs_rpc_process_request () from /lib64/libganesha_nfsd.so.5.6
#8  0x00007f153bcc27cd in nfs_rpc_valid_NFS () from /lib64/libganesha_nfsd.so.5.6
#9  0x00007f153c09d466 in svc_vc_decode () from /lib64/libntirpc.so.5.0
#10 0x00007f153c0988e7 in svc_request () from /lib64/libntirpc.so.5.0
#11 0x00007f153c09d36b in svc_vc_recv () from /lib64/libntirpc.so.5.0
#12 0x00007f153c098867 in svc_rqst_xprt_task_recv () from /lib64/libntirpc.so.5.0
#13 0x00007f153c099422 in svc_rqst_epoll_loop () from /lib64/libntirpc.so.5.0
#14 0x00007f153c0a5f01 in work_pool_thread () from /lib64/libntirpc.so.5.0
#15 0x00007f15384082ff in start_thread () from /lib64/libpthread.so.0
#16 0x00007f1537439dd3 in clone () from /lib64/libc.so.6

**Comment by ffilz** [comment]
Yes, see https://github.com/nfs-ganesha/nfs-ganesha/issues/1102

**Comment by ffilz** [comment]
Patch posted in #1102 btw...
