### ISSUE TITLE
fail to building code

### ISSUE THREAD

**Issue by qhb19870226** [nfs-ganesha/nfs-ganesha#1090]
[root@localhost build]# make
Scanning dependencies of target log
[  1%] Building C object log/CMakeFiles/log.dir/display.c.o
[  1%] Building C object log/CMakeFiles/log.dir/log_functions.c.o
In file included from /home/leon/leon_nfs_3.5/nfs-ganesha/src/log/log_functions.c:47:0:
/home/leon/leon_nfs_3.5/nfs-ganesha/src/include/gsh_rpc.h:17:28: fatal error: rpc/xdr_inline.h: No such file or directory
 #include <rpc/xdr_inline.h>
                            ^
compilation terminated.
make[2]: *** [log/CMakeFiles/log.dir/log_functions.c.o] Error 1
make[1]: *** [log/CMakeFiles/log.dir/all] Error 2
make: *** [all] Error 2

**Comment by yogendra-t** [comment]
looks like you have not cloned NFS-Ganesha submodule ntirpc. You can run below command :

git submodule update --init --recursive

**Comment by qhb19870226** [comment]
> looks like you have not cloned NFS-Ganesha submodule ntirpc. You can run below command :
> 
> git submodule update --init --recursive

it works！thanks
