### ISSUE TITLE
Remote I/O error 5.7

### ISSUE THREAD

**Issue by madmax01** [nfs-ganesha/nfs-ganesha#1091]
Hi Team,

when i try to do an "ls -l" i get 

ls: reading directory '.': Remote I/O error

but i can write and delete
-----------------------------

EXPORT
{
        #Start Delay
        Start = 10;

        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 1;

        # Exported path (mandatory)
        Path = "/sharedganesha_system";

        Pseudo = "/sharedganesha_system";

        Protocols = 3,4,9P;

        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;

        Disable_ACL = TRUE;

        # Allow root access
        Squash = No_Root_Squash;

        # Security flavor supported
        SecType = "sys,krb5,krb5i,krb5p";

        # Exporting FSAL
        FSAL {
                Name = "GLUSTER";
                Hostname = localhost;
                Volume = "sharedganesha_system";
                enable_upcall = true;
                Transport = tcp; # tcp or rdma
        }
client {
        clients = 10.2.1.0/24;  # IP of the client.
        access_type = RW;
}
}

**Comment by madmax01** [comment]
doesnt matter if i mount with v3 or v4 (tested up to 4.2)....above i have RW . not understanding why i get read issues

**Comment by dang** [comment]
Can you post the error from the ganesha.log?  Something like this is usually an error from the back end filesystem (gluster, in this case), so knowing the actual error can help figure it out.

**Comment by madmax01** [comment]
root@node01:~# cd /var/lib/one/datastores/103
root@node01:/var/lib/one/datastores/103# ls
ls: reading directory '.': Remote I/O error
root@node01:/var/lib/one/datastores/103# tail -f /var/lo
local/ lock/  log/   
root@node01:/var/lib/one/datastores/103# tail -f /var/lo
local/ lock/  log/   
root@node01:/var/lib/one/datastores/103# tail -f /var/log/ganesha.log 
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Shutting down handles for FSAL PSEUDO
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Shutting down DS handles for FSAL PSEUDO
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Shutting down exports for FSAL PSEUDO
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Exports for FSAL PSEUDO shut down
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Shutting down handles for FSAL GLUSTER
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Shutting down DS handles for FSAL GLUSTER
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Shutting down exports for FSAL GLUSTER
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Exports for FSAL GLUSTER shut down
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :Unloading FSAL GLUSTER
08/02/2024 15:03:39 : epoch 65c4ea5c : node01 : ganesha.nfsd-49861[Admin] destroy_fsals :FSAL :EVENT :FSAL GLUSTER unloaded
^C
root@node01:/var/lib/one/datastores/103# date
Thu  7 Mar 16:58:34 UTC 2024
------------------------

not seeing really an info during that time when i do that.........may need log level increase?

**Comment by madmax01** [comment]
but when doing "fuse"  nativ with gluster > no issues

**Comment by madmax01** [comment]
EXPORT
{
        #Start Delay
        Start = 10;

        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 1;

        # Exported path (mandatory)
        Path = "/sharedganesha_system";

        Pseudo = "/sharedganesha_system";

        Protocols = 3,4,9P;


        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;

        Disable_ACL = TRUE;

        # Allow root access
        Squash = No_Root_Squash;

        # Security flavor supported
        SecType = "sys,krb5,krb5i,krb5p";

        # Exporting FSAL
        FSAL {
                Name = "GLUSTER";
                Hostname = localhost;
                Volume = "sharedganesha_system";
                enable_upcall = true;
                Transport = tcp; # tcp or rdma
        }
client {
        clients = 10.2.1.0/24;  # IP of the client.
        access_type = RW;
}
}


**that one above have the issue**

**have other config and not an issue**

EXPORT
{
        #Start Delay
        Start = 10;

        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 2;

        # Exported path (mandatory)
        Path = "/sharedganesha_images";

        Pseudo = "/sharedganesha_images";

        Protocols = 3,4,9P;

        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;

        Disable_ACL = TRUE;

        # Allow root access
        Squash = No_Root_Squash;

        # Security flavor supported
        SecType = "sys,krb5,krb5i,krb5p";

        # Exporting FSAL
        FSAL {
                Name = "GLUSTER";
                Hostname = localhost;
                Volume = "sharedganesha_images";
                enable_upcall = true;
                Transport = tcp; # tcp or rdma
        }
client {
        clients = 10.2.1.0/24;  # IP of the client.
        access_type = RW;
}
}

**Comment by madmax01** [comment]
3rd also not an issue

EXPORT
{
        #Start Delay
        Start = 10;

        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 3;

        # Exported path (mandatory)
        Path = "/sharedganesha_files";

        Pseudo = "/sharedganesha_files";

        Protocols = 3,4,9P;

        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;

        Disable_ACL = TRUE;

        # Allow root access
        Squash = No_Root_Squash;

        # Security flavor supported
        SecType = "sys,krb5,krb5i,krb5p";

        # Exporting FSAL
        FSAL {
                Name = "GLUSTER";
                Hostname = localhost;
                Volume = "sharedganesha_files";
                enable_upcall = true;
                Transport = tcp; # tcp or rdma
        }
client {
        clients = 10.2.1.0/24;  # IP of the client.
        access_type = RW;
}
}

Just the id 1 have issues with this strange IO read

**Comment by madmax01** [comment]
gluster 11.1 is used. just as info

**Comment by madmax01** [comment]
maybe any idea?

kernel 6.5.0-21
22.04.4 LTS (Jammy Jellyfish)

i can create folders and files.. but cannot read from on putty..... it seems once creating vms on it they can read as its inside the os..but on host side ganesha not able to read... on gluster level no issues

any ideas?

**Comment by madmax01** [comment]
i enabled full debug.

when i done "ls"  i see this. might help?


1/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[reaper] reaper_run :CLIENT ID :DEBUG :Now checking NFS4 clients for expiration
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] alloc_nfs_request :DISP :DEBUG :0x7fbe84000da0 fd 47 context 0x7fbe7c007380
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 32384
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:127.0.0.1 for Program 100003, Version 4, Function 1 has xid=580407208
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 3 operations, res = 0x7fbe7c015050, tag = NO TAG
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] nfs4_op_sequence :SESSIONS :DEBUG :SEQUENCE session=0x7fbe8400a5d0
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] complete_op :NFS4 :DEBUG :Status of OP_SEQUENCE in position 0 = NFS4_OK, op response size is 40 total response size is 76
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] process_one_op :NFS4 :DEBUG :Request 1: opcode 22 is OP_PUTFH
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] get_gsh_export :EXPORT :DEBUG :Found Export     1 pseudo (/sharedganesha_system) with path (/sharedganesha_system) and tag ((null)) perms (options=037021e0/0071f1e7 no_root_squash, RWrw, 349,               ,               ,         ,                ,                ,                , sys)
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] nfs4_mds_putfh :EXPORT :DEBUG :PUTFH Export     1 pseudo (/sharedganesha_system) with path (/sharedganesha_system) and tag ((null)) perms (options=037021e0/0071f1e7 no_root_squash, RWrw, 349,               ,               ,         ,                ,                ,                , sys)
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 13231
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] complete_op :NFS4 :DEBUG :Status of OP_PUTFH in position 1 = NFS4_OK, op response size is 4 total response size is 84
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] process_one_op :NFS4 :DEBUG :Request 2: opcode 9 is OP_GETATTR
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] file_To_Fattr :NFS4 ACL :DEBUG :No permission check for ACL for obj 0x5558351306e8
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] encode_fsid :NFS4 :DEBUG :fsid.major = 1378, fsid.minor = 99908
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] complete_op :NFS4 :DEBUG :Status of OP_GETATTR in position 2 = NFS4_OK, op response size is 164 total response size is 252
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_4] free_nfs_request :DISP :DEBUG :SVC_DECODE on 0x7fbe84000da0 fd 47 (::ffff:127.0.0.1:1008) xid=580407208 returned XPRT_IDLE
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] alloc_nfs_request :DISP :DEBUG :0x7fbe84000da0 fd 47 context 0x7fbdd8007360
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 32384
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:127.0.0.1 for Program 100003, Version 4, Function 1 has xid=597184424
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 3 operations, res = 0x7fbdd8007df0, tag = NO TAG
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs4_op_sequence :SESSIONS :DEBUG :SEQUENCE session=0x7fbe8400a5d0
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] complete_op :NFS4 :DEBUG :Status of OP_SEQUENCE in position 0 = NFS4_OK, op response size is 40 total response size is 76
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] process_one_op :NFS4 :DEBUG :Request 1: opcode 22 is OP_PUTFH
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] get_gsh_export :EXPORT :DEBUG :Found Export     1 pseudo (/sharedganesha_system) with path (/sharedganesha_system) and tag ((null)) perms (options=037021e0/0071f1e7 no_root_squash, RWrw, 349,               ,               ,         ,                ,                ,                , sys)
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs4_mds_putfh :EXPORT :DEBUG :PUTFH Export     1 pseudo (/sharedganesha_system) with path (/sharedganesha_system) and tag ((null)) perms (options=037021e0/0071f1e7 no_root_squash, RWrw, 349,               ,               ,         ,                ,                ,                , sys)
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 13231
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] complete_op :NFS4 :DEBUG :Status of OP_PUTFH in position 1 = NFS4_OK, op response size is 4 total response size is 84
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] process_one_op :NFS4 :DEBUG :Request 2: opcode 26 is OP_READDIR
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs4_op_readdir :NFS READDIR :DEBUG :dircount=4008 maxcount=4012 cookie=0
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] mdcache_readdir :NFS READDIR :DEBUG :Calling mdcache_readdir_chunked whence=0
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] mdcache_populate_dir_chunk :NFS READDIR :DEBUG :FSAL readdir status=Undefined server error
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs4_op_readdir :NFS READDIR :DEBUG :fsal_readdir returned Undefined server error
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] nfs4_op_readdir :NFS READDIR :DEBUG :Returning NFS4ERR_SERVERFAULT
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] complete_op :NFS4 :DEBUG :Status of OP_READDIR in position 2 = NFS4ERR_SERVERFAULT, op response size is 4 total response size is 92
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_SERVERFAULT lastindex = 3
11/06/2024 18:12:06 : epoch 666892d6 : node01 : ganesha.nfsd-166533[svc_10] free_nfs_request :DISP :DEBUG :SVC_DECODE on 0x7fbe84000da0 fd 47 (::ffff:127.0.0.1:1008) xid=597184424 returned XPRT_IDLE

**Comment by dang** [comment]
ENOTCONN means the socket isn't connected to the gluster cluster?  This seems unlikely, since it shouldn't get far enough to try a READDIR without a connection.  FSAL_GLUSTER never creates a ENOTCONN, so the error came from libgfapi somehow.  Maybe you're connected to 1 brick, but not to others?  I'd start with looking at the gluster logs to see where the ENOTCONN error comes from.

**Comment by madmax01** [comment]
i mean this is a default setup and causing issues......and might i'am not only one......... its most pitty gluster not supporting itself with NFS4....the ganesha ton top is not well tested......leave lots down to clients.....but well its non-support ;)

**Comment by dang** [comment]
Unfortunately, Red Hat stopped supporting Gluster years ago, and Red Hat was the only company doing Ganesha on Gluster work, so there's no one in the community that's supporting FSAL_GLUSTER anymore.
