### ISSUE TITLE
FSAL_SAUNAFS (was Is there a tool or script to update FSAL's code for bypassing commit hooks?)

### ISSUE THREAD

**Issue by ralcolea** [nfs-ganesha/nfs-ganesha#1094]
Hello community,

I'm currently working for sharing a new FSAL for a distributed filesystem called [SaunaFS](https://github.com/leil-io/saunafs) developed by Leil Storage company. We would like to share with the Ganesha community our current SaunaFS FSAL. I have been working the last days to release the code in the Ganesha repository.

However, I'm having issues to bypass commit hooks when pushing the code. I can start fixing these issues manually, but it will take longer for me because there are a lot of issues related with the column limit of 80 characters and also other reported when the open brace of functions appears in the same line as the signature and not in the other.

I found checkpatch.pl script (src/scripts/checkpatch.pl) that I tested and it fixes some of the issues, but it doesn't fix the ones related with the column limit of 80 characters. I would like to know if there is some tool or other script to speed the process of fixing the issues to bypass commit hooks.

Thanks in advance,
Ruben Alcolea

**Comment by ffilz** [comment]
There are pretty print code re-formatters that might help.

We really do appreciate having code, even FSALs, follow the preferred style For one thing, when others patch your code and submit patches to Gerrithub, the continuous integration checkpatch can flag lines that didn't change, and certainly will flag lines that changed where the submitter followed the style in place.

**Comment by ffilz** [comment]
Here's something that will help:

https://www.kernel.org/doc/html/next/process/clang-format.html

We follow the Linux kernel style (that's where we get checkpatch from), so you can grab the config file from the kernel source tree.

**Comment by ralcolea** [comment]
Thank you very much @ffilz, I really appreciate it. I will take a look to the config file from the kernel source tree and I will try to use it in my current code. I will give you feedbak after test it.

**Comment by ralcolea** [comment]
Hello @ffilz,

Your suggestion was very useful. I could format most of the code using Linux [clang format](https://github.com/torvalds/linux/blob/master/.clang-format). However there is only one issue I have not been able to fix and is related with SPDX comment style in the first line of file `handle.c`. 

For that specific file, I get the following two warnings, despite of having the expected comment in the first line, just like for the other ***.c** files:
```bash
WARNING: Improper SPDX comment style for 'src/FSAL/FSAL_SAUNAFS/handle.c', please use '//' instead
#1764: FILE: src/FSAL/FSAL_SAUNAFS/handle.c:1:
+﻿// SPDX-License-Identifier: LGPL-3.0-or-later

WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
#1764: FILE: src/FSAL/FSAL_SAUNAFS/handle.c:1:
+﻿// SPDX-License-Identifier: LGPL-3.0-or-later
```

What I cannot explain is why this only happens with the file `handle.c`. The first line of this file has the expected comment: `// SPDX-License-Identifier: LGPL-3.0-or-later`.

Any ideas about how to proceed in this case?

Thanks again,
Ruben Alcolea

**Comment by ffilz** [comment]
Checkpatch seems to be cranky about those SPDX-License-Identifier lines. If you have no other checkpatch issues with a file and are matching the style of comment for the SPDX identifiers, you can -f force commit to bypass the commit hook. When those warnings show up from the continuous integration checkpatch, I just ignore them.

**Comment by ralcolea** [comment]
Thanks for the answer @ffilz. I'm running our integration tests again Ganesha v5.7, but I'm having issues running `showmount -e` command after starting Ganesha. 

Most of our integration test run this command to check whether nfs services started successfully. I'm receiving error: 
`rpc mount export: RPC: Unable to receive; errno = Connection refused`

ASAP I will fix these issues, I will submit the code.

**Comment by ralcolea** [comment]
Hello @ffilz

I created this [PR #1097](https://github.com/nfs-ganesha/nfs-ganesha/pull/1097) for sharing SaunaFS FSAL compatible with Ganesha v5.7.

I just noticed that by accident, I included in the PR a small change in LIZARDFS FSAL for being able to compile the whole project and test if the shared library was generated correctly. This change does not belong to the SaunaFS FSAL code.
Please, tell me how should I proceed. Should I remove this change non-related with SaunaFS?

I could remove this change from the PR and if this change is needed, I can create a new PR for adding this change.

**Comment by ffilz** [comment]
Thanks for the code submission, however, as per src/CONTRIBUTING_HOWTO.txt we use Gerrithub for code submissions. Please use that process.

**Comment by ralcolea** [comment]
Thank you very much for your answer. I will use the Contributing file for submitting the code, and I will give you feedback after doing it.

**Comment by ralcolea** [comment]
I submitted this [patch](https://gerrithub.io/c/ffilz/nfs-ganesha/+/1185373) for adding SaunaFS FSAL to be reviewed.

**Comment by ffilz** [comment]
Thanks for the submission.

As to including this in V5-stable, first you get the patch reviewed, updated if necessary (probably, there are some recent changes to fsal_fd that should be considered), and then merged into next.

Once there, we back port to V5-stable.

**Comment by ralcolea** [comment]
Thank you very much @ffilz for your quick answer.
I will review your suggestions and will update the requested changes.

All the best,
Rubén Alcolea

**Comment by ffilz** [comment]
Closing as done with 6.0 release.
