### ISSUE TITLE
[Question] What is the meaning of `add_revoke_fh` in `nfs4_recovery_backend`?

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1095]
I'm reading Ganesha code, and confused about the `add_revoke_fh` callback in `nfs4_recovery_backend`.  

It seems that Ganesha will record all delegations revoked history into recovery_backend when running. And after Ganesha restarts, it will reload these revoked file handles from recovery_backend to check whether delegations to be reclaimed are valid. 

What problem is this callback designed to solve? Is it not enough to just use clid_list to check whether a client can reclaim state?

Some cases are appreciated.

**Comment by ffilz** [comment]
The purpose is to harden revoked delegations, so if a delegation was revoked and the server crashed, a client that had not yet processed the delegation revocation would not be allowed to reclaim the delegation. The client would otherwise be allowed to reclaim state.

**Comment by zhitaoli-6** [comment]
Got it. Thanks for your reply.
