### ISSUE TITLE
Mount fails with EACCES if `sec=none` is not specified on Export with `Sectype=none`

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1100]
For a NFS export configured as follows:
```
EXPORT {
    Export_Id = 1;
    Path = /ns-hadoop-test;
    Pseudo = /ns-hadoop-test;
    Attr_Expiration_Time = 0;
    Access_Type = RW;
    Squash = no_root_squash;
    Sectype = none;
    Anonymous_uid = -2;
    Anonymous_gid = -2;
    FSAL {
        Name = SFS;
    }
}
```

If we mount with v3 and other options as default, mount fails with EACCES. If we mount with v3 and `sec=none`, or mount with NFS v4, mount succeeds. 
<img width="699" alt="image" src="https://github.com/nfs-ganesha/nfs-ganesha/assets/13163985/58d5678e-cf0b-44c2-9210-cb07644ac52e">

When we mount with v3, `dmesg` shows that:
```
[Mon Mar 18 15:25:07 2024] NFS: received 1 auth flavors
[Mon Mar 18 15:25:07 2024] NFS:   auth flavor[0]: 0
[Mon Mar 18 15:25:07 2024] NFS: MNT request succeeded
[Mon Mar 18 15:25:07 2024] NFS: attempting to use auth flavor 1
...
[Mon Mar 18 15:25:07 2024] NFS call pathconf
[Mon Mar 18 15:25:07 2024] RPC: xs_tcp_send_request(112) = 0
[Mon Mar 18 15:25:07 2024] RPC: xs_data_ready...
[Mon Mar 18 15:25:07 2024] RPC: server 192.168.31.153 requires stronger authentication.
[Mon Mar 18 15:25:07 2024] NFS reply pathconf: -13
[Mon Mar 18 15:25:07 2024] NFS call getattr
[Mon Mar 18 15:25:07 2024] RPC: xs_tcp_send_request(112) = 0
[Mon Mar 18 15:25:07 2024] RPC: xs_data_ready...
[Mon Mar 18 15:25:07 2024] RPC: server 192.168.31.153 requires stronger authentication.
[Mon Mar 18 15:25:07 2024] NFS reply getattr: -13
```

When `sec` option is not specified by mount, Linux kernel will try `auth flavor 1` though `auth flavor 0` is supported, and nfs-ganesha replies with EACCES. 

 According to `man 5 nfs`:
```
       sec=flavors    A  colon-separated  list of one or more security flavors to
                      use for accessing files  on  the  mounted  export.  If  the
                      server  does  not  support  any of these flavors, the mount
                      operation fails.  If sec=  is  not  specified,  the  client
                      attempts to find a security flavor that both the client and
                      the server supports.  Valid flavors are  none,  sys,  krb5,
                      krb5i,  and  krb5p.   Refer  to the SECURITY CONSIDERATIONS
                      section for details.
```
It seems that nfs-ganesha and Linux NFS client do not co-work very well currently in this case.

**Comment by dang** [comment]
I think this is intended by the linux kernel, if I'm understanding correctly.  A while ago. the kernel was changed to never try sec=NONE unless it was specified on the command line.  This was done for security reasons.  So if sec=NONE is the only security supported on an export, you have to specify it on the mount command line to get it to work.  I don't believe there's any fix for this, since it's intentional.

**Comment by ffilz** [comment]
I agree that it's an intentional thing, and anyway, I don't see anything Ganesha should do differently. The export has been configured to only accept sectype=none. The code should enforce that no matter what the client does.

**Comment by zhitaoli-6** [comment]
Thanks @dang @ffilz for your reply. Got it.
