### ISSUE TITLE
build failure on centos7.2

### ISSUE THREAD

**Issue by osier** [nfs-ganesha/nfs-ganesha#111]
```
# make
Scanning dependencies of target log
[  0%] Building C object log/CMakeFiles/log.dir/log_functions.c.o
In file included from /root/nfs-ganesha/src/log/log_functions.c:51:0:
/root/nfs-ganesha/src/include/gsh_rpc.h:17:28: fatal error: rpc/xdr_inline.h: No such file or directory
 #include <rpc/xdr_inline.h>
                            ^
compilation terminated.
make[2]: *** [log/CMakeFiles/log.dir/log_functions.c.o] Error 1
make[1]: *** [log/CMakeFiles/log.dir/all] Error 2
make: *** [all] Error 2
[root@i-c15zaghi nfs-ganesha]# 
```

I tried find xdr_inline.h under /usr/include, there is one, but it's of ntirpc:

```
# find . | grep xdr_inline
./ntirpc/rpc/xdr_inline.h
```

It looks like ganesha is not compatible with CentOS 7 yet?

**Comment by osier** [comment]
More info:

```
# uname -a
Linux i-c15zaghi 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

And the failure was on building with branch V2.3-stable.

**Comment by kalebskeithley** [comment]
did you do a `git submodule --init` (or similar) to get the ntirpc submodule? Or install libntirpc-devel from EPEL or CentOS Storage SIG.

Otherwise we there are builds of 2.3.2 in EPEL at https://koji.fedoraproject.org/koji/buildinfo?buildID=759929 and builds of 2.3.3 in CentOS Build System for the CentOS Storage Sig at https://cbs.centos.org/koji/buildinfo?buildID=12057 that would seem to suggest that ganesha is compatible with CentOS 7.

**Comment by GuanshengWang** [comment]
git submodule update --init --recursive ; you can do it! it's work.
twitter: wgs0120

**Comment by lokendrarathour** [comment]
hello team, any update on the issue as above,i am also facing the same issue in centos 8. 
root@localhost build]# make
[  1%] Building C object MainNFSD/CMakeFiles/MainServices.dir/nfs_admin_thread.c.o
In file included from /root/nfs-ganesha/src/include/nfs4.h:5,
                 from /root/nfs-ganesha/src/include/fsal_pnfs.h:37,
                 from /root/nfs-ganesha/src/include/sal_data.h:50,
                 from /root/nfs-ganesha/src/include/nfs_core.h:41,
                 from /root/nfs-ganesha/src/MainNFSD/nfs_admin_thread.c:41:
/root/nfs-ganesha/src/include/gsh_rpc.h:17:10: fatal error: rpc/xdr_inline.h: No such file or directory
 #include <rpc/xdr_inline.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/build.make:59: MainNFSD/CMakeFiles/MainServices.dir/nfs_admin_thread.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2121: MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make: *** [Makefile:137: all] Error 2

**Comment by dang** [comment]
xdr_inline.h is part of ntirpc, which is a sub-module of Ganesha.  You need to run the command in the previous comment:

git submodule update --init --recursive

**Comment by lokendrarathour** [comment]
Yes Daniel,
Thanku so much for your inputs.
 It did work !!

Best regards,
Lokendra
