### ISSUE TITLE
IO HUNG UP  in NFS-GANESHA 5.7

### ISSUE THREAD

**Issue by tojoyccnu** [nfs-ganesha/nfs-ganesha#1112]
For high performance, I tried to enable the PNFS option, then i mount nfs by 
`
mount -t nfs -o vers=4.2,sec=krb5p 192.168.5.84:/ /mnt/nfs
`

> 07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_op :NFS4 :DEBUG :Status of OP_PUTFH in position 1 = NFS4_OK, op response size is 4 total response size is 84
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] process_one_op :NFS4 :DEBUG :Request 2: opcode 64 is OP_LAYOUTERROR
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] nfs4_op_layouterror :PNFS :EVENT :LAYOUTERROR OP 13 status 0 offset: 0 length: 4
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_op :NFS4 :DEBUG :Status of OP_LAYOUTERROR in position 2 = NFS4_OK, op response size is 4 total response size is 92
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_request :DISP :F_DBG :Before svc_sendreply on socket 25
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] rpc :TIRPC :DEBUG :svc_vc_reply: 0x7fb3530c9c00 fd 25 SVCAUTH_WRAP failed (will set dead)
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_request :DISP :DEBUG :NFS DISPATCHER: FAILURE: Error while calling svc_sendreply on a new request. rpcxid=3473231288 socket=25 function:NFS4_COMP client:::ffff:192.168.5.97 program:100003 nfs version:4 proc:1 errno: 0
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_request :DISP :F_DBG :After svc_sendreply on socket 25
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] free_nfs_request :DISP :DEBUG :SVC_DECODE on 0x7fb3530c9c00 fd 25 (::ffff:192.168.5.97:984) xid=3473231288 returned (null)
07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] free_nfs_request :DISP :F_DBG :free_nfs_request: 0x7fb3530c9c00 fd 25 xp_refcnt 3

SO, I doute that, version 4.2 of  NFS-GANESHA  or PNFS of  NFS-GANESHA  is Completed?

**Comment by tojoyccnu** [comment]
Similar to this issue  #452

**Comment by tojoyccnu** [comment]
> 07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_op :NFS4 :DEBUG :Status of OP_LAYOUTERROR in position 2 = NFS4_OK, op response size is 4 total response size is 92
> 07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_request :DISP :F_DBG :Before svc_sendreply on socket 25
> 07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] rpc :TIRPC :DEBUG :svc_vc_reply: 0x7fb3530c9c00 fd 25 SVCAUTH_WRAP failed (will set dead)
> 07/04/2024 14:13:34 : epoch 66123969 : node584.jetio.com : ganesha.nfsd-57317[svc_4] complete_request :DISP :DEBUG :NFS DISPATCHER: FAILURE: Error while calling svc_sendreply on a new request. rpcxid=3473231288 socket=25

**Comment by ffilz** [comment]
What FSAL are you using? We have limited PNFS support, not all FSALs support it and it has not had recent attention from any of the active contributors. Do note that PNFS is an optional feature, so not having it does not make Ganesha incomplete for 4.2.

**Comment by xiaods** [comment]
@tojoyccnu please check the wiki, it show some notes abt pNFS

**pNFS**
NFS-Ganesha has support infrastructure for pNFS but efforts in this area have not been active for many years and pNFS is not currently supported by the active community.

**Comment by xiaods** [comment]
@tojoyccnu any feedback?

**Comment by ffilz** [comment]
Closing for being inactive for more than 60 days.

Please re-open if you have more questions.

Note that almost certainly code changes will be necessary to use pNFS.
