### ISSUE TITLE
Is this a bug in ntirpc ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#1115]
@ffilz @dang hi, we met nfs client hang for rpc length and body mismatch.

**Reason**
let's see the function [svc_ioq_flushv](https://github.com/nfs-ganesha/ntirpc/blob/bac8a136c8c756a8d9bd7471789a2c592698da95/src/svc_ioq.c#L74C1-L74C15) in ntirpc.

**step1**
svc_ioq_flushv process an xioq with xioq->write_start=0, and end=10, i.e. there exist 10 bytes to send
**step2**
first into while loop with remaining=10, because xioq->write_start is 0, so frag_hdr_size is 4 bytes, and we need 4 bytes header to save the length of 10 bytes, so need to send 14bytes = 4bytes(header) + 10bytes(body).
**step3**
sendmsg send 2 bytes of header, and result=2 which less than frag_hdr_size=4bytes, and [goto again](https://github.com/nfs-ganesha/ntirpc/blob/bac8a136c8c756a8d9bd7471789a2c592698da95/src/svc_ioq.c#L267)
**step4**
in again, sendmsg send 5bytes(result=5) including 2bytes header and 3bytes body, then result-= frag_hdr_size, so result=1, then remaining-=result, so remaining is 9bytes, and xioq->write_start+=result, so xioq->write_start=1. but actually remaining should be 7 and xioq->write_start should be 3, because already sent [0, 3)bytes body.
**step5**
twice into while loop with remaining=9, and xioq->write_start=1, so send [1, 3)bytes body again. i.e. we send [1, 3)bytes body twice times in step4 and step5. and error happens.

**Comment by liyinshubyte** [comment]
@ffilz @dang friendly ping.

**Comment by ffilz** [comment]
Since this is indeed an ntirpc bug, please see the pull request referenced above.

Can we close this issue now?

**Comment by liyinshubyte** [comment]
sure
