### ISSUE TITLE
NFSv4.1 client hangs Status: NFS4ERR_BAD_STATEID

### ISSUE THREAD

**Issue by Howar-sz** [nfs-ganesha/nfs-ganesha#1117]
## background
I use ganesha's NFSv4.1 to run a vdbench job with restart ganesha daemon and vdbench's traffic has stop without recovery after Ganesha grace complete. So, I use tcpdump to capture the packet in client found the nfsclient does not send **`RECLAIM_COMPLETE`**, and **`TEST_STATEID`** return a `NFS4ERR_BAD_STATEID` error.
<img width="639" alt="image" src="https://github.com/nfs-ganesha/nfs-ganesha/assets/13518768/f70f6c56-0512-4b56-8c40-e111e8123516">

## What did I try
I try to read NFSv4.1's RFC and found in [section 15.1.16.5](https://datatracker.ietf.org/doc/html/rfc5661#section-15.1.16.5) `NFS4ERR_STALE_STATEID` is moot in NFSv4.1.
> A stateid generated by an earlier server instance was used. This
error is moot in NFSv4.1 because all operations that take a stateid
MUST be preceded by the SEQUENCE operation, and the earlier server
instance is detected by the session infrastructure that supports
SEQUENCE.

I found ganesha has been [old an issue](https://github.com/nfs-ganesha/nfs-ganesha/issues/801) about the same problem, so maybe it needs `NFS4ERR_BAD_STATEID` error in NFSv4.1 protocol, I have tried to fix it in NFSv4.1 and it works.
https://github.com/nfs-ganesha/nfs-ganesha/blob/2cf6d40fa8d92519cd7d3cbe5b6bd22f201c778a/src/SAL/nfs4_state_id.c#L920

**Comment by ffilz** [comment]
I'm re-opening the old issue, and duping this to it.

This is a dupe of #801

**Comment by ffilz** [comment]
Can we close this in favor of #801?

**Comment by ffilz** [comment]
Try this fix https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1193189?usp=search

It retains NFS4ERR_STALE_STATEID for 4.0 while changing to NFS4ERR_BAD_STATEID for 4.1.

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1193189?usp=search

**Comment by Howar-sz** [comment]
> Can we close this in favor of #801?

Sure, I close this.
