### ISSUE TITLE
does nfs-ganesha support translateing 64 bits inode to 32 bits?

### ISSUE THREAD

**Issue by hit1943** [nfs-ganesha/nfs-ganesha#1118]

**Comment by ffilz** [comment]
Could you give more insight on this question?

**Comment by hit1943** [comment]
> Could you give more insight on this question?

ok, my nfs server is nfs-ganesha+libcephfs，so the file inode number is 64bits，and the client is an android envirement，and some app is 32 bit，when the apps visited the nfs mounted dir，they crashed

i try to disable the client nfs config "enable_ino64" by set:
echo N > /sys/module/nfs/parameters/enable_ino64
then the apps can run normally

so is it a good idea to translate inode number from 64bit to 32bit in nfs-ganesha?

**Comment by ffilz** [comment]
Really the best solution is that client option since the issue is a client side limitation.

**Comment by xiaods** [comment]
please /close as resolved.
