### ISSUE TITLE
Does support NFS Multipathing Link feature.

### ISSUE THREAD

**Issue by xiaods** [nfs-ganesha/nfs-ganesha#1121]
https://docs.openeuler.org/en/docs/23.03/docs/NfsMultipath/usage.html

Hi team, I want to know nfs-ganesha can support NFS Multipathing Link  feature.

NFS 4.1 supports multipathing as per protocol specifications. For NFS 3 multipathing is not applicable.

**Comment by xiaods** [comment]
i read RFC5661(NFS v4.1) https://datatracker.ietf.org/doc/html/rfc5661#section-13.5  Data Server Multipathing section, the rfc docs said: The NFSv4.1 file layout supports multipathing to multiple data server  addresses.

**Comment by ffilz** [comment]
Per issue #398, it's possible Ganesha now supports session trunking which I believe would allow this for NFSv4.1+

**Comment by xiaods** [comment]
OK. thanks for clarify.
