### ISSUE TITLE
Q: unwind requires libc-devel, provided by which package in centos 8.2?

### ISSUE THREAD

**Issue by Haroldll** [nfs-ganesha/nfs-ganesha#1122]
When installing the latest version of ganesha, the os reported an error:
```
1.177 Error:
1.177  Problem: conflicting requests
1.177   - nothing provides libc-devel needed by nfs-ganesha-utils
```

I found the corresponding code：
```
%if %{with unwind}
%if ( 0%{?rhel} && 0%{?rhel} < 8 )
Requires: libc6-dev
%else
Requires: libc-devel
%endif
%if ( 0%{?suse_version} )
Requires: glibc-devel
%endif
%endif
```

In centos 8.2, Requires is libc-devel, but I don't find this dependency in my os, only the glibc-devel provided by the glibc-devel-2.28 package is seen. 
So, may I ask which rpm package provides libc-devel in centos 8.2?
Also, why is it nfs-ganesha-utils that needs this dependency?

**Comment by xiaods** [comment]
@Haroldll please provide your specific nfs-ganesha version use yum.

**Comment by Haroldll** [comment]
> @Haroldll please provide your specific nfs-ganesha version use yum.

nfs-ganesha version is 6-dev.11.
nothing provides libc-devel needed by nfs-ganesha-utils-6-dev.11.el8.x86_64

**Comment by kalebskeithley** [comment]
How exactly did you install?   With `dnf install -y ...`?   Or with `rpm -I ...` ?  Packages I presume you built from source?

**Comment by Haroldll** [comment]
> How exactly did you install? With `dnf install -y ...`? Or with `rpm -I ...` ? Packages I presume you built from source?

Yes, build the rpm packages from source and then use rpm -ivh ... command to install

**Comment by xiaods** [comment]
https://cbs.centos.org/koji/buildinfo?buildID=51972#/   use this package to install

**Comment by Haroldll** [comment]
> https://cbs.centos.org/koji/buildinfo?buildID=51972#/ use this package to install

nfs-ganesha-5.7-2.el8 is fine, but this version contains no modifications: https://github.com/nfs-ganesha/nfs-ganesha/commit/158f3958292c1bd9572270caa85999adabe33dc7

**Comment by xiaods** [comment]
> > https://cbs.centos.org/koji/buildinfo?buildID=51972#/ use this package to install
> 
> nfs-ganesha-5.7-2.el8 is fine, but this version contains no modifications: [158f395](https://github.com/nfs-ganesha/nfs-ganesha/commit/158f3958292c1bd9572270caa85999adabe33dc7)

ok. you only build rpm by yourself.

**Comment by kalebskeithley** [comment]
If you're going to use `rpm -ivh ...` to install, then you have to install the dependencies yourself.

Or you could use `dnf install ...`, (or `yum install ...`) instead, which will automatically install any required dependencies.

If you're coming from the SUSE world, dnf/yum are analogous to zypper.

**Comment by xiaods** [comment]
> When installing the latest version of ganesha, the os reported an error:
> 
> ```
> 1.177 Error:
> 1.177  Problem: conflicting requests
> 1.177   - nothing provides libc-devel needed by nfs-ganesha-utils
> ```
> 
> I found the corresponding code：
> 
> ```
> %if %{with unwind}
> %if ( 0%{?rhel} && 0%{?rhel} < 8 )
> Requires: libc6-dev
> %else
> Requires: libc-devel
> %endif
> %if ( 0%{?suse_version} )
> Requires: glibc-devel
> %endif
> %endif
> ```
> 
> In centos 8.2, Requires is libc-devel, but I don't find this dependency in my os, only the glibc-devel provided by the glibc-devel-2.28 package is seen. So, may I ask which rpm package provides libc-devel in centos 8.2? Also, why is it nfs-ganesha-utils that needs this dependency?

glibc-devel is new better version than libc-devel. nfs-ganesha-utils use some c calling, it maybe dependency with libc. directly use glibc-devel as soon as.

**Comment by Haroldll** [comment]
> If you're going to use `rpm -ivh ...` to install, then you have to install the dependencies yourself.
> 
> Or you could use `dnf install ...`, (or `yum install ...`) instead, which will automatically install any required dependencies.
> 
> If you're coming from the SUSE world, dnf/yum are analogous to zypper.

yum install nfs-ganesha nfs-ganesha-utils
Last metadata expiration check: 0:00:26 ago on Wed 08 May 2024 06:51:22 AM UTC.
Error:
 Problem: conflicting requests
  - nothing provides libc-devel needed by nfs-ganesha-utils-6-dev.11.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

yum can't find this dependency either.

**Comment by xiaods** [comment]
@Haroldll cloud you please share your spec, let me testing on my box. I suggest directly update spec to use glibc-devel replace libc-devel. the spec is out of date on centos8

**Comment by Haroldll** [comment]
> @Haroldll cloud you please share your spec, let me testing on my box. I suggest directly update spec to use glibc-devel replace libc-devel. the spec is out of date on centos8

My spec is the community source code, unmodified, and I also think that libc-devel should be glibc-devel, since glibc-devel doesn't report dependency errors.

**Comment by xiaods** [comment]
> > @Haroldll cloud you please share your spec, let me testing on my box. I suggest directly update spec to use glibc-devel replace libc-devel. the spec is out of date on centos8
> 
> My spec is the community source code, unmodified, and I also think that libc-devel should be glibc-devel, since glibc-devel doesn't report dependency errors.

agree with your options. this is bug.

**Comment by kalebskeithley** [comment]
> > When installing the latest version of ganesha, the os reported an error:
> > ```
> > 1.177 Error:
> > 1.177  Problem: conflicting requests
> > 1.177   - nothing provides libc-devel needed by nfs-ganesha-utils
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I found the corresponding code：
> > ```
> > %if %{with unwind}
> > %if ( 0%{?rhel} && 0%{?rhel} < 8 )
> > Requires: libc6-dev
> > %else
> > Requires: libc-devel
> > %endif
> > %if ( 0%{?suse_version} )
> > Requires: glibc-devel
> > %endif
> > %endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In centos 8.2, Requires is libc-devel, but I don't find this dependency in my os, only the glibc-devel provided by the glibc-devel-2.28 package is seen. So, may I ask which rpm package provides libc-devel in centos 8.2? Also, why is it nfs-ganesha-utils that needs this dependency?
> 
> glibc-devel is new better version than libc-devel. nfs-ganesha-utils use some c calling, it maybe dependency with libc. directly use glibc-devel as soon as.

I don't know where the author of that change got those package names from. 

I'd say that, across the board:  rhel, centos, fedora, and suse, it should just be glibc-devel. Even on centos7 and rhel7. Probably even on rhel6/centos6, although I can't check.  Looking back through Red Hat's build system there was a glibc-devel on rhel6 too.

**Comment by xiaods** [comment]
> %if %{with unwind}
> %if ( 0%{?rhel} && 0%{?rhel} < 8 )
> Requires: libc6-dev
> %else
> Requires: libc-devel
> %endif
> %if ( 0%{?suse_version} )
> Requires: glibc-devel
> %endif
> %endif

I seriously doubt that the nfs-ganesha.spec file you have comes from the SUSE community. 

https://gist.github.com/trinhpham/b90f4b2741f01948f9165a13a0cfd986 sample setup scripts.

**Comment by kalebskeithley** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1194649
