### ISSUE TITLE
Add testing instructions to CONTRIBUTING_HOWTO.txt

### ISSUE THREAD

**Issue by yonic2** [nfs-ganesha/nfs-ganesha#1127]
Following the discussion with @ffilz, there are a few tests that are being run manually by the maintainers before merging a branch (e.g. pynfs).
It would be nice to have those documented in CONTRIBUTING_HOWTO.txt so the branch authors can reproduce the errors and fix them.

**Comment by xiaods** [comment]
@yonic2 contribute is welcome

**Comment by ffilz** [comment]
Done
