### ISSUE TITLE
Ha cluster config

### ISSUE THREAD

**Issue by neroita** [nfs-ganesha/nfs-ganesha#1129]
Hi all ,
I'm using nfs-ganesha to export a ocfs filesystem on a two node cluster.
This is the config:
* corosync/pacemaker move cluster ip from one node to other.
* filesystem to export is on shared ocfs2 storage.
* nfs-ganesha run at startup when fs is already mounted on both nodes.
* this is ganesha.conf:
```
NFS_CORE_PARAM {
        Enable_NLM = false;
        Enable_RQUOTA = false;
        Protocols = 4;
        mount_path_pseudo = true;
}
NFS_KRB5 {
        Active_krb5 = false;
}
NFSV4 { 
        Only_Numeric_Owners = true; 
}
CACHEINODE {
    Dir_Chunk = 0;
    NParts = 1;
    Cache_Size = 1;
}
MDCACHE {
        Dir_Chunk = 0;
}
EXPORT {
        Export_Id = 2;
        Path = "/u";
        Pseudo = "/u";
        Protocols = 4;
        Disable_ACL = TRUE;
        Transports = "TCP";
        Access_Type = RW;
        Sectype = "sys";
        Attr_Expiration_Time = 0;
        Squash = no_root_squash;
        FSAL {
                Name = VFS;
        }
        CLIENT {
                Clients = 10.0.0.0/16;
        }
}
```

Everything seem to work but when I move the service from one node to another:
1) I get that message on client's dmesg:
```
[683224.304437] NFS: nfs: lost 2 locks
[683339.273146] NFS: nfs: lost 2 locks
```
2) Some service on my swarm cluster that run on nfs get an IOWAIT error.

Is there something on my config that I need to change or optimize ?

thank's,
neroita.

**Comment by xiaods** [comment]
@neroita 

https://serverfault.com/questions/943474/can-2-servers-share-the-same-ocfs2-fs-via-nfs
This could be a potential bug with OCFS2.

**Comment by xiaods** [comment]
@neroita 

https://serverfault.com/questions/943474/can-2-servers-share-the-same-ocfs2-fs-via-nfs
This could be a potential bug with OCFS2.
