### ISSUE TITLE
[Question] Is there replay cache for NFS v3 or NFS v4.0 in nfs-ganesha?

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1131]
In our environment using NFS, we find that NFS client does not change the source port on reconnecting, which may bring some problems(eg.  slow to recover) as the VIP is detached/attached from/to nfs-ganesha node. 

In fact, we prefer NFS client changes the source port on reconnecting to avoid problems resulting from stale TCP sockets in nfs-ganesha node.

Linux commit "[NFSv4.1: Don't rebind to the same source port when reconnecting](https://github.com/torvalds/linux/commit/e6237b6feb37582fbd6bd7a8336d1256a6b4b4f9)" brings this behavior.  

```
NFSv4.1: Don't rebind to the same source port when reconnecting to th…
…e server

NFSv2, v3 and NFSv4 servers often have duplicate replay caches that look
at the source port when deciding whether or not an RPC call is a replay
of a previous call. This requires clients to perform strange TCP gymnastics
in order to ensure that when they reconnect to the server, they bind
to the same source port.

NFSv4.1 and NFSv4.2 have sessions that provide proper replay semantics,
that do not look at the source port of the connection. This patch therefore
ensures they can ignore the rebind requirement.

Signed-off-by: Trond Myklebust <trond.myklebust@hammerspace.com>
```
It seems that `nfsd` may look at the source port because of replay cache. So I want to know whether nfs-ganesha have such replay cache or not.

**Comment by ffilz** [comment]
Ganesha has DRC, but it is not used for V4.1+. The DRC does match source port, so NFSv3 and NFSv4.0 clients should endeavor to re-use the source port on re-connection for DRC purposes.

**Comment by zhitaoli-6** [comment]
Got it. Thanks for your reply.
