### ISSUE TITLE
How to close socket when socket idle ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#1133]
@ffilz Hi, when the bug happens https://github.com/nfs-ganesha/ntirpc/pull/294. Our nfs client hang, and client will not send any message to server. So when socket idle, we want to close socket in nfs-ganesha, and client will recover from hang. we only make this change in our company, and will not submit merge request to community to avoid bug.  But I don't know how to close socket, because if I call SVC_DESTROY,  I need to set xprt.xp_flags, not sure it's right or not. Could you give me some suggestions about how to close socket ?

**Comment by liyinshubyte** [comment]
@dang cc

**Comment by dang** [comment]
You shouldn't need to set anything, just call SVC_DESTROY().  By default, TCP sockets are closed when the xprt is destroyed.

**Comment by liyinshubyte** [comment]
Thanks a lot, I will try it.

**Comment by xiaods** [comment]
@liyinshubyte /close as resolved
