### ISSUE TITLE
NFSv4 ACL support in FSAL_VFS but without VFS_POSIX_ACL / USE_ACL_MAPPING

### ISSUE THREAD

**Issue by maksim-harbachou-resilio** [nfs-ganesha/nfs-ganesha#1134]
Hello.
Could you please provide information about NFSv4 ACL support in FSAL_VFS but without VFS_POSIX_ACL / USE_ACL_MAPPING ?

Not sure if it's a real bug or just a result of misconfiguration, but with nfs-ganesha built from current `next` with the following config:
```
ENABLE_RFC_ACL:BOOL=ON
ENABLE_VFS_DEBUG_ACL:BOOL=ON
ENABLE_VFS_POSIX_ACL:BOOL=OFF
USE_ACL_MAPPING:BOOL=OFF
USE_NFSACL3:STRING=OFF
USE_FSAL_VFS:STRING=ON
```
nfs4 client gets EOPNOTSUPP on attempt to read NFSv4 ACL:
```
$ strace nfs4_getfacl /mnt/share2/test1
...
stat("/mnt/share2/test1", {st_mode=S_IFREG|0600, st_size=4, ...}) = 0
getxattr("/mnt/share2/test1", "system.nfs4_acl", NULL, 0) = -1 EOPNOTSUPP (Operation not supported)
write(2, "Operation to request attribute n"..., 64Operation to request attribute not supported: /mnt/share2/test1
```

It works with VFS_POSIX_ACL / USE_ACL_MAPPING, but I'd like to have original (not converted to POSIX ACL) NFSv4 ACL in xattrs.
Is it possible? If yes, what build parameters should be used?

BTW, it seems FSAL_VFS info at https://github.com/nfs-ganesha/nfs-ganesha/wiki/ACL-Support should be updated.

**Comment by dang** [comment]
I don't believe that VFS has any support for NFS ACLs.  It only supports POSIX ACLs, since is only supports POSIX filesystems.  If you want any ACL support it VFS, you will need to map to POSIX ACLs.

**Comment by maksim-harbachou-resilio** [comment]
> I don't believe that VFS has any support for NFS ACLs. It only supports POSIX ACLs, since is only supports POSIX filesystems. If you want any ACL support it VFS, you will need to map to POSIX ACLs.

The question is more about FSAL_VFS than VFS itself. If I get src/FSAL/FSAL_VFS/vfs/attrs.c correctly, the answer is -- no, currently it's not possible to just put NFSv4 ACL to xattrs using FSAL_VFS. Currently FSAL_VFS either does in-memory processing of NFSv4 ACLs (with ENABLE_VFS_DEBUG_ACL), or converts those to POSIX ACLs and writes to FS /  `system.posix_acl_access` xattrs (with ENABLE_VFS_POSIX_ACL), or does nothing.

**Comment by dang** [comment]
(I meant FSAL_VFS).  Without something like RichACLs (which the linux kernel seems to not want), we cannot support NFS ACLs in FSAL_VFS.

**Comment by maksim-harbachou-resilio** [comment]
> (I meant FSAL_VFS). Without something like RichACLs (which the linux kernel seems to not want), we cannot support NFS ACLs in FSAL_VFS.

Thanks. Could you please clarify the purpose of ENABLE_VFS_DEBUG_ACL ? Does that code enforce any access limitations? I was not able to make it work..

**Comment by dang** [comment]
It was originally written in support of a draft RFC that defined rules for converting NFS ACLs to POSIX ACLs in a way that was at least consistent, if not correct.  It did do enforcement as long as the ACL was stored in memory, but when it went out of memory, it stopped enforcement.  It was intended for dev and debugging, rather than for production use.  It has not been tested in years, so it may be completely broken.

**Comment by maksim-harbachou-resilio** [comment]
> It was originally written in support of a draft RFC that defined rules for converting NFS ACLs to POSIX ACLs in a way that was at least consistent, if not correct. It did do enforcement as long as the ACL was stored in memory, but when it went out of memory, it stopped enforcement. It was intended for dev and debugging, rather than for production use. It has not been tested in years, so it may be completely broken.

Thanks again. I thought it would be not that hard to read / store NFS4 ACLs from / to xattrs without converting from / to POSIX ACLs and reuse ENABLE_VFS_DEBUG_ACL code to actually enforce access rules. That would provide support for persistent NFS4 ACLs. Now it seems that task requires much more work.

**Comment by ffilz** [comment]
Yea, Ganesha trying to actually manage NFSv4 ACLs for production use would be a challenge.

For what it's worth, there has been mention of maybe getting NFSv4 ACLs into Lustre.

**Comment by dang** [comment]
You can do a "best effort" enforcement that way, but it can't be complete, because the filesystem isn't doing the enforcement.  So there will at least be races between setting and enforcement.  This means it's probably best not to depend on it for security,  However, it can be used for testing/developing against NFS ACLs.
