### ISSUE TITLE
Docker support (make rpcbind optional)

### ISSUE THREAD

**Issue by drauschenbach** [nfs-ganesha/nfs-ganesha#114]
rpcbind is currently documented as being used in support of NFSv3, but startup actually fails in a Docker container that is configured for exclusive NFSv4/tcp.

The experimental Docker containers out there don't really work since the Dockerfile can't encapsulate ganesha, and `systemctl start rpcbind` has to be run on the Host OS before the container can be launched, which obviously doesn't work in most Docker runtime environments such as Kubernetes, Marathon, etc.

**Comment by dang** [comment]
The way I've fixed this is to just start rpcbind in the entrypoint of the image, like so:
function start_rpc {
  rpcbind || return 0
  rpc.statd -L || return 0
  rpc.idmapd || return 0
}

Then just call this function once.

**Comment by drauschenbach** [comment]
@dang when I try that, ganesha.nfsd seg faults on invocation, even before logging anything.

**Comment by dang** [comment]
Well, works for me...  I am running with host networking, however.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by DUOLabs333** [comment]
I have the same problem --- even if I only configure it for v4, I still need rpcbind.
