### ISSUE TITLE
[ubuntu] nfs-ganesha 5 package issues on Ubuntu 22.04

### ISSUE THREAD

**Issue by gouthampacha** [nfs-ganesha/nfs-ganesha#1149]
We install nfs-ganesha packages via the Ubuntu PPA to test OpenStack Manila on an Ubuntu 22.04 LTS host; and since the beginning of June 2024, we're hitting a package issue. 

The steps to reproduce:

**Enable the ubuntu PPA**

sudo add-apt-repository -y ppa:nfs-ganesha/libntirpc-5
sudo add-apt-repository -y ppa:nfs-ganesha/nfs-ganesha-5

**Install the nfs-ganesha packages**
sudo apt-get install libntirpc5 nfs-ganesha nfs-ganesha-ceph nfs-ganesha-rados-urls nfs-ganesha-vfs 

**Setup a ganesha.conf file**

**Start the nfs-ganesha service**
sudo systemctl enable nfs-ganesha
sudo systemctl start nfs-ganesha

Extracted error log: https://paste.opendev.org/show/bQZaqHitjdJzoe9slNAc/

The failure occurs when starting the nfs-ganesha service, the startup failure:
```
2024-06-26 19:01:22.127821 | controller | Jun 26 19:01:22 np0037817366 bash[85969]: /usr/bin/ganesha.nfsd: error while loading shared libraries: libntirpc.so.5.0: cannot open shared object file: No such file or directory
```

**Comment by relzhong** [comment]
nfs-ganesha build [failed](https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-5/+build/28593348), so package version of nfs-ganesha no update to 5.9 and confilct with libntirpc5_5.8.

**Comment by gouthampacha** [comment]
> nfs-ganesha build [failed](https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-5/+build/28593348), so package version of nfs-ganesha no update to 5.9 and confilct with libntirpc5_5.8.

This failed build seems to be for Ubuntu Bionic Beaver (20.04 LTS). Is there a possibility the build for Jammy Jellyfish (22.04 LTS) wasn't tested? 


/cc @ffilz @kalebskeithley

**Comment by xiaods** [comment]
> > nfs-ganesha build [failed](https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-5/+build/28593348), so package version of nfs-ganesha no update to 5.9 and confilct with libntirpc5_5.8.
> 
> This failed build seems to be for Ubuntu Bionic Beaver (20.04 LTS). Is there a possibility the build for Jammy Jellyfish (22.04 LTS) wasn't tested?
> 
> /cc @ffilz @kalebskeithley

I guess no one is maintaining the nfs-ganesha package on the Ubuntu22.04 branch. @gouthampacha you can build it from source.

**Comment by kalebskeithley** [comment]
packages get built when I have cycles to build them, and if the build breaks, when I have cycles to debug them. Packages are provided as a convenience to the community, but there are no guarantees.

nfs-ganesha-5.9 packages are there now for all supported ubuntu releases from focal on.
