### ISSUE TITLE
How can NFS client enable XATTR features in nfs-ganesha?

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1150]
I see the implementation of operations related to XATTR as follows:
```
	NFS4_OP_GETXATTR = 72,
	NFS4_OP_SETXATTR = 73,
	NFS4_OP_LISTXATTR = 74,
	NFS4_OP_REMOVEXATTR = 75,
```
in nfs-ganesha. However, these OPs are defined in NFSv4.3. So I'm curious about how to enable these features in NFS client.

**Comment by ffilz** [comment]
Really this is a question for the client. I think it may just work using xattr as per other filesystems.

**Comment by zhitaoli-6** [comment]
It seems that Linux kernel with version as 5.9 or newer support extended attributes in NFS v4.2 mounts. Anyone interested in this question can see this [link](https://stackoverflow.com/a/72563477/24520562).
