### ISSUE TITLE
pseudo fsal

### ISSUE THREAD

**Issue by izxl007** [nfs-ganesha/nfs-ganesha#1155]
I don't understand how pseudo fsal works , is there documentation?

**Comment by ffilz** [comment]
There really isn't any documentation other than the code.

What is confusing you?

Fundamentally, FSAL_PSEUDO allows Ganesha to implement a pseudo fs as described in RFC 7530. The purpose is to provide a root node and any directory nodes necessary to reach each export.

Practically, what it implements is a RAM based filesystem that can only contain directories. Ganesha supports automatically creating directories to reach each export.

With the more recent version of Ganesha, rebuilding the pseudofs is supported for any change in exports, adding, removing, or moving from one path to another.

**Comment by ffilz** [comment]
Do you have any more specific questions or can we close this?

**Comment by izxl007** [comment]
yes, it can be closed
