### ISSUE TITLE
wait_to_start_io should signal fd_{work|io}_cond if !open_correct && cant_reopen

### ISSUE THREAD

**Issue by drieber** [nfs-ganesha/nfs-ganesha#1156]
I am thinking specifically about this `wait_to_start_io` return path via `goto out`:
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/commonlib.c#L2405

```
		if (!open_correct(fsal_fd->openflags, openflags)) {
			if (cant_reopen(fsal_fd, may_open, may_reopen)) {
				/* fsal_fd is in wrong mode and we aren't
				 * allowed to reopen, so return EBUSY.
				 */
				PTHREAD_MUTEX_unlock(&fsal_fd->work_mutex);
				/* Use fsalstat to avoid LogInfo... */
				status = fsalstat(ERR_FSAL_DELAY, EBUSY);
				goto out;
			}
                         ....
```

In that scenario the current logic unlocks the work_mutex and returns, but it does not signal fd_work_cond. The scenario is probably rare, but it may explain some deadlocks, for example if some other thread(s) are waiting to do fd work.

Some of the other `wait_to_start_io` return paths do signal fd_work_cond, e.g. https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/commonlib.c#L2483

**Comment by ffilz** [comment]
Ah, good catch. Do you want to submit a patch?

**Comment by drieber** [comment]
I submitted this patch for review:
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1198358

**Comment by drieber** [comment]
EDIT (my previous comment was incomplete):

Another thing I noticed: I think fsal_fd.openflags access is not thread safe. Writes sometimes happen while holding work_mutex, and sometimes without work_mutex. There are reads with & without work_mutex.

Writes:

* I think an open2 by lookup (name!=NULL) with state!=NULL leads to setting fsal_fd.open_flags without holding work_mutex.
* When fsal_complete_io is called with a close_on_complete fsal_fd also writes fsal_fd.open_flags without holding work_mutex, but this one should be safe because it must be acting on a temporary fsal_fd. 
* Other writes of fsal_fd.open_flags seem to all happen while holding work_mutex.

Reads:

* All reads inside reopen_fsal_fd happen while holding work_mutex
* The first cant_reopen call inside wait_to_start_io happens while holding work_mutex
* The second cant_reopen call inside wait_to_start_io happens without work_mutex
* The read of related_fd->openflags inside fsal_start_io happens without work_mutex

**Comment by drieber** [comment]
**UPDATE:
I now see this comment is incorrect: lru_try_one holds fsal_fd_mutex when getting fsal_fd AND incrementing fsal_fd->lru_reclaim. close_fsal_fd calls remove_fd_lru which grabs fsal_fd_mutex, so there is no race condition here. Please ignore the rest of this comment.**

Here is a different issue that *maybe* is the real problem.

First let me say what the real problem is: we are seeing users of our ganesha-based NFS server (with our custom FSAL) report the filesystem deadlocks. Every trace I have seen includes a stack stuck in `fsal_start_fd_work`, waiting on the condition variable, here is one example (but I have seen others):

```
  Thread 0x906e    1000 samples (1-1000)    priority 31 (base 31)
  1000  thread_start + 8 (libsystem_pthread.dylib + 7476) [0x186405d34]
    1000  _pthread_start + 136 (libsystem_pthread.dylib + 28564) [0x18640af94]
      1000  work_pool_thread + 452 (srcfsd_darwin + 5998768) [0x1013808b0]
        1000  svc_rqst_epoll_loop + 720 (srcfsd_darwin + 5972684) [0x10137a2cc]
          1000  svc_rqst_xprt_task_recv + 92 (srcfsd_darwin + 5978292) [0x10137b8b4]
            1000  svc_vc_recv + 1268 (srcfsd_darwin + 5986160) [0x10137d770]
              1000  svc_request + 60 (srcfsd_darwin + 5978556) [0x10137b9bc]
                1000  nfs_rpc_process_request + 2248 (srcfsd_darwin + 4938420) [0x10127dab4]
                  1000  nfs4_Compound + 1160 (srcfsd_darwin + 5017404) [0x101290f3c]
                    1000  process_one_op + 852 (srcfsd_darwin + 5013968) [0x1012901d0]
                      1000  nfs4_op_close + 1340 (srcfsd_darwin + 5079924) [0x1012a0374]
                        1000  _state_del_locked + 2476 (srcfsd_darwin + 5349184) [0x1012e1f40]
                          1000  mdcache_close2 + 76 (srcfsd_darwin + 5749284) [0x101343a24]
                            1000  devtools_srcfs::srcfsn_fsal_close2(fsal_obj_handle*, state_t*) + 176 (srcfsd_darwin + 4445580) [0x10120558c]
                              1000  close_fsal_fd + 60 (srcfsd_darwin + 5673864) [0x101331388]
                                1000  fsal_start_fd_work + 756 (srcfsd_darwin + 5681912) [0x1013332f8]
                                  1000  __psynch_cvwait + 8 (libsystem_kernel.dylib + 18924) [0x1863cd9ec]
                                   *1000  psynch_cvcontinue + 0 (com.apple.kec.pthread + 18232) [0xfffffe000b7ac998]
```

So far I have focused a lot of my attention at `wait_to_start_io`, but now I'm also looking at `close_fsal_fd` and `lru_try_one`. Observation: every lru_try_one iteration (except when fsal_fd is null) results in two calls to `PTHREAD_COND_signal(&fsal_fd_cond)` (first inside close_fsal_fd then in the function body).

Now, a worker thread, say X, may be entering `close_fsal_fd` (with is_reclaiming=false) to close a global fsal_fd because some handle is being released (see for example the implementation of FSAL_VFS release). At exactly that time an `lru_try_one` iteration may be issuing that extra signal on fsal_fd_cond. Now suppose thread X reaches line2121, https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/commonlib.c#L2121  at time T1:

```
fsal_status_t close_fsal_fd(struct fsal_obj_handle *obj_hdl,
			    struct fsal_fd *fsal_fd,
			    bool is_reclaiming)
{
	fsal_status_t status;
	bool is_globalfd = fsal_fd->fd_type == FSAL_FD_GLOBAL;

	status = fsal_start_fd_work(fsal_fd, is_reclaiming);
        ...
	status = obj_hdl->obj_ops->close_func(obj_hdl, fsal_fd);
        ....
	fsal_complete_fd_work(fsal_fd);

	if (is_reclaiming) {
		PTHREAD_MUTEX_lock(&fsal_fd_mutex);
		PTHREAD_COND_signal(&fsal_fd_cond);
		PTHREAD_MUTEX_unlock(&fsal_fd_mutex);
	} else if (is_globalfd) {                                                     <======== LINE 2121
		while (atomic_fetch_int32_t(&fsal_fd->lru_reclaim)) {
			/* Just in case FD LRU is trying to work on this fd,
			 * wait until its done. Note it really won't have
			 * anything to do since we have just closed the fd, but
			 * this assures the lifetime of the fsal_fd is
			 * maintained while LRU does its work.
			 */
			PTHREAD_MUTEX_lock(&fsal_fd_mutex);
			PTHREAD_COND_wait(&fsal_fd_cond, &fsal_fd_mutex);
			PTHREAD_MUTEX_unlock(&fsal_fd_mutex);
		}
	}

	return status;
}
```

At time T2 `lru_try_one` happens to pick up this same global fsal_fd for eviction, and atomically increments `lru_reclaim`: https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/commonlib.c#L1512 (notice lru_try_one holds fsal_fd_mutex while doing this, but most of close_fsal_fd runs without it).

At time T3 thread X continues, sees `lru_reclaim > 0`, grabs fsal_fd_mutex and gets that extra signal (one that was done by a previous lru_try_one iteration). It gets past the condition variable wait, returns a status and thread X releases the memory allocated to this global fsal_fd.

At time T4 the lru_try_one thread reaches this point https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/commonlib.c#L1525 ..... now it is working on memory that has been deallocated.

**Comment by drieber** [comment]
**UPDATE:
I now see this comment is incorrect (see above). Please ignore the rest of this comment.**

BTW, @ffilz and I discussed this erroneous extra signal of `fsal_fd_cond` offline yesterday, but it is not until today that I can make a direct connection between that one the `fsal_start_fd_work` deadlock I am seeing. I am assuming my analysis on the previous posting is correct, obviously I may be wrong.... there are many moving parts here...

**Comment by drieber** [comment]
**UPDATE:
I now see this comment is incorrect: lru_try_one holds fsal_fd_mutex when getting fsal_fd AND incrementing fsal_fd->lru_reclaim. close_fsal_fd calls remove_fd_lru which grabs fsal_fd_mutex, so there is no race condition here. Please ignore the rest of this comment.**

Continuing with my thoughts from 2 posts ago: I think the bug can be explained in a much simpler way: `lru_try_one` can race with another thread that is also closing the global fd, perhaps with one that deletes this global fd!

The `lru_reclaim` field in fsal_fd, the `fsal_fd_cond` condition variable, and the `is_reclaiming` argument to `close_fsal_fd` seem to be there to solve this race condition, but I think the solution is flawed.

**Comment by ffilz** [comment]
Just got back today, will try and look this afternoon

**Comment by drieber** [comment]
I have updated 3 of my previous comments.

One thing that still stands is this: we are seeing users of our ganesha-based NFS server (with our custom FSAL) report the filesystem deadlocks. Every trace I have seen includes a stack stuck in fsal_start_fd_work, waiting on the condition variable, here is one example (but I have seen others):

```
  Thread 0x906e    1000 samples (1-1000)    priority 31 (base 31)
  1000  thread_start + 8 (libsystem_pthread.dylib + 7476) [0x186405d34]
    1000  _pthread_start + 136 (libsystem_pthread.dylib + 28564) [0x18640af94]
      1000  work_pool_thread + 452 (srcfsd_darwin + 5998768) [0x1013808b0]
        1000  svc_rqst_epoll_loop + 720 (srcfsd_darwin + 5972684) [0x10137a2cc]
          1000  svc_rqst_xprt_task_recv + 92 (srcfsd_darwin + 5978292) [0x10137b8b4]
            1000  svc_vc_recv + 1268 (srcfsd_darwin + 5986160) [0x10137d770]
              1000  svc_request + 60 (srcfsd_darwin + 5978556) [0x10137b9bc]
                1000  nfs_rpc_process_request + 2248 (srcfsd_darwin + 4938420) [0x10127dab4]
                  1000  nfs4_Compound + 1160 (srcfsd_darwin + 5017404) [0x101290f3c]
                    1000  process_one_op + 852 (srcfsd_darwin + 5013968) [0x1012901d0]
                      1000  nfs4_op_close + 1340 (srcfsd_darwin + 5079924) [0x1012a0374]
                        1000  _state_del_locked + 2476 (srcfsd_darwin + 5349184) [0x1012e1f40]
                          1000  mdcache_close2 + 76 (srcfsd_darwin + 5749284) [0x101343a24]
                            1000  devtools_srcfs::srcfsn_fsal_close2(fsal_obj_handle*, state_t*) + 176 (srcfsd_darwin + 4445580) [0x10120558c]
                              1000  close_fsal_fd + 60 (srcfsd_darwin + 5673864) [0x101331388]
                                1000  fsal_start_fd_work + 756 (srcfsd_darwin + 5681912) [0x1013332f8]
                                  1000  __psynch_cvwait + 8 (libsystem_kernel.dylib + 18924) [0x1863cd9ec]
                                   *1000  psynch_cvcontinue + 0 (com.apple.kec.pthread + 18232) [0xfffffe000b7ac998]
```

I suspect retries may be involved here, but I am not sure.

**Comment by drieber** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1199063 appears to fix this issue. Here is an argument for why it probably does, with very high likelihood:

In constructs like this: `PTHREAD_MUTEX_dec_int32_t_and_lock(&fsal_fd->io_work, &fsal_fd->work_mutex)`, when using the broken GCC_SYNC_FUNCTIONS functions, we could have two threads about to decrement fsal_fd->io_work. Assume fsal_fd->io_work is 2 to begin with. In some interleavings one thread manages to correctly set fsal_fd->io_work to 1, in such a way that the other thread exits atomic_add_unless_int32_t *WITHOUT* decrementing `fsal_fd->io_work`, but returns true.

NOTE: I also sent https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1198358 for review, but I think it should be revisited. It may be unnecessary or may in fact introduce new bugs.

**Comment by ffilz** [comment]
Closing as done with 6.0 release.
