### ISSUE TITLE
1.2GB memory used by nfs-ganesha in serving write requests with rpc_in_flight as 64

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1159]
Hi, community,

In our practice, when our write workload begins, there are 64 inflight 1MB write requests for nfs-ganesha and it takes up 1.8GB memory(RSS).  After the workload finishes, the memory reduced to 600MB as before.

It's known that there are 128MB data inflight if there are 64 request inflight. However, it does not lead to the 1.2GB in total. I'm curious which part in nfs-ganesha takes up 1.2GB in serving these write requests.

Is this issue known before? What is the possible reason?

<img width="406" alt="image" src="https://github.com/user-attachments/assets/11299b71-ba60-483d-928e-ce1bbf617874">

<img width="406" alt="image" src="https://github.com/user-attachments/assets/95cff616-7162-4c06-85cc-b2038589a05b">

**Comment by ffilz** [comment]
Hmm, with 64 in flight 1 M operations, I would expect a buffer use of 64 M. We know lack of zero-copy results in doubling that. But then we seem to have a 10x on top of that.

Have you tried the latest merge, V6-dev.17 with the zero copy patches in? Maybe there's a path where we use more than double the memory.

**Comment by zhitaoli-6** [comment]
It is because of jemalloc we are using, which is similar with the issue https://github.com/jemalloc/jemalloc/issues/1128

**Comment by ffilz** [comment]
Ah, thanks for checking into that.

**Comment by zhitaoli-6** [comment]
I also submitted a new issue https://github.com/jemalloc/jemalloc/issues/2688 if someone is interested in this case.
