### ISSUE TITLE
ganesha 5.9: Could not get the referral locations

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#1175]
When testing ganesha 5.9 with nfs referrals, we always get the error:

lookup_with_fd :FSAL :EVENT :Could not get the referral locations the path

This happens, because https://github.com/nfs-ganesha/nfs-ganesha/blob/7b6f5b54343dc3de69b2312f206f1f52060ebb78/src/FSAL/FSAL_VFS/handle.c#L217 calls getattrs with fd parameter set to -1 .
This results in a call to https://github.com/nfs-ganesha/nfs-ganesha/blob/7b6f5b54343dc3de69b2312f206f1f52060ebb78/src/FSAL/FSAL_VFS/vfs/attrs.c#L238 function vfs_sub_getattrs  with fd = -1.
In https://github.com/nfs-ganesha/nfs-ganesha/blob/7b6f5b54343dc3de69b2312f206f1f52060ebb78/src/FSAL/FSAL_VFS/vfs/attrs.c#L270-L273 ganesha tries to get the ACL entry for the fd which fails because fd = -1 and exits the function with error.

If I insert
`
if (fd == -1) {
  LogDebug(COMPONENT_FSAL, "fd == -1, must be referral skip acl checking for now");
  goto out;
}
`
before attrs.c line 270 referrals work again.

I didn't try all the previous versions, so I don't know with which code change this error was introduced.

**Comment by ffilz** [comment]
Ah, that was added for FSAL_VFS to support POSIX ACLs in V4.0.9. Can you submit a patch?

**Comment by christmart** [comment]
It was working in 4.0.12 and 4.3. Maybe the call now takes another route.
I'll prepare a patch.

**Comment by christmart** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1201193
