### ISSUE TITLE
Can't mount with NFSv4 from SunOS Solaris 11.3

### ISSUE THREAD

**Issue by aepotapov** [nfs-ganesha/nfs-ganesha#1179]
Hello,
I've got the following  error when mounting nfs-ganesha NFSv4 exports from Solaris:
```
# mount -o vers=4 192.168.122.234:/mnt/nfs_ganesha /mnt/nfs4/
nfs mount: 192.168.122.234:/mnt/nfs_ganesha: No such file or directory
```
Mounting with NFSv3 completes without any problem.
Which debug information will be suitable to diagnose the problem?

Thanks,
Alexey

**Comment by zhitaoli-6** [comment]
Maybe the export doesn't support NFSv4 access. It would be better if you show your ganesha.conf.

**Comment by aepotapov** [comment]
Thank you! Problem was with incorrect ganesha.conf.
