### ISSUE TITLE
ceph fsal 2.4.1: long delay between the file pops up in ls and file content is actually available

### ISSUE THREAD

**Issue by kwaegema** [nfs-ganesha/nfs-ganesha#118]
We synced some data to ceph using cephFS kernel mount to a directory that was exported by Ganesha using cephfs fsal.
Two days later, we saw that we could not see the files synced since the last restart of ganesha.
After restarting ganesha, we saw all the files.
 Is this some kind of caching bug?
We are using ganesha 2.3.2

Thanks!!

**Comment by ffilz** [comment]
Hmm, did the mtime on the directory change from what Ganesha had cached? That would be the primary thing that would cause Ganesha to not realize the directory had changed.

 

Could you try 2.4.0 just in case behavior has changed?

 

Frank

**Comment by kwaegema** [comment]
Indeed, the mtime did not change, since the data was rsynced with -a. The ctime did change though.

We will try 2.4.0 asap. (Should it be fixed then?)

**Comment by dang** [comment]
Only mtime triggers dirent refresh.

**Comment by kwaegema** [comment]
Hi, we tried this with 2.4.1, and it looks like now it gets updated (after a minute or so). 

There is however a long delay (another minute, sometimes more) between the file pops up in ls and when I can actually output the file content:


-bash-4.2$ ls -al
total 6
drwxr-xr-x   1 vsc40605 vsc40605   14 Dec  2 11:28 .
dr-xr-xr-x. 22 root     root     4096 Nov 10 15:16 ..
-rw-r--r--   1 vsc40605 vsc40605    0 Dec  2 11:28 qqqq # file pops up in ls output, but empty

-bash-4.2$ cat qqqq 
-bash-4.2$ cat qqqq 
-bash-4.2$ cat qqqq 
-bash-4.2$ cat qqqq 
-bash-4.2$ cat qqqq 
-bash-4.2$ cat qqqq 
eeee

Which is quite strange

**Comment by ffilz** [comment]
Any further information here?

**Comment by kwaegema** [comment]
Do you need more information from me? Last comment desribes an actual issue.

**Comment by jtlayton** [comment]
If this is reproducible, then it might be interesting to mount the nfs mount using "actimeo=0"  and try reproducing it to see how much of this is dependent on client behavior.

**Comment by ffilz** [comment]
In addition to client side actimeo = 0, could you also try CACHEINODE param Dir_Max = 1 to disable directory caching and CACHEINODE Attr_Expiration_Time = 0 to effectively disable attribute expiration time.

Of course we want to try these options one at a time, and maybe in some combinations.

It would be good to understand if at this point we are seeing expected delay in appearance of new files due to the various aspects of caching.

**Comment by kwaegema** [comment]
Tested this with 2.4.3, still a delay until the file pops up, but the content is available immediately. I can't reproduce the empty file issue, so looks ok
