### ISSUE TITLE
Risk of referencing null pointers in ceph_fsal_open2

### ISSUE THREAD

**Issue by newbeezhc** [nfs-ganesha/nfs-ganesha#1187]
Dear friends,
I think there  is a risk of referencing null pointers here.
Since function open2_by_name and fsal_open2 all pass *obj = NULL as an input parameter of  ceph_fsal_open2, when *new_obj havent been set in ceph_fsal_open2， and function needs to exit in the branch below, it will reference null pointers.
![image](https://github.com/user-attachments/assets/1289512a-799a-4c7c-93fb-2fb77c546112)

https://github.com/nfs-ganesha/nfs-ganesha/blob/e13bc5dae062f4c34780137d9845db2fde7dbccb/src/FSAL/FSAL_CEPH/handle.c#L1653C8-L1653C24

Would you please check this out?

**Comment by bjfhdhhaha** [comment]
I encountered this issue when returning the error stx.stx_mode, and the ganesha process core dumped.

**Comment by newbeezhc** [comment]
Thank you for checking！

**Comment by sachinpunadikar** [comment]
This is fixed in V6.2 via below commit 

commit 59c6edd45835f5900429785ebe327deb9e47ee57
Author: bjfhdhhaha <1453769042@qq.com>
Date:   Fri Oct 18 15:57:07 2024 +0800

    FSAL_CEPH: Fix null pointer reference

    Change-Id: I2eeeb82f6e1fa0243db7102c364362baf9c96068
    Signed-off-by: bjfhdhhaha <1453769042@qq.com>

**Comment by newbeezhc** [comment]
thanks for telling me this! I am closing this issue.
