### ISSUE TITLE
Latency metric  is always 0, exposed with CephFS backend

### ISSUE THREAD

**Issue by cgg102333** [nfs-ganesha/nfs-ganesha#1191]
Sorry, I'm having a problem with my nfs-ganesha v3.5.0 docking cephfs. Sometimes the bandwidth, ops, and latency counts obtained via dbus are normal. But more often only bandwidth and ops are counted and latency is always 0 (which I'm sure is unrealistic).

log:
```
[root@node2 ~]# dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportstats.GetNFSv41IO uint16:1002
method return time=1658978595.486307 sender=:1.954 -> destination=:1.20936
serial=704685 reply_serial=2
boolean true
string "OK"
struct { 
uint64 1658393066
uint64 941802003
}
struct {  //read
uint64 1370  //bytes
uint64 1370  //bytes
uint64 7  //ops
uint64 0
uint64 0  //latency
uint64 0
}
struct {  //write
uint64 319907789  //bytes
uint64 319907789  //bytes
uint64 78112   //ops
uint64 0
uint64 0   //latency
uint64 0
}
```

**Comment by dang** [comment]
3.5 is quite old, and unsupported.  Please try 5.x or 6.0

**Comment by ffilz** [comment]
There are some FSAL metrics that I think include latency that are ONLY used by FSAL_GPFS. See the fsal_extract_stats FSAL method.

**Comment by cgg102333** [comment]
Eventually I solved the issue and the cause of the problem was enabling fast_stats in the parameter configuration. Anyway, thanks for all the suggestions.
