### ISSUE TITLE
NFS ganesha does fsync for every write call?

### ISSUE THREAD

**Issue by npc203** [nfs-ganesha/nfs-ganesha#1199]
strace-ing the main ganesha server PID shows that ganesha is doing "fsync" way too many times. For every byte of write io from client we see 1 fsync being done. 
As our backend filesystem is slow during fsync, most of our bandwidth is lost at fsync-ing.
Is there a way to disable this in ganesha?

**Comment by ffilz** [comment]
What FSAL are you using?

FSAL_VFS only does an fsync on COMMIT operation, or WRITE from the client that is DATA_SYNC or FILE_SYNC or the NFS_Commit EXPORT option has been set TRUE.

**Comment by npc203** [comment]
Thanks, and yep, we're using FSAL_VFS
We haven't set "NFS_Commit" option, it's default value looks to be false.

the write IO sent is simply bufferIO without any O_DIRECT or O_SYNC flag set..
how would I check if my client is mounted with some default file_sync/data_sync option?

**Comment by ffilz** [comment]
One option is to collect a tcpdump trace and verify what mode the writes are, UNSTABLE, FILE_SYNC, or DATA_SYNC.

**Comment by npc203** [comment]
Using a nfsv4 client,
Capturing and looking into the dump from wireshark, I see all the writes having FILE_SYNC4  (in nfs.stable_how4 column). In fact filtering "nfs.stable_how4 != 2" yields empty.

I don't think I've explicitly set this. Any options to not default to file_sync? or change this?

Here's are my nfs mount options
```
 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.214.128.255,local_lock=none,addr=10.214.128.90)
 ```

**Comment by ffilz** [comment]
Yea, I'm not sure how to make the client not do FILE_SYNC4, but that indicates that Ganesha is doing what it's been asked to do.

**Comment by npc203** [comment]
Makes sense, I'll dig in further in the client side.
Thanks for the help

**Comment by YananSunn** [comment]
Hello, I met a similar issue. Have you resolved it? Did you do it by modifying the configuration on the client side, or by other means?

**Comment by ffilz** [comment]
How did you mount on the client?

What system calls is the application making? What is the options used on open system call?
