### ISSUE TITLE
root_squash squashes all groups unlike kernel NFS

### ISSUE THREAD

**Issue by wongma7** [nfs-ganesha/nfs-ganesha#120]
When root_squash is enabled, the groups (alt_groups or secondary groups, i.e. the output of `id -G`) of the user are discarded. I found this post https://sourceforge.net/p/nfs-ganesha/mailman/message/30034244/ which seems to indicate that this is intentional: 
> When root_squash is performed,
   if uid is 0, uid is set to anonymous_uid, gid is set to anonymous_gid,
and alt_groups is set to none

This is different from how the kernel server behaves: if I am root and my uid and gid are squashed but I have a group matching the group associated with a share, I get the directory's group permissions.

Is this difference intentional and if so why? I can give more info about my use-case if wanted

Thanks

**Comment by ffilz** [comment]
Please do give more info on your use case. We did make decisions to do things differently than knifed but I have wondered if we made the right decisions.

**Comment by wongma7** [comment]
I am trying to expose NFS shares to docker containers in a kubernetes cluster and I want to restrict access to the shares to only certain containers/pods. The containers are typically running as "fake" root inside the container and all their uids (& primary gid) are apparently equal to 0 from nfs ganesha's perspective. So the simplest method available to me for differentiating between clients is groups.

I can use a mechanism in docker & kubernetes to make containers have extra groups (supplemental groups) and I can restrict what extra groups each container can have. So I want to be able to: root_squash to prevent every container from getting root privileges in every share, then control access to a share by restricting it to a certain group and selectively handing out membership to that group.

Hope that makes sense!

**Comment by ffilz** [comment]
Ahh, ok, I misread your original message (sorry, was reading it on my iPhone...). What you want is to be able to do root squash but not have the altgroups discarded... I think the best way to handle that would be a new squash mode. I assume there is no way to identify containers as different clients?

**Comment by wongma7** [comment]
Yes, a new squash mode sounds good to me. No, I don't know of any way.

**Comment by ffilz** [comment]
Would you like to try and code up a new squash method? My suggestion is to call it root_id_only. Should be pretty easy. You may still want to squash gid 0 within the gid and altgroups provided.

**Comment by wongma7** [comment]
OK, I will try.

**Comment by wongma7** [comment]
solved by `root_id_squash`!
