### ISSUE TITLE
Couldn't  able mount 

### ISSUE THREAD

**Issue by SudheeshPSuresh** [nfs-ganesha/nfs-ganesha#1208]
**Status:** 

cteng1/sudheesh% sudo systemctl status  nfs-ganesha
● nfs-ganesha.service - NFS-Ganesha file server
     Loaded: loaded (/usr/lib/systemd/system/nfs-ganesha.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2024-12-12 10:50:51 JST; 11min ago
       Docs: http://github.com/nfs-ganesha/nfs-ganesha/wiki
    Process: 13881 ExecStart=/bin/bash -c ${NUMACTL} ${NUMAOPTS} /usr/bin/ganesha.nfsd ${OPTIONS} ${EPOCH} (code=exited, status=0/SUCCESS)
   Main PID: 13882 (ganesha.nfsd)
      Tasks: 278 (limit: 4915)
     CGroup: /system.slice/nfs-ganesha.service
             └─13882 /usr/bin/ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /etc/ganesha/ganesha.conf -N NIV_EVENT

Dec 12 10:50:51 hareesh systemd[1]: Starting NFS-Ganesha file server...
Dec 12 10:50:51 hareesh systemd[1]: Started NFS-Ganesha file server.
cteng1/sudheesh% showmount -e
Export list for hareesh:
cteng1/sudheesh%

**Error:** 

cteng1/sudheesh% sudo mount -t nfs 10.213.132.106://data1/nfs_file/nfs_share /data1/sudheesh/nfs_rec
[sudo] password for root:
mount.nfs: access denied by server while mounting 10.213.132.106://data1/nfs_file/nfs_share

**Logs:**

12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_Start_threads :THREAD :EVENT :Starting delayed e                                                                                xecutor.
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_Start_threads :THREAD :EVENT :9P/TCP dispatcher                                                                                 thread was started successfully
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[_9p_disp] _9p_dispatcher_thread :9P DISP :EVENT :9P dispat                                                                                cher started
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was                                                                                 started successfully
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_Start_threads :THREAD :EVENT :admin thread was s                                                                                tarted successfully
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_Start_threads :THREAD :EVENT :reaper thread was                                                                                 started successfully
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_Start_threads :THREAD :EVENT :General fridge was                                                                                 started successfully
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_start :NFS STARTUP :EVENT :---------------------                                                                                ----------------------------
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_start :NFS STARTUP :EVENT :             NFS SERV                                                                                ER INITIALIZED
12/12/2024 10:50:52 : epoch 675a417b : hareesh : ganesha.nfsd-13882[main] nfs_start :NFS STARTUP :EVENT :---------------------                                                                                ----------------------------
12/12/2024 10:52:22 : epoch 675a417b : hareesh : ganesha.nfsd-13882[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server No                                                                                w NOT IN GRACE

**Comment by zhitaoli-6** [comment]
> cteng1/sudheesh% showmount -e
Export list for hareesh:
cteng1/sudheesh%

It shows that no export is ready. So your mount will fail with EACCES in NFSv3.
