### ISSUE TITLE
ganesha segfaults when removing export

### ISSUE THREAD

**Issue by jlanclos** [nfs-ganesha/nfs-ganesha#121]
Hi,

With ganesha V2.4.0.3, when using ganesha_mgr to remove a ceph export (CEPH FSAL), ganesha segfaults.
Removing an export with VFS FSAL does not result in segfault.

ceph version 10.2.3 (ecc23778eb545d8dd55e2e4735b53cc93f92e65b)

ganesha.nfsd -v
nfs-ganesha compiled on Oct 19 2016 at 10:23:25
Release = V2.4.0.3
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = 0f55a9a97a4bf232fb0e42542e4ca7491fbf84ce
Git Describe = V2.4.0.3-0-g0f55a9a

From dmesg:
[90667.975872] ganesha.nfsd[9770]: segfault at 115 ip 00007f7d43d6887d sp 00007f7c74ef7ad0 error 4 in libcephfs.so.1.0.0[7f7d43c41000+5ab000]

From debug log:
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] unexport :EXPORT :DEBUG :Unexport /srv/home/user2, Pseduo /exports/srv/home/user2
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] nfs_export_get_root_entry :RW LOCK :F_DBG :Got read lock on 0x21cbee0 (&export->lock) at /home/cephadmin/nfs-ganesha/src/support/exports.c:2123
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] nfs_export_get_root_entry :RW LOCK :F_DBG :Unlocked 0x21cbee0 (&export->lock) at /home/cephadmin/nfs-ganesha/src/support/exports.c:2128
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] release_export_root :RW LOCK :F_DBG :Got write lock on 0x21f0380 (&obj->state_hdl->state_lock) at /home/cephadmin/nfs-ganesha/src/support/exports.c:2238
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] release_export_root :RW LOCK :F_DBG :Got write lock on 0x21cbee0 (&export->lock) at /home/cephadmin/nfs-ganesha/src/support/exports.c:2239
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1418
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1425
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] release_export_root :RW LOCK :F_DBG :Unlocked 0x21cbee0 (&export->lock) at /home/cephadmin/nfs-ganesha/src/support/exports.c:2247
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] release_export_root :RW LOCK :F_DBG :Unlocked 0x21f0380 (&obj->state_hdl->state_lock) at /home/cephadmin/nfs-ganesha/src/support/exports.c:2248
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1418
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1425
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] release_export_root :EXPORT :DEBUG :Released root obj 0x21eff68 for path /srv/home/user2 on export_id=2
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1418
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1425
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1443
19/10/2016 10:48:51 : epoch 58079588 : cephadmin : nfs-ganesha-9454[dbus_heartbeat] mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x7cf440 (&(qlane)->mtx) at /home/cephadmin/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1462

Regards,

Jason Lanclos

**Comment by dang** [comment]
Could you post the backtrace?

**Comment by jlanclos** [comment]
[ganesha_remove_export_backtrace.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/540451/ganesha_remove_export_backtrace.txt)

**Comment by dang** [comment]
This appears to be a double release of Ceph's inode for the root.  Not obvious how it happens.

**Comment by jlanclos** [comment]
I've also tried with nfs-ganesha V2.3.3 and ceph firefly (0.80.11).
Ganesha still crashes when removing a ceph export, but does not segfault.

**Comment by jlanclos** [comment]
The crash seems to be caused by ceph_shutdown, I added a debug message before and after the call to ceph_shutdown. When removing an export, only the debug message prior to the call shows in the log.

```
static void release(struct fsal_export *export_pub)
{
        /* The private, expanded export */
        struct export *export =
            container_of(export_pub, struct export, export);

        deconstruct_handle(export->root);
        export->root = 0;

        fsal_detach_export(export->export.fsal, &export->export.exports);
        free_export_ops(&export->export);

        LogDebug(COMPONENT_FSAL,"fsal_ceph release: Calling ceph_shutdown.");
        ceph_shutdown(export->cmount);
        LogDebug(COMPONENT_FSAL,"fsal_ceph release: Call to ceph_shutdown complete");

        export->cmount = NULL;
        gsh_free(export);
        export = NULL;
}
```
```
22/10/2016 08:53:59 : epoch 580b6f6e : nfs : nfs-ganesha-9682[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
22/10/2016 08:53:59 : epoch 580b6f6e : nfs : nfs-ganesha-9682[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
22/10/2016 08:53:59 : epoch 580b6f6e : nfs : nfs-ganesha-9682[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
22/10/2016 08:53:59 : epoch 580b6f6e : nfs : nfs-ganesha-9682[main] nfs_start :THREAD :DEBUG :Wait for admin thread to exit
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] unexport :EXPORT :DEBUG :Unexport /home/user1, Pseduo /exports/home/usr2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] release_export_root_locked :EXPORT :DEBUG :Released root entry 0xc28c30 for path /home/user1 on export_id=2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] pseudo_unmount_export :EXPORT :DEBUG :Unmount /exports/home/usr2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cleanup_pseudofs_node :EXPORT :DEBUG :Checking if pseudo node /exports/home/usr2 is needed
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cih_get_by_key_latched :HT CACHE :DEBUG :cih cache hit slot 24095
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cih_get_by_key_latched :HT CACHE :DEBUG :cih AVL hit slot 7304
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_remove :INODE :DEBUG :usr2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_remove :INODE :DEBUG :cache_inode_remove_cached_dirent usr2 status CACHE_INODE_SUCCESS
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] getattrs :FSAL :DEBUG :Requesting attributes for removed entry 0xc61d30, name=usr2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_kill_entry :INODE :DEBUG :Using cache_inode_kill_entry for entry 0xc62130
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_refresh_attrs :INODE :DEBUG :Failed on entry 0xc62130 CACHE_INODE_ESTALE
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_lru_unref :INODE :DEBUG :LRU_ENTRY_CLEANUP of entry 0xc62130
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[reaper] nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cleanup_pseudofs_node :EXPORT :DEBUG :Checking if pseudo node /exports/home is needed
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cih_get_by_key_latched :HT CACHE :DEBUG :cih cache hit slot 28603
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cih_get_by_key_latched :HT CACHE :DEBUG :cih cache hit slot 24095
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_remove :INODE :DEBUG :home
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cleanup_pseudofs_node :EXPORT :DEBUG :PseudoFS parent directory /exports/home is not empty
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] release :FSAL :DEBUG :Releasing hdl=0xc61d30, name=usr2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_lru_unref :INODE :DEBUG :LRU_ENTRY_CLEANUP of entry 0xc28c30
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] gsh_export_removeexport :EXPORT :INFO :Removed export with id 2
22/10/2016 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] release :FSAL :DEBUG :fsal_ceph release: Calling ceph_shutdown.
```


I also tried changing the call to ceph_release, which prevents the crash, however when running lsof on the ganesha.nfsd pid, it still shows the TCP connections to the mon and mds.

```
22/10/2016 08:46:26 : epoch 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat] cache_inode_lru_unref :INODE :DEBUG :LRU_ENTRY_CLEANUP of entry 0x2731b20
22/10/2016 08:46:26 : epoch 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat] gsh_export_removeexport :EXPORT :INFO :Removed export with id 1
22/10/2016 08:46:26 : epoch 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat] release :FSAL :DEBUG :fsal_ceph release: Calling ceph_release.
22/10/2016 08:46:27 : epoch 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat] release :FSAL :DEBUG :fsal_ceph release: Call to ceph_release complete
22/10/2016 08:46:27 : epoch 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat] fsal_put :FSAL :INFO :FSAL Ceph now unused
22/10/2016 08:46:35 : epoch 580b6da0 : nfs : nfs-ganesha-9058[reaper] nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
22/10/2016 08:46:45 : epoch 580b6da0 : nfs : nfs-ganesha-9058[reaper] nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
^C
root@nfs:/home/cephadmin/nfs-ganesha.build# lsof -p 9058 | grep TCP
ganesha.n 9058 root    5u  IPv4              17478      0t0    TCP nfs:54436->mon:6789 (ESTABLISHED)
ganesha.n 9058 root    6u  IPv4              17479      0t0    TCP nfs:51184->mds:6800 (ESTABLISHED)
ganesha.n 9058 root   24u  IPv6              17495      0t0    TCP *:nfs (LISTEN)
ganesha.n 9058 root   26u  IPv6              17497      0t0    TCP *:44594 (LISTEN)
ganesha.n 9058 root   28u  IPv6              17499      0t0    TCP *:44018 (LISTEN)
ganesha.n 9058 root   30u  IPv6              17501      0t0    TCP *:875 (LISTEN)
ganesha.n 9058 root   32u  IPv6              17656      0t0    TCP *:564 (LISTEN)
```

Additional mon and mds connections are established when re-adding the export and remain when the export is removed.



The shutdown function in libcephfs  closes/deletes the messenger and monclient connections, then the client.  Since the shutdown is being called within FSAL_CEPHFS, could that be what is causing the crash?  Should the call to shutdown happen outside of the FSAL_CEPHFS module to prevent this?

**Comment by jlanclos** [comment]
Here is a better backtrace of the issue with more debug libraries installed.
[ganesha-v2.4.0.3-backtrace.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/551283/ganesha-v2.4.0.3-backtrace.txt)

**Comment by dang** [comment]
On 10/22/2016 10:36 AM, jlanclos wrote:
> The crash seems to be caused by ceph_shutdown, I added a debug message
> before and after the call to ceph_shutdown. When removing an export,
> only the debug message prior to the call shows in the log.
>
> |static void release(struct fsal_export *export_pub) { /* The private,
> expanded export */ struct export *export = container_of(export_pub,
> struct export, export); deconstruct_handle(export->root); export->root =
> 0; fsal_detach_export(export->export.fsal, &export->export.exports);
> free_export_ops(&export->export); LogDebug(COMPONENT_FSAL,"fsal_ceph
> release: Calling ceph_shutdown."); ceph_shutdown(export->cmount);
> LogDebug(COMPONENT_FSAL,"fsal_ceph release: Call to ceph_shutdown
> complete"); export->cmount = NULL; gsh_free(export); export = NULL; } |
>
> |22/10/2016 08:53:59 : epoch 580b6f6e : nfs : nfs-ganesha-9682[main]
> nfs_start :NFS STARTUP :EVENT
> :------------------------------------------------- 22/10/2016 08:53:59 :
> epoch 580b6f6e : nfs : nfs-ganesha-9682[main] nfs_start :NFS STARTUP
> :EVENT : NFS SERVER INITIALIZED 22/10/2016 08:53:59 : epoch 580b6f6e :
> nfs : nfs-ganesha-9682[main] nfs_start :NFS STARTUP :EVENT
> :------------------------------------------------- 22/10/2016 08:53:59 :
> epoch 580b6f6e : nfs : nfs-ganesha-9682[main] nfs_start :THREAD :DEBUG
> :Wait for admin thread to exit 22/10/2016 08:54:09 : epoch 580b6f6e :
> nfs : nfs-ganesha-9682[dbus_heartbeat] get_gsh_export :HT CACHE :DEBUG
> :export_mgr cache hit slot 2 22/10/2016 08:54:09 : epoch 580b6f6e : nfs
> : nfs-ganesha-9682[dbus_heartbeat] unexport :EXPORT :DEBUG :Unexport
> /home/user1, Pseduo /exports/home/usr2 22/10/2016 08:54:09 : epoch
> 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat]
> release_export_root_locked :EXPORT :DEBUG :Released root entry 0xc28c30
> for path /home/user1 on export_id=2 22/10/2016 08:54:09 : epoch 580b6f6e
> : nfs : nfs-ganesha-9682[dbus_heartbeat] pseudo_unmount_export :EXPORT
> :DEBUG :Unmount /exports/home/usr2 22/10/2016 08:54:09 : epoch 580b6f6e
> : nfs : nfs-ganesha-9682[dbus_heartbeat] cleanup_pseudofs_node :EXPORT
> :DEBUG :Checking if pseudo node /exports/home/usr2 is needed 22/10/2016
> 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat]
> cih_get_by_key_latched :HT CACHE :DEBUG :cih cache hit slot 24095
> 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cih_get_by_key_latched :HT CACHE :DEBUG
> :cih AVL hit slot 7304 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cache_inode_remove :INODE :DEBUG :usr2
> 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cache_inode_remove :INODE :DEBUG
> :cache_inode_remove_cached_dirent usr2 status CACHE_INODE_SUCCESS
> 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] getattrs :FSAL :DEBUG :Requesting
> attributes for removed entry 0xc61d30, name=usr2 22/10/2016 08:54:09 :
> epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat]
> cache_inode_kill_entry :INODE :DEBUG :Using cache_inode_kill_entry for
> entry 0xc62130 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cache_inode_refresh_attrs :INODE :DEBUG
> :Failed on entry 0xc62130 CACHE_INODE_ESTALE 22/10/2016 08:54:09 : epoch
> 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat] cache_inode_lru_unref
> :INODE :DEBUG :LRU_ENTRY_CLEANUP of entry 0xc62130 22/10/2016 08:54:09 :
> epoch 580b6f6e : nfs : nfs-ganesha-9682[reaper] nfs_in_grace :STATE
> :DEBUG :NFS Server IN GRACE 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cleanup_pseudofs_node :EXPORT :DEBUG
> :Checking if pseudo node /exports/home is needed 22/10/2016 08:54:09 :
> epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat]
> cih_get_by_key_latched :HT CACHE :DEBUG :cih cache hit slot 28603
> 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cih_get_by_key_latched :HT CACHE :DEBUG
> :cih cache hit slot 24095 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cache_inode_remove :INODE :DEBUG :home
> 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] cleanup_pseudofs_node :EXPORT :DEBUG
> :PseudoFS parent directory /exports/home is not empty 22/10/2016
> 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat]
> release :FSAL :DEBUG :Releasing hdl=0xc61d30, name=usr2 22/10/2016
> 08:54:09 : epoch 580b6f6e : nfs : nfs-ganesha-9682[dbus_heartbeat]
> cache_inode_lru_unref :INODE :DEBUG :LRU_ENTRY_CLEANUP of entry 0xc28c30
> 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] gsh_export_removeexport :EXPORT :INFO
> :Removed export with id 2 22/10/2016 08:54:09 : epoch 580b6f6e : nfs :
> nfs-ganesha-9682[dbus_heartbeat] release :FSAL :DEBUG :fsal_ceph
> release: Calling ceph_shutdown. |
>
> I also tried changing the call to ceph_release, which prevents the
> crash, however when running lsof on the ganesha.nfsd pid, it still shows
> the TCP connections to the mon and mds.
>
> |22/10/2016 08:46:26 : epoch 580b6da0 : nfs :
> nfs-ganesha-9058[dbus_heartbeat] cache_inode_lru_unref :INODE :DEBUG
> :LRU_ENTRY_CLEANUP of entry 0x2731b20 22/10/2016 08:46:26 : epoch
> 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat]
> gsh_export_removeexport :EXPORT :INFO :Removed export with id 1
> 22/10/2016 08:46:26 : epoch 580b6da0 : nfs :
> nfs-ganesha-9058[dbus_heartbeat] release :FSAL :DEBUG :fsal_ceph
> release: Calling ceph_release. 22/10/2016 08:46:27 : epoch 580b6da0 :
> nfs : nfs-ganesha-9058[dbus_heartbeat] release :FSAL :DEBUG :fsal_ceph
> release: Call to ceph_release complete 22/10/2016 08:46:27 : epoch
> 580b6da0 : nfs : nfs-ganesha-9058[dbus_heartbeat] fsal_put :FSAL :INFO
> :FSAL Ceph now unused 22/10/2016 08:46:35 : epoch 580b6da0 : nfs :
> nfs-ganesha-9058[reaper] nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
> 22/10/2016 08:46:45 : epoch 580b6da0 : nfs : nfs-ganesha-9058[reaper]
> nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE ^C
> root@nfs:/home/cephadmin/nfs-ganesha.build# lsof -p 9058 | grep TCP
> ganesha.n 9058 root 5u IPv4 17478 0t0 TCP nfs:54436->mon:6789
> (ESTABLISHED) ganesha.n 9058 root 6u IPv4 17479 0t0 TCP
> nfs:51184->mds:6800 (ESTABLISHED) ganesha.n 9058 root 24u IPv6 17495 0t0
> TCP *:nfs (LISTEN) ganesha.n 9058 root 26u IPv6 17497 0t0 TCP *:44594
> (LISTEN) ganesha.n 9058 root 28u IPv6 17499 0t0 TCP *:44018 (LISTEN)
> ganesha.n 9058 root 30u IPv6 17501 0t0 TCP *:875 (LISTEN) ganesha.n 9058
> root 32u IPv6 17656 0t0 TCP *:564 (LISTEN) |
>
> Additional mon and mds connections are established when re-adding the
> export and remain when the export is removed.
>
> The shutdown function in libcephfs closes/deletes the messenger and
> monclient connections, then the client. Since the shutdown is being
> called within FSAL_CEPHFS, could that be what is causing the crash?
> Should the call to shutdown happen outside of the FSAL_CEPHFS module to
> prevent this?
>

No, this is the correct place to call it.  Either something is wrong in 
the call, or the ceph code to do this is broken somehow.  When I get a 
chance, I'll take a look, if no one else beats me to it.

Daniel

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
