### ISSUE TITLE
Support for NFS4 with mTLS 

### ISSUE THREAD

**Issue by eingemaischt** [nfs-ganesha/nfs-ganesha#1216]
nfs-kernel-server under Linux has beginning with kernel 6.4 the possibility to authenticate and encrypt all nfs traffic with TLS.

It's as simple as installing ktls-utils (under Ubuntu), enable&start tlhsd.service and then fill in key and crt in /etc/tlshd.conf. With mount and export-option xprtsec=tls (server cert checked) or xprtsec=mtls (server and client certs checked against os trust store) it is even possible to make tls obligatory.

Does or will nfs-ganesha support this, too?

The great thing is that this enables admins to encrypt NFS without the need of a complex kerberos infrastructure.

**Comment by ffilz** [comment]
We are now working on it, see #986

**Comment by eingemaischt** [comment]
Ah, sorry, I didn't find that. Thank you!
