### ISSUE TITLE
Some CMake options are ignored (_NO_PORTMAPPER)

### ISSUE THREAD

**Issue by wongma7** [nfs-ganesha/nfs-ganesha#122]
I am not too familiar with CMake, but it looks like it needs to be added to this file to take effect? https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/include/config-h.in.cmake

Will submit a patch to add it there if so.

**Comment by dang** [comment]
You are correct.  I wanted to make some related changes, so I've submitted https://review.gerrithub.io/299488 which should cover this issue.

**Comment by wongma7** [comment]
Thanks!
