### ISSUE TITLE
nfs-ganesha-config.sh missing from Ubuntu 16.04 PPA

### ISSUE THREAD

**Issue by madpsy** [nfs-ganesha/nfs-ganesha#125]
Using ppa:gluster/nfs-ganesha with Ubuntu 16.04

When starting ganesha with the GlusterFS FASL I see the following:

systemd[9158]: nfs-ganesha-config.service: Failed at step EXEC spawning /usr/libexec/ganesha/nfs-ganesha-config.sh: No such file or directory

1) I can't find that file anywhere on the filesystem
2) AFAIK Debian doesn't use /usr/libexec/
3) The source of that script (https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/scripts/nfs-ganesha-config.sh) has RH references such as /etc/sysconfig
4) The package specifies /etc/defaults/nfs-ganesha instead of /etc/default/nfs-ganesha

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by kalebskeithley** [comment]
leave open for now

**Comment by wyllys66** [comment]
This is still an issue for 2.4.2, as ubuntu xenial install base grows, this becomes a bigger problem:

The checks in src/nfs-ganesha.spec-in.cmake set "with_systemd" only for fedora>=15 or rhel>=7 or suse >= 12.  It needs to also check for something that sets this flag on Ubuntu 16 (Xenial) build servers so systemd scripts can work for xenial.

Can "with_systemd" be made into a BCOND_SYSTEMD flag so it can be overridden at build time by cmake?

**Comment by dang** [comment]
No, the spec file is only for making RPMs, so only Fedora, Centos, Suse, and the like.  Making .debs is a different process, and done out-of-tree.

**Comment by wyllys66** [comment]
OK thanks - is there a git repo with instructions and files for building .debs?

**Comment by dang** [comment]
@kalebskeithley builds them on his PPA.

**Comment by kalebskeithley** [comment]
----- Original Message -----
> From: "Daniel Gryniewicz" <notifications@github.com>
> 
> @kalebskeithley builds them on his PPA.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nfs-ganesha/nfs-ganesha/issues/125#issuecomment-275137922

The packaging bits are here

https://github.com/nfs-ganesha/nfs-ganesha-debian

**Comment by kalebskeithley** [comment]
fixed in 2.5.0-3 packages on download.gluster.org and Launchpad PPA
