### ISSUE TITLE
NFS_V4_RECOV_ROOT is not configurable

### ISSUE THREAD

**Issue by wongma7** [nfs-ganesha/nfs-ganesha#127]
Comment here suggests it should be configurable https://github.com/nfs-ganesha/nfs-ganesha/blob/b045dce8ab57114802f4a032c03b87ad84d1b862/src/SAL/nfs4_recovery.c#L1001 . It defaults to /var/lib/nfs/ganesha for me

Should it be a cmake option? 

Thanks.

**Comment by dang** [comment]
It's indirectly configurable, currently, because it's defined as SYSSTATEDIR/lib/nfs/ganesha.  I don't have a problem with a patch to make it directly configurable.

**Comment by wongma7** [comment]
Oh I see, configuring SYSSTATEDIR would work for me. But I am not sure how: changes I make to it in the CMake cache get reverted, I think because SYSSTATEDIR is set to FORCE https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/CMakeLists.txt#L33

**Comment by dang** [comment]
You're right, it's FORCE that's causing it.  I've done some testing, and it seems to work properly without it. https://review.gerrithub.io/303086

**Comment by wongma7** [comment]
thanks!
