### ISSUE TITLE
Cmake overrides SYSCONFDIR and SYSSTATEDIR based on CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by Ferroin** [nfs-ganesha/nfs-ganesha#129]
When trying to configure Ganesha with a non-default CMAKE_INSTALL_PREFIX, SYSCONFDIR and SYSSTATEDIR get overridden by CMake to start with CMAKE_INSTALL_PREFIX.

As an example, I have CMAKE_INSTALL_PREFIX set to /usr/local/stow/nfs-ganesha (I put all software that isn't part of my distro's packaging system in /usr/local, and use GNU Stow to manage things there), and I want SYSCONFDIR to be /etc (because that's where system config files belong regardless of source) and SYSSTATEDIR to be /var (because /usr/local is read-only on my systems most of the time).  When I set these and have CMake configure things, it overrides SYSCONFDIR to /usr/local/stow/nfs-ganesha/etc and SYSSTATEDIR to /usr/local/stow/nfs-ganesha/var.  Even if I manually edit CMakeCache.txt or explicitly set the values on the CMake command-line with -D, they get overridden.

**Comment by dang** [comment]
It 2.5-dev, you can override SYSCONFDIR and SYSSTATEDIR on the command line with -DSYSCONFDIR=/foo/bar.  This has not yet been backported to 2.4.x; if you need it there, feel free to ask on the mailing list, and I'm sure Kaleb will be happy to backport it.

**Comment by Ferroin** [comment]
Ah, I hadn't looked at 2.5-dev yet, glad to see it.  I don't desperately need it backported (it's possible to work around with config and command-line switches to the tools themselves), it just ends up being an annoyance for me because I invariably forget about it each time I'm setting up a new system.

I may try just running a build of 2.5-dev though, I'm pretty used to running bleeding-edge software, and NFS access to the systems I'm using Ganesha on isn't critical (It's nice to have remote file access to them, but I have other methods to move data on and off if NFS doesn't work).

**Comment by dang** [comment]
You can patch in the one patch on your local copy, if you want.  It's this one: 108ab46212c7aac81accd830013cec5f2506e1f2
