### ISSUE TITLE
Unable to create new file on FS mounted through FSAL proxy

### ISSUE THREAD

**Issue by anilchabba** [nfs-ganesha/nfs-ganesha#133]
I am using FASL proxy to mount remote netaap filer to Proxy client
following is my conf file

EXPORT
{
            Export_Id = 77;
            Path = "/nfs_ganesha_test_01/" ;
            Pseudo = /proxy/bbb;
            Access_Type = RW;
            SecType="sys";
            FSAL
            {
                        Name = PROXY;
            }
            Filesystem_id = 10.29;
            Tag = "proxy1_1";
}

PROXY
{
            Remote_Server
            {
                        Srv_Addr= 10.29.16.163;
            }
}

now when i am trying to create new file from client to /nfs_ganesha_test_01/ volume 
i am getting following error
bash-3.00# touch /mnt/proxy/bug
touch: cannot create /mnt/proxy/bug: Invalid argument

following is mount point of /mnt/proxy
10.29.49.251:/nfs_ganesha_test_01
                        48G   7.0G    40G    15%    /mnt/proxy
where 10.29.49.251 is ip where nfs-ganesha is running

i got following error in log
15/12/2016 22:38:43 : epoch 5852edbe : 0 : ganesha.nfsd-11861[work-255] nfs3_FSALattr_To_Fattr :NFS3 :CRIT :Likely bug: FSAL did not fill in a standard NFSv3 attribute: missing 800

point is i ma able to write to exiting file
bash-3.00# echo "test write " >>/mnt/proxy/write_me
bash-3.00# cat /mnt/proxy/write_me
this sis what i wrote
a

test write a
aas
aas
aas
aas
aas
aas
aas
aas
aas
aas
aqwas
aqwas
test write
 i am able to create directory
bash-3.00# mkdir -p /mnt/proxy/bugs/bugs1
bash-3.00# ls /mnt/proxy/bugs/bugs1
bash-3.00# ls -al /mnt/proxy/bugs/bugs1
total 16
drwxr-xr-x   2 root     root        4096 Dec 15  2016 .
drwxr-xr-x   3 root     root        4096 Dec 15  2016 ..
bash-3.00#

only issue as mentioned above is i am unable to create file

i am able to create file on FS mounted directly
10.29.16.163:/nfs_ganesha_test_01
                        48G   7.0G    40G    15%    /test
bash-3.00# touch /test/bugs123
bash-3.00# cat /test/bugs123
bash-3.00# echo "test a bug" >/test/bugs123
bash-3.00# cat /test/bugs123
test a bug

Please suggest what i am doing wrong here

**Comment by anilchabba** [comment]
following Ganesha version i am using
[root@vinfsganeshafinal pesudo]# ganesha.nfsd -v
NFS-Ganesha Release = V2.5-dev-5
nfs-ganesha compiled on Dec 15 2016 at 12:51:35
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = 2bc42861923d3af188e285911938705527008a58
Git Describe = V2.5-dev-5-0-g2bc4286

**Comment by anilchabba** [comment]
falsely close the issue

**Comment by ffilz** [comment]
The CRIT error is occurring because the rawdev attribute isn't provided, however, there is nothing in the code that looks like that itself should actually cause any failures.

If you could collect a network trace (tcpdump -s0 -w /tmp/trace) we might be able to figure out where the failure occurs. It would actually be valuable for that trace to have both the client <-> Ganesha traffic and the Ganesha <-> Netapp traffic.

**Comment by anilchabba** [comment]
Attaching network trace from client <-> Ganesha (traceclientotganesha) and Ganesha <-> Netapp traffic(traceganeshatonetapp) in attached traceclientotganesha.zip

**Comment by anilchabba** [comment]
Hi frank ,
I have send you network trace on you mail id as i am unable to attach tracedump zip file here

**Comment by anilchabba** [comment]
tires on linux ubuntu client get following error
root@vitestnfsproxyclientonlinux:~# touch /mnt/proxy/testubuntulinuxclient
touch: setting times of ‘/mnt/proxy/testubuntulinuxclient’: No such file or directory
root@vitestnfsproxyclientonlinux:~#
is it due to following change
https://github.com/nfs-ganesha/nfs-ganesha/commit/16b0057f1a06ef4f1f7cd4db345e7942418928e8
may be it is skipped in new file operation
earlier i am testing on solaris110 and its giving 
touch: cannot create /mnt/proxy/bug: Invalid argument

**Comment by anilchabba** [comment]
Hi team
I have fix the issue by putting proxy server srcip and one free port in r_addr and it is working fine i am able to now do both read and write
/nfs-ganesha/src/FSAL/FSAL_PROXY/handle.c:850: cbproxy.cb_location.r_addr = "10.29.48.96.156.181";
./nfs-ganesha/src/libntirpc/src/rpcb_clnt.c:1134:#define IN4_LOCALHOST_STRING "10.29.48.96.156.181"
10.29.48.96 i ip and 156.181 is port
I have hard-coded it  src code we can take it from configuration file

**Comment by anilchabba** [comment]
I have now issue with read write performance

**Comment by anilchabba** [comment]
with following configuration i am getting read write latency 10 times more through proxy then direct
EXPORT
{
            Export_Id = 77;
            Path = "/nfs_ganesha_test_01/" ;
            Pseudo = "/proxy/bbb";
           Access_Type = RW;
            #Access_Type = MDONLY;
            Squash = no_root_squash;
            SecType = "sys";
            Disable_ACL = true;
            Protocols = "3", "4" ;
 Anonymous_uid = 0 ;
  Anonymous_gid = 0 ;
            Cache_Data = TRUE ;

            FSAL
            {
                        Name = PROXY;
            }
            Filesystem_id = 10.29;
            Tag = "proxy1_1";
}

PROXY
{
            Remote_Server
            {
                        Srv_Addr= 10.29.16.163;
            }
}

**Comment by anilchabba** [comment]
with following configuration read performance improve dramatically but write is still issue
EXPORT
{
            Export_Id = 77;
            Path = "/nfs_ganesha_test_01/" ;
            Pseudo = "/proxy/bbb";
           Access_Type = RW;
            #Access_Type = MDONLY;
            Squash = no_root_squash;
            SecType = "sys";
            Disable_ACL = true;
            Protocols = "3", "4" ;
 Anonymous_uid = 0 ;
  Anonymous_gid = 0 ;
            Cache_Data = TRUE ;

            FSAL
            {
                        Name = PROXY;
            }
            Filesystem_id = 10.29;
            Tag = "proxy1_1";
}

PROXY
{
            Remote_Server
            {
                        Srv_Addr= 10.29.16.163;
            }
NFSv4
{
        Lease_Lifetime = 600;
        DomainName = defaultv4iddomain.com;
        Delegations = TRUE;
}
CacheInode
{
        Entries_HWMark = 1500000;
        LRU_Run_Interval = 90;
        FD_HWMark_Percent = 60;
        FD_LWMark_Percent = 20;
        FD_Limit_Percent = 90;
}
}

**Comment by anilchabba** [comment]
can you suggest how to improve write performance
