### ISSUE TITLE
vfs_open2() -- "use the global fd to continue" problem

### ISSUE THREAD

**Issue by therealkenc** [nfs-ganesha/nfs-ganesha#135]
I am hitting a problem at [line 405](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/FSAL_VFS/file.c#L405) in `FSAL/VFS/file.c`. There is a local variable `struct vfs_fsal_obj_handle *hdl` that gets initialized to `NULL` at the top of the function, but then isn't assigned before we make it to this line. It's later dereffed when we call vfs_open_my_fd() immediately below and boom.

The test I'm doing is copying the same file destination twice with the nfs-cp sample from libnfs. This is with NFSv3. I am not yet entirely familiar with the ganesha source base, but I get here by way of mdc_open2_by_name(), which calls vfs_open2() with a NULL name at [line 497](https://github.com/nfs-ganesha/nfs-ganesha/blob/4ee0fb128720fb5b3c5cbf2d8c9eee25a7a12f4b/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c#L499) with createmode FSAL_UNCHECKED.

What operation should I do at this point to get the "global fd to continue" per the comment in vfs_open2()?  I see vfs_open_func() which looks promising but before I start mashing keys blindly I thought I should ask. I tried just grabbing `myself->u.file.fd` but that makes vfs_open_my_fd() unhappy because of course it's already open.

**Comment by therealkenc** [comment]
One more data point before I loose my train of thought over Christmas. I rolled back to V2.3-stable, which seems to be the last stable branch that doesn't have the null `hdl` local variable in `vfs_open2()`. The two `nfs-cp` in a row scenario does not segfault on that branch. However, even 2.3 seems to have difficulty with the following sequence:
```
# bar does not exist to start
$ nfs-cp foo nfs://127.0.0.1/home/ken/bar
copied 16 bytes        <--- works both versions
$ nfs-cp foo nfs://127.0.0.1/home/ken/bar
copied 16 bytes        <--- instead server segfaults on V2.5-dev-6
$ rm bar
$ nfs-cp foo nfs://127.0.0.1/home/ken/bar
Failed to creat file /bar: creat call failed with "NFS: CREATE of /foo 
    failed with NFS3ERR_EXIST(-17)"
Failed to open nfs://127.0.0.1/home/ken/bar
# one more try immediately, server seems to sort itself
$ nfs-cp foo nfs://127.0.0.1/home/ken/bar
copied 16 bytes      
```
I can provide ganesha traces if that helps. Basically the client always requests nfs3_create with name 'bar'. On the second time around 'bar' is in the cache, but there does not seem to be a path allowing 'bar' to be subsequently opened with O_CREAT unless it fails first.

**Comment by dang** [comment]
This is a bug, for sure.  I've submitted a potential fix for it here: https://review.gerrithub.io/308164

**Comment by therealkenc** [comment]
@dang Had a chance to actually look at your patch. That's the fix I mentioned in the OP ("...I tried just grabbing `myself->u.file.fd`..."). Doing that subsequently asserts in `vfs_open_my_fd()` because my_fd->fd is not -1.
```
	assert(my_fd->fd == -1
	       && my_fd->openflags == FSAL_O_CLOSED && openflags != 0);
```
And even if you punch though that and say "it's me, just run with the file descriptor we have", it doesn't work because this is a create operation. You could truncate, but that doesn't work either because file might have been deleted server-side and that fd might point to an inode with no dentry. That's where I stopped to ask before trying to make wholesale changes to an unfamiliar code base.

**Comment by dang** [comment]
Hmmm...  I think Frank may need to take a look at this.

**Comment by ffilz** [comment]
Hmm, this patch that I'm working on would also have some application:

https://review.gerrithub.io/300030

However, looking and thinking, we need to be able to do a stateless UNCHECKED create where the global fd is already open, in that case we should actually just return success (though we COULD then check the linkcount and make sure it's non-zero) since a hit on the name with an open fd really implies the file exists. We can't resolve all races with local fs activity without notifications, so the possibility that we have the file open and it's been unlinked locally is something hard to defend against.

I think other bits will help if the file was unlinked, though maybe there would be an issue if our dirent cache is not in sync.

**Comment by dang** [comment]
Okay, I'll work up a patch for that.

**Comment by therealkenc** [comment]
Thanks for taking a look. Understood about the difficulties with respect to local unlink without resorting to inotify. I shouldn't have muddied up the water with that. 

It is possible for client A to unlink the file but hold open the fd; and then client B creates with the same path (possibly but not necessarily with different mode bits and uid). You could `stat()` the path and get the link count, but really what matters is that this is a new inode. Might as well have gone out to `name_to_handle_at()` to see if this is really the inode/handle you expected.

**Comment by ffilz** [comment]
Maybe for unchecked create we should bypass the cache. If we actually have the same file cached, we can simply merge the resulting new fsal_obj_handle with the cached one.

In that way, the file will ALWAYS be created if needed.

**Comment by therealkenc** [comment]
Not sure about "merging" though (to the extent I follow the code). There's still two fsal_obj_handles in the cache, with two open file descriptors with two different handles pointing to two different inodes, until the first one is ejected by normal means. You don't know when client "A" is done with that inode, and can still get handle (but not name) requests from that client.

**Comment by ffilz** [comment]
The merging was in the context of always doing a create even if we think the file already exists. In this case, if the file already exists, the non-exclusive open(O_CREAT) will succeed in opening the existing file, and the result would be a duplicate fsal_obj_handle for the same file object. In this case, there is a merge method that allows the two fsal_obj_handles to be merged (primarily dealing with share reservation stuff, but should also deal with the global file descriptor).

Now if indeed the file had been unlined, and thus a new file is actually created, then the new fsal_obj_handle would reference a different file object than the previous fsal_obj_handle for the file object that used to have that particular file name. In this case, the merge method would not be invoked.

**Comment by ffilz** [comment]
Where do we stand with this one?

**Comment by dang** [comment]
I'm not sure, at this point, what should be done for this.
