### ISSUE TITLE
Duplicate fsids: using device number instead? (Docker OverlayFS)

### ISSUE THREAD

**Issue by wongma7** [nfs-ganesha/nfs-ganesha#140]
I am having some trouble getting Ganesha to export from inside a Docker container using the OverlayFS storage driver. The issue is that `/` of type overlay and docker volumes (bind mounted from host?) appear to have the same fsid, though they have different device numbers. So I can't create exports from `/export` ext4 here because Ganesha discards it as a duplicate of `/`.

I am using a hacky patch to use device.major/minor as fsid.major/minor in "populate_posix_file_systems" and it seems to work, the filesystems get distinguished and exports can be made. Is this a workable idea? Could a preference to do this be offered for cases like this?

Thanks.

```
13/01/2017 02:14:49 : epoch 58783819 : 040ced8773c5 : nfs-ganesha-25[main] posix_create_file_system :FSAL :INFO :Added filesystem / namelen=255 dev=0.48 fsid=0x000000004b2ba8b6.0x0000000043f2afd8 1261152438.1139978200
...
13/01/2017 02:14:50 : epoch 58783819 : 040ced8773c5 : nfs-ganesha-25[main] posix_create_file_system :FSAL :DEBUG :Skipped duplicate /export namelen=255 fsid=0x000000004b2ba8b6.0x0000000043f2afd8 1261152438.1139978200```
```
```
[root@834a1912719d /]# df -T
Filesystem              Type    1K-blocks     Used Available Use% Mounted on
overlay                 overlay 123723748 80797752  36618156  69% /
tmpfs                   tmpfs     8191912        0   8191912   0% /dev
tmpfs                   tmpfs     8191912        0   8191912   0% /sys/fs/cgroup
/dev/mapper/fedora-root ext4    123723748 80797752  36618156  69% /export
shm                     tmpfs       65536        0     65536   0% /dev/shm
```

(I tried to look up what the fsid is and the statfs man page says "Nobody knows what f_fsid is supposed to contain (but see below)."....)

**Comment by ffilz** [comment]
Can we have a Ganesha patch submitted to Gerrithub for this issue for discussion and merging upstream? I'm not sure it's a good idea to maintain a patch outside the Ganesha project.

Note that Ganesha does have a circumstance already where it uses dev.major/minor for fsid and we may just need to tweak when that needs to happen.

**Comment by wongma7** [comment]
OK, sure, I will get started on a proper patch & we can discuss it there. My ugly patch is just to get some people going ASAP and help me debug their issues, a properly reviewed patch would be ideal.

**Comment by wongma7** [comment]
thanks, config option added.
