### ISSUE TITLE
PROXY: cp cannot create regular file 'full_path_to_file' : file exists

### ISSUE THREAD

**Issue by ghost** [nfs-ganesha/nfs-ganesha#141]
While testing v2.5-dev9 (and other recent 2.5 dev builds), I frequently see the message below:
cp cannot create regular file 'full_path_to_file' : file exists

I'm not sure that I have ever seen the error if I don't specify the full destination file name/path.

After the error, a zero byte length file exists for 'full_path_to_file'.

The PC serving the referenced/PROXY file system is running Fedora 24. The Fedora PC is running nfs-ganesha 2.4.1-2.fc24.

**Comment by dang** [comment]
To be clear, you're using FSAL_PROXY, with the proxy server running 2.5-dev, and the original server is running ganesha 2.4?  I assume that one is running FSAL_VFS?

Could you look at the logs of the two machines to see if either of them shows errors?  That would narrow down which machine is originating the error.  (For the record, I can't reproduce with just a single 2.5-dev machine, so my guess at the moment is that it's the PROXY machine).

**Comment by kec200408** [comment]
I am using one physical PC with multiple virtual Oracle VirtualBox PCs for NFS-Ganesha tests. The multiple virtual PCs share a virtual network connection. One virtual PC is configured for Proxy and a different virtual PC is configured for VFS.

The PC serving the referenced/PROXY file system is running Fedora 24. The Fedora PC is running nfs-ganesha 2.4.1-2.fc24 and serving a VFS configuration using the default ganesha.conf file except for the following trivial changes:
Export_Id = 33;
Path = /nfsexport;
Pseudo = /botnfs;

I'll attach the log files (hopefully in a couple minutes).

**Comment by kec200408** [comment]
The end of grace to shutdown period was less than two minutes. The "mdcache_lru_fds_available :INODE LRU :CRIT :FD Hard Limit Exceeded.  Disabling FD Cache and waking LRU thread." is between the end of grace and shutdown but is very close to the shutdown. I suspect it is actually related to the start of shutdown.

I didn't notice anything of interest in the VFS log.

**Comment by kec200408** [comment]
In case you care to see them, I've attached the configuration files.
[ganesha_conf.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/709267/ganesha_conf.zip)
