### ISSUE TITLE
nfs referral support

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#142]
https://github.com/nfs-ganesha/nfs-ganesha/wiki/Referral documents the possibility to configure nfs referrals with nfs-ganesha, but as of version 2.4.1 there seams to be no support for it. The error message is:

config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:33): Unknown parameter (Referral)

https://sourceforge.net/p/nfs-ganesha/mailman/message/32215088/ shows a discussion about this with the prospect, that there might be referral support starting with 2.2.

What is the status?

**Comment by dang** [comment]
It looks like it was never implemented, or at least never submitted.

**Comment by ffilz** [comment]
There was a referral mechanism in Ganesha in 1.5. It has been removed.

Ganesha 2.3 (maybe earlier) does support an fs_locations special attribute, however, only FSAL_GPFS actually implements the plumbing for this.

It would be easy to re-implement the old style referral if trying to store fslocations information in an xattr on the underlying filesystem was undesirable.

**Comment by christmart** [comment]
Am 18.01.2017 um 19:00 schrieb Frank Filz:
> There was a referral mechanism in Ganesha in 1.5. It has been removed.
> 
> Ganesha 2.3 (maybe earlier) does support an fs_locations special
> attribute, however, only FSAL_GPFS actually implements the plumbing for
> this.
> 
> It would be easy to re-implement the old style referral if trying to
> store fslocations information in an xattr on the underlying filesystem
> was undesirable.

It would be really great to see nfs referral support in ganesha.

The referral support in the Linux kernel is somehow suboptimal. We have
a referral server running on Debian wheezy which maps about 50000 user
home directories from different servers into a single namespace. This
needs the same count of bind mount for every referral. These mounts and
umounts take a lot of time. With systemd this is takes fare longer. So
this is no option.

I was hoping that with ganesha the overhead is much less.

I can offer to do at least testing with ganesha referral code or also to
help coding.

Christoph

-- 
============================================================================
Christoph Martin, Leiter Unix-Systeme
Zentrum für Datenverarbeitung, Uni-Mainz, Germany
 Anselm Franz von Bentzel-Weg 12, 55128 Mainz
 Telefon: +49(6131)3926337
 Instant-Messaging: Jabber: martin@uni-mainz.de
  (Siehe http://www.zdv.uni-mainz.de/4010.php)

**Comment by ffilz** [comment]
> Am 18.01.2017 um 19:00 schrieb Frank Filz:
> > There was a referral mechanism in Ganesha in 1.5. It has been removed.
> >
> > Ganesha 2.3 (maybe earlier) does support an fs_locations special
> > attribute, however, only FSAL_GPFS actually implements the plumbing for
> > this.
> >
> > It would be easy to re-implement the old style referral if trying to
> > store fslocations information in an xattr on the underlying filesystem
> > was undesirable.
> 
> It would be really great to see nfs referral support in ganesha.
> 
> The referral support in the Linux kernel is somehow suboptimal. We have
> a referral server running on Debian wheezy which maps about 50000 user
> home directories from different servers into a single namespace. This
> needs the same count of bind mount for every referral. These mounts and
> umounts take a lot of time. With systemd this is takes fare longer. So
> this is no option.
> 
> I was hoping that with ganesha the overhead is much less.
> 
> I can offer to do at least testing with ganesha referral code or also to
> help coding.

The mechanism used by FSAL_GPFS would be easy to copy over to FSAL_VFS.

With this mechanism, you would have your "home" directory with a bunch of empty sub-directories in it. Each sub-directory would have a xattr with the referral destination. There would be no overhead until the referral is accessed, and then that is just a getxattr system call, so should have much less impact than all those bind mounts.

If you wanted to take a stab at the coding that would be wonderful.

I think the following represents all the commits related to fs_locations/referrals:
81fa48836d987ec367cbc5d03090b5ef9a676929
7eec1a273ff95b16b51ca81d0e87b7bc1c57229a
1717ed13750846c3091ab9ba60627fa905d02d39

Frank


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by christmart** [comment]
Hi Frank,

Am 25.01.2017 um 19:45 schrieb Frank Filz:
> 
> The mechanism used by FSAL_GPFS would be easy to copy over to FSAL_VFS.
> 
> With this mechanism, you would have your "home" directory with a bunch
> of empty sub-directories in it. Each sub-directory would have a xattr
> with the referral destination. There would be no overhead until the
> referral is accessed, and then that is just a getxattr system call, so
> should have much less impact than all those bind mounts.
> 
> If you wanted to take a stab at the coding that would be wonderful.

I had a look at it and will try it.

Why was it implemented in FSAL_GPFS instead of FSAL_VFS in the first
place? Is FSAL_VFS not used if GPFS is used? Isn't VFS also used when
accessing GPFS?

Christoph

-- 
============================================================================
Christoph Martin, Leiter Unix-Systeme
Zentrum für Datenverarbeitung, Uni-Mainz, Germany
 Anselm Franz von Bentzel-Weg 12, 55128 Mainz
 Telefon: +49(6131)3926337
 Instant-Messaging: Jabber: martin@jabber.uni-mainz.de
  (Siehe http://www.zdv.uni-mainz.de/4010.php)

**Comment by dang** [comment]
FSAL_VFS is not commonly used outside of testing, since kNFSd is faster for most use cases of exporting a local filesystem.  Other FSALs are shipped in supported products by various compaines (GPFS == IBM, CEPH RGW and GLUSTER == Red Hat, and so on).  IBM needed this feature, so they implemented it in the FSAL they ship.

**Comment by ffilz** [comment]
It's also worth noting FSAL_GPFS predates FSAL_VFS. FSAL_VFS was ported from an iteration of FSAL_GPFS that used only POSIX system calls except for a kernel module to implement open_by_handle. At some point, open_by_handle was absorbed into the GPFS kernel module and FSAL_GPFS also started to depend more on additional special GPFS calls. Meanwhile, open_by_handle made it into the kernel and others saw a benefit of using a POSIX system call FSAL with open_by_handle and FSAL_VFS was derived from the older FSAL_GPFS code.

Since that time, FSAL_GPFS has seen active development utilizing new features while FSAL_VFS has mostly just been a convenient reference and basic testing implementation.

And that's probably more explanation than you needed...

**Comment by christmart** [comment]
Am 25.01.2017 um 19:45 schrieb Frank Filz:
> The mechanism used by FSAL_GPFS would be easy to copy over to FSAL_VFS.
> 
> With this mechanism, you would have your "home" directory with a bunch
> of empty sub-directories in it. Each sub-directory would have a xattr
> with the referral destination. There would be no overhead until the
> referral is accessed, and then that is just a getxattr system call, so
> should have much less impact than all those bind mounts.
> 
> If you wanted to take a stab at the coding that would be wonderful.
> 
> I think the following represents all the commits related to
> fs_locations/referrals:
> 81fa48836d987ec367cbc5d03090b5ef9a676929
> 7eec1a273ff95b16b51ca81d0e87b7bc1c57229a
> 1717ed13750846c3091ab9ba60627fa905d02d39

I am in the middle of coding. I now have a function check_fs_location
for VFS and get the server location and the path from the extended
attributes.

What I am missing is the rootpath to return in the fs_location call. If
I understand this correctly the root path is the path for which the
getxattr call is issued where the referral should be returned. As
parameter to the function I get only a filehandle to the respective
directory.

Is there any place or method how I can get the original path?

Christoph

-- 
============================================================================
Christoph Martin, Leiter Unix-Systeme
Zentrum für Datenverarbeitung, Uni-Mainz, Germany
 Anselm Franz von Bentzel-Weg 12, 55128 Mainz
 Telefon: +49(6131)3926337
 Instant-Messaging: Jabber: martin@jabber.uni-mainz.de
  (Siehe http://www.zdv.uni-mainz.de/4010.php)

**Comment by ffilz** [comment]
Marc, could you take a look at this and help us understand how FSAL_GPFS handles fs_locations?

**Comment by eshelmarc** [comment]
If you set on the the sticky bit on a directory Ganesha will return 
NFS4ERR_MOVED to getattr request, this return code will trigger the NFS 
client to request for fs_locations in its next getattr call and if the 
FSAL is supporting the fs_locations method like FSAL_GPFS does, you can 
return the new or alternative location of the file system.
Marc.

**Comment by christmart** [comment]
the fs_locations information is retrieved for FSAL_GPFS via a GPFS ioctl
which sets the struct fs_loc completely including the root path for the
struct fs_location4.

For vfs I have to get this information using some other way.

Christoph


-- 
============================================================================
Christoph Martin, Leiter Unix-Systeme
Zentrum für Datenverarbeitung, Uni-Mainz, Germany
 Anselm Franz von Bentzel-Weg 12, 55128 Mainz
 Telefon: +49(6131)3926337
 Instant-Messaging: Jabber: martin@jabber.uni-mainz.de
  (Siehe http://www.zdv.uni-mainz.de/4010.php)

**Comment by ffilz** [comment]
Ah, ok, had to read up on fs_locations...

The fs_root path really needs to be constructed by Ganesha given the construction of the pseudo fs.

The old mechanism where each referral had an export of course had a Pseudo path for that export which was thus the fs_root.

The correct mechanism would be to do lookupp from the node in question until one finds the root of an export from which the Pseudo path can be taken, but then it may be tricky to reconstruct the path within the export.

Hmm, it would at least make the brute force search easier since you would have inode numbers of each directory, you could do readdir of each parent directory until you find the next path element, then readdir THAT directory...

So if you are searching for /export/export1/some/path/to/referral

First lookupp finds handle of to
then next finds handle of path
then some
then export1 - root of export found, so the path so far is "/export/export1" (assuming the Pseudo for export1 is "/export/export1).
Then readdir in export1 until you find the inode corresponding to some, append "some/" to path.
Then readdir in some until you find path's inode, append "path/"
Then readdir in path until you find to's inode, append "to/"
Then final readdir in to find's the inode for referral and you append "referral"
And done, you have dynamically constructed the path

Another option might be to put the path into the xatttr...

And a final option would be to re-implement the original export based referrals...

**Comment by christmart** [comment]
I think about storing the directory name and the path in
vfs_fsal_obj_handle in the u union in function alloc_handle to not have
to do syscalls with directory traversal in every referral call.

Christoph

**Comment by dang** [comment]
The problem with this is that an obj_handle represents an inode, which is not associated with a path.  It can be moved while open, or have multiple paths to reach it, so storing it's patch in it will be guaranteed to be wrong sometimes.

**Comment by ffilz** [comment]
Also, storing the referral information in the vfs_obj_handle may prevent it from being updated when the value is changed in the underlying filesystem.

Referrals should only be directory entries, so there WILL only be a single path to them

**Comment by ffilz** [comment]
we COULD cache the fs_location4 attribute in MDCACHE with appropriate invalidation checks...

**Comment by christmart** [comment]
Is the GPFS referral code really working? I think the code in
nfs_proto_tools.c function encode_fs_locations is wrong.

The comment says:

/* For now allow for one fs locations, fs_locations() should set:
	   root and update its length, can not be bigger than MAXPATHLEN
	   path and update its length, can not be bigger than MAXPATHLEN
	   server and update its length, can not be bigger than MAXHOSTNAMELEN
	*/

RFC 7530 ( and nfs4.x) say

typedef component4      pathname4<>;

so pathname4 is defined as an *array* of component4 types which are
strings and not only one string.

Looking into a tcpdump of nfs-kernel-server a referral or root_path is
delivered as components of the actual path. That is, a path

/path/to/referral

is coded as the three components "path", "to" and "referral" and not one
component "/path/to/referral".

the GPFS code in fsal_attrs.c is only setting one component from the
result of gpfs_ganesha.

My code for VFS referrals returning the paths in one component does not
work on the client.

So I think I have to redesign the handling of component4.

Christoph

**Comment by eshelmarc** [comment]
It used to work when I tried it long time ago, if you think that it not 
compliant with the spec please go a had and fix it. GPFS is not using this 
feature currently.
Marc.

**Comment by christmart** [comment]
> Am 02.02.2017 um 20:42 schrieb eshelmarc <notifications@github.com>:
> 
> It used to work when I tried it long time ago, if you think that it not 
> compliant with the spec please go a had and fix it. GPFS is not using this 
> feature currently. 
> Marc. 

To fix that I need the specifications for the kGanesha ioctl s.

**Comment by eshelmarc** [comment]
I did not mean that you should fix the GPFS code, you should fix the 
Ganesha common code with whatever FSAL you want to support, or you can 
extend the export configuration to allow for alternative fs-locations.

**Comment by christmart** [comment]
After analyzing the code and programming for a while I now have some working code. I hat to introduce some dynamic memory management for the fs_locations structure and find a good place to introduce the code which checks for the extended attributes which hold the referral for the directory. I choose to use the attribute user.exportid with a value in the form of server:/path .

The tricky part was to find out, that the protocol requests the fsid to be different for a referral. I choose the calculate a hash of the referral stored in the extattr and give this back as fsid.

The attached patch is working for ganesha version 4.2.0. 

Christoph
[20-vfs-fslocation-patch.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/821808/20-vfs-fslocation-patch.txt)

**Comment by christmart** [comment]
Of course I mean 2.4.0 instead of 4.2.0

**Comment by ffilz** [comment]
Could you base this patch on V2.5 and push to Gerrithub for review.

One option might be to specify fsid in the xattr (or maybe have an optional xattr for fsid) so the user could specify the fsid that the referral server will use, though not sure if that actually matters.

Certainly a hash is a good automatic fsid.

**Comment by christmart** [comment]
I cloned it to christmart/nfs-ganesha and published the patches. The changes are in https://review.gerrithub.io/351750

**Comment by moschlar** [comment]
I just found this issue still open - isn't the NFS referral code merged yet?

**Comment by dang** [comment]
There is referral support for VFS in.  It doesn't exactly match this patch, however.

**Comment by ffilz** [comment]
I'm going to close this. Something to this effect went into V2.5-dev.21 and then there has been fixes in V2.6-rc3, V2.7-dev.3 and V2.7-dev.10.
