### ISSUE TITLE
nfs-ganesha`s rsize ,wrize block size and Linux 3.10 kernel`s NFSSVC_MAXBLKSIZE

### ISSUE THREAD

**Issue by zanglinjie** [nfs-ganesha/nfs-ganesha#143]
The following definitions  in Linux 3.10 kernel :
#define NFSSVC_MAXBLKSIZE       RPCSVC_MAXPAYLOAD
#define RPCSVC_MAXPAYLOAD	(1*1024*1024u)
when I mount nfs-ganesha vers=3 ,the rsize ,wrize block size is only 256k , not 1M .
How it happen?

**Comment by zanglinjie** [comment]
In kernel NFS(MEM 1G) ：
cat /proc/fs/nfsd/max_block_size
131072 (128k)
In user space ganesha(Mem 125G) ：
cat /proc/fs/nfsd/max_block_size
0
why?

**Comment by ffilz** [comment]
Ganesha as a user space NFS server does not have access to /proc/fs/nfsd...

**Comment by zanglinjie** [comment]
Thanks @ffilz  for pointing this.
Many thanks for your kind help.

**Comment by zanglinjie** [comment]
hello@ffilz
my version :centos 7.2 kerner 3.10  nfs-ganesha-v2.3-ceph
 block size problem is not solved......
https://www.mail-archive.com/nfs-ganesha-devel@lists.sourceforge.net/msg02297.html
But the highest size of the block is always 256k. Is there some way to increase my block size?

**Comment by dang** [comment]
These are set with the MaxRead and MaxWrite Export parameters.
