### ISSUE TITLE
FSAL Version

### ISSUE THREAD

**Issue by marekk1717** [nfs-ganesha/nfs-ganesha#147]
I'm trying to register fsal library but it ends with the following error
"register_fsal :NFS STARTUP :CRIT :FSAL "TDFS" failed to register because of version mismatch core = 4.0, fsal = 3.0"

what does it exactly mean ? should I install older version of nfs-ganesha ?

**Comment by ffilz** [comment]
What FSAL are you using? How did you install it and Ganesha?

If you are using an out of tree FSAL, you should make sure you use the version of Ganesha the FSAL is intended to be used with. If using an in tree FSAL, make sure you either build everything from one source, or use matching packages.

Based on the "TDFS" I suspect an out of tree FSAL, Please note our ability to support out of tree FSALs is limited...

**Comment by dang** [comment]
To elaborate:  The FSAL API is versioned.  We update the version every time we break ABI on the FSAL.  This means that you must use your FSAL library against a Ganesha with the same FSAL API version as your FSAL was built with.

So, use the same Ganesha you built against, or rebuild your FSAL against the newer Ganesha.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
