### ISSUE TITLE
FSAL_RGW inconsistent fsid causing nfs client automount

### ISSUE THREAD

**Issue by guihecheng** [nfs-ganesha/nfs-ganesha#149]
Hi, all

I found that FSAL_RGW tends to trigger automount from the nfs client when there are multiple exports created.
The scenario is as follows:
1. add export path=/     (id=1)         //  this does rgw_mount(), RGWLibFS instance created with fs_inst = 1
2. mount export 1 && mkdir /b1    //  make a bucket to mount 
3. add export path=/b1 (id=2)        //  rgw_mounte(), RGWLibFS instance with fs_inst = 2
4. mount export 2 && mkdir under this export /dir1 (actually /b1/dir1)
5. do lookup under /dir1 (e.g. ls <mountpoint>/dir1)
then we get an extra mountpoint under /etc/mtab.

After some debugging, I found that it is an fsid consistency that triggers automount of nfs client.
Actually, FSAL_RGW is using fs_inst from librgw as fsid, which is a static in-memory counter, increasing upon every rgw_mount() call.
When an export is created, the fs_inst is encoded in an fh.
When we do lookup under /b1/dir1, nfs client found /b1 with fsid = 1 in its fh and fsid = 2 with /b1/dir1,
then nfs client decides to do an automount.

AFAICU, fs_inst got increased per every rgw_mount(), so multiple buckets exported could serve as different fs instances to users. But rgw_mount() seems to lack some persistency work?

Also, at present, as we found, if we do a stop & start and recreat export for /b1, then fs_inst restart from 1 again, then some automount will happen, too.

Any suggestions on how to fix this one? Or, do I miss anything?

cc @mattbenjamin

**Comment by ffilz** [comment]
What code versions are you using? This should be fixed with recent code.

**Comment by guihecheng** [comment]
nfs-ganesha branch next; HEAD at V2.5-dev-16(7808ba522fdd9e42747e698e7d1acb7ef09df7a7)
ceph branch master;         HEAD at (8786b4c8fe27a9ed9a685dce1283c279ad418832)

BTW,
There is a patch fixing a similar problem:
rgw_file: fix spurious mount entries w/Linux NFS client(d929ba0c5b8671150ebe1ab9057836b0fa6dadea)

But actually they are different ones.

**Comment by mattbenjamin** [comment]
I'm not sure this is a bug at this point.  I definitely don't think fsid should be persisted.  Maybe it should be handled entirely from fsal and export config?

**Comment by dang** [comment]
@mattbenjamin I think @guihecheng may be right here.  Maybe something like this:

```
diff --git a/src/rgw/rgw_file.h b/src/rgw/rgw_file.h
index 9cc55ac..def5b58 100644
--- a/src/rgw/rgw_file.h
+++ b/src/rgw/rgw_file.h
@@ -945,7 +945,7 @@ namespace rgw {
          fh->mtx.unlock(); /* ! LOCKED */
       } else {
        /* make or re-use handle */
-       RGWFileHandle::Factory prototype(this, get_inst(), parent, fhk,
+       RGWFileHandle::Factory prototype(this, root_fh.state.dev, parent, fhk,
                                         obj_name, CREATE_FLAGS(flags));
        fh = static_cast<RGWFileHandle*>(
          fh_lru.insert(&prototype,
```

**Comment by mattbenjamin** [comment]
@dang that would be harmless, but does it yield a different fs instance?

**Comment by dang** [comment]
It means that all the handles for a given export/mount have the same FSID.  The way it is now, all handles created after the next mount will have incremented FSIDs, so not the same as the root handle.  And each time there's a new mount, FSIDs increment again.

**Comment by mattbenjamin** [comment]
@dang the get_inst() method of RGWLibFS is supposed to be returning its stable instance, not the current value of the instance counter;  I think I'd prefer to fix that, rather than point to the root (though that would be ok)

**Comment by dang** [comment]
So maybe this:

```
diff --git a/src/rgw/rgw_file.h b/src/rgw/rgw_file.h
index 9cc55ac..178bd83 100644
--- a/src/rgw/rgw_file.h
+++ b/src/rgw/rgw_file.h
@@ -762,7 +762,7 @@ namespace rgw {
 
     RGWLibFS(CephContext* _cct, const char *_uid, const char *_user_id,
            const char* _key)
-      : cct(_cct), root_fh(this, get_inst()), invalidate_cb(nullptr),
+      : cct(_cct), root_fh(this, ++fs_inst), invalidate_cb(nullptr),
        invalidate_arg(nullptr), shutdown(false), refcnt(1),
        fh_cache(cct->_conf->rgw_nfs_fhcache_partitions,
                 cct->_conf->rgw_nfs_fhcache_size),
@@ -770,9 +770,6 @@ namespace rgw {
               cct->_conf->rgw_nfs_lru_lane_hiwat),
        uid(_uid), key(_user_id, _key) {
 
-      /* fixup fs_inst */
-      root_fh.state.dev = ++fs_inst;
-
       /* no bucket may be named rgw_fs_inst-(.*) */
       fsid = RGWFileHandle::root_name + "rgw_fs_inst-" +
        std::to_string(fs_inst);
@@ -1069,7 +1066,7 @@ namespace rgw {
 
     struct rgw_fs* get_fs() { return &fs; }
 
-    uint32_t get_inst() { return fs_inst; }
+    uint32_t get_inst() { return root_fh.state.dev; }
 
     RGWUserInfo* get_user() { return &user; }
```

**Comment by mattbenjamin** [comment]
Yeah, just pushed:
https://github.com/ceph/ceph/pull/13832

**Comment by guihecheng** [comment]
@dang @mattbenjamin Thanks, I am testing the patch.
(Actually, I've tried a similar way, but it failed, hoping this makes a difference.)

**Comment by guihecheng** [comment]
I think the patch is good for rgw_file, but don't solve my problem completely.
There is some thought of mine in nfs-ganesha FSAL_RGW:
https://review.gerrithub.io/#/c/351984/
This commit together with the commit from matt solves my problem here, please help review it.

**Comment by guihecheng** [comment]
But actually I've got another problem as I raised at the end of the first post.
If nfs-ganesha is killed and restarted, and I just add the second export under cmdline, then fs_inst_counter starts again from 1, but who knows what is inside the filehandles of all the files and directories already there in that export?

**Comment by mattbenjamin** [comment]
Hi,

Thanks for your work and feedback on this.

Our thinking to this point is that clients will refresh their view of the export.  RGW has atomicity, so if a client was actually attempting a mutating change, it either took effect completely, or "never happened."

The fact that filehandles are intrinsically stable makes it conceivable that we could make this information part of HA configuration, though, which will help, but we can't completely assure that some or all handles will not go stale, as handles are not indexed in the cluster.

Regards,

Matt

----- Original Message -----
> From: "Gui Hecheng" <notifications@github.com>
> To: "nfs-ganesha/nfs-ganesha" <nfs-ganesha@noreply.github.com>
> Cc: "Matt Benjamin" <mbenjamin@redhat.com>, "Mention" <mention@noreply.github.com>
> Sent: Thursday, March 9, 2017 1:18:22 AM
> Subject: Re: [nfs-ganesha/nfs-ganesha] FSAL_RGW inconsistent fsid causing nfs client automount (#149)
> 
> But actually I've got another problem as I raised at the end of the first
> post.
> If nfs-ganesha is killed and restarted, and I just add the second export
> under cmdline, then fs_inst_counter starts again from 1, but who knows what
> is inside the filehandles of all the files and directories already there in
> that export?
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nfs-ganesha/nfs-ganesha/issues/149#issuecomment-285265465

-- 
Matt Benjamin
Red Hat, Inc.
315 West Huron Street, Suite 140A
Ann Arbor, Michigan 48103

http://www.redhat.com/en/technologies/storage

tel.  734-821-5101
fax.  734-769-8938
cel.  734-216-5309
