### ISSUE TITLE
compile error in nfs_dupreq.c

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#150]
While trying to build next branch I get errors. I used

cmake -DBUILD_CONFIG=debian -DCMAKE_BUILD_TYPE=Debug -DUSE_FSAL_NULL=YES -DUSE_FSAL_ZFS=NO -DUSE_FSAL_XFS=YES -DUSE_FSAL_CEPH=NO -DUSE_FSAL_RGW=NO -DUSE_FSAL_GPFS=YES -DUSE_FSAL_PANFS=NO -DUSE_FSAL_GLUSTER=YES -DUSE_SYSTEM_NTIRPC=ON -DUSE_9P_RDMA=NO -DUSE_LTTNG=NO -DUSE_ADMIN_TOOLS=YES -DUSE_GUI_ADMIN_TOOLS=YES -DUSE_FSAL_VFS=ON -DUSE_FSAL_PROXY=ON -DUSE_DBUS=ON -DUSE_9P=ON -DDISTNAME_HAS_GIT_DATA=OFF /data/martin/ganesha.gerrit/src/

/data/martin/ganesha.gerrit/src/RPCAL/nfs_dupreq.c: In function 'get_drc_type':
/data/martin/ganesha.gerrit/src/RPCAL/nfs_dupreq.c:354:18: error: 'req->rq_msg' is a pointer; did you mean to use '->'?
   if (req->rq_msg.cb_vers == 4)
                  ^
                  ->
/data/martin/ganesha.gerrit/src/RPCAL/nfs_dupreq.c: In function 'nfs_dupreq_start':
/data/martin/ganesha.gerrit/src/RPCAL/nfs_dupreq.c:1022:35: error: 'req->rq_msg' is a pointer; did you mean to use '->'?
   dk->hin.tcp.rq_xid = req->rq_msg.rm_xid;
                                   ^
                                   ->
/data/martin/ganesha.gerrit/src/RPCAL/nfs_dupreq.c:1024:32: error: 'req->rq_msg' is a pointer; did you mean to use '->'?
   dk->hin.rq_prog = req->rq_msg.cb_prog;
                                ^
                                ->
/data/martin/ganesha.gerrit/src/RPCAL/nfs_dupreq.c:1025:32: error: 'req->rq_msg' is a pointer; did you mean to use '->'?
   dk->hin.rq_vers = req->rq_msg.cb_vers;

What am I doing wrong?
Christoph

**Comment by dang** [comment]
I believe your system ntirpc is too old.  In general, the -dev versions of Ganesha will need development versions of ntirpc as well.  These are not yet packaged by distros.  The simplest way to get this is to use the sub-module version (build without -DUSE_SYSTEM_NTIRPC=ON).  The alternative is that you'll have to create your own newer libntirpc package with at least version 4339bec669e42e6d26aa30fec594f9c7c1704018

A new version of libntirpc is about to be tagged and released, so packages for it should make it into new distros (like Fedora 25) some time in the next few weeks.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
