### ISSUE TITLE
How to find out what causes nfs-ganesha being killed?

### ISSUE THREAD

**Issue by panho66** [nfs-ganesha/nfs-ganesha#156]
I have a working version of GlusterFS 3.8 and nfs-Ganesha 2.4.1 with nfs client in red-hat kernel 6.4

After kernel upgrade to 6.8 in nfs-client node, application failover causing nfs-ganesha being killed. 

The application failover is active application component  release nfs file lock and shutting down. The standby application component in another node which checking the lock file every 2s and starting up as active.

Mar 24 10:08:24 pmc71dev1949 dbus[761]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)
Mar 24 10:08:24 pmc71dev1949 dbus-daemon: dbus[761]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)
Mar 24 10:08:24 pmc71dev1949 dbus[761]: [system] Successfully activated service 'org.freedesktop.problems'
Mar 24 10:08:24 pmc71dev1949 dbus-daemon: dbus[761]: [system] Successfully activated service 'org.freedesktop.problems'
Mar 24 10:08:27 pmc71dev1949 su: (to root) cloud-user on pts/0
Mar 24 10:08:52 pmc71dev1949 kernel: ganesha.nfsd[16177]: segfault at 40 ip 00007f1390bbf9e7 sp 00007f12fff3dd60 error 4 in ganesha.nfsd[7f1390aa1000+176000]
Mar 24 10:08:52 pmc71dev1949 abrt-hook-ccpp: Process 15967 (ganesha.nfsd) of user 0 killed by SIGSEGV - dumping core
Mar 24 10:08:55 pmc71dev1949 abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Mar 24 10:08:55 pmc71dev1949 systemd: nfs-ganesha.service: main process exited, code=killed, status=11/SEGV
Mar 24 10:08:55 pmc71dev1949 systemd: Unit nfs-ganesha.service entered failed state.
Mar 24 10:08:55 pmc71dev1949 systemd: nfs-ganesha.service failed.
Mar 24 10:08:55 pmc71dev1949 abrt-server: Package 'nfs-ganesha' isn't signed with proper key
Mar 24 10:08:55 pmc71dev1949 abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2017-03-24-10:08:52-15967' exited with 1
Mar 24 10:08:55 pmc71dev1949 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2017-03-24-10:08:52-15967'
Mar 24 10:09:02 pmc71dev1949 crmd[26346]:  notice: Result of notify operation for nfs-grace on pmc71dev1949.auiag.corp: 0 (ok)
Mar 24 10:09:02 pmc71dev1949 crmd[26346]:  notice: Result of stop operation for nfs-grace on pmc71dev1949.auiag.corp: 0 (ok)
Mar 24 10:09:07 pmc71dev1949 IPaddr(pmc71dev1949.auiag.corp-cluster_ip-1)[18321]: INFO: IP status = ok, IP_CIP=
Mar 24 10:09:08 pmc71dev1949 crmd[26346]:  notice: Result of stop operation for pmc71dev1949.auiag.corp-cluster_ip-1 on pmc71dev1949.auiag.corp: 0 (ok)
Mar 24 10:09:09 pmc71dev1949 ntpd[818]: Deleting interface #35 eth1, 10.139.136.48#123, interface stats: received=0, sent=0, dropped=0, active_time=61548 secs

**Comment by thotz** [comment]
To get coredump set following configuration optionsc in RHEL machines
Also set the ulimit -C "unlimited"

Update the /etc/abrt/abrt-action-save-package-data.conf file and set following variables.

OpenGPGCheck = no
ProcessUnpackaged = yes

Restart the abrtd daemon - as root - for the new settings to take effect:

# service abrtd restart

Note that abrt-1.* has these variables set in file /etc/abrt/abrt.conf.

Another reason might be this bug https://bugzilla.redhat.com/show_bug.cgi?id=1259402

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
