### ISSUE TITLE
posix style parent directory permission check seems weak

### ISSUE THREAD

**Issue by guihecheng** [nfs-ganesha/nfs-ganesha#157]
As we test through some FSALs: xfs, ext4, cephfs, rgw
We find that FSAL_XFS, _EXT4 have posix-style permission checks, while _CEPHFS, _RGW do not.
(Mainly some fs namespace operations: create, unlink, mkdir, rmdir, rename)

As we found, _XFS and _EXT4 actually relies glibc calls to do the permission checks,
while _CEPHFS, _RGW use there own libs.

Also, there is a comment in src/FSAL/fsal_helper.c:
> 837         /* Permission checking will be done by the FSAL operation. */

So, as we understand, we should do permission checks in libcephfs, librgw, etc.
But why not do generic checks using fsal_access (perhaps in the corresponding fsal_helpers)?

cc @dang

**Comment by dang** [comment]
Which checks in particular?  We've generally left many checks to FSALs, 1) because they can likely do them more efficiently, 2) because they are likely being done already, so duplicating the checks is unnecessary, and 3) the checks require up-to-date attributes, and getattr() can be expensive, as discovered during the early 2.4 cycle with gluster.

If there's checks missing in Ceph and RGW, we will need to add them somehow.

**Comment by ffilz** [comment]
The biggest reason directory permission checks for operations that change directories (create, mknod, symlink, link, rename, and unlink) are left to the FSAL is that Ganesha can not guarantee atomicity of permission check and operation.

This is particularly insidious on rename where a client rename could race with a rename external to Ganesha that replaces the target file (that would be deleted, and was owned by the Ganesha client owner) with a file owned by someone else. The result would be that a Ganesha client could delete a file owned by someone else. There is one or two more insidious scenarios.

The basic structure we thus have is that Ganesha should not grant permission to something the client user did not at least at one point have permission. Thus any races that remain are ones that could be won by the client owner no matter what atomicity we had. For example, if a user was allowed to read a file and attempted to read at the same time the file owner tried to close a permission hole, all we do by relying on possibly stale permission attributes is slightly extend the window of vulnerability, we don't create a new vulnerability.

**Comment by guihecheng** [comment]
@dang @ffilz thanks for explanations, the points are very clear.
