### ISSUE TITLE
ClientMgr dBus API should map exports to IP addresses if possible

### ISSUE THREAD

**Issue by wyllys66** [nfs-ganesha/nfs-ganesha#158]
Not sure if this is possible, but it would be nice if there was a way to see which exports are mounted by which client IP addresses, i.e a mapping of export IDs to client IP addresses and vice-versa.

**Comment by ffilz** [comment]
This is slightly possible for NFS v3 by tracking the MOUNT calls, however, it is problematical in that such information would not survive a reboot. Also clients have a habit of going away without issuing UNMOUNT and for this reason we don't track it.

NFS v4 clients just use LOOKUP operations to traverse the PseudoFS and regular export namespace which could be tracked (but there definitely is no way to know when they are no longer mounted).

**Comment by ffilz** [comment]
Closing this since there is no plan to implement something like this.
