### ISSUE TITLE
nfs-ganesha: service reload fails

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#162]
see bugs.debian.org/860042

The systemd service file for nfs-ganesha containts the following line:

ExecReload=/bin/dbus-send --system   --dest=org.ganesha.nfsd --type=method_call /org/ganesha/nfsd/admin org.ganesha.nfsd.admin.reload

Before testing what is described in this bug I have already created a
symbolic link at /bin/dbus-send pointing to /usr/bin/dbus-send, since
this problem of wrong paths to the dbus-send executable is a separate
issue.

Unfortunately systemctl daemon-reload does not reload the configuration
of nfs-ganesha because ganesha seems to no longer provide
org.ganesha.nfsd.admin.reload .

It looks like this problem exists upstream as well, because in commit
5cd4abd6c738bb88ed80793ab2734902e270f25c [1]
this functionality was removed but the documentation (in the wiki at
[2]) and the service file provided by upstream were not modified
accordingly.

However sending a SIGHUP signal to ganesha.nfsd [3] gives the expected
result of nfs-ganesha reloading it's config.

[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/5cd4abd6c738bb88ed80793ab2734902e270f25c
[2] https://github.com/nfs-ganesha/nfs-ganesha/wiki/Dbusinterface
[3] https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/MainNFSD/nfs_init.c#L197

**Comment by dang** [comment]
The wiki is definitely (and perennially) out of date.  This is, sadly, the nature of wikis.  The correct way to reload the config is SIGHUP.  The service file should be updated.

**Comment by CyrilPeponnet** [comment]
Same for centos packages. Not sure from where the service file is coming from but it’s not working as it should for reload. @kalebskeithley

**Comment by CyrilPeponnet** [comment]
https://github.com/nfs-ganesha/nfs-ganesha/blob/1c71400606f0d3146907cd4994caa6ab2fc7060f/src/scripts/systemd/nfs-ganesha.service#L29

**Comment by dmanzoni** [comment]
Same for RHEL74 and nfs-ganesha-2.5.5-1.el7.x86_64

**Comment by dang** [comment]
Current next is this: https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/scripts/systemd/nfs-ganesha.service.el7#L30

This commit needs to be backported:
https://github.com/nfs-ganesha/nfs-ganesha/commit/d64dee8e8437f8faadcf006f9d832203fffcd25b

**Comment by ffilz** [comment]
Closing this as resolved.
