### ISSUE TITLE
build fails on older system (SLES 11 SP3), unknown type name 'va_list'

### ISSUE THREAD

**Issue by tm4n** [nfs-ganesha/nfs-ganesha#163]
Error output is:

nfs-ganesha-2.4.5/src/config_parsing/analyse.h:132:19: error: unknown type name 'va_list'

This can be fixed by simply adding an include to <stdarg.h> to the analyse.h file. After that, ganesha compiles. I checked the redhat bug tracker but could not find any bug report about this yet. I can supply a patch file if that helps.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
