### ISSUE TITLE
ganesha_conf not found error during build of 2.5-rc1

### ISSUE THREAD

**Issue by wyllys66** [nfs-ganesha/nfs-ganesha#164]
Any idea what Im doing wrong here?  Im building from a fresh clone of V2.5-rc1 tag on Ubuntu 14.04.3 LTS build server  that builds 2.4.X builds with no problems.

...
[ 93%] Built target MainServices
[ 94%] Built target gshdbus
[ 97%] Built target ganesha.nfsd
[ 97%] Built target man
[ 97%] Generating build/timestamp
running build
running build_py
running build_scripts
error: file '/home/foobar/ganeshabuilder/nfs-ganesha/build/scripts/ganeshactl/ganesha_conf' does not exist
make[2]: *** [scripts/ganeshactl/build/timestamp] Error 1
make[1]: *** [scripts/ganeshactl/CMakeFiles/target.dir/all] Error 2
make: *** [all] Error 2

**Comment by supriti** [comment]
I have seen this issue when compiling with -DBUS_ADMIN_TOOLS=ON. 
If I don't compile within a build dir, just in src its able to compile (because it always find files at correct location).
It seems like something is wrong in cmake somehow.

**Comment by wyllys66** [comment]
Yes, I am building with "-DUSE_ADMIN_TOOLS=ON -DUSE_DBUS=ON" flags, building inside the "build" directory (cd build; make)

**Comment by dang** [comment]
Is this a clean build dir? (i.e., you just made it?)  If not, try removing the build dir, re-creating it, and trying again?  It's working for me...

**Comment by wyllys66** [comment]
Fresh build of 2.5-rc2 with "-DUSE_ADMIN_TOOLS=ON -DUSE_DBUS=ON -DCMAKE_INSTALL_PREFIX=/opt/keeper" flags.  Note the alternate INSTALL_PREFIX, which works fine in 2.4.X.

...
[ 92%] Built target MainServices
[ 93%] Built target gshdbus
[ 96%] Built target ganesha.nfsd
[ 97%] Built target man
[ 97%] Generating build/timestamp
running build
running build_py
running build_scripts
error: file '/home/keeper/ganeshabuilder/nfs-ganesha/build/scripts/ganeshactl/ganesha_conf' does not exist
make[2]: *** [scripts/ganeshactl/build/timestamp] Error 1
make[1]: *** [scripts/ganeshactl/CMakeFiles/target.dir/all] Error 2
make: *** [all] Error 2
cp: cannot stat ‘build/install/opt’: No such file or directory
mv: cannot stat ‘nfs-ganesha_2.5-rc2_all/opt/keeper/etc/ganesha/ganesha.conf’: No such file or directory

**Comment by dang** [comment]
I build exclusively with CMAKE_INSTALL_PREFIX, and it works for me.  Here's my bulid options:

-DCMAKE_INSTALL_PREFIX=/home/dang/src/ganesha/next/clean/install -DUSE_ADMIN_TOOLS=YES -DUSE_DBUS=ON

(Plus some CEPH options...)

I'm trying to understand the issue here...

**Comment by wyllys66** [comment]
I just tried again on a different build server:
Ubuntu 16.04.1

I still get errors relating to ganesha_conf:

```
...
Scanning dependencies of target target
[ 98%] Generating fake_recall
[ 98%] Generating get_clientids
[ 98%] Generating grace_period
[100%] Generating purge_gids
[100%] Generating ganesha_mgr
[100%] Generating ganesha_stats
[100%] Generating build/timestamp
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/config_editor.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/io_stats.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/client_mgr.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/glib_dbus_stats.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/__init__.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/ganesha_mgr_utils.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/export_mgr.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/admin.py -> build/lib.linux-x86_64-2.7/Ganesha
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/log_mgr.py -> build/lib.linux-x86_64-2.7/Ganesha
creating build/lib.linux-x86_64-2.7/Ganesha/QtUI
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/QtUI/log_settings.py -> build/lib.linux-x86_64-2.7/Ganesha/QtUI
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/QtUI/clients_table.py -> build/lib.linux-x86_64-2.7/Ganesha/QtUI
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/QtUI/__init__.py -> build/lib.linux-x86_64-2.7/Ganesha/QtUI
copying /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/Ganesha/QtUI/exports_table.py -> build/lib.linux-x86_64-2.7/Ganesha/QtUI
running build_scripts
creating build/scripts-2.7
copying and adjusting fake_recall -> build/scripts-2.7
copying and adjusting get_clientids -> build/scripts-2.7
copying and adjusting grace_period -> build/scripts-2.7
copying and adjusting purge_gids -> build/scripts-2.7
copying and adjusting ganesha_mgr -> build/scripts-2.7
copying and adjusting ganesha_stats -> build/scripts-2.7
error: file '/home/wyllys/ganeshabuilder/nfs-ganesha/build/scripts/ganeshactl/ganesha_conf' does not exist
scripts/ganeshactl/CMakeFiles/target.dir/build.make:66: recipe for target 'scripts/ganeshactl/build/timestamp' failed
make[2]: *** [scripts/ganeshactl/build/timestamp] Error 1
CMakeFiles/Makefile2:2550: recipe for target 'scripts/ganeshactl/CMakeFiles/target.dir/all' failed
make[1]: *** [scripts/ganeshactl/CMakeFiles/target.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wyllys66** [comment]
Could it be that "ganesha_conf" does not end in ".py" like the other files in the SCRIPT_SRC block in src/scripts/ganeshactl/CMakefile.txt  ?  ganesha_conf was just added to the SCRIPT_SRC files 2 months ago and seems to be writing the dependency in scripts/ganeshactl/CMakeFiles/target.dir/build.make incorrectly.

These dependencies are wrong:
```
scripts/ganeshactl/build/timestamp: scripts/ganeshactl/fake_recall
scripts/ganeshactl/build/timestamp: scripts/ganeshactl/get_clientids
scripts/ganeshactl/build/timestamp: scripts/ganeshactl/grace_period
scripts/ganeshactl/build/timestamp: scripts/ganeshactl/purge_gids
scripts/ganeshactl/build/timestamp: scripts/ganeshactl/ganesha_mgr
scripts/ganeshactl/build/timestamp: scripts/ganeshactl/ganesha_stats
scripts/ganeshactl/build/timestamp: /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/ganesha_conf
...
scripts/ganeshactl/ganesha_conf: /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/ganesha_conf
        @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/wyllys/ganeshabuilder/nfs-ganesha/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Generating ganesha_conf"
        cd /home/wyllys/ganeshabuilder/nfs-ganesha/build/scripts/ganeshactl && cp /home/wyllys/ganeshabuilder/nfs-ganesha/src/scripts/ganeshactl/ganesha_conf ganesha_conf
```

The rule that copies ganesha_conf over from the src tree to the build area never executes because the timestamp dependency references the full path to the file in the src tree rather than the relative path like the others "scripts/ganeshactl/ganesha_conf"

**Comment by dang** [comment]
That is possibly an issue, but it definitely executes on my system, and ganesha_conf is copied to the build directory and installed.

If you rename ganesha_conf to ganesha_conf.py (and update the CMakeLists.txt), does that fix the problem?

**Comment by wyllys66** [comment]
Yes, that fixed the problem.

Im using cmake 3.5.1, what version do you build with?

**Comment by dang** [comment]
3.4.3, 3.6.2.  Both work for me. but I think we should make the change so it matches the rest of the python scripts.  Do you want to submit it?

**Comment by wyllys66** [comment]
ok ill submit a pull soon

**Comment by wyllys66** [comment]
https://github.com/nfs-ganesha/nfs-ganesha/pull/165

**Comment by wyllys66** [comment]
I think this can be closed, recent builds have been fine.
