### ISSUE TITLE
Invalid argument when creating symbol link to '.'

### ISSUE THREAD

**Issue by kaoet** [nfs-ganesha/nfs-ganesha#167]
My nfs-ganesha config:
```
###################################################
#
# EXPORT
#
# To function, all that is required is an EXPORT
#
# Define the absolute minimal export
#
###################################################

EXPORT
{
		# Export Id (mandatory, each EXPORT must have a unique Export_Id)
		Export_Id = 77;

		# Exported path (mandatory)
		Path = /export;

		# Pseudo Path (for NFS v4)
		Pseudo = /export_nfs4;

		Access_Type = RW;

		Squash = No_Root_Squash;

		#Transports = TCP;
		#Protocols = NFS4;

		SecType = "sys";

		# Exporting FSAL
		FSAL {
			Name = VFS;
		}
}
```

How I mount it:
```
172.22.8.200:/export_nfs4 on /home/infra/mnt type nfs4 (rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=10.203.1.21,local_lock=none,addr=172.22.8.200)
```

Then I create the symbol link in the root of mount point:
```
~/mnt$ sudo ln -s . cur
ln: failed to create symbolic link ‘cur’: Invalid argument
```

But it seems that as long as the source is not exactly '.' (like './' or '../mnt'), the creation will succeed.

I also tried to `ln -s . cur` inside the nfs server, which has no problem.

And I tried to do `ln -s . cur` inside a mount point of a kernel nfs server, which has no problem too.

**Comment by dang** [comment]
My guess is that this is related to the way that the shell resolves "." vs other ways of doing the path.  It probably expands to the pseudo dir, which doesn't support symlink.  Other names, like "./" and "../mnt" probably resolve to the VFS directory, which does support symlink.

**Comment by ffilz** [comment]
Would be good to see what actually happens over the wire.

If the symlink operation is going over to Ganesha as expected (handle of export root, linkpath of ".", name of "cur"), then It would also be good to test what happens to symlinkat(linkpath, dir_fd, name), it could be a limitation of symlinkat in which case Ganesha can't do much about it.

**Comment by sachinpunadikar** [comment]
This has been fixed with patch https://review.gerrithub.io/#/c/372645/ 
Release - V2.6-dev-4

**Comment by ffilz** [comment]
Closed as fixed.
