### ISSUE TITLE
ganesha.nfsd segfaults when exporting second file system

### ISSUE THREAD

**Issue by apnorrie** [nfs-ganesha/nfs-ganesha#168]
Ganesha release 2.4.1 (from gluster repositories for Debian). Debian8, kernel 4.9 from Debian backports.
This is reproducible when mounting and then exporting a file system AFTER ganesha.nfsd has started and already exported a different filesystem. FSAL is vfs with XFS filesystems.

Steps to reproduce:

mount /data1
start ganesha.nfsd
export /data1 using:
        dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/exports.conf string:"EXPORT(Path=/data1)"
mount /data2
export /data2 using:
        dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/exports.conf string:"EXPORT(Path=/data2)"

ganesha.nfsd segfaults

**Comment by dang** [comment]
Can you get a backtrace?

**Comment by apnorrie** [comment]
Adding gdb backtrace ...

Thread 269 "ganesha.nfsd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6bd8b700 (LWP 27086)]
0x00007ffff733903b in blkid_get_dev () from /lib/x86_64-linux-gnu/libblkid.so.1
(gdb) bt
#0  0x00007ffff733903b in blkid_get_dev () from /lib/x86_64-linux-gnu/libblkid.so.1
#1  0x0000555555583ec9 in ?? ()
#2  0x0000555555587433 in populate_posix_file_systems ()
#3  0x00005555555889a9 in resolve_posix_filesystem ()
#4  0x00007fff69aa4c70 in vfs_create_export () from /usr/lib/x86_64-linux-gnu/ganesha/libfsalxfs.so
#5  0x00005555556547af in mdcache_fsal_create_export ()
#6  0x000055555563593f in ?? ()
#7  0x000055555566cdb8 in ?? ()
#8  0x000055555566c20f in ?? ()
#9  0x000055555566d4f9 in load_config_from_node ()
#10 0x000055555564478e in ?? ()
#11 0x0000555555668522 in ?? ()
#12 0x00007ffff77986a3 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#13 0x00007ffff7789d24 in dbus_connection_dispatch () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#14 0x00007ffff778a03d in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#15 0x00005555556693b3 in gsh_dbus_thread ()
#16 0x00007ffff63bc464 in start_thread (arg=0x7fff6bd8b700) at pthread_create.c:333
#17 0x00007ffff5cb69df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb)

**Comment by dang** [comment]
I suspect this is fixed by this in 2.5: b69d1ec4c6e245318111cb006785d2b30ec5cea4

**Comment by apnorrie** [comment]
Ok, many thanks. I will give it a test and report back.

**Comment by apnorrie** [comment]
Yes indeed, this works now in version 2.5-rc2. Many thanks for the quick response ! This can be closed off.
