### ISSUE TITLE
Build Error: Unsued functions in src/support/server_stats.c

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#170]
From the commit: https://github.com/nfs-ganesha/nfs-ganesha/commit/9b4739f9b192a7e0596555cb0f37b57f837eed7d 
cmake version: 3.5.2
gcc version: 4.8.5
Compiling with -Werror=unused-function with latest ganesha gives following error:

src/support/server_stats.c:754:13: error: ‘reset_nfsv3_stats’ defined but not used [-Werror=unused-function]
 static void reset_nfsv3_stats(struct nfsv3_stats *nfsv3)
nfs-ganesha/src/support/server_stats.c:768:13: error: ‘reset_nfsv40_stats’ defined but not used [-Werror=unused-function]
 static void reset_nfsv40_stats(struct nfsv40_stats *nfsv40)
             ^
/src/support/server_stats.c:784:13: error: ‘reset_nfsv41_stats’ defined but not used [-Werror=unused-function]
 static void reset_nfsv41_stats(struct nfsv41_stats *nfsv41)
             ^
src/support/server_stats.c:805:13: error: ‘reset_mnt_stats’ defined but not used [-Werror=unused-function]
static void reset_mnt_stats(struct mnt_stats *mnt)
             ^
src/support/server_stats.c:818:13: error: ‘reset_rquota_stats’ defined but not used [-Werror=unused-function]
static void reset_rquota_stats(struct rquota_stats *rquota)
             ^
src/support/server_stats.c:831:13: error: ‘reset_nlmv4_stats’ defined but not used [-Werror=unused-function]
 static void reset_nlmv4_stats(struct nlmv4_stats *nlmv4)
             ^
src/support/server_stats.c:843:13: error: ‘reset_deleg_stats’ defined but not used [-Werror=unused-function]
 static void reset_deleg_stats(struct deleg_stats *deleg)

**Comment by sachinpunadikar** [comment]
Provided new patch to enclose the new code under ifdef USE_DBUS block
https://review.gerrithub.io/#/c/360034/

**Comment by supriti** [comment]
Fixed in latest version. Closing the issue.
