### ISSUE TITLE
Can i reload config when the server is running?

### ISSUE THREAD

**Issue by bianwenhui** [nfs-ganesha/nfs-ganesha#173]
tks

**Comment by dang** [comment]
Yes.  There are several methods.
1. You can cause Ganesha to reread config by sending SIGHUP or the DBUS reload command (see ganeshactl reload).  This has limitations; it can only add or remove exports, I believe.

2. You can add and remove exports directly with DBUS commands (see manage_exports.py)

3. You can update exports in place using DBUS (see manage_exports.py)

**Comment by ffilz** [comment]
SIGHUP will reload EXPORT and LOG config sections. It will not remove exports (only add or change).

You can also tweak log levels with DBUS

**Comment by bianwenhui** [comment]
thanks for solving my problem

**Comment by bianwenhui** [comment]
thanks
