### ISSUE TITLE
hi, what's the maxcount of exports?

### ISSUE THREAD

**Issue by bianwenhui** [nfs-ganesha/nfs-ganesha#174]
##  when i export 1024 exports, the service is down.

17/05/2017 11:49:12 : epoch 591bc838 : node1 : nfs-ganesha-21603[main] log_conf_commit :CONFIG :EVENT :Switching to new component log levels
17/05/2017 11:49:12 : epoch 591bc838 : node1 : nfs-ganesha-21603[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
17/05/2017 11:49:12 : epoch 591bc838 : node1 : nfs-ganesha-21603[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
17/05/2017 11:49:12 : epoch 591bc838 : node1 : nfs-ganesha-21603[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.

no more logs

**Comment by soumyakoduri** [comment]
Could you check system messages or dmesg as well. One of the reasons which I can think of is that the service may have got OOM killed.

**Comment by bianwenhui** [comment]
maybe casued by ceph-mds. i will try again tomorrow.  thanks
`May 16 13:17:41 node1 kernel: Out of memory: Kill process 21940 (ceph-mds) score 532 or sacrifice child`
