### ISSUE TITLE
nfs-ganesha multiple nics

### ISSUE THREAD

**Issue by nconder** [nfs-ganesha/nfs-ganesha#176]
Does nfs-ganesha support single thread file transfers across multiple NIC's similar to SMB Multichannel and ISCIS Multipath?

**Comment by ffilz** [comment]
No, Ganesha doesn't support that, it is something that might well be useful, but no one has advanced a proposal to implement

**Comment by nconder** [comment]
This would be a great feature addition specifically in the world of big data when dealing with very large single file consumption to increase throughput to compute nodes by scaling out NICs. By the way this is an issue that I currently dealing with.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest.
