### ISSUE TITLE
anonymous_uid and anonymous_gid should be 65534 but not 4294967294

### ISSUE THREAD

**Issue by CuiBinghua** [nfs-ganesha/nfs-ganesha#178]
As we know, in UNIX/Linux, nobody's UID and nogroup's GID are both 65534.
However, in NFS-Ganesha, anonymous_uid and anonymous_gid's default value are both -2, which would be converted to 4294967294 because uid_t and git_t are both 32-bit.
So, I suggest that we should modify ANON_UID and ANON_GID from -2 to 65534 in header file src/include/nfs_exports.h.
After that, anonymous_uid/anonymous_gid's default value could be mapped into nobody/nogroup correctly.

**Comment by dang** [comment]
Actually, the anonymous UID and GID can vary from distro to distro, and even sometimes from install to install.  The anonymous settings are configurable (in EXPORT_DEFAULTS or per-export) via the anonymous_uid and anonymous_gid settings, so feel free to set them to the correct values for your install.

-2 is a safe value, that won't ever clash with an actual value in use by the system.

**Comment by ffilz** [comment]
Also, at least some systems define nfsnobody to be -2/4294967294.

 

Frank

**Comment by ffilz** [comment]
Closing as a will not fix.
