### ISSUE TITLE
ganesha holds file handle open even after export is removed

### ISSUE THREAD

**Issue by wyllys66** [nfs-ganesha/nfs-ganesha#179]
Using ganesha 2.4.5 on Ubuntu 16.04.2

When a share is removed from the config file and ganesha is reloaded (pkill -HUP), it no longer appears as being exported, however the ganesha.nfsd process continues to hold a file descriptor open on the previously exported directory which makes it impossible to clean up or unmount the filesystem without completely restarting ganesha.nfsd. 

Is this a known issue?  Is there any workaround other than restarting the daemon?

**Comment by ffilz** [comment]
SIGHUP doesn't cause Ganesha to actually remove exports. I'm not sure why you're seeing it as no longer exported. Did you try dBus remove export? That should cause every mdcache entry on the export to get discarded (assuming there isn't a 2nd export that the mdcache entry belongs to also) and any open file descriptors closed.

There COULD be refcount issues, so it might be worth checking if the current V2.5-final shows this behavior also. We have discovered a few important patches that need backporting to V2.4 stable, I don't know if they have all made it into the stable branch (and we certainly haven't tagged a new V2.4.6 with all of the missing patches).

**Comment by wyllys66** [comment]
I use 'ganesha_mgr remove_export XXXX' to remove it, but fuser and lsof still show the ganesha.nfsd process holding a handle to the exported directory.

**Comment by ffilz** [comment]
Hmm, ok, what FSAL are you using? I think you might be hitting a refcount issue that may have been fixed.

**Comment by wyllys66** [comment]
VFS

**Comment by wyllys66** [comment]
Tested with 2.5-final and I think the problem is fixed.

**Comment by wyllys66** [comment]
Could be a timing issue or race condition because sometimes it does get released correctly and other times it does not.

**Comment by ffilz** [comment]
Ok, it's probably one of the patches that have come up as missing from 2.4 in the past few weeks. Look for 2.4.6 or if you can move to 2.5.0 (which will come out Friday). The refcount issues were all possible race conditions. Hmm, and actually, I think there was a race between activity and unexport.

**Comment by wyllys66** [comment]
Is it fixed in 2.5?  I did see it occur a couple of times even with 2.5-final.

**Comment by ffilz** [comment]
Oh, you did see it on 2.5, hmm, there probably still is a refcount issue. If you can narrow down to an easy recreate, we can get it under various debug and see if something comes out.

**Comment by wyllys66** [comment]
Recreating it on 2.5.0:

1. create an export, I used VFS FSAL, export it with ganesha_mgr
2. mount it from a client
3. unmount it from a client
4. un-export the file system with ganesha_mgr
5. Use "fuser -v MOUNTPOINT" to see if gansha.nfsd still has a hold on it (it does)
6. Also use "lsof -p <ganesha PID>" to see if ganesha.nfsd is accessing the export dir (it is).

**Comment by wyllys66** [comment]
This is STILL a problem, any chance of fixing it?

**Comment by wyllys66** [comment]
This is still a problem as of 2.5.4

**Comment by ffilz** [comment]
Hmm, can you see if it's still a problem with 2.6-dev.19?

If it is, we need a good recreate scenario and/or debug...

**Comment by wyllys66** [comment]
The recreate steps are above.  I haven't had time to build and test with 2.6-dev yet.

**Comment by wyllys66** [comment]
There is no "unexport" function in the VFS export_ops structure, so whenever release_export is called, the underlying VFS structure is never fully released.  Nobody ever calls the "unclaim" function for the individual  VFS export unless all of the filesystems are being removed, so the file descriptor opened in "claim" and added to the fsal structure is never closed.

**Comment by wyllys66** [comment]
I dont have a system where I can install and test 2.6-dev yet, but this fix appears to work for me in 2.5.4.

```
--- a/src/FSAL/FSAL_VFS/export.c
+++ b/src/FSAL/FSAL_VFS/export.c
@@ -375,6 +375,12 @@ static fsal_status_t wire_to_host(struct fsal_export *exp_hdl,
        return vfs_check_handle(exp_hdl, fh_desc, &fs, fh, &dummy);
 }
 
+static void vfs_unexport(struct fsal_export *exp_hdl,
+                  struct fsal_obj_handle *root_obj)
+{
+    return release(exp_hdl);
+}
+
 /* vfs_export_ops_init
  * overwrite vector entries with the methods that we support
  */
@@ -402,10 +408,13 @@ void vfs_export_ops_init(struct export_ops *ops)
        ops->set_quota = set_quota;
        ops->alloc_state = vfs_alloc_state;
        ops->free_state = vfs_free_state;
+    ops->unexport = vfs_unexport;
 }
```

**Comment by ffilz** [comment]
Ok, that's not correct, the documentation for the export method states:

 * This function is called when the export is unexported.  It should release any
 * working data that is not necessary when unexported, but not free the export
 * itself, as there are still references to it.

What this means though is someone (possibly mdcache) is holding an extra reference to the exp_hdl. I will check over the code to find where that is, and then it just needs to be released in mdcache_unexport.

**Comment by wyllys66** [comment]
I dont get how mdcache is used in this case?  Its not defined anywhere in my configuration. The only FSAL I have listed for this particular export is VFS.  The only place in the FSAL_VFS where that fd is managed is in vfs_free_filesystem which only gets called from the claim/unclaim functions.

**Comment by ffilz** [comment]
MDCACHE is automatically stacked on top of VFS. I see VFS export release being called from MDCACHE export release on shutdown, but not on unexport... But on unexport, mdcache_exp_release IS called, so something's wrong... Examining...

**Comment by ffilz** [comment]
Ah, got it. Unexport didn't set op_ctx, which causes MDCACHE to not actually call VFS's release export method... V2.6 patch to be posted momentarily. You can then backport to V2.5

**Comment by wyllys66** [comment]
great, thanks!

**Comment by ffilz** [comment]
https://review.gerrithub.io/#/c/390911/
