### ISSUE TITLE
Chown command returned error when set same group as already set at a file on nfs-ganesha volume

### ISSUE THREAD

**Issue by tshibata-iij** [nfs-ganesha/nfs-ganesha#180]
I tested permission management features of nfs-ganesha.  And I encountered a strange behavior compared with usual nfs server. I changed a group of file as already set at that file. 
I think there is no side-effect, but I encountered error, like below.
```
$ sudo chown test:test2 my_file 
$ ls -l my_file 
-rw-rw-r-- 1 test test2 0 May 31 19:01 my_file
$ chown test:test2 my_file                            <---- fail
chown: changing ownership of 'my_file': Operation not permitted
```

### Linux kernel nfs (expected):
It pass the permission evaluation, when set "same group".
### nfs-ganesha + VFS backend:
It fails permission evaluation, when set the parameter to "same group". It mean that nfs-ganesha always evaluate execute user is belonging to the group specified as chown command parameter.

I think nfs-ganesha may want to be same behavior as usual nfs server.

Prerequisites:
1. Target file's group is different from execute user.
2. Sets the chown's parameter to "same to target file group".

```
//  Linux kernel nfs (expected)

$ id
uid=1018(test) gid=1020(test) groups=1020(test),27(sudo)
$ touch my_file 
$ ls -l my_file 
-rw-rw-r-- 1 test test 0 May 31 17:53 my_file
$ sudo chown test:test2 my_file
$ ls -l my_file 
-rw-rw-r-- 1 test test2 0 May 31 17:53 my_file
$ chown test:test2 my_file                           <---- success
$ ls -l my_file 
-rw-rw-r-- 1 test test2 0 May 31 17:53 my_file

// ganesha VFS

$ id
uid=1018(test) gid=1020(test) groups=1020(test),27(sudo)
$ touch my_file 
$ sudo chown test:test2 my_file 
$ ls -l my_file 
-rw-rw-r-- 1 test test2 0 May 31 19:01 my_file
$ chown test:test2 my_file                            <---- fail
chown: changing ownership of 'my_file': Operation not permitted
```

**Comment by dang** [comment]
Yeah, this is because that user cannot, in fact, change the file to that group.   Yes, the operation is a no-op, but Ganesha doesn't currently have a check to see if the group isn't actually changing.  This should probably be fixed (fsal_check_setattr_perms() is the relevant location).  Do you think you could knock something up?

**Comment by ffilz** [comment]
Hmm, that's an interesting question whether it's actually ok to allow a no-op group ownership set when the user isn't part of the group but is the owner of the file.

Does that work for local access?

I'll have to check the details of the POSIX spec for chown system call to see what is actually expected here.

**Comment by Ferroin** [comment]
I don't know about POSIX for certain, but it does succeed without error on at least Linux, and I think it does too on FreeBSD.

**Comment by ffilz** [comment]
Ok, we can fix this up, it would be a simple patch in the permission checking for setattr

**Comment by ffilz** [comment]
Hmm, I was about to submit a patch that skips the permission check if the current owner_group is the same as what is being set, however, that could cause a security race if the owner_group was changed by a local admin such that Ganesha's knowledge of the current owner_group is wrong.

**Comment by ffilz** [comment]
Closing this as will not fix. If this issue really is still important, please re-open.
