### ISSUE TITLE
FSAL_CEPH and FSAL_RGW can't limit access client lists

### ISSUE THREAD

**Issue by HIK-GYK** [nfs-ganesha/nfs-ganesha#182]
the configure file  likes this :
**********************************************************************
 [EXPORT]
 {            Export_Id=1;
              Path = "/";
              Pseudo = /cephfs;
              Access_Type = RW;
              Squash = None;
              FSAL {
                          Name = CEPH;
                  }
               CLIENT{
                           Clients = 192.169.30.182;
                           Squash = No_Root_Squash;
                }
 }
 [EXPORT]
 {            Export_Id=2;
              Path = "/";
              Pseudo = /rgw;
              Access_Type = RW;
              Squash = None;
              FSAL {
                          Name = RGW;
                          User_Id = "test";
                          Access_Key_Id = "VMWUAYWUGXX60NMQ9C7J";
                          Secret_Access_Key = "WpmDLsixEXK1XXnwewGL xsDDFJEJEKDJ8DCJJLVMEC";
                  }
               CLIENT{
                           Clients = 192.169.30.182;
                           Squash = No_Root_Squash;
                }
 }
          RGW {
                    ceph_conf="/etc/ceph/ceph.conf";
              }
**************************************************************************************

then I found that although the exports list have 192.168.30.182, I still can mount in some other clients. 
do my configure file have any problems? or there actually doesn't exit a limitation for ACLs?
This test is done  with ceph v10.2.7 and ganesha2.4 stable ,and I find in this ganesha version,even I mount the exports for RGW succeessful, the process will be dead if I do commands like : ll /mnt/test/RGW.

**Comment by ffilz** [comment]
You need to move that Access_Type into the CLIENT block, it's presence in the EXPORT block allows RW access to all clients, so all your CLIENT block is doing is allowing no root squash instead of the default root squash for the specified client.

This is an aspect of Ganesha EXPORT configuration we need to improve documentation on...

**Comment by HIK-GYK** [comment]
thanks , I will try.
