### ISSUE TITLE
Protocols v3, v4  with NFS-Ganesha 2.5.0

### ISSUE THREAD

**Issue by bianwenhui** [nfs-ganesha/nfs-ganesha#183]
**at begin i used Protocols =3, it works well.
then i changed the Protocols =3,4; send SIGHUP to reload exports,
and mount use vers=4,  the output like this,**
`mount.nfs: mounting node1:/export_1 failed, reason given by server: No such file or directory`
**only after i restart the ganesha service, it can be mounted.** 

`23/06/2017 10:47:24 [sigmgr] src/support/exports.c:1327 :export_commit_common :CONFIG :INFO :Export 1 updated at pseudo (/export_1) with path (/   export_1) and tag ((null)) perms (options=023033e0no_root_squash, RWrw, 34-, ---, TCP, ----,               ,         ,                ,                )`

`23/06/2017 10:47:32 [work-77] src/Protocols/NFS/nfs4_Compound.c:682 :nfs4_Compound :NFS4 :DEBUG :Request 1: opcode 15 is OP_LOOKUP
23/06/2017 10:47:32 [work-77] src/Protocols/NFS/nfs4_op_lookup.c:98 :nfs4_op_lookup :NFS4 :DEBUG :name=export_1
23/06/2017 10:47:32 [work-77] src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:1212 :mdc_lookup :INODE :DEBUG :Cache Miss detected for       export_1
23/06/2017 10:47:32 [work-77] src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:1268 :mdc_lookup_uncached :INODE :DEBUG :lookup export_1      failed with No such file or directory
23/06/2017 10:47:32 [work-77] src/Protocols/NFS/nfs4_Compound.c:768 :nfs4_Compound :NFS4 :DEBUG :Status of OP_LOOKUP in position 1 = NFS4ERR_NOENT
23/06/2017 10:47:32 [work-77] src/Protocols/NFS/nfs4_Compound.c:841 :nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_NOENT lastindex = 1`

`EXPORT
{
        Export_ID = 1;
        Path = /export_1;
        Pseudo = /export_1;
        Access_Type = RW;
        Squash = None;
        Protocols = "3","4";
        Transports = "TCP";
		FSAL { Name = CEPH; }
}
`
**NFS-Ganesha Release = V2.5.0**

**Comment by dang** [comment]
This is correct.  As of now, only added or deleted export sections take effect on SIGHUP, not changed exports or any other config section.

**Comment by ffilz** [comment]
And to be absolutely correct, the config changes that take effect on SIGHUP:

Updates to the LOG config take effect (note if a Log level had been changed, the new config has to set it back to take effect).

Updates to existing exports take effect

New exports are added

Exports that no longer exist in the config file are NOT deleted (export removal may ONLY be accomplished by use of the dBus command).

**Comment by bianwenhui** [comment]
but the other sections can be changed， like access_type @dang @ffilz .
thks

**Comment by bianwenhui** [comment]
@dang  but the others scetion can be changed, like access_type,

**Comment by bianwenhui** [comment]
@ffilz oh, i see. thks

**Comment by ffilz** [comment]
What is sometimes confusing is that Protocols exists both in NFS_CORE_PARAM and EXPORTS. In NFS_CORE_PARAM it controls which listening sockets are opened, and how Ganesha registers with portmap. If a protocol is not enabled in NFS_CORE_PARAM it can't be enabled in an EXPORT (since the listening socket isn't open for it). The Protocols option in EXPORT allows specific exports to have a more restrictive list of protocols supported, and that list may be updated with SIGHUP.

**Comment by bianwenhui** [comment]
thank both of u for answering me
