### ISSUE TITLE
Segmentation fault when exporting FSAL Ceph and RGW in the same conf file. 

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#184]
NFS-Ganesha version 2.5.0.1
Ceph version:12.1.0

Config file: [ganesha.conf.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/1114747/ganesha.conf.txt)

If both FSALs are present in file, I see a segmentation fault. Exporting only on FSAL does not result in segmentation fault. 

Looking at the log:
Both FSALs in export file: [ganesha_both_fsal_log.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/1114749/ganesha_both_fsal_log.txt)

Only CEPH fsal in export file: [ganesha_only_cephfs_log.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/1114752/ganesha_only_cephfs_log.txt)

From the log it looks like in case both the FSALs are exported, even for FSAL CEPH its calling the function lookup_init (which is defined for FSAL_RGW in file handle.c). Then it tries to call function create_pseudofs and it dies with message "BUILDING PSEUDOFS: Export_Id 1 Path / Pseudo Path /cephfs LOOKUP cephfs failed with No such file or directory (can't create directory on non-PSEUDO FSAL)"

In case of only FSAL Ceph, its calling the right function "lookup"

Dump:
*** Caught signal (Aborted) **
 in thread 7fb5a3da90c0 thread_name:ganesha.nfsd
 ceph version v12.1.0-289-g117b171715 (117b1717154e1236b2d37c405a86a9444cf7871d) luminous (dev)
 1: (()+0x436f07) [0x7fb580cf8f07]
 2: (()+0x10b10) [0x7fb5a25d6b10]
 3: (gsignal()+0x37) [0x7fb5a1e028d7]
 4: (abort()+0x13a) [0x7fb5a1e03caa]
 5: (finish()+0xb6) [0x7fb59fc90e61]
 6: (()+0xf2ca) [0x7fb5a3bb22ca]
 7: (()+0x37139) [0x7fb5a1e05139]
 8: (()+0x37185) [0x7fb5a1e05185]
 9: (ReturnLevelAscii()+0) [0x51fa45]
 10: (display_log_component_level()+0x1a8) [0x5226d1]
 11: (DisplayLogComponentLevel()+0xbe) [0x522791]
 12: (create_pseudofs()+0x84) [0x4899fe]
 13: /usr/bin/ganesha.nfsd() [0x458ab0]
 14: (nfs_start()+0x70) [0x458dee]
 15: (main()+0xb2e) [0x41ff5f]
 16: (__libc_start_main()+0xf5) [0x7fb5a1dee6e5]
 17: (_start()+0x29) [0x41f079]
2017-06-30 10:44:47.607489 7fb5a3da90c0 -1 *** Caught signal (Aborted) **
 in thread 7fb5a3da90c0 thread_name:ganesha.nfsd

 ceph version v12.1.0-289-g117b171715 (117b1717154e1236b2d37c405a86a9444cf7871d) luminous (dev)
 1: (()+0x436f07) [0x7fb580cf8f07]
 2: (()+0x10b10) [0x7fb5a25d6b10]
 3: (gsignal()+0x37) [0x7fb5a1e028d7]
 4: (abort()+0x13a) [0x7fb5a1e03caa]
 5: (finish()+0xb6) [0x7fb59fc90e61]
 6: (()+0xf2ca) [0x7fb5a3bb22ca]
 7: (()+0x37139) [0x7fb5a1e05139]
 8: (()+0x37185) [0x7fb5a1e05185]
 9: (ReturnLevelAscii()+0) [0x51fa45]
 10: (display_log_component_level()+0x1a8) [0x5226d1]
 11: (DisplayLogComponentLevel()+0xbe) [0x522791]
 12: (create_pseudofs()+0x84) [0x4899fe]
 13: /usr/bin/ganesha.nfsd() [0x458ab0]
 14: (nfs_start()+0x70) [0x458dee]
 15: (main()+0xb2e) [0x41ff5f]
 16: (__libc_start_main()+0xf5) [0x7fb5a1dee6e5]
 17: (_start()+0x29) [0x41f079]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

     0> 2017-06-30 10:44:47.607489 7fb5a3da90c0 -1 *** Caught signal (Aborted) **
 in thread 7fb5a3da90c0 thread_name:ganesha.nfsd

 ceph version v12.1.0-289-g117b171715 (117b1717154e1236b2d37c405a86a9444cf7871d) luminous (dev)
 1: (()+0x436f07) [0x7fb580cf8f07]
 2: (()+0x10b10) [0x7fb5a25d6b10]
 3: (gsignal()+0x37) [0x7fb5a1e028d7]
 4: (abort()+0x13a) [0x7fb5a1e03caa]
 5: (finish()+0xb6) [0x7fb59fc90e61]
 6: (()+0xf2ca) [0x7fb5a3bb22ca]
 7: (()+0x37139) [0x7fb5a1e05139]
 8: (()+0x37185) [0x7fb5a1e05185]
 9: (ReturnLevelAscii()+0) [0x51fa45]
 10: (display_log_component_level()+0x1a8) [0x5226d1]
 11: (DisplayLogComponentLevel()+0xbe) [0x522791]
 12: (create_pseudofs()+0x84) [0x4899fe]
 13: /usr/bin/ganesha.nfsd() [0x458ab0]
 14: (nfs_start()+0x70) [0x458dee]
 15: (main()+0xb2e) [0x41ff5f]
 16: (__libc_start_main()+0xf5) [0x7fb5a1dee6e5]
 17: (_start()+0x29) [0x41f079]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

Aborted (core dumped)

**Comment by dang** [comment]
This is because your pseudo path for RGW is /, so it's overwriting the root of the PSEUDO FS.  This means any lookups attempted at all go to RGW.

You cannot use / as a pseudo path if you have more than one export.  You must have unique pseudo paths.

**Comment by supriti** [comment]
@dang This seems to be issue. Thanks. May be we can add a check during conf file parsing, so that it complains early enough, and does not cause segmentation fault.

**Comment by ffilz** [comment]
Ok, I see the issue... We could improve the error messages, but we don't want to prevent what's going on here.

Ganesha explicitly allows specifying Pseudo = /; This is to allow use of a real file system instead of FSAL_PSEUDO or for situations where there is only a single export.

Ganesha also explicitly allows placing any export anywhere in the name space, however, in general the "mount point" of an export must exist as a directory on the filesystem it's placed on. The exception is that on an FSAL_PSEUDO filesystem, Ganesha is allowed to create directories necessary to instantiate the export.

We could allow that for all FSALs, but I'm not sure that's a good idea.

Part of the problem here is that we don't have really good documentation for how exports work...

**Comment by supriti** [comment]
Thanks for detailed explanation @ffilz  and +1 for documentation 👍
