### ISSUE TITLE
about HA

### ISSUE THREAD

**Issue by bianwenhui** [nfs-ganesha/nfs-ganesha#185]
very sorry for asking questions at here. long time no receipt of your mail, and very except to get answers, so  really sorry to put questions here.
recently i tried CTDB to make nfs-ganesha high availability, but it sames support nfs-ganesha not very well.
is nfs-ganesha support HA or any other solution can i try.
sorry again.

**Comment by soumyakoduri** [comment]
For Gluster, we use Pacemaker/Corosync to make nfs-ganesha highly available. But I think there was some effort on making use of CTDB for HA - https://wiki.samba.org/index.php/Setting_up_CTDB_for_Clustered_NFS

@malahal .. do you have any insights?

**Comment by malahal** [comment]
We did use CTDB with ganesha1.5 and ganesha2.2 with our GPFS clustered file system.  Now we use some home grown solution but the bulk of the work is done by our clustered file system (GPFS).

**Comment by bianwenhui** [comment]
@soumyakoduri @malahal 
i was using cephfs

**Comment by dang** [comment]
The work for cephfs for HA is using pacemaker/corosync.  It's being done by the upstream Ceph community right now.

**Comment by bianwenhui** [comment]
@dang thank u, i‘ll test it later.
