### ISSUE TITLE
cephfs open4_validate_claim failed; touch is very slow 

### ISSUE THREAD

**Issue by junxfl** [nfs-ganesha/nfs-ganesha#187]
I use nfs-gansha + cephfs， but  find a problem.  The steps is:
1、 mount -t nfs 10.100.189.52:/volumes /mnt/
2、touch /mnt/1 ; tocuh is very show,  after a long period of time，it is ok.  Log is：
 nfs_rpc_execute :DISP :DEBUG :Request from ::ffff:10.100.161.182 for Program 100003, Version 4, Function 1 has xid=3973493752
 dupreq_tcp_cmpf :DUPREQ :DEBUG :dupreq_tcp_cmpf
 nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 5 operations, res = 0x7f7ed40009f0, tag = NO TAG
 nfs4_Compound :NFS4 :DEBUG :Request 0: opcode 22 is OP_PUTFH
 get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
 cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 15543
 nfs4_Compound :NFS4 :DEBUG :Request 1: opcode 18 is OP_OPEN
 nfs4_op_open :STATE :DEBUG :Entering NFS v4 OPEN handler -----------------------------
 nfs4_op_open :STATE :DEBUG :OPEN Client id = 5963475500000001
 nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
 nfs4_op_open :NFS4 :DEBUG :open4_validate_claim failed
 nfs4_op_open :STATE :DEBUG :failed with status NFS4ERR_GRACE
 nfs4_Compound :NFS4 :DEBUG :Status of OP_OPEN in position 1 = NFS4ERR_GRACE
 nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_GRACE lastindex = 1
nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
reaper_run :CLIENT ID :DEBUG :Now checking NFS4 clients for expiration
s_rpc_cond_stall_xprt :DISP :DEBUG :xprt 0x7f7f50001170 xp_refs 2 has 0 reqs active (max 512)
 thr_decode_rpc_request :DISP :DEBUG :0x7f7f50001170 context (nil)
 nfs_rpc_enqueue_req :DISP :DEBUG :enqueued req, q 0x7d7ff8 (REQ_Q_HIGH_LATENCY 0x7d7ff8:0x7d8060) size is 1 (enq 30 deq 29)
 thr_decode_rpc_requests :DISP :DEBUG :exiting, stat=XPRT_IDLE
 worker_run :DISP :DEBUG :NFS protocol request, reqdata=0x7f7f500008c0 xprt=0x7f7f50001170 requests=1
 get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
 nfs_rpc_execute :DISP :DEBUG :Request from ::ffff:10.100.161.182 for Program 100003, Version 4, Function 1 has xid=3990270968
 dupreq_tcp_cmpf :DUPREQ :DEBUG :dupreq_tcp_cmpf
 nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 5 operations, res = 0x7f7ed80009f0, tag = NO TAG
 nfs4_Compound :NFS4 :DEBUG :Request 0: opcode 22 is OP_PUTFH
 get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
 cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 15543
 nfs4_Compound :NFS4 :DEBUG :Request 1: opcode 18 is OP_OPEN
 nfs4_op_open :STATE :DEBUG :Entering NFS v4 OPEN handler -----------------------------
 nfs4_op_open :STATE :DEBUG :OPEN Client id = 5963475500000001
 nfs_in_grace :STATE :DEBUG :NFS Server IN GRACE
 nfs4_op_open :NFS4 :DEBUG :open4_validate_claim failed
 nfs4_op_open :STATE :DEBUG :failed with status NFS4ERR_GRACE
 nfs4_Compound :NFS4 :DEBUG :Status of OP_OPEN in position 1 = NFS4ERR_GRACE
 nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_GRACE lastindex = 1

congfig is:
EXPORT
{
        Export_ID=1;
        Path = /;
        Pseudo = /volumes;
        Disable_ACL = TRUE;
        Access_Type = RW;
        NFS_Protocols = 4;
        Squash = No_Root_Squash;
        Transport_Protocols = TCP;

        FSAL {
                Name = CEPH;
                User_Id = "cephfs";
                Secret_Access_Key = "AQDqFilZ8VgEFBAAdRsmX+fmfKbPcirCDG4KCA==";
        }
}
CEPH {
        ceph_conf = "/etc/ceph/ceph.conf";
        cluster = "ceph";
}

**Comment by junxfl** [comment]
nfs-ganesha version is V2.5-stable.

**Comment by junxfl** [comment]
ceph version is 10.2.7

**Comment by dang** [comment]
Your NFS server is in Grace on startup, and will not accept write operations until it leaves Grace. This is a feature of the protocol.  By default, the Grace period is 60 seconds.  Wait until it's done, and things should operate normally.

Note, for debugging purposes only, you can disable Grace by setting Graceless to True in the NFSV4 section; this is *not* how you should ever deploy a server, since that server will be unable to recover from crashes or reboots, and clients will lose data.

**Comment by junxfl** [comment]
Thank you very much. I'll continue to test.
