### ISSUE TITLE
Python web based framework under GlusterFS+NFS Ganesha?

### ISSUE THREAD

**Issue by BzMB** [nfs-ganesha/nfs-ganesha#190]
Hi there,

During the implementation of a GlusterFS cluster (3 node replicated) we find out that our glusterfs client suffer from reading small files from the gluster volume (sessions files, .py files). 

2 GlusterFS client one per each vm instance in which we run execute the python framework.

Seems that GlusterFS is very good with the large static but is very bad with small files.

Switching/putting on top the NFS Ganesha will give us the speed improvements that we need in order 
to run smoothly the python web based framework ?

Will you install nfs-ganesha on:
1) the first glusterfs node only
2) all the 3 replicated nodes
3) on it's own server (so in case of failover you can switch between the replicated nodes accordingly)

If so, do you recommend this tutorial to start with?
http://blog.gluster.org/2015/10/linux-scale-out-nfsv4-using-nfs-ganesha-and-glusterfs-one-step-at-a-time/

_GlusterFS volume info
Volume Name: XXXXXXXXXXX
Type: Replicate
Volume ID:XXXXXXXXXXXXXXXXXXXXX
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 3 = 3
Transport-type: tcp
Bricks:
Brick1: node01:/mnt/disks/brick01sdb/XXXXXXXXXXX
Brick2: node02:/mnt/disks/brick02sdb/XXXXXXXXXXX
Brick3: node03:/mnt/disks/brick03sdbt/XXXXXXXXXXX
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
diagnostics.latency-measurement: on
diagnostics.count-fop-hits: on_

We hope to receive some advice and guidance.

Apologies in advance for the rookie questions!

Thanks.

**Comment by soumyakoduri** [comment]
Hi,

NFS-ganesha server is typically started on the same nodes where glusterfs servers are running (though its not mandatory). If you need high-availability,  then please choose any >=3 nodes (to maintain cluster quorum) and  configure nfs-ganesha servers on them. 

Yes.. you can refer to he blog link which you have mentioned above or its documented even in glusterdocs on how to setup stand-alone or clustered nfs-ganesha server - http://gluster.readthedocs.io/en/latest/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/

**Comment by dattah** [comment]
Hi, 

Thank you so much for your technical advise.

In your opinion, do you think that our performance will improve by adding NFS Ganesha ?

_Seems that GlusterFS is very good with the large static but is very bad with small files.

Switching/putting on top the NFS Ganesha will give us the speed improvements that we need in order
to run smoothly the python web based framework ?_

Thanks.

**Comment by BzMB** [comment]
Hi,

Thank you so much for your advise.

In your opinion, we can achieve improvements by swtiching to NFS-ganesha from glusterfs at client level?

_Seems that GlusterFS is very good with the large static but is very bad with small files.

Switching/putting on top the NFS Ganesha will give us the speed improvements that we need in order
to run smoothly the python web based framework ?_

thanks.

**Comment by soumyakoduri** [comment]
From the tests carried out so far by our team, the results always favoured glusterfs native client (this may change in near future as we are working on improving nfs-ganesha performance)  and the assumption was that the gluster native client performs better compared to NFS-Ganesha. It is interesting to know that your particular work-load scales well with NFS-Ganesha.

What version of NFS-Ganesha are you using? If you really like to use gluster native client, I suggest to send out mail to gluster-users@gluster.org. May be there are some tunings available which other community developers may recommend to improve small-files work-load on native client.

**Comment by BzMB** [comment]
Thanks to share your feedbacks.
At the moment we're profiling and monitoring with the glusterfs native client only.
We will definitely send an email to the gluster user mail suggested.

The framework that we would like to run under glusterFS architecture is this one:
https://github.com/odoo/odoo

We want to pass from a pure NFS implementation (single point of failure) to a glusterFS implementation but we'll need to address the [small file](https://access.redhat.com/documentation/en-US/Red_Hat_Storage/3/html/Administration_Guide/Small_File_Performance_Enhancements.html) issue before considering to add the NFS-ganesha capability "on top" of it.

**Comment by guihecheng** [comment]
@soumyakoduri Hi soumya, we are also interested in improving nfs-ganesha + glusterfs performance. We got the same result as you that glusterfs-gNFS performs better than glusterfs-nfs-ganesha (nfs-ganesha 2.4.1 glusterfs 3.8.4). And Matt told me that you are working on gfapi *_aysnc apis, do you think nfs-ganesha also needs some work to be done (e.g. we should at least have a send/recv threads model for async calls)?

**Comment by dang** [comment]
work on async in ganesha is also underway.  That's the big changes due for 2.6.

**Comment by guihecheng** [comment]
@dang thanks for reply, nice to hear that !

**Comment by ffilz** [comment]
Closing since async is implemented though not in any FSAL yet.
