### ISSUE TITLE
FSAL module linking

### ISSUE THREAD

**Issue by DarkHaze** [nfs-ganesha/nfs-ganesha#191]
I'm getting linking error in fsal modules (any fsal module) 'undefined symbol: component_log_level'

`Jul 27 11:08:58 artur-dragon nfs-ganesha[18953]: [main] load_fsal :NFS STARTUP :CRIT :Could not dlopen module:/home/artur/local/lib/ganesha/libfsalvfs.so Error:/home/artur/local/lib/ganesha/libfsalvfs.so: undefined symbol: component_log_level
Jul 27 11:08:58 artur-dragon nfs-ganesha[18953]: [main] load_fsal :NFS STARTUP :MAJ :Failed to load module (/home/artur/local/lib/ganesha/libfsalvfs.so) because: Can not access a needed shared library
Jul 27 11:08:58 artur-dragon nfs-ganesha[18953]: [main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
`

The symbol is defined in ganesha.nfsd, but somehow dlopen can't use it.

My system is ubuntu 17.04 with kernel 4.10.0-28-generic. This problem doesn't occur on ubuntu 16.04.

Ganesha version 
NFS-Ganesha Release = V2.5.1
ganesha.nfsd compiled on Jul 27 2017 at 10:59:09
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P

**Comment by dang** [comment]
This sounds like a change in how the linker or loader behaves.  What version of gcc and binutils do you have?  Do you set LD_LIBRARY_PATH?  If not, can you try setting it?

**Comment by DarkHaze** [comment]
It's not the problem with finding library (directory with fsal libraries is in added in ld.so.conf). The strange thing is that using ganesha.nfsd compiled on ubuntu 16.04 resolves the problem. All other libraries are compiled locally on ubuntu 17.04.

Switching compiler to gcc-5.4 didn't help.

Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.3.0-12ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 
GNU ld (GNU Binutils for Ubuntu) 2.28

**Comment by dang** [comment]
I wonder if it's being bitten by -z now.  Can you try building with these LDFLAGS:

LDFLAGS=-Wl,-z,lazy

**Comment by DarkHaze** [comment]
It's the same.

Below output from make VERBOSE=1 with linking of ganesha.nfsd (to show that -Wl,-z,lazy is used).

`/usr/lib/ccache/cc   -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wall -Wimplicit -Wformat -Wmissing-braces -Wreturn-type -Wunused-variable -Wuninitialized -Wno-pointer-sign -Wno-strict-aliasing -g  -Wl,-z,lazy CMakeFiles/ganesha.nfsd.dir/nfs_main.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_convert.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/commonlib.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_manager.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/access_check.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_config.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/default_methods.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/common_pnfs.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_destroyer.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_helper.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_top.c.o CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_async.c.o  -o ganesha.nfsd -Wl,-rpath,/usr/lib/x86_64-linux-gnu/mit-krb5:/home/artur/work/lizardfs-closed/external/nfs-ganesha-2.5-stable/src/build/libntirpc/src:  libMainServices.a ../Protocols/NFS/libnfsproto.a ../Protocols/RQUOTA/librquota.a ../Protocols/NLM/libnlm.a ../Protocols/9P/lib9p.a ../Protocols/XDR/libnfs_mnt_xdr.a ../SAL/libsal.a ../idmapper/libidmap.a ../avl/libavltree.a ../hashtable/libhashtable.a ../RPCAL/librpcal.a ../support/libsupport.a ../Protocols/NFS/libnfs4callbacks.a ../cidr/libcidr.a ../support/libstring_utils.a ../support/libhash.a ../log/liblog.a ../support/libuid2grp.a ../support/libnetgroup_cache.a ../FSAL/FSAL_PSEUDO/libfsalpseudo.a ../FSAL/Stackable_FSALs/FSAL_MDCACHE/libfsalmdcache.a ../config_parsing/libconfig_parsing.a -ljemalloc ../os/libgos.a -ldl /usr/lib/x86_64-linux-gnu/mit-krb5/libkrb5.so /usr/lib/x86_64-linux-gnu/mit-krb5/libk5crypto.so -lcom_err /usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so -lpthread -lrt ../libntirpc/src/libntirpc.so.1.5.3 -ljemalloc /usr/lib/x86_64-linux-gnu/mit-krb5/libkrb5.so /usr/lib/x86_64-linux-gnu/mit-krb5/libk5crypto.so -lcom_err /usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so -lrt -lnsl -lpthread `

**Comment by DarkHaze** [comment]
I solved the problem. Recently for some tests I removed -rdynamic from linking flags generated by cmake (by editing cmake modules). This was causing problem in genesha with modules linking.
With this flag everything is working correctly. Sorry for wasting your time :).

**Comment by dang** [comment]
Glad you figured it out, and that it's not a bigger problem.
