### ISSUE TITLE
VFS: cannot write mount vers=4.2

### ISSUE THREAD

**Issue by wongma7** [nfs-ganesha/nfs-ganesha#192]
Hi, I have run into a weird error where I cannot write to the VFS export when I have mounted it with vers=4.2. Reading is fine, though.

e.g.: 
127.0.0.1:/home/mawong/pvc on /home/mawong/Documents/42 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
```sh
$ touch 42/test
touch: setting times of '42/test': No such file or directory
$ mkdir 42/test
mkdir: cannot create directory ‘42/test’: Invalid argument
$ echo hello > 42/test
bash: 42/test: Invalid argument
```

Tested vers 4.0, 4.1, & 3.0 to work fine. I don't know how to debug this so any hints would be appreciated!

Versions:
NFS-Ganesha Release = V2.4.1
mount.nfs: (linux nfs-utils 2.1.1)

Export entry:
```
EXPORT
{
	Export_Id = 1;
	Path = /home/mawong/pvc
	Pseudo = /home/mawong/pvc
	Access_Type = RW;
	Squash = no_root_squash;
	SecType = sys;
	Filesystem_id = 1.1;
	FSAL {
		Name = VFS;
	}
}
```

**Comment by ffilz** [comment]
I can't guarantee that we have a proper trivial 4.2 implementation. The only actual 4.2 work that has been done so far has been for FSAL_GPFS and I'm not even sure that necessarily works with the latest client (there hasn't been an update in at least a year, maybe even a couple years).

**Comment by wongma7** [comment]
I see, thanks. I didn't realize the spec was as new as it is, sucks for me that my machine has started defaulting to 4.2 but I can work around it easily.

**Comment by ffilz** [comment]
We really need to disable Ganesha defaulting to responding with 4.2 support... Or make the trivial implementation work.

**Comment by stephen-9** [comment]
Hi folks,
The new default to 4.2 isn't specific to Fed26, it comes with kernel updates for Fedora releases still in support. The oldest I've verified is 4.10.17-100 (Fed24). We're working on enforcing a minorversion with autofs. I haven't found any documentation that says anything besides major nfs versions is supported by the ganesha.conf file.

**Comment by wongma7** [comment]
ok, it will be more widespread then, let's keep open so confused people like me can find this.

**Comment by ffilz** [comment]
Should we re-examine our state of 4.2 support and make sure there are no gotchas?

**Comment by ffilz** [comment]
I think we still need to consider V4.2 validation.
