### ISSUE TITLE
 Mount timeout after restart

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#196]
I am using the nfs-ganesha v2.5.1.1.

At client side, I mount nfs-ganesha. Then unmount it. Now I restart nfs-ganesha and try again from the same client to
mount. But the first attempt to mount after restart always time out. In the log file, I see the error:

ganesha.nfsd-16761[decoder] thr_decode_rpc_request :DISP :DEBUG :0x1f1efa0 context (nil)
ganesha.nfsd-16761[decoder] thr_decode_rpc_request :DISP :DEBUG :Client on socket=32, addr=<unresolved> has status
XPRT_IDLE
ganesha.nfsd-16761[decoder] thr_decode_rpc_requests :DISP :DEBUG :exiting, stat=XPRT_IDLE

If I cancel mount command, and try again it always work. What could be the issue here? 

I am using TCP protocol and version 4. FSAL=Ceph.

**Comment by supriti** [comment]
Analyzing the tcpdump from client and server side, the client send the following request at mount time:
```
V4 Call RENEW CID:
V4 Call PUTROOTFH |GETATTR
```

But in the server log, it looks like its treated as new client connection. 
```
nfs_rpc_getreq_ng :DISP :F_DBG :An initial NFS TCP request from a new client 32
thr_decode_rpc_requests :RPC :F_DBG :enter xprt=0x21cbee0
thr_decode_rpc_request :DISP :DEBUG :0x21cbee0 context (nil)
thr_decode_rpc_request :DISP :F_DBG :SVC_RECV on socket 32 returned false, xid=0
thr_decode_rpc_request :DISP :DEBUG :Client on socket=32, addr=<unresolved> has status XPRT_IDLE
ganesha.nfsd-2487[decoder] thr_decode_rpc_requests :DISP :DEBUG :exiting, stat=XPRT_IDLE
```
From code, this error occurs if its a new client connection. From the client side, it looks like it is trying to renew the old connection.

**Comment by ffilz** [comment]
What's happening at the tcp level in the tcpdump?

**Comment by supriti** [comment]
after doing a fresh installation I am unable to reproduce it. Closing for now.
