### ISSUE TITLE
 Input/output error when cp files over NFS for RGW

### ISSUE THREAD

**Issue by HIK-GYK** [nfs-ganesha/nfs-ganesha#197]
Hi 
I have ceph 12.0.2 and ganesha v2.5 stable installed in centos 7.2.
The export configure file is that:

EXPORT
{
    Export_ID=1;
    Path="/";
    Psseudo=/cephfs;
    Access_Type=RW;
    Squash=No_Root_Squash;
    FSAL{
              Name=CEPH
     }
}
EXPORT
{
    Export_ID=2;
    Path="/";
    Psseudo=/rgw;
    Access_Type=RW;
    Squash=No_Root_Squash;
    FSAL{
              Name=RGW;
              User_Id="test";
              Access_Key_Id="123456";
              Secret_Access_Key="123456";
     }
}
RGW{
          ceph_conf="/etc/ceph/ceph.conf";
}

and I start ganesha :
ganesha.nfsd -F -L /var/log/ganesha.log -N NIV_DEBUG

then mount:
mount -t nfs dev1:/  /mnt/ganesha

but when I want to copy some files to /mnt/ganesha/rgw/bucket1 , the process always broken because
the Input/output error like that:
cp: error writing ' /mnt/ganesha/rgw/bucket1/file1.txt': Input/output error
cp:failed to extend '/mnt/ganesha/rgw/bucket1/file1.txt':Input/output error

and I find this problem usually caused with the files's size big than 50MB, if reduce files' size  to 100Kb, the problem won't happen.

how can I fix it?

**Comment by HIK-GYK** [comment]
my copy commands is that:

cp /mnt/ganesha/rgw/bucket2/file1.txt   /mnt/ganesha/rgw/bucket1/

**Comment by guihecheng** [comment]
You could try mount with -o sync as FSAL_RGW only supports ordered write for now.

**Comment by HIK-GYK** [comment]
I got  that . thank you very much !

**Comment by QuantumEnergyE** [comment]
Hi，
I met the same problem， but can't fix with *-o sync*
ceph: 12.2.0-9
ganesha: v2.5 stable
```

EXPORT
{
        Export_ID=1;

        Path = "/";

        Pseudo = "/";

        Access_Type = RW;

        Squash = No_root_squash;

        NFS_Protocols = 4;

        Transport_Protocols = TCP;

        FSAL {
                Name = RGW;
                User_Id = "test_user";
                Access_Key_Id ="TX10VPXABL0Q8ZW83LU9";
                Secret_Access_Key = "HN1ROqZh18BQ2IV9XmPlUfVqh3ofsW91WwqCCDoK";
        }
}

RGW {
    ceph_conf = "/etc/ceph/ceph.conf";
    name = "client.rgw.host1";
}
```
> mount -t nfs -o sync  192.168.10.100:/ /mnt/test/
> cp 1.iso 2.iso
cp: error reading ‘1.iso’: Input/output error

**Comment by HIK-GYK** [comment]
Hi, this issue is caused by unordered writes , please refer to #204
