### ISSUE TITLE
FSAL_CEPH nfs-ganesha 2.4.5-7 source rpm build failure

### ISSUE THREAD

**Issue by pdvian** [nfs-ganesha/nfs-ganesha#201]
The nfs-ganesha-2.4.5-7.el7cp.src.rpm is failing while compiling and giving error fsal_obj_handle has no member 'handle'

[ 78%] Built target fsalmdcache
make -f FSAL/FSAL_PSEUDO/CMakeFiles/fsalpseudo.dir/build.make FSAL/FSAL_PSEUDO/CMakeFiles/fsalpseudo.dir/depend
make[2]: Entering directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
cd /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_PSEUDO /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_PSEUDO /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_PSEUDO/CMakeFiles/fsalpseudo.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
make -f FSAL/FSAL_PSEUDO/CMakeFiles/fsalpseudo.dir/build.make FSAL/FSAL_PSEUDO/CMakeFiles/fsalpseudo.dir/build
make[2]: Entering directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
make[2]: Nothing to be done for `FSAL/FSAL_PSEUDO/CMakeFiles/fsalpseudo.dir/build'.
make[2]: Leaving directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
/usr/bin/cmake -E cmake_progress_report /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/CMakeFiles  24
[ 79%] Built target fsalpseudo
make -f FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build.make FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/depend
make[2]: Entering directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
cd /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
make -f FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build.make FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/build
make[2]: Entering directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
/usr/bin/cmake -E cmake_progress_report /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/CMakeFiles 
[ 79%] Building C object FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/handle.c.o
cd /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH && /usr/bin/cc  -D_FILE_OFFSET_BITS=64 -Dfsalceph_EXPORTS -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic  -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -DNDEBUG -fPIC -I/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/include -I/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/include/os/linux -I/include -I/usr/include/ntirpc    -o CMakeFiles/fsalceph.dir/handle.c.o   -c /root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH/handle.c
/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH/handle.c: In function 'ceph_fsal_readdir':
/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src/FSAL/FSAL_CEPH/handle.c:186:30: error: 'struct fsal_obj_handle' has no member named 'handle'
    cb_rc = cb(de.d_name, &obj->handle, &attrs, dir_state,
                              ^
make[2]: *** [FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/handle.c.o] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
make[1]: *** [FSAL/FSAL_CEPH/CMakeFiles/fsalceph.dir/all] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/nfs-ganesha-2.4.5/src'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.Xz5b41 (%build)

**Comment by ajarr** [comment]
Is this still an issue?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
