### ISSUE TITLE
FSAL_CEPH: Unable to create or write to file, even if Acces Type is RW for all clients.

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#203]
I assume if the Access_Type is RW, then at client side, we should be able to create file. But I am unable to do so. Only when I add Squash = No_root_squash;, I am able to create file. Is this expected behavior? 

I use the following mount command: mount -t nfs -o nfsvers=4 server:/ /mnt

EXPORT
{
     Export_ID=1;
     Path = /;
     Pseudo = /cephfs/;
    Access_Type = RW;
    Protocols = 3, 4;
    Transports = UDP, TCP;
    FSAL {
            Name = CEPH;
    }
}

**Comment by ffilz** [comment]
Are you just writing files using root on client, or other users on client?

What are the directory permissions where you are trying to create files?

Ganesha defaults to root squash, which means root will be translated to anon_uid/anon_gid (defaults for those are -2 - well, the unsigned equivalent...).

**Comment by dang** [comment]
The user that root is squashed to needs to have permission in CephFS to write, as well.

**Comment by supriti** [comment]
I mounted using root. I used just touch command to create files. My setup is broken now, and I can not verify if the issue is fixed. So closing the issue for now. Will reopen in case, I see it again.

**Comment by supriti** [comment]
I see the issue again.

Case 1: Using option, Access_Type = RW; and NOT using Squash = No_root_squash;.
I mount as root user. 
```
# mount -t nfs -o rw nfs-ganesha-server:/ /mnt/cephfs
/mnt # ls -l
total 1
drwxr-xr-x 1 root root 0 Sep 21 14:48 cephfs

#/mnt/cephfs # ls -l
total 1
-rw-r--r-- 1 root root 29 Sep 21 14:48 hello.txt
-rw-r--r-- 1 root root 30 Sep 21 14:40 test1.txt
```
I am unable to create or write to file.

Case 2:  Using option Squash = No_root_squash
I am able to create and write to file. The files and directory permission are same.

**Comment by dang** [comment]
Based on the permissions shown, that directory is only writable by root.  So, with squashing on (the default), you should *not* be able to write there.  With squashing off (case 2), you should be able to write.  So everything looks like it's working properly.
