### ISSUE TITLE
FSAL_RGW: unable do write: bs>256k

### ISSUE THREAD

**Issue by HIK-GYK** [nfs-ganesha/nfs-ganesha#204]
environment: ceph 12.1.3 , ganesha-next
mount cmd:  mount -t nfs -o sync dev1:/ /mnt/ganesha 

 call glibc function write as: 
   ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
            int fd, UINT_SIZE = 1024*1024;
            int size;
            char *buf = malloc(UINT_SIZE);
            memset(buf,UINT_SIZE,0);
            
            fd = open("/mnt/ganesha/rgw/bucket1/test.log",O_CREAT|O_RDWR|O_SYNC,0666);
            
            if(fd<0){
                     printf("open fd failed,error %s %d\n", strerror(errno),errno);
             }else{
                     for(int i=0;i<1000;i++)
                       {
                           size = write(fd,buf,UINT_SIZE);
                           if(size<0)  printf("write fd error: %d %s %d\n",i,strerror(errno),errno);
                           printf("write success: %d",i);    
                        }
             }
   ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
   I found that the write will always success if set UINT_SIZE <= 256K,but if set  UINT_SIZE>256K, e.g. 1M ,EIO will happen. 
   by gdb I found the problem caused before ganesha's server get the request data, the variable stable_how4 of struct WRITE4args already be UNSTABLE4.
   how can I fix it?

**Comment by dang** [comment]
You can see some of the limitations of FSAL_RGW here: https://github.com/ceph/ceph/blob/master/doc/radosgw/nfs.rst#supported-operations  However, you're using -o sync already, so it *should* be a synchronous mount.  Maybe you have a limit in your RGW config that maxes out at 256K for some reason?

**Comment by HIK-GYK** [comment]
I found the limitation of 256k is not the problem, the problem is when bs>256k, the write will be divide to several times. Such as , 260k ,the first write offset = 0, size = 256k , the second write ,offset = 256k , size = 4k. However,  the offset and size have probability wrong before they are passed to worker_run() function.

**Comment by HIK-GYK** [comment]
well， the reason for this problem  is multi-threads for write op not run sequential,   to fix this problem , an independent thread judgment must be provided to the RGW.

**Comment by dang** [comment]
There is work underway to make RGW writes truly random, but this is a large amount of work.  For now, there are limitation in what FSAL_RGW can do, and I think this is one of them.

**Comment by HIK-GYK** [comment]
@dang First of all , thanks for your reply.
   I think this problem seriously affects the normal use  of FSAL_RGW. If you copy some files big than 256K, EIO will always happen beacause  copy is just read then write. And  the application scenario of copy files or directories is quite common.
  To fix it, can I add a judgement that if the next request to process is write and the file to write is same with the processing request, then put the next request in a wait queue , before  the worker threads run?

**Comment by dang** [comment]
Normal I/O, including tar (modulo a bug in GNU tar) and whatnot, seems to work fine in our testing, so this isn't a common problem with big writes, at least in any test setup we've had.  I think this will have to wait until @mattbenjamin is back from vacation.

**Comment by guihecheng** [comment]
@HIK-GYK hi, there is a patch on librgw side, which may serve as a temporary solution for unordered writes, https://github.com/ceph/ceph/pull/15623, maybe you could try it out ;)

**Comment by HIK-GYK** [comment]
I'm trying to use your solution, thank you very much for your reminding!

**Comment by HIK-GYK** [comment]
@guihecheng  I have tried your method, and the write process seems  good, but when the write were finished, I found the size of files are wrong. Thus I think we can't make sure the processing of write to these files were right.

**Comment by HIK-GYK** [comment]
@guihecheng  Uh... your code is right, now my problem is fixed, thanks a lot !
