### ISSUE TITLE
FSAL_XFS issue on kernel v2.6.32

### ISSUE THREAD

**Issue by xiankevin** [nfs-ganesha/nfs-ganesha#210]
I was trying to run ganesha.nfsd on CentOS 6.x with kernel v2.6.32.
As what is mentioned in wiki, FSAL_VFS is not supported on kernels earlier than v2.6.39 and I configured ganesha.nfsd with FSAL_XFS instead.
It seemed to be ok just after ganesha.nfsd started. I can mount the exported directory through NFSv3 protocol. However, after a short while, it could be weird. I got an error message "mount.nfs: an incorrect mount option was specified" when trying to mount.
I examined stace output and found some clue. The systemcall fstatat with flag AT_EMPTY_PATH is not supported. It said the flag AT_EMPTY_PATH was also introduced since kernel v2.6.39.

How can I run ganesha.nfsd on CentOS 6.x without upgrading the kernel?

Any help would be appreciated. Thanks a lot in advance!

My ganesha.conf file is shown below.

EXPORT {
  Export_Id = 10001;
  Protocols = 3;
  Path = /data1/nfs/app_data;
  Squash = No_Root_Squash;
  Access_Type = RW;
  FSAL {
    Name = XFS;
  }
}

**Comment by ffilz** [comment]
Hmm, I’m not sure anyone had really noticed that before…

 

Unfortunately, I think the answer is the only way to use Ganesha on a CentOS 6.x kernel is to use FSAL_GPFS (which uses an fcntl interface to implement open by handle and stat by handle). I’m not sure if FSAL_GLUSTER is supported on CentOS 6.x.

 

Frank

**Comment by ffilz** [comment]
Closed as will not fix.
