### ISSUE TITLE
mount ganesha NFSV4 then Set Ceph RGW quotas,but Client's I/O is blocking

### ISSUE THREAD

**Issue by jeremyzhou2001** [nfs-ganesha/nfs-ganesha#211]
1.config the ganesha configration file,and start ganesha
2.client mount nfs v4,upload some files
3.set quotas
**radosgw-admin quota set --uid=testuser --quota-scope=bucket  --bucket=second_bucket --max-size=100**
4.touch a new file, write some words
5.client IO is blocking

![ganesha-quota-block](https://user-images.githubusercontent.com/29558548/30675934-0add5fb6-9eb6-11e7-8d96-8a66158e3260.jpg)

**Comment by dang** [comment]
This is expected behavior, I think.  The default for --max-size (with no suffix) is bytes, so you've set the quota to 100 bytes, so writing almost anything will exceed your quota.

**Comment by jeremyzhou2001** [comment]
@dang is it a expected behavior?
100 bytes is just a quota, we can set 1GB, but IO should not block , i suggest give a  tips "not enough space" to alert clients
clients can not read write,even can not use cmd ls files. use cmd 
**radosgw-admin quota set --uid=testuser --quota-scope=bucket --bucket=second_bucket --max-size=1000000000000**
clients remain blocking status

**Comment by dang** [comment]
Quota is a hard limit.  You cannot write past your quota.  You're right that the client should probably get an error; but that's not something that Ganesha can control, since the IO was just submitted to Ceph.  At any rate, the IO should definitely not succeed when it goes over quota.

I suspect that quota is not working properly yet with RGW.  It's still in early stages of development, and only intended for certain types of workloads.  Quota is lot listed as supported here:
https://github.com/ceph/ceph/blob/master/doc/radosgw/nfs.rst

Maybe open a feature request on the Ceph project?

**Comment by jeremyzhou2001** [comment]
@dang 
RGW  both of user and bucket scopes do have the return code.

if (bucket_quota.enabled) {
      RGWStorageStats bucket_stats;
      int ret = bucket_stats_cache.get_stats(user, bucket, bucket_stats,
                                           bucket_quota);
      if (ret < 0) {
        return ret;
      }
      **ret = check_quota("bucket", bucket_quota, bucket_stats, num_objs, size);
      if (ret < 0) {
        return ret;
      }**
    }

    if (user_quota.enabled) {
      RGWStorageStats user_stats;
      int ret = user_stats_cache.get_stats(user, bucket, user_stats, user_quota);
      if (ret < 0) {
        return ret;
      }
      **ret = check_quota("user", user_quota, user_stats, num_objs, size);
      if (ret < 0) {
        return ret;
      }**
    }
    return 0;
  }

can u give me some tips of ganesha source code, 
do u have compared the performance between ganesha mount and kernel mount？

**Comment by dang** [comment]
Ganesha doesn't call through the HTTP interface, it uses a library interface that generates RADOS directly.  The callpath Ganesha uses is rgw_write().  Looking at this callpath, it does check quota in the exec finisher, but I'm not sure if that's early enough or not, I'm not an expert on this interface.  At any rate, it doesn't look like the hang can be in ganesha, it just calls into librgw and returns the result.

@mattbenjamin do you have a comment on this?

**Comment by mattbenjamin** [comment]
@dang @jeremyzhou2001 my impressions are a) that it should be safe (and desirable for performance reasons) to check quota only once in exec_finish;  b) that blocking in this codepath is unexpected and needs to be root caused; regardless of the quota state at any point in the execution of the RGWPutObjProcessor, we expect it's operation to eventually terminate, releasing the client threaed.

**Comment by jeremyzhou2001** [comment]
@mattbenjamin @dang 
do u have any plan on it?
I am looking for a cloud storage gateway which can work with ceph, I writed a mail to Sage Weil in August, He suggested me to get know ganesha. So i have some test on ganesha and Ceph recently

**Comment by ffilz** [comment]
Is this still relevant?

**Comment by ffilz** [comment]
Closing with no response  in 30 days and does not appear to be an ongoing issue.
