### ISSUE TITLE
nfs-ganesha service fails to start on CentOS 7.4 due to permission denied on /var/log/ganesha

### ISSUE THREAD

**Issue by djgalloway** [nfs-ganesha/nfs-ganesha#212]
SELinux is preventing nfs-ganesha.service from starting on CentOS 7.4 due to a dac_override denial when attempting to create /var/log/ganesha/ganesha.log.

/var/log/ganesha is owned by ganesha:ganesha but the systemd unit files attempt to start the service as root:root.

If nfs-ganesha can't be run as a non-privileged user as suggested by https://github.com/nfs-ganesha/nfs-ganesha/commit/58877b02576334e9f9b21b2dec881031db7db49c then /var/log/ganesha should be owned by root:root during post-install.

**Comment by soumyakoduri** [comment]
+@nixpanic +@kalebskeithley 

 58877b0 was done to add ability to run nfs-ganesha as non-root user. We faced similar issue in our centos CI upstream tests. Maybe as stated in http://danwalsh.livejournal.com/69478.html, the right fix is to change owning group of this folder to root .. that way both root and ganesha user shall have access to log. Request Niels/Kaleb to comment.

**Comment by nixpanic** [comment]
If changing the ownership of `/var/log/ganesha` from `ganesha:ganesha` to `root:ganesha` solves the problem when nfs-ganesha runs as root, I'm fine with getting that changed.

Please try it out and report back with the results.

**Comment by nixpanic** [comment]
After reading the blog post, it may make more sense to change the permissions to `ganesha:root` instead. Either way, once tested we can send a patch for the `.spec` to change it.

**Comment by kalebskeithley** [comment]
agree, change owner to ganesha.root seem to be the preferred solution according to the danwalsh blog.

**Comment by kalebskeithley** [comment]
https://review.gerrithub.io/379661

**Comment by kalebskeithley** [comment]
AVC denial of /var/log/ganesha/ganesha.log create when SELinux is in enforcing mode. 

http://danwalsh.livejournal.com/69478.html suggests the correct owner of /var/log/ganesha should be ganesha.root and does not require any SELinux tweaks. (Quick test on CentOS 7.4 box seemed to work.)

But after several hours of wrangling with selinux devs it seems that's a Red Herring. SELinux created the ganesha_var_log_t type to allow ganesha.nfsd to write its log file to /var/log/ganesha.log. But having moved the logs to /var/log/ganesha/... we apparently need to apply this type to the (new) directory in order for the ganesha.nfsd to write its log files. 

See https://bugzilla.redhat.com/show_bug.cgi?id=1494670
