### ISSUE TITLE
nfs-ganesha 2.5.2 under certain conditions crashes a lot

### ISSUE THREAD

**Issue by f1-outsourcing** [nfs-ganesha/nfs-ganesha#215]
When i do an rsync of a distribution centoslinux/7/os/x86_64/ onto nfs ganesha share with cephfs backend, it just crashes without copying one file. I think this has to do maybe because rsync is reading a lot of remote and local files first to compare. Because 'smaller' rsync seem to go fine.

I am running the binaries the people of redhat packaged for ceph. 

nfs-utils-1.3.0-0.33.el7_3.x86_64
libnfsidmap-0.25-15.el7.x86_64
nfs-ganesha-2.5.2-.el7.x86_64
nfs-ganesha-xfs-2.5.2-.el7.x86_64
nfs-ganesha-ceph-2.5.2-.el7.x86_64

```
[root@c01 ganesha]# /usr/bin/ganesha.nfsd -f /etc/ganesha/ganesha.conf -F -C
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.1/rpm/el7/BUILD/ceph-12.2.1/src/client/Client.cc: In function 'int Client::ll_setattrx(Inode*, ceph_statx*, int, const UserPerm&)' thread 7f7b98ff9700 time 2017-09-30 18:46:47.715601
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.1/rpm/el7/BUILD/ceph-12.2.1/src/client/Client.cc: 10564: FAILED assert(in == target.get())
 ceph version 12.2.1 (3e7492b9ada8bdc9a5cd0feafd42fbca27f9c38e) luminous (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x110) [0x7f7c30bbe180]
 2: (()+0x6a447) [0x7f7c3962c447]
 3: (()+0x4cc6) [0x7f7c398d8cc6]
 4: (ceph_setattr2()+0x767) [0x7f7c398de6bd]
 5: /usr/bin/ganesha.nfsd() [0x53c6ee]
 6: (fsal_setattr()+0x326) [0x43168e]
 7: (nfs4_op_setattr()+0x3c0) [0x4805e3]
 8: (nfs4_Compound()+0xa1e) [0x45f890]
 9: (nfs_rpc_execute()+0x1d6c) [0x44c369]
 10: /usr/bin/ganesha.nfsd() [0x44cb73]
 11: /usr/bin/ganesha.nfsd() [0x508dda]
 12: (()+0x7dc5) [0x7f7c3ce2bdc5]
 13: (clone()+0x6d) [0x7f7c3c4ed76d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

**Comment by f1-outsourcing** [comment]
```
MDS_CLIENT_LATE_RELEASE 1 clients failing to respond to capability release
    mdsa(mds.0): Client c01:cephfs.nfs failing to respond to capability releaseclient_id: 2661726
```

**Comment by f1-outsourcing** [comment]
Opens multiple sessions?

```
[root@c01 ganesha]# ceph daemon mds.a session ls | egrep '(id|entity_id|inst)'
        "id": 2680000,
        "inst": "client.2680000 192.168.10.111:0/2464604986",
            "entity_id": "cephfs.nfs",
            "pid": "23509",
        "id": 2661729,
        "inst": "client.2661729 192.168.10.111:0/1324656044",
            "entity_id": "cephfs.nfs",
            "pid": "23509",
        "id": 2661726,
        "inst": "client.2661726 192.168.10.111:0/694827203",
            "entity_id": "cephfs.nfs",
            "pid": "23509",
        "id": 2661723,
        "inst": "client.2661723 192.168.10.111:0/2838669481",
            "entity_id": "cephfs.nfs",
            "pid": "23509",
        "id": 2661720,
        "inst": "client.2661720 192.168.10.111:0/3635118249",
            "entity_id": "cephfs.nfs",
            "pid": "23509",
        "id": 2680003,
        "inst": "client.2680003 192.168.10.111:0/2459043802",
            "entity_id": "cephfs.nfs",
            "pid": "23509",

```

**Comment by dang** [comment]
What version of ceph?  The actual assert is in ceph code, not in ganesha code, so the ceph version may be more important.

Also, can you install the ceph debug packages, so that the backtrace includes the ceph functions?

**Comment by supriti** [comment]
From backtrace the ceph version is ceph version 12.2.1 (3e7492b9ada8bdc9a5cd0feafd42fbca27f9c38e) luminous (stable)

**Comment by dang** [comment]
Okay, so this is an assert (in ceph) that the inode hasn't changed out from under us.  It looks like it can happen if mask == 0 (which probably shouldn't happen, but shouldn't assert regardless).  I'm pinging a cephfs guy to take a look.

**Comment by jtlayton** [comment]
Ok, so it hit this assertion in ll_setattrx, I think:

`
assert(in == target.get());
`
Basically that means that we got a request to issue a setattr vs. an inode, but the reply trace from the operation pertained to an entirely _different_ inode. Given that we should be holding references to the original inode, it seems like that shouldn't happen.

**Comment by jtlayton** [comment]
You may want to collect the info that @dang suggested and open a case at tracker.ceph.com.

**Comment by jtlayton** [comment]
Either way, none of these codepaths actually do anything with the "target" other than assert here. I have a draft patch to just remove that argument and the assertions. I think that's probably what we'll want to do.

This is almost certainly a race occurring in the MDS since it's what sends back the traces. Asserting on the client when it occurs doesn't really make much sense.

**Comment by jtlayton** [comment]
@f1-outsourcing : did you happen to have the ceph client.* logs for the ganesha instance that failed? I'm wondering if the setattr reply had no trace in it. In particular, I'm wondering whether any of the log messages from Client::verify_reply_trace might have popped up.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
