### ISSUE TITLE
Privileged mode when dynamic exports are used

### ISSUE THREAD

**Issue by jprovaznik** [nfs-ganesha/nfs-ganesha#219]
If I run ganesha in a container and I want to create an export (from openstack manila-share running in another container), it fails with error:
2017-10-06 13:25:24.697 40 ERROR oslo_messaging.rpc.server [req-e361d952-0f1b-4b86-9c8d-d34e052c4a31 5cd03ecc4d6f449aadaf123b3006d242 85789beb39b74940ab93cca7c626896e - - -] Exception during
 message handling: GaneshaCommandFailure: Ganesha management command failed.
Command: dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/export.d/share-08e4bf6c-2747-427d-9923-
3b2cd07ac7d8.conf string:EXPORT(Export_Id=102)
Exit code: 1

DBus is running on host machine and its socket is bindmounted to containers, ganesha systemd service is:
$ cat /etc/systemd/system/ceph-nfs\@.service
[Unit]
Description=NFS-Ganesha file server
Documentation=http://github.com/nfs-ganesha/nfs-ganesha/wiki
After=docker.service

[Service]
EnvironmentFile=-/etc/environment
ExecStartPre=-/usr/bin/docker rm ceph-nfs-%i
ExecStartPre=/usr/bin/mkdir -p /etc/ceph /etc/ganesha /var/lib/nfs/ganesha
ExecStart=/usr/bin/docker run --rm --net=host \
  -v /var/lib/ceph:/var/lib/ceph \
  -v /etc/ceph:/etc/ceph \
  -v /var/lib/nfs/ganesha:/var/lib/nfs/ganesha \
  -v /etc/ganesha:/etc/ganesha \
  -v /etc/localtime:/etc/localtime:ro \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  -e CLUSTER=ceph \
  -e CEPH_DAEMON=NFS \
   \
  --name=ceph-nfs-pacemaker \
  192.168.24.1:8787/ceph/daemon:latest
ExecStopPost=-/usr/bin/docker stop ceph-nfs-%i
Restart=always
RestartSec=10s
TimeoutStartSec=120
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target

If I run ganesha service in privileged mode (--privilege) it solves the issue. My question is if privileged mode is necessary or if there is other way to make dbus working with ganesha w/o privileged mode?

**Comment by dang** [comment]
On 10/13/2017 07:41 AM, Jan Provaznik wrote:
> If I run ganesha in a container and I want to create an export (from 
> openstack manila-share running in another container), it fails with error:
> 2017-10-06 13:25:24.697 40 ERROR oslo_messaging.rpc.server 
> [req-e361d952-0f1b-4b86-9c8d-d34e052c4a31 
> 5cd03ecc4d6f449aadaf123b3006d242 85789beb39b74940ab93cca7c626896e - - -] 
> Exception during
> message handling: GaneshaCommandFailure: Ganesha management command failed.
> Command: dbus-send --print-reply --system --dest=org.ganesha.nfsd 
> /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport 
> string:/etc/ganesha/export.d/share-08e4bf6c-2747-427d-9923-
> 3b2cd07ac7d8.conf string:EXPORT(Export_Id=102)
> Exit code: 1
> 
> DBus is running on host machine and its socket is bindmounted to 
> containers, ganesha systemd service is:
> 
> 
>   cat /etc/systemd/system/ceph-nfs@.service
> 
> [Unit]
> Description=NFS-Ganesha file server
> Documentation=http://github.com/nfs-ganesha/nfs-ganesha/wiki 
> <https://github.com/nfs-ganesha/nfs-ganesha/wiki>
> After=docker.service
> 
> [Service]
> EnvironmentFile=-/etc/environment
> ExecStartPre=-/usr/bin/docker rm ceph-nfs-%i
> ExecStartPre=/usr/bin/mkdir -p /etc/ceph /etc/ganesha /var/lib/nfs/ganesha
> ExecStart=/usr/bin/docker run --rm --net=host
> -v /var/lib/ceph:/var/lib/ceph
> -v /etc/ceph:/etc/ceph
> -v /var/lib/nfs/ganesha:/var/lib/nfs/ganesha
> -v /etc/ganesha:/etc/ganesha
> -v /etc/localtime:/etc/localtime:ro
> -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
> -e CLUSTER=ceph
> -e CEPH_DAEMON=NFS
> 
> --name=ceph-nfs-pacemaker
> 192.168.24.1:8787/ceph/daemon:latest
> ExecStopPost=-/usr/bin/docker stop ceph-nfs-%i
> Restart=always
> RestartSec=10s
> TimeoutStartSec=120
> TimeoutStopSec=15
> 
> [Install]
> WantedBy=multi-user.target
> 
> If I run ganesha service in privileged mode (--privilege) it solves the 
> issue. My question is if privileged mode is necessary or if there is 
> other way to make dbus working with ganesha w/o privileged mode?
> 

Could you try changing the <policy user="root"> line in 
/etc/dbus-1/system.d/org.ganesha.nfsd.conf to this:
<policy context="default">

This should allow "anyone" to own the ganesha dbus tree.  If this works, 
then maybe we can come up with some policy that works for inside 
containers.  If not, then unprivileged containers cannot own system dbus 
paths.

Daniel

**Comment by jprovaznik** [comment]
Unfortunately, with  <policy context="default"> I'm hitting the same error:
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.ganesha.nfsd was not provided by any .service files

**Comment by jprovaznik** [comment]
actually ignore my previous comment, after re-checking with properly applied change it seems it works fine

**Comment by dang** [comment]
Okay, I'll have to look into policy in more detail to see if we can have a shipable policy that allows access from containers, and still maintains security.

**Comment by ffilz** [comment]
Closed as will not fix. dbus and containers don't mix well.
