### ISSUE TITLE
fsal_dirs.c:166: error: cannot convert to a pointer type

### ISSUE THREAD

**Issue by knogbe** [nfs-ganesha/nfs-ganesha#22]
/libtirpc/tirpc/ -g -O2 -D_REENTRANT -Wall -Wimplicit -Wformat -Wmissing-braces -Wno-pointer-sign -I../../RPCAL/gssd -MT fsal_dirs.lo -MD -MP -MF .deps/fsal_dirs.Tpo -c fsal_dirs.c  -fPIC -DPIC -o .libs/fsal_dirs.o
fsal_dirs.c: In function âCEPHFSAL_readdirâ:
fsal_dirs.c:166: error: cannot convert to a pointer type
fsal_dirs.c:166: error: âcephfsal_cookie_tâ has no member named âcookieâ
fsal_dirs.c:167: error: cannot convert to a pointer type
fsal_dirs.c:167: error: âcephfsal_cookie_tâ has no member named âcookieâ
make[2]: *** [fsal_dirs.lo] Error 1
make[2]: Leaving directory `/root/nfs-ganesha-1.5.1/FSAL/FSAL_CEPH'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/nfs-ganesha-1.5.1/FSAL'

**Comment by ffilz** [comment]
Ganesha V1.5 is really only supported in any fashion for FSAL_GPFS. If there is still an issue with Ganesha V2.2.0 or later, open a Red Hat Bugzilla

https://bugzilla.redhat.com/enter_bug.cgi?product=nfs-ganesha
