### ISSUE TITLE
Error in Compiling nfs-ganesha under centos7.3 arch aarch64 

### ISSUE THREAD

**Issue by MrSate** [nfs-ganesha/nfs-ganesha#221]
I compile Ganesha in arm64 bit architecture CentOS7.3, Follow the steps on the wiki to compile .but when I  do make, I met some mistakes

make output:

[  1%] [  5%] [  5%] [  5%] [  6%] [  7%] [  8%] [  8%] [  8%] [  9%] [  9%] [  9%] [  9%] Built target string_utils
Built target hashtable
Built target avltree
Built target NodeList
Built target hash
Built target cidr
Built target gos
Built target config_parsing
Built target log
Built target nfs4callbacks
Built target fsal_os
Built target uid2grp
Built target idmap
[ 10%] Built target rpcal
[ 12%] Built target nfs_mnt_xdr
[ 14%] Built target fsalpseudo
[ 16%] [ 19%] Built target MainServices
Built target support
[ 22%] Built target nlm
[ 27%] Built target sal
[ 29%] [ 30%] [ 36%] Built target rquota
Built target fsalnull
Built target cache_inode
[ 48%] [ 63%] Built target 9p
Built target ntirpc
[ 64%] Built target fsalproxy
[ 65%] [ 66%] Built target fsalvfs
Building C object FSAL/FSAL_GLUSTER/CMakeFiles/fsalgluster.dir/fsal_up.c.o
[ 68%] Built target fsalpanfs
[ 72%] Built target fsalgpfs
[ 94%] Built target nfsproto
Scanning dependencies of target sm_notify.ganesha
Scanning dependencies of target ganesha.nfsd
[ 94%] Building C object Protocols/NLM/CMakeFiles/sm_notify.ganesha.dir/sm_notify.c.o
[ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 96%] [ 98%] [ 98%] [ 98%] /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c: In function ‘GLUSTERFSAL_UP_Thread’:
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:111:30: error: storage size of ‘callback’ isn’t known
  struct callback_arg         callback;
                              ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:197:8: error: ‘GFAPI_CBK_EVENT_NULL’ undeclared (first use in this function)
   case GFAPI_CBK_EVENT_NULL:
        ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:197:8: note: each undeclared identifier is reported only once for each function it appears in
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:200:8: error: ‘GFAPI_INODE_INVALIDATE’ undeclared (first use in this function)
   case GFAPI_INODE_INVALIDATE:
        ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:211:21: error: dereferencing pointer to incomplete type
    if (cbk_inode_arg->object)
                     ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:213:21: error: dereferencing pointer to incomplete type
        cbk_inode_arg->object);
                     ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:214:21: error: dereferencing pointer to incomplete type
    if (cbk_inode_arg->p_object)
                     ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:216:22: error: dereferencing pointer to incomplete type
         cbk_inode_arg->p_object);
                      ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:217:21: error: dereferencing pointer to incomplete type
    if (cbk_inode_arg->oldp_object)
                     ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:219:22: error: dereferencing pointer to incomplete type
         cbk_inode_arg->oldp_object);
                      ^
/root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:111:30: error: unused variable ‘callback’ [-Werror=unused-variable]
  struct callback_arg         callback;
                              ^
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/common_pnfs.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_utils.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/nfs_main.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_manager.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/default_methods.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_convert.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_top.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/commonlib.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL_UP/fsal_up_async.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_destroyer.c.o
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/access_check.c.o
cc1: all warnings being treated as errors
Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_config.c.o
make[2]: *** [FSAL/FSAL_GLUSTER/CMakeFiles/fsalgluster.dir/fsal_up.c.o] Error 1
make[1]: *** [FSAL/FSAL_GLUSTER/CMakeFiles/fsalgluster.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking C executable sm_notify.ganesha
[ 98%] Built target sm_notify.ganesha
Linking C executable ganesha.nfsd
[ 98%] Built target ganesha.nfsd
make: *** [all] Error 2

and cmake output:
-- cmake version 2.8
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected an UNKNOWN Linux machine
-- toolchain options processed
-- Compilation from within a git repository. Using git rev-parse HEAD
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- GFAPI_INCLUDE_DIRS=/usr/include/uuid;/usr/include/glusterfs
-- GFAPI_LIBRARY_DIRS=
CMake Warning at CMakeLists.txt:626 (message):
  Disabling SHOOK because it needs LUSTRE

-- Found nfs idmap library: /usr/lib64/libnfsidmap.so
-- Found Winbind4 client: 
-- OVERRIDE_INSTALL_PREFIX = 
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so;/usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- Found Winbind4 client: 
-- 
-- -------------------------------------------------------
-- TIRPC_EPOLL = ON
-- USE_RPC_RDMA = OFF
-- Using ntirpc submodule
/root/ganesha/nfs-ganesha/src/libntirpc/ntirpc/
-- 
-- -------------------------------------------------------
-- PLATFORM = LINUX
-- VERSION = 2.3.3
-- BUILD HOST = f08n29
-- -------------------------------------------------------
-- USE_FSAL_PROXY = ON
-- USE_FSAL_VFS = ON
-- USE_FSAL_CEPH = OFF
-- USE_FSAL_RGW = OFF
-- USE_FSAL_HPSS = OFF
-- USE_FSAL_XFS = OFF
-- USE_FSAL_PANFS = ON
-- USE_FSAL_GPFS = ON
-- USE_FSAL_PT = OFF
-- USE_FSAL_ZFS = OFF
-- USE_FSAL_LUSTRE = OFF
-- USE_FSAL_SHOOK = OFF
-- USE_FSAL_LUSTRE_UP = OFF
-- USE_FSAL_GLUSTER = ON
-- USE_FSAL_NULL = ON
-- USE_SYSTEM_NTIRPC = OFF
-- USE_DBUS = OFF
-- USE_CB_SIMULATOR = OFF
-- USE_NFSIDMAP = ON
-- ENABLE_ERROR_INJECTION = OFF
-- ENABLE_VFS_DEBUG_ACL = OFF
-- ENABLE_RFC_ACL = OFF
-- USE_CAPS = ON
-- USE_BLKID = ON
-- STRICT_PACKAGE = OFF
-- DISTNAME_HAS_GIT_DATA = OFF
-- _MSPAC_SUPPORT = ON
-- USE_EFENCE = OFF
-- _NO_TCP_REGISTER = ON
-- _NO_PORTMAPPER = ON
-- _NO_XATTRD = ON
-- DEBUG_SAL = OFF
-- _VALGRIND_MEMCHECK = OFF
-- PROXY_HANDLE_MAPPING = OFF
-- DEBUG_SYMS = OFF
-- COVERAGE = OFF
-- ENFORCE_GCC = OFF
-- PROFILING = OFF
-- USE_GSS = ON
-- TIRPC_EPOLL = ON
-- USE_9P = ON
-- _USE_9P = ON
-- _USE_9P_RDMA = OFF
-- USE_NFS_RDMA = OFF
-- KRB5_PREFIX = 
-- CEPH_PREFIX = 
-- RGW_PREFIX = 
-- HPSS_PREFIX = 
-- GLUSTER_PREFIX = /usr
-- ZFS_PREFIX = /usr
-- LUSTRE_PREFIX = /usr
-- CMAKE_PREFIX_PATH = /usr
-- _GIT_HEAD_COMMIT = 165fc33ad240a5d3147f1aedd2e3420ea700cdb4
-- _GIT_HEAD_COMMIT_ABBREV = 165fc33
-- _GIT_DESCRIBE = V2.3.3-0-g165fc33
-- ALLOCATOR = jemalloc
-- GOLD_LINKER = 
-- CMAKE_INSTALL_PREFIX = /usr
-- FSAL_DESTINATION = /usr/lib64/ganesha
-- USE_ADMIN_TOOLS = OFF
-- USE_GUI_ADMIN_TOOLS = ON
-- MODULES_PATH = 
-- USE_TSAN = OFF
-- USE_LTTNG = OFF
-- USE_BLKIN = OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /root/ganesha/nfs-ganesha/src

How can I solve this problem?

**Comment by dang** [comment]
On 10/19/2017 06:53 AM, MrSate wrote:
> I compile Ganesha in arm64 bit architecture CentOS7.3, Follow the steps 
> on the wiki to compile .but when I do make, I met some mistakes
> 
> make output:
> 
> [ 1%] [ 5%] [ 5%] [ 5%] [ 6%] [ 7%] [ 8%] [ 8%] [ 8%] [ 9%] [ 9%] [ 9%] 
> [ 9%] Built target string_utils
> Built target hashtable
> Built target avltree
> Built target NodeList
> Built target hash
> Built target cidr
> Built target gos
> Built target config_parsing
> Built target log
> Built target nfs4callbacks
> Built target fsal_os
> Built target uid2grp
> Built target idmap
> [ 10%] Built target rpcal
> [ 12%] Built target nfs_mnt_xdr
> [ 14%] Built target fsalpseudo
> [ 16%] [ 19%] Built target MainServices
> Built target support
> [ 22%] Built target nlm
> [ 27%] Built target sal
> [ 29%] [ 30%] [ 36%] Built target rquota
> Built target fsalnull
> Built target cache_inode
> [ 48%] [ 63%] Built target 9p
> Built target ntirpc
> [ 64%] Built target fsalproxy
> [ 65%] [ 66%] Built target fsalvfs
> Building C object FSAL/FSAL_GLUSTER/CMakeFiles/fsalgluster.dir/fsal_up.c.o
> [ 68%] Built target fsalpanfs
> [ 72%] Built target fsalgpfs
> [ 94%] Built target nfsproto
> Scanning dependencies of target sm_notify.ganesha
> Scanning dependencies of target ganesha.nfsd
> [ 94%] Building C object 
> Protocols/NLM/CMakeFiles/sm_notify.ganesha.dir/sm_notify.c.o
> [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 95%] [ 96%] [ 98%] [ 
> 98%] [ 98%] /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c: 
> In function ‘GLUSTERFSAL_UP_Thread’:
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:111:30: error: 
> storage size of ‘callback’ isn’t known
> struct callback_arg callback;
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:197:8: error: 
> ‘GFAPI_CBK_EVENT_NULL’ undeclared (first use in this function)
> case GFAPI_CBK_EVENT_NULL:
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:197:8: note: 
> each undeclared identifier is reported only once for each function it 
> appears in
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:200:8: error: 
> ‘GFAPI_INODE_INVALIDATE’ undeclared (first use in this function)
> case GFAPI_INODE_INVALIDATE:
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:211:21: error: 
> dereferencing pointer to incomplete type
> if (cbk_inode_arg->object)
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:213:21: error: 
> dereferencing pointer to incomplete type
> cbk_inode_arg->object);
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:214:21: error: 
> dereferencing pointer to incomplete type
> if (cbk_inode_arg->p_object)
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:216:22: error: 
> dereferencing pointer to incomplete type
> cbk_inode_arg->p_object);
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:217:21: error: 
> dereferencing pointer to incomplete type
> if (cbk_inode_arg->oldp_object)
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:219:22: error: 
> dereferencing pointer to incomplete type
> cbk_inode_arg->oldp_object);
> ^
> /root/ganesha/nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c:111:30: error: 
> unused variable ‘callback’ [-Werror=unused-variable]
> struct callback_arg callback;
> ^
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/common_pnfs.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL_UP/fsal_up_utils.c.o
> Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/nfs_main.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/fsal_manager.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/default_methods.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/fsal_convert.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL_UP/fsal_up_top.c.o
> Building C object MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/commonlib.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL_UP/fsal_up_async.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/fsal_destroyer.c.o
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/*/FSAL/access_check.c.o
> cc1: all warnings being treated as errors
> Building C object 
> MainNFSD/CMakeFiles/ganesha.nfsd.dir/__/FSAL/fsal_config.c.o
> make[2]: *** [FSAL/FSAL_GLUSTER/CMakeFiles/fsalgluster.dir/fsal_up.c.o] 
> Error 1
> make[1]: *** [FSAL/FSAL_GLUSTER/CMakeFiles/fsalgluster.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> Linking C executable sm_notify.ganesha
> [ 98%] Built target sm_notify.ganesha
> Linking C executable ganesha.nfsd
> [ 98%] Built target ganesha.nfsd
> make: *** [all] Error 2
> 
> and cmake output:
> -- cmake version 2.8
> -- override default CMAKE_INSTALL_PREFIX = /usr
> -- Detected an UNKNOWN Linux machine
> -- toolchain options processed
> -- Compilation from within a git repository. Using git rev-parse HEAD
> -- found krb5-config here /usr/bin/krb5-config
> -- Found kerberos 5 headers: /include
> -- Found kerberos 5 libs: 
> /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
> -- GFAPI_INCLUDE_DIRS=/usr/include/uuid;/usr/include/glusterfs
> -- GFAPI_LIBRARY_DIRS=
> CMake Warning at CMakeLists.txt:626 (message):
> Disabling SHOOK because it needs LUSTRE
> 
> 
>     -- Found nfs idmap library: /usr/lib64/libnfsidmap.so
>     -- Found Winbind4 client:
>     -- OVERRIDE_INSTALL_PREFIX =
>     -- found krb5-config here /usr/bin/krb5-config
>     -- Found kerberos 5 headers: /include
>     -- Found kerberos 5 libs:
>     /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so;/usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
>     -- Found Winbind4 client:
> 
> ------------------------------------------------------------------------
> 
> 
>     -- TIRPC_EPOLL = ON
>     -- USE_RPC_RDMA = OFF
>     -- Using ntirpc submodule
>     /root/ganesha/nfs-ganesha/src/libntirpc/ntirpc/
> 
> ------------------------------------------------------------------------
> 
> -- PLATFORM = LINUX
> -- VERSION = 2.3.3
> -- BUILD HOST = f08n29
> 
> ------------------------------------------------------------------------
> 
> -- USE_FSAL_PROXY = ON
> -- USE_FSAL_VFS = ON
> -- USE_FSAL_CEPH = OFF
> -- USE_FSAL_RGW = OFF
> -- USE_FSAL_HPSS = OFF
> -- USE_FSAL_XFS = OFF
> -- USE_FSAL_PANFS = ON
> -- USE_FSAL_GPFS = ON
> -- USE_FSAL_PT = OFF
> -- USE_FSAL_ZFS = OFF
> -- USE_FSAL_LUSTRE = OFF
> -- USE_FSAL_SHOOK = OFF
> -- USE_FSAL_LUSTRE_UP = OFF
> -- USE_FSAL_GLUSTER = ON
> -- USE_FSAL_NULL = ON
> -- USE_SYSTEM_NTIRPC = OFF
> -- USE_DBUS = OFF
> -- USE_CB_SIMULATOR = OFF
> -- USE_NFSIDMAP = ON
> -- ENABLE_ERROR_INJECTION = OFF
> -- ENABLE_VFS_DEBUG_ACL = OFF
> -- ENABLE_RFC_ACL = OFF
> -- USE_CAPS = ON
> -- USE_BLKID = ON
> -- STRICT_PACKAGE = OFF
> -- DISTNAME_HAS_GIT_DATA = OFF
> -- _MSPAC_SUPPORT = ON
> -- USE_EFENCE = OFF
> -- _NO_TCP_REGISTER = ON
> -- _NO_PORTMAPPER = ON
> -- _NO_XATTRD = ON
> -- DEBUG_SAL = OFF
> -- _VALGRIND_MEMCHECK = OFF
> -- PROXY_HANDLE_MAPPING = OFF
> -- DEBUG_SYMS = OFF
> -- COVERAGE = OFF
> -- ENFORCE_GCC = OFF
> -- PROFILING = OFF
> -- USE_GSS = ON
> -- TIRPC_EPOLL = ON
> -- USE_9P = ON
> -- _USE_9P = ON
> -- _USE_9P_RDMA = OFF
> -- USE_NFS_RDMA = OFF
> -- KRB5_PREFIX =
> -- CEPH_PREFIX =
> -- RGW_PREFIX =
> -- HPSS_PREFIX =
> -- GLUSTER_PREFIX = /usr
> -- ZFS_PREFIX = /usr
> -- LUSTRE_PREFIX = /usr
> -- CMAKE_PREFIX_PATH = /usr
> -- _GIT_HEAD_COMMIT = 165fc33 
> <https://github.com/nfs-ganesha/nfs-ganesha/commit/165fc33ad240a5d3147f1aedd2e3420ea700cdb4>
> -- _GIT_HEAD_COMMIT_ABBREV = 165fc33 
> <https://github.com/nfs-ganesha/nfs-ganesha/commit/165fc33ad240a5d3147f1aedd2e3420ea700cdb4>
> -- _GIT_DESCRIBE = V2.3.3-0-g165fc33
> -- ALLOCATOR = jemalloc
> -- GOLD_LINKER =
> -- CMAKE_INSTALL_PREFIX = /usr
> -- FSAL_DESTINATION = /usr/lib64/ganesha
> -- USE_ADMIN_TOOLS = OFF
> -- USE_GUI_ADMIN_TOOLS = ON
> -- MODULES_PATH =
> -- USE_TSAN = OFF
> -- USE_LTTNG = OFF
> -- USE_BLKIN = OFF
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/ganesha/nfs-ganesha/src
> 
> How can I solve this problem?
> 

2.3.3 is a very old version of Ganesha, and is not expected to work with 
current versions of Gluster.  Please try 2.5.3 instead.

Daniel

**Comment by MrSate** [comment]
Thanks, but I want use nfs-ganesha for gluster 3.7.20（this version we've tested,so  I don't want to change it）.
So,which latest version can support gluster3.7.20 ?

**Comment by dang** [comment]
I'm not sure.  The oldest one I've used is 3.8.x.  @supriti do you know?  Was 3.7.20 ever supported?

**Comment by supriti** [comment]
@dang I guess you meant to ask @soumyakoduri

**Comment by dang** [comment]
Oops, yes, sorry.

**Comment by MrSate** [comment]
Thank you suggestion, but I want to try to compile this version( beacuse nfs-ganesha may be the latest version support gluster3.7.20). 
I can't find the definition of the struct callback_arg(in nfs-ganesha/src/FSAL/FSAL_GLUSTER/fsal_up.c) in ganesha source. It may be the compile error caused by this .do you have any suggestions? Thanks

**Comment by soumyakoduri** [comment]
Please switch to >=nfs-ganesha-2.4.x which consumes new upcall APIs backported to gluster-3.7.20

**Comment by soumyakoduri** [comment]
But you are right...V2.4-stable would require >glusterfs-3.8.6. If you really need to use gluster-3.7, I suggest to either 
* switch to glusterfs-3.7.15 which had old upcall APIs or 
* backport https://review.gerrithub.io/#/c/298501/ on top of nfs-ganesha V2.3.3 (but please make sure to uncomment the changes in CMakeLists.txt).
