### ISSUE TITLE
A problem when I tried to compile

### ISSUE THREAD

**Issue by gongneilianhua2** [nfs-ganesha/nfs-ganesha#222]
[root@controll build]# make
Scanning dependencies of target ntirpc
[  0%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/auth_none.c.o
[  0%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/auth_unix.c.o
[  1%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/authunix_prot.c.o
[  1%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/bindresvport.c.o
[  1%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/bsd_epoll.c.o
[  1%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/city.c.o
[  2%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_bcast.c.o
[  2%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_dg.c.o
[  2%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_generic.c.o
[  3%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_perror.c.o
[  3%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_raw.c.o
[  3%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_simple.c.o
[  3%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/clnt_vc.c.o
[  4%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/getnetconfig.c.o
[  4%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/getnetpath.c.o
[  4%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/getpeereid.c.o
[  4%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/getrpcent.c.o
[  5%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/getrpcport.c.o
[  5%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/mt_misc.c.o
[  5%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/pmap_clnt.c.o
[  5%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/pmap_getmaps.c.o
[  6%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/pmap_getport.c.o
[  6%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/pmap_prot.c.o
[  6%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/pmap_prot2.c.o
[  7%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/pmap_rmt.c.o
[  7%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rbtree.c.o
[  7%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rbtree_x.c.o
[  7%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_prot.c.o
[  8%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_callmsg.c.o
[  8%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_commondata.c.o
[  8%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_crc32.c.o
[  8%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_ctx.c.o
[  9%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_dplx_msg.c.o
[  9%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_dtablesize.c.o
[  9%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_generic.c.o
[  9%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpc_soc.c.o
[ 10%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpcb_clnt.c.o
[ 10%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpcb_prot.c.o
[ 10%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/rpcb_st_xdr.c.o
[ 10%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/strlcpy.c.o
[ 11%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc.c.o
[ 11%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_auth.c.o
[ 11%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_auth_unix.c.o
[ 12%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_auth_none.c.o
[ 12%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_dg.c.o
[ 12%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_generic.c.o
[ 12%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_raw.c.o
[ 13%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_rqst.c.o
[ 13%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_run.c.o
[ 13%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_simple.c.o
[ 13%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_vc.c.o
[ 14%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_xprt.c.o
[ 14%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/vc_generic.c.o
[ 14%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr.c.o
[ 14%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_array.c.o
[ 15%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_float.c.o
[ 15%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_mem.c.o
[ 15%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_rec.c.o
[ 16%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_reference.c.o
[ 16%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_stdio.c.o
[ 16%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_inrec.c.o
[ 16%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/xdr_ioq.c.o
[ 17%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_ioq.c.o
[ 17%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/work_pool.c.o
[ 17%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/auth_gss.c.o
[ 17%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/authgss_hash.c.o
[ 18%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/authgss_prot.c.o
[ 18%] Building C object libntirpc/src/CMakeFiles/ntirpc.dir/svc_auth_gss.c.o
Linking C shared library libntirpc.so
[ 18%] Built target ntirpc
Scanning dependencies of target log
[ 18%] Building C object log/CMakeFiles/log.dir/display.c.o
[ 19%] Building C object log/CMakeFiles/log.dir/log_functions.c.o
In file included from /data/downloads/nfs-ganesha-2.4.0/src/log/log_functions.c:49:0:
/data/downloads/nfs-ganesha-2.4.0/src/include/gsh_rpc.h:27:26: error：rpc/rpc_dplx.h：no such file or directory
 #include <rpc/rpc_dplx.h>

[root@controll build]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

###################################
nfs-ganesha version : 2.4.0
WIKI : https://github.com/nfs-ganesha/nfs-ganesha/wiki/Compiling
###################################
what should i do with the problem??

**Comment by sagarfan** [comment]
try this : git submodule update --init
[https://github.com/nfs-ganesha/nfs-ganesha/wiki/BuildingV2](url)

**Comment by dang** [comment]
2.4.0 is quite old.  Can you try at least 2.4.5?  If not 2.5.3?

**Comment by dang** [comment]
(FWIW, 2.4.0 builds for me...)

**Comment by AAuby** [comment]
it's ok . Thank you very much !

**Comment by ffilz** [comment]
Closed as resolved.
