### ISSUE TITLE
Why v4.1 latency is higher then v4.0？

### ISSUE THREAD

**Issue by zhanghongzhou** [nfs-ganesha/nfs-ganesha#224]
In v4.1 REQ_Q_HIGH_LATENCY queue size is 1->2->3->1->2->3, which is not in v4.0, thus 4.1 latency is worse than 4.0

while in kernel nfs-server, 4.1 latency is better than 4.0

**Comment by zhanghongzhou** [comment]
I got it. It's because NFS41_NB_SLOTS is set to 3
Can anyone tell me why is it set to 3?

**Comment by dang** [comment]
The slot table is new in NFS 4.1, so it's not part of 4.0.  I don't know why the table size is 3; it was that way in the first commit.  Could you try with 64 (which is the default for knfsd)?

**Comment by zhanghongzhou** [comment]
I tried 100. Latency is much better using fio. However I am not sure if there's side effect.

**Comment by dang** [comment]
Thanks.  I'll work up a patch.

**Comment by dang** [comment]
https://review.gerrithub.io/390465

**Comment by supriti** [comment]
Closing issue as the patch has already been merged.
