### ISSUE TITLE
ls command can't show all files when there are more than 1000 files in a directory.

### ISSUE THREAD

**Issue by kuailedubage** [nfs-ganesha/nfs-ganesha#226]
Hi, guys. I'm using CentOS7.1.1503, Ceph 12.2.1 and nfs-ganesha V2.5-stable for NFS over RGW.
When I create 1001 files in one folder (bucket in rgw) of mounted nfs directory , I use command `ls -alh` to show all files in this directory, but it only shows 51 files. I can see normal ouput with `ls <missing file>` directly. And when I keep creating more than 50 files with `touch` command, it shows only 100 files. I try it many times and I find that it reproduces only when creating more than 1000 files. Any idea would be appreciated.

Here are my ganesha.conf.
```
EXPORT
{
        Export_id=1;
        Path = "/";
        Pseudo = /share;
        Access_Type = RW;
        Protocols = 3,4;
        Transports = TCP;
        SecType = sys,krb5,krb5i,krb5p;
        FSAL {
                Name = RGW;
                User_Id = "xxx";
                Access_Key_Id ="xxx";
                Secret_Access_Key = "xxx";
        }
}
RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        cluster = "xxx";
        name = "xxx";
}
LOG {
        Facility {
                name = FILE;
                destination = "/var/log/ganesha/ganesha.log";
                enable = active;
        }
}
```

**Comment by taoCH** [comment]
same issue met, I think it might has something to do with code in librgw side:
```
class RGWStatLeafRequest : public RGWLibRequest,
      public RGWListBucket /* RGWOp */
{
public:
  RGWFileHandle* rgw_fh;
  std::string path;
  bool matched;
  bool is_dir;
  bool exact_matched;

  RGWStatLeafRequest(CephContext* _cct, RGWUserInfo *_user,
       RGWFileHandle* _rgw_fh, const std::string& _path)
    : RGWLibRequest(_cct, _user), rgw_fh(_rgw_fh), path(_path),
      matched(false), is_dir(false), exact_matched(false) {
    default_max = 1000; // logical max {"foo", "foo/"}
    op = this;
  }
}
```

You can see the variable here, **default_max = 1000**, you can try to modify this value to see the difference.

**Comment by ffilz** [comment]
This is a known issue. There are fixes in V2.6-dev.14. These will soon be backported to V2.5-stable and included in the V2.5.4 tag.

 

Frank

**Comment by supriti** [comment]
@ffilz Can you point out which commits fix this issue in 2.6-dev14. Thanks

**Comment by dang** [comment]
2223c3c70fa2189185e9e968a2ffe0cf763b3544
8d039cd139ea1dcfbe316b7e93e96efe755669ef
011f90be782b755c763e81783cdd96e7cb48828d
79dc970258df0bec21ca838f56270628195a2e21
56142298c471663c286f4df5527ea4f20feaa26b

**Comment by ffilz** [comment]
My patches in dev.14, the debug ones aren't specifically needed, but may be needed to patch cleanly

2d6ccb3 Frank S. Filz MDCACHE: remove unused icreate_refcnt
5614229 Frank S. Filz MDCACHE: Don't test MDCACHE_DIR_POPULATED in mdcache_readdir_chunked
79dc970 Frank S. Filz MDCACHE: Fixup whence_is_name
011f90b Frank S. Filz MDCACHE: Additional cleanup of chunk before reuse or free
95e2174 Frank S. Filz FSAL_VFS: Additional debug messages
71833a8 Frank S. Filz Improve readdir debug in upper layers
dfdeb5b Frank S. Filz MDCACHE: add debug for readdir processing

Matt's patches for FSAL_RGW
8d039cd Matt Benjamin RGW: use new whence_is_name for READDIR continuation
2223c3c Matt Benjamin RGW: set fso_compute_readdir_cookie

Note you also need newer RGW code

These also from dev.15
824cea6 Matt Benjamin RGW: don't deref NULL at LogFullDebug after add_detached_dirent()
5b701cb Frank S. Filz MDCACHE: Catch an end of directory condition and record in dirent cache

**Comment by kuailedubage** [comment]
Thanks a lot !
