### ISSUE TITLE
Do we really need registration of signal handle for librgw?

### ISSUE THREAD

**Issue by taoCH** [nfs-ganesha/nfs-ganesha#228]
Hi,

This is a question about the code of librgw. When a librgw is created and initialized, it invokes function global_init() to get the Ceph context:

```
int RGWLib::init(vector<const char*>& args)
  {
    int r = 0;

    /* alternative default for module */
    vector<const char *> def_args;
    def_args.push_back("--debug-rgw=1/5");
    def_args.push_back("--keyring=$rgw_data/keyring");
    def_args.push_back("--log-file=/var/log/radosgw/$cluster-$name.log");

    cct = global_init(&def_args, args,
          CEPH_ENTITY_TYPE_CLIENT,
          CODE_ENVIRONMENT_DAEMON,
          CINIT_FLAG_UNPRIVILEGED_DAEMON_DEFAULTS);
    ...
}
```

And Inside the function global_init(), Ceph install standard sighandler for librgw:

```
boost::intrusive_ptr<CephContext>
global_init(std::vector < const char * > *alt_def_args,
      std::vector < const char* >& args,
      uint32_t module_type, code_environment_t code_env,
      int flags,
      const char *data_dir_option, bool run_pre_init)
{
    ...
  // signal stuff
  int siglist[] = { SIGPIPE, 0 };
  block_signals(siglist, NULL);

  if (g_conf->fatal_signal_handlers)
     install_standard_sighandlers();
   ...
}
```
And here comes my question:  In my opinion, librgw is a client-side rados gateway, which is always embedded into client's program. I think, normally, client's program will handle the system signal  itself, so do we really need registration of signal handle for librgw? 

Thanks for your attention.

**Comment by dang** [comment]
Hi.
Librgw is part of the Ceph project, not part of the Ganesha project (which is just a consumer).  Can you open this issue on the Ceph project instead?

**Comment by taoCH** [comment]
Ok
