### ISSUE TITLE
build error when /etc/os-release is missed

### ISSUE THREAD

**Issue by vitlav** [nfs-ganesha/nfs-ganesha#229]
CMake Error at CMakeLists.txt:85 (elseif):
  given arguments:
    "MATCHES" "Debian GNU/Linux" "OR" "MATCHES" "Ubuntu"
  Unknown arguments specified
-- Configuring incomplete, errors occurred!

**Comment by malahal** [comment]
Does this work? https://github.com/malahal/nfs-ganesha/commit/adad1d5a2be8cb7591b7c0d11c7021341ddcf75c

diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 19c8953..85fdabf 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -82,7 +82,7 @@ if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      message( STATUS "Detected a Linux openSUSE machine" )
      set(DISTRO "SLES")
      set(LIBEXECDIR "/usr/lib")
-  elseif( ${SYS_RELEASE} MATCHES "Debian GNU/Linux" OR ${SYS_RELEASE} MATCHES "Ubuntu")
+  elseif( (${SYS_RELEASE} MATCHES "Debian GNU/Linux") OR (${SYS_RELEASE} MATCHES "Ubuntu"))
      message( STATUS "Detected a Linux Debian base machine" )
      set(DISTRO "DEBIAN")
      set(LIBEXECDIR "/usr/lib")

**Comment by vitlav** [comment]
@malahal, yes it does work.

**Comment by ffilz** [comment]
Closed as resolved.
