### ISSUE TITLE
cmake options broken for proxy with HANDLE_MAPPING

### ISSUE THREAD

**Issue by wojd** [nfs-ganesha/nfs-ganesha#23]
Cmake config options are set to allow _HANDLE_MAPPING= to be ON or OFF.

FSAL_PROXY/CMakeLists.txt however checks for "ENABLE_HANDLE_MAPPING"

---snip---
if(ENABLE_HANDLE_MAPPING)
  SET(fsalproxy_LIB_SRCS
    ${fsalproxy_LIB_SRCS}
    handle_mapping/handle_mapping.c
    handle_mapping/handle_mapping_db.c
    )
endif(ENABLE_HANDLE_MAPPING)

This causes handle_mapping library not to be built.

**Comment by ffilz** [comment]
If this is still an issue in Ganesha V2.2.0 or later, please open a Red Hat Bugzilla

https://bugzilla.redhat.com/enter_bug.cgi?product=nfs-ganesha
