### ISSUE TITLE
Nfs-ganesha V2.5.4 can not support ceph luminous stable 12.2.1 ?

### ISSUE THREAD

**Issue by kuailedubage** [nfs-ganesha/nfs-ganesha#231]
@mattbenjamin New FSAL_RGW of nfs-ganesha V2.5.4 can't support ceph luminous stable 12.2.1 (RGW 1.1.4) because of [8d039cd](https://github.com/nfs-ganesha/nfs-ganesha/commit/8d039cd139ea1dcfbe316b7e93e96efe755669ef)，any advice？Sorry to bother you cause I want to solve this problem #226.

**Comment by supriti** [comment]
I tried nfs-ganesha v2.5.4 and luminous branch (https://github.com/ceph/ceph/tree/luminous). It gives me error: "load_fsal :NFS STARTUP :CRIT :Could not dlopen module:/usr/lib64/ganesha/libfsalrgw.so Error:/usr/lib64/ganesha/libfsalrgw.so: undefined symbol: rgw_readdir2"

**Comment by kuailedubage** [comment]
This has been fixed by [this](https://github.com/ceph/ceph/pull/18801). Thanks.
