### ISSUE TITLE
mdcache_close doesnot have cache_fds check?

### ISSUE THREAD

**Issue by waterdyg** [nfs-ganesha/nfs-ganesha#233]
before ganesha 2.4, in cache_inode_close() check cache_inode_lru_caching_fds() to hold fd in cache inode entry.
but in ganesha 2.4, in mdcache_close(), there doesnot have that check, so when i test write big file, like 10G, fsal_commit will take errno 9, because the same fd in different thread is shared, so one thread  use the fd to commit, another thread maybe close the fd, then errno 9.

so, why remove check cache_inode_lru_caching_fds()  in mdcache_close()? for some bug, or other reason?
could i add hold fd in close?

**Comment by dang** [comment]
Each open now gets it's own FD, stored in the state, so FDs should not be shared between client opens.

**Comment by waterdyg** [comment]
my test  is NFS v3 .write request use  fsal_rdwr() to write, there is no independent open request.
in fsal_rdwr(), all threads use same obj  to open-write-close same file, so i found the shared FDs in obj makes errno 9.

**Comment by dang** [comment]
NFSv3 uses the global FD.  There have been some fixes related to this, so try 2.5.x and see if it fixes your problem.

For NFSv4, explicit opens are used, and this results in a unique FD associated with the open, stored in a state_t hung off the obj_hdl (mdcache's version, in this case).  These are unique per NFSv4 state ID, and so can't interfere with each other.

**Comment by ffilz** [comment]
There have been fixes in this area in newer code. Closing.
