### ISSUE TITLE
Gluster export to vmware

### ISSUE THREAD

**Issue by int0x21** [nfs-ganesha/nfs-ganesha#234]
Mounting NFS 4.1 gluster volume from vmware gives the following error message
The max file name size (1024) of file system is larger than that of FSS (128)

**Comment by dang** [comment]
This does not appear to be an error message from Ganesha.  Where does this error come from?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
