### ISSUE TITLE
nfs-ganesha-fsal unmet dependency problem for nfs-ganesha 2.5.3 on Ubuntu

### ISSUE THREAD

**Issue by andrewlove** [nfs-ganesha/nfs-ganesha#236]
I'm trying to use nfs-ganesha 2.5.3 that is installed from the Ubuntu rep ppa:gluster/nfs-ganesha
I get this error:
`The following packages have unmet dependencies:
 nfs-ganesha-fsal : Depends: nfs-ganesha (= 2.5.0-ubuntu1~xenial3) but 2.5.3-ubuntu1~xenial1 is installed.
`
When I search for available packages I get:

`aptitude search nfs-ganesha -F "%c %p %d %V"`
`i nfs-ganesha                                                    nfs-ganesha is a NFS server in User Space                                2.5.3-ubuntu1~`  
`p nfs-ganesha-ceph                                               nfs-ganesha fsal ceph libraries                                          2.5.3-ubuntu1~`  
`p nfs-ganesha-doc                                                Documentation for nfs-ganesha                                            2.5.3-ubuntu1~`  
`p nfs-ganesha-fsal                                               nfs-ganesha fsal libraries                                               2.5.0-ubuntu1~`  
`p nfs-ganesha-gluster                                            nfs-ganesha fsal gluster libraries                                       2.5.3-ubuntu1~`  
`p nfs-ganesha-gpfs                                               nfs-ganesha fsal gpfs libraries                                          2.5.3-ubuntu1~`  
`p nfs-ganesha-mem                                                nfs-ganesha fsal mem libraries                                           2.5.3-ubuntu1~`  
`p nfs-ganesha-mount-9p                                           nfs-ganesha mount.9P                                                     2.5.3-ubuntu1~`  
`p nfs-ganesha-nullfs                                             nfs-ganesha fsal nullfs libraries                                        2.5.3-ubuntu1~`  
`p nfs-ganesha-proxy                                              nfs-ganesha fsal proxy libraries                                         2.5.3-ubuntu1~`  
`p nfs-ganesha-vfs                                                nfs-ganesha fsal vfs libraries                                           2.5.3-ubuntu1~`  
`p nfs-ganesha-xfs                                                nfs-ganesha fsal xfs libraries                                           2.5.3-ubuntu1~`  
`p python-nfs-ganesha                                             Python bindings for nfs-ganesha                                          2.5.3-ubuntu1~` 
 
How do I get nfs-ganesha-fsal 2.5.3 from the repo?

**Comment by kalebskeithley** [comment]
You don't.  There never was an nfs-ganesha-fsal-2.5.3.  The various fsals were unbundled into separate packages starting with nfs-ganesha-2.5.2, e.g. nfs-ganesha-vfs, nfs-ganesha-gluster, nfs-ganesha-gpfs.  Pick the one(s) you need from the list above.

**Comment by andrewlove** [comment]
Nice one.

For the record installing `nfs-ganesha-gluster` and restarting the nfs-ganesha service resolved teh problem.
I now have my NFS mounts back!

Many thanks
