### ISSUE TITLE
2.5.4 build failures on mipsel

### ISSUE THREAD

**Issue by bneumeier** [nfs-ganesha/nfs-ganesha#238]
I'm having an issue building nfs-ganesha 2.5.4 on a debian stretch mipsel system. Specifically, there are errors that occur when linking two programs that use libntirpc, with undefined references to __atomic_fetch_sub_8 and __atomic_fetch_add_8:

ganesha.nfsd
sm_notify.ganesha

In both instances, the problem is trivially corrected by adding "-latomic" to the link command line. This is easy to do just by modifying the link.txt file that the cmake process runs, but obviously it would be better for this to be done in the cmake metadata somewhere; I just don't know nearly enough about cmake to figure out where or how to do that.

If you'd like any more information, build or configure logs, etc., let me know!

**Comment by dang** [comment]
This needs a check on CMAKE_SYSTEM_PROCESSOR.  Can you paste in the output of uname -p here?

**Comment by bneumeier** [comment]
I doubt `uname -p` is good enough: it returns the string `unknown`.
FWIW, `uname -a` says `Linux colel 3.10.14 #1 SMP Wed Mar 1 10:20:40 BRT 2017 mips GNU/Linux`. 
The target triplet for this box is `mipsel-unknown-linux-gnu`.

LMK if there's anything else I can provide that might help.

**Comment by dang** [comment]
Unfortunately, uname -p is what CMake uses for this purpose (and is the correct thing to use, I think).  If it returns unknown, then we're going go have to do something rather hackish.

Does either -m or -i print anything useful?

**Comment by bneumeier** [comment]
I'm not sure:
`uname -m`  yields `mips`
`uname -i` yields `unknown`

I don't know whether it's necessarily the case that libatomic needs to be linked in for all mips systems. On the other hand, adding `-Wl,--as-needed,-latomic` to the end of the command line for all mips program builds won't cause any issues as long as there _is_ a libatomic to be found, and would fix the issue.

**Comment by dang** [comment]
Can you test with this commit, and see if it fixes your problem:
https://github.com/dang/nfs-ganesha/commit/15d2fd56a7ef28027408c1cb75be9d0392b4192b

You can try with this branch, if it's more convenient:
https://github.com/dang/nfs-ganesha/tree/arch

**Comment by bneumeier** [comment]
That commit fails almost immediately on this command:

`cd /tmp/build/build-ganesha/log && /usr/bin/cc  -D__USE_GNU -I/tmp/build/build-ganesha/include -I/tmp/build/nfs-ganesha/src/include -I/tmp/build/nfs-ganesha/src/include/os/linux -I/tmp/build/nfs-ganesha/src/libntirpc/ntirpc  -O2 -fomit-frame-pointer -I/srv/freesa/stack/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -DNDEBUG   -D _GNU_SOURCE -o CMakeFiles/log.dir/log_functions.c.o   -c /tmp/build/nfs-ganesha/src/log/log_functions.c`

With `fatal error: rpc/xdr_inline.h: No such file or directory`

**Comment by dang** [comment]
Did you update your submodule?

**Comment by bneumeier** [comment]
Oops, no, and I also neglected to use the flag that tells the build process that libntirpcd is already available on the system. After updating the submodule, I find this commit fixes the build -- I actually cherry-picked it onto 2.5.4 rather than using the 2.6 branch, but I doubt that matters.

**Comment by dang** [comment]
https://review.gerrithub.io/390257
