### ISSUE TITLE
How to disable BIND_CONN_TO_SESSION

### ISSUE THREAD

**Issue by zhanghongzhou** [nfs-ganesha/nfs-ganesha#246]
I updated code and found that client keep send BIND_CONN_TO_SESSION request and ganesha reply with illegal request.
It seems to be related to set_ssv. How could I disable the BIND_CONN_TO_SESSION request?

Thanks.

**Comment by ffilz** [comment]
I am in the process of implementing BIND_CONN_TO_SESSION. I'm not sure if there's a way to make the client not sent it. Which client?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
