### ISSUE TITLE
Each ganesha server in an active/passive configuration with pacemaker appears as a unique share to VMware ESXi

### ISSUE THREAD

**Issue by ACiDGRiM** [nfs-ganesha/nfs-ganesha#247]
I have a GlusterFS storage cluster that I'm trying to present via 4.1 to an ESXi 6.5 system.
If I mount the system on gluster node01 via ganesha sucessfully on the esxi system, access works correctly.
However after I move the VIP from gluster node01 to gluster node 02, the esxi mount is disconnected. This issue remains until all VM's connected are powered down after which point the connection is restored.
I was able to get the switch over to work just once with live VM's running on nfs41, but esxi/vcenter reported that the lock had been lost, however vm operation continued.

I've got a common_shared gluster volume mounted on all nodes and have the inode cache timeout set to 0, as well as several cache configurations in gluster fs I'll post in another comment. I have noticed that there seems to not be any data actually stored by ganesha in this path, but I'm not aware of a configuration for this.

Any information on why this is happening will be appreciated, as it's a project I've been trying to complete for some time.

I don't have this issue with nfs3, infact the switch over is instantanious with no iterruption.

**Comment by ACiDGRiM** [comment]
Gluster info
Volume Name: storage3
Type: Distributed-Replicate
Volume ID: 14fbf7ba-7785-42e1-b2c2-fa5e05db8ca6
Status: Started
Snapshot Count: 0
Number of Bricks: 3 x (2 + 1) = 9
Transport-type: tcp
Bricks:
Brick1: s-san-hq1:/mnt/gluster/storage/brick0/glusterfs3
Brick2: s-san-hq0:/storage_pool-01/brick01/glusterfs
Brick3: s-san-hq2:/gluster_pool-01/storage/brick01/glusterfs (arbiter)
Brick4: s-san-hq1:/mnt/gluster/storage/brick1/glusterfs3
Brick5: s-san-hq0:/storage_pool-02/brick02/glusterfs
Brick6: s-san-hq2:/gluster_pool-01/storage/brick02/glusterfs (arbiter)
Brick7: s-san-hq1:/mnt/gluster/storage/brick2/glusterfs3
Brick8: s-san-hq0:/storage_pool-03/brick03/glusterfs
Brick9: s-san-hq2:/gluster_pool-01/storage/brick03/glusterfs (arbiter)
Options Reconfigured:
performance.write-behind: off
cluster.use-compound-fops: on
performance.parallel-readdir: on
cluster.granular-entry-heal: enable
features.leases: on
features.cache-invalidation: on
cluster.server-quorum-type: server
features.scrub: Inactive
features.bitrot: off
performance.cache-invalidation: true
performance.client-io-threads: off
server.event-threads: 4
client.event-threads: 4
performance.cache-samba-metadata: true
performance.write-behind-window-size: 4MB
performance.cache-max-file-size: 2MB
performance.io-thread-count: 32
performance.cache-size: 256MB
diagnostics.client-log-level: WARNING
diagnostics.brick-log-level: WARNING
cluster.data-self-heal-algorithm: diff
cluster.lookup-optimize: on
transport.address-family: inet6
nfs.disable: on
server.allow-insecure: on
client.bind-insecure: on
features.lock-heal: on
cluster.brick-multiplex: off
cluster.enable-shared-storage: enable
nfs-ganesha: enable
cluster.localtime-logging: enable

**Comment by ACiDGRiM** [comment]
Ganesha general config

GLUSTER
{
 PNFS_MDS = true;
}

NFS_Core_Param
{
        Nb_Worker = 256;
        Clustered = TRUE;
        NFS_Protocols= 3,4;
        NFS_Port = 2049;
        MNT_Port = 0;
        NLM_Port = 0;
        RQUOTA_Port = 0;
        RPC_Max_Connections = 10000;
        heartbeat_freq = 10;
        short_file_handle = FALSE;
        NSM_Use_Caller_Name = TRUE;
}

NFSv4
{
        Lease_Lifetime = 60;
        DomainName = cosmicbitflip.net;
        Delegations = TRUE;
}

CacheInode
{
        Attr_Expiration_Time = 0;
        Entries_HWMark = 1500000;
        LRU_Run_Interval = 90;
        FD_HWMark_Percent = 60;
        FD_LWMark_Percent = 20;
        FD_Limit_Percent = 90;
}

Export_Defaults
{
        Access_Type = none;
        Protocols = 3,4;
        Transports = TCP;
        Anonymous_uid = 0;
        Anonymous_gid = 0;
        SecType = sys;
        PrivilegedPort = FALSE;
        #Manage_Gids = FALSE;
        Squash = root_squash;
        #NFS_Commit = FALSE;
}

**Comment by ACiDGRiM** [comment]
Also to note, this is not an issue with nfs3 mounts

**Comment by soumyakoduri** [comment]
Hi,

We haven't done thorough testing using NFS V4.1 on Gluster, although it shoudn't impact IP failover.  Also we do not support delegations yet. Please turn it off in NFSV4 block and re-try the tests.
While you re-try, please capture packet trace and monitor ganesha.log & ganesha-gfapi.log for any errors.

It maybe worth to check with other tested protocol - NFSV4.0 (i.e.,  mount -t nfs -o vers=4.0).
To further narrow down the issue, post failover of VIP1, could you check if that VIP is accessible using below methods
* showmount -e VIP1
* try a fresh mount of the same volume using VIP1. 

Thanks!

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
