### ISSUE TITLE
exporting aufs file system via nfs-ganesha

### ISSUE THREAD

**Issue by adolfyang** [nfs-ganesha/nfs-ganesha#252]
Hi,
Is it possible to export aufs union path via nfs-ganesha?
I tried, but failed.
My ganesha server version is V2.5.4 on CentOS 7 with kernel 4.14.13-1.el7.centos.x86_64.
My export block config option is shown below(The path /data/nfs/aufs_check is an aufs union path):

EXPORT
{
    Export_Id = 12346;
    Path = /data/nfs/aufs_check;
    Pseudo = /aufs_check;
    Protocols = 3,4;
    Access_Type = RW;
    Squash = no_root_squash;
    FSAL {
        Name = VFS;
    }
}

The ganesha server can start sucessfully as usual, but when I mount the exported path, the nfs client which used version 3 blocked. The log said: 
"vfs_open_by_handle :FSAL :DEBUG :Failed with Stale file handle openflags 0x00220003
mdcache_locate_host :INODE :DEBUG :create_handle failed with The file no longer exists" 

In the same environment, I then tried the kernel nfs server. It worked well. The /etc/exports file is shown below:
/data/nfs/aufs_check  192.0.0.0/8(rw,sync,no_subtree_check,insecure,no_root_squash,fsid=9988,nohide,crossmnt)

How could I export aufs via nfs-ganesha?

Any help would be appreciated. Thanks a lot!

**Comment by dang** [comment]
Ganesha's FSAL_VFS requires a working open_by_handle_* for it to export a filesystem.  Not all kernel filesystems provide this, so not all kernel filesystems can be exported.  I've never tried aufs, but it may be one of these.

Note that aufs isn't in the kernel tree (and may not be maintained anymore?) so it will lag behind in-tree FSs in terms of features.

**Comment by ffilz** [comment]
If a kernel filesystem is exportable by knfsd, it SHOULD also be exportable by Ganesha. open_by_handle uses the "exportfs" interfaces that are required for knfsd export (knfsd also has to be able to open by handle, all that the open_by_handle system calls did was provide system calls so user space applications could access the API knfsd had been using all along).

It might be instructive to try with some debug enabled, in your config add:

LOG {
        COMPONENTS {
                FSAL=FULL_DEBUG;
                FILEHANDLE = FULL_DEBUG;
        }
}

That may help us identify where the handle operations are going wrong.

One remote possibility is that the form of aufs handles are long enough to cause issues, if that's the case, it would be interesting to see if NFS  v4 works. If that's an issue, you can change the fsid type.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
