### ISSUE TITLE
Does NFS-Ganesha provide  High availability?

### ISSUE THREAD

**Issue by HIK-GYK** [nfs-ganesha/nfs-ganesha#254]
I would like to know if the configuration of NFS-Ganesha  provide to support HA, if so ,how?

**Comment by supriti** [comment]
AFAIK it requires pacemaker/corosync stack. So you can have multiple ganesha nodes, and using pacemaker/corosync you assign virtual ip. If a nodes goes down, virtual ip migrates to active nfs-ganesha node. For FSAL CEPH, in v2.5-stable support for using rados kv is also added. For Gluster FSAL, refer to http://docs.gluster.org/en/latest/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/

**Comment by thotz** [comment]
Please Note HA for nfs-ganesha+gluster is only available at glusterfs 3.10

**Comment by thotz** [comment]
If are u interested u can also lookup into ongoing venture storhaug https://github.com/linux-ha-storage/storhaug

**Comment by supriti** [comment]
Added a wiki entry with available information: https://github.com/nfs-ganesha/nfs-ganesha/wiki/NFS-Ganesha-and-High-Availability Closing the issue. Reopen if you have further questions.

**Comment by ducpx** [comment]
Hello guys, I wanna how to configure HA nfs-ganesha for cephfs backend?
