### ISSUE TITLE
ganesha fails when trying to add new export using dbus-send

### ISSUE THREAD

**Issue by hardy2323** [nfs-ganesha/nfs-ganesha#255]
when trying to add new share using following command:
`dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/dir string:/tmp/ganesha.conf "string:EXPORT(Export_Id=49)";`

ganesha fail with following message in log:
`06/02/2018 08:24:08 : epoch 5a7965da : ocata-ceph-node1 : ganesha.nfsd-20615[dbus_heartbeat] unregister_fsal :FSAL :CRIT :Unregister FSAL Ceph with non-zero refcount=1
06/02/2018 08:24:08 : epoch 5a7965da : ocata-ceph-node1 : ganesha.nfsd-20615[dbus_heartbeat] finish :FSAL :CRIT :Unable to unload Ceph FSAL.  Dying with extreme prejudice.`
running debian stretch with ganesha packages from sid:
ii  nfs-ganesha                          2.5.4-1                        amd64
ii  nfs-ganesha-ceph:amd64               2.5.4-1                        amd64
ii  nfs-ganesha-vfs:amd64                2.5.4-1                        amd64

strace shows that process exited with SIGABRT:
`open("/var/log/ganesha.log", O_WRONLY|O_CREAT|O_APPEND, 0644) = 35
write(35, "05/02/2018 17:08:34 : epoch 5a78"..., 163) = 163
close(35)                               = 0
open("/var/log/ganesha.log", O_WRONLY|O_CREAT|O_APPEND, 0644) = 35
write(35, "05/02/2018 17:08:34 : epoch 5a78"..., 149) = 149
close(35)                               = 0
open("/var/log/ganesha.log", O_WRONLY|O_CREAT|O_APPEND, 0644) = 35
write(35, "05/02/2018 17:08:34 : epoch 5a78"..., 163) = 163
close(35)                               = 0
futex(0x7fcbc2efd9d0, FUTEX_WAIT, 7822, NULLinput in flex scanner failed
) = ?
+++ killed by SIGABRT +++
Aborted`

config file:
`EXPORT
{
    # Export Id (mandatory, each EXPORT must have a unique Export_Id)
    Export_Id = 79;

    # Exported path (mandatory)
    Path = /dir2;

    # Pseudo Path (required for NFS v4)
    Pseudo = /dir2;

    # Required for access (default is None)
    # Could use CLIENT blocks instead
    Access_Type = RW;

    # Exporting FSAL
    FSAL {
        Name = CEPH;
    }
}`

conf file used to add export:
`EXPORT
{
    # Export Id (mandatory, each EXPORT must have a unique Export_Id)
    Export_Id = 49;

    # Exported path (mandatory)
    Path = /dir;

    # Pseudo Path (required for NFS v4)
    Pseudo = /dir;

    # Required for access (default is None)
    # Could use CLIENT blocks instead
    Access_Type = RW;

    # Exporting FSAL
    FSAL {
        Name = CEPH;
    }
}`

**Comment by hardy2323** [comment]
after removing "string:/dir" from dbus-send command adding share works as expected, however i think that ganesha shouldn't fail with incorrect dbus message

**Comment by dang** [comment]
I agree in principle, but I'm not sure how important it is to harden the DBUS API.  It's not really intended to be called directly, but with scripting tools (such as src/scripts/ganeshactl), so the arguments shouldn't be wrong in general.

We'll look into it.

**Comment by ffilz** [comment]
Closed as will not fix.
