### ISSUE TITLE
ganesha does not refresh mdcache when i rm a file from backend(my distributed fs)

### ISSUE THREAD

**Issue by lee-fan** [nfs-ganesha/nfs-ganesha#256]
There are 4 files in a share directory.
 i remove a file from backend fs instead of nfs mountpoint. As a result, when i ls -l in nfs  mountpoint,nothing is showing. But 3 files should be there.

 i got a ENOENT error from tcpdump in readdirplus request. because ganesha think a file is there,so it send a getattr request to backend, but actually this file is already removed.

i am confused the config parameter **Attr_Expiration_Time** and **LRU**  whether it is useful or not to refresh mdcache.

**Comment by dang** [comment]
So, how this works depends on which FSAL you're using.  Some FSALs (currently Gluster and GPFS) can send an up-call to notify Ganesha when the file disappears; some FSALs (such as VFS) cannot.  For these FSALs, Ganesha cannot know about the file changing until it tries to access it or until the metadata cache times out.  Attr_Expiration_Time controls how long the metadata cache waits before timing out attributes on a file/directory (although not dirents directly...).  This is a compromise between efficiency and correctness.  If you set this to 0, then attributes will never be cached, and updates should be correct, but response will be slower.

In general, you should not be changing the filesystem underneath Ganesha on a  FSAL that does not support up-calls, unless you can deal with this kind of delays in updates.

**Comment by lee-fan** [comment]
Thank you @dang 
i am pretty sure that ganesha already knows the deleted file is removed,because when i ls -l,client send a readdirplus request, and getattr request per file,i found for the file which i deleted, backend fs return ENOENT. why ganesha doest not remove the file cache inode? Actually  the Attr_Expiration_Time must time out.

**Comment by dang** [comment]
It does remove the cached entry for the removed *file* when the getattr fails.  However, I'm not sure it removes the cached *dirent* (which is an attribute of the parent directory).  That would be worth exploring.

**Comment by ffilz** [comment]
The challenge is for an arbitrary inode that has been discovered to be invalid how to find the dirents (with hard links, or back end renames Ganesha didn't track, there could be more than one) that reference the inode.

With an invalidation upcall mechanism, the back end removal ALSO signals an invalidation of the directory that contained the name that was unlinked (or renamed) so Ganesha tracks all the directory updates (in the right circumstances, we could even update the dirent cache rather than invalidate it).

**Comment by dang** [comment]
In general, without upcalls, ganesha cannot be 100% correct in the presence of backend changes.  This is the downside of being a userspace NFS server, and why we added upcalls.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
