### ISSUE TITLE
running valgrind on nfs-ganesha daemon reported definite memory leaks 

### ISSUE THREAD

**Issue by mukesh-bafna** [nfs-ganesha/nfs-ganesha#259]
Running valgrind on nfs-ganesha daemon and performing operations like create/list/remove shares reported following definite memory leaks in code - 

20922== 176 bytes in 1 blocks are definitely lost in loss record 237 of 323
==20922== at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20922== by 0x507850: gsh_calloc__ (abstract_mem.h:145)
==20922== by 0x507DF3: pnfs_ds_alloc (ds.c:92)
==20922== by 0x508C25: pds_init (ds.c:344)
==20922== by 0x56237D: load_config_from_parse (config_parsing.c:1949)
==20922== by 0x508ED4: ReadDataServers (ds.c:462)
==20922== by 0x41D3C3: main (nfs_main.c:468)
==20922==
==20922== 480 bytes in 1 blocks are definitely lost in loss record 267 of 323
==20922== at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==20922== by 0x51F667: gsh_calloc__ (abstract_mem.h:145)
==20922== by 0x5206C8: alloc_export (export_mgr.c:227)
==20922== by 0x50B9D5: export_init (exports.c:930)
==20922== by 0x56237D: load_config_from_parse (config_parsing.c:1949)
==20922== by 0x50DCC5: ReadExports (exports.c:2005)
==20922== by 0x41D439: main (nfs_main.c:478)
==20922==

**Comment by dang** [comment]
What version of Ganesha?  This should be fixed in 2.6-dev/rc versions.

**Comment by mukesh-bafna** [comment]
Thanks for checking on issue. This was seen with below version -

root@sclvmesxd19-vm4:/# /usr/bin/ganesha.nfsd -v
NFS-Ganesha Release = V2.5.2
ganesha.nfsd compiled on Jan 16 2018 at 21:05:40
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = 9e93d73237d7c5d9d793d2ad21767fb8bb54429a
Git Describe = V2.5.4-0-g9e93d73

**Comment by dang** [comment]
Okay, this is fixed in 2.5.5 (by 775cfb6a1b1915d51021805a2e8fb2afdf493dc6) and 2.6.  Please update your Ganesha.

**Comment by mukesh-bafna** [comment]
Thanks, will try  2.5.5. Closing issue!
