### ISSUE TITLE
pynfs failures with v2.5-stable + FSAL CEPH

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#261]
Using nfs4.0 pynfs tests 3 failures and 1 warning. Opening issue as place holder and if some one is already aware of these. I will investigate if these are valid errors or not. 

```
RNM17    st_rename.testFileToFullDir                              : FAILURE
           RENAME file into existing, nonempty dir should return
           NFS4ERR_EXIST or NFS4ERR_ISDIR, instead got NFS4ERR_NOTEMPTY
PUTFH3   st_putfh.testStaleHandle                                 : FAILURE
           Using a stale fh should return NFS4ERR_STALE, instead
           got NFS4_OK
RD4      st_read.testLargeCount                                   : WARNING
           READ returned 4194304 characters, expected 9000000
LOCKHELD st_lock.testClose                                        : UNSUPPORTED
           Can not close locked files
```

**Comment by ffilz** [comment]
RNM17 and PUTFH3 failures are worrisome.

RD4 requires configuring MaxRead on the export large enough and then it should pass.

LOCKHELD is an expected point of non-support. You could add a wish list card item to implement that, it would be an easy project for someone wanting to learn about how Ganesha manages NFS v4 state.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
