### ISSUE TITLE
Unable to start NFS Ganesha

### ISSUE THREAD

**Issue by sudeep9** [nfs-ganesha/nfs-ganesha#264]
I am unable to start NFS Ganesha server. Here are the details:

**Error message**

`Register_program :DISP :FATAL :Cannot register NFS V3 on UDP`

More details:

1. rpcbind is running (also confirmed using `nestat`)
2. Able to start kernel nfs server
3. Running NFS Ganesha as `root` 
4. OS = `Ubuntu 17.10`
5. NFS-Ganesha version = `V2.5.4`

```
root # service rpcbind status
● rpcbind.service - RPC bind portmap service
   Loaded: loaded (/lib/systemd/system/rpcbind.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-02-18 00:46:43 IST; 4min 24s ago
     Docs: man:rpcbind(8)
 Main PID: 479 (rpcbind)
    Tasks: 1 (limit: 4915)
   Memory: 3.0M
      CPU: 12ms
   CGroup: /system.slice/rpcbind.service
           └─479 /sbin/rpcbind -f -w
```

**Comment by dang** [comment]
This means that another NFS server is running, and using the well-known-ports.  Probably knfsd.  Disable the kernel NFS server, and it should work.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Comment by Davidrjx** [comment]
In kubernetes case, both nfs-ganesha pod container and host  have rpcbind service, do they conflict?

**Comment by dang** [comment]
They shouldn't, with the default network config.  Each pod will have it's own network partition, so each can have it's own rpcbind.  It you set the pod to use the host network partition, then they will conflict.

**Comment by ffilz** [comment]
It's best to create a new issue rather than commenting in a closed one...

**Comment by Davidrjx** [comment]
> They shouldn't, with the default network config. Each pod will have it's own network partition, so each can have it's own rpcbind. It you set the pod to use the host network partition, then they will conflict.

ok, thanks

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
