### ISSUE TITLE
pynfs fslocations tests fail

### ISSUE THREAD

**Issue by srirampatil** [nfs-ganesha/nfs-ganesha#265]
The st_fslocations tests in pynfs test the FS_LOCATIONS attribute and expected behavior of GETATTR and READDIR around it. Following are the results of running the test on ganesha and knfs

Name | Description | ganesha | knfs
------------ | ------------- | ------------ | -------------
testReference | GETFH + FS_LOCATIONS. GETFH should return NFS4ERR_MOVED | **FAIL** | PASS
testReference2 | FS_LOCATIONS on special path but does not verify that fs_locations are no-empty | PASS | PASS
testReference3 | FS_LOCATIONS on the specified mount path | PASS | PASS
testAttr1a | GETATTR w/o FS_LOCATIONS or RDATTR_ERROR should return NFS4ERR_MOVED | PASS | PASS
testAttr1b | READDIR w/o FS_LOCATIONS or RDATTR_ERROR should return NFS4ERR_MOVED | PASS | PASS
testAttr2a | GETATTR w/o FS_LOCATIONS but with RDATTR_ERROR should return NFS4ERR_MOVED | **FAIL** | **FAIL**
testAttr2b | READDIR w/o FS_LOCATIONS but with RDATTR_ERROR should return NFS4ERR_MOVED in RDATTR_ERROR and returns what it can | **FAIL** | PASS
testAttr3a | GETATTR w/o FS_LOCATIONS but with restricted attrs should return NFS4ERR_OK | PASS | PASS
testAttr3b | READDIR w/o FS_LOCATIONS but with restricted attrs should return NFS4ERR_OK | **FAIL** | PASS
testAttr4a | GETATTR with FS_LOCATIONS and RDATTR_ERROR should return what it can | **FAIL** | PASS
testAttr4b | READDIR with FS_LOCATIONS and RDATTR_ERROR should return NFS4ERR_MOVED in RDATTR_ERROR and return what it can | **FAIL** | PASS
testAttr5a | GETATTR with FS_LOCATIONS but w/o RDATTR_ERROR should return what it can | **FAIL** | PASS
testAttr5b | READDIR with FS_LOCATION but w/o RDATTR_ERROR should return NFS4ERR_MOVED in RDATTR_ERROR and return what it can | **FAIL** | PASS

A total of 8 tests fail out of 13 for Ganesha. Since the corresponding tests are passing on knfs, need to fix these issues.

**Comment by ffilz** [comment]
This may still be worth looking into, retaining to be entered into our backlog.

**Comment by srirampatil** [comment]
I have fixed most of these tests as part of this change -> https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/400805

It may still have a couple of tests failing, but others are fixed.

**Comment by ffilz** [comment]
Ok, I'll close this as resolved,
