### ISSUE TITLE
2.5.5 fails to start on system with IPv6 enabled,  but not configured

### ISSUE THREAD

**Issue by filip3090** [nfs-ganesha/nfs-ganesha#267]
Environment: Ubuntu 14.04, nfs-ganesha 2.5.5, libntirpc 1.5.4
Server has IPv6 enabled, but not configured (only link local addresses), e.g.:
```
$ ip a s bond0
14: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:33:56:55:06:ea brd ff:ff:ff:ff:ff:ff
    inet 10.108.56.154/23 brd 10.108.57.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 fe80::33:56ff:fe55:6ea/64 scope link 
       valid_lft forever preferred_lft forever
```

In this environment, nfs-ganesha 2.5.0.2 started without any problems.
Now we're testing nfs-ganesha 2.5.5 and we're facing following error message when trying to start:
```
2018-02-22 14:42:44.0543 +0000 USER.CRIT [ganesha.nfsd]  [main] Register_program :DISP :FATAL :Cannot register NFS V3 on UDPv6
```
libtirpc1 configuration:
```
$ cat /etc/netconfig 
udp        tpi_clts      v     inet     udp     -       -
tcp        tpi_cots_ord  v     inet     tcp     -       -
udp6       tpi_clts      v     inet6    udp     -       -
tcp6       tpi_cots_ord  v     inet6    tcp     -       -
rawip      tpi_raw       -     inet      -      -       -
local      tpi_cots_ord  -     loopback  -      -       -
unix       tpi_cots_ord  -     loopback  -      -       -
```

When we remove the udp6- and tcp6-entries from the above file, nfs-ganesha starts without problems. Is there another solution aside from this workaround, which we would prefer not use if possible?

Thanks,

Filip

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
