### ISSUE TITLE
fails to build on non amd64 Debian/sid installations

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#268]
While building nfs-ganesha on amd64 Debian/sid is working without a problem, building it on e.g. i386 or arm64 fails with:

(see https://buildd.debian.org/status/package.php?p=nfs-ganesha)

cd /<<PKGBUILDDIR>>/src/obj-aarch64-linux-gnu/config_parsing && /usr/bin/cc  -I/usr/include/glusterfs -I/usr/include/uuid -I/<<PKGBUILDDIR>>/src/obj-aarch64-linux-gnu/include -I/<<PKGBUILDDIR>>/src/include -I/<<PKGBUILDDIR>>/src/include/os/linux -I/include -I/usr/include/ntirpc -I/<<PKGBUILDDIR>>/src/config_parsing -I/<<PKGBUILDDIR>>/src/obj-aarch64-linux-gnu/config_parsing  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -DNDEBUG   -o CMakeFiles/config_parsing.dir/conf_lex.c.o   -c /<<PKGBUILDDIR>>/src/obj-aarch64-linux-gnu/config_parsing/conf_lex.c
In file included from /<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:8:0:
/<<PKGBUILDDIR>>/src/include/config_parsing.h:33:9: error: unknown type name 'caddr_t'
 typedef caddr_t config_file_t;
         ^~~~~~~
In file included from /<<PKGBUILDDIR>>/src/include/abstract_mem.h:45:0,
                 from /<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:11:
/<<PKGBUILDDIR>>/src/include/log.h:164:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
 int display_timeval(struct display_buffer *dspbuf, struct timeval *tv);
                                                           ^~~~~~~
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l: In function 'ganeshun_yylex':
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:328:6: warning: implicit declaration of function 'index' [-Wimplicit-function-declaration]
   return TOK_V4ADDR;
      ^~~~~
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:328:6: warning: incompatible implicit declaration of built-in function 'index'
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:340:6: warning: incompatible implicit declaration of built-in function 'index'
   return TOK_V6ADDR;
      ^~~~~
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l: In function 'new_file':
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:445:19: warning: implicit declaration of function 'alloca' [-Wimplicit-function-declaration]
 
                   ^     
/<<PKGBUILDDIR>>/src/config_parsing/conf_lex.l:445:19: warning: incompatible implicit declaration of built-in function 'alloca'
config_parsing/CMakeFiles/config_parsing.dir/build.make:173: recipe for target 'config_parsing/CMakeFiles/config_parsing.dir/conf_lex.c.o' failed

**Comment by dang** [comment]
https://review.gerrithub.io/#/c/400806/

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
