### ISSUE TITLE
Config parser does not throw error in case of some misspelled block names

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#269]
For blocks such as , CEPH and RGW, parser does not detect if they are misspelled. This results in error while creating export, but from those errors its not clear that the issue was misspelled block.  For the other blocks such as FSAL, parser does print "Unkown parameter". We should extend the parse to handle missing blocks.

**Comment by ffilz** [comment]
Request for enhancement that may be worth retaining for our backlog.

**Comment by ffilz** [comment]
Bump, these currently don't cause an error so the patch I just submitted doesn't trigger this one....

**Comment by ffilz** [comment]
I submitted this patch which should do the trick: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/552557

**Comment by ffilz** [comment]
V5.0 has been released. Closing.
