### ISSUE TITLE
FSAL_RGW: Directories disappear

### ISSUE THREAD

**Issue by MartinEmrich** [nfs-ganesha/nfs-ganesha#273]
I have an issue with the RadosGW fsal: Mounting works fine, running "ls" in the directories, too. but when I try to tar up a whole bucket, directories disappear:

...
tar: /store/testbucket/sGlMWjFlfPLmcbmd: File removed before we read it
tar: /store/testbucket/uZAKQkQeXTRyLVrr: File removed before we read it
tar: /store/testbucket/ucIqmGmthjHBQWqn: File removed before we read it
tar: /store/testbucket/uiBBNTyQxwnqnKBO: File removed before we read it
tar: /store/testbucket/vRfZJRHfXdnfGGgx: File removed before we read it
tar: /store/testbucket/vbifbMjyIqOFtaFO: File removed before we read it
tar: /store/testbucket/viKmlbRBXFeEdAsh: File removed before we read it
tar: /store/testbucket/wYmlGYkjvgeDRSnh: File removed before we read it
tar: /store/testbucket/wZgjLHrQbwOSikLI: File removed before we read it
...

(the paths listed are "directories")

around the time, I see this line in the nfs-ganesha output:

2018-03-06 17:12:29.598516 7f7e39ffb700  0 lookup_handle handle lookup failed <13234489286997512229,9160472602707183340>(need persistent handles)

Any ideas?

Thanks

Martin

**Comment by mattbenjamin** [comment]
Hi Martin,

The handle lookup failure is a clue that the number of vnodes in use by ganesha in this workload forced eviction in its LRU, and subsequently those evicted handles were recycled from RGW's file LRU.

As a potential workaround, you could try increasing the size of nfs-ganesha's vnode cache--any handle still referenced by nfs-ganesha cannot be recycled by RGW, so will be found in cache.

More broadly, if we need to track down a bug, a clear indication of the versions of nfs-ganesha and ceph/librgw that you're using will be essential to the process.

**Comment by MartinEmrich** [comment]
Uh sorry: I run ganesha from Git (Branch V2.6-stable), with Ceph 12.2.4 on CentOS 7.

my command line: `ganesha.nfsd -N DEBUG -L /dev/stdout -f /etc/ganesha/ganesha.conf -F`

My config:
```
EXPORT
{
	Export_Id = 3726;
	Path = "/";
	Pseudo = "/";
	Access_Type = RO;
        SecType = "sys";
        Protocols = 4;
        Transports = TCP;
	Squash = No_root_squash;

	FSAL {
		Name = RGW;
                User_Id = xxx;
                Access_Key_Id ="xxx";
                Secret_Access_Key = "xxx";
	}
}

RGW {
    cluster = "ceph";
    name = "client.rgw.ceph-s3fs";
    ceph_conf = "/etc/ceph/ceph.conf";
    init_args = "-d --debug-rgw=0";
}
```

Indeed the Buckets contain very many small files, for test data I generated 1000000 random 40k files with this script:

```
#!/usr/bin/perl -w

use strict;

sub randstring() {
    my @chars = ("A".."Z", "a".."z");
    my $string;
    $string .= $chars[rand @chars] for 1..16;

    return $string;
}

my @randstrings;
for (my $i = 0; $i < 100; $i++) {
    push @randstrings, randstring();
}


my $path;
my $count = 0;
foreach my $l1 (@randstrings) {
    mkdir $l1;
    foreach my $l2 (@randstrings) {
	mkdir $l1."/".$l2;
	foreach my $f (@randstrings) {
	    $path = "$l1/$l2/$f";
	    $count++;
	    system("dd if=/dev/urandom of=$path bs=40k count=1");
	    print "\r$count";
	}
    }
}
```

How can I increase this "vnode cache"? It looks like a temporary fix, but for now it might do...

Thanks,

Martin

**Comment by mattbenjamin** [comment]
I think what you'd do is increase the values of 
cache_inode {
NParts(uint32, range 1 to 32633, default 7)
Cache_Size(uint32, range 1 to UINT32_MAX, default 32633)
}
(mainly cache_size) so so that nparts*cache_size is a suitably large number.

**Comment by mattbenjamin** [comment]
that said, thanks VERY much for the detailed info, I'll debug with this and see what I find;  buckets of up to 1M files are supposed to be enumerable

**Comment by mattbenjamin** [comment]
ANOTHER thing you should look at though, is increasing the namespace timeout for RGW NFS (maybe a lot), in ceph.conf--the config param to change is described with other info, here:
https://github.com/ceph/ceph/blob/master/doc/radosgw/nfs.rst

**Comment by MartinEmrich** [comment]
Hi! Your hints sound interesting, but are quite vague... the page you linked does not contain the string "namespace timeout", and in the source code, I find lots of "cache_inode", but do not know where to change a value.

Can you just tell me in which source file I have to change the values? or are these configuration options? if so, can you give me an example where to set them? Is it in ganesha.conf or in ceph.conf? or both?

Thanks

Martin

**Comment by supriti** [comment]
Regarding cache_inode, its ganesha's config parameters. https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-cache-config.rst#cacheinode- In ganesha.conf, you need to add block, CACHEINODE and set the values, NParts and Cache_Size

**Comment by MartinEmrich** [comment]
Thanks... I tried with

```
CACHEINODE {
           NParts = 2048;
           Cache_Size = 134217728; # 128M
}
```
(Just guessed some numbers).

Same behaviour, just the librgw error message does not appear this time.

**Comment by mattbenjamin** [comment]
Hi Martin,
That's awfully large...but anyway, before you change this back,

What you should try next is, in the ceph.conf seen by nfs-ganesha's librgw, in the rgw (or global) section, increase the namespace timeout, e.g.,

  rgw_nfs_namespace_expire_secs = 86400

I'm running your file generator, so can't run the tar yet. 

Matt

**Comment by MartinEmrich** [comment]
Hi!

I set this option... Now my tar process endures much longer, but at some point ganesha crashes:

```
    -1> 2018-03-12 13:36:56.816095 7d8b4ff5b700  1 -- 10.32.82.222:0/3283638693 <== osd.7 10.32.95.201:6802/65471 4178 ==== osd_op_reply(57552 94852c8d-e438-4ac0-93de-86671c75c202.7740032.2_FfnDhzCwhPPlKBDq/pzKYPQCqzDBGbaZf/vbifbMjyIqOFtaFO [getxattrs,stat] v0'0 uv8432 ond
isk = 0) v8 ==== 283+0+1142 (3744127199 0 975783355) 0x7d8b43b2dd40 con 0x7d8af400db70
     0> 2018-03-12 13:36:56.949111 7d8b207f8700 -1 *** Caught signal (Aborted) **
 in thread 7d8b207f8700 thread_name:ganesha.nfsd

 ceph version 12.2.4 (52085d5249a80c5f5121a76d6288429f35e4e77b) luminous (stable)
 1: (()+0x482b51) [0x7d8b545d5b51]
 2: (()+0xf5e0) [0x7f8b63b755e0]
 3: (gsignal()+0x37) [0x7f8b630201f7]
 4: (abort()+0x148) [0x7f8b630218e8]
 5: (()+0x2e266) [0x7f8b63019266]
 6: (()+0x2e312) [0x7f8b63019312]
 7: (()+0x173b38) [0x7d8b542c6b38]
 8: (rgw::RGWFileHandle::~RGWFileHandle()+0x4d) [0x7d8b542ca46d]
 9: (rgw::RGWFileHandle::~RGWFileHandle()+0x9) [0x7d8b542ca4e9]
 10: (rgw_fh_rele()+0xf2) [0x7d8b542c7672]
 11: (()+0x43b3) [0x7d8b548f03b3]
 12: ganesha.nfsd() [0x52a119]
 13: (mdcache_lru_get()+0x93) [0x52e18e]
 14: ganesha.nfsd() [0x53c068]
 15: (mdcache_new_entry()+0x1c6) [0x53d9a2]
 16: ganesha.nfsd() [0x5427fa]
 17: ganesha.nfsd() [0x543525]
 18: (()+0x468d) [0x7d8b548f068d]
 19: (rgw::RGWReaddirRequest::send_response()+0x42d) [0x7d8b542e775d]
 20: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*, rgw::RGWLibIO*)+0x4e5) [0x7d8b542bef75]
 21: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*)+0x46) [0x7d8b542bfd96]
 22: (rgw::RGWFileHandle::readdir(bool (*)(char const*, void*, unsigned long, unsigned int), void*, boost::variant<unsigned long*, char const*>, bool*, unsigned int)+0x5d5) [0x7d8b542d1ca5]
 23: (rgw_readdir()+0x9b) [0x7d8b542d202b]
 24: (()+0x4801) [0x7d8b548f0801]
 25: (mdcache_populate_dir_chunk()+0x6d0) [0x543c7c]
 26: (mdcache_readdir_chunked()+0x9de) [0x54511d]
 27: ganesha.nfsd() [0x533b92]
 28: (fsal_readdir()+0x28b) [0x4323a6]
 29: (nfs4_op_readdir()+0x55a) [0x4759d0]
 30: (nfs4_Compound()+0xaa8) [0x45b0a5]
 31: ganesha.nfsd() [0x458002]
 32: (nfs_rpc_valid_NFS()+0xa5) [0x458749]
 33: (()+0x2a3f2) [0x7f8b6373d3f2]
 34: ganesha.nfsd() [0x44b76b]
 35: (()+0x2a303) [0x7f8b6373d303]
 36: (()+0x26987) [0x7f8b63739987]
 37: (()+0x26e01) [0x7f8b63739e01]
 38: (()+0x270a3) [0x7f8b6373a0a3]
 39: (()+0x27156) [0x7f8b6373a156]
 40: (()+0x302fa) [0x7f8b637432fa]
 41: (()+0x7e25) [0x7f8b63b6de25]
 42: (clone()+0x6d) [0x7f8b630e334d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
