### ISSUE TITLE
Unable to create files

### ISSUE THREAD

**Issue by jfarcher** [nfs-ganesha/nfs-ganesha#274]
I've been having an issue with nfs-ganesha where I cannot create files from a client machine.
I have a gluster volume "vol1" with the following export:
EXPORT{
Export_Id = 1;
Path = /vol1;
Pseudo = "/vol1"; # NFSv4 pseudo path for this export. Eg: "/test_volume_pseudo"
CLIENT {
clients = 192.168.1.0/24;
access_type="RW";
}
Disable_ACL = TRUE;

    FSAL {
            Name = GLUSTER;
            Hostname = nfs01.local;
            volume = vol1;
    }
Access_type = RW; # Access permissions
Squash = No_root_squash; # To enable/disable root squashing
Protocols = "4"; # NFS protocols supported
Transports = "UDP","TCP" ; # Transport protocols supported
SecType = "sys"; # Security flavors supported
}

From the client I mount successfully (at /mnt), but
touch /mnt/test
gives the following error
touch: setting times of '/mnt/test': No such file or directory
if I try to copy a file in:
cp: cannot create regular file '/mnt/test': Invalid argument.

I've got logging set to DEBUG but cannot see anything relevant showing up as to why the files aren't being created.

I'm running CentOS 7.4 with nfs-ganesha RPMs from the Gluster 3.10 repo's (2.4.5-1).

Any ideas?

**Comment by dang** [comment]
The client in question: is it on the 192.168.1.0/24 network?  Can you try without the CLIENT section, since you're giving RW to everyone anyway?

**Comment by jfarcher** [comment]
Yes the client is within that subnet, and I've already tried without the CLIENT section. I added the it to see if it made a difference.
Thanks

**Comment by dang** [comment]
Could you post logs?

**Comment by ffilz** [comment]
Should we verify subnets work correctly?

**Comment by ffilz** [comment]
Closing for lack of response.
