### ISSUE TITLE
FSAL_RGW: Failed to rename file in NFS3

### ISSUE THREAD

**Issue by taoCH** [nfs-ganesha/nfs-ganesha#275]
Hi, I found the following test can't pass in NFS-Ganesha with NFS3 over RGW:

* client side mount option : mount -t nfs xx.xx.xx.xx:/   /mnt  -o vers=3,sync,nolock

Once sharing filesystem is successfully mounted, I executed:

```shell
 /mnt/bucket1 $ touch test_obj
 /mnt/bucket1 $ mv test_obj  test_obj_new
 
 Operation not permitted -1
```

I traced the code in Ceph side and I found that the 'mv' operation tried to rename the opening object 'test_obj', which should have been closed, then librgw return error code EPRM.

Unlike to filesystem(FSAL VFS), inode doesn't exist in Object store-FSAL RGW, name is the key to the object, so we should make sure the target object is closed before rename operation.

**Comment by mattbenjamin** [comment]
@taoCH this is plausible, but are we sure we want the rename option to supercede?  probably?
@dang randomly, what are your thoughts?

**Comment by taoCH** [comment]
Here is my patch : https://review.gerrithub.io/#/c/403203/

**Comment by taoCH** [comment]
This path is not very elegant. However, the close operation is inspired by UNLINK operation which close the IO before unlink the target file, too ([fsal_helper.c   line 1208](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/fsal_helper.c#L1208)).  

As this bug only appears in NFS3, I don't think librgw can handle this. I will try to find a better fix in FSAL_RGW layer.

**Comment by taoCH** [comment]
@mattbenjamin @dang  Here is the new patch, which fix in librgw side
https://github.com/ceph/ceph/pull/20818

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
