### ISSUE TITLE
FSAL Proxy question

### ISSUE THREAD

**Issue by coozy** [nfs-ganesha/nfs-ganesha#279]
Hi,  
I'd like to designate a different Remote_Server for each export that uses the proxy FSAL. So for example, I want /mnt/proxy1 to proxy to 10.10.10.3 and /mnt/proxy2 to proxy to 10.10.10.4 

Is it possible to do that?

Thanks.

**Comment by ffilz** [comment]
Without a greater demand for PROXY and a champion to support it, I am going to close this as won't fix even though I have long thought this would be good to implement.
