### ISSUE TITLE
mac and windows client support

### ISSUE THREAD

**Issue by wangke1020** [nfs-ganesha/nfs-ganesha#281]
Hi, I tried to use clients in different platform to connect to nfs-ganesha. It seem's nfs-ganesha only works well with linux client.

version: 2.6 final
server os: ubuntu 14.04
nfs-ganesha config:
Access_Type = RW;
Squash = no_root_squash;
FSAL=MEM;

In Win10, `network err -53` is reported when I tried to mount with command `mount \\server-ip\data X:`, and nfs-ganesha log shows 
` epoch 5aba60bb : ubuntu : nfs-ganesha-4117[svc_27] rpc :TIRPC :INFO :svc_vc_wait: 0x7f4044000a00 fd 27 recv errno 104 (will set dead)` 

 In mac, I tried to mount V3 and V4. Only some cmds works. I got "aaaaa" after cat a small file which contain "abcde".  got `permission denied` after exec `sudo "sdf" > file`  while nfs-ganesha log shows:
` epoch 5aba66c8 : ubuntu : nfs-ganesha-4430[svc_10] get_quota :FSAL :CRIT :Invoking unsupported FSAL operation
`

Is ganesha not support windows and mac client?  Or the implement of these clients differ with linux client?

**Comment by ffilz** [comment]
FSAL_MEM is not a full FSAL, I'm not sure it stores data yet, so you should use an FSAL backed by a real filesystem (FSAL_VFS is the simplest).

Not all FSALs support quota, so you may want to configure to not have quota support enabled (I assume since RQUOTAD is registered with rpcbind, the Mac client is trying to use it).

I'm not quite sure what's up with the Windows client, if you could get a network trace that we can examine in Wireshark, we might be able to identify the issue.

**Comment by wangke1020** [comment]
Thanks for apply. I tried FSAL_VFS and it works with mac client.

In windows, FSAL_VFS also could not be mounted.  I tried to use nfs-kernel-server, the exported dir can be mounted by window nfs client.

I use wireshark in Win10 to trace network but still did not understand why mount failed. 
Here is the file: [ganesha-win.pcapng.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/1856457/ganesha-win.pcapng.zip)

**Comment by ffilz** [comment]
Glad FSAL_VFS worked for Mac client.

For Windows, it would help to run Ganesha with some debug enabled, add this to your config:

LOG {
    COMPONENTS {
        DISPATCH = FULL_DEBUG;
    }
}

There is an NLM FREE_ALL call that is getting an RPC auth error. I'm not sure why that's happening, that procedure should have no authentication requirements.

**Comment by wangke1020** [comment]
As following log,  `errno 104` is reported while NLM auth failed, is it the cause?
```
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_6] nfs_rpc_dispatch_tcp_MNT :DISP :F_DBG :MOUNT TCP request on SVCXPRT 0x7f3cd80008c0 fd 38
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_decode_request :DISP :DEBUG :0x7f3cd80008c0 fd 38 context 0x7f3cd4000ed0
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_process_request :DISP :F_DBG :About to authenticate Prog=100005, vers=3, proc=0, xid=3, SVCXPRT=0x7f3cd80008c0, fd=38
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_process_request :DISP :F_DBG :Before SVCAUTH_CHECKSUM on SVCXPRT 0x7f3cd80008c0 fd 38
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:100.100.32.38 for Program 100005, Version 3, Function 0 has xid=3
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_process_request :DISP :F_DBG :Current request is not duplicate or not cacheable.
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_process_request :DISP :F_DBG :Before svc_sendreply on socket 38
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_process_request :DISP :F_DBG :After svc_sendreply on socket 38
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7f3cd80008c0 fd 38 (::ffff:100.100.32.38:952) xid=3 returned XPRT_IDLE
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] free_nfs_request :DISP :DEBUG :free_nfs_request: 0x7f3cd80008c0 fd 38 xp_refs 3 rq_refs 0
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_10] nfs_rpc_dispatch_tcp_NFS :DISP :F_DBG :NFS TCP request on SVCXPRT 0x7f3cc40008c0 fd 39
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_decode_request :DISP :DEBUG :0x7f3cc40008c0 fd 39 context 0x7f3ce4007cf0
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_process_request :DISP :F_DBG :About to authenticate Prog=100003, vers=3, proc=0, xid=5, SVCXPRT=0x7f3cc40008c0, fd=39
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_process_request :DISP :F_DBG :Before SVCAUTH_CHECKSUM on SVCXPRT 0x7f3cc40008c0 fd 39
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:100.100.32.38 for Program 100003, Version 3, Function 0 has xid=5
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_process_request :DISP :F_DBG :Current request is not duplicate or not cacheable.
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_process_request :DISP :F_DBG :Before svc_sendreply on socket 39
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_process_request :DISP :F_DBG :After svc_sendreply on socket 39
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7f3cc40008c0 fd 39 (::ffff:100.100.32.38:908) xid=5 returned XPRT_IDLE
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_2] free_nfs_request :DISP :DEBUG :free_nfs_request: 0x7f3cc40008c0 fd 39 xp_refs 3 rq_refs 0
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_6] rpc :TIRPC :INFO :svc_vc_wait: 0x7f3cc40008c0 fd 39 recv errno 104 (will set dead)
29/03/2018 19:19:37 : epoch 5abccaf3 : ubuntu : nfs-ganesha-17913[svc_7] rpc :TIRPC :INFO :svc_vc_wait: 0x7f3cd80008c0 fd 38 recv errno 104 (will set dead)
```

**Comment by ffilz** [comment]
104 is:

Error 104: Connection reset by peer

I think that's the client killing the connection because of the auth error. I'm not sure why logging isn't showing what's wrong.

It will be killer slow, but maybe just run Ganesha with -N NIV_FULL_DEBUG to see what shakes out. If you only try the one Windows mount the log won't be too horridly long...

**Comment by wangke1020** [comment]
I restart the linux server and found mount works in Windows. After many tries, I just know how to reproduce the issue.

1. restart nfs-ganesha
2. mount in linux server with V3 protocol and do not umount. (I always execute it to test if nfs works) 
3. mount with windows client and `Network Error 53` reported.

Only after nfs-ganesha restarted and mount NFSV3 in linux at first time ahead of windows, this issue can be reproduced.  Then if I umount linux client, windows client can works well.  Then linux nfs client will not affect windows client no matter whether it mounted.

I will check the FULL_DEBUG log later to see if any other error shakes out.

**Comment by ffilz** [comment]
So from Windows client you first mount a Linux knfsd server, leave that mounted and then try to mount the Ganesha server? Is the Linux knfsd server a different host than the Ganesha server or are you using the same host? Did you completely shut down the Linux server? Did you do a local v3 mount on the Linux server?

I think the switching server types is the core of the issue and may be something that would not be expected to work, but to determine that, I need to understand exactly what sequence of actions is taken, and what hosts are involved.

**Comment by wangke1020** [comment]
Ganesha server runs on Ubuntu 14.04, a virtual machine, and no knfsd server deployed on it. 

export path of VFS_FSAL is `/data`. After  ganesha restarted,  I execute `sudo mount -t nfs -o vers=3 127.0.0.1:/data /opt/test` on this Ubuntu host. Then mount operation in Windows will be fail.

**Comment by ffilz** [comment]
Try mounting -o nolock 

Unfortunately the NFS v3 lock protocol NLM requires the client to run an RPC server as well as the server. And it uses the same RPC program number. With both client and Ganesha server on the same host, both need to register their program with rpcbind. I’m guessing that causes a problem.

**Comment by wangke1020** [comment]
`-o nolock` works. thanks!

**Comment by ffilz** [comment]
Oh, good, glad that all resolved out.
