### ISSUE TITLE
FSAL RGW: Fix the default value for maxnamelen and maxpathlen

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#284]
Opening this issue so that it does not get lost. Currently these are hardcoded to 1024. Replace by realistic values. 
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/FSAL_RGW/main.c#L61

**Comment by ffilz** [comment]
This might be a good one for the backlog.
