### ISSUE TITLE
Now nfs-ganesha not support cephfs posix ACL？

### ISSUE THREAD

**Issue by wedy542700927** [nfs-ganesha/nfs-ganesha#290]
Hi, sorry to bother you：) 
I use ganesha2.6 as nfs server and mount cephfs.
When i use "setacl u:xx:r", "Operation not supported" comes. so I want to know whether ganesha supports cephfs posix ACL .
If not， do you have suggestions for achieving it ? Can I follow glusterfs posix ACL'implementation ?
Thank you !

**Comment by dang** [comment]
FSAL_CEPH doesn't have ACL support at this time.  (Note that NFS doesn't have POSIX ACLs at all, just NFS ACLs, which are not the same.  Mapping POSIX ACLs to NFS ACLs and back is not a simple task, and doesn't work properly.  It can be done, and works for certain circumstances, but not properly.)

**Comment by ffilz** [comment]
A little side comment - Linux (client and knfsd) support a non-standard side band protocol that provides POSIX ACLs for NFS v3. With Ganesha being generally aimed at NFS v4 and up, we have chosen not to implement this side band protocol.

**Comment by wedy542700927** [comment]
I got it. Thank you very much,  have a nice day : )

**Comment by zanglinjie** [comment]
Did RichACL support will eventually come?

**Comment by zanglinjie** [comment]
@ffilz  
“Moving NFSv4 to POSIX ACL mapping code to a common code base
Change-Id: If61be6d48ed6b9d45eb02a9d425a6c816a4e752b
Signed-off-by: Sriram Patil <sriramp@vmware.com>”

Do you have suggestions for achieving  FSAL_CEPH  for ACL support ? Can I follow glusterfs posix ACL'implementation ?
What is the ACL request invocation process on the client side to NFS-Ganesha？
