### ISSUE TITLE
FSAL-PROXY mounting nfs3 with PROXY_HANDLE_MAPPING on results in mount(2): Stale file handle

### ISSUE THREAD

**Issue by renzaniance** [nfs-ganesha/nfs-ganesha#291]
Complied with PROXY_HANDLE_MAPPING enabled

Compiled and running run on CentOS Linux release 7.4.1708, tried mounting nfsv3 on an number of different clients running different distributions 

Cannot mount with nfsv3 (proxied to primary ganesha nfs server over nfsv4), nfsv3 mount attempts fail with the client mount attempt reporting, (mounting nfsv4 works):

===
mount.nfs: trying text-based options 'udp,vers=3,addr=172.30.26.242'
mount.nfs: prog 100003, trying vers=3, prot=17
mount.nfs: trying 172.30.26.242 prog 100003 vers 3 prot UDP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 172.30.26.242 prog 100005 vers 3 prot UDP port 39981
mount.nfs: mount(2): Stale file handle
===

Have tried ganesha releases 2.1 through 2.6.1, all with same result 

ganesha.conf
===
EXPORT_DEFAULTS {
        Protocols = 3,4;
}

NFS_CORE_PARAM {
       NFS_Protocols = 3,4;
}

EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 77;
	Filesystem_id = 1.0;

        # Exported path (mandatory)
       # Path = /nfsdatadirect;
        Path = /export;

        # Pseudo Path (required for NFS v4)
      #  Pseudo = /nfsdatadirect;
        Pseudo = /export;

        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;
        Squash = no_root_squash;

        # Exporting FSAL
        FSAL {
                Name = PROXY;
        }
}

LOG {
        COMPONENTS {
#            FSAL = FULL_DEBUG;
            ALL = FULL_DEBUG;
    }
}

PROXY {
        Remote_Server {
                Srv_Addr = 172.30.15.11;
                Enable_Handle_Mapping = true;
                HandleMap_DB_Dir = /var/ganesha/handlemap;
                HandleMap_Tmp_Dir = /var/ganesha/tmp;
                HandleMap_DB_Count = 8;
                HandleMap_HashTable_Size = 103;
        }
}
====

on starting ganesha I see /var/ganesha/handlemap/handlemap.sqlite.[0-] created

extract from ganesha log during nfsv4 mount attempt:

26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:172.30.14.91 for Program 100003, Version 3, Function 19 has xid=4213328770
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :DISP :F_DBG :Current request is not duplicate or not cacheable.
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs3_Is_Fh_Invalid :FH :F_DBG :NFS3 Handle (24:0x4300004d1010230000c806bde90000000000000000000000)
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] get_gsh_export :RW LOCK :F_DBG :Got read lock on 0x7bf200 (&export_by_id.lock) at /root/repos/nfs-ganesha/src/support/export_mgr.c:324
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 77
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] get_gsh_export :EXPORT :F_DBG :get export ref for id 77 /export, refcount = 2
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] get_gsh_export :RW LOCK :F_DBG :Unlocked 0x7bf200 (&export_by_id.lock) at /root/repos/nfs-ganesha/src/support/export_mgr.c:352
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :DISP :M_DBG :DISP: MID DEBUG: Found export entry for path=/export as exportid=77
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :DISP :M_DBG :DISP: MID DEBUG: nfs_rpc_process_request about to call nfs_export_check_access for client ::ffff:172.30.14.91
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :RW LOCK :F_DBG :Got read lock on 0x232e310 (&op_ctx->ctx_export->lock) at /root/repos/nfs-ganesha/src/support/exports.c:2775
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] convert_ipv6_to_ipv4 :EXPORT :M_DBG :Converting IPv6 encapsulated IPv4 address ::ffff:172.30.14.91 to IPv4 172.30.14.91
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :EXPORT :M_DBG :Check for address 172.30.14.91 for export id 77 path /export
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :RW LOCK :F_DBG :Got read lock on 0x7be4a0 (&export_opt_lock) at /root/repos/nfs-ganesha/src/support/exports.c:2835
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :EXPORT :M_DBG :EXPORT          (options=033031e0no_root_squash, RWrw,    ,               ,               ,         ,                ,                )
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :EXPORT :M_DBG :EXPORT_DEFAULTS (options=03303002              ,     , 34-,               ,               ,         ,                ,                )
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :EXPORT :M_DBG :default options (options=03303002root_squash   , ----, 34-, UDP, TCP, ----, No Manage_Gids, -- Deleg, anon_uid=    -2, anon_gid=    -2, none, sys)
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :EXPORT :M_DBG :Final options   (options=033031e0no_root_squash, RWrw, 34-, UDP, TCP, ----, No Manage_Gids, -- Deleg, anon_uid=    -2, anon_gid=    -2, none, sys)
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :RW LOCK :F_DBG :Unlocked 0x7be4a0 (&export_opt_lock) at /root/repos/nfs-ganesha/src/support/exports.c:2909
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] export_check_access :RW LOCK :F_DBG :Unlocked 0x232e310 (&op_ctx->ctx_export->lock) at /root/repos/nfs-ganesha/src/support/exports.c:2913
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_req_creds :DISP :M_DBG :DISP: MID DEBUG: AUTH_SYS creds mapped to uid=0, gid=0, glen=1
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs3_fsinfo :NFS3 :DEBUG :REQUEST PROCESSING: Calling NFS3_FSINFO handle: File Handle V3: Len=24 4300004d1010230000c806bde90000000000000000000000
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs3_Is_Fh_Invalid :FH :F_DBG :NFS3 Handle (24:0x4300004d1010230000c806bde90000000000000000000000)
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] hashtable_getlatch :RW LOCK :F_DBG :Got read lock on 0x2332258 (&(ht->partitions[index].lock)) at /root/repos/nfs-ganesha/src/hashtable/hashtable.c:498
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] hashtable_getlatch : :F_DBG :Get (null) returning Value=0x7fd6280142d0 {1D074300004D1644030800000000000081644C1A4000000000D58F3D40}
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] hashtable_releaselatched :RW LOCK :F_DBG :Unlocked 0x2332258 (&ht->partitions[latch->index].lock) at /root/repos/nfs-ganesha/src/hashtable/hashtable.c:562
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :DISP :F_DBG :Before svc_sendreply on socket 19
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] rpc :TIRPC :F_DBG :xdr_reply_encode:93 ACCEPTED INLINE
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] rpc :TIRPC :F_DBG :xdr_reply_encode:109 SUCCESS
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :DISP :F_DBG :After svc_sendreply on socket 19
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_dupreq_rele :DUPREQ :F_DBG :releasing no-cache res 0x7fd60c041e50
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_process_request :EXPORT :F_DBG :put export ref for id 77 /export, refcount = 1
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7fd60c001220 fd 19 (::ffff:172.30.14.91:829) xid=4213328770 returned XPRT_IDLE
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] free_nfs_request :DISP :DEBUG :free_nfs_request: 0x7fd60c001220 fd 19 xp_refs 1 rq_refs 0
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] rpc :TIRPC :F_DBG :svc_release_it() 0x7fd60c001220 fd 19 xp_refs 0 af 10 port 829 @ free_nfs_request:1281
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] rpc :TIRPC :F_DBG :svc_dg_destroy_it() 0x7fd60c001220 fd 19 xp_refs 0 should actually destroy things @ free_nfs_request:1281
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] rpc :TIRPC :F_DBG :svc_release_it() 0x235b720 fd 19 xp_refs 2 af 0 port 4294967295 @ svc_rqst_xprt_task:754
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_4] rpc :TIRPC :F_DBG :work_pool_thread() svc_4 waiting
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_7] rpc :TIRPC :F_DBG :work_pool_thread() svc_7 task 0x7fd60c001438
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_7] rpc :TIRPC :F_DBG :svc_dg_destroy_task() 0x7fd60c001220 fd 19 xp_refs 0
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_7] rpc :TIRPC :F_DBG :svc_release_it() 0x235b720 fd 19 xp_refs 1 af 0 port 4294967295 @ svc_dg_destroy_task:455
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_7] rpc :TIRPC :F_DBG :work_pool_thread() svc_7 waiting
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_3] rpc :TIRPC :F_DBG :work_pool_thread() svc_3 task 0x2343a40
26/04/2018 11:28:43 : epoch 5ae10f0e : centos7SwarmNFSClient1 : ganesha.nfsd-22109[svc_3] rpc :TIRPC :F_DBG :svc_rqst_epoll_loop: epoll_fd 15 before epoll_wait (29000)

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
