### ISSUE TITLE
NFS HA (keepalived+ganesha)，when  failover，touch is very slow (about 3 minutes)

### ISSUE THREAD

**Issue by wedy542700927** [nfs-ganesha/nfs-ganesha#292]
Hi, 
When I tested ganesha HA (export cephfs), I encountered a new problem. In the event of a failover, although I didn't have to remount cephfs, I would wait for a long time while reading or writing(cat, vi, ls, etc.).
At first, I thought it was the cause of the grace period, but after the grace period was disabled, the problem still existed. I don't know whether the problem is on ganesha or keepalived. Have you got any good solutions to the problem? Thank you.

VMware
VIP: 192.168.72.200
ganesha server: 192.168.72.131 (master), 192.168.72.133 (backup)
client:192.168.72.128

start 192.168.72.131 keepalived,   failover from 192.168.72.133 to 192.168.72.131
If you need ,we can provide other information.

**/var/log/ganesha.log (192.168.72.131)：**

26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Reaping up to 50 entries from lane 15
26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Actually processed 0 entries on lane 15 closing 0 descriptors
26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run :INODE LRU :DEBUG :Reaping up to 50 entries from lane 16
26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Reaping up to 50 entries from lane 16
26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Actually processed 0 entries on lane 16 closing 0 descriptors
26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run :INODE LRU :DEBUG :After work, open_fd_count:0  count:2 fdrate:0 threadwait=90
26/04/2018 11:20:44 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[chunk_lru] chunk_lru_run :INODE LRU :DEBUG :After work, threadwait=90 totalwork=0
26/04/2018 11:21:57 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_74] rpc :TIRPC :DEBUG :svc_vc_wait: 0x7f710c003190 fd 33 recv errno 104 (will set dead)
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] nfs_rpc_decode_request :DISP :DEBUG :0x7f710c003190 fd 33 context 0x7f7104001650
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:192.168.72.128 for Program 100003, Version 3, Function 1 has xid=1489887640
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] nfs3_getattr :NFS3 :DEBUG :REQUEST PROCESSING: Calling NFS3_GETATTR handle: File Handle V3: Len=24 43000001101a00000000010000feffffffffffffff000000
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] getattrs :FSAL :DEBUG :getattr returned 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7f710c003190 fd 33 (::ffff:192.168.72.128:780) xid=1489887640 returned XPRT_IDLE
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_71] free_nfs_request :DISP :DEBUG :free_nfs_request: 0x7f710c003190 fd 33 xp_refs 3 rq_refs 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_rpc_decode_request :DISP :DEBUG :0x7f710c003190 fd 33 context 0x7f70f8000c20
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:192.168.72.128 for Program 100003, Version 3, Function 4 has xid=1506664856
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs3_access :NFS3 :DEBUG :REQUEST PROCESSING: Calling NFS3_ACCESS handle: File Handle V3: Len=24 43000001101a00000000010000feffffffffffffff000000
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: Requested ACCESS=READ,-,MODIFY,EXTEND,-,EXECUTE
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: access_mask = mode(rwx) ACL(read_data,write_data,execute,add_subdirectory,-)
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] getattrs :FSAL :DEBUG :getattr returned 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: Supported ACCESS=READ,-,MODIFY,EXTEND,-,EXECUTE
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: Granted ACCESS=READ,-,MODIFY,EXTEND,-,-
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] getattrs :FSAL :DEBUG :getattr returned 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7f710c003190 fd 33 (::ffff:192.168.72.128:780) xid=1506664856 returned XPRT_IDLE
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_151] free_nfs_request :DISP :DEBUG :free_nfs_request: 0x7f710c003190 fd 33 xp_refs 3 rq_refs 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_rpc_decode_request :DISP :DEBUG :0x7f710c003190 fd 33 context 0x7f710c0008c0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:192.168.72.128 for Program 100003, Version 3, Function 4 has xid=1523442072
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 1
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs3_access :NFS3 :DEBUG :REQUEST PROCESSING: Calling NFS3_ACCESS handle: File Handle V3: Len=24 43000001100100000000000000feffffffffffffff000000
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] cih_get_by_key_latch :HT CACHE :DEBUG :cih AVL hit slot 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: Requested ACCESS=READ,LOOKUP,MODIFY,EXTEND,DELETE,-
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: access_mask = mode(rwx) ACL(list_dir,add_file,execute,add_subdirectory,delete_child)
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] getattrs :FSAL :DEBUG :getattr returned 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: Supported ACCESS=READ,LOOKUP,MODIFY,EXTEND,DELETE,-
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_access_op :NFS3 :DEBUG :NFS3: DEBUG: Granted ACCESS=READ,LOOKUP,MODIFY,EXTEND,DELETE,-
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] getattrs :FSAL :DEBUG :getattr returned 0
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7f710c003190 fd 33 (::ffff:192.168.72.128:780) xid=1523442072 returned XPRT_IDLE
26/04/2018 11:21:58 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[svc_47] free_nfs_request :DISP :DEBUG :free_nfs_request: 0x7f710c003190 fd 33 xp_refs 3 rq_refs 0
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run :INODE LRU :DEBUG :Reaping up to 50 entries from lane 0
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Reaping up to 50 entries from lane 0
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Actually processed 0 entries on lane 0 closing 0 descriptors
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run :INODE LRU :DEBUG :Reaping up to 50 entries from lane 1
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Reaping up to 50 entries from lane 1
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run_lane :INODE LRU :DEBUG :Actually processed 0 entries on lane 1 closing 0 descriptors
26/04/2018 11:22:14 : epoch 5ae0aab7 : master : ganesha.nfsd-38255[cache_lru] lru_run :INODE LRU :DEBUG :Reaping up to 50 entries from lane 2

**/var/log/messages (192.168.72.131)：**

Apr 26 11:18:27 master systemd: Starting LVS and VRRP High Availability Monitor...
Apr 26 11:18:27 master Keepalived[47326]: Starting Keepalived v1.3.9 (10/21,2017)
Apr 26 11:18:27 master Keepalived[47326]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 26 11:18:27 master systemd: PID file /var/run/keepalived.pid not readable (yet?) after start.
Apr 26 11:18:27 master Keepalived[47328]: Starting Healthcheck child process, pid=47329
Apr 26 11:18:27 master Keepalived[47328]: Starting VRRP child process, pid=47330
Apr 26 11:18:27 master systemd: Started LVS and VRRP High Availability Monitor.
Apr 26 11:18:27 master Keepalived_healthcheckers[47329]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 26 11:18:27 master Keepalived_vrrp[47330]: Registering Kernel netlink reflector
Apr 26 11:18:27 master Keepalived_vrrp[47330]: Registering Kernel netlink command channel
Apr 26 11:18:27 master Keepalived_vrrp[47330]: Registering gratuitous ARP shared channel
Apr 26 11:18:27 master Keepalived_vrrp[47330]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 26 11:18:27 master Keepalived_vrrp[47330]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Apr 26 11:18:27 master Keepalived_vrrp[47330]: Unsafe permissions found for script '/etc/keepalived/check_ganesha.sh'.
Apr 26 11:18:27 master Keepalived_vrrp[47330]: SECURITY VIOLATION - scripts are being executed but script_security not enabled. There are insecure scripts.
Apr 26 11:18:27 master Keepalived_vrrp[47330]: VRRP_Instance(VI_1) removing protocol VIPs.
Apr 26 11:18:27 master Keepalived_vrrp[47330]: Using LinkWatch kernel netlink reflector...
Apr 26 11:18:27 master Keepalived_vrrp[47330]: VRRP sockpool: [ifindex(2), proto(112), unicast(0), fd(10,11)]
Apr 26 11:18:27 master Keepalived_vrrp[47330]: VRRP_Script(chk_ganesha) succeeded
Apr 26 11:18:28 master Keepalived_vrrp[47330]: VRRP_Instance(VI_1) Transition to MASTER STATE
Apr 26 11:18:29 master Keepalived_vrrp[47330]: VRRP_Instance(VI_1) Entering MASTER STATE
Apr 26 11:18:29 master Keepalived_vrrp[47330]: VRRP_Instance(VI_1) setting protocol VIPs.
Apr 26 11:18:29 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:29 master Keepalived_vrrp[47330]: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on ens33 for 192.168.72.200
Apr 26 11:18:29 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:29 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:29 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:29 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:34 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:34 master Keepalived_vrrp[47330]: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on ens33 for 192.168.72.200
Apr 26 11:18:34 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:34 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:34 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:18:34 master Keepalived_vrrp[47330]: Sending gratuitous ARP on ens33 for 192.168.72.200
Apr 26 11:20:01 master systemd: Started Session 35 of user root.
Apr 26 11:20:01 master systemd: Starting Session 35 of user root.

**Comment by dang** [comment]
Hi.

I think this may actually be an issue in CephFS.  When Ganesha opens a 
file, it get a CAP on the Ceph MDS for that file, so that no other user 
can access that part of that file (all of it by default) while Ganesha 
is using it.  When failover happens, the new Ganesha can't get the CAP 
on that file until it times out, since the old Ganesha isn't there to 
release it anymore.

There is work underway upstream to add APIs to Ceph to allow the new 
Ganesha to indicate that it's taking over for the old one and reclaim 
it's CAPs, but that isn't yet in place.  This makes it very difficult to 
do active-active HA with Ganesha over CephFS.

You can probably lower the CAP timeout on your Ceph MDS; this will, of 
course, have consequences, if you're using multiple CephFS clients, but 
it may mitigate this particular situation.

Daniel

**Comment by wedy542700927** [comment]
Thank you for your reply！

**Comment by Luukth** [comment]
Hi, Is there more news on this topic. I would also like to share my cephfs filesystem over NFS using ganesha.
