### ISSUE TITLE
module refcount > 0 in MODULE_FINI

### ISSUE THREAD

**Issue by dirk1730** [nfs-ganesha/nfs-ganesha#293]
v2.5.5

Scenario:
- Start ganesha with 3 exports (using our own fsal)
- Result: module refcount = 3 (OK) (first because of load_fsal, next 2 because of lookup_fsal)
- A LogFatal in the code calls exit()
- MODULE_FINI is called
Problem: The 3 exports are not removed -> unregister_fsal() fails (returns EBUSY) because refcount > 0.

When doing a Remove export (using DBUS command), we can see that one export is unloaded with a call to fsal_detach_export.

**Comment by ffilz** [comment]
There are a number of export refcounting issues that have not been back ported to V2.5-stable yet. Is there any possibility you can use V2.6.1?

**Comment by dirk1730** [comment]
Not really. 2.6 does only support extended operations. And we didn't implement them (yet).
We are at a stage in our development where implementing the extended operations is not a viable option.

**Comment by was4** [comment]
On 4/30/18 2:30 AM, Dirk Verheyden wrote:
> Not really. 2.6 does only support extended operations. And we didn't implement them (yet).
> We are at a stage in our development where implementing the extended operations is not a viable option.
> 
Goodness gracious. V2.5 is at the point where only very serious
bugfixes are backported. V2.6 is the latest stable code.

If you are developing a new FSAL, and not in production, it should be
with V2.7-dev.

**Comment by ffilz** [comment]
V2.5 is long out of support by the upstream community. Closing as will not fix.
