### ISSUE TITLE
V2.6.1: Unhook failed

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#295]
Does "unhook failed" mean error here?
```
ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6180300 fd 22 xp_refs 0 sr_rec 0x5622a6154b90 evchan 4 refcnt 6 epoll_fd 18 control fd pair (16:17) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6180760 fd 23 xp_refs 0 sr_rec 0x5622a6154a80 evchan 3 refcnt 6 epoll_fd 21 control fd pair (19:20) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6180b70 fd 24 xp_refs 0 sr_rec 0x5622a6154b90 evchan 4 refcnt 5 epoll_fd 18 control fd pair (16:17) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6180fd0 fd 25 xp_refs 0 sr_rec 0x5622a6154a80 evchan 3 refcnt 5 epoll_fd 21 control fd pair (19:20) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a61813e0 fd 26 xp_refs 0 sr_rec 0x5622a6154b90 evchan 4 refcnt 4 epoll_fd 18 control fd pair (16:17) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6181840 fd 27 xp_refs 0 sr_rec 0x5622a6154a80 evchan 3 refcnt 4 epoll_fd 21 control fd pair (19:20) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6181c50 fd 28 xp_refs 0 sr_rec 0x5622a6154b90 evchan 4 refcnt 3 epoll_fd 18 control fd pair (16:17) unhook failed (9)
22/05/2018 20:15:08 : epoch 5b047a36 : target167114252037.teuthology : ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a61820b0 fd 29 xp_refs 0 sr_rec 0x5622a6154a80 evchan 3 refcnt 3 epoll_fd 21 control fd pair (19:20) unhook failed (9)
```

**Comment by dang** [comment]
That error means we passed an invalid FD to epoll_ctl.  Not sure yet how it can happen.  Are there negative effects seen?

**Comment by supriti** [comment]
This is output from the our internal automated test system. After one test run, it automatically restarts nfs-ganesha. And in the next run there is segfault "Program terminated with signal SIGABRT, Aborted". The backtrace is from glibc no ganesha function. I don't think program termination and "unhook error" would be related. The seg fault does not happen all the time. 

Backtrace
`#0  0x00007f2afc31d0e0 in raise () from /lib64/libc.so.6
#1  0x00007f2afc31e6c1 in abort () from /lib64/libc.so.6
#2  0x00007f2afc360427 in __libc_message () from /lib64/libc.so.6
#3  0x00007f2afc366c43 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f2afc368dc3 in _int_free () from /lib64/libc.so.6
#5  0x00007f2afc44d662 in __libc_thread_freeres () from /lib64/libc.so.6
#6  0x00007f2afce6a57e in start_thread () from /lib64/libpthread.so.0
#7  0x00007f2afc3df82f in clone () from /lib64/libc.so.6
(gdb) frame 7
#7  0x00007f2afc3df82f in clone () from /lib64/libc.so.6
`

End of log file before the ganesha is killed
`nfs_client_id_expire :CLIENT ID :DEBUG :Expiring {0x7f2200005e30 ClientID={Epoch=0x5b047a4d Counter=0x00000002} CONFIRMED Client={0x7f22000037a0 name=(47:Linux NFSv4.0 167.114.252.39/167.114.252.37 tcp) refcount=2} t_delta=69 reservations=0 refcount=3 cb_prog=1073741824 r_addr=167.114.252.39.172.155 r_netid=tcp}
22/05/2018 20:18:59 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[reaper] fs_rm_clid_impl :CLIENT ID :DEBUG :Removed client dir [/var/lib/nfs/ganesha/v4recov/node0/::ffff:167.114.252.39-(96:0x4c696e7578204e465376342e30203136372e3131342e3235322e33392f3136372e3131342e3235322e333720746370)]
22/05/2018 20:18:59 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[reaper] nfs_client_id_expire :CLIENT ID :DEBUG :Expired (done), about to release last reference {0x7f2200005e30 ClientID={Epoch=0x5b047a4d Counter=0x00000002} CONFIRMED Client={0x7f22000037a0 name=(47:Linux NFSv4.0 167.114.252.39/167.114.252.37 tcp) refcount=2} t_delta=69 reservations=0 refcount=3 cb_prog=1073741824 r_addr=167.114.252.39.172.155 r_netid=tcp0x7f2200005e30 ClientID={Epoch=0x5b047a4d Counter=0x00000002} EXPIRED Client={} t_delta=69 reservations=0 refcount=2 cb_prog=1073741824 r_addr=167.114.252.39.172.155 r_netid=tcp}
22/05/2018 20:19:09 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[reaper] reaper_run :CLIENT ID :DEBUG :Now checking NFS4 clients for expiration
22/05/2018 20:19:19 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[reaper] reaper_run :CLIENT ID :DEBUG :Now checking NFS4 clients for expiration
22/05/2018 20:19:39 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[chunk_lru] chunk_lru_run :INODE LRU :DEBUG :After work, threadwait=90 totalwork=0
22/05/2018 20:19:39 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[cache_lru] lru_run :INODE LRU :DEBUG :FD count is 0 and low water mark is 524288: not reaping.
22/05/2018 20:19:39 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[cache_lru] lru_run :INODE LRU :DEBUG :After work, open_fd_count:0  count:3 fdrate:1 threadwait=90
22/05/2018 20:21:09 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[chunk_lru] chunk_lru_run :INODE LRU :DEBUG :After work, threadwait=90 totalwork=0
22/05/2018 20:21:09 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[cache_lru] lru_run :INODE LRU :DEBUG :FD count is 0 and low water mark is 524288: not reaping.
22/05/2018 20:21:09 : epoch 5b047a4d : target167114252037.teuthology : ganesha.nfsd-31667[cache_lru] lru_run :INODE LRU :DEBUG :After work, open_fd_count:0  count:3 fdrate:1 threadwait=90`

**Comment by was4** [comment]
On 5/23/18 9:25 AM, supriti wrote:
> What does this error mean?
> ```
> ganesha.nfsd-31197[Admin] rpc :TIRPC :EVENT :svc_rqst_unhook_events: 0x5622a6180300 fd 22 xp_refs 0 sr_rec 0x5622a6154b90 evchan 4 refcnt 6 epoll_fd 18 control fd pair (16:17) unhook failed (9)

Specifically, it means that during shutdown we have a flag saying that
the event has been added, but when it was unhooked, the system tells us
that it had already been removed.

This is/was a timing issue related to closing the fd.  A close also
removes that event hook.

Once upon a time, the unhook was done before the close.  Somebody
may be doing a close out of order....

I vaguely remember a spot in Ganesha that was closing instead of
SVC_DESTROY().  But I submitted a patch for that long ago.  Maybe
there are more, or my patch wasn't applied, or something.

**Comment by was4** [comment]
On 5/24/18 11:59 AM, supriti wrote:
> Only single coredump was generated. It does not happen all the time. I will update if there is another crash and more helpful backtrace.
> 
Dan and I were tracking down some rare ones a month ago.

I found and fixed one in ntirpc related to heavy delegation
callbacks, but don't remember whether that made V2.6.x yet.

He was working on something with heavy iobench.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
