### ISSUE TITLE
Two node NFS HA Cluster with GlusterFS replicated & distributed volume

### ISSUE THREAD

**Issue by sushobhan78** [nfs-ganesha/nfs-ganesha#296]
NOTE: This is not an issue but more of a question. I am not finding necessary instructions via Google search and so writing here for your help.

I want to setup Two node NFS HA Cluster with GlusterFS replicated & distributed volume. I plan to use CentOS 7.x
Here is what this cluster should do -
1. Both nodes will have independent two storage disk of the same size (in addition to their independent OS disk) and GlusterFS replicated & distributed volume to be configured such that data is replicated between the nodes.
2. If one node goes down, NFS server should come up on the other node with data from node2 which is already replicated from node1.

Request you to guide me to achieve this objective. If there are any clearly noted steps, please share that.

**Comment by dang** [comment]
There's instructions for HA here:
https://docs.gluster.org/en/v3/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/

HA over Gluster is usually active-active, which means both servers would run Ganesha, each with a VIP.  When one goes down, it's VIP would be moved to the other, and clients would recover.  When it comes back up, it's VIP would be moved back.

**Comment by sushobhan78** [comment]
Thanks Dang. I am following the link you mentioned. I have a question regarding ganesh-ha.conf

Here is the sample ganesha-ha.conf file as mentioned in the link:

# Name of the HA cluster created. must be unique within the subnet

HA_NAME="ganesha-ha-360"

# The gluster server from which to mount the shared data volume.

HA_VOL_SERVER="server1"

# The subset of nodes of the Gluster Trusted Pool that form the ganesha HA cluster.

# Hostname is specified.

HA_CLUSTER_NODES="server1,server2,..."

#HA_CLUSTER_NODES="server1.lab.redhat.com,server2.lab.redhat.com,..."

# Virtual IPs for each of the nodes specified above.

VIP_server1="10.0.2.1"

VIP_server2="10.0.2.2"
------------------------------

My question are ---
1. Do I need to create this file in both nodes of a two-node cluster?
2. What should be the value for HA_VOL_SERVER in a two-node cluster? "server1,server2" or just "server1"?

**Comment by dang** [comment]
Yes, you need this on both nodes.  In your case (and the common case), each node should have itself in HA_VOL_SERVER.  That should only be different if you're not running Ganesha on Gluster nodes, which should be the uncommon case.

Also, you'll need to take the ",..." out of HA_CLUSTER_NODES.

**Comment by sushobhan78** [comment]
Stuck in another place. ranger is node1 (primary) and tundra is node2 in my case.

```
[ranger]:/etc/ganesha# ssh-keygen -f /var/lib/glusterd/nfs/secret.pem
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /var/lib/glusterd/nfs/secret.pem.
Your public key has been saved in /var/lib/glusterd/nfs/secret.pem.pub.
The key fingerprint is:
SHA256:6xoUB65INSvQdXaMqOzHlOwyxWnoGfn6Mw1Bk0zpl20 root@ranger.XYZ.net
The key's randomart image is:
+---[RSA 2048]----+
XXXXXXXXXXXXXXXXXX
|   ..o...        |
+----[SHA256]-----+
[ranger]:~# mkdir .ssh
[ranger]:~# ssh-copy-id -i /var/lib/glusterd/nfs/secret.pem.pub root@tundra.XYZ.net
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/var/lib/glusterd/nfs/secret.pem.pub"
The authenticity of host 'tundra.XYZ.net (15.218.120.65)' can't be established.
ECDSA key fingerprint is SHA256:JE+mDEUA/NHpkhw3bvj3FmvHDHwVjw+2+BA4ZYjgMnw.
ECDSA key fingerprint is MD5:56:91:34:f0:d0:82:90:e0:17:2f:c5:59:5f:ac:a4:36.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@tundra.XYZ.net's password: 

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'root@tundra.XYZ.net'"
and check to make sure that only the key(s) you wanted were added.

[ranger]:~# scp /var/lib/glusterd/nfs/secret.* tundra.XYZ.net:/var/lib/glusterd/nfs/
root@tundra.XYZ.net's password: 
secret.pem                                                                                                                      100% 1766     1.7MB/s   00:00    
secret.pem.pub                                                                                                                  100%  406   661.5KB/s   00:00    
**[ranger]:~# gluster nfs-ganesha enable    **### THIS IS WHAT GUIDE SAYS. BUT I AM GETTING ERROR.**
unrecognized word: nfs-ganesha (position 0)**
[ranger]:~# systemctl start nfs-ganesha.service     **#### SO I RAN THIS COMMAND INSTEAD. IS IT CORRECT?**
[ranger]:~# gluster volume set gluster_vol_distributed_replicated ganesha.enable on   **### HOW TO FIX THIS ERROR**
volume set: failed: option : ganesha.enable does not exist
Did you mean auth.allow?
[ranger]:~# 
```

**Comment by kalebskeithley** [comment]
The integrated nfs-ganesha support in Gluster (i.e. the `gluster nfs-ganesha enable` and `gluster volume set $vol ganesha.enable` commands) is only available up to Gluster 3.10.

If you want the integrated support then your only option is to use 3.10.

You can roll your own HA using CTDB or keepalived.

**Comment by sushobhan78** [comment]
Ok. I have Gluster 4.0.2. Can you please point me to doc for "You can roll your own HA using CTDB or keepalived."

**Comment by StefanKaerst** [comment]
https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.4/html-single/administration_guide/#gdeploy_ganesha
https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.4/html/administration_guide/chap-red_hat_storage_volumes#gdeploy_samba

http://keepalived.org/doc/ but the available online resources for keepalived a very thin. IMHO it's better to install it and see man 5 keepalived.conf + trying. it mainly uses linux LVS + heartbeat using VRRP to move a VIP accross machines. I'm not sure how usefull keepalived is regarding NFS HA cluster.
I'm currently trying gdeploy which uses ansible to configure nfs-ganesha for me. it shoud be easy to "reverse engineer" the ansible playbooks, used by gdeploy to figure out which steps are needed for nfs-ganesha HA setup. so you dont have to do it step by step (if you are using CentOS/RHEL :)

CentOS7.5, qemu/kvm guests (gluster 3.10 and gluster 4.1)

HTH

**Comment by thotz** [comment]
@StefanKaerst Did u use glusterfs storage volume for qemu/kvm accessed via ganesha. Do u have any documentation to the same?

**Comment by StefanKaerst** [comment]
hi @thotz,
I managed to run 3 qemu/kvm nodes with glusterfs3.10/nfs-ganesha and pacemaker/corosync (as deployed by RedHats "gdeploy")
I successfully upgraded those VMs to gluster41 without losing cluster functionality.

I used https://gluster.readthedocs.io/en/latest/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/ as a start. 
if you carefully read this you can create a glusterfs/nfs-ganesha cluster without "gedploy". 

some hints:
- qemu/kvm nodes should have 2 NICs (gluster comunication does not seem to work on the first virbr interface of host)
- the pacemaker healthchecks for ganesha are removed in gluster41 packages, so I just copied
/usr/lib/ocf/resource.d/heartbeat/*ganehsa* to the new nodes. I guess keepalived could be used for VIP management as well, although a real cluster only works with pacemaker/corosync.
- "gluster nfs-ganesha enable/disable" is removed in gluster41, but creating a symlink and start nfs-ganesha is sufficent to start ganesha with config files on a replicated glusterfs volume.

nfs mounts from outside to one of the ganesha VIPs worked well. even node shutdown works as excpeted (nfs reconnect took about 20 to 30 seconds). I'm not sure about nfs file looks - I'm still playing around with the VMs.

good look (have fun!)
HTH
Stefan Kärst

**Comment by thotz** [comment]
> hi @thotz,
> I managed to run 3 qemu/kvm nodes with glusterfs3.10/nfs-ganesha and pacemaker/corosync (as deployed by RedHats "gdeploy")
> I successfully upgraded those VMs to gluster41 without losing cluster functionality.
> 
> I used https://gluster.readthedocs.io/en/latest/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/ as a start.
> if you carefully read this you can create a glusterfs/nfs-ganesha cluster without "gedploy".
> 
> some hints:
> 
>     * qemu/kvm nodes should have 2 NICs (gluster comunication does not seem to work on the first virbr interface of host)
> 
>     * the pacemaker healthchecks for ganesha are removed in gluster41 packages, so I just copied
>       /usr/lib/ocf/resource.d/heartbeat/ganehsa* to the new nodes. I guess keepalived could be used for VIP management as well, although a real cluster only works with pacemaker/corosync.
> 
>     * "gluster nfs-ganesha enable/disable" is removed in gluster41, but creating a symlink and start nfs-ganesha is sufficent to start ganesha with config files on a replicated glusterfs volume.
> 
> 
> nfs mounts from outside to one of the ganesha VIPs worked well. even node shutdown works as excpeted (nfs reconnect took about 20 to 30 seconds). I'm not sure about nfs file looks - I'm still playing with the VMs.
> 
> good look (have fun!)
> HTH
> Stefan Kärst

Cool. Thanks for sharing the info

**Comment by ffilz** [comment]
This question looks answered. Note that in the future, you might want to use the support mailing list: support@lists.nfs-ganesha.org for this kind of question.
