### ISSUE TITLE
Client permission issue

### ISSUE THREAD

**Issue by tonyabrhm** [nfs-ganesha/nfs-ganesha#300]
Hey,

I am experiencing issues with permissions when using NFS Ganesha. If I set the access_type within the EXPORT block, the client can connect. When I specify the client in the CLIENT block, I receive an access denied error message. Please see my config below, any help would be appreciated.

EXPORT

{

        ## Export Id (mandatory, each EXPORT must have a unique Export_Id)

        Export_Id = 1;

        ## Exported path (mandatory)

        Path = /exp;

        ## Pseudo Path (required for NFSv4 or if mount_path_pseudo = true)

        Pseudo = /expsp;

        ## Restrict the protocols that may use this export.  This cannot allow

        ## access that is denied in NFS_CORE_PARAM.

        Protocols = 3,4;

        Transports = "UDP", "TCP";

        ## Exporting FSAL

        FSAL {

                Name = share;

                hostname = "test01";

                volume = "sharevol01";

        }

CLIENT

{

        Clients = 192.168.1.223;

        Access_Type = "RW";

        Squash = No_Root_Squash;

        }

}

**Comment by ffilz** [comment]
Did you verify the address given for the client is the one that it actually uses for communication? Is it possible it is using IPv6?

Otherwise, your config looks fine.

**Comment by tonyabrhm** [comment]
Nope. Definitely not ipv6.  If i move the access_type into the EXPORT block it works. Just trying to ensure the share is as secure as possible

**Comment by ffilz** [comment]
Try adding LOG { COMPONENTS { EXPORT = Full_Debug; } } 
and see what access decisions Ganesha is actually making (post the log on pastebin or something like it if you can).

**Comment by dang** [comment]
Can you try adding:
Sectype = sys,krb5,krb5i,krb5p;

The default sec type doesn't have krb in it, but the linux client always tries it.  I've had issues with this in the past.

**Comment by tonyabrhm** [comment]
Hey

Unfortunately, that didnt seem to work. Same error of access denied.

Thanks

**Comment by ffilz** [comment]
So did you try the debug logging? That will help identify the issue

**Comment by tonyabrhm** [comment]
Hi Frank

Sorry I didnt see your message there. Will give this a shot shortly

**Comment by tonyabrhm** [comment]
@ffilz please find logs attached. Apologies, I have changed the naming of a few things, if anything doesn't add up let me know and I will explain. Thanks for your help.

[https://pastebin.com/embed_js/kB8ThNvC](url)

**Comment by tonyabrhm** [comment]
I think you are onto something with the ipv6 comment Frank. After examining the logs, I can see that ganesha is interpreting my client as ipv6 and gives an error: ffff:192.168.1.225 is not allowed to access Export_Id 1 but then further down in the logs there is a conversion from ffff:192.168.1.225 to 192.168.1.225.

 Is there another parameter I need to set in the logs to force ipv4, all my servers use ipv4, so I am unsure why this is happening.

Cheers

**Comment by tonyabrhm** [comment]
After a bit of testing, I can definitely mount the NFS share on my client, but it will not accept the CLIENT block and only loads in the EXPORT block parameters. At least this tells me we can connect via the network.

Spent a considerable amount of time examining the logs and trying various settings but cannot get this to work.

**Comment by JoelStienlet** [comment]
Hello,
I supposed you've tried to set: 
Clients = ffff:192.168.1.225; 
already and that didn't work? The config file looks fine to me too... Another solution would be to block all incoming connections except from 192.168.1.225 using iptables.
But anyway, IMHO if you really want to make this share secure, you have no other choice than use cryptography, and enable krb5i (authentication only) or krb5p (authentication + encryption).
Anything else will just protect you against the average user discovering the share by chance.

**Comment by tonyabrhm** [comment]
Yeah I tried that with no success. I am pretty new to Ganesha, in an ideal world I would like to tie this directory down to a specific user, but I don't know how to do that with Ganesha.

**Comment by tonyabrhm** [comment]
OK, I have figured it out... should have been obvious to me really but a few red herrings were thrown into the mix.

I have two gluster servers which mirror this NFS share. I used a network load balancer for fault tolerance and that was the problem. It was routing via the VIP rather than my client IP addresses.

So this leads me to my next two questions:

1. Is it possible to configure permissions by user?
2. Is it possible to configure fault tolerance with Ganesha?

Cheers all for help.

**Comment by JoelStienlet** [comment]
1. I think the server always uses unix permissions, I haven't seen any option to override these... Maybe you could "overlayfs" without "upper dir" to make a read-only image of the directories you want to protect? just my 2 cent.

**Comment by ffilz** [comment]
Ah, yes, load balancers don't tend to work with NFS unless they assign clients statically (this client always is sent to this server). HA fault tolerance has been done with Gluster using Pacemaker/Corosync. There is work underway to convert to Storhaug. See:

https://docs.gluster.org/en/latest/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/

As Joel has mentioned, Kerberos provides the best security. It does allow "per user" security in two ways:

1. Only users who are authorized to use NFS services in the Kerberos realm may use such (you need to have a Kerberos principle to access any services). This may not allow fine grained per export control, but does at least let you know the user has some level of trust.

2. The Kerberos principle is translated into POSIX uid/gid/alt groups style credentials in the NFS server. The client/user is not able to spoof the credentials (even with root access on the client - unless they have a root Kerberos principle). This allows the POSIX permissions on files (mode) to be trusted.

FSAL_GLUSTER does support POSIX ACLs for more flexibility than POSIX mode.

I hope that helps

Frank

**Comment by ffilz** [comment]
Closing as will not fix.
