### ISSUE TITLE
Please add Configuration steps for ceph

### ISSUE THREAD

**Issue by vasukulkarni** [nfs-ganesha/nfs-ganesha#302]
Currently the document doesn't list how to configure ceph, please add the basic configuration steps on how to use with ceph.

**Comment by dang** [comment]
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/config_samples/ceph.conf
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-ceph-config.rst

**Comment by vasukulkarni** [comment]
thanks @dang

**Comment by supriti** [comment]
Closing the iss

**Comment by supriti** [comment]
Sorry closed by mistake.

**Comment by ajarr** [comment]
There is also this for CephFS
http://docs.ceph.com/docs/master/cephfs/nfs/
and for RGW
http://docs.ceph.com/docs/master/radosgw/nfs/

**Comment by ffilz** [comment]
Closed as resolved.
