### ISSUE TITLE
obj_handle in mdcache_fsal_obj_handle wastes significant mdcache memory

### ISSUE THREAD

**Issue by michaelzeis** [nfs-ganesha/nfs-ganesha#303]
I was curious as to why an individual mdcache_fsal_obj_handle entry was so large on my system:

`
(gdb) print sizeof(struct mdcache_fsal_obj_handle)
$73 = 1624
`

A significant portion of that comes from the  mdcache obj_ops (struct fsal_obj_ops) in the fsal_obj_handle:

`
(gdb) print sizeof( struct fsal_obj_ops)
$72 = 512
`

Inside fsal_obj_ops is kept a copy of the entire mdcache operations vector.   This causes it to be duplicated and filled in for every mdcache entry.

Seems like you could remove all this duplicated obj_obs vector space in the mdcache (and the time spent initializing it each time) by changing the struct fsal_obj_handle to use a pointer to the operations vector instead:

`
struct fsal_obj_handle {
        struct glist_head handles;      /*< Link in list of handles under
                                           the same FSAL. */
        struct fsal_filesystem *fs;     /*< Owning filesystem */
        struct fsal_module *fsal;       /*< Link back to fsal module */
        struct fsal_obj_ops obj_ops;    /*< Operations vector */   <--- CHANGE to *obj_ops
`

**Comment by fun4u** [comment]
Obviously, fsal_obj_handle has occupied too much memory. Howerver, there are too much links to this obj such as state_t or last_entry in state_owner，and we cannot just free this memory so simplely. Instead, we should share fsal_obj_handle in memory rather than creating a new one when a new compound data is introduce in the new rpc.

**Comment by ffilz** [comment]
While this may be worthy to address, I am closing this as will not fix,
