### ISSUE TITLE
2.5.3 segfault on CentOS 6.9

### ISSUE THREAD

**Issue by werenzo** [nfs-ganesha/nfs-ganesha#304]
Hello, I'm trying to configure nfs access for glusterfs 3.12 volume on a CentOS 6.9 server.

I followed the gluster doc https://docs.gluster.org/en/v3/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/ but I'm experiencing segfault (also happening with 2.5.5)

I also started this way

ganesha.nfsd -f /etc/ganesha/ganesha.conf -L /var/log/ganesha_debug.log -N DEBUG

Here's what I'm seeing on messages (I'll attach ganesha_debug.log)
[ganesha_debug.log](https://github.com/nfs-ganesha/nfs-ganesha/files/2101447/ganesha_debug.log)

Jun 14 10:20:47 node3001 kernel: glustertimer[8754]: segfault at 7fb9db931e4a ip 000000396562f119 sp 00007fb9d3c4d4c0 error 7 in libglusterfs.so.0.0.1[3965600000+f9000]
Jun 14 10:20:50 node3001 abrt[9070]: Saved core dump of pid 8745 (/usr/bin/ganesha.nfsd) to /var/spool/abrt/ccpp-2018-06-14-10:20:47-8745 (1048576000 bytes)
Jun 14 10:20:50 node3001 abrtd: Directory 'ccpp-2018-06-14-10:20:47-8745' creation detected
Jun 14 10:20:50 node3001 abrtd: Package 'nfs-ganesha' isn't signed with proper key
Jun 14 10:20:50 node3001 abrtd: 'post-create' on '/var/spool/abrt/ccpp-2018-06-14-10:20:47-8745' exited with 1
Jun 14 10:20:50 node3001 abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2018-06-14-10:20:47-8745'

Could you help to debug issue?

Thank you

**Comment by werenzo** [comment]
Hello, it seems this issue was helpful for me: https://github.com/nfs-ganesha/nfs-ganesha/issues/181

Could the installer can make "/var/log/ganesha" dir by default?

**Comment by dang** [comment]
The installer should be making /var/log/ganesha/ where log files are supposed to go.

**Comment by kalebskeithley** [comment]
The "installer" only makes /var/log/ganesha on rhel/centos 7, due to the fact that it's in the %if %{with_systemd} block. I'm not sure why that's the case.

Same in both the upstream .spec and in the .spec used to build the packages for the CentOS Storage SIG.  It's still that way on the HEAD of the master branch.

**Comment by dang** [comment]
Interesting.  Is it worth fixing?  How log is RHEL/Centors 6 relevant?  It appears to be because it went in with a systemd-specific change, and so was added to the same part of the file.

**Comment by werenzo** [comment]
Thanks for your replies, 

another thing I've noticed: if I configure logging in ganesha.conf to use /var/log/ganesha/somefile, some logging still goes to /var/log/ganesha.log.

I don't know if this can be another issue related to CentOS 6.

**Comment by dang** [comment]
Logging by default goes to syslog, so logging going to /var/log/ganesha.log must be configured.  Log location can be configured in the conf file, or passed on the command line.  Check your init scripts to see if it's passing a log option to ganesha on startup.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
