### ISSUE TITLE
XFS FSAL problem with symlink

### ISSUE THREAD

**Issue by wdeviers** [nfs-ganesha/nfs-ganesha#307]
Problem: Creating a symlink against a mount (4 or 3) backed by XFS using XFS FSAL breaks things eventually (1-2 minutes)

Running:
```
root@ashdevnfs00:/exports/landing_pages_dev# dpkg -l|grep ganesha
ii  nfs-ganesha                     2.6.2-ubuntu1~xenial2                      amd64        nfs-ganesha is a NFS server in User Space
ii  nfs-ganesha-xfs:amd64           2.6.2-ubuntu1~xenial2                      amd64        nfs-ganesha fsal xfs libraries
```

Config as:

```
EXPORT
{
	# Export Id (mandatory, each EXPORT must have a unique Export_Id)
	Export_Id = 10;

	# Exported path (mandatory); mostly used for NFS3-
	Path = "/exports/landing_pages_dev";

	# Pseudo Path (required for NFS v4)
	Pseudo = "/landing_pages_dev";

	# Required for access (default is None)
	# Could use CLIENT blocks instead
	Access_Type = RW;
	SecType = sys;
	Squash = no_root_squash;

	# Exporting FSAL
	FSAL {
	 	Name = "XFS";
	}

	CLIENT {
		
		Clients = 10.40.5.28,10.130.250.244,10.132.132.100,10.40.5.28;
		Squash = no_root_squash;
		Access_Type = RW;
		protocols = "4";
	}
```

`/dev/mapper/nfs_server-landing_pages_dev on /exports/landing_pages_dev type xfs (rw,relatime,attr2,discard,inode64,noquota)`

Steps to Repro:

1. Mount export
1. _mkdir test_
1. _ln -s test good_symlink_
1. ls -l 
```
drwxr-xr-x 8 2000 root 151 Apr  4 00:29 autolandingpages
drwxr-xr-x 2 root root   6 Jun 21 21:01 test
lrwxrwxrwx 1 root root   4 Jun 21 21:01 good_symlink -> test
```
1. sleep 300;
1. ls -l 
```
wdeviers@devlp00:/mnt/nfslp_new$ ls -l
ls: cannot access 'good_symlink': Input/output error
ls: reading directory '.': Remote I/O error
total 0
drwxr-xr-x 8 2000 root 151 Apr  4 00:29 autolandingpages
drwxr-xr-x 2 root root   6 Jun 21 21:01 test
l????????? ? ?    ?      ?            ? good_symlink
```

Log Output:

```
root@ashdevnfs00:~# tail -n 4 /var/log/ganesha/ganesha.log
21/06/2018 21:26:05 : epoch 5b2c1721 : ashdevnfs00 : ganesha.nfsd-36207[svc_2] nfs4_readdir_callback :NFS READDIR :CRIT :nfs4_FSALattr_To_Fattr failed to convert attr
21/06/2018 21:26:08 : epoch 5b2c1721 : ashdevnfs00 : ganesha.nfsd-36207[svc_7] nfs4_readdir_callback :NFS READDIR :CRIT :nfs4_FSALattr_To_Fattr failed to convert attr
21/06/2018 21:26:10 : epoch 5b2c1721 : ashdevnfs00 : ganesha.nfsd-36207[svc_3] nfs4_readdir_callback :NFS READDIR :CRIT :nfs4_FSALattr_To_Fattr failed to convert attr
21/06/2018 21:26:58 : epoch 5b2c1721 : ashdevnfs00 : ganesha.nfsd-36207[svc_12] nfs4_readdir_callback :NFS READDIR :CRIT :nfs4_FSALattr_To_Fattr failed to convert attr
```

Mount point is now broken across all clients. Additional access yeilds:

```
wdeviers@devlp00:/mnt/nfslp_new$ ls -l
ls: reading directory '.': Remote I/O error
```

Test is **not** repeatable using VFS backend (literal string replace of 'XFS' to 'VFS' in export config)

**Comment by ffilz** [comment]
Could you enable EVENT logging, that will tell us which attribute is causing failure and might shed light on what is going on.

**Comment by wdeviers** [comment]
If I understand you correctly, EVENT was already on via /etc/defaults/nfs-ganesha.  I bumped it to debug.  This appears to be the relevant part of the DEBUG log -

`22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_op_readdir :NFS READDIR :DEBUG :dircount=8172 ma
xcount=29419 cookie=0 estimated_num_entries=50
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] mdcache_readdir :NFS READDIR :DEBUG :NFS READDIR: DEBUG: Calling mdcache_readdir_chunked whence=0
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 5108
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] encode_fsid :NFS4 :DEBUG :fsid.major = 3028392669, fsid.minor = 2920809569
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 17558
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] encode_fsid :NFS4 :DEBUG :fsid.major = 3028392669, fsid.minor = 2920809569
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 25086
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] encode_fsid :NFS4 :DEBUG :fsid.major = 3028392669, fsid.minor = 2920809569
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 9367
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_readdir_callback :NFS READDIR :CRIT :nfs4_FSALattr_To_Fattr failed to convert attr
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] mdcache_readdir_chunked :NFS READDIR :DEBUG :NFS READDIR: DEBUG: readdir completed, eod = false
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_op_readdir :NFS READDIR :DEBUG :fsal_readdir returned No error
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_op_readdir :NFS READDIR :DEBUG :Tracker error
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_op_readdir :NFS READDIR :DEBUG :Returning NFS4ERR_SERVERFAULT
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_Compound :NFS4 :DEBUG :Status of OP_READDIR in position 1 = NFS4ERR_SERVERFAULT
22/06/2018 18:43:51 : epoch 5b2d42e0 : ashdevnfs00 : ganesha.nfsd-34918[svc_7] nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_SERVERFAULT lastindex = 1`

**Comment by dang** [comment]
Unfortunately, the attribute conversion failure log in 2.6.2 is a
FULL_DEBUG log, not an EVENT log, like it is in 2.7.   To see which
attribute is failing in 2.6.2, you're going to have to turn on FULL_DEBUG
for NFS4.

Daniel

**Comment by wdeviers** [comment]
Here's what looks important to me.  Attached is the full log.  That's a tail -f |grep -v dbus; if you need the chatty dbus messages let me know.  Thanks!

`25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_readdir_callback :RW LOCK :F_DBG :Unlocked 0x7f4d640057d8 (&obj->state_hdl->state_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/Protocols/NFS/nfs4_op_readdir.c:273
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_FSALToFhandle :FH :F_DBG :NFS4 Handle 0x0 export id 10
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_FSALToFhandle :FH :F_DBG :NFS4 Handle (29:0x4300000a18dd9a81b4610418ae0e000000271cb1e986bf050000000000)
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] mdcache_getattrs :RW LOCK :F_DBG :Got read lock on 0x7f4d640053c0 (&entry->attr_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:1102
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] mdcache_getattrs :RW LOCK :F_DBG :Unlocked 0x7f4d640053c0 (&entry->attr_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:1138
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=00000680 NO_FILE_TYPE
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] fsal_check_access_no_acl :NFS4 ACL :F_DBG :Nothing was requested
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Maximum allowed attr index = 55
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encode FAILED for attr 1, name = FATTR4_TYPE
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_readdir_callback :NFS READDIR :CRIT :nfs4_FSALattr_To_Fattr failed to convert attr
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] _mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x5606be33cd20 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1868
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] _mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x5606be33cd20 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1875
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] mdcache_readdir_chunked :NFS READDIR :F_DBG :NFS READDIR: FULLDEBUG: dirent = 0x7f4d64005a20 yomomma, cb_result = DIR_TERMINATE, eod = false
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] mdcache_readdir_chunked :NFS READDIR :DEBUG :NFS READDIR: DEBUG: readdir completed, eod = false
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] mdcache_readdir_chunked :RW LOCK :F_DBG :Unlocked 0x5606bf4f4e70 (&directory->content_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3252
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_op_readdir :NFS READDIR :DEBUG :fsal_readdir returned No error
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_op_readdir :NFS READDIR :DEBUG :Tracker error
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_op_readdir :NFS READDIR :DEBUG :Returning NFS4ERR_SERVERFAULT
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] LogCompoundFH :FH :F_DBG :Current FH  File Handle V4: Len=29 4300000a18dd9a81b4610418ae0e000000000000006000000000000000
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] LogCompoundFH :FH :F_DBG :Saved FH    File Handle V4: Len=0 <null>
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_Compound :NFS4 :DEBUG :Status of OP_READDIR in position 1 = NFS4ERR_SERVERFAULT
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_SERVERFAULT lastindex = 1
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] _mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x5606be33d0a0 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1868
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] _mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x5606be33d0a0 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1875
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] compound_data_Free :EXPORT :F_DBG :put export ref for id 10 /exports/landing_pages_dev, refcount = 1
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] nfs_rpc_process_request :DISP :F_DBG :Before svc_sendreply on socket 24
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] rpc :TIRPC :F_DBG :xdr_ioq_reset() xioq 0x7f4d64002cd0 head 0x7f4d64007460 wh_pos 0
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] rpc :TIRPC :F_DBG :xdr_reply_encode:93 ACCEPTED INLINE
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] rpc :TIRPC :F_DBG :xdr_reply_encode:109 SUCCESS
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] rpc :TIRPC :F_DBG :svc_ref_it() 0x7f4d74000ad0 fd 24 xp_refs 4 af 10 port 771 @ svc_ioq_write_now:250
25/06/2018 13:31:52 : epoch 5b30ee50 : ashdevnfs00 : ganesha.nfsd-30663[svc_6] rpc :TIRPC :F_DBG :svc_release_it() 0x7f4d74000ad0 fd 24 xp_refs 3 af 10 port 771 @ svc_ioq_write:218
`
[nfs_symlinks.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/2133304/nfs_symlinks.gz)

**Comment by wdeviers** [comment]
Another oddity: restarting the service restores the symlinks to the correct state for a while.  Here's what a 'good' read looks like:

> 25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=00000680 Valid Mask=0015dfce Supported Mask=0015dfce SYMBOLIC_LINK numlinks=0x1 size=0x4 mode=0777 owner=0x0 group=0x0 atime=25/06/2018 13:30:04 mtime=22/06/2018 18:42:21
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] fsal_check_access_no_acl :NFS4 ACL :F_DBG :Nothing was requested
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Maximum allowed attr index = 55
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 1, name = FATTR4_TYPE
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 3, name = FATTR4_CHANGE
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 4, name = FATTR4_SIZE
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] encode_fsid :NFS4 :DEBUG :fsid.major = 3028392669, fsid.minor = 2920809569
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 8, name = FATTR4_FSID
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 11, name = FATTR4_RDATTR_ERROR
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 19, name = FATTR4_FILEHANDLE
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 20, name = FATTR4_FILEID
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 33, name = FATTR4_MODE
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 35, name = FATTR4_NUMLINKS
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] xdr_encode_nfs4_princ :RW LOCK :F_DBG :Got read lock on 0x55f2ea959a40 (group ? &idmapper_group_lock : &idmapper_user_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/idmapper/idmapper.c:124
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] xdr_encode_nfs4_princ :RW LOCK :F_DBG :Unlocked 0x55f2ea959a40 (group ? &idmapper_group_lock : &idmapper_user_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/idmapper/idmapper.c:139
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 36, name = FATTR4_OWNER
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] xdr_encode_nfs4_princ :RW LOCK :F_DBG :Got read lock on 0x55f2ea959a00 (group ? &idmapper_group_lock : &idmapper_user_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/idmapper/idmapper.c:124
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] xdr_encode_nfs4_princ :RW LOCK :F_DBG :Unlocked 0x55f2ea959a00 (group ? &idmapper_group_lock : &idmapper_user_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/idmapper/idmapper.c:139
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 37, name = FATTR4_OWNER_GROUP
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 41, name = FATTR4_RAWDEV
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 45, name = FATTR4_SPACE_USED
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 47, name = FATTR4_TIME_ACCESS
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 52, name = FATTR4_TIME_METADATA
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 53, name = FATTR4_TIME_MODIFY
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_FSALattr_To_Fattr :NFS4 :F_DBG :Encoded attr 55, name = FATTR4_MOUNTED_ON_FILEID
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] _mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x55f2ea9676c0 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1868
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] _mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x55f2ea9676c0 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1875
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] mdcache_readdir_chunked :NFS READDIR :F_DBG :NFS READDIR: FULLDEBUG: dirent = 0x7f28d0006370 test, cb_result = DIR_CONTINUE, eod = true
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] mdcache_readdir_chunked :NFS READDIR :DEBUG :NFS READDIR: DEBUG: readdir completed, eod = true
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] mdcache_readdir_chunked :RW LOCK :F_DBG :Unlocked 0x55f2ebc16e70 (&directory->content_lock) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3252
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_op_readdir :NFS READDIR :DEBUG :fsal_readdir returned No error
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_op_readdir :NFS READDIR :DEBUG :Returning NFS4_OK
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] LogCompoundFH :FH :F_DBG :Current FH  File Handle V4: Len=29 4300000a18dd9a81b4610418ae0e000000000000006000000000000000
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] LogCompoundFH :FH :F_DBG :Saved FH    File Handle V4: Len=0 <null>
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_Compound :NFS4 :DEBUG :Status of OP_READDIR in position 1 = NFS4_OK
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] _mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x55f2ea9670a0 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1868
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] _mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x55f2ea9670a0 (&(qlane)->mtx) at /build/nfs-ganesha-EF6_Us/nfs-ganesha-2.6.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1875
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] compound_data_Free :EXPORT :F_DBG :put export ref for id 10 /exports/landing_pages_dev, refcount = 1
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs_rpc_process_request :DISP :F_DBG :Before svc_sendreply on socket 20
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :xdr_ioq_reset() xioq 0x55f2eea06ce0 head 0x55f2eea06e40 wh_pos 0
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :xdr_reply_encode:93 ACCEPTED INLINE
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :xdr_reply_encode:109 SUCCESS
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :svc_ref_it() 0x7f28f4000ad0 fd 20 xp_refs 4 af 10 port 771 @ svc_ioq_write_now:250
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :svc_release_it() 0x7f28f4000ad0 fd 20 xp_refs 3 af 10 port 771 @ svc_ioq_write:218
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :xdr_ioq_destroy() xioq 0x55f2eea06ce0
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs_rpc_process_request :DISP :F_DBG :After svc_sendreply on socket 20
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] rpc :TIRPC :F_DBG :xdr_bytes_free:641 already free
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs_dupreq_rele :DUPREQ :F_DBG :releasing no-cache res 0x55f2eea023b0
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs4_Compound_Free :SESSIONS :F_DBG :Compound Free 0x55f2eea023b0 (resarraylen=2)
25/06/2018 13:44:03 : epoch 5b30f162 : ashdevnfs00 : ganesha.nfsd-32152[svc_16] nfs_rpc_decode_request :DISP :DEBUG :SVC_DECODE on 0x7f28f4000ad0 fd 20 (::ffff:10.132.132.100:771) xid=126268389 returned XPRT_IDLE

**Comment by dang** [comment]
It looks like XFS returned invalid attributes from stat() the first time.  Since the attribute cache times out, a later check will refresh the attributes, which worked that time, resulting in the correct attributes being set.

**Comment by wdeviers** [comment]
To be clear, the "Working" dump was after restarting ganesha.  It definitely never resolves on its own.  Once the symlinks go berserk, the entire NFS mount gets IO failures for every client accessing it until a restart of nfsd

**Comment by dang** [comment]
Ah, okay, so presumably all stat() calls are returning invalid attributs, and possibly other calls as well.  Maybe the handles are being messed up, so open_by_handle_at() is failing to return a valid handle?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
