### ISSUE TITLE
Configure SNMP ADM

### ISSUE THREAD

**Issue by mknapphrt** [nfs-ganesha/nfs-ganesha#309]
Sorry for posting so many issues, I don't know where else to post questions. I'm trying to follow the guide (https://github.com/nfs-ganesha/nfs-ganesha/wiki/StatsSNMP#Requirements) for getting stats from ganesha. It says you need to enable it for ganesha, because it's off by default. It says to do this:
```
./configure --with-fsal=FUSE --enable-snmp-adm
```
But there is no configure file anywhere and I can't figure out how to enable it.

Thanks

**Comment by dang** [comment]
SNMP stats support was removed in 2013, sorry.  The documentation is out-of-date.

**Comment by mknapphrt** [comment]
Is there an alternative way to get stats now? Or just nothing at all?
