### ISSUE TITLE
FSAL_RGW: Encounter input/output error when cp files

### ISSUE THREAD

**Issue by sdkfzv** [nfs-ganesha/nfs-ganesha#321]
nfs-ganesha version: V2.6.2-0-gb9685b8
ceph version: 12.2.2 luminous (stable)
os:  centos 7.2.1511

I mount the nfs to a local directory with the option "sync", and then cp a file to the nfs directory.
but hit the input/output error.

mount -t nfs4 -o sync 172.16.3.127:/ /mnt/nfs/
`172.16.3.127:/ on /mnt/nfs type nfs4 (rw,relatime,sync,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.16.3.128,local_lock=none,addr=172.16.3.127)`

```
[root@tw-node3228 ~]# cp 50M.file /mnt/nfs/dir0/
cp: error writing ‘/mnt/nfs/dir0/50M.file’: Input/output error
cp: failed to extend ‘/mnt/nfs/dir0/50M.file’: Input/output error
```

It seems like the unordered io issue.
But some patches should be in my ganesha&ceph version already, such as below

https://github.com/nfs-ganesha/nfs-ganesha/pull/193/files
https://github.com/ceph/ceph/pull/17809/files

So why the input/output error happened ?
Thanks.

the ganesha.conf:
```
EXPORT
{
                # Export Id (mandatory, each EXPORT must have a unique Export_Id)
                Export_Id = 1;
                # Exported path (mandatory)
                Path = /;
                # Pseudo Path (for NFS v4)
                Pseudo = /;
                # Access control options
                Access_Type = RW;
                Squash = No_Root_Squash;
                #Root_Access = "";
                #Access = "";
                # NFS protocol options
                Transports = "TCP";
                Protocols = "4";
                SecType = "sys";
                # Exporting FSAL
                FSAL {
                        Name = RGW;
                        User_Id = "cephtest";
                        Access_Key_Id = "MYURJT2C9PYZRY6EBY9A";
                        Secret_Access_Key = "8vinUKwLtNHSSHhRJunm326RSZcnvJweDuRjvc1K";
                }
}
RGW {
                ceph_conf = "/etc/ceph/ceph.conf";
                name = "client.rgw.tw-node3227";
                cluster = "ceph";
                init_args = "-d --debug-rgw=16";
}
```

**Comment by dang** [comment]
That ganesha code has not been committed to any upstream branch.  Have you patched your local ganesha with it?

**Comment by sdkfzv** [comment]
no... I'll patch and test it again. Thanks.

I tried to mount the same nfs server on another machine with the same option, but no IO error occurred.
Seems like some configure errors on my first machine?

Then I updated the nfs-utils version to nfs-utils-1.3.0-0.54, and mounted with "vers=4.1".
After that I got the "Operation not permitted" when I wrote some data to the dir.

```
# rpm -qa|grep nfs
libnfsidmap-0.25-12.el7.x86_64
nfs-utils-1.3.0-0.54.el7.x86_64

mount|grep nfs4
172.16.3.127:/ on /mnt/nfs type nfs4 (rw,relatime,sync,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.16.3.129,local_lock=none,addr=172.16.3.127)

#  echo "test" > /mnt/nfs/dir0/test
bash: /mnt/nfs/dir0/test: Operation not permitted
```

**Comment by taoCH** [comment]
I think this links to the bug in ceph side. Try to set librgw debug level to 20 in ceph.conf, like:
```
vim /etc/ceph/ceph.conf

[client.rgw.tw-node3227]
....
log file = /var/log/ceph/ceph-client.rgw.tw-node3227.log
debug_rgw = 20
```

Then re-run the scenario and check the  /var/log/ceph/ceph-client.rgw.tw-node3227.log

**Comment by f1-outsourcing** [comment]
I have something similar with cephfs. Files added on a cephfs client node, give a Input/output error on the nfs client node. (fasl CEPH)

nfs-ganesha-xfs-2.6.1-0.1.el7.x86_64
nfs-ganesha-2.6.1-0.1.el7.x86_64
nfs-ganesha-mem-2.6.1-0.1.el7.x86_64
nfs-ganesha-vfs-2.6.1-0.1.el7.x86_64
nfs-ganesha-rgw-2.6.1-0.1.el7.x86_64
nfs-ganesha-ceph-2.6.1-0.1.el7.x86_64

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
