### ISSUE TITLE
Config error?

### ISSUE THREAD

**Issue by fun4u** [nfs-ganesha/nfs-ganesha#322]
Anyone knows that? I have not modified any configuration in this file...
-----------------------
yacc: e - line 1 of "/root/third-party/nfs-ganesha/src/config_parsing/conf_yacc.y", syntax error
%code top {
^
make: *** [/root/third-party/nfs-ganesha/src/config_parsing/conf_yacc.c] Error 1
-----------------------
thx !

**Comment by dang** [comment]
What version of Ganesha?  What version of yacc and/or bison?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
