### ISSUE TITLE
2.7rc1 crash with gpfs fsal

### ISSUE THREAD

**Issue by diederichm** [nfs-ganesha/nfs-ganesha#326]
(gdb) bt full
#0  0x000000000052651a in UNALIGNED_LOAD64 (
    p=0x7f189001e6d8 <Address 0x7f189001e6d8 out of bounds>)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/support/city.c:43
        result = 0
#1  0x0000000000526555 in Fetch64 (
    p=0x7f189001e6d8 <Address 0x7f189001e6d8 out of bounds>)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/support/city.c:92
No locals.
#2  0x0000000000526d29 in CityHash64 (s=0x7f1250001740 "", len=26843664320)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/support/city.c:271
        x = 0
        y = 0
        z = 0
        temp = 0
        v = {first = 0, second = 0}
        w = {first = 0, second = 0}
#3  0x00000000004fcb27 in fsal_acl_hash_both (hparam=0x27ed850, 
    key=0x7f12a35116a0, index=0x7f12a3511604, rbthash=0x7f12a35115f0)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/support/nfs4_acls.c:37
No locals.
#4  0x00000000004efbfe in compute (ht=0x27ed850, key=0x7f12a35116a0, 
    index=0x7f12a3511604, rbt_hash=0x7f12a35115f0)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/hashtable/hashtable.c:248
        __PRETTY_FUNCTION__ = "compute"
#5  0x00000000004f0624 in hashtable_getlatch (ht=0x27ed850, 
    key=0x7f12a35116a0, val=0x7f12a3511680, may_write=true, 
    latch=0x7f12a3511660)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/hashtable/hashtable.c:490
        index = 0
        locator = 0x0
        data = 0x0
        rbt_hash = 0
        rc = HASHTABLE_SUCCESS
        __PRETTY_FUNCTION__ = "hashtable_getlatch"
        __func__ = "hashtable_getlatch"
#6  0x00000000004fd642 in nfs4_acl_release_entry (acl=0x7f12500019b0)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/support/nfs4_acls.c:204
        key = {addr = 0x7f1250001740, len = 26843664320}
        old_key = {addr = 0x0, len = 43157936}
        old_value = {addr = 0x0, len = 43157936}
        rc = 0
        latch = {locator = 0x0, rbt_hash = 139718036825656, index = 2740000432}
        status = 0
        __func__ = "nfs4_acl_release_entry"
        __PRETTY_FUNCTION__ = "nfs4_acl_release_entry"
#7  0x0000000000556bdb in mdc_update_attr_cache (entry=0x28f6f30, 
    attrs=0x7f12a3511760)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3275
No locals.
#8  0x0000000000544072 in mdcache_refresh_attrs (entry=0x28f6f30, 
    need_acl=true, need_fslocations=false, invalidate=true)
    at /usr/src/debug/nfs-ganesha-2.7-rc1/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:844
        attrs = {request_mask = 9223372036872986622, valid_mask = 385006, 
          supported = 26599422, type = DIRECTORY, filesize = 8388608, fsid = {
            major = 12622160777320136202, minor = 2}, acl = 0x7f1288002270, 
          fileid = 326656, mode = 448, numlinks = 2, owner = 0, group = 0, 
          rawdev = {major = 0, minor = 0}, atime = {tv_sec = 1527235850, 
            tv_nsec = 468777516}, creation = {tv_sec = 0, tv_nsec = 0}, 
          ctime = {tv_sec = 1527265752, tv_nsec = 570504000}, mtime = {
            tv_sec = 1527265752, tv_nsec = 570504000}, chgtime = {
            tv_sec = 1527265752, tv_nsec = 570504000}, spaceused = 8388608, 
          change = 2097769752, generation = 0, expire_time_attr = 0, 
          fs_locations = 0x0}
        status = {major = ERR_FSAL_NO_ERROR, minor = 0}
        oldmtime = {tv_sec = 1527265752, tv_nsec = 570504000}
        __func__ = "mdcache_refresh_attrs"

**Comment by dang** [comment]
So, none of this code has changed in a long time.  Do you know what was the last version that worked?

**Comment by qrGitHub** [comment]
hi @diederichm，I encountered a similar problem.
Did you find a solution?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Comment by malahal** [comment]
> hi @diederichm，I encountered a similar problem.
> Did you find a solution?

Do you still have this issue? I will re-open this issue if you still have it.
