### ISSUE TITLE
FSAL_VFS(and GPFS?): bind mounted files can confuse posix_create_file_system

### ISSUE THREAD

**Issue by wongma7** [nfs-ganesha/nfs-ganesha#327]
### issue
Consider these entries in /etc/mtab:
```
/dev/mapper/fedora_localhost--live-root /etc/resolv.conf ext4 rw,seclabel,relatime 0 0
/dev/mapper/fedora_localhost--live-root /export ext4 rw,seclabel,relatime 0 0
```

/etc/resolv.conf and /export have the same FSID. Since /etc/resolv.conf occurs first in /etc/mtab, it is used to "represent" fsid=0x00000000000000fd.0x0000000000000001 and /export is skipped. In this particular use-case (the container runtime i.e. docker/containerd is creating this "/etc/resolv.conf" mount) I don't have control over the mount ordering, but the intention is to have /export be the directory from which to create NFS exports.
```
13/08/2018 21:07:12 : epoch 5b71f2fe : nfs-provisioner-0 : nfs-ganesha-22[main] posix_create_file_system :FSAL :INFO :Added filesystem /etc/resolv.conf namelen=255 dev=253.1 fsid=0x00000000000000fd.0x0000000000000001 253.1
13/08/2018 21:07:12 : epoch 5b71f2fe : nfs-provisioner-0 : nfs-ganesha-22[main] posix_get_fsid :FSAL :F_DBG :statfs of /export pathlen 0
13/08/2018 21:07:12 : epoch 5b71f2fe : nfs-provisioner-0 : nfs-ganesha-22[main] posix_create_file_system :FSAL :DEBUG :Skipped duplicate /export namelen=255 fsid=0x00000000000000fd.0x0000000000000001 253.1
```

But /etc/resolv.conf is a bind-mounted file, it is not a directory. So later we get errors when we try to export things from /export.
```
13/08/2018 21:07:12 : epoch 5b71f2fe : nfs-provisioner-0 : nfs-ganesha-22[main] vfs_get_root_handle :FSAL :MAJ :Could not open VFS mount point /etc/resolv.conf: rc = Not a directory (20)
13/08/2018 21:07:12 : epoch 5b71f2fe : nfs-provisioner-0 : nfs-ganesha-22[main] process_claim :FSAL :CRIT :FSAL VFS failed to claim file system /etc/resolv.conf error Not a directory
```
### proposed workaround
Check if the mountpoint in /etc/mtab is a directory and if not, skip it. https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/commonlib.c#L1284

### limitations
Even if we skip all mounted files, there is still a chance that multiple directories have the same fsid. (edit: and the order of /proc/mounts / /etc/mtab will determine which one is added and which skipped). In this case I don't think there's anything we can do. 

I am working on a patch now, but would appreciate any insight/feedback on whether what I have said makes any sense. Thanks.

**Comment by ffilz** [comment]
Yea, skipping things that aren't directories makes sense.

The Linux mount table sure is a confusing mess...

As to directories having the same fsid, I'm not sure what all can be done there. Ideally, UUIDs are being used and each file system has a unique UUID. If your environment doesn't have unique UUIDs, then it might be better to disable that and use device major/minor.

It may be that we need to have an option to specify file systems in the config file to be able to work around some of these issues. Make a best possible automatic attempt and if your setup doesn't work with the automated attempt, then you need to explicitly configure the file systems.

**Comment by Zagrebelsky** [comment]
I faced with same issue with FSAL_GPFS

**Comment by fbezdeka** [comment]
I guess I'm facing the same problem here.

OS: CentOS 8
ganesha-nfs: 2.7.6

I'm mounting a nfs share exported by nfs-ganesha, and "adding" some bind mounts to the nfs mount location.

Example: 
/home is mounted using nfs
/home/somefile.conf is a bind mount to somewhere else in the system.

After some time the bind mount seems to disappear.

From /var/log/ganesha-gfapi.log
```
[2019-12-21 08:21:43.742811] I [MSGID: 104043] [glfs-mgmt.c:661:glfs_mgmt_getspec_cbk] 0-gfapi: No change in volfile, continuing
[2019-12-21 08:50:11.110945] W [MSGID: 114031] [client-rpc-fops_v2.c:336:client4_0_stat_cbk] 0-mirror-client-2: remote operation failed [No such file or directory]
[2019-12-21 08:50:11.111662] W [MSGID: 114031] [client-rpc-fops_v2.c:2634:client4_0_lookup_cbk] 0-mirror-client-2: remote operation failed. Path: /home/somefile.conf (0683322f-ca9d-4210-bca6-0bbb203eb7fc) [No such file or directory]
[2019-12-21 08:50:11.111728] W [MSGID: 114031] [client-rpc-fops_v2.c:2634:client4_0_lookup_cbk] 0-mirror-client-0: remote operation failed. Path: /home/somefile.conf (0683322f-ca9d-4210-bca6-0bbb203eb7fc) [No such file or directory]
[2019-12-21 08:50:11.111763] W [MSGID: 114031] [client-rpc-fops_v2.c:2634:client4_0_lookup_cbk] 0-mirror-client-1: remote operation failed. Path: /home/somefile.conf (0683322f-ca9d-4210-bca6-0bbb203eb7fc) [No such file or directory]
```

Is there any workaround available?

**Comment by malahal** [comment]
I recall bind mounts not getting added to file systems. I don’t remember
any workarounds? Maybe we need a patch against Ganesha to fix this.

**Comment by Zagrebelsky** [comment]
I added script to remount filesystems if that not be mounted before ganesha. After that in  /etc/mtab I got right order of mounts

**Comment by ffilz** [comment]
This should be resolved by recent efforts on export reload that went into V4-dev.23. Please evaluate with the latest V4-dev build and if there are still issues, re-open the issue.
