### ISSUE TITLE
lru_bump_chunk using wrong DQ macro

### ISSUE THREAD

**Issue by michaelzeis** [nfs-ganesha/nfs-ganesha#328]
It appears that lru_bump_chunk is calling the wrong DQ macro (LRU_DQ_SAFE macro instead of CHUNK_LRU_DQ_SAFE) below:

void lru_bump_chunk(struct dir_chunk *chunk) 

    switch (lru->qid) {
    case LRU_ENTRY_L1:
        /* advance chunk to MRU (of L1) */
               LRU_DQ_SAFE(lru, q);

This is causing the code to use the qlane from LRU[] instead of CHUNK_LRU[].

I also see an issue further down in lru_remove_chunk() which is using CHUNK_LRU_DQ_SAFE, but is not setting the 'qid' to LRU_ENTRY_NONE after the dequeue, I think it should be doing this:

`if (lq) {
		/* dequeue the chunk */
		CHUNK_LRU_DQ_SAFE(&chunk->chunk_lru, lq);
                chunk->chunk_lru.qid = LRU_ENTRY_NONE;     /* <-- INSERT THIS HERE? */
}`

If you add an assert() to the DQ macros to verify q->size, you can find these problems fairly easily, for example:

`		glist_del(&(lru)->q); \
               assert((q)->size > 0); \   /* INSERT THIS HERE */
               --((q)->size); \
`

**Comment by mattbenjamin** [comment]
oi vey

**Comment by michaelzeis** [comment]
I believe I see another use of LRU_DQ_SAFE in chunk_lru_run_lane() as well.

**Comment by dang** [comment]
You're right, it is.  Fortunately, it's only affecting in-progress iterators, and not mixing the queues, but it still needs to be fixed.

**Comment by dang** [comment]
https://review.gerrithub.io/#/c/ffilz/nfs-ganesha/+/422581

**Comment by ffilz** [comment]
Closed as resolved.
