### ISSUE TITLE
lru_bump_chunk calling chunk_lru_queue_of without QLOCK first

### ISSUE THREAD

**Issue by michaelzeis** [nfs-ganesha/nfs-ganesha#329]
I see in lru_bump_chunk() that it is calling chunk_lru_queue_of without calling QLOCK first:

void lru_bump_chunk(struct dir_chunk *chunk)
{
	mdcache_lru_t *lru = &chunk->chunk_lru;
	struct lru_q_lane *qlane = &CHUNK_LRU[lru->lane];
	struct lru_q *q = chunk_lru_queue_of(chunk);

         QLOCK(qlane);

In the comment section of chunk_lru_queue_of() it says:

* @note The caller @a MUST hold the lane lock

I believe the lru_bump_chunk() code should look like this instead to get the QLOCK first:

void lru_bump_chunk(struct dir_chunk *chunk)
{
	mdcache_lru_t *lru = &chunk->chunk_lru;
	struct lru_q_lane *qlane = &CHUNK_LRU[lru->lane];
	struct lru_q *q;

         QLOCK(qlane);
	q = chunk_lru_queue_of(chunk);

**Comment by dang** [comment]
You're right.

https://review.gerrithub.io/#/c/ffilz/nfs-ganesha/+/423152

**Comment by ffilz** [comment]
Closed as resolved.
