### ISSUE TITLE
proxy 9p --> NFS via ganesha

### ISSUE THREAD

**Issue by zeigerpuppy** [nfs-ganesha/nfs-ganesha#331]
I have installed ganesha on Debian 9 and am trying to proxy a 9p filesystem.

It's a nested virtualisation setup (Xen inside a KVM machine) and I want to share my 9p mounts with Xen DomUs.

So the stack so far is
Layer 1: ZFS filesystem -- virtfs(9p) --> KVM Vm
Layer 2: mounted 9p filesystem on Debian (Xen) running nfs-ganesha
Layer 3: share mounted 9p filesystem to Xen DomU via NFS (ganesha)

I have ganesha running properly but it refuses to share the filesystem:

```
xen1 : ganesha.nfsd-3786[main] vfs_lookup_path :FSAL :CRIT :Could not get handle for path /mnt/websites, error Operation not supported
xen1 : ganesha.nfsd-3786[main] init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=88 Path=/mnt/websites FSAL_ERROR=(Operation not supported,95)
```

Looking through the docs, I think this is because I'm using the wrong FSAL (VFS), but I can't see a way of proxying a 9p filesystem as NFS.
Is this possible with ganesha?

Config file:

```
EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 88;
        # Exported path (mandatory)
        Path = "/mnt/websites";
        # Pseudo Path (required for NFS v4)
        Pseudo = "/mnt/websites";
        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RO;
        # Exporting FSAL
        FSAL {
                Name = VFS;
        }
}

```

**Comment by ffilz** [comment]
I'm guessing 9P doesn't provide open_by_handle and name_to_handle_at.

Is 9P exportable by the kernel NFS server? FSAL_VFS can only export filesystems that are exportable by the kernel server (it uses the same exportfs interface for handles, just via system call).

**Comment by zeigerpuppy** [comment]
Ah I see.  As you guess, 9P is not exportable from the kernel NFS server.
I'll have to try a different method.

**Comment by martinetd** [comment]
@phdeniel They want to export a 9p filesystem, not export it as 9p :)

I can confirm that 9p does not provide `open_by_handle`/`name_to_handle_at`, there is no way in the protocol for this to work unfortunately so this is not likely to happen.


@zeigerpuppy, if you're courageous enough, there used to be a "POSIX FSAL" in an ancient version of ganesha (up until around 1.5) -- at this point I think it'd be faster to reimplement it from scratch than to try to port the old FSAL but you could try something similar if you really want to export that filesystem. The principle is that ganesha would generate a handle the first time it encouters a file and proceed by storing that handle in a database; then when a request comes for a given handle it looks in the DB if the file is known and opens it by path.

This would work with 9p, but the performance won't be great so I'm not sure I would recommend it. It would probably be much more efficient to export the ZFS filesystem directly if you can.

**Comment by ffilz** [comment]
Closed as will not fix.
