### ISSUE TITLE
unknown protocol error

### ISSUE THREAD

**Issue by squarejester** [nfs-ganesha/nfs-ganesha#334]
ubuntu 16.04 luminous, repos for ceph and nfs-ganesha are from download.ceph.com, nfs-ganesha 2.6.2

looking in the logs of nfs-ganesha after it starts, it comes up with an error stating "unknown protocol" and showmount -a says RPC: Program not registered. NMAP does show NFS listening on 2049/tcp.

No matter what I do I can not get nfs-ganesha to export my cephfs mount. The cephfs is mounted and I can manually go into it no problem. 

I'm trying to use NFS 4. In another system using an older  version of nfs-ganesha 2.5.3 on opensuse it does not have this issue. 

I have tried setting the log level in nfs-ganesha to ALL = FULL_DEBUG and gone through pages and pages with no help from the logs. Can anyone shine a light maybe???

**Comment by dang** [comment]
Can you post your ganesha config and ganesha log?

**Comment by dang** [comment]
There's DBUS.  You can get all the exports from that.

**Comment by wkjun** [comment]
@ffilz you are right,
if use NFS v4,
```
NFS_CORE_PARAM
{
	Protocols = 4;
}
```
`rpcbind` and `rpcstatd` are not needed，because nfs v4  don't depend on rpcbind,
at server end:
when  `showmount -e`
the result is :
 `clnt_create: RPC: Program not registered`
this is normal.

**Comment by ffilz** [comment]
Closing due to age.

Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
