### ISSUE TITLE
ver 2.7 RC3  - cannot start due to "system may not have V6 intfs" issue

### ISSUE THREAD

**Issue by stef97** [nfs-ganesha/nfs-ganesha#337]
Hi,

I am trying to deploy ver 2.7-rc3 on a ceph osd node running centos 7.5 
I am unsuccessful 
Please note that IPV6 is disabled on the node 

here are some log excerpts

"..
nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
29/08/2018 16:14:58 : epoch 5b86fec2 : osd04.tor.medavail.net : ganesha.nfsd-10143[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
29/08/2018 16:14:58 : epoch 5b86fec2 : osd04.tor.medavail.net : ganesha.nfsd-10143[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
29/08/2018 16:14:58 : epoch 5b86fec2 : osd04.tor.medavail.net : ganesha.nfsd-10143[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
29/08/2018 16:14:58 : epoch 5b86fec2 : osd04.tor.medavail.net : ganesha.nfsd-10143[main] Allocate_sockets :DISP :WARN :System may not have V6 intfs configured error 97(Address family not supported by protocol)
29/08/2018 16:14:58 : epoch 5b86fec2 : osd04.tor.medavail.net : ganesha.nfsd-10143[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs ..'

**Comment by ffilz** [comment]
What is the full log, none of those messages indicate a fatal issue.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
