### ISSUE TITLE
git clone question

### ISSUE THREAD

**Issue by techie879** [nfs-ganesha/nfs-ganesha#338]
Hi, this might sound crazy , sorry if it does.  I am having a bit of a trouble cloning version 2.6.3.  I can't seem to find the URL to clone 2.6.3 .

Can someone please tell me what that URL might be? 

thanks.

**Comment by dang** [comment]
You can also clone any version of Ganesha and check out the V2.6.3 tag.

**Comment by ffilz** [comment]
Closed as resolved.
