### ISSUE TITLE
nfs-ganesha 2.6.0 coredump

### ISSUE THREAD

**Issue by shangzhong** [nfs-ganesha/nfs-ganesha#339]
4 nfs-ganesha servers，the cephfs is used as their backend storage(FSAL_CEPH is being used).
These servers are exporting the same cephfs sub directory.
The export directory is mounted with 4 different clients, and each client is connecting to different nfs-ganesha server respectively.

Using the vdbench tool to write 64KB size files(1 million files) to the mounted directory.
The vdbench is running on the 4 clients respectively, each vdbench instance will write 250 thousand files to the mounted directory on each client.

The nfs-ganesha server will be terminated by SIGSEGV. 
call stack:
Core was generated by /usr/bin/ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /share-fs/export/ganes.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000546955 in ?? ()
"/core.37041" is a core file.
Please specify an executable to debug.
(gdb) bt
#0  0x0000000000546955 in ?? ()
#1  0x00007f35ab5fd9c0 in ?? ()
#2  0x00007f35a0505400 in ?? ()
#3  0x000000000000002a in ?? ()
#4  0x00000000005437a9 in ?? ()
#5  0x00007f35c544d5a8 in ?? ()
#6  0x0000000000000000 in ?? ()
(gdb) file /usr/bin/ganesha.nfsd
Reading symbols from /usr/bin/ganesha.nfsd...Reading symbols from /usr/bin/ganesha.nfsd...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: debuginfo-install nfs-ganesha-2.6.0-0.1.el7.x86_64
(gdb) bt
#0  0x0000000000546955 in mdcache_clean_dirent_chunks ()
#1  0x00000000005469fc in mdcache_dirent_invalidate_all ()
#2  0x0000000000545a9b in mdc_clean_entry ()
#3  0x0000000000533423 in mdcache_lru_clean ()
#4  0x0000000000537f74 in _mdcache_lru_unref ()
#5  0x0000000000544442 in mdcache_put ()
#6  0x000000000054736b in mdcache_new_entry ()
#7  0x0000000000547bcd in mdcache_locate_host ()
#8  0x0000000000540ddd in mdcache_create_handle ()
#9  0x000000000047576b in nfs4_mds_putfh ()
#10 0x0000000000475954 in nfs4_op_putfh ()
#11 0x000000000045ea7e in nfs4_Compound ()
#12 0x000000000045b9db in nfs_rpc_process_request ()
#13 0x000000000045c122 in nfs_rpc_valid_NFS ()
#14 0x00007f365c425422 in ?? ()
#15 0x00007f358880e480 in ?? ()
#16 0x00007f35aa818800 in ?? ()
#17 0x00007f364a419400 in ?? ()
#18 0x00007f358880e480 in ?? ()
#19 0x00007f35ab5fb2a0 in ?? ()
#20 0x000000000044f144 in nfs_rpc_decode_request ()
Backtrace stopped: frame did not save the PC

nfs-ganesha log(last 20+ lines):
03/09/2018 10:19:57 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
03/09/2018 10:19:57 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 2
03/09/2018 10:19:57 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] mdcache_find_keyed :INODE :F_DBG :Looking for hk=43b6d7eb8d95d20f fsal=0x7f2abb1e0700 key=0x6521000000010000feffffffffffffff
03/09/2018 10:19:57 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] cih_get_by_key_latch :HT CACHE :DEBUG :fdcache MISS
03/09/2018 10:20:01 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
03/09/2018 10:20:12 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_46] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
03/09/2018 10:20:12 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_47] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
03/09/2018 10:20:27 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_44] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
03/09/2018 10:20:27 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 123, old: 122; deq new: 82, old: 82
03/09/2018 10:20:32 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_48] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 0
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] mdcache_find_keyed :INODE :F_DBG :Looking for hk=43b6d7eb8d95d20f fsal=0x7f2abb1e0700 key=0x6521000000010000feffffffffffffff
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] mdcache_find_keyed :INODE :F_DBG :Looking for hk=43b6d7eb8d95d20f fsal=0x7f2abb1e0700 key=0x6521000000010000feffffffffffffff
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] cih_get_by_key_latch :HT CACHE :DEBUG :fdcache MISS
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] cih_get_by_key_latch :HT CACHE :DEBUG :fdcache MISS
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] cih_get_by_key_latch :HT CACHE :DEBUG :fdcache MISS
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] mdcache_new_entry :INODE :DEBUG :Adding a DIRECTORY, entry=0x7f2aac05f400 setting MDCACHE_TRUST_CONTENT clearing MDCACHE_DIR_POPULATED
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] mdcache_new_entry :INODE :F_DBG :New entry 0x7f2aac05f400 added with fh_hk.key hk=43b6d7eb8d95d20f fsal=0x7f2abb1e0700 key=0x6521000000010000feffffffffffffff
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] mdcache_locate_host :INODE :F_DBG :create_handle Created entry 0x7f2aac05f400 FSAL Ceph
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] cih_get_by_key_latch :HT CACHE :DEBUG :cih AVL hit slot 0
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] mdcache_new_entry :INODE :DEBUG :lost race to add entry 0x7f2aac05f400 type: 7, New type: 7
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_45] mdcache_dirent_invalidate_all :INODE :F_DBG :Invalidating directory for 0x7f2a1ac50400, clearing MDCACHE_DIR_POPULATED setting MDCACHE_TRUST_CONTENT and MDCACHE_TRUST_DIR_CHUNKS
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=00000680 Valid Mask=0015ffce Supported Mask=0015dfce DIRECTORY numlinks=0x1 size=0x2ad0000 mode=0755 owner=0x0 group=0x0 atime=03/09/2018 09:27:54 mtime=03/09/2018 10:19:47
03/09/2018 10:20:36 : epoch 5b8c9a47 : host131 : ganesha.nfsd-382267[svc_5] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=0014c084 Valid Mask=0015ffce Supported Mask=0015dfce DIRECTORY numlinks=0x1 size=0x2ad0000 mode=0755 owner=0x0 group=0x0 atime=03/09/2018 09:27:54 mtime=03/09/2018 10:19:47

**Comment by shangzhong** [comment]
Thanks dang. We are validating with 2.6.3. The result will be sent later.

**Comment by shangzhong** [comment]
@dang , the V2.6.3 works well. Thanks!

**Comment by shangzhong** [comment]
@kevin-olbrich , you may build the 2.6.3 by yourself according to https://github.com/nfs-ganesha/nfs-ganesha/wiki/BuildingV2

**Comment by supriti** [comment]
There was announcement for 2.6.3 release and it has links to community releases.
https://lists.nfs-ganesha.org/archives/list/devel@lists.nfs-ganesha.org/thread/UGU75TJNZ66EKF5MVY54E4B2WTN2XFPG/

**Comment by dang** [comment]
It looks like the ceph team hasn't updated their packages to 2.6.3 yet.  I'll poke them.

**Comment by kevin-olbrich** [comment]
> @kevin-olbrich , you may build the 2.6.3 by yourself according to https://github.com/nfs-ganesha/nfs-ganesha/wiki/BuildingV2

How do I build the Ceph-FSAL?

**Comment by shangzhong** [comment]
cd ~/git/nfs-ganesha
mkdir build
cd build
#The libcephfs rpm should be installed before running cmake
cmake -DUSE_FSAL_CEPH=ON ~/git/nfs-ganesha/src 
make rpm

**Comment by kevin-olbrich** [comment]
It is very painful to build 3.6.3 on CentOS 7.5:

```
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
CMake Error at CMakeLists.txt:537 (message):
  Cannot find GSS libraries
-- Configuring incomplete, errors occurred!
```

```
[root@nfs-gw nfs-ganesha-2.6.3]# find / -name "gssapi.h"
/usr/include/heimdal/gssapi/gssapi.h
/usr/include/heimdal/gssapi.h
/usr/include/gssapi/gssapi.h
/usr/include/gssapi.h
```

There is the file which is "missing". I just commented out the check to continue.

```
[root@nfs-gw build]# make rpm
Run CPack packaging tool for source...
CPack: Create package using TGZ
CPack: Install projects
CPack: - Install directory: /usr/local/src/nfs-ganesha-2.6.3/src
CPack: Create package
CPack: - package: /usr/local/src/nfs-ganesha-2.6.3/build/nfs-ganesha-2.6.3.tar.gz generated.
Built target dist
error: line 133: Version required: Requires: libntirpc =
make[3]: *** [rpm] Error 1
make[2]: *** [CMakeFiles/rpm.dir/all] Error 2
make[1]: *** [CMakeFiles/rpm.dir/rule] Error 2
make: *** [rpm] Error 2
```

Lines:
```
%if %{with system_ntirpc}
BuildRequires: libntirpc-devel >= 1.6.1
%else
Requires: libntirpc =
%endif
```

The "Requires" is incomplete.
I changed the spec under "src" and ran cmake again but the spec files are built automatically.

For some reason "NTIRPC_VERSION_EMBED" is not populated in this case.

**Comment by shangzhong** [comment]
@kevin-olbrich I guess you are missing to git submodule in your  ~/git/nfs-ganesha : 
git submodule update --init

**Comment by kevin-olbrich** [comment]
> @kevin-olbrich I guess you are missing to git submodule in your ~/git/nfs-ganesha :
> git submodule update --init

You are right! I used the release-tar.gz. Using the git-branch it actually succeeded on the first try!

**Comment by shangzhong** [comment]
> CMake Error at CMakeLists.txt:537 (message):
  Cannot find GSS libraries
Don't comment out the check. Run yum install krb5-devel.

**Comment by kevin-olbrich** [comment]
> > CMake Error at CMakeLists.txt:537 (message):
> > Cannot find GSS libraries
> > Don't comment out the check. Run yum install krb5-devel.

Thats the point, this lib is installed. But this is resolved since I switched from the release archive to the git-branch.
