### ISSUE TITLE
Rewrite Pseudo filesystem as a fsal

### ISSUE THREAD

**Issue by lieb** [nfs-ganesha/nfs-ganesha#34]
Pseudo filesystem handling is a series of special case tests in V4 ops with calls to nfs4_pseudo.  Move all the pseudo fs logic to a fsal.  This eliminates all the special code scattered about in Protocols/NFS/nfs4_op_* by turning the pseudofs into the top level "export" with its own export id embedded in the handle.

Jeremy's work with pseudo fs persistent handles for 1.5 is merged into 2.0 via the fsal

**Comment by ffilz** [comment]
Done
