### ISSUE TITLE
V2.5-stable + windows client "NFS3 :CRIT :Likely bug: FSAL did not fill in a standard NFSv3 attribute: missing 1dfce"

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#342]
With windows client, when creating a folder the ganesha.log is filled with message "nfs3_FSALattr_To_Fattr :NFS3 :CRIT :Likely bug: FSAL did not fill in a standard NFSv3 attribute: missing 1dfce". The folder is created but unusable for sometime. What exactly does this error mean in this context? 

Also, I found this patch for 2.6 that suppress such prints: https://github.com/nfs-ganesha/nfs-ganesha/commit/b31316826cf7620e03fef850024fcec86c5d1db9 Is it related to this bug?

**Comment by ffilz** [comment]
Closed as resolved.
