### ISSUE TITLE
V2.5-stable + FSAL RGW: Stale file handle

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#344]
The config file has 

"Path = bucket;
Pseudo = /user/bucket;"

cd /mnt/nfs/user/bucket:
ls /mnt/nfs/user:
ls: cannot access 'user' Stale file handle

The log file is filled with 
```
"mdcache_locate_host :INODE :DEBUG :create_handle failed with The file no longer exists
30/08/2018 13:42:15 : epoch 5b875d33 : salt : ganesha.nfsd-13267[work-152] nfs4_mds_putfh :FH :DEBUG :could not get create_handle object error The file no longer exists
30/08/2018 13:42:15 : epoch 5b875d33 : salt : ganesha.nfsd-13267[work-152] nfs4_Compound :NFS4 :DEBUG :Status of OP_PUTFH in position 0 = NFS4ERR_STALE
30/08/2018 13:42:15 : epoch 5b875d33 : salt : ganesha.nfsd-13267[work-152] nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_STALE lastindex = 0""

```
From rgw code, the error happens when the filehandle is missing in lookup_handle. There is no other client accessing this file. Any pointers on what could be causing stale file error.

**Comment by mattbenjamin** [comment]
No, not for a file type handle,  unless possibly the object no longer exists?

**Comment by supriti** [comment]
It just happens randomly after sometime and there is no other client accessing this object. The pseudo path is "/user/bucket" and it seems like stale error happens only when ls is called at "/user" path and not at /user/bucket.

**Comment by mattbenjamin** [comment]
can you come up with a minimal setup and workload?  if you can, I'll debug it

**Comment by supriti** [comment]
I don't have a reproducer, but have logs and  [tcpdump](https://github.com/nfs-ganesha/nfs-ganesha/files/2405750/rgw-nfs.pcap.txt) when it happens. The buckets are still present.

From log, mdcache_locate_host() is called from mdcache_create_handle().  IIUC, mdcache_create_handle() is called only when the entry is not present in the mdcache. If that is the case what can result in removal of an entry from mdcache? In tcpdump as well, getattr is followed by putfh. 

I will try to disable cache, and enable rgw logging to see if anything else shows up.

**Comment by dang** [comment]
No, mdcache_create_handle() is called whenever a wire handle converted to a
real obj_handle.  So PUTFH will always call mdcache_create_handle().

**Comment by dang** [comment]
Looking at the log, everything is fine in Ganesha; rgw_lookup_handle()
returned an error, which FSAL_RGW converts into ESTALE.

**Comment by mattbenjamin** [comment]
If the fh really isn't in the cache, then rgw_lookup_handle() returns -ENOENT.  I'm trying to find the ganesha log @dang is referring to, but I can't see it to confirm if that is the error.

**Comment by mattbenjamin** [comment]
Contextually, I'd like to clarify "when" this happens.  E.g., when it happens, has the client accessed a mount whose RGW restarted, or, if not, can it happen right away--or only after a period of time.  If it's a side-effect of natural cache turnover, you might increase the CACHE_INODE Cache_size parameter, and maybe Entries_Hwmark if it is low.

**Comment by supriti** [comment]
@mattbenjamin I think dang is just referring to log snippet I attached in first comment.  I understood mdcache_create_handle() wrongly. It does not seem to be mdcache error, but the objects are missing from RGW. I am confused because I can see bucket when I use radosgw-admin bucket list.  I will check again with rgw logging enabled and see if we get any helpful log message from rgw_lookup_handle().

**Comment by mattbenjamin** [comment]
@supriti could you provide some more context as above, though, and experiment with cache settings?  In addition, I should have asked, what happens after the ESTALE?  Can the client not scan the mount/dir and re-establish state?

**Comment by supriti** [comment]
We enabled rgw side logs. The error in log file:
```
7f94c3fff700 -1 RGWWatcher::handle_error cookie 22111760 err (107) Transport endpoint is not connected
2 removed watcher, disabling cache
RGWWatcher::handle_error cookie 22084352 err (107) Transport endpoint is not connected
2 all 8 watchers are set, enabling cache
```
I don't understand  error "Transport endpoint not connected". But looking at log it seems like that triggers cache cleanup and maybe that results in stale file handle? 

But there is no error message from lookup_handle https://github.com/ceph/ceph/blob/master/src/rgw/rgw_file.h#L1024. The only other return type that  could result in ESTALE could be this condition: https://github.com/ceph/ceph/blob/master/src/rgw/rgw_file.h#L1024. But from rgw_lookup_handle we always pass the flag "RGW_LOOKUP_FLAG_NONE" (assuming we get that in state.flags)

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
