### ISSUE TITLE
Error compiling next on arm7l

### ISSUE THREAD

**Issue by ennwise** [nfs-ganesha/nfs-ganesha#345]
Getting the following error after a make on raspbian:

Scanning dependencies of target sal
[ 20%] Building C object SAL/CMakeFiles/sal.dir/state_async.c.o
[ 20%] Building C object SAL/CMakeFiles/sal.dir/state_lock.c.o
[ 20%] Building C object SAL/CMakeFiles/sal.dir/state_share.c.o
[ 21%] Building C object SAL/CMakeFiles/sal.dir/state_misc.c.o
[ 21%] Building C object SAL/CMakeFiles/sal.dir/state_layout.c.o
[ 21%] Building C object SAL/CMakeFiles/sal.dir/state_deleg.c.o
[ 21%] Building C object SAL/CMakeFiles/sal.dir/nfs4_clientid.c.o
[ 22%] Building C object SAL/CMakeFiles/sal.dir/nfs4_state.c.o
[ 22%] Building C object SAL/CMakeFiles/sal.dir/nfs4_state_id.c.o
[ 22%] Building C object SAL/CMakeFiles/sal.dir/nfs4_lease.c.o
[ 22%] Building C object SAL/CMakeFiles/sal.dir/nfs4_recovery.c.o
In file included from /root/nfs-ganesha/src/SAL/nfs4_recovery.c:33:0:
/root/nfs-ganesha/src/SAL/nfs4_recovery.c: In function ‘nfs4_chk_clid_impl’:
/root/nfs-ganesha/src/SAL/nfs4_recovery.c:433:31: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 7 has type ‘clientid4 {aka long long unsigned int}’ [-Werror=format=]
  LogDebug(COMPONENT_CLIENTID, "chk for %lu",
                               ^
/root/nfs-ganesha/src/include/log.h:300:19: note: in definition of macro ‘LogDebug’
        NIV_DEBUG, format, ## args); \
                   ^~~~~~
cc1: all warnings being treated as errors
SAL/CMakeFiles/sal.dir/build.make:302: recipe for target 'SAL/CMakeFiles/sal.dir/nfs4_recovery.c.o' failed
make[2]: *** [SAL/CMakeFiles/sal.dir/nfs4_recovery.c.o] Error 1
CMakeFiles/Makefile2:866: recipe for target 'SAL/CMakeFiles/sal.dir/all' failed
make[1]: *** [SAL/CMakeFiles/sal.dir/all] Error 2
Makefile:149: recipe for target 'all' failed

**Comment by dang** [comment]
This would be a 32/64 bit error.  It should probably be PRIu64 rather than lu.  Can you submit a patch?  (and for any other similar errors that hit)?

**Comment by ennwise** [comment]
See the attached patch.

[arm7l-format-specifiers.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/2398914/arm7l-format-specifiers.zip)

**Comment by dang** [comment]
Can you submit this on gerrithub?  See src/CONTRIBUTING_HOWTO.txt

**Comment by ffilz** [comment]
This fix was never submitted, I'm surprised it hasn't been caught by any of the build testing.

**Comment by ennwise** [comment]
:) I don't think anyone's running this on arm7 besides myself from extensive talks to people doing similar stuff. The patch works if you need it.

**Comment by ffilz** [comment]
We have done 32 bit compiling in the past which should catch things like this. Could you submit the patch via gerrithub? We would be happy to take it.

**Comment by philproctor** [comment]
I believe this is the same as #371 as my patches in my repo for building on multiple targets here fix both: https://github.com/homelab-library/glusterfs/tree/a7ff29945e9b231770adfb86dcaf9f993f7b5f8d/patches

Those patches are for that build, let me know if you want me to fork and submit a PR

**Comment by ffilz** [comment]
We need an upstream patch first: https://github.com/nfs-ganesha/nfs-ganesha/wiki/DevPolicy#Patch_Submission_Guidelines

And then we can backport.

**Comment by ffilz** [comment]
patch submitted, closing.
