### ISSUE TITLE
nfs-ganesha stop service after copy file from local to nfs mountpoint

### ISSUE THREAD

**Issue by hoanhdo** [nfs-ganesha/nfs-ganesha#348]
Hi all.

Currently, i install a rados gateway and export it to nfs-ganesha. (my ceph version : mimic)

I install nfs-ganesha 2.6.2-0-gb9685b8-1xenial on ubuntu 16.04.

My config nfs-ganesha;

```
EXPORT
{
        Export_ID=101;

        Path = "/";

        Pseudo = "/";

        Access_Type = RW;

        Protocols = 4;

        Transports = TCP;

        Squash = No_Root_Squash;

        FSAL {
                Name = RGW;
                User_Id = "hoannv";
                Access_Key_Id ="N7UVVC2W19KFAWYU794P";
                Secret_Access_Key = "f91STPGO0Lf2YsODdNIpdyHgDihpN6wD0hCHDHlV";
        }
}

RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        name = "client.admin";
        cluster = "ceph";
        init_args = "--keyring=/etc/ceph/ceph.client.admin.keyring";
}

```
Nfs client server  i run command.
 mount -t nfs4 10.5.9.61:/ /mnt/test

I copy any one file from local to /mnt/test, nfs-ganesha will be stop.

Thanks.

**Comment by dang** [comment]
Do you mean it crashes?  Can you get a backtrace for the crash?

**Comment by hoanhdo** [comment]
Yes. It crashes.

My config log


```
LOG {
       Components {
               MEMLEAKS = FATAL;
               FSAL = FATAL;
               NFSPROTO = FATAL;
               NFS_V4 = FATAL;
               EXPORT = FATAL;
               FILEHANDLE = FATAL;
               DISPATCH = FATAL;
               CACHE_INODE = FATAL;
               CACHE_INODE_LRU = FATAL;
               HASHTABLE = FATAL;
               HASHTABLE_CACHE = FATAL;
               DUPREQ = FATAL;
               INIT = DEBUG;
               MAIN = DEBUG;
               IDMAPPER = FATAL;
               NFS_READDIR = FATAL;
               NFS_V4_LOCK = FATAL;
               CONFIG = FATAL;
               CLIENTID = FATAL;
               SESSIONS = FATAL;
               PNFS = FATAL;
               RW_LOCK = FATAL;
               NLM = FATAL;
               RPC = FATAL;
               NFS_CB = FATAL;
               THREAD = FATAL;
               NFS_V4_ACL = FATAL;
               STATE = FATAL;
               FSAL_UP = FATAL;
               DBUS = FATAL;
       }
       # optional: redirect log output
       Facility {
              name = FILE;
              destination = "/tmp/ganesha-rgw.log";
              enable = active;
       }
}
```
No log when nfs-ganesha crashesd. 
My config log is correct ?.

**Comment by hoanhdo** [comment]
I enable all log config to DEBUG level and this is my log.
[ganesha_crash_log.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/2404029/ganesha_crash_log.txt)

**Comment by dang** [comment]
Can you get a backtrace?  You can take a look at https://wiki.ubuntu.com/Backtrace for information on backtraces on Ubuntu.

**Comment by hoanhdo** [comment]
Yes i can.

My backtrace log

[gdb-6512.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/2405797/gdb-6512.txt)

**Comment by dang** [comment]
It looks like it crashed on a mutex in libceph-common.  Can you do this one more time, but instead of typing "continue" when it says "received signal SIGSEGV", can you type "backtrace" instead, and post that output?

**Comment by hoanhdo** [comment]
Yes. it is output.
[gdb-22720.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/2405905/gdb-22720.txt)

**Comment by dang** [comment]
Okay, so this crash is entirely in Ceph code.  It's in a thread started by librgw and containing only RGW code.  @mattbenjamin any ideas?

**Comment by hoanhdo** [comment]
my cluster has 2 zone, zone-1 and zone-2.

I config zone-2 and elastic search use this guide

https://ceph.com/rgw/new-luminous-rgw-metadata-search/

If i remove zone-2, it works.

Hope this help.

**Comment by taoCH** [comment]
I guess your RGW and librgw share the same ceph auth entry : client.admin

Try to create a new ceph auth entry with:

```
ceph auth add client.librgw --in-file=/etc/ceph/ceph.client.librgw.keyring
```

Then, you could modify your ganesha.conf to ：

```
EXPORT
{
        Export_ID=101;

        Path = "/";

        Pseudo = "/";

        Access_Type = RW;

        Protocols = 4;

        Transports = TCP;

        Squash = No_Root_Squash;

        FSAL {
                Name = RGW;
                User_Id = "hoannv";
                Access_Key_Id ="N7UVVC2W19KFAWYU794P";
                Secret_Access_Key = "f91STPGO0Lf2YsODdNIpdyHgDihpN6wD0hCHDHlV";
        }
}

RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        name = "client.librgw";
        cluster = "ceph";
        init_args = "--keyring=/etc/ceph/ceph.client.librgw.keyring";
}
```
Hope it helps

**Comment by taoCH** [comment]
As you configure multisite(elasticsearch), the RGW will sync your object's metadata to elasticsearch, on the other hand your are writing data with librgw. These two entries should be seprated.

**Comment by cbodley** [comment]
hi @mattbenjamin, it looks like there were changes to initialization in rgw_main/admin.cc that weren't also applied to `RGWLib::init()` in librgw.cc. in particular, it's missing the calls to `rgw_http_client_init()` and `rgw::curl::setup_curl()` that allocate the `RGWHTTPManager` and `RGWCurlHandles` classes that are present in this stack trace

**Comment by hoanhdo** [comment]
I found a isssue in ceph.

http://tracker.ceph.com/issues/36233

I think it has same problem.

**Comment by cbodley** [comment]
i've opened a ceph tracker issue at http://tracker.ceph.com/issues/36302 and proposed a fix at https://github.com/ceph/ceph/pull/24402

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
