### ISSUE TITLE
VFS fsal needs a notify mechanism for exported filesystem changes

### ISSUE THREAD

**Issue by lieb** [nfs-ganesha/nfs-ganesha#35]
Ganesha needs to be notified if the underlying filesystem is changed by other services or local users.  For example, if the system administrator creates or moves a directory within an export, ganasha will not see it until the cache entry for that directory is refreshed.  Currently, that will only happen if the entry is LRU'd due to inactivity.  If it is an active directory, it may stay cached (stale) for a long time.

This task is to use kernel services (either fanotify or inotify) to watch cached directories and mark the entry as changed.

**Comment by ffilz** [comment]
This is unlikely to be addressed anytime soon.
