### ISSUE TITLE
nfstest optest01 test 72 failing with NFS4ERR_INVAL

### ISSUE THREAD

**Issue by jtlayton** [nfs-ganesha/nfs-ganesha#350]
optest01 test 72 is failing when nfstests are run as a batch. Run individually, it seems to pass:

```
    INFO: 13:37:25.319895 - Running optest01 test 72                            
    PASS: Locking byte range should be granted, lock1(O_RDWR, F_WRLCK, F_SETLKW)
    PASS: locking with overlapping range on second process should block, lock2(O_RDWR, F_WRLCK, F_SETLKW)
    PASS: Unlocking full file after delay should be granted, lock2(O_RDWR, F_WRLCK, F_SETLKW)
    PASS: Blocked lock is granted after conflicting lock is released, lock2(O_RDWR, F_WRLCK, F_SETLKW)
    PASS: Unlocking full file on second process should be granted, lock2(O_RDWR, F_WRLCK, F_SETLKW)
    DBG2: 13:37:25.745229 - Trace stop                                          
    DBG2: 13:37:25.745368 - /usr/bin/sudo killall tcpdump                       
    DBG2: 13:37:25.765197 - /usr/bin/sudo kill 4531                             
    DBG1: 13:37:25.799205 - trace_open [/home/aglo/logs/fall-bat/ganesha-cephfs/nfstest_lock_20180920133555_14.cap]
    FAIL: NFS   v4.1 reply xid:0x58569160 SEQUENCE;PUTFH;LOCK       NFS4ERR_INVAL
    FAIL: NFS   v4.1 reply xid:0x57569160 SEQUENCE;FREE_STATEID     NFS4ERR_BAD_STATEID
    TIME: 9.754967s                                                             
```
The log has this in it:

`2018-09-20 17:55:35.423268 I | 20/09/2018 17:55:35 : epoch 5ba3a871 : rook-ceph-ganesha-my-nfs-a-5659554f68-66756 : nfs-ganesha-16[svc_68] fsal_find_fd :FSAL :CRIT :Conflicting open, can not re-open fd with locks`

In the pcap file, it shows that the client does a LOCK/LOCKU/FREE_STATEID on a file. Before the reply to FREE_STATEID comes back however, it sends a new LOCK request for the file with "new lock owner" set to true, but with  the same lockowner as the previous LOCK request.

I suspect that the server ends up processing the new LOCK request before the FREE_STATEID, and finds the old stateid. We then end up calling into fsal_find_fd and hit this condition:

```
       if (open_for_locks) {                                                   
                if (state_fd->openflags != FSAL_O_CLOSED) {                     
                        LogCrit(COMPONENT_FSAL,                                 
                                "Conflicting open, can not re-open fd with locks");
                        return fsalstat(posix2fsal_error(EINVAL), EINVAL);      
                }                                                               
```

...the openflags are not FSAL_O_CLOSED however, because we're reusing the same stateid we had before, and it still as an open file associated with it.

I think there are two potential fixes:

1) the FSAL_O_CLOSED check might just be bogus. Just because we got a LOCK with "new lock owner" set to true, it doesn't mean that we don't already have an existing stateid for this lockowner. The client could just be forgetful (or we could be racing with FREE_STATEID like in the capture).

...or...

2) we could just create a new stateid when we see "new lock owner" set to true. I'm not too keen on this however, as you could end up having to track a large number of LOCK stateids for the same fh+lockowner tuple if the client is behaving badly.

**Comment by jtlayton** [comment]
The sequence in the capture is:

OPEN - OPEN4_SHARE_ACCESS_WRITE
LOCK
OPEN - OPEN4_SHARE_ACCESS_READ
LOCKU
FREE_STATEID
LOCK (fails with NFS4ERR_INVAL)

**Comment by ffilz** [comment]
That 2nd open is what is causing the problem. The first lock was probably exclusive, the 2nd shared. The open_for_locks code uses the open stateid open mode for V4 otherwise it uses RDWR. I think we just need to always open lock stateid fd RDWR

**Comment by ffilz** [comment]
Ok, came up with a pynfs test case to test this (it leaves out the FREE_STATEID and is done with NFS v4.0, but otherwise the same scenario). Of course I got the write/read backwards, but same difference. It results in the EINVAL without my Ganesha fix.

Here is the test case: https://github.com/ffilz/pynfs/commit/1c44a2ef07510aaa71b8c8cfb4fabc9b8dd466d0

And here's the patch:

https://review.gerrithub.io/426288

**Comment by jtlayton** [comment]
Fixed.
