### ISSUE TITLE
service not starting

### ISSUE THREAD

**Issue by billikill** [nfs-ganesha/nfs-ganesha#352]
Hi.
I am install nfs-ganesha, but service not starting. Selinux - disabled.
In node 1 and 2 service running.
help me, plz.
Log ganesha https://pastebin.com/rLtSTasw

**Comment by kalebskeithley** [comment]
which version? On which Linux distro? How did you install, by building from source or installing packages? Where did you get the packages? Which FSAL are you using? Post or paste your /etc/ganesha/ganesha.conf file.

**Comment by dang** [comment]
Also paste your /var/log/ganesha/ganesha.log file

**Comment by billikill** [comment]
Hi.
Problem is resolved
