### ISSUE TITLE
libcephfs / librados namespace support for nfs-ganesha

### ISSUE THREAD

**Issue by hydro-b** [nfs-ganesha/nfs-ganesha#353]
libcephfs / librados supports "namespaces". Note: namespaces in this context are not "multiple filesystems" but rather an "object prefix" to separate different objects in cephfs / rados. One of the benefits of "namespaces" is that you can have multiple instances of ganesha using the same pool / filesystem without objects clashing. Currently you would need a separate pool for "RADOS_KV" and "RADOS_URLS" per ganesha instance. With namespace support (in libcephfs) you would be able to logically seperate the objects per namespace (ganesha instance) ... and restrict access to _only_ this namespace instead of the whole pool:

caps: [mds] allow rw path=/path/on/cephfs
        caps: [mon] allow r
        caps: [osd] allow rw pool=cephfs_data namespace=your-name-space-here

As a (Ceph) storage admin you would be able to provide tenants the (cephx) capabilities to use nfs-ganesha, without the need to give them rw access to your cephfs_data pool(s).

**Comment by mattbenjamin** [comment]
@hydro-b this seems interesting;  do you think you could send an email on this topic to the ceph-devel mailing list?

**Comment by jtlayton** [comment]
The namespace parameter works for all the RADOS recovery backends (rados_kv, rados_ng and rados_cluster). It hasn't been added to the RADOS_URLS config block, but that wouldn't be too hard to do.

**Comment by ffilz** [comment]
Is this one resolved?

**Comment by jtlayton** [comment]
Yes, it can be closed.
