### ISSUE TITLE
Segmentation Faults w/ GlusterFS

### ISSUE THREAD

**Issue by honeybadger91** [nfs-ganesha/nfs-ganesha#356]
I have a pretty basic install of GlusterFS (latest version) and Ganesha (latest version) with two volumes running as a replica. Here are the configs.

Volume Name: gv0
Type: Replicate
Volume ID: 72e8a75d-0784-4c4b-8ae6-ff6942ca9c08
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 2 = 2
Transport-type: tcp
Bricks:
Brick1: 10.0.0.18:/data/brick1/gv0
Brick2: 10.0.0.20:/data/brick1/gv0
Options Reconfigured:
transport.address-family: inet
nfs.disable: on
performance.client-io-threads: off

`
EXPORT{
    Export_Id = 1 ;   # Export ID unique to each export
    Path = "/data/brick1/gv0";  # Path of the volume to be exported. Eg: "/test_volume"

    FSAL {
        name = GLUSTER;
        hostname = "10.0.0.18";  # IP of one of the nodes in the trusted pool
        volume = "gv0";  # Volume name. Eg: "test_volume"
    }

    Access_type = RW;    # Access permissions
    Squash = No_root_squash; # To enable/disable root squashing
    Disable_ACL = TRUE;  # To enable/disable ACL
    Pseudo = "/nfs";  # NFSv4 pseudo path for this export. Eg: "/test_volume_pseudo"
    Protocols = "3","4" ;    # NFS protocols supported
    Transports = "UDP","TCP" ; # Transport protocols supported
    SecType = "sys";     # Security flavors supported
}
`
I have logs running in debug mode, but I don't know really see anything of value. Last thing before the failure was:

6/10/2018 00:12:26 : epoch 5bb7fd8f : glusterfs-03 : ganesha.nfsd-15558[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now NOT IN GRACE

It seems to happen when I try to install an application or something in that regard. Any idea how I can solve this?

dmesg log:

[ 2342.638831] glfs_epoll000[15570]: segfault at 8 ip 00007f482c8a993c sp 00007f482e359c60 error 4 in read-ahead.so[7f482c8a8000+e000]

**Comment by soumyakoduri** [comment]
With Gluster and Ganesha current latest version, there is a symbol collision leading to crashes. You would need either of these patches  - 
https://review.gerrithub.io/427287
https://review.gluster.org/21313

Both the patches are merged now. Please update your sources (gluster and ganesha).

**Comment by honeybadger91** [comment]
> With Gluster and Ganesha current latest version, there is a symbol collision leading to crashes. You would need either of these patches -
> https://review.gerrithub.io/427287
> https://review.gluster.org/21313
> 
> Both the patches are merged now. Please update your sources (gluster and ganesha).

I've done so, but still seeing the same issues. I cloned down the latest stuff from both repositories.

**Comment by kalebskeithley** [comment]
@skoduri: the symbol collision with dht's 'options' is/was only on the master branch. It's not in any released version of gluster.

@honeybadger91: the Path in your Export block seems unusual to me. That looks like a path to the gluster brick. I'd change it to something else just to be less confusing. I'd use "/gv0", then clients do `mount $ganesha_host:/gv0 /mnt`

**Comment by honeybadger91** [comment]
@kalebskeithley thanks so much for this. I used "/gv0" and this seems to have solved the issue. Would you be able to explain to me why this is the case though? My volume was create at /data/brick1/gv0, so I'm confused as to how it works by referencing just "/gv0".

**Comment by kalebskeithley** [comment]
It comes down to the Path you specify in the Export block of the /etc/ganesha/ganesha.conf file, which is directly related to the 'path' that clients use to mount. A '/' in the Path is illegal AFAIK.
Ganesha is agnostic about gluster brick paths. It only knows the gluster volume name from the FSAL section.

**Comment by ffilz** [comment]
Closed as resolved.
