### ISSUE TITLE
File lock got fcntl error:: Permission denied on CentOS7 with NFSv3

### ISSUE THREAD

**Issue by wugang33** [nfs-ganesha/nfs-ganesha#357]
Hi all 

I am work on this problem serval days . Some time lock can work will, but most of the time ,it return Permission Denied  error .
I see the ganesha's log, but got nothing. The error was reported by the kernel thread.
I use the nfsd replace the ganesha. The error disappear. 
So I want get some help from here.

[root@node1 auth.unix.ip]# ganesha.nfsd -version
NFS-Ganesha Release = V2.6.2
nfs-ganesha compiled on Sep 30 2018 at 03:28:05
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = bb3b3926e782a35654582ef945605a76c5e111bf
Git Describe = 

cmake script
 cmake -DUSE_GSS=OFF -DUSE_TOOL_MULTILOCK=ON -DUSE_FSAL_CEPH=ON -DUSE_FSAL_GPFS=OFF -DUSE_FSAL_GLUSTER=OFF -DUSE_9P=OFF -DUSE_RADOS_RECOV=OFF ../src/ 

vfs.conf
NFS_CORE_PARAM
{
        Enable_NLM = true;
}

EXPORT
{
        Export_Id = 77;
        Path = /test;
        Pseudo = /test;
        Transports = TCP;
        Protocols = 3;
        Access_Type = RW;
        Squash = No_Root_Squash;
        FSAL {
                Name = VFS;
        }
}

start script 
ganesha.nfsd -f /etc/ganesha/vfs.conf -L /var/log/ganasha.log -F

mount script 
mount -t nfs -o rw,noatime,vers=3 localhost:/test  /mnt

cat lock.c
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include <stdlib.h>

int fd = -1;
int sleepsec = 10;
const char*filename;
struct flock _lock;
int ret;

void unlock(){
   if(fd<=0)return;
   puts( "unlock..." );
  _lock.l_type =  F_UNLCK;
  _lock.l_whence = SEEK_SET;
  _lock.l_start = 0;
  _lock.l_len = 0;

  ret = fcntl( fd,F_SETLK,&_lock );
  if ( ret < 0 ){
      perror( "unlock error:" );
    }
  close( fd );
}
void ctrlc_message(int s){
        if(fd>0)unlock();
}

int main(int argc,char**argv){
  if(argc<3){
    printf("usage: %s filename sleeptime[int]\n",argv[0]);
    return -1;
  }
  filename = argv[1];
  _lock.l_type =  F_WRLCK;
  _lock.l_whence = SEEK_SET;
  _lock.l_start = 0;
  _lock.l_len = 0;
  sleepsec = atoi(argv[2]);
  printf("filename:%s sleep:%d\n",filename,sleepsec);
  fd = open( filename,O_CREAT|O_RDWR,S_IRWXU|S_IRGRP|S_IWGRP|S_IRWXO );
  if ( fd < 0 ){
    printf( "open file:%s failure due to error:%s",filename,strerror(errno));
    return 0;
  }

  ret = fcntl( fd,F_SETLK,&_lock );
  if ( ret < 0 )  {
      perror( "fcntl error:" );
      close( fd );
      return 0;
    }
    struct sigaction sigIntHandler;
        sigIntHandler.sa_handler = ctrlc_message;
        sigemptyset(&sigIntHandler.sa_mask);
        sigIntHandler.sa_flags = 0;
        sigaction(SIGINT,&sigIntHandler,NULL);
        puts( "sleep now ..." );
        sleep( sleepsec )
}

touch on the kernel debug log
sunrpc.nfs_debug = 65535
sunrpc.nlm_debug = 65535
sunrpc.rpc_debug = 65535

Can see something like this
Oct  6 18:05:19 node1 kernel: svc: transport ffff8a1fa5e88000 put into queue
Oct  6 18:05:19 node1 kernel: RPC:       xs_tcp_send_request(184) = 0
Oct  6 18:05:19 node1 kernel: lockd: request from 127.0.0.1, port=724
Oct  6 18:05:19 node1 kernel: RPC:   167 xmit complete
Oct  6 18:05:19 node1 kernel: svc: svc_authenticate (1)
Oct  6 18:05:19 node1 kernel: RPC:       Want update, refage=120, age=0
Oct  6 18:05:19 node1 kernel: svc: authentication failed (1)

[root@node1 auth.unix.ip]# cat /proc/net/rpc/auth.unix.ip/content
#class IP domain
\# expiry=1538824126 refcnt=1 flags=3
\# nfsd 127.0.0.1 -no-domain-

**Comment by wugang33** [comment]
I found this problem is caused When I start the ganesha service and mount at same machine. When I mount the filesystem, It replace the lockmgr port Which is registed by Ganesha in Portmap, So the request send to the lockd kernel thread.

**Comment by ffilz** [comment]
Yes, a host running Ganesha can not also run the kernel NLM client. Unfortunately NLM requires BOTH the client AND server to register the NLM program. There is no way for both a kernel client and a user space server to register the NLM program.

(I do have ideas for how if Ganesha incorporated RPC Bind it COULD see the kernel client registration and forward the client bound NLM requests to the kernel client while keeping the server bound requests for itself). But that has limited real world use...
