### ISSUE TITLE
Delegations are not granted in the first open call for nfsv4

### ISSUE THREAD

**Issue by thotz** [nfs-ganesha/nfs-ganesha#359]
Following check in should_we_grant_deleg() always true for first open call
---
|| (!owner->so_owner.so_nfs4_owner.so_confirmed
             && claim == CLAIM_NULL)

resok->delegation.open_delegation4_u.od_whynone.ond_why =
                                                        WND4_NOT_SUPP_FTYPE;
                return false;

---
And delegations won't granted. from the code readding it looks like open4_open_owner sets owner->so_owner.so_nfs4_owner.so_confirmed is set to true for nfsv4 clients and claim = CLAIM_NULL for the first open call. Hence delegations won't granted.

**Comment by soumyakoduri** [comment]
As per rfc7530 ,


   Servers MUST NOT require confirmation on OPENs that grant delegations
   or are doing reclaim operations.  See Section 9.1.11 for details.
   The server can easily avoid this by noting whether it has disposed of
   one open_owner4 for the given client ID.  If the server does not
   support delegation, it might simply maintain a single bit that notes
   whether any open_owner4 (for any client) has been disposed of.
<<<

So I think we need to relax that particular check and allow delegations even if nfs4_owner is not yet confirmed.

**Comment by soumyakoduri** [comment]
hmm..rfc also states 
When the server observes the use of the
   open-owner for the first time, it will direct the client to perform
   the OPEN_CONFIRM for the corresponding OPEN.
.....
....

Fortunately, these are
   situations in which the server can avoid the need for confirmation
   when responding to open requests.  The two constraints are:

   o  The server must not bestow a delegation for any open that would
      require confirmation.
<<<<
 
For the first time OPEN, open-owner used will be new and would require confirmation and thus delegations cant be granted. Wonder how kNFS handles this situation.

**Comment by soumyakoduri** [comment]
So rfc7530 states below at two different sections -

Section-9.1.11:
" When the server observes the use of the open-owner for the first time, it will direct the client to perform
the OPEN_CONFIRM for the corresponding OPEN.......The server must not bestow a delegation for any open that would require confirmation."

and 
Section 16.18.5:
"Servers MUST NOT require confirmation on OPENs that grant delegations or are doing reclaim operations. "

@jtlayton  @ffilz .. please provide your comments on what should be the right behavior. Currently ganesha server doesn't grant delegations if open_owner is not confirmed (i.e, first OPEN call) and it results in pynfs delegation tests failure.

**Comment by jtlayton** [comment]
I think ganesha's behavior is correct and matches that of knfsd. FWIW, knfsd has this on CLAIM_NULL and CLAIM_FH opens:

                        if (!cb_up || !(oo->oo_flags & NFS4_OO_CONFIRMED))
                                goto out_no_deleg;

If pynfs is expecting an unconfirmed openowner to get a delegation, then that test is probably wrong.

**Comment by soumyakoduri** [comment]
okay..thanks Jeff for confirming. Will look into that testcase in detail and update.

**Comment by jtlayton** [comment]
No problem. Note that a client is never entitled to a delegation (except during certain reclaim scenarios). The server can choose not to hand one out for any reason whatsoever.

**Comment by thotz** [comment]
Thanks Soumya and Jeff for clearing the information, this is expected behaviour wrt delegations. Hence closing this issue
