### ISSUE TITLE
display_export fails - too many values to unpack

### ISSUE THREAD

**Issue by wyllys66** [nfs-ganesha/nfs-ganesha#365]
in Ganesha 2.7.1, the following command fails:
```
$ ganesha_mgr display_export 1001
Display export with id 1001
Traceback (most recent call last):
  File "/usr/bin/ganesha_mgr", line 303, in <module>
    exportmgr.displayexport(sys.argv[2])
  File "/usr/bin/ganesha_mgr", line 114, in displayexport
    status, msg, reply = self.exportmgr.DisplayExport(exp_id)
  File "/usr/lib/python2.7/dist-packages/Ganesha/ganesha_mgr_utils.py", line 184, in DisplayExport
    id, fullpath, pseudopath, tag = display_export_method(int(exp_id))
ValueError: too many values to unpack
```

This is because the dbus command in 2.7.1 is now returning many more fields than it was in 2.6 but the python module is only expecting 4.

For example, on a 2.7.1 server, the DisplayExport DBUS call returns the following:
```
(dbus.UInt16(1001), dbus.String(u'/exports/NFStest'), dbus.String(u'/exports/NFStest'), dbus.String(u'NFStest'), dbus.Array([dbus.Struct((dbus.String(u'*'), dbus.Int32(0), dbus.Byte(0), dbus.Byte(0), dbus.Int32(0), dbus.UInt32(4294967294L), dbus.UInt32(4294967294L), dbus.UInt32(0L), dbus.UInt32(53490144L), dbus.UInt32(487L)), signature=None)], signature=dbus.Signature('(siyyiuuuuu)')))
```

but on a 2.6.X system it returned only:
```
(dbus.UInt16(1001), dbus.String(u'/exports/NFStest'), dbus.String(u'/exports/NFStest'), dbus.String(u'NFStest'))
```

The python module ganesha_mgr_utils.py needs to expect more data from the display_export_method function in 2.7.X and later.

**Comment by srirampatil** [comment]
Fixes in review -> https://review.gerrithub.io/#/c/ffilz/nfs-ganesha/+/434843/

**Comment by wyllys66** [comment]
This is still an issue in 2.7.2, can this be finallized and closed ?

**Comment by srirampatil** [comment]
Unfortunately this change is not back ported to V2.7-stable branch. However, the patch only changes the python files in admin tools. You can apply the patch separately for the admin tools and use those scripts.

Here's the commit -> c9311bfbcf711e9e42024d212cb1a134f89c56d5

**Comment by ffilz** [comment]
This appears to have a resolution and V2.7 is not longer supported.
