### ISSUE TITLE
active active cephfs

### ISSUE THREAD

**Issue by stef97** [nfs-ganesha/nfs-ganesha#367]
Hi,

I 've read some comments mentioning that cephfs active/active configuration is possible using 2.7
Is it true ? If yes , are there any instructions  ?

If it is not true, can we use active/passive with rados backend ( i.e no need for pacemaker/ cluster software) If yes, are there any instructions ?

I just downloaded and installed 2.8 

Also mayne someone can point me to a document depicting  implementing recovery backend ( NG,  KV, CLUSTER ).
 Which one should,be used and what are the differences

Many thanks

**Comment by dang** [comment]
HA, whether active-active or active-passive, always needs a manager to control it.  This can be pacemaker/corosync, ctdb, or kubernetes, but Ganesha cannot do it alone.  

Pacemaker/corosync and ctdb work similarly, by creating virtual IPs that the Ganesha instances run on, and tracking Ganesha status, and failing over the virtual IPs from on Ganesha to another, and back, based on that status.

Kubernetes works by quickly restarting the dead Ganesha instance.  In this case, it also needs to signal to the other Ganesha instances that they should go into grace, by calling the appropriate ganesha-rados-grace command.  This style is still a work-in-progress, so it's not fully automated yet.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
