### ISSUE TITLE
NFS v3,nfs-ganesha 2.6.3, HA Migration, and stale handles on clients  

### ISSUE THREAD

**Issue by uyghfjhh** [nfs-ganesha/nfs-ganesha#368]
nfs-ganesha is configured to use CEPH：

e.g.

CACHEINODE
{
        Dir_Max = 1;
        Dir_Chunk = 0;
        Cache_FDs = false;
        NParts = 1;
        Cache_Size = 1;
        Attr_Expiration_Time = 0;
}

NFSV4
{
        Grace_Period = 10;
}

EXPORT
{
        Export_Id = 1;
        Path = /test1;
        Pseudo = /test1;
        Access_Type = RW;
        Protocols = 3,4;
        Squash = No_Root_Squash;
        Filesystem_id = 666.1;
        FSAL {
                Name = CEPH;
        }
}

Test environment: two node with nfs-ganesha 2.6.3 and CTDB installed . ceph version is 12.2.2-18.
		
Step one: On node 1 I exectue the command 'dd of=./test if=/dev/zero bs=64k count=1000000 ' 	
Step two: Make nfs-ganesha switch from node 1 to node 2 , most of the time is good, but sometimes an error 'Stale file handle ' occurs on node 2

I found that every time client report error 'Stale file handle ', the client will have a log similar to the following.

__
Nov  6 09:19:49 xk_ceph73 kernel: [514433.246913] NFS: permission(0:44/1099511629802), mask=0x81, res=-10
Nov  6 09:19:49 xk_ceph73 kernel: [514433.246916] NFS call  access
Nov  6 09:19:49 xk_ceph73 kernel: [514433.247467] NFS: nfs_update_inode(0:44/1099511629802 fh_crc=0x65d3b25e ct=2 info=0x27e7f)
Nov  6 09:19:49 xk_ceph73 kernel: [514433.247470] NFS: isize change on server for file 0:44/1099511629802 (0 to 2383343616)
Nov  6 09:19:49 xk_ceph73 kernel: [514433.247471] NFS reply access: 0
Nov  6 09:19:49 xk_ceph73 kernel: [514433.247474] NFS: permission(0:44/1099511629802), mask=0x1, res=0
Nov  6 09:19:49 xk_ceph73 kernel: [514433.254134] NFS: permission(0:44/1099511629802), mask=0x81, res=0
__

But the nfs-ganesha log did not report an error.

Question:
How to solve the error 'Stale file handle'

**Comment by dang** [comment]
@jtlayton Any ideas?

**Comment by dang** [comment]
(Note, you may have to upgrade to 2.7.1, I believe there are HA fixes that are not in 2.6.x)

**Comment by jtlayton** [comment]
Not right offhand.  Are some of these inodes snapshotted? There is a known problem with being able to lookup snapshotted inodes after a restart. What NFS version are you using too?

What may be best is to get a capture of the network traffic during failover, which may give us some idea of the series of events. And yes, trying a later ganesha version would be a helpful data point.

**Comment by jtlayton** [comment]
Actually, I wonder if you may just need to pull in 7d10d18dec51. ganesha from this era will tear down the exports table before shutting down RPC services, and that could lead to ESTALE errors if some RPCs race in between the two events.

It looks like v2.6.z never got that patch, though it should be in stock v2.7.

**Comment by dang** [comment]
It looks like EIO (or, more specifically NFS4ERR_IO) can only be returned by the FSAL, except in the case of invalid attributes.  So, either the attributes got messed up, or CEPH returned an error that translated into EIO.

**Comment by jtlayton** [comment]
Yes an error like that on the client could be a bug on the client or the server. What you'll probably need to do is sniff traffic between client and server and determine what happened.

**Comment by uyghfjhh** [comment]
@pasikarkkainen those input/output error occurs regardless of whether or not to  apply the patch.

**Comment by pasikarkkainen** [comment]
Ok. Sounds like the patch should then be applied/backported to 2.6 branch aswell?

**Comment by uyghfjhh** [comment]
@jtlayton During HA Migration, I sometimes get an Input/output error. I caught the following log, and I sniffed the network traffic and generated a pcap file with a size of 90M.
But I don't know how to send it to you.
Here is the error log I caught:
```
14/11/2018 T16:41:13.457753+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/Protocols/NFS/nfs4_op_open.c :open4_open_owner :STATE :F_DBG :Open: STATE_OPEN_OWNER_NFSV4 0x7f227001fa20: clientid={0x7f227c53d8a0 ClientID={Epoch=0x5bebc202 Counter=0x00000002} CONFIRMED Client={0x7f227c405740 name=(40:Linux NFSv4.0 192.8.9.73/192.8.9.233 tcp) refcount=1} t_delta=0 reservations=1 refcount=4 cb_prog=1073741824 r_addr=192.8.9.73.204.190 r_netid=tcp} owner=(24:0x6f70656e2069643a0000002c000000010001d8c98e57a6f9) confirmed=1 seqid=3 refcount=2
14/11/2018 T16:41:13.457780+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/SAL/nfs4_owner.c :Check_nfs4_seqid :STATE :F_DBG :OPEN: Check {STATE_OPEN_OWNER_NFSV4 0x7f227001fa20: clientid={0x7f227c53d8a0 ClientID={Epoch=0x5bebc202 Counter=0x00000002} CONFIRMED Client={0x7f227c405740 name=(40:Linux NFSv4.0 192.8.9.73/192.8.9.233 tcp) refcount=1} t_delta=0 reservations=1 refcount=4 cb_prog=1073741824 r_addr=192.8.9.73.204.190 r_netid=tcp} owner=(24:0x6f70656e2069643a0000002c000000010001d8c98e57a6f9) confirmed=1 seqid=3 refcount=2} next 4 req seqid 5
14/11/2018 T16:41:13.457797+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/SAL/nfs4_owner.c :Check_nfs4_seqid :STATE :DEBUG :OPEN: Invalid seqid 5 in request (not replay), expected seqid for {STATE_OPEN_OWNER_NFSV4 0x7f227001fa20: clientid={0x7f227c53d8a0 ClientID={Epoch=0x5bebc202 Counter=0x00000002} CONFIRMED Client={0x7f227c405740 name=(40:Linux NFSv4.0 192.8.9.73/192.8.9.233 tcp) refcount=1} t_delta=0 reservations=1 refcount=4 cb_prog=1073741824 r_addr=192.8.9.73.204.190 r_netid=tcp} owner=(24:0x6f70656e2069643a0000002c000000010001d8c98e57a6f9) confirmed=1 seqid=3 refcount=2}, returning NFS4ERR_BAD_SEQID
14/11/2018 T16:41:13.457809+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/Protocols/NFS/nfs4_op_open.c :nfs4_op_open :NFS4 :DEBUG :open4_open_owner failed
14/11/2018 T16:41:13.457834+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/SAL/state_misc.c :dec_state_owner_ref :STATE :F_DBG :Decrement refcount now=1 {STATE_OPEN_OWNER_NFSV4 0x7f227001fa20: clientid={0x7f227c53d8a0 ClientID={Epoch=0x5bebc202 Counter=0x00000002} CONFIRMED Client={0x7f227c405740 name=(40:Linux NFSv4.0 192.8.9.73/192.8.9.233 tcp) refcount=1} t_delta=0 reservations=0 refcount=4 cb_prog=1073741824 r_addr=192.8.9.73.204.190 r_netid=tcp} owner=(24:0x6f70656e2069643a0000002c000000010001d8c98e57a6f9) confirmed=1 seqid=3 refcount=2}
14/11/2018 T16:41:13.457848+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/Protocols/NFS/nfs4_Compound.c :nfs4_Compound :NFS4 :DEBUG :Status of OP_OPEN in position 1 = NFS4ERR_BAD_SEQID
14/11/2018 T16:41:13.457860+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/Protocols/NFS/nfs4_Compound.c :nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_BAD_SEQID lastindex = 1
14/11/2018 T16:41:13.457872+0800 : epoch 5bebc202 : ceph7 : ganesha.nfsd-224036[::ffff:192.8.9.73] [svc_2833] /root/rpmbuild/BUILD/nfs-ganesha-2.6.3/Protocols/NFS/nfs4_Compound.c :compound_data_Free :EXPORT :F_DBG :put export ref for id 1 /test1, refcount = 3
```

Can you help me analyze the cause of the error? If you need a pcap file, how can I send it to you?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
