### ISSUE TITLE
cephfs rados_cluster HA not working

### ISSUE THREAD

**Issue by stef97** [nfs-ganesha/nfs-ganesha#370]
Hi
I have configured latest 2.8 to use rados_cluster and pacemaker
It is working fine as long as BOTH instances are up and running
As soon as one is down, I cannot connect using VIP address - I can still see the shares if I connect directly to   the host that is up 

Any hints/suggestions for troubleshooting this will be appreciated 

When one host is down 
ganesha-rados-grace
cur=21 rec=20
======================================================
osd01.tor.medavail.net  NE
osd02.tor.medavail.net   E

Here are more info
rados -p nfs-ganesha ls
ganesha-config
rec-0000000000000015:osd02.tor.medavail.net
rec-0000000000000015:osd01.tor.medavail.net
grace

Excerpt from /etc/ganesha/ganesha.conf

%url rados://nfs-ganesha/ganesha-config

NFSv4 {
  RecoveryBackend = "rados_cluster";
}

RADOS_KV {
  ceph_conf = "/etc/ceph/ceph.conf";
   UserId =  admin;
#   pool = rbd;
   nodeid = osd02.tor.medavail.net;
}

pcs config show
Cluster Name: ganesha
Corosync Nodes:
 osd01.tor.medavail.net osd02.tor.medavail.net
Pacemaker Nodes:
 osd01.tor.medavail.net osd02.tor.medavail.net

Resources:
 Resource: virtual_public_ip (class=ocf provider=heartbeat type=IPaddr2)
  Attributes: cidr_netmask=32 ip=10.10.30.189 nic=eth14
  Meta Attrs: failure-timeout=30s migration-threshold=2
  Operations: monitor interval=10s (virtual_public_ip-monitor-interval-10s)
              start interval=0s timeout=20s (virtual_public_ip-start-interval-0s)
              stop interval=0s timeout=20s (virtual_public_ip-stop-interval-0s)
 Clone: nfs-ganesha-clone
  Meta Attrs: clone-max=2 clone-node-max=2 interleave=true
  Resource: nfs-ganesha (class=systemd type=nfs-ganesha)
   Operations: monitor interval=30s (nfs-ganesha-monitor-interval-30s)
               start interval=0s timeout=100 (nfs-ganesha-start-interval-0s)
               stop interval=0s timeout=100 (nfs-ganesha-stop-interval-0s)

Stonith Devices:
Fencing Levels:

Location Constraints:
Ordering Constraints:
Colocation Constraints:
  virtual_public_ip with nfs-ganesha-clone (score:INFINITY)
Ticket Constraints:

Alerts:
 No alerts defined

Resources Defaults:
 No defaults set
Operations Defaults:
 No defaults set

Cluster Properties:
 cluster-infrastructure: corosync
 cluster-name: ganesha
 dc-version: 1.1.18-11.el7_5.3-2b07d5c5a9
 have-watchdog: false
 no-quorum-policy: ignore
 stonith-enabled: false

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by ffilz** [comment]
Closing due to age with no response.

**Comment by indian4646** [comment]
Hi @ffilz

This problem still exists.

I deployed a 3-node Ceph cluster using cephadm, running 3 active NFS servers with RADOS backend using rados_cluster. When I stop one NFS server, the remaining NFS servers enter a grace period and cannot lift the grace period. Linux mount clients freeze during read/write operations.

From my understanding, they should exit this state after 90 seconds. However, even after waiting longer than 90 seconds, they do not exit. In this situation, what does the client need to do to exit the grace period? I understand this period is meant to prevent data loss, but it’s unclear how to exit it correctly.  It seems that the grace period can only be lifted when the stopped node recovers.

My version is 5-stable. I tried using Graceless true, but it caused a crash, so I didn't use it.


ganesha log:
nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
nfs_start_grace :STATE :EVENT :grace reload client info completed from backend
nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(1)

ganesha-rados-grace -p .nfs --ns nfss.pod1_rack1
cur=39 rec=38
======================================================
nfs.nfss.pod1_rack1.0	NE
nfs.nfss.pod1_rack1.1	 E
nfs.nfss.pod1_rack1.2	 E
