### ISSUE TITLE
Doubt about ganesha configuration file

### ISSUE THREAD

**Issue by uyghfjhh** [nfs-ganesha/nfs-ganesha#372]
I found  a config file at path nfs-ganesha/src/config_samples/ceph.conf
there is something in this file as blow：
：
CACHEINODE {
	# Size the dirent cache down as small as possible.
	Dir_Chunk = 0;

	# size the inode cache as small as possible
	NParts = 1;
	Cache_Size = 1;
}

After using the above configuration, the cache will still be inserted into avltree.
As shown in the following code：

static inline int
cih_set_latched(mdcache_entry_t *entry, cih_latch_t *latch,
		struct fsal_module *fsal,
		struct gsh_buffdesc *fh_desc,
		uint32_t flags)
{
	cih_partition_t *cp = latch->cp;

	/* Omit hash if you are SURE we hashed it, and that the
	 * hash remains valid */
	if (unlikely(!(flags & CIH_SET_HASHED)))
		if (!cih_hash_key(&entry->fh_hk.key, fsal,
				  fh_desc, CIH_HASH_NONE))
			return 1;

	(void)avltree_insert(&entry->fh_hk.node_k, &cp->t);
	entry->fh_hk.inavl = true;
#ifdef USE_LTTNG
	tracepoint(mdcache, mdc_lru_insert, __func__, __LINE__, entry,
		   entry->lru.refcnt);
#endif

	if (likely(flags & CIH_SET_UNLOCK))
		cih_hash_release(latch);

	return 0;
}

And  Mdcache_find_keyed(mdcache_key_t *key, mdcache_entry_t **entry)  seems to get slower.

My question is: What is the purpose of this configuration?

	# size the inode cache as small as possible
	NParts = 1;
	Cache_Size = 1;

**Comment by dang** [comment]
The short answer is: not much.  You cannot run without MDCACHE, since it provides the stable handle cache required by SAL and the protocol layers.  Those settings change the size of the hash table used to speed up lookups.  It will have a slight negative affect on speed, and use somewhat less memory.

**Comment by uyghfjhh** [comment]
@dang thank you very much，I've got it
