### ISSUE TITLE
Here may lead the inode( . .. ) reference leak.

### ISSUE THREAD

**Issue by wugang33** [nfs-ganesha/nfs-ganesha#373]
https://github.com/nfs-ganesha/nfs-ganesha/blob/25876b6bb486cb919e9454df4d10b06236c8d57d/src/FSAL/FSAL_CEPH/handle.c#L223

**Comment by dang** [comment]
I'm not seeing how there's a reference leak there.  We haven't taken any refs on Ganesha objects, and de doesn't seem to be refcounted.  Can you be more specific?

**Comment by wugang33** [comment]
When we got a Inode* from libcephfs , will add a reference to Inode* into the libcepfs. 

the reference code of libcephfs is here
`Client::readdir_r_cb
  .....
if (dirp->offset == 0) {
    ldout(cct, 15) << " including ." << dendl;
    assert(diri->dn_set.size() < 2); // can't have multiple hard-links to a dir
    uint64_t next_off = 1;

    int r;
    r = _getattr(diri, caps, dirp->perms);
    if (r < 0)
      return r;

    fill_statx(diri, caps, &stx);
    fill_dirent(&de, ".", S_IFDIR, stx.stx_ino, next_off);

    Inode *inode = NULL;
    if (getref) {
      inode = diri.get();
      _ll_get(inode);     // this is the reference we leaked
    }`


So maybe change code in ganesha like this
`/* skip . and .. */
			if ((strcmp(de.d_name, ".") == 0)
			    || (strcmp(de.d_name, "..") == 0)) {
				if(i)
					ceph_ll_put(export->cmount, i);
				continue;
			}`

The other inode is not leak because the code
`void deconstruct_handle(struct handle *obj)
{
	ceph_ll_put(obj->export->cmount, obj->i);
	fsal_obj_handle_fini(&obj->handle);
	gsh_free(obj);
}`
will do reference release;

**Comment by ffilz** [comment]
Patch submitted and applied, resolved... Commit 1a9ed7f74ccd5cf72f5c09d79158409efe7091d4
