### ISSUE TITLE
 nfs-ganesha 2.6.3 not support fsal_ceph  nfsacl？

### ISSUE THREAD

**Issue by uyghfjhh** [nfs-ganesha/nfs-ganesha#376]
I encountered the following error when testing:
```
[root@node181 mnt]# nfs4_setfacl -a A::EVERYONE@:r s1
Failed setxattr operation: Invalid argument
```
Then after I modified the code, the error disappeared，but nfs4_getfacl returns nothing
```c
diff --git a/src/FSAL/FSAL_CEPH/internal.h b/src/FSAL/FSAL_CEPH/internal.h
index 14e2341..bf4784f 100644
--- a/src/FSAL/FSAL_CEPH/internal.h
+++ b/src/FSAL/FSAL_CEPH/internal.h
@@ -146,7 +146,7 @@ struct ds {
 #define CEPH_SETTABLE_ATTRIBUTES ((const attrmask_t) (                 \
        ATTR_MODE  | ATTR_OWNER | ATTR_GROUP | ATTR_ATIME        |      \
        ATTR_CTIME | ATTR_MTIME | ATTR_SIZE  | ATTR_MTIME_SERVER |      \
---       ATTR_ATIME_SERVER))
+++       ATTR_ATIME_SERVER | ATTR_ACL ))
```
My question ：
Is this is a bug, or ganesha fsal_ceph does not support nfsacl?

**Comment by dang** [comment]
Ceph's LL interface (part of libcephfs) doesn't support ACLs, only normal attributes and xattrs.  All your change did was move from returning an error for ACLs to silently ignoring them, since there's no way to set them into CephFS itself.

**Comment by uyghfjhh** [comment]
@dang Thank you very much, I get it
