### ISSUE TITLE
Disable ganesha caches

### ISSUE THREAD

**Issue by tm4n** [nfs-ganesha/nfs-ganesha#379]
I'm trying to disable caching for a specific folder, that should only be accessible for clients in a specific IP range. I do this by checking the caller ip address in my custom FSAL code on lookup operations, and rejecting access if needed.
But ganesha caches the result of a successful lookup, and afterwards clients that should not be able to see the folder get the contents from the cache. I can see that with two nearly simultaneous NFSv4 operations from different clients, my FSAL gets only one call with one if the IP addresses.

I tried to set the expire_time_attr for the returned attrlist in lookup to 0, but that did not help. I've tested both 2.4.5 and 2.7.1.

I then tried to disable the whole cache via config options (in version 2.4.5):
```
NFS_Core_Param
{
  DRC_Disabled = true;
}
CACHE_INODE {
  Attr_Expiration_Time = 0;   // Also tried -1
  Cache_FDs = false;
}
```
But no success, I can still get access if I get the timing right. I also set the Cache_Size and FD_Limit_Percent options to their minimal values, but that didn't help.

**Comment by tm4n** [comment]
Thank you for your fast answer! I'm actually trying to disallow NFSv4 mount (lookup call) directly into the folder, so dirents might be the right cache entry type, I'm not sure.
However I just tested it with 2.4.5 and the Dir_Max = 1; setting, and I can still trigger the bug as described above. It usually needs a few tries, but if I get the timing right there still is only one lookup_call into the fsal. I'm using two different physical machines for the two simultaneous mount commands, so I'm pretty sure it's not caused by a client cache.

**Comment by dang** [comment]
A lookup will first look into the dirent cache, and if it's found there, return it.  If not, it will call into the FSAL.  This may not always work on 2.4, since the relevant conditions only trigger after a readdir has happened, but it should work correctly on 2.7.

You should be using 2.7, anyway, as 2.4 has been end-of-life and unsupported for a long time.

**Comment by ffilz** [comment]
I'm not sure what you're trying to do of client permission checking on a per folder basis is workable.
Do you have lots of such folders? You could do an export per folder and use export permissions to only allow the specific client.
Another way if you were up to some Ganesha coding would be to extend the file permission model to include the client in the credentials so then even if the entries were cached, we still do a per operation permission check. That might not be too hard to add.

**Comment by tm4n** [comment]
Thank you both for your input! I've tried Dir_Chunk in 2.7.1 and it looks like it fully disables the cache and solves the issue. My fsal now crashes on readdir however, because I now receive a getattrs (though fsal_test_access) while the readdir is passing data through the callback. My code has a thread local variable that assumes only one fsal call is running at the same time, and I now have two (readdir and getattrs). I can post the stacktrace if you are interested.

I still need a solution for 2.4.5 unfortunately, so I guess I'll need to make changes to the ganesha codeanyway.

**Comment by dang** [comment]
There's no reason why mdcache can't call back down into your FSAL during a callback, so it's probably best to just fix that.

**Comment by tm4n** [comment]
I've been able to fix that crash. Also I'm now solely using 2.7.3 and thus Dir_Chunk = 0; works as expected. Thank you for your help, it is very much appreciated.
