### ISSUE TITLE
Cmake minimal version should be 2.8.4

### ISSUE THREAD

**Issue by odoucet** [nfs-ganesha/nfs-ganesha#38]
This project requires the policy CMP0017. This has been added in Cmake 2.8.4 : 
http://multivac.fatburen.org/localdoc/cmake/cmake-policies.html#policy:CMP0017

But file src/CMakeLists.txt reports minimal version of Cmake as 2.6.3

**Comment by ffilz** [comment]
Dan, is this an issue we need to address?

**Comment by dang** [comment]
I don't think so.  I don't think that we care which version gets used. Rather, we should remove the versions we're carrying around as soon as we require a version that provides that feature.

**Comment by dang** [comment]
Okay, I've diffed all the versions we carry, and there's no significant differences.  In addition, only CMakeParseArguments.cmake isn't shipped with 2.6.3, so we can probably drop the other 3 entirely.  If we want to up the minimum version to 2.8 (which is available even in Trusty) we can get rid of all of the standard modules.

**Comment by dang** [comment]
Which, I just realized, would put us at the version of this issue...

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
