### ISSUE TITLE
Type pun (strict-aliasing) warning seen in x86_64 build log

### ISSUE THREAD

**Issue by tserlin** [nfs-ganesha/nfs-ganesha#380]
This was seen in the RPMDiff of downstream nfs-ganesha 2.7.1:

```
    470  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c: In function 'rados_grace_dump':
    471  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c:122:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    474  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c: In function 'rados_grace_epochs':
    475  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c:164:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    478  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c: In function 'rados_grace_enforcing_toggle':
    479  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c:278:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    482  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c: In function 'rados_grace_join_bulk':
    483  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c:461:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    487  Building C object support/CMakeFiles/support.dir/nfs4_acls.c.o
    488  /builddir/build/BUILD/nfs-ganesha-2.7.1/src/support/rados_grace.c:594:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
```

Our internal downstream documentation for RPMDiff says:

> Type pun (strict-aliasing) warning: triggers on this gcc warning: "dereferencing type-punned pointer will break strict-aliasing rules" (rfe 225186); these errors occur occasionally and are serious and easy to fix: the compiler is warning that it might be taking the address of a temporary, rather than the address of the "real" data, so the resulting pointer might not be what you were expecting. The fix is easy: add -fno-strict-aliasing to the compiler flags. See stackoverflow (http://stackoverflow.com/questions/98650/what-is-the-strict-aliasing-rule) for further discussion.

Is there any issue with using their recommendation of "-fno-strict-aliasing"?

**Comment by dang** [comment]
These aliases should be safe, although they may violate alighment. (unlikely, but possible for rados_grace_enforcing_toggle() and rados_grace_join_bulk())  I think turning on -fno-strict-aliasing should be fine.

**Comment by ffilz** [comment]
I'm going to mark this as resolved.
