### ISSUE TITLE
ganesha_stats failed to run

### ISSUE THREAD

**Issue by bstillwell** [nfs-ganesha/nfs-ganesha#382]
When attempting to run ganesha_stats it fails to run with the following error message:

```
# ganesha_stats
  File "/usr/bin/ganesha_stats", line 105
    print exp_interface.status_stats()
                      ^
SyntaxError: invalid syntax
```

It appears like there are some missing parenthesis based on the rest of the if/elif statements.

**Comment by dang** [comment]
The if statements are fine, it's the print statement that needs the parens.
https://review.gerrithub.io/#/c/ffilz/nfs-ganesha/+/437682

**Comment by bstillwell** [comment]
The fix looks good to me, thanks!
