### ISSUE TITLE
Connection terminated with krb5p

### ISSUE THREAD

**Issue by xiaoxichen** [nfs-ganesha/nfs-ganesha#384]
When mounting a VFS/CephFS share from NFS Ganesha with krb5p and *copy* large files from the share,  the TCP connection will soon goes to "FIN_WAIT2" in client side and "close_wait" in Ganesha side. 

Small files (like cat an txt file) is good. krb5i and host security both works fine too.

I scan across the Ganesha log, only strange thing is `nfs_rpc_decode_request ` return change from `XPRT_IDLE` to `XPRT_DESTROPYED`

The client side is ubuntu 16.04 with 4.4 kernel and rpc.gssd. Ganesha side is v2.7.1

**Comment by dang** [comment]
Can you try with FSAL_CEPH rather than with VFS?  Ganesha has a FSAL designed to access CephFS.

**Comment by xiaoxichen** [comment]
BY VFS/CephFS  I mean we hit the issue on both FSAL...actually our intention is FSAL_CEPH and hit the connection terminating issue, then we switched to VFS+ XFS to see if it related with FSAL_CEPH, and hit same issue as well, which indicate it is not related with CEPH_FSAL

**Comment by dang** [comment]
Ah, okay.  I misunderstood.  Can you capture a log with FULL_DEBUG on, and either paste it here, or (if it has sensitive information) mail it to me?

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
