### ISSUE TITLE
NFS Server Now NOT IN GRACE  - 2.7.1  - vmware 6.7 U1 NFS4.1

### ISSUE THREAD

**Issue by madmax01** [nfs-ganesha/nfs-ganesha#386]
Hi there,

maybe anyone have an Hint.

i'am not exactly sure if this is a Bug on Vmware Side or a Bug on Ganesha Side.

Issue:

1.	Hot VM svmotion from Local Storage to NFS 4.1 Datastore =  Failed waiting for data. Error 195887107. Not found. 

2.	Cold VM svmotion from Local Storage to NFS 4.1 Datastore = WORKS
3.	Hot VM svmotion from NFS 4.1 Datastore to Local Datastore = WORKS
4.     VM Snapshot > then i could do a Hot svmotion from local Datastore to NFS 4.1  = WORKS
5.     CLONE Vm from local datastore to NFS 4.1  = WORKS

So only a normal svmotion from local to NFS4.1 doesn't work.

Error in the vmware Logs:  (doesn't make Sense to me). just a 2GB memory test vm.

failed to open (The file specified is not a virtual disk): Size of extent in descriptor file larger than real size. Type 3    

Maybe anything special need to be configured with Ganesha? NFS3  works without any issues.

i use this Config:

NFS_CORE_PARAM {

        Short_File_Handle = TRUE;

        ## Allow NFSv3 to mount paths with the Pseudo path, the same as NFSv4,
        ## instead of using the physical paths.
        #mount_path_pseudo = true;
        mount_path_pseudo = true;

        ## Configure the protocols that Ganesha will listen for.  This is a hard
        ## limit, as this list determines which sockets are opened.  This list
        ## can be restricted per export, but cannot be expanded.
        #Protocols = 3,4,9P;
        Protocols = 3,4;
}

## These are defaults for exports.  They can be overridden per-export.
EXPORT_DEFAULTS {
        ## Access type for clients.  Default is None, so some access must be
        ## given either here or in the export itself.
        #Access_Type = RW;
        Access_Type = RW;
}

## Configure settings for the object handle cache
#CACHEINODE {
        ## The point at which object cache entries will start being reused.
        #Entries_HWMark = 100000;
#}

## Configure an export for some file tree
EXPORT
{
        ## Export Id (mandatory, each EXPORT must have a unique Export_Id)
        #Export_Id = 12345;
        Export_Id = 1;

        ## Exported path (mandatory)
        #Path = /nonexistant;
        Path = /test0;

        ## Pseudo Path (required for NFSv4 or if mount_path_pseudo = true)
        #Pseudo = /nonexistant;
        Pseudo = /test0;
## Pseudo Path (required for NFSv4 or if mount_path_pseudo = true)
        #Pseudo = /nonexistant;
        Pseudo = /test0;

        ## Restrict the protocols that may use this export.  This cannot allow
        ## access that is denied in NFS_CORE_PARAM.
        #Protocols = 3,4;
        Protocols = 3,4;

        ## Access type for clients.  Default is None, so some access must be
        ## given. It can be here, in the EXPORT_DEFAULTS, or in a CLIENT block
        #Access_Type = RW;
        Access_Type = RW;

        #to enable/disable ACL
        Disable_ACL = TRUE;

        Transports = UDP,TCP ; # Transport protocols supported

        ## Whether to squash various users.
        #Squash = root_squash;
        Squash = No_root_squash;

        ## Allowed security types for this export
        #Sectype = sys,krb5,krb5i,krb5p;
        Sectype = sys;

        ## Exporting FSAL
        FSAL {
                Name = GLUSTER;
                hostname = x.x.x.x;
                volume = "test0";

        }

        client {
        clients = x.x.x.x/24;  # IP of the client.
        access_type = RW;
        Protocols = 3,4;

  }
}

## configured from the command line
LOG {
        ## Default log level for all components
        Default_Log_Level = WARN;

        ## Configure per-component log levels.
        Components {
                FSAL = INFO;
                NFS4 = EVENT;
        }

        ## Where to log
        #Facility {
                #name = FILE;	

 #destination = "/var/log/ganesha.log";
                #enable = active;
        #}
}

				`

thx

Max

**Comment by dang** [comment]
Sorry for the late reply; Much of the USA has been on holiday for the last several weeks.

Googling around, it appears that this is a mismatch between the recorded size of the VMDK in it's config file and the actual size of the VMDK.  This means that either Ganesha is returning the incorrect size, or that writing the file via v4 somehow ended up with a different size.  Can you do two things for me:

1. In the log, there should be a line like this:
vmx| DISKLIB-VMFS : VmfsExtentCommonOpen: possible extent truncation (?) realSize is 58720256, size in descriptor 83886080.

Can you find that line and post it, so we can see the expected and actual sizes?

2. Can you get a packet trace of the process (or at least the end of it)?  Wireshark can be used to get a packet trace.

**Comment by madmax01** [comment]
Hi Dang,

Happy New Year ;).

thx for Message.

it appears having 2 Issues i figured out.

1:    Hot Svmotion from local to NFS4.1  doesn't work (only Cold works.  and from NFS to local)
2:    delete  "Folder"  on NFS4.1  not working   (gives  "Not a directory") Error.   equal if  with rmdir or rm.
       mounting same mountpoint over Linux all fine to delete the Folders

i checked the vmdk file:

# Extent description
RW 20971520 VMFS

in the vmware.log it says

vmfs capacity=20971520 (10 GB) adapter=lsilogic info=cowGran=0 allocType=1 objType= policy=''
creation successful
open successful (1) size = 10737418240, hd = 0. Type 3

so the error appears such fast, that i'am not able to look to filesystem.  1sec

so it looks like it's creating the file,.. as it says successful and giving right size,...

but then throw error after.

VmfsExtentCommonOpen: possible extent truncation (?) realSize is 0, size in descriptor 20971520.
----------------

so that sounds to me it's getting created,... but then somehow thrown away for any reason

but i dont see any activity in the Ganesha log file

tail -f /var/log/ganesha/ganesha.log

how do i need to change ganesha conf > able to see more details? may could paste then more helpfully infos

for Tracing,... need to check how it works.  you mean tracing the ganesha process? or you mean tracing vmnic on vmware side

thx

**Comment by dang** [comment]
If it's quick, you can turn on FULL_DEBUG logging on Ganesha.  This is done by putting
ALL = FULL_DEBUG;
in the LOG { Components { } } section, or by specifying
-N NIV_FULL_DEBUG
on the command line that starts Ganesha.

By tracing, I meant a packet trace.  Probably the best place to do it is on the NIC of the Ganesha machine, but the vmnic on vmware would work as well, if that's even possible.  You can wait on this until we've had a look at the debug logging on Ganesha, however.

**Comment by madmax01** [comment]
Hi there

i generated an wetransfer link with the ganesha.log

https://we.tl/t-3m9j2tPd3C   (migration)

tried 2 times.

based on the time inside the log.  i started migration round about 

17:35:03 and 17:37:23

i got error in few secs,.. but debug log running fastly down.

1.1.1.2 is  ip on the esxi side
1.1.1.4 is ip on the ganesha side

2nd Log is where i tried to delete  Folder from Mountpoint.  as once migration failes ,... seems esxi not able to delete the folder. (but once mounting it over linux all fine). rmdir: 'xxxxx': Not a directory. May this is related to the failing Hot Migration.  and it's definitv an Director. drwxr-xr-x    and could "cd" into

https://we.tl/t-N2AWQnKT4K (tried to delete Directory)

thx for Analyze ;)

**Comment by madmax01** [comment]
Hi dang,

many thx for Answer.  The Confusing Point for me for Point 1 is,  it's equal when i do it > seems hot migration fails all time.  so means Gluster/ganesha is all time in a Grace Mode?  anything i need to change for this?

for the tracing.  would look onto gluster vm.   could you may help me for the correct syntax, as i'am not very familiar with Tracings.  

Many thx

**Comment by dang** [comment]
I think you have two separate failure cases.  The first case is when you try to migrate too soon after Ganesha has started, and get NFS4ERR_GRACE.  This is expected, and correct behavior.

However, even after Ganesha has left Grace, there appears to be another failure.  It seems to be related to the VERIFY op, but the logging in Ganesha isn't sufficient, so a packet trace becomes necessary.

To get a raw packet dump, you run this on the Ganesha server:

`tcpdump -s0 -w /tmp/nfs.pcap <vmware-machine>`

where _vmware-machine_ is the hostname or IP address of the VMWare that's doing the migration.  That will create a file /tmp/nfs.pcap (which you can, of course, name whatever you want) that has the raw packet traces between the two machines.  You can post that here, or we can find some other way to get it to me if you'd prefer.

These raw packet traces can be analyzed by Wireshark, is you'd like to look at them before you give them to me.

**Comment by madmax01** [comment]
Hi there,

i created 2 pcap files and uploaded zipped

above i got syntax error.  so i processed "dst+src" like described here https://unix.stackexchange.com/questions/193637/how-to-capture-src-and-dst-traffic-both-directions-with-tcpdump-with-one-comm

https://we.tl/t-QiXZ2yD9Hp

is that helpfully?

many thx

Max

**Comment by dang** [comment]
The pcap files are fine, thanks.  I'm analyzing.

**Comment by dang** [comment]
I've tracked this down to VMWare sending an attribute bitmap larger than it needs to be.  It's only requesting attribute 2 (TYPE), which fits (of course) in the first word of the bitmap.  However, it's sending 3 words of bitmap, with the rest of the words set to zero.  This is technically a valid bitmap, but Ganesha is (somewhat reasonably) expecting a minimal bitmap, so it's expecting one word.  I'm working on a fix for this.

**Comment by dang** [comment]
Okay, I believe I have a fix proposed here:
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/440749
If you can build from source, could you test that build?  I don't have access to VMWare to test.

**Comment by dang** [comment]
It should fix both.  You can follow instructions here:
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/COMPILING_HOWTO.txt
That file's also in the checked out source.  Unfortunately, the fix isn't committed to the main codebase yet (it's still under review), so you'd have to get it from gerrithub.  That's a bit complicated, so it may be better to just wait until it's merged.  The maintainer is on vacation this week, so that will be next friday.

**Comment by madmax01** [comment]
Many thx Dang.  I will just wait until it's committed.

**Comment by dang** [comment]
Frank did a special merge yesterday, so it's in the next branch now.

**Comment by madmax01** [comment]
Hi Dang.

many thx.  just tried to handle the Source.  but getting Issues

once processing the cmake i'am getting this error:

 Cannot find GLUSTER GFAPI runtime.  Disabling GLUSTER fsal build
userspace-rcu library not found!

but once i check installed Package i see : 

Package userspace-rcu-0.10.0-3.el7.x86_64 already installed and latest version
Package glusterfs-api-5.2-1.el7.x86_64 already installed and latest version

how could i fix the right path so that the compiler find it?

thx

Max

**Comment by madmax01** [comment]
ah many thx.  that seems was it.  just version error is bit confusing ;)

glusterfs-api-devel
 userspace-rcu-devel.x86_64

compiler worked now.

but the Docus stopping at "make install".  not seeing any kind of rpm and no instructions how to install nfs-ganesha.service

i think i will wait for officially 2.8 release.  bit complicated

**Comment by pasikarkkainen** [comment]
@dang Thanks a lot for the patch! What's needed for this to get backported to 2.7 branch, for 2.7.2 release?

@madmax01 You could use the existing nfs-ganesha.service file (from the earlier rpm you used, save a backup copy of it). It'd be good to get the patch tested and verified on your setup.

**Comment by dang** [comment]
We'll do a backport to 2.7

These are different errors, unrelated to the other one.  We'll have to track these down as well, I suspect. Unfortunately, I looked at both the traces, and I didn't see any problems.  Yes, you get a ENOENT error back on some of the file tree traversals, but this is the correct result.  What's happening is that VMWare is starting in a directory, and repeatedly calling LOOKUPP to get the parent directory up the tree.  When we reach the top if the tree, we return NFS4ERR_NOENT (which is what the spec says we should do at that point).  These sequences are the only ones that result in ENOENT being returned, and they all look correct.

**Comment by madmax01** [comment]
Hi there.  just wondering if anything special was fixed since 2.7 and 2.8 in regards to Vmware. since Gluster removed the nativ nfs option > we have issues with the Ganesha.

**Comment by pasikarkkainen** [comment]
@madmax01 Did you try with nfs-ganesha v2.7.3 ? How about 2.8.0 ?

**Comment by madmax01** [comment]
Hi guys,

yes all same with 2.8.2  as well

what i found is > found 1 helpfully Article:

https://www.reddit.com/r/vmware/comments/9dxoyk/unable_to_create_new_vms_or_do_storage_vmotion_to/e5q7x2z/

so once i make a Snapshot of the VM > i could sVmotion the VM onto the NFS4 Datastore.  But without i'am getting the Error.

at the End the person told :

> So, if anyone comes across this issue in the future, make sure they have sync writes enabled on the backing storage; vMotion is creating the file and then immediately trying to open the file to copy into, and not finding it because the sync write isn't  complete.

but it was zfs.   so not sure where to check if sync write is activ  with nfs-ganesha and gluster.   ? 

thx

Max

**Comment by madmax01** [comment]
too old. will open new ones with latest infos
