### ISSUE TITLE
Cannot start nfs-ganesha on Ubuntu 18.04

### ISSUE THREAD

**Issue by mituller** [nfs-ganesha/nfs-ganesha#389]
I am trying to install nfs-ganesha with gluster. I have gluster running, but when I setup nfs-ganesha and try to start it, I get:

load_fsal :NFS STARTUP :CRIT :Could not dlopen module:/usr/lib/arm-linux-gn
ueabihf/ganesha/libfsalshared.so Error:/usr/lib/arm-linux-gnueabihf/ganesha/libfsalshared.so: cannot open shared object file: No such file or directory

I don't know what I am missing. I have tried everything I can think of on this.

**Comment by dang** [comment]
There isn't a libfsalshared.so as part of upstream Ganesha.  Where did you get your packages?  If we can track down how they were built, we can maybe figure out where that library should come from.

**Comment by dang** [comment]
Ah, okay, I think you have a misconfiguration.  Can you paste your config?  I suspect you're trying to specify a FSAL named "shared"

**Comment by mituller** [comment]
Yes, I am. I did try other names and got the same error however, so maybe something else is wrong. I am also including my gluster volume info, as the volume is named shared.

# create new
NFS_CORE_PARAM {
    # possible to mount with NFSv3 to NFSv4 Pseudo path
    mount_path_pseudo = true;
    # NFS protocol
    Protocols = 3,4;
}
EXPORT_DEFAULTS {
    # default access mode
    Access_Type = RW;
}
EXPORT {
    # uniq ID
    Export_Id = 101;
    # mount path of Gluster Volume
    Path = "/shared";
    FSAL {
    # any name
        name = SHARED;
        # hostname or IP address of this Node
        hostname="192.168.86.101";
        # Gluster volume name
        volume="shared";
    }
    # rconfig for root Squash
    Squash="No_root_squash";
    # NFSv4 Pseudo path
    Pseudo="/shared";
    # allowed security options
    SecType = "sys";
}

LOG {
    # default log level
    Default_Log_Level = DEBUG;
}

**Gluster Volume Info**
Volume Name: shared
Type: Stripe
Volume ID: 02b8ddd1-e62b-4011-95a1-d6d855377066
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x 2 = 2
Transport-type: tcp
Bricks:
Brick1: 192.168.86.101:/gluster
Brick2: 192.168.86.102:/gluster
Options Reconfigured:
nfs.disable: on
transport.address-family: inet

**Comment by mituller** [comment]
I still get the same errors. I'll list more from the log file that I see to see if that gives you more info.

```
ganesha.nfsd-16315[main] load_fsal :NFS STARTUP :CRIT :Could not dlopen module:/usr/lib/arm-linux-gnueabihf/ganesha/libfsalgluster.so Error:/usr/lib/arm-linux-gnueabihf/ganesha/libfsalgluster.so: cannot open shared object file: No such file or directory

ganesha.nfsd-16315[main] load_fsal :NFS STARTUP :MAJ :Failed to load module (/usr/lib/arm-linux-gnueabihf/ganesha/libfsalgluster.so) because: Can not access a needed shared library

ganesha.nfsd-16315[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!

ganesha.nfsd-16315[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:11): Failed to load FSAL (GLUSTER) because: Can not access a needed shared library

ganesha.nfsd-16315[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:11): 1 validation errors in block FSAL

ganesha.nfsd-16315[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:11): Errors processing block (FSAL)

ganesha.nfsd-16315[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:8): 1 validation errors in block EXPORT

ganesha.nfsd-16315[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:8): Errors processing block (EXPORT)
```
And my config file
```
NFS_CORE_PARAM {
    mount_path_pseudo = true;
    Protocols = 3,4;
}
EXPORT_DEFAULTS {
    Access_Type = RW;
}
EXPORT {
    Export_Id = 101;
    Path = "/shared";
    FSAL {
        name = GLUSTER;
        hostname="192.168.86.101";
        volume="shared";
    }
    Squash="No_root_squash";
    Pseudo="/shared";
    SecType = "sys";
}

LOG {
    Default_Log_Level = DEBUG;
}
```

**Comment by dang** [comment]
The various FSALs are separate packages for Ganesha.  You need to install "nfs-ganesha-<FSAL>", so in this case, nfs-ganesha-gluster.  If you look at all the packages that are part of the Ganesha project, you can see all the FSALs that BIONIC supports:

https://packages.ubuntu.com/source/bionic/nfs-ganesha

I can see why this might be confusing.

**Comment by mituller** [comment]
That was it. I swear I had that package installed before, but in the process I removed and reinstalled. I may have forgotten to install again in the process. I think it all works now. I tried to connect from my Mac, and found that there are issues with NFS on OSX, and that I have Windows 10 Home, which doesn't have NFS connectors. Grrr.

Thanks for your help.

**Comment by dang** [comment]
Glad it's working.  You can install linux on a virtual machine to test.  VirtualBox supports both windows and OSX.
