### ISSUE TITLE
Cannot dd files on  mountpoints with RGW FSAL backend.

### ISSUE THREAD

**Issue by Dreamyu20xx** [nfs-ganesha/nfs-ganesha#390]
I’m trying to dd some  files to mountpoints ,example:

- **cmd**

   for i in {0..100} ;do dd if=/dev/zero of=./$i bs=1M count=$i; done;

- **result:**
75497472 bytes (75 MB) copied, 1.24629 s, 60.6 MB/s
dd: closing output file ‘./73’: Input/output error
74+0 records in
74+0 records out
77594624 bytes (78 MB) copied, 1.33452 s, 58.1 MB/s
75+0 records in
75+0 records out
91226112 bytes (91 MB) copied, 1.50006 s, 60.8 MB/s
dd: closing output file ‘./88’: Input/output error
dd: closing output file ‘./89’: Input/output error
dd: closing output file ‘./90’: Input/output error
dd: closing output file ‘./91’: Input/output error
92+0 records in
92+0 records out
96468992 bytes (96 MB) copied, 1.61472 s, 59.7 MB/s
dd: closing output file ‘./93’: Input/output error
dd: closing output file ‘./94’: Input/output error
dd: closing output file ‘./95’: Input/output error
........

- **ganesha.log**
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_206] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_220] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_225] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_135] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_105] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_199] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_93] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_166] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
17/01/2019 02:08:44 : epoch 5c3edbe7 : test2 : ganesha.nfsd-91453[svc_190] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable

- **mount cmd** 
mount -t nfs -o nfsvers=4.1,async,proto=tcp 10.0.98.104:/ /mnt/fs3

>  and  I use nfsvers=3 to mount . It creates the same problem.

- **cluster status** 
[root@client2 iortest2]# pwd
/mnt/fs3/cephobject/iortest2
[root@test2 ~]# ceph -s
  cluster:
    id:     11320905-b5dd-4bb9-acfd-71fbb6221c09
    health: HEALTH_OK
 
  services:
    mon:     1 daemons, quorum test2
    mgr:     test2(active)
    osd:     9 osds: 9 up, 9 in
    rgw:     1 daemon active
    rgw-nfs: 1 daemon active
 
  data:
    pools:   6 pools, 768 pgs
    objects: 3.72k objects, 13.0GiB
    usage:   22.1GiB used, 65.5TiB / 65.5TiB avail
    pgs:     768 active+clean

-  **ganesha.conf** 
NFS_Core_Param
{
}
EXPORT
{
        Export_id=20134;
        Path = "/";
        Pseudo = /cephobject;
        Access_Type = RW;
        Protocols = 3,4;
        Transports = TCP;
        SecType = sys,krb5,krb5i,krb5p;
        Squash = Root_Squash;
        FSAL {
                Name = RGW;
                User_Id = "cephnfs";
                Access_Key_Id ="D6AMKHM7EBDP6VSXL01D";
                Secret_Access_Key = "MSwCKdMDBhJQuVFI5NkTJLhWJjSlv8umnsvGLujp";
        }
}
RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        cluster = "ceph";
        name = "client.rgw.test2";
}
LOG {
        Facility {
                name = FILE;
                destination = "/var/log/ganesha/ganesha.log";
                enable = active;
        }
}

**version：**
- ganesha
v2.6

- ceph
12.2.10

I don't understand it ,but I use  it based cephfs . it doesn't create problems. Hope you could explain for me a little bit. Really appreciate your help!

**Comment by Dreamyu20xx** [comment]
Hi Dang,
Sorry for the late reply; I was delayed by something else.
As you see , open **ALL = FULL_DEBUG;**
in the LOG { Components { } } section, 
use **for i in {0..100} ;do dd if=/dev/urandom of=djsds$i bs=1M count=$i; done;**  In client mountpoint
In nfs server I get some  ganesha logs
**result:**
3a0000002c0000000000007d550cff43cd) confirmed=1 seqid=0 refcount=2}
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : ganesha.nfsd-1092898[svc_8] nfs4_write :NFS4 :F_DBG :offset = 10485760  length = 1048576  stable = 0
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : ganesha.nfsd-1092898[svc_8] nfs4_write :NFS4 :F_DBG :offset = 10485760 length = 1048576
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : ganesha.nfsd-1092898[svc_8] rgw_fsal_write2 :FSAL :F_DBG :rgw_fsal_write2 enter obj_hdl 0x7f798012f730 state 0x7f7980022930
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : **ganesha.nfsd-1092898[svc_8] rgw_fsal_write2 :FSAL :F_DBG :rgw_fsal_write2 post obj_hdl 0x7f798012f730 state 0x7f7980022930 returned -5**
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : **ganesha.nfsd-1092898[svc_8] fsal_write2 :FSAL :F_DBG :FSAL WRITE operation returned I/O error, asked_size=1048576, effective_size=0**
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : ganesha.nfsd-1092898[svc_8] nfs4_write :NFS4 :DEBUG :write returned I/O error
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : ganesha.nfsd-1092898[svc_8] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write converted to NFS4ERR_IO but was set non-retryable
22/01/2019 06:11:13 : epoch 5c46b357 : test1 : ganesha.nfsd-1092898[svc_8] dec_nfs4_state_ref :STATE :F_DBG :Decrement refcount now=16 {STATE 0x7f7980022930 OTHER=0x0100000057b3465c12000000 {{CLIENTID Epoch=0x5c46b357 Counter=0x00000001} StateIdCounter=0x00000012} obj=0x7f7980022998 type=SHARE seqid=1 owner={STATE_OPEN_OWNER_NFSV4 0x7f7980023da0: clientid={0x7f7968001740 ClientID={Epoch=0x5c46b357 Counter=0x00000001} CONFIRMED Client={0x7f7968001660 name=(21:Linux NFSv4.1 client1) refcount=1} t_delta=0 reservations=8 refcount=3} owner=(24:0x6f70656e2069643a0000002c0000000000007d550cff43cd) confirmed=1 seqid=0 refcount=1} refccount=17}
 **ganesha code** 
```
int rc = rgw_write(export->rgw_fs, handle->rgw_fh, offset,
		buffer_size, wrote_amount, buffer,
		(!state) ? RGW_OPEN_FLAG_V3 : RGW_OPEN_FLAG_NONE);

LogFullDebug(COMPONENT_FSAL,
	"%s post obj_hdl %p state %p returned %d", __func__, obj_hdl,
	state, rc);
```
So I don't know why **rc ==-5** . could you please help me analyze it ? maybe this log is missing. if need I will provide a full log.
Many thx

**Comment by Dreamyu20xx** [comment]
hi dang,
I slove it by  using mount cli  with sync  .
**mount -t nfs -o nfsvers=4.1,sync 10.0.98.103:/ /mnt/fs4**
But I feel confused .why async is failed. 
I use async to mount in nfs-cephfs ,it works very well .and it is better than sync innfs-cephfs.Can you give me your opinion about it.
Many thx

**Comment by dang** [comment]
Okay, that makes sense.  I didn't realize (or overlooked) that you were mounted async.  The reason is that RGW isn't a filesystem.  It's an object store, and so it has different rules.  One of these rules is that you can't modify an object, you have to make a new version of the object.  This results in odd interactions with POSIX filesystem clients, especially in the context of async mounts.  You'll always have to mount RGW sync for now.

**Comment by Dreamyu20xx** [comment]
hi,dang
Thanks your reply . I use **dd if=/dev/zero  of=128g bs=1m count=134217728** ,
**result:** 
dd:  error writing 128g Input/Output error
I use strace to get it
**result:**
18:15:37 read(0, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1048576) = 1048576
18:15:37 write(1, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1048576) = -1 EIO (Input/output error)

and bs=4k is no problem I want to know why ?
Many thx

**Comment by mattbenjamin** [comment]
@Dreamyu20xx the minimal requirement from the RGW FSA currently is that the client write strictly sequentially, from offset 0.

**Comment by Dreamyu20xx** [comment]
@mattbenjamin @dang  thank your reply. yesterday I use  **bs=4k,1m,4m** to do it .and result it is that **bs=4m** is more likely to I/O ERROR . and find When the file size is between 0.5g and 1g, dd don't gowrong(**bs=4k,1m**),but **bs=4m** can I/O ERROR . I suspect it's bs and count.(these dd parameter ).

**Comment by Dreamyu20xx** [comment]
ok， I get some rgw log 。I think maybe useful 
`2019-01-29 14:01:21.213468 7fa1e04f5700  5 writess1 failed write at position 17825792 (fails write transaction)
2019-01-29 14:01:21.213525 7fa1e06f7700  5 write ss1 non-0 initial write position 16777216
2019-01-29 14:01:21.213544 7fa1b45f6700  5 write ss1 non-0 initial write position 18874368
2019-01-29 14:01:21.213777 7fa1e05f6700  5 write ss1 non-0 initial write position 19922944`
and rgw **code** is 

if (! f->write_req) {
      /* guard--we do not support (e.g., COW-backed) partial writes */
      if (off != 0) {
	lsubdout(fs->get_context(), rgw, 5)
	  << __func__
	  << " " << object_name()
	  << " non-0 initial write position " << off
	  << dendl;
	return -EIO; //
      }
if (rc == 0) {
      size_t min_size = off + len;
      if (min_size > get_size())
	set_size(min_size);
      if (stateless_open()) {
	/* bump write timer */
	RGWLibFS::write_timer.adjust_event(
	  f->write_req->timer_id, std::chrono::seconds(10));
      }
    } else {
      /* continuation failed (e.g., non-contiguous write position) */
      lsubdout(fs->get_context(), rgw, 5)
	<< __func__
	<< object_name()
	<< " failed write at position " << off
	<< " (fails write transaction) "
	<< dendl;
      /* zap failed write transaction */
      delete f->write_req;
      f->write_req = nullptr;
      rc = -EIO;
    }

**Comment by dang** [comment]
So, what this means is that the transaction associated with the open() ended in the middle of the set of writes.  This can only happen if there's an error during the write, or if a close().  Ganesha only calls close() if the client called close(), so that shouldn't be happening.

Can you turn on FULL_DEBUG on Ganesha, and rerun your test case, and post the logs here?

**Comment by mattbenjamin** [comment]
Note that the above comment about close() applies for nfsv4--that's what's shown above, however.

Matt

**Comment by mattbenjamin** [comment]
@Dreamyu20xx YMMV, but to get a buffer this large, I'd malloc or mmap.

Matt

**Comment by Dreamyu20xx** [comment]
@dang  I see ,I  should invoke close() function to do it. 
@mattbenjamin  that's good idear. 
The reason I tested this was to exclude the impact of client-side writing.  Nfs are not sent to the RGW in order from my previous log .

**Comment by Dreamyu20xx** [comment]
[https://github.com/ceph/ceph/pull/15623](url) ，maybe I should modify the RGW code .

**Comment by dang** [comment]
Work for unordered writes is definitely nice so have.  It's non-trivial, so it hasn't been started yet, but feel free to work on it.

**Comment by mattbenjamin** [comment]
Agree.  The approach proposed in the PR #15623 above is not viable, in my judgement.  Basically what is needed is a robust mechanism that permits immediate write-out of each incoming NFS write, regardless of offset.  The approach I currently favor would require:
1. new prepare-commit-write transaction cycle in the RGW bucket index
1.1 the prepare step would define the RADOS name of corresponding shadow objects
1.2 the commit would be responsible for write-out of a new head object, with correct attribute and manifest
1.3 logic must also be provided for reliable cleanup of shadow objects for write transactions which, for whatever reason (crash?) never commit;  this probably should involve logic similar to the current cleanup of abandoned multipart uploads
2. design and implementation of a satisfying strategy for construction of a final ETAG/checksum for objects on commit;
2.1 Pre-emptively, I think that I cannot be satisfied by a strategy which requires caching entire objects in nfs-ganesha or librgw, in memory or otherwise;  although might seem at first that multipart upload provides a model we could re-used, actually it is just as inconsistent with NFS write sequencing as ordinary upload
2.2 Removal of 2.1 appears to leave:
2.2.1 "eventual" construction of the S3 ETAG with conformant MD5 checksum
2.2.2 immediate construction of the S3 ETAG with conformant MD5 checksum 
2.2.3 alternate algorithm for construction of the ETAG?  
2.2.4 some combination
Matt

**Comment by mattbenjamin** [comment]
updated comment

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
