### ISSUE TITLE
segfault error 14 with glusterfs

### ISSUE THREAD

**Issue by RainerW** [nfs-ganesha/nfs-ganesha#392]
It seems like using the GLUSTER FSAL crashes when at night backups got transfered. This happend now two times, not sure what this means. 

Found #356 which has "error 4" , not sure if this ist similar?

-- 
My last logs lines were all about:

```
21/01/2019 23:25:08 : epoch 5c459a6d : b116-storage-nfs-state2 : ganesha.nfsd-15867[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 13543806, old: 13543805; deq new: 13543802, old: 13543802
```

```
[Jan19 02:33] ganesha.nfsd[15422]: segfault at 0 ip           (null) sp 00007f52653bf518 error 14 in ganesha.nfsd[5653db3fb000+1aa000]
[Jan21 23:59] ganesha.nfsd[16358]: segfault at 0 ip           (null) sp 00007f1bf61cb518 error 14 in ganesha.nfsd[55b405863000+1aa000]
```

```
EXPORT
{
        Export_Id = 5003;
        Path = /sb/dev/state;
        Pseudo = /sb/dev/state;
        Protocols = 3,4;
        CLIENT { # dev IP Pool
          Clients = 192.168.2.0/23;
          Access_Type = RW;
          Squash = All;
          Anonymous_Uid = 6004;
          Anonymous_Gid = 6000;
        }
        Access_Type = None;
        FSAL {
           name = GLUSTER;
           hostname="gluster-test1";
           volume="dev-storage_test";
        }
}
```

Debian 9,  ganesha.nfsd -v > NFS-Ganesha Release = V2.6.3

**Comment by RainerW** [comment]
#356 : adding a / in front of volume="/dev-storage_test" did cause an access denied error on the nfs client side.

**Comment by soumyakoduri** [comment]
can you please collect core and provide backtrace. "volume" should always be absolute name and should n't contain "/". 

In #356  Kaleb was mentioning about "Path" field which should actually be mount path, which in your case is "/dev-storage_test".

**Comment by RainerW** [comment]
Switched to using VFS directly with glusterfs as just a mount. Seems to work. Would this be a valid solution?

Will keep this setup at least over my holiday to see how all servers behave after 2 weeks. So will probably try to get the backtrace in 2-3 weeks ( guess this is how : https://wiki.ubuntu.com/Backtrace#Already_running_programs ?) .

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
