### ISSUE TITLE
  NFS V4 does not support blocking file locks?

### ISSUE THREAD

**Issue by zhanghaozz** [nfs-ganesha/nfs-ganesha#397]

**Comment by zhanghaozz** [comment]
In my test，nfs v3 support blocking lock, but does not support asynchronous blocking lock.  And nfs v4 does not support blocking locks。I looked at the kernel code， it have been implemented in it. Are there any plans for follow-up?

**Comment by zhanghaozz** [comment]
Plus，I use CEPH FSAL.

**Comment by ffilz** [comment]
NFS v4.0 blocking locks are a kludgey thing.

NFS v4.1 blocking locks would be more interesting, and would be worth working on if someone took up the idea.

Async blocking locks require the FSAL or it's underlying filesystem be able to generate upcall notifications that a blocked lock has been granted.

**Comment by zhanghaozz** [comment]
Thanks for your reply. NFS v4.0 blocking locks are a weird thing in kernel，it depend on re-request rather than notify. I will try to implement async blocking locks on NFS v4.1 according to the implement of kernel lately.

**Comment by ffilz** [comment]
Feature request worth being in our backlog somewhere...

**Comment by ffilz** [comment]
Implemented and merged into V6-dev.16
