### ISSUE TITLE
NFS 4.1 server : mandatory session trunking support

### ISSUE THREAD

**Issue by ohault** [nfs-ganesha/nfs-ganesha#398]
Missing documentation about Ganesha NFS4.1 implementation for "Session Trunking" MUST support (see RFC 5661: 2.10.5)

**Comment by ffilz** [comment]
Could you explain more what the perceived failure is here? I'm having trouble understanding the text of that section.

**Comment by ffilz** [comment]
I think we may have some work to do here.

**Comment by ohault** [comment]
Indeed as Session Trunking is a mandatory server feature on the NFS 4.1

**Comment by ffilz** [comment]
New issue raised... Maybe this needs to be worked on...

https://github.com/nfs-ganesha/nfs-ganesha/issues/784

**Comment by ohault** [comment]
Can you please write an implémentation as it is a mandatory feature of NFS4.1 server spec?

**Comment by ffilz** [comment]
> Can you please write an implémentation as it is a mandatory feature of NFS4.1 server spec?

We always welcome additional folks joining us in development. I can only do so much...

**Comment by ohault** [comment]
Any updates about this mandatory feature on server side ?

**Comment by ffilz** [comment]
We have limited resources for development. Looking through RFC 5661, I'm not quite clear on what actually needs to happen here. We do have support for BIND_CONN_TO_SESSION.

Are there any pynfs test cases that test this functionality? Or is there another way to test?

It's possible we can work on this in the near future.

**Comment by ohault** [comment]
Any updates on this ?

**Comment by ffilz** [comment]
There is a patch set up for review on Gerrithub that addresses a bunch of issues, starting with this patch:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1172195/1

I'm not clear if anything else is missing, but I think with that patch set, we should have workable session trunking.

@ohault Are you in a position to verify session trunking?

**Comment by ffilz** [comment]
With the 6.0 release, can we close this?

**Comment by mattbenjamin** [comment]
why don't you think we can close this resolved issue?

**Comment by ffilz** [comment]
Hearing no complaints that it isn't working, I'll close it.

**Comment by ohault** [comment]
This is an unexpected quality practice to close a ticket without a proof of working.

**Comment by mschwenke-ddn** [comment]
@ohault Perhaps you could contribute by doing the testing and sharing the results?  Thanks...

**Comment by ffilz** [comment]
> This is an unexpected quality practice to close a ticket without a proof of working.

There was no response in a reasonable time frame. For quite some time I have been almost the only one responding to github issues (that may be changing as our team has grown) and keeping track of everything has been a challenge. Reducing the number of open issues allows a measure of sanity.

If you would like to verify and find it not working as expected, please re-open.

**Comment by ffilz** [comment]
We very rarely see any response once an issue is tagged "needs verification". I have added tags to improve my sanity on which issues need attention.
