### ISSUE TITLE
mount.nfs: Connection refused

### ISSUE THREAD

**Issue by meirhazonAnyVision** [nfs-ganesha/nfs-ganesha#399]
Hello,
I am using rook and I am getting the following, what is the cause?

Thanks 

ok-nfs-pv
Feb  6 22:19:49 ceph-2 kubelet: Output: Running scope as unit run-17427.scope.
Feb  6 22:19:49 ceph-2 kubelet: mount.nfs: Connection refused
Feb  6 22:19:49 ceph-2 kubelet: E0206 22:19:49.177344   28654 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/nfs/b5860e94-2a5c-11e9-85d8-42010a840fd5-rook-nfs-pv\" (\"b5860e94-2a5c-11e9-85d8-42010a840fd5\")" failed. No retries permitted until 2019-02-06 22:19:50.177295237 +0000 UTC m=+45650.582595199 (durationBeforeRetry 1s). Error: "MountVolume.SetUp failed for volume \"rook-nfs-pv\" (UniqueName: \"kubernetes.io/nfs/b5860e94-2a5c-11e9-85d8-42010a840fd5-rook-nfs-pv\") pod \"wordpress-mysql-5d499f5dcd-5wbjc\" (UID: \"b5860e94-2a5c-11e9-85d8-42010a840fd5\") : mount failed: exit status 32\nMounting command: systemd-run\nMounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/b5860e94-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv --scope -- mount -t nfs -o vers=4.1 10.98.14.12:/nfs-ceph-claim /var/lib/kubelet/pods/b5860e94-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv\nOutput: Running scope as unit run-17427.scope.\nmount.nfs: Connection refused\n\n"
Feb  6 22:19:50 ceph-2 systemd: Started Kubernetes transient mount for /var/lib/kubelet/pods/b5860e94-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv.

 Warning  FailedMount  2m20s  kubelet, ceph-3  MountVolume.SetUp failed for volume "rook-nfs-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/3dfb8666-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv --scope -- mount -t nfs -o vers=4.1 10.98.14.12:/nfs-ceph-claim /var/lib/kubelet/pods/3dfb8666-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv
Output: Running scope as unit run-26565.scope.
mount.nfs: Connection refused
  Warning  FailedMount  2m12s (x5 over 11m)  kubelet, ceph-3  Unable to mount volumes for pod "rook-nfs-0_default(3dfb8666-2a5c-11e9-85d8-42010a840fd5)": timeout expired waiting for volumes to attach or mount for pod "default"/"rook-nfs-0". list of unmounted volumes=[nfs-ceph-claim]. list of unattached volumes=[nfs-ceph-claim nfs-ganesha-config default-token-9ns5x]
  Warning  FailedMount  2s                   kubelet, ceph-3  MountVolume.SetUp failed for volume "rook-nfs-pv" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/3dfb8666-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv --scope -- mount -t nfs -o vers=4.1 10.98.14.12:/nfs-ceph-claim /var/lib/kubelet/pods/3dfb8666-2a5c-11e9-85d8-42010a840fd5/volumes/kubernetes.io~nfs/rook-nfs-pv
Output: Running scope as unit run-26987.scope.
mount.nfs: Connection refused

**Comment by dang** [comment]
The rook mount attempt cannot connect to the Ganesha.  Either kube hasn't set up the network properly, so it's not connected, or ganesha is mis-configured, so that the client is trying to mount something that Ganesha isn't exporting.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
