### ISSUE TITLE
Better check if system supports file handle

### ISSUE THREAD

**Issue by odoucet** [nfs-ganesha/nfs-ganesha#40]
When using Ganesha on a kernel without CONFIG_FHANDLE, error in log is not very understandable : 
ganesha.nfsd-15726[main] vfs_create_export :FSAL :MAJ :vfs_fd_to_handle: root_path: /tmp, root_fd=4, errno=(38) Function not implemented

It would be great to have a better error code : maybe doing a specific test at launch ?

**Comment by ffilz** [comment]
Please report this in

https://bugzilla.redhat.com/enter_bug.cgi?product=nfs-ganesha

and close this issue.
