### ISSUE TITLE
Issuing filelocks over NFSv4 against a GLUSTER FSAL leaks fds on the bricks and memory on nfs-ganesha

### ISSUE THREAD

**Issue by teizz** [nfs-ganesha/nfs-ganesha#404]
When a file is opened, and a lock acquired, find_fd is called by glusterfs_lock_op2 to fetch the status of the fd. It in turn calls fsal_find_fd in the FSAL commonlib, and passes the open_for_locks boolean along as it got it.

Back in commit https://github.com/nfs-ganesha/nfs-ganesha/commit/365d7cb28ef09612df42c42a98f123c44b08df30 the following lines were changed to not always set open_for_locks to true, but have it rely on whether a state exists and if it is either a STATE_TYPE_NLM_LOCK or STATE_TYPE_9P_FID.
https://github.com/nfs-ganesha/nfs-ganesha/blob/c2da133a212eb2dca5e6623d5d7635a0d45292f7/src/FSAL/FSAL_GLUSTER/handle.c#L2368-L2372

A problem arises when using NFSv4 because this does not in fact use NLM locks. The result is that nfs-ganesha treats the lock as coming an FSAL that doesn't "bother with opening a separate file for the lock state". Although locking seems to work, this leaks a bit of memory on the ganesha.nfsd process and the glusterfsd ends up never closing the separate file. Sooner or later one of either 3 things happen:
* nfs-ganesha runs out of memory
* glusterfsd runs out of open file descriptors
* the node running the glusterfsd process runs out of global open file descriptors (gluster's open-file limit typically is set to 1<<20 but the sysctl fs.file-max might be a lot lower depending on the amount of memory in the node).

From my tests the following patch solves this issue:
```
diff --git a/src/FSAL/FSAL_GLUSTER/handle.c b/src/FSAL/FSAL_GLUSTER/handle.c
index 3a610051e..87aeaad36 100644
--- a/src/FSAL/FSAL_GLUSTER/handle.c
+++ b/src/FSAL/FSAL_GLUSTER/handle.c
@@ -2369,6 +2369,7 @@ static fsal_status_t glusterfs_lock_op2(struct fsal_obj_handle *obj_hdl,
                         &has_lock, &closefd,
                         (state &&
                          ((state->state_type == STATE_TYPE_NLM_LOCK) ||
+                         (state->state_type == STATE_TYPE_LOCK) ||
                          (state->state_type == STATE_TYPE_9P_FID))));
 
        if (FSAL_IS_ERROR(status)) {
```

It's probably easier for everybody to submit this an issue rather than going through the whole gerrithub and hook stuff for a single line. Plus this is the first time going over any of this code for me, so I'd appreciate someone actually familiar with it to double-check my rationale.

Cheers!

**Comment by soumyakoduri** [comment]
hi,
we just have a fix proposed to fix this issue - https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/446592.
 please check if it works for you

**Comment by teizz** [comment]
Yes, that proposed fix works as well! I suppose my suggestion resulted in a workaround where it would not hit the bug in the code anymore?

**Comment by soumyakoduri** [comment]
As mentioned in commit 365d7cb ,  FSAL_GLUSTER cannot have separate fd for NFSv4 lock_state. This is  to prevent any race of file being removed at the backend which may result in ENOENT error for lock operation on an already opened file.

**Comment by soumyakoduri** [comment]
So yes, I guess suggested workaround would bring back that issue quoted in that commit.

**Comment by teizz** [comment]
Thanks for clearing that up! I can also confirm that the latest RHGS with nfs-ganesha-2.5.5-11.el7rhgs has this issue and that backporting the freeing of the duped fd resolves the issue there too.

Cheers!
