### ISSUE TITLE
Gluster GEO replication fault after write over nfs-ganesha

### ISSUE THREAD

**Issue by ruatag** [nfs-ganesha/nfs-ganesha#408]
2 gluster dispersed volumes (2+1) TEST / SLAVE
latest gluster 5.5 nfs-ganesha 2.7.2 from CentOS 7 repositories
Everything setup according official documentation, only changed config use-meta-volume true 
Works as expected
But as 1 file written over nfs-ganesha replication goes to Fault and gsyncd fail with error
```
OSError: [Errno 61] No data available: '.gfid/9c9514ce-a310-4a1c-a87b-a800a32a99f8' 
```
but if I check over glusterfs mounted with aux-gfid-mount
```
getfattr -n trusted.glusterfs.pathinfo -e text /mnt/TEST/.gfid/9c9514ce-a310-4a1c-a87b-a800a32a99f8
getfattr: Removing leading '/' from absolute path names
# file: mnt/TEST/.gfid/9c9514ce-a310-4a1c-a87b-a800a32a99f8
trusted.glusterfs.pathinfo="(<DISTRIBUTE:TEST-dht> (<EC:TEST-disperse-0> <POSIX(/srv/TEST):sog-gl-m2.avp.ru:/srv/TEST/kapacitor.tar>))"
```
File exist

[ganesha.conf.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/3012892/ganesha.conf.txt)
[status.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/3011958/status.txt)
[getfattr.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/3011959/getfattr.txt)
[master-gsyncd.log](https://github.com/nfs-ganesha/nfs-ganesha/files/3011960/master-gsyncd.log)
[master-status.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/3011961/master-status.txt)
[slave-gsyncd.log](https://github.com/nfs-ganesha/nfs-ganesha/files/3011962/slave-gsyncd.log)
[slave-status.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/3011963/slave-status.txt)

**Comment by soumyakoduri** [comment]
Since this question seems more related to gluster geo-rep feature, could you please post this issue in gluster-users@gluster.org mailing list. Most of the gluster developers are on that mailing list and you could get apt response.

**Comment by ruatag** [comment]
No problem to use glusterfs-fuse, probably something written to gluster over nfs-ganesha in a way that produced this problem. But can be an interaction problem
I will post to gluster-user

**Comment by ffilz** [comment]
Doesn't seem to be a Ganesha issue, closing.
