### ISSUE TITLE
question about split chunk->dirents into split->dirents in place_new_dirent

### ISSUE THREAD

**Issue by yangruifeng** [nfs-ganesha/nfs-ganesha#410]
hi, all
why not set the chunk of splited dirents to split_chunk? (mdcache_dir_entry_t::chunk)
https://github.com/nfs-ganesha/nfs-ganesha/blob/74222f618b4b958f67d9e1ecd6884ea463808a16/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c#L2007-L2018

like this
`

		glist_for_each(glist, &split->dirents) {
			split_dir_entry = glist_entry(glist,
					   mdcache_dir_entry_t,
					   chunk_list);
			split_dir_entry->chunk = split;
		}

`

it may cause two problem

`
 
1: (()+0x5c4222) [0x7ff4bf68b222]
 2: (()+0xf5e0) [0x7ff4bd6745e0]
 3: (gsignal()+0x37) [0x7ff4bc92e1f7]
 4: (abort()+0x148) [0x7ff4bc92f8e8]
 5: (()+0x2e266) [0x7ff4bc927266]
 6: (()+0x2e312) [0x7ff4bc927312]
 7: (place_new_dirent()+0xc2e) [0x5595cd]
 8: (mdcache_dirent_add()+0x1f3) [0x558049]
 9: (mdcache_alloc_and_check_handle()+0x11d) [0x549139]
 10: /usr/bin/ganesha.nfsd() [0x549857]
 11: (fsal_create()+0x203) [0x433e33]
 12: (nfs3_mkdir()+0x313) [0x49237a]
 13: /usr/bin/ganesha.nfsd() [0x45c9df]
 14: (nfs_rpc_valid_NFS()+0x11d) [0x45d19e]
 15: (()+0x2a2a1) [0x7ff4bd23c2a1]
 16: /usr/bin/ganesha.nfsd() [0x450146]
 17: (()+0x2a1b2) [0x7ff4bd23c1b2]
 18: (()+0x2699e) [0x7ff4bd23899e]
 19: (()+0x26e18) [0x7ff4bd238e18]
 20: (()+0x270ba) [0x7ff4bd2390ba]
 21: (()+0x2716d) [0x7ff4bd23916d]
 22: (()+0x3025a) [0x7ff4bd24225a]
 23: (()+0x7e25) [0x7ff4bd66ce25]
 24: (clone()+0x6d) [0x7ff4bc9f134d]

`

if chuk->next == next_ck, then endless loop

https://github.com/nfs-ganesha/nfs-ganesha/blob/74222f618b4b958f67d9e1ecd6884ea463808a16/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c#L2391-L2403

**Comment by dang** [comment]
You're right, this is a bug.  Feel free to submit a patch.  If you don't, I'll do it when I get a chance.

**Comment by yangruifeng** [comment]
thank you for your quick reply.
It would be great if you could help submit it, thanks.

**Comment by dang** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/454777

**Comment by ffilz** [comment]
Closing as resolved.
