### ISSUE TITLE
Ganesha (2.7.1) segfaults using Gluster FSAL

### ISSUE THREAD

**Issue by Wmyers559** [nfs-ganesha/nfs-ganesha#411]
Hello,

We seem to be having a reasonably interesting issue, which is that `nfs-ganesha` seems to be encountering segmentation faults while running with a Gluster backend (Gluster 5.3) on CentOS 7.6.1810 (Core). 

Similar to #392, we get `error 14`, but we additionally get `error 4`. From Ganesha itself, for the last two crashes listed in dmesg, with log level DEBUG, we get: [ganesha.log](https://gist.github.com/Wmyers559/53f5a57db507a0924505a4663cc76960).

This shows up in `dmesg` as 
``` 
[1257606.023829] ganesha.nfsd[21982]: segfault at 28 ip 00007f09090543d2 sp 00007f075dcf0460 error 4 in libntirpc.so.1.7.1[7f090902b000+3d000]
...
[1305709.486143] ganesha.nfsd[7227]: segfault at 0 ip           (null) sp 00007f644aefc458 error 14 in ganesha.nfsd[555dcef59000+1b6000]
...
[1313704.631648] ganesha.nfsd[20481]: segfault at 50 ip 000055fdfd18ea55 sp 00007f33ceffbe00 error 4 in ganesha.nfsd[55fdfd0e5000+1b6000]
```

The `ganesha.conf` exports looks like:
```
EXPORT {
    Export_Id = 2;
    Path = /user;
    Pseudo = /user;
    Transports = UDP, TCP;

    FSAL {
        name = GLUSTER;
        hostname = localhost;
        volume = /user;
    }

    Disable_ACL = true;
    Protocols = 3,4;

    CLIENT {
        Clients = 192.168.0.140;
        Access_type = RW;
        Squash = No_Root_Squash;
        SecType = sys;
    }
    CLIENT {
        Clients = 192.168.0.215;
        Access_type = RW;
        Squash = No_Root_Squash;
        SecType = sys;
    }

    CLIENT {
        Clients = 192.168.0.110;
        Access_type = RW;
        Squash = None;
        SecType = sys;
    }

    CLIENT {
        Clients = 192.168.0.0/24;
        Access_type = RW;
        Squash = Root;
        SecType = krb5p;
    }
}
```

Any ideas for what is occurring? We will try to get a core dump when we get a chance, but we will see.

**Comment by Wmyers559** [comment]
An additional point to note is that almost all of our active clients are using NFSv3 to access this server, as we had been having problems with ACLs seeming to be enabled despite the configuration.

**Comment by dang** [comment]
Unfortunately, without a backtrace, there isn't much we can tell, other than that its's crashing somewhere in ntirpc.  So please work on getting a backtrace.

I suppose you could use gdb to load the binary and print the addresses that are crashing in the log.  That might at least give us a codepoint.

**Comment by soumyakoduri** [comment]
> An additional point to note is that almost all of our active clients are using NFSv3 to access this server, as we had been having problems with ACLs seeming to be enabled despite the configuration.

could you please provide details about your workload (like if it involves locks)? Does it crash during any particular I/O? Also if "Disable_ACL = true;" is set, ACLs should be disabled. If not its a bug then. Were you able to set ACLs even when this config option is set?

**Comment by pasikarkkainen** [comment]
@Wmyers559 : Did you try with the latest versions? In 5.x branch glusterfs v5.8 has been released recently, and also nfs-ganesha V2.7.6. Please try with those versions and please let us know if it works better!

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Comment by desertsagebrush** [comment]
Unfortunately, there was a change in which group was managing the servers in question, and they have moved to utilizing other software. :/

Sorry that I wasn't able to get a core dump before they nuked the OS. Closing this is a good plan.
