### ISSUE TITLE
CentOS SIG (storage interest group) repository broken

### ISSUE THREAD

**Issue by fbezdeka** [nfs-ganesha/nfs-ganesha#413]
The CentOS Storage Special Interest Group (SIG) (please see [1] for more details) offers  a CentOS package called `centos-release-gluster41` that installs the necessary yum configuration files for finding the repository.

The SIG repository located at [2] is currently broken.
The ganesha package was updated to version 2.7.3 on 12th of April. This version depends on libntirpc-1.7.3 but version 1.7.3 is missing in the repository.

Seems that someone forgot to update the libntirpc package as well.

Who is the right one to contact regarding this issue?

A community build for the missing package is available at [3]. So manually updating the ganesha package may work.

[1] https://wiki.centos.org/SpecialInterestGroup/Storage
[2] http://mirror.centos.org/centos/7.6.1810/storage/x86_64/gluster-4.1/
[3] https://cbs.centos.org/koji/buildinfo?buildID=25653

**Comment by kalebskeithley** [comment]
-release tags added
