### ISSUE TITLE
v2.7-stable build failure in centos 7.6

### ISSUE THREAD

**Issue by techie879** [nfs-ganesha/nfs-ganesha#415]
Hi, 

We back on building an NFS server, running with ganesha.  It looks like version 2.7 seems to be the current stable branch.

I have a few questions, if you don't mind -- 

make crashes with the following error:

[ 93%] Building C object MainNFSD/CMakeFiles/MainServices.dir/nfs_rpc_dispatcher_thread.c.o
/root/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c: In function ‘nfs_Init_svc’:
/root/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1087:12: error: ‘svc_init_params’ has no member named ‘request_cb’
  svc_params.request_cb = nfs_rpc_decode_request;
            ^
make[2]: *** [MainNFSD/CMakeFiles/MainServices.dir/nfs_rpc_dispatcher_thread.c.o] Error 1
make[1]: *** [MainNFSD/CMakeFiles/MainServices.dir/all] Error 2
make: *** [all] Error 2

I am using all the default options, stock gcc 4.8.5 , didn't change anything .  latest v2.8-dev28 compiles without issues.

Is the v2.7-dev28 safe to use in production?  If not, can you suggest a fix for v2.7?

this is what I did to pull down v2.7 .

[root@nas-10-2 ~]# git clone --recursive https://github.com/nfs-ganesha/nfs-ganesha.git
Cloning into 'nfs-ganesha'...
remote: Enumerating objects: 128086, done.
remote: Total 128086 (delta 0), reused 0 (delta 0), pack-reused 128086
Receiving objects: 100% (128086/128086), 102.58 MiB | 15.67 MiB/s, done.
Resolving deltas: 100% (103194/103194), done.
Submodule 'src/libntirpc' (https://github.com/nfs-ganesha/ntirpc.git) registered for path 'src/libntirpc'
Cloning into 'src/libntirpc'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 47693 (delta 30), reused 24 (delta 14), pack-reused 47641
Receiving objects: 100% (47693/47693), 58.07 MiB | 14.06 MiB/s, done.
Resolving deltas: 100% (36996/36996), done.
Submodule path 'src/libntirpc': checked out '52bb2d5df75b798b9e80f3417ab8880b5895dc36'

[root@nas-10-2 nfs-ganesha]# git checkout V2.7-stable
M       src/libntirpc
Branch V2.7-stable set up to track remote branch V2.7-stable from origin.
Switched to a new branch 'V2.7-stable'

Thanks for your help

**Comment by dang** [comment]
When you check out the 2.7 branch, you have to update the ntirpc submodule:
git submodule update
You can tell you need to do this because of this line from your output:
M src/libntirpc
In general, you'll need to do this when switching branches on Ganesha.

**Comment by techie879** [comment]
thanks a lot, that helped!
