### ISSUE TITLE
segmentation fault in dupreq free

### ISSUE THREAD

**Issue by jasonsung1** [nfs-ganesha/nfs-ganesha#418]
code:
func = nfs_dupreq_func(dv);
func->free_function(dv->res);
if  nfs_dupreq_func return NULL, func->free_function may coredump when access null pointer。

**Comment by malahal** [comment]
nfs_dupreq_func() is not supposed to return a NULL pointer. Do you have a case where it is returning NULL (it should log Major error if it returns NULL, based on the code reading)?

**Comment by malahal** [comment]
What are values for  dv->hin.rq_proc and dv->hin.rq_prog at crash time? Also, what release are you using?

**Comment by ffilz** [comment]
This is old and I know we've had some fixes. Feel free to re-open if this actually is still an issue.
