### ISSUE TITLE
the main process of nfs-ganesha(2.7.3) will exit

### ISSUE THREAD

**Issue by renhwztetecs** [nfs-ganesha/nfs-ganesha#419]
* server info：nfs-ganesha-2.7.3 ceph14.2.1
* client info：nfs-utils-1.3.0 and On the same node, use the same mount point and mount 
  it to 2 directories, as follows: 

  > 100.100.5.101:/testdir2 on /mnt/test1 type nfs4 (rw,relatime,sync,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,noac,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=100.100.5.115,local_lock=none,addr=100.100.5.101)
100.100.5.101:/testdir2 on /mnt/test2 type nfs4 (rw,relatime,sync,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,noac,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=100.100.5.115,local_lock=none,addr=100.100.5.101)

* test tool info: vdbench
* error info(no coredump info):
  1.message(operation system):
     
  > May 11 13:53:18 host-192-168-5-101 systemd[1]: nfs-ganesha.service: main process 
     exited, code=killed, status=6/ABRT
     May 11 13:53:18 host-192-168-5-101 systemd[1]: Unit nfs-ganesha.service entered 
     failed state.
     May 11 13:53:18 host-192-168-5-101 systemd[1]: nfs-ganesha.service failed.

  2.nfs-ganesha log(stop in the nfs cache):
    
    > 11/05/2019 13:53:18 : epoch 5cd66307 : host-192-168-5-101 : ganesha.nfsd-3132634[svc_16] get_mounted_on_fileid :RW LOCK :F_DBG :Got read lock on 0x2725348 (&op_ctx->ctx_export->lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.3/Protocols/NFS/nfs_proto_tools.c:3412
11/05/2019 13:53:18 : epoch 5cd66307 : host-192-168-5-101 : ganesha.nfsd-3132634[svc_16] get_mounted_on_fileid :RW LOCK :F_DBG :Unlocked 0x2725348 (&op_ctx->ctx_export->lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.3/Protocols/NFS/nfs_proto_tools.c:3426
11/05/2019 13:53:18 : epoch 5cd66307 : host-192-168-5-101 : ganesha.nfsd-3132634[svc_16] mdcache_getattrs :RW LOCK :F_DBG :Got read lock on 0x7f0e680745b0 (&entry->attr_lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:887
11/05/2019 13:53:18 : epoch 5cd66307 : host-192-168-5-101 : ganesha.nfsd-3132634[svc_16] mdcache_getattrs :RW LOCK :F_DBG :Unlocked 0x7f0e680745b0 (&entry->attr_lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:895
11/05/2019 13:53:18 : epoch 5cd66307 : host-192-168-5-101 : ganesha.nfsd-3132634[svc_16] mdcache_getattrs :RW LOCK :F_DBG :Got write lock on 0x7f0e680745b0 (&entry->attr_lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:896

**Comment by renhwztetecs** [comment]
maybe mdcache deadlock problem

**Comment by dang** [comment]
An ABRT should have generated a core file.  Is there no way to get that?  Without it, we can't know what's going on.

Maybe a FULL_DEBUG log might show more, but all we have right now is successful operations.

**Comment by skyatlantis** [comment]
thank you@dang
I will pay attention to whether there is a coredump file when there is an error.

**Comment by renhwztetecs** [comment]
thank you@dang
I will pay attention to whether there is a coredump file when there is an error.

**Comment by malahal** [comment]
Make sure you have abrt components installed to get coredump though (abrt-cli package what I usually install). If you build your own Ganesha packages, then it needs a little more work!

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
