### ISSUE TITLE
mount(2): Operation not permitted /  access denied by server while mounting...

### ISSUE THREAD

**Issue by alex-caelus** [nfs-ganesha/nfs-ganesha#420]
Hi all!

I've been attempting to mount a nfs share on my proxmox host while nfs-ganesha is running inside an LXC container. I have tested both privileged and unprivileged (no difference).

The LXC container is running ubuntu 18.04 LTS and the relevant configurations are as follows. (You should note that I have tried multiple variations of the configuration, this is just the example which matches with this particular debug log, the container was currently running as unpriviliged).

And yes, I have tried with both NFSv3 and NFSv4.

```
# mount
zfs/subvol-109-disk-0 on / type zfs (rw,xattr,posixacl)
zfs/subvol-109-disk-1 on /media/backups type zfs (rw,xattr,posixacl)
...
```

```
# cat /etc/ganesha/ganesha.conf
LOG {
        ## Default log level for all components
        #Default_Log_Level = FullDebug;

        ## Configure per-component log levels.
        COMPONENTS  {
                FSAL = FULL_DEBUG;
                NFS4 = FULL_DEBUG;
                EXPORT = FULL_DEBUG;
        }

        ## Where to log
        #Facility {
        #        name = FILE;
        #        destination = "/var/log/ganesha/ganesha.log";
        #        enable = active;
        #        MAX_LEVEL = FULL_DEBUG;
        #        header = all;
        #}
}


NFS_Core_Param {
        Bind_addr=0.0.0.0;
        NFS_Port=2049;
        MNT_Port=20048;
        NLM_Port=38468;
        Rquota_Port=4501;
}


EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 77;

        # Exported path (mandatory)
        Path = /media/backups;

        # Pseudo Path (required for NFS v4)
        Pseudo = /backups;

        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = RW;

        # Exporting FSAL
        FSAL {
                Name = VFS;
        }

        Protocols = NFSV4;

        Transports = TCP;

        Squash = No_Root_Squash;

        SecType = "sys";
}
```

Debug logs are here (too big for pasting): https://pastebin.com/8c5k7uK3

The ouput from the client (as root on the proxmox host, outside the container):
```
# mount.nfs -v backup-gw:/backups /media/ -o defaults,vers=4
mount.nfs: timeout set for Sat May 11 22:10:13 2019
mount.nfs: trying text-based options 'vers=4,addr=192.168.1.109,clientaddr=192.168.1.51'
mount.nfs: mount(2): Operation not permitted
mount.nfs: trying text-based options 'addr=192.168.1.109'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 192.168.1.109 prog 100003 vers 3 prot TCP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 192.168.1.109 prog 100005 vers 3 prot UDP port 59360
mount.nfs: mount(2): Permission denied
mount.nfs: access denied by server while mounting backup-gw:/backups
```

**Comment by dang** [comment]
/media/backup failed to open:
find_fd :FSAL :DEBUG :Failed with Operation not permitted openflags 0x00000020
So not even "root" inside the container has permissions to access that path.

**Comment by alex-caelus** [comment]
what operation is that exactly? because I can cd and create files and stuff on the command line for that path no problem...

**Comment by dang** [comment]
Is that inside the container?

**Comment by alex-caelus** [comment]
Yes, that is inside the container.

Okay, is there something I can do to provide more information about this? Is it easy to write a 20 line C-program with that syscall that I can use to test and maybe use to provide more information? Or something... I don't know.

This is a ZFS subvolume provided solely for this container, might that have something to do with this?

**Comment by dang** [comment]
Ganesha on ZFS is not well tested, since it's not in the kernel, but as far as I know, it should support open_by_handle_at().

You can see the code Ganesha uses for file handles at src/FSAL/FSAL_VFS/os/linux/linux_syscalls.c You'll likely want to look at vfs_name_to_handle(), vfs_fd_to_handle(), and vfs_open_by_handle().

**Comment by davemc50** [comment]
You also need to turn off seccomp in /etc/pve/lxc/___.conf
lxc.seccomp.profile =
as discussed [here](https://discuss.linuxcontainers.org/t/nfs-ganesha-in-lxc/2401) by lxc maintainer Stéphane Graber, because nfs-ganesha
uses `vfs_open_by_handle` and `open_by_handle_at` which the default seccomp profile does not allow.
Undoes lots of security protection goodness, but makes nfs-ganesha work on proxmox.

**Comment by alex-caelus** [comment]
This is great! I do not really have the time to test this solution, but after reading the comments in your link I feel confident that it should resolve the issue. You could probably close this issue now, if you want... but perhaps some documentation about this might also be in order?

**Comment by ffilz** [comment]
Looks like maybe some documentation needed here? I'm not sure where to put it though... We don't really support ZFS even if it can be exported via FSAL_VFS.

**Comment by zssfred** [comment]
So what is the best supported FSAL? CephFS?

Thanks.

Fred

Frank Filz <notifications@github.com>于2020年6月18日 周四上午7:37写道：

**Comment by dang** [comment]
Most FSALs are fully supported at this point with a few exceptions.
FSAL_VFS is supported, but currently only tested with XFS and EXT4 as backing stores
FSAL_PANFS is not supported at all
FSAL_XFS is not really tested, as modern XFS works correctly with FSAL_VFS
FSAL_LUSTER is partially supported (the maintainers are mostly AFK, but show up occasionally)
FSAL_LIZARDFS has it's own upstream, but gets periodically merged
The rest of the FSALS all have active maintainers who contribute regularly.

**Comment by zssfred** [comment]
How about FSAL_ZFS? Is OpenZFS or FUSE-ZFS?

Thanks.

Fred

Daniel Gryniewicz <notifications@github.com>于2020年6月18日 周四下午11:46写道：

**Comment by dang** [comment]
There's no FSAL_ZFS in the current tree.  It was removed before 2.6 was released.

**Comment by zssfred** [comment]
See.

Thanks.

Fred

**Comment by ffilz** [comment]
Closed as something we don't have resources to address.
