### ISSUE TITLE
Compiling gtest error

### ISSUE THREAD

**Issue by zanglinjie** [nfs-ganesha/nfs-ganesha#421]
hi，
What version of gcc-c++ does compiling gtest require？
How to Compile and Run gtest ？  

------------
nfs-ganesha has a few dependencies. On a red-hat based linux distribution, this should be enough for most of it:

 # Common things
 yum install gcc git cmake autoconf libtool bison flex
 # More nfs-ganesha specific
 yum install libgssglue-devel openssl-devel nfs-utils-lib-devel doxygen redhat-lsb gcc-c++

**Comment by zanglinjie** [comment]
My gcc version 4.8.5 （red-hat） .

**Comment by dang** [comment]
We don't have any requirements that I'm aware of; the GTest framework might have some.  The oldest G++ I have lying around is 6.3.1-1, but I'm pretty sure I've used some older than that.

**Comment by ffilz** [comment]
Closing as won't fix.
