### ISSUE TITLE
under ganeshaV2.5.0, client mount process is stuck in D state

### ISSUE THREAD

**Issue by Davidrjx** [nfs-ganesha/nfs-ganesha#423]
In the whole, my use case is ganesha nfs over ceph RBD. Specifically,  nfs-ganesha data export is placed into Ceph RBD volume in kubernetes and data export is bound to persistent volume in kubernetes. 

The problem is that after most pods with persistent volume are scheduled to a certain node, mount.nfs mount process is stuck in D state.

Any ideas?

**Comment by malahal** [comment]
It is odd that mount.nfs is stuck (usually it should come out). You can try "tcpdump" and see what is happening between your client and your server. Doing "tcpdump -i any -w /tmp/mount.cap host <IP-address-of-server>" on your client while the mount hangs should help. Of course, you need to analyse mount.cap using wireshark.

**Comment by Davidrjx** [comment]
@malahal first thanks for you reply.
really odd as occasionally mount op is ok. 
by tcpudump, unluckily i can not capture any packages to nfs-ganesha server.
at my case, a client's pending process looks like the following snippets
```
root     21626  0.0  0.0  29232  1232 ?        S    May15   0:00 /bin/mount -t nfs -o hard,retrans=2,rsize=1048576,timeo=600,vers=4.1,wsize=1048576 *.*.*.*.*:/ /var/lib/kubelet/pods/59a800cc-7717-11e9-9033-e4434b09762c/volumes/kubernetes.io~nfs/plugin-88816
root     21629  0.0  0.0  42336  1784 ?        D    May15   0:00 /sbin/mount.nfs *.*.*.*.*:/ /var/lib/kubelet/pods/59a800cc-7717-11e9-9033-e4434b09762c/volumes/kubernetes.io~nfs/plugin-88816 -o rw,hard,retrans=2,rsize=1048576,timeo=600,vers=4.1,wsize=1048576
```

**Comment by dang** [comment]
So, -i any should capture all packets to/from the pod, regardless of address.  It may be hard to run a tcpdump inside the pod; it may require modifying the pod itself.

Can you turn on FULL_DEBUG on Ganesha and get the logs?  That might be useful.

One possibility I can think of is that some pods don't have the network set up correctly.  A mis-configured firewall would cause this, so I suspect that kube could set things up in the same way.

**Comment by Davidrjx** [comment]
@dang hi, pod network setup can be ignorable. when node rebooting where pending mount.nfs resides in , problem got solved but i think it was temporary.

My local environment:
nfs-ganesha version: 2.5.0 from mitcdh/nfs-ganesha:2.5 image
linux: 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

**Comment by dang** [comment]
Thanks for the update.

**Comment by Davidrjx** [comment]
@dang hi, above problem arises again and yet need your ideas.
 At the node where mount process got stuck in, instead of kuberntes pods pvc, manually executing the following same line in two cases where either vers=4.1 or 4.0, i capture network traffic in nfs-ganesha server pod by "tcpdump -i any  -w ganesha.pcap".
```
sudo /sbin/mount.nfs 10.111.9.*:/ /var/lib/kubelet/pods/7b557afb-7b7a-11e9-9033-e4434b09762c/volumes/kubernetes.io~nfs/config-815 -o  rw,hard,retrans=2,rsize=1048576,timeo=600,vers=[4.1|4.0],wsize=1048576
```
in which 10.111.9.* is a kubernetes service IP for nfs-ganesha server. 
below, i just pasted screenshots, sorry about that. 
Case 1 with 4.1(Failed but pending):
![image](https://user-images.githubusercontent.com/4284791/58071556-aea4e680-7bcf-11e9-9792-4f8dcad26d82.png)
![image](https://user-images.githubusercontent.com/4284791/58071606-d136ff80-7bcf-11e9-81a6-9ef49a0c156c.png)

Case 2(Normal):
![image](https://user-images.githubusercontent.com/4284791/58071468-61287980-7bcf-11e9-8d8d-02485c588a65.png)

**Comment by dang** [comment]
So Ganesha is seeing the message, and sending a reply, but the reply may not be getting through.  Could you attach the pcap file so I can examine it?

**Comment by Davidrjx** [comment]
[tmp1.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/3209997/tmp1.zip)
some sensitive packages were filtered.

**Comment by dang** [comment]
Thanks.  This is not hugely helpful.  The NULL reply definitely gets through, since it's ACK'd.  However, the client never sends the next packet (which should be a CREATE_SESSION).  This means that NFSv4 itself isn't filtered by port, but something is blocking traffic somewhere. 

I'm sorry, but my knowledge of kubernetes is not very good at this point.  I'll ping @jtlayton , who has done the most work with kubernetes and Ganesha at this point, but it may be necessary to take this issue to the kubernetes people.

**Comment by jtlayton** [comment]
I agree with @dang that none of this is terribly helpful. Your mount command shows 10.111.9.* , but the capture doesn't show a server address like that -- only 192.168.56.113. Are you sure you're talking to the right host?

**Comment by Davidrjx** [comment]
thank both @dang and @jtlayton . About above 10.111.9.* ,  it is service ip of nfs-ganesha server instead of pod ip.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
