### ISSUE TITLE
how to compile gtest

### ISSUE THREAD

**Issue by YaqiZhang-UESTC** [nfs-ganesha/nfs-ganesha#424]
hi ,I tried to compile gtest few times but all failed, i was really confused where the problems were and how to compile gtest? any suggestions will be thankful.
here are the imformation about cmake ../src   and make 
- [root@localhost build]# cmake ../src/
-- cmake version 2.8
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected an UNKNOWN Linux machine
-- toolchain options processed
CMake Warning at cmake/maintainer_mode.cmake:45 (message):
  CMAKE_BUILD_TYPE is not set, defaulting to Debug
Call Stack (most recent call first):
  CMakeLists.txt:120 (include)

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Outside a git repository, use saved data
-- Looking for lttng executable...
-- Found LTTng: /usr/local/include  
-- Found Gperftools: /lib64/libprofiler.so  
-- Found GTest: /usr/local/lib64/libgtest.a;/usr/local/lib64/libgtest_main.a  
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   filesystem
--   program_options
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- Looking for include file gssapi.h
-- Looking for include file gssapi.h - found
-- Looking for llapi_hsm_state_get_fd in lustreapi
-- Looking for llapi_hsm_state_get_fd in lustreapi - not found
CMake Warning at CMakeLists.txt:582 (message):
  Cannot find lustreapi.  We will only build a dummy lustre fsal.

-- 
-- Looking for ceph_ll_lookup in cephfs
-- Looking for ceph_ll_lookup in cephfs - not found
-- Found cephfs libraries: CEPHFS_LIBRARY-NOTFOUND
-- Could NOT find CEPHFS (missing:  CEPHFS_INCLUDE_DIR CEPHFS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:592 (message):
  Cannot find CEPH runtime.  Disabling CEPH fsal build

-- Looking for open_by_handle in handle
-- Looking for open_by_handle in handle - not found
-- Looking for include file xfs/xfs.h
-- Looking for include file xfs/xfs.h - not found
CMake Warning at CMakeLists.txt:615 (message):
  Cannot find XFS runtime.  Disabling XFS build

-- checking for module 'glusterfs-api>=7.3.10.7'
--   package 'glusterfs-api>=7.3.10.7' not found
CMake Warning at CMakeLists.txt:636 (message):
  Cannot find GLUSTER GFAPI runtime.  Disabling GLUSTER fsal build

-- Looking for rgw_mount in rgw
-- Looking for rgw_mount in rgw - not found
-- Found rgw libraries: RGW_LIBRARY-NOTFOUND
-- Could NOT find RGW: Found unsuitable version "0.0.0", but required is at least "1.1.6" (found )
CMake Warning at CMakeLists.txt:716 (message):
  Cannot find supported RGW runtime.  Disabling RGW fsal build

-- Could NOT find JeMalloc (missing:  JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:730 (message):
  jemalloc not found, falling back to libc

-- checking for module 'dbus-1'
--   package 'dbus-1' not found
CMake Warning at CMakeLists.txt:783 (message):
  Cannot find DBUS libs.  Disabling DBUS support

CMake Warning at CMakeLists.txt:799 (message):
  libnfsidmap not found, disabling USE_NFSIDMAP

-- Looking for wbcLookupSids in wbclient
-- Looking for wbcLookupSids in wbclient - not found
-- Winbind4 client not found /lib
CMake Warning at CMakeLists.txt:826 (message):
  Samba 4 wbclient not found.  Disabling MSPAC_SUPPORT

-- Looking for lttng executable...
-- Looking for rados_read_op_omap_get_vals2 in rados
-- Looking for rados_read_op_omap_get_vals2 in rados - not found
-- Found rados libraries: RADOS_LIBRARY-NOTFOUND
-- Could NOT find RADOS (missing:  RADOS_INCLUDE_DIR RADOS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:848 (message):
  Rados libraries not found.  Disabling USE_RADOS_RECOV

-- Found rados libraries: RADOS_LIBRARY-NOTFOUND
-- Could NOT find RADOS (missing:  RADOS_INCLUDE_DIR RADOS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:857 (message):
  Rados libraries not found.  Disabling RADOS_URLS

-- Looking for cap_set_proc in cap
-- Looking for cap_set_proc in cap - not found
-- Could NOT find Caps (missing:  CAPS_LIBRARIES CAPS_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:919 (message):
  Capability libraries not found.  Disabling USE_CAPS

-- Looking for include file blkid/blkid.h
-- Looking for include file blkid/blkid.h - not found
-- Looking for blkid_devno_to_devname in blkid
-- Looking for blkid_devno_to_devname in blkid - not found
-- Looking for include file uuid/uuid.h
-- Looking for include file uuid/uuid.h - found
-- Looking for uuid_parse in uuid
-- Looking for uuid_parse in uuid - found
-- Could not find blkid library, disabling USE_BLKID
-- Looking for daemon in c
-- Looking for daemon in c - found
-- OVERRIDE_INSTALL_PREFIX = 
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so;/usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- Looking for lttng executable...
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file sys/epoll.h
-- Looking for include file sys/epoll.h - found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Found EPOLL: 1  
-- Found NSL: /usr/lib64/libnsl.so  
-- 
-- -------------------------------------------------------
-- TIRPC_EPOLL = TRUE
-- USE_RPC_RDMA = OFF
-- USE_GSS = ON
-- USE_PROFILE = OFF
-- USE_LTTNG_NTIRPC = ON
-- Using ntirpc submodule
/root/nfs-ganesha-next/nfs-ganesha-next/src/libntirpc/ntirpc/
-- Looking for urcu_ref_get_unless_zero
-- Looking for urcu_ref_get_unless_zero - found
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.5.37") 
-- 
-- -------------------------------------------------------
-- PLATFORM = LINUX
-- ARCH = x86_64
-- VERSION = 2.8-dev.31
-- BUILD HOST = localhost.localdomain
-- -------------------------------------------------------
-- USE_FSAL_PROXY = ON
-- USE_FSAL_VFS = ON
-- USE_FSAL_LUSTRE = ON
-- USE_FSAL_CEPH = OFF
-- USE_FSAL_CEPH_MKNOD = 
-- USE_FSAL_CEPH_SETLK = 
-- USE_FSAL_CEPH_LL_LOOKUP_ROOT = 
-- USE_FSAL_CEPH_STATX = 
-- USE_FSAL_CEPH_LL_DELEGATION = 
-- USE_FSAL_CEPH_LL_SYNC_INODE = 
-- USE_FSAL_CEPH_ABORT_CONN = 
-- USE_FSAL_CEPH_RECLAIM_RESET = 
-- USE_FSAL_CEPH_GET_FS_CID = 
-- USE_FSAL_RGW = OFF
-- USE_FSAL_XFS = OFF
-- USE_FSAL_PANFS = OFF
-- USE_FSAL_GPFS = ON
-- USE_FSAL_GLUSTER = OFF
-- USE_FSAL_NULL = ON
-- USE_FSAL_MEM = ON
-- USE_SYSTEM_NTIRPC = OFF
-- USE_DBUS = OFF
-- USE_CB_SIMULATOR = OFF
-- USE_NFSIDMAP = OFF
-- ENABLE_ERROR_INJECTION = OFF
-- ENABLE_VFS_DEBUG_ACL = OFF
-- ENABLE_RFC_ACL = OFF
-- USE_CAPS = OFF
-- USE_BLKID = OFF
-- DISTNAME_HAS_GIT_DATA = OFF
-- _MSPAC_SUPPORT = OFF
-- USE_EFENCE = OFF
-- _NO_TCP_REGISTER = OFF
-- RPCBIND = ON
-- DEBUG_SAL = OFF
-- _VALGRIND_MEMCHECK = OFF
-- ENABLE_LOCKTRACE = OFF
-- PROXY_HANDLE_MAPPING = OFF
-- DEBUG_MDCACHE = OFF
-- DEBUG_SYMS = OFF
-- COVERAGE = OFF
-- ENFORCE_GCC = OFF
-- USE_GTEST = ON
-- USE_GSS = ON
-- TIRPC_EPOLL = TRUE
-- USE_9P = ON
-- _USE_9P = ON
-- _USE_9P_RDMA = OFF
-- USE_NFS_RDMA = OFF
-- USE_NFS3 = ON
-- USE_NLM = ON
-- USE_ACL_MAPPING = OFF
-- KRB5_PREFIX = 
-- CEPH_PREFIX = 
-- RGW_PREFIX = 
-- GLUSTER_PREFIX = /usr
-- CMAKE_PREFIX_PATH = 
-- _GIT_HEAD_COMMIT = NOT-GIT
-- _GIT_HEAD_COMMIT_ABBREV = NOT-GIT
-- _GIT_DESCRIBE = /root/nfs-ganesha-next/nfs-ganesha-next/src
-- ALLOCATOR = libc
-- GOLD_LINKER = 
-- CMAKE_INSTALL_PREFIX = /usr
-- FSAL_DESTINATION = /usr/lib64/ganesha
-- USE_ADMIN_TOOLS = OFF
-- USE_GUI_ADMIN_TOOLS = ON
-- MODULES_PATH = 
-- USE_LTTNG = ON
-- USE_BLKIN = OFF
-- USE_VSOCK = OFF
-- USE_TOOL_MULTILOCK = OFF
-- USE_MAN_PAGE = OFF
-- USE_RADOS_RECOV = OFF
-- RADOS_URLS = OFF
-- USE_CUNIT = OFF
-- SANITIZE_ADDRESS = OFF
-- Found LSB_RELEASE: /usr/bin/lsb_release  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/nfs-ganesha-next/nfs-ganesha-next/build

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- Scanning dependencies of target ganesha_nfsd
Linking C shared library libganesha_nfsd.so
[ 98%] Built target ganesha_nfsd
Scanning dependencies of target test_nfs4_lookup_latency
[100%] Building CXX object gtest/nfs4/CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o
Linking CXX executable test_nfs4_lookup_latency
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `LookupEmptyLatencyTest_SIMPLE_Test::TestBody()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/nfs4/test_nfs4_lookup_latency.cc:90: undefined reference to `nfs4_op_lookup'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `LookupEmptyLatencyTest_LOOP_Test::TestBody()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/nfs4/test_nfs4_lookup_latency.cc:111: undefined reference to `nfs4_op_lookup'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `LookupFullLatencyTest_BIG_SINGLE_Test::TestBody()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/nfs4/test_nfs4_lookup_latency.cc:140: undefined reference to `nfs4_op_lookup'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `LookupFullLatencyTest_BIG_Test::TestBody()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/nfs4/test_nfs4_lookup_latency.cc:171: undefined reference to `nfs4_op_lookup'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::Environment::Environment(char*, char*, int, char*, char const*, unsigned short)':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:67: undefined reference to `nfs_libmain'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::Environment::~Environment()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:73: undefined reference to `admin_halt'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::GaneshaFSALBaseTest::SetUp()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:216: undefined reference to `get_gsh_export'
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:219: undefined reference to `nfs_export_get_root_entry'
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:245: undefined reference to `fsal_create'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::GaneshaFSALBaseTest::TearDown()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:265: undefined reference to `_put_gsh_export'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::GaneshaFSALBaseTest::create_and_prime_many(int, fsal_obj_handle**, fsal_obj_handle*)':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:293: undefined reference to `fsal_create'
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:307: undefined reference to `fsal_readdir'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::GaneshaFSALBaseTest::remove_many(int, fsal_obj_handle**, fsal_obj_handle*)':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:324: undefined reference to `fsal_remove'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::GaeshaNFS4BaseTest::TearDown()':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest_nfs4.hh:64: undefined reference to `nfs4_Compound_FreeOne'
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest_nfs4.hh:67: undefined reference to `compound_data_Free'
CMakeFiles/test_nfs4_lookup_latency.dir/test_nfs4_lookup_latency.cc.o: In function `gtest::GaeshaNFS4BaseTest::setCurrentFH(fsal_obj_handle*)':
/root/nfs-ganesha-next/nfs-ganesha-next/src/gtest/gtest_nfs4.hh:80: undefined reference to `nfs4_FSALToFhandle'
collect2: error: ld returned 1 exit status
make[3]: *** [gtest/nfs4/CMakeFiles/test_nfs4_lookup_latency.dir/build.make:108: gtest/nfs4/test_nfs4_lookup_latency] Error 1
make[2]: *** [CMakeFiles/Makefile2:3452: gtest/nfs4/CMakeFiles/test_nfs4_lookup_latency.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3464: gtest/nfs4/CMakeFiles/test_nfs4_lookup_latency.dir/rule] Error 2
make: *** [Makefile:1158: test_nfs4_lookup_latency] Error 2

**Comment by dang** [comment]
Which version of Ganesha are you building?  GTest was broken by the DSO changes, and fixed by this commit; c7f1f83d7a3b2af06b3dd1ab2ee43a8783a60b3e

**Comment by YaqiZhang-UESTC** [comment]
Thank you for reply！The version of ganesha I build is next. I noticed the commit you mentioned. I believe they are same about the CMakeList.txt files. I've been stuck here for a long time,Any information would be appreciated！

**Comment by dang** [comment]
I'm not sure what's wrong here.  It works for me, with the same version of gcc.  @kalebskeithley Any ideas?

**Comment by dang** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/455687

**Comment by YaqiZhang-UESTC** [comment]
wow,wow , it works,man.thank you so so so  much .

**Comment by YaqiZhang-UESTC** [comment]
Sorry to bother you @dang , last time i compiled gtest with no error .About five days ago, when i tried to compile it again,somehow it failed. Here are the result of compiling test_nfs4_lookup_latency for the first time:
[==========] Running 4 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from LookupEmptyLatencyTest
[ RUN      ] LookupEmptyLatencyTest.SIMPLE
[       OK ] LookupEmptyLatencyTest.SIMPLE (3 ms)
[ RUN      ] LookupEmptyLatencyTest.LOOP
Average time per lookup: 16648 ns
[       OK ] LookupEmptyLatencyTest.LOOP (16650 ms)
[----------] 2 tests from LookupEmptyLatencyTest (16653 ms total)

[----------] 2 tests from LookupFullLatencyTest
[ RUN      ] LookupFullLatencyTest.BIG_SINGLE
Average time per lookup: 60733 ns
[       OK ] LookupFullLatencyTest.BIG_SINGLE (47439 ms)
[ RUN      ] LookupFullLatencyTest.BIG
Average time per lookup: 12616 ns
[       OK ] LookupFullLatencyTest.BIG (46719 ms)
[----------] 2 tests from LookupFullLatencyTest (94158 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 2 test suites ran. (110812 ms total)
[  PASSED  ] 4 tests.

It's very odd because i did nothing before compile it again,the information are as follows.I tried to work it out ,but all failed.thank you very much!
[root@bogon build]# cd gtest/nfs4/
[root@bogon nfs4]# ls
CMakeFiles           Makefile                test_nfs4_lookup_latency  test_nfs4_rename_latency
cmake_install.cmake  test_nfs4_link_latency  test_nfs4_putfh_latency
[root@bogon nfs4]# ./test_nfs4_lookup_latency 
[==========] Running 4 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from LookupEmptyLatencyTest
[ RUN      ] LookupEmptyLatencyTest.SIMPLE
/root/code/nfs-ganesha-next/src/gtest/gtest.hh:217: Failure
Expected: (a_export) != (nullptr), actual: NULL vs (nullptr)
Segmentation fault (core dumped)

**Comment by dang** [comment]
That test works for me.  My guess is that your ganesha.conf doesn't have an export with ID 77.  This is required for these tests to pass.

**Comment by YaqiZhang-UESTC** [comment]
Thank you ，I’ve dealed with ganesha.conf when I compile gtest. It's very odd because i cannot compile gtest successfully everytime even with the same way.Anyway,thank you again,i will try my best to figure it out.

**Comment by ffilz** [comment]
I'm assuming this is resolved.
