### ISSUE TITLE
Question: HA in GLUSTER

### ISSUE THREAD

**Issue by varuntanwar** [nfs-ganesha/nfs-ganesha#427]
I have two cluster of glusterfs, clusterA -v3.12 and clusterB - v6.1. On these clusters, I have installed the nfs-ganesh (v2.5 on clusterA and v2.7 on clusterB). Now, I want HA on the gluster. 

Should I use keepalive or lvs to achieve HA? or Is there any module of ganesh which I can use? I tried the steps mentioned in this document : 
https://docs.gluster.org/en/v3/Administrator%20Guide/NFS-Ganesha%20GlusterFS%20Integration/

OS Installed: Ubuntu(16.04)
I was not able to find following file: ganesha-ha.sh

**Comment by kalebskeithley** [comment]
> Now, I want HA on the gluster.
? gluster has it's own HA built in. I presume you really mean on ganesha.

ganesha-ha.sh is a wrapper script for setting up a Pacemaker+Corosync based HA solution. AFAIK Ubuntu does not ship Pacemaker or Corosync. Now, I want HA on the gluster.It was last shipped in glusterfs-3.10 IIRC and may return in glusterfs-7.

Others have set up their own HA solutions using keepalived and CTDB; I haven't heard of lvs before. There is also the Storhaug project under Gluster that uses CTDB.

**Comment by ffilz** [comment]
Closing as resolved. Note that this would be a better question for the support@lists.nfs-ganesha.org mailing list.
