### ISSUE TITLE
ganesha_status: Error: Can't talk to ganesha service on d-bus. Looks like Ganesha is down

### ISSUE THREAD

**Issue by q1216482432** [nfs-ganesha/nfs-ganesha#428]
hi,

I don't know why this is happening.... My ganesha is running, and the Enable_NFS_Stats in the ganesha.conf  is true. I restarted ganesha many times, however it is invalid and print "Error: Can't talk to ganesha service on d-bus. Looks like Ganesha is down" . Could you have some suggestions on it??

**Comment by fantastic2085** [comment]
How to solve the problem @q1216482432
