### ISSUE TITLE
Permission denied in middle of file creation using kerberos

### ISSUE THREAD

**Issue by prabhu-08** [nfs-ganesha/nfs-ganesha#429]
While trying to create a 1TB file with 1GB block size , the file creation fails with permission denied even though the token is still valid. With 1GB block size file creation is successful for non kerberos mount, issue is only observed only if mounted with kerberos security.

`dd if=/dev/urandom  of=/mnt/test/1TB_testfile  iflag=fullblock bs=1G count=1024`

`dd: error writing '/mnt/test/1TB_testfile': Permission denied`
`370+0 records in`
`369+0 records out`
`396210733056 bytes (396 GB, 369 GiB) copied, 29044.1 s, 13.6 MB/s`

Ganesh log says

> 2019-05-30 08:58:18.9775 +0000 USER.INFO [fslib-ganesha]  [svc_19623] nfs_rpc_process_request :DISP :INFO :Could not authenticate request... rejecting with AUTH_STAT=AUTH_REJECTEDCRED

Also if we reduce the block size to 4MB instead of 1GB the file creation is successful with kerberos also.

Does NFS/NFS Ganesh/Kerberos has any issue with respect to larger block size?

TIA

**Comment by dang** [comment]
What version of Ganesha?  What form of KRB are you using (integrity?  privacy?)

**Comment by prabhu-08** [comment]
Thank you @dang for the response. Below are the details
Ganesha version: V2.7.1
MS 2016 AD server
We are using krb5 as security type while mounting.

**Comment by dang** [comment]
Can you turn on tirpc debugging?  It's done like this:

NFS_CORE_PARAM {
    RPC_Debug_Flags = 0xffffffff;
}
LOG {
    Components {
        TIRPC = FULL_DEBUG;
    }
}

This will generate a lot of debug messages, but hopefully not too many.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
