### ISSUE TITLE
NFS Ganesha server share mounting issue

### ISSUE THREAD

**Issue by SeanChristopherConway** [nfs-ganesha/nfs-ganesha#434]
I am running nfs-ganesha using Rook-ceph and am getting the following error when I try to mount a share:
`mount.nfs: mount to NFS server '192.168.1.xxx:/cephfs' failed: RPC Error: Unable to receive`

**Comment by dang** [comment]
That's not a very useful error.  All it tells us is that the communication failed for some reason.  Are there Ganesha logs?  Can you get a packet trace?  Is the firewall blocking access?
Also, what version of Ganesha?
