### ISSUE TITLE
nfs-ganesha V2.7.5 commits not available in V2.7-stable branch

### ISSUE THREAD

**Issue by pasikarkkainen** [nfs-ganesha/nfs-ganesha#439]
It seems commits leading to V2.7.5 are not available in V2.7-stable branch (https://github.com/nfs-ganesha/nfs-ganesha/commits/V2.7-stable), but the actual release tag is still here: https://github.com/nfs-ganesha/nfs-ganesha/releases/tag/V2.7.5

Maybe someone forgot to push the V2.7-stable branch?

**Comment by pasikarkkainen** [comment]
Actually, the commits are there, it's just the most recent commit which has a typo (?).. it says V2.7.4, when it should say V2.7.5 ..

@dang right? :)

**Comment by dang** [comment]
Yep.  Unfortunate, but we can't change it now.

**Comment by pasikarkkainen** [comment]
Yep, thanks for confirming. I'll close the issue.
