### ISSUE TITLE
V2.8.0.3 crash with -N NIV_INFO, but not NIV_DEBUG on gluster

### ISSUE THREAD

**Issue by eliv** [nfs-ganesha/nfs-ganesha#441]
Gluster 6.3 & nfs-ganesha V2.8.0.3 on Debian 9 crashes all the time in my testing with NIV_INFO. Ran with NIV_DEBUG and I've yet to see a crash, though the multi GB log file is likely to be a pain to deal with. .deb packages from https://download.nfs-ganesha.org/2.8/2.8.0/Debian/9/

gdb output:

Thread 2.319 "ganesha.nfsd" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffebb9ff700 (LWP 5394)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff540142a in __GI_abort () at abort.c:89
#2  0x00007ffff543dc00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff5532fd0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5443fc6 in malloc_printerr (action=3, str=0x7ffff552fb8a "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>)
    at malloc.c:5049
#4  0x00007ffff544480e in _int_free (av=0x7ffff5766b00 <main_arena>, p=0x7ffebb9fd968, have_lock=0) at malloc.c:3905
#5  0x00007ffff7b1d67e in ?? () from /usr/lib/libganesha_nfsd.so.2.8
#6  0x00007ffff7b1e5e9 in ?? () from /usr/lib/libganesha_nfsd.so.2.8
#7  0x00007ffff7b0b39a in ?? () from /usr/lib/libganesha_nfsd.so.2.8
#8  0x00007ffff7a4c996 in fsal_readdir () from /usr/lib/libganesha_nfsd.so.2.8
#9  0x00007ffff7af9722 in ?? () from /usr/lib/libganesha_nfsd.so.2.8
#10 0x00007ffff7a2cadc in ?? () from /usr/lib/libganesha_nfsd.so.2.8
#11 0x00007ffff77dca31 in ?? () from /lib/x86_64-linux-gnu/libntirpc.so.1.8
#12 0x00007ffff77daf4d in ?? () from /lib/x86_64-linux-gnu/libntirpc.so.1.8
#13 0x00007ffff77db58a in ?? () from /lib/x86_64-linux-gnu/libntirpc.so.1.8
#14 0x00007ffff77e3f94 in ?? () from /lib/x86_64-linux-gnu/libntirpc.so.1.8
#15 0x00007ffff5b834a4 in start_thread (arg=0x7ffebb9ff700) at pthread_create.c:456
#16 0x00007ffff54b5d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by ffilz** [comment]
Can you run with full debug info so we can see the Ganesha stack?

**Comment by eliv** [comment]
New and improved, now with debug symbols installed:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff540142a in __GI_abort () at abort.c:89
#2  0x00007ffff543dc00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff5532fd0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5443fc6 in malloc_printerr (action=3, str=0x7ffff552fb8a "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
#4  0x00007ffff544480e in _int_free (av=0x7ffff5766b00 <main_arena>, p=0x7fffd6802968, have_lock=0) at malloc.c:3905
#5  0x00007ffff7b1d67e in gsh_free (p=0x7fffd6802978) at ./src/include/abstract_mem.h:246
#6  mdcache_populate_dir_chunk (directory=directory@entry=0x7fffcc0317d0, whence=<optimized out>, whence@entry=17787, dirent=dirent@entry=0x7fffd6802ac0, prev_chunk=prev_chunk@entry=0x0, eod_met=eod_met@entry=0x7fffd6802abf)
    at ./src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:2651
#7  0x00007ffff7b1e5e9 in mdcache_readdir_chunked (directory=directory@entry=0x7fffcc0317d0, whence=17787, dir_state=dir_state@entry=0x7fffd6802c80, cb=cb@entry=0x7ffff7a4b270 <populate_dirent>, attrmask=attrmask@entry=0, 
    eod_met=eod_met@entry=0x7fffd6802d4f) at ./src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:2985
#8  0x00007ffff7b0b39a in mdcache_readdir (dir_hdl=0x7fffcc031808, whence=0x7fffd6802c68, dir_state=0x7fffd6802c80, cb=0x7ffff7a4b270 <populate_dirent>, attrmask=0, eod_met=0x7fffd6802d4f)
    at ./src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:559
#9  0x00007ffff7a4c996 in fsal_readdir (directory=directory@entry=0x7fffcc031808, cookie=<optimized out>, cookie@entry=17787, nbfound=nbfound@entry=0x7fffd6802d50, eod_met=eod_met@entry=0x7fffd6802d4f, attrmask=attrmask@entry=0, 
    cb=cb@entry=0x7ffff7af9130 <nfs3_readdir_callback>, opaque=0x7fffd6802d60) at ./src/FSAL/fsal_helper.c:1176
#10 0x00007ffff7af9722 in nfs3_readdir (arg=<optimized out>, req=<optimized out>, res=0x7fffc808c5f0) at ./src/Protocols/NFS/nfs3_readdir.c:285
#11 0x00007ffff7a2cadc in nfs_rpc_process_request (reqdata=0x7fffc8046640) at ./src/MainNFSD/nfs_worker_thread.c:1484
#12 0x00007ffff77dca31 in svc_request (xprt=0x7fffc8000ae0, xdrs=<optimized out>) at ./src/svc_rqst.c:793
#13 0x00007ffff77daf4d in svc_rqst_xprt_task (wpe=0x7fffc8000d00) at ./src/svc_rqst.c:774
#14 0x00007ffff77db58a in svc_rqst_epoll_loop (wpe=0x555555889860) at ./src/svc_rqst.c:1089
#15 0x00007ffff77e3f94 in work_pool_thread (arg=0x7fffd00008c0) at ./src/work_pool.c:184
#16 0x00007ffff5b834a4 in start_thread (arg=0x7fffd6804700) at pthread_create.c:456
#17 0x00007ffff54b5d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by dang** [comment]
This was fixed by 445575d4d7923b86187a3c479d4f7abcf25338f8 in 2.8.1

**Comment by eliv** [comment]
Great, any idea when the packages will be up on the download site?

**Comment by ffilz** [comment]
Closed as resolved.
