### ISSUE TITLE
fallocate still failed even though fallocate() api is implemented

### ISSUE THREAD

**Issue by tracymacding** [nfs-ganesha/nfs-ganesha#446]
i got not support error running fallocate
```
[root@hadoop003 fio]# fallocate -l 100 /mnt/c/test
fallocate: fallocate failed: Operation not supported
```
but i have already implement fallocate api in fsal:
```
void handle_ops_init(struct fsal_obj_ops *ops)
{
        fsal_default_obj_ops_init(ops);
        ...
        ops->fallocate = juicefs_fallocate;
}
```

**Comment by ffilz** [comment]
Did you make sure to enable 4.2 in the NFSV4 config block minor_versions parameter (it does default to 0, 1, 2). Otherwise, I'm not quite sure why it isn't working. You may want to enable debug (and maybe add some debug) to figure out where the not supported is happening.

**Comment by tracymacding** [comment]
> Did you make sure to enable 4.2 in the NFSV4 config block minor_versions parameter (it does default to 0, 1, 2). Otherwise, I'm not quite sure why it isn't working. You may want to enable debug (and maybe add some debug) to figure out where the not supported is happening.

I use nfs version 3

**Comment by dang** [comment]
The ALLOCATE op was added in NFS 4.2, so it cannot work in 4.1 or less, as there's no way for the client to send it to the server.

**Comment by ffilz** [comment]
Yea, that won't be available in NFS v3 at all.
