### ISSUE TITLE
FASL_RGW: can't  copy file.

### ISSUE THREAD

**Issue by chenyg0911** [nfs-ganesha/nfs-ganesha#447]
Ceph deploy in k8s cluster with rook.
ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
NFS-Ganesha Release = V2.7.6
nfs mount option:
nfs4 (rw,relatime,sync,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.17.2.101,local_lock=none,addr=172.17.2.103)

copy a test file to nfs mount directory:
```
[root@k8s-1 buck1]# cat /root/testfile 
2019年 07月 25日 星期四 09:24:09 UTC
2019年 07月 25日 星期四 09:24:11 UTC
2019年 07月 25日 星期四 09:24:13 UTC

[root@k8s-1 buck1]# cp /root/testfile .
[root@k8s-1 buck1]# ll
total 0
-rw-r--r--. 1 root root 0 7月  25 09:26 testfile

# use minio client to check the bucket:
[desktop:minio]$ mc ls ceph/buck1
[2019-07-25 17:26:56 CST]      0B testfile

```

the another proble:
when I use mc cp xxxx host/bucket/
which upload the file to ceph rgw, all is OK with s3 client access, but on the side of NFS mountpoint,  after a few minutes, I can get the file. It seams nfs need period to sync with rgw. 

what's the problem?

**Comment by dang** [comment]
The issue with files copied via S3 taking time to show up is because Ganesha caches directories, so you have to wait for that cache to expire.  This happens with all FSALs for Ganesha.  You can turn it off, but it will have performance penalties, possibly large ones.

I'm not sure why the copy is failing.  It should work, (and it does for us here).

**Comment by chenyg0911** [comment]
Thanks for your quickly reply.  Can you tell me how to turn it off? As you said, all FSALs use cache, but when I test with Cephfs, it seam no such problem, the file sync quickly.
For the copy problem, it very odd. As object side, the key create, but value miss.  I'm not sure it cause by Ganesha or ceph lib? Maybe I can change the different version to test it.

**Comment by dang** [comment]
You can see all the cache config in the "ganesha-cache-config" manpage (src/doc/man/ganesha-cache-config.rst in the source).  The relevant config is Dir_Chunk.  Setting it to zero will disable directory caching.

**Comment by chenyg0911** [comment]
OK。I’ll try it. Thanks!

Daniel Gryniewicz <notifications@github.com>于2019年7月26日 周五下午8:19写道：
