### ISSUE TITLE
fio test write shorter than expected

### ISSUE THREAD

**Issue by tracymacding** [nfs-ganesha/nfs-ganesha#448]
Fio is used to test nfs-ganesha with my own FSAL, command like
```
fio -iodepth 1 -thread -rw=write -ioengine=sync -bs=1M -size=2G -numjobs=1 -runtime=1 -group_reporting -name=mytest -nrfiles=1 -directory=/mnt/c
```
but i found fio finished with less written size(< 2G), see:
```
WRITE: bw=1706MiB/s (1789MB/s), 1706MiB/s-1706MiB/s (1789MB/s-1789MB/s), io=1725MiB (1809MB), run=1011-1011msec
```

what is the possible reason?

**Comment by tracymacding** [comment]
each write() call gets ok, but after call the last successful commit(), write stops and fio finished

**Comment by dang** [comment]
You limited the runtime to 1 second with the "-runtime=1", so it can only send 1 second's worth of data.  In my case, that's ~1G.  If I take that out, it sends 2G of data.

**Comment by tracymacding** [comment]
> You limited the runtime to 1 second with the "-runtime=1", so it can only send 1 second's worth of data. In my case, that's ~1G. If I take that out, it sends 2G of data.

Yes, my fault, thanks :)
