### ISSUE TITLE
IP notation not accepting CIDR

### ISSUE THREAD

**Issue by odoucet** [nfs-ganesha/nfs-ganesha#45]
For fields Root_Access or RW_Access, we cannot use CIDR notation (X.X.X.X/Y), but the biggest problem is that this notation is silently ignored, leading to hours of debugging ...

We should first state that CIDR notation is not supported, then warn / fail if such notation is encountered. 

Then, it will be great to support this notation for every IP access in configuration.

**Comment by ffilz** [comment]
The config format has been changed, please open a bug in Red Hat Bugzilla

https://bugzilla.redhat.com/enter_bug.cgi?product=nfs-ganesha

If you are still unable to use CIDR as expected with the new configuration
