### ISSUE TITLE
ganesha-2.7.6 cache don't release

### ISSUE THREAD

**Issue by renhwztetecs** [nfs-ganesha/nfs-ganesha#450]
I use nfs-ganesha 2.7.6, FASL is cephfs. When I write a large number of small files through the nfs client mount, I find that nfs-ganesha's memory usage keeps increasing, and I stop at When the client sends the service, the memory of nfs-ganehsa will not be released, and the MDS has a notification to perform the trim operation.

> top - 11:00:43 up 58 days, 16:08,  5 users,  load average: 0.53, 0.71, 0.82
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.6 us,  0.9 sy,  0.0 ni, 94.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  65777452 total, 64615816 used,  1161636 free,   159160 buffers
KiB Swap: 32763900 total,  6857228 used, 25906672 free. 14714536 cached Mem

>    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
3940590 root      20   0 9890296 3.169g   9304 S  12.6  5.1 222:03.89 ganesha.nfsd

**Comment by renhwztetecs** [comment]
I use ceph-fuse without this problem.
and when is ganesha's trim mechanism going?
thank you

**Comment by renhwztetecs** [comment]
I can grab the lru_state information when I use high memory. I can see that the Entries information is larger than the value I set, as follows:

> $3 = {**entries_hiwat** = 10000, **entries_used** = 11092, chunks_hiwat = 100000, chunks_used = 0, fds_system_imposed = 1048576, fds_hard_limit = 314572,
  fds_hiwat = 209715, fds_lowat = 104857, futility = 0, per_lane_work = 2000, biggest_window = 419430, prev_fd_count = 1740, prev_time = 1564572539,
  fd_state = 0}

Why can't I change the entry to the range I set, but it will exceed it? and can we control the memory usage of nfs-ganesha (2.7.6)?
@dang @malahal 
thanks.

**Comment by dang** [comment]
You can use more entries than your hard limit if the actual working set is larger than the entries_hiwat, but that not important.  11k entries cannot OOM you, entries aren't that big.  11k entries will take up 11 MB.  To get the kind of numbers you seem to be hitting, you'd need millions of entries, not thousands.  Something else must be taking up memory.

**Comment by malahal** [comment]
Ideally, we shouldn't be using more than what is set, but this is a limitation. I agree with Dan that 11K entries is not much. The leak is something else! I suggest you use mmleak tool:
https://ganltc.github.io/tracing-nfs-ganesha-daemon-memory-leaks-with-mmleak-tool.html
You will have to use "systemctl restart nfs-ganesha" instead of mmces command for step5 though.

**Comment by renhwztetecs** [comment]
Today, after we used the 2.7.6 compression test, we saw that the memory rose to about 8.7G. After stopping the pressure reading and writing operation, the memory could not be dropped. Only the file deletion operation can reduce a small amount of memory.

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
> 3108928 root      20   0   11.4g   8.7g   9680 S 166.7  4.7   1174:55 ganesha.nfsd



> (gdb) p lru_state
> $1 = {entries_hiwat = 100000, entries_used = 1624855, chunks_hiwat = 100000, chunks_used = 0, fds_system_imposed = 1048576, fds_hard_limit = 1038090, fds_hiwat = 943718,
>   fds_lowat = 524288, futility = 0, per_lane_work = 50, biggest_window = 419430, prev_fd_count = 684931, prev_time = 1565741547, fd_state = 2}

> (gdb) p open_fd_count
> $2 = 687492

**Comment by ffilz** [comment]
This may have been resolved in more recent releases.

Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
