### ISSUE TITLE
NFS_KRB5 Config Section does not support a own KeytabPath

### ISSUE THREAD

**Issue by ps20renar** [nfs-ganesha/nfs-ganesha#451]
Hallo All,
we want to implement a NFS_KRB5 section with following definitions:
NFS_KRB5 
{ 
PrincipalName = "nfs" ; 
KeytabPath = /etc/myownPATH/krb5.keytab ;
}
Our Version are here gpfs.nfs-ganesha-gpfs-2.5.3-ibm036.04.el7.x86_64
It seems to be, there are some hardcode lines in the Code for /etc/krb5.keytab. This should be changed.

**Comment by malahal** [comment]
Yes, this was brought to my attention recently. Currently, anything other
than /etc/krb5.keytab won't work.

**Comment by ps20renar** [comment]
Hallo malahal,
Thanks for checking. Can you estimate how Long does it take to fix it? Is it possible to put  this fix in the next scale Ganesha release. 
Thanks in Advance.

**Comment by malahal** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/464391 should fix it.

**Comment by ps20renar** [comment]
Thanks Malahal,
We will Check its work.
Regards Renar
