### ISSUE TITLE
Can not mount with nfsv3 which the backend is cephfs

### ISSUE THREAD

**Issue by Hughen** [nfs-ganesha/nfs-ganesha#453]
I can not mount directory with nfsv3, and the real `ganesha.nfsd` backend storage is cephfs.
ceph version: `ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)`
nfs-ganesha version: `2.8.1.2`
All programs(ceph and nfs-ganesha) run in the container, docker version: `18.09.8`

The client(`10.10.249.230`) mount command output:
```shell
user@s01:~$ mount -t nfs -o port=3000,vers=3 10.10.249.233:/efs /mnt/nfs-test --verbose
mount.nfs: timeout set for Mon Aug  5 07:53:53 2019
mount.nfs: trying text-based options 'port=3000,vers=3,addr=10.10.249.233'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 10.10.249.233 prog 100003 vers 3 prot TCP port 3000
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 10.10.249.233 prog 100005 vers 3 prot UDP port 46708
mount.nfs: mount(2): Permission denied
mount.nfs: access denied by server while mounting 10.10.249.233:/efs
```
After the server enable `FULL_DEBUG`, so the log is too many contents, and use the attachment: 
[nfsv3-mount-failed.log](https://github.com/nfs-ganesha/nfs-ganesha/files/3466598/v3-mount-failed.log)

**Comment by dang** [comment]
So, most of the log is something trying to connect with nfsv4; but the few attempts to connect with nfsv3 seem to work.  The reply was correctly sent.  This means there's probably a firewall/network issue.  It appears you're running inside kube?  Are the kube networks set up correctly to allow the client to receive from the server?

**Comment by Hughen** [comment]
@dang 
At the same time, nfsv4 can be connected to the server.

**Comment by dang** [comment]
NFSv4 uses a single, well-known port on the server; NFSv3 uses portmapper to advertise whatever ephemeral port the server registered.  This means that v4 is easy to make work with a firewall, and v3 is much harder.

**Comment by Hughen** [comment]
Then as your mean, does nfsv3 still need port 111 of the udp protocol?

**Comment by dang** [comment]
NFSv4 needs 2049.  NFSv3 needs 111 (portmap), mountd (ephemeral), statd (ephemeral), and lockd (ephemeral).  All if them need to be available for IPv4/IPv6 and UDP/TCP (linux client uses TCP by default).  You can hard-configure the mountd port and lockd ports via MNT_port and NLM_port in Ganesha config.  This can help.

**Comment by Hughen** [comment]
Your tips are very helpful to me. thank you very much @dang 

My problem is that the client uses an illegal prefix when it is mounted. The correct one should be nfs fs structure root "`/`".

**Comment by ffilz** [comment]
I think this is resolved?

Note that as a support question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
