### ISSUE TITLE
Current CMake requires explicit include(CheckSymbolExists)

### ISSUE THREAD

**Issue by StefanBruens** [nfs-ganesha/nfs-ganesha#454]
With current CMake (3.15.1), the build fails as check_symbol_exists is unknown.

FindCEPHFS.cmake uses check_symbol_exists, but does not include the CheckSymbolExists module. CMake commands implemented by modules have to be included:
https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/How-To-Write-Platform-Checks
> Additionally to the builtin commands, cmake offers more commands implemented by cmake script files, called modules. ... To use commands from these modules, they have to be included in the CMakeLists.txt.

**Comment by woodliu** [comment]
why not give a release thing, building is a mess

**Comment by kalebskeithley** [comment]
see https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/466942

**Comment by StefanBruens** [comment]
> bleeding edge distributions
> like fedora-32/rawhide, Ubuntu eoan (19/10), and Debian bullseye/sid
> are still using cmake-3.14.x or cmake-3.13.x.

ROFL ...
Bleeding edge: Arch, Gentoo, Mageia Cauldron, Manjaro, openSUSE Tumbleweed have 3.15.1/3.15.2
