### ISSUE TITLE
utf8_scan error on NFSv4 mount when filename appers garbled

### ISSUE THREAD

**Issue by xujiatong** [nfs-ganesha/nfs-ganesha#458]
I have a file with chinese name which appers garbled on Linux.
[111.tar.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/3504741/111.tar.gz)
I can cp it to nfs-ganesha server with v3 mount but I got "invalid arg return" when cp to v4 the same path mount.
I can cp it to **nfsd server** with either v3 or v4 mount.
Even if I had cp it to ganesha server through v3 mount, if I stat it with v4 mount(the same path)，it returns “Invalid arg”.
Also, when it does not exists on server. If I "stat" the filename with v4 mount, I got “invlid arg” instead of “does not exsist”. 

Then I trace this and found  that the “invalid arg”error code comes from ①  function “nfs4_utf8string2dynamic” (v2.4-v2.8) ②function "nfs4_utf8string_scan" (v2.9+) in "Protocol" layer.

Can we have an option to keep the consistency of NFSv3&v4

**Comment by xujiatong** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/465149

I had done it. Please reivew it if you think this is an issue.

**Comment by kalebskeithley** [comment]
There are other, possibly better ways to do this, e.g. I found https://stackoverflow.com/questions/12456560/encoding-of-filenames-containing-non-latin-characters-while-extracting-from-tar

Which I trivially modified to:

```
#!/usr/bin/python2

import tarfile
import codecs
import sys

def recover(name):
    return codecs.decode(name, 'gbk')

for tar_filename in sys.argv[1:]:
    tar = tarfile.open(name=tar_filename, mode='r', bufsize=16*1024)
    updated = []
    for m in tar.getmembers():
        m.name = recover(m.name)
        updated.append(m)
    tar.extractall(members=updated)
    tar.close()

```
which successfully extracts your 111.tar file and perhaps even better, converts the gbk encoded file name to utf-8, which seems preferable to naively extracting "garbage." Unfortunately I don't read Mandarin, so I can't actually confirm that the file name conversion is correct.

(To run it, save above as tar.py.  `chmod +x tar.py; gunzip 111.tar.gz; ./tar.py 111.tar`)

NFSv3 does not check that filenames are valid UTF. If you mount the volume with -o vers=3 you'll be able to untar the tar file without any extra steps.

Let us know how this works for you. I'm especially interested in whether the file name was correctly decoded.

Regards,

**Comment by Pating** [comment]
Hi, Kaleb. The method works on nfs-ganesha v4. Thanks

Everyone should keep in mind that, you could never predict user behavior.  **if there is a non-utf8 named file(maybe from private client, nfsv3, gnfs) in the cluster, end-user could never copy it out from nfsv4 client**.

Anyway, we'll backport https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/465149 to reduce operation and maintenance costs.

**Comment by ffilz** [comment]
Closed as resolved
