### ISSUE TITLE
nfs-ganesha with glusterfs warning nfs_health :DBUS :WARN :Health status is unhealthy. enq new... old

### ISSUE THREAD

**Issue by doreno39** [nfs-ganesha/nfs-ganesha#463]
Hi,

I'm using nfs-ganesha-2.7.4 and glusterfs-6.3.1 on centos7.6.
Exporting some volume via nfs-ganesha, the NFS client still seems fine. But I see some warning messages in /var/log/ganesha/ganesha.log, please help me to explain them.
`27/08/2019 15:52:07 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
27/08/2019 15:52:07 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
27/08/2019 15:52:07 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
27/08/2019 15:53:37 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
27/08/2019 16:37:37 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 83465, old: 83464; deq new: 83464, old: 83464
27/08/2019 20:56:38 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 291408, old: 291407; deq new: 291407, old: 291407
27/08/2019 22:09:01 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 326479, old: 326478; deq new: 326478, old: 326478
27/08/2019 22:09:19 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 326480, old: 326479; deq new: 326479, old: 326479
28/08/2019 01:10:24 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 420803, old: 420802; deq new: 420802, old: 420802
28/08/2019 03:41:33 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 578353, old: 578321; deq new: 578261, old: 578261
28/08/2019 06:17:42 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 861557, old: 861556; deq new: 861555, old: 861555
28/08/2019 08:36:06 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 912099, old: 912098; deq new: 912097, old: 912097
28/08/2019 10:36:03 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 953797, old: 953796; deq new: 953795, old: 953795
28/08/2019 16:00:09 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1085655, old: 1085654; deq new: 1085653, old: 1085653
28/08/2019 16:32:26 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1109477, old: 1109476; deq new: 1109475, old: 1109475
28/08/2019 17:57:00 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1192291, old: 1192290; deq new: 1192289, old: 1192289
28/08/2019 18:22:25 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1194224, old: 1194223; deq new: 1194222, old: 1194222
28/08/2019 21:26:07 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1282100, old: 1282099; deq new: 1282098, old: 1282098
28/08/2019 22:36:38 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1349170, old: 1349169; deq new: 1349168, old: 1349168
29/08/2019 00:37:56 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1402493, old: 1402492; deq new: 1402491, old: 1402491
29/08/2019 01:42:32 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1447513, old: 1447512; deq new: 1447511, old: 1447511
29/08/2019 04:43:52 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1636125, old: 1636124; deq new: 1636063, old: 1636063
29/08/2019 13:35:10 : epoch 5d64ef36 : node104 : ganesha.nfsd-46790[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1993737, old: 1993736; deq new: 1993734, old: 1993734`

Thanks!

**Comment by pasikarkkainen** [comment]
Did you try with the latest versions? glusterfs 6.5 and nfs-ganesha 2.7.6. Do those versions show the same problem?

**Comment by doreno39** [comment]
Hi Pasikarkkainen,

Thank for your response!
I have not tried with the latest version, can you help me to know more about this issue? How did you know the latest version can resolve the problem?

Thanks!

**Comment by kalebskeithley** [comment]
It's just a warning. IIRC it just means that dbus didn't respond within the time it expected. It's sort of a heartbeat to assess how loaded the system is.

I don't recall ever seeing it on my development systems. Make sure you have dbus-broker installed. It's possible that there are some missing rpm dependencies in the packages.

**Comment by doreno39** [comment]
Hi Kalebskeithley,
Thank for your response!

> It's just a warning. IIRC it just means that dbus didn't respond within the time it expected. It's sort of a heartbeat to assess how loaded the system is.
> 
> I don't recall ever seeing it on my development systems. Make sure you have dbus-broker installed. It's possible that there are some missing rpm dependencies in the packages.
Sure, the dbus has been installed.

But now, not just a warning. It's was hung, can not mount and showmount from the client after two days, return the error message "rpc mount export: RPC: Timed out". I have restarted the service to work this time.
Below is the log of /var/log/gansha/ganeshe.log when restarting the service:
`29/08/2019 18:23:38 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
29/08/2019 18:23:38 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
29/08/2019 18:23:38 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
29/08/2019 18:23:38 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
29/08/2019 18:23:48 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
29/08/2019 19:15:26 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 42482, old: 42481; deq new
: 42481, old: 42481
29/08/2019 21:11:03 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 115622, old: 115621; deq n
ew: 115621, old: 115621
29/08/2019 21:24:53 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 116475, old: 116474; deq n
ew: 116474, old: 116474
30/08/2019 05:22:10 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 646493, old: 646478; deq n
ew: 646463, old: 646463
30/08/2019 05:22:15 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 646603, old: 646588; deq n
ew: 646573, old: 646573
30/08/2019 05:22:45 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 647167, old: 647137; deq n
ew: 647137, old: 647137
30/08/2019 09:00:30 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 796202, old: 796201; deq n
ew: 796197, old: 796197
30/08/2019 12:13:22 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 870026, old: 870025; deq n
ew: 870021, old: 870021
30/08/2019 15:34:28 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 982515, old: 982514; deq n
ew: 982510, old: 982510
31/08/2019 03:44:38 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1500493, old: 1500446; deq
 new: 1500376, old: 1500376
31/08/2019 05:00:42 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1581257, old: 1581256; deq
 new: 1581251, old: 1581251
31/08/2019 06:53:35 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1661659, old: 1661658; deq
 new: 1661652, old: 1661652
31/08/2019 06:56:48 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1661782, old: 1661781; deq
 new: 1661774, old: 1661774
31/08/2019 06:59:21 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1661870, old: 1661869; deq
 new: 1661857, old: 1661857
31/08/2019 07:00:08 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 1661901, old: 1661900; deq
 new: 1661887, old: 1661887
31/08/2019 10:55:53 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[sigmgr] sigmgr_thread :MAIN :EVENT :SIGHUP_HANDLER: Received SIGHUP.... initiating export list reload
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] do_shutdown :MAIN :EVENT :NFS EXIT: stopping NFS service
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[dbus_heartbeat] gsh_dbus_thread :DBUS :EVENT :shutdown
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] do_shutdown :MAIN :EVENT :Stopping delayed executor.
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] do_shutdown :MAIN :EVENT :Delayed executor stopped.
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] do_shutdown :MAIN :EVENT :Stopping state asynchronous request thread
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] do_shutdown :THREAD :EVENT :State asynchronous request system shut down.
31/08/2019 10:58:00 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] do_shutdown :MAIN :EVENT :Unregistering ports used by NFS service
31/08/2019 10:58:09 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:58:18 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:58:27 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:58:36 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:58:45 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:58:54 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:59:03 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:59:12 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:59:21 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:59:30 : epoch 5d67b5b7 : node104 : ganesha.nfsd-20829[Admin] rpc :TIRPC :EVENT :rpcb_unset: RPC: Timed out
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72537[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 2.7.3
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_start_grace :STATE :WARN :NFS Server GRACE duration should at least match LEASE period. Curre
nt configured values are GRACE(10), LEASE(60)
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 10
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume alglobal exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume cbtrmtl exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ctrbmvn exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume dtrcm exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume dcstrth exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume dttr3qvn exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume h5trpkm exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume jtrs2m exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ltrdk exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume mutra exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume nartrutoh5 exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume tctrqk exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ttrj exported at : '/'
31/08/2019 10:59:30 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ttrk exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume tktr4 exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume tltrbbnew exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ttrtk exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume vltr3web exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ytrgh5 exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume yutrgisea exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume ztrtm exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume mutrw exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume pvtrkh exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume rotrspcvn exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume jxtrh5 exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume putrbgm exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] glusterfs_create_export :FSAL :EVENT :Volume zstrm exported at : '/'
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
31/08/2019 10:59:31 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,35,36+ep
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/var/run/ganesha) already exists
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:0)
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Start_threads :THREAD :EVENT :9P/TCP dispatcher thread was started successfully
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[_9p_disp] _9p_dispatcher_thread :9P DISP :EVENT :9P dispatcher started
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Start_threads :THREAD :EVENT :gsh_dbusthread was started successfully
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
31/08/2019 10:59:32 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
31/08/2019 10:59:42 : epoch 5d69f0a2 : node104 : ganesha.nfsd-72540[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
`

**Comment by malahal** [comment]
Health status is unhealthy. **enq new: 42482, old: 42481; deq new : 42481, old: 42481** 
Health status is unhealthy. **enq new: 115622, old: 115621; deq n ew: 115621, old: 115621**

The above message should appear from dbus thread if Ganesha daemon appears to hang. Clearly there is a bug in the hang detection as the deq numbers change over the time. This is a known issue and we disabled this message. Both the above messages indicate that ganesha hasn't picked up the new request that has been placed in the queue. By default, dbus threads checks this every second. It is possible that the new request was placed just before the dbus check or the daemon is busy working with old requests and couldn't pick a new one.

**Comment by ryno83** [comment]
Having the same on debian 9, nfs-ganesha 2.8 and glusterfs 6.6. Should I worry about it since it's only a warning ?

**Comment by dang** [comment]
In general, unless you get multiples of those messages in a row with the  same numbers, or you're seeing other symptoms (such as client hangs), then you can ignore that message.

**Comment by jonashrem** [comment]
We had the same message.

During this, we had an issue, that we were not able to read a single directory.

Reading other directories worked without any issues.

Reading files withing the directory worked as well (as we knew all file names, we tested each one of them)

Anyone an idea? I also attached pstack output.

We use:

glusterfs: 6.7
ganesha: 3.2
nfs: 4
mountoptions: rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys
Virtuozzo Linux: 7.2.0
Kernel: 3.10.0-1062.4.2.vz7.116.7

[03-11-2020_15:40:13.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/4319460/03-11-2020_15.40.13.txt)

**Comment by ffilz** [comment]
Closing due to age. If this issue is still of interest, please reopen.

**Comment by guol-fnst** [comment]
I have the same questions.
Environment:
Centos7.2 gluster5.13 ganesha2.7 
Mount point is hung.  
I think these message is not a warnings but errors.

**Comment by dang** [comment]
The health status messages are warnings.  They are best-effort indications that something might be wrong.  Due to the way the warning is implemented, it might trigger sometimes when there's nothing wrong, depending on client load.  However, if it happens frequently, or if it happens multiple times in a row with the same numbers, then it's an indication that something is either hanging or taking a very long time to complete.
