### ISSUE TITLE
A compilation error occurs when setting USE_FSAL_PANFS=ON

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#464]
A compilation error occurs when setting USE_FSAL_PANFS=ON, as follows:
src/FSAL/FSAL_VFS/panfs/mds.c:295:45: error: 'const struct fsal_up_vector' has no member named 'export'

**Comment by kalebskeithley** [comment]
AFAIK we don't typically build FSAL_PANFS, so it's possible that some bitrot has occurred.

Are you even using PANFS?

Also for questions it's probably better to ask on the devel@lists.nfs-ganesha.org or support@nfs-ganesha.org mailing lists, or #ganesha on freenode IRC.

**Comment by ffilz** [comment]
FSAL_PANFS at this point is pretty much unsupported. We really should remove the code. Panasas has not been engaged with Ganesha for several years now.

**Comment by ffilz** [comment]
Closing as will not fix.
