### ISSUE TITLE
nfs-ganecha use jemalloc by default. What are the benefits?

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#465]
nfs-ganecha use jemalloc by default. What are the benefits?

**Comment by kalebskeithley** [comment]
For some workloads ganesha may perform better when it's built with jemalloc.

You can also build it with tcmalloc (from gperftools). All the packages  on download.nfs-ganesha.org, in Fedora, CentOS Storage SIG, Launchpad, and OpenSUSE OBS are built with jemalloc disabled.
