### ISSUE TITLE
about lru 

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#468]
nfs version =3 

operation: touch a

ganesha log gain and again to print below:
lru_run :INODE LRU :CRIT :Futility count exceeded.  The LRU thread is unable to make progress in reclaiming FDs, will try harder.

why?

**Comment by dang** [comment]
This is either because many files are opened by the client (more than Entries_HWMark), or because there is an FD leak.  More information would be necessary, such as Ganesha version and config used.

**Comment by fantastic2085** [comment]
ganesha vesion is v2.6.2
ganesha.conf，below:
NFS_Core_Param
{
    Nb_Worker = 2048;
    Dispatch_Max_Reqs = 10000;
    Dispatch_Max_Reqs_Xprt = 2048;
    RPC_Ioq_ThrdMax = 4096;
    MaxRPCSendBufferSize = 9437184;
    MaxRPCRecvBufferSize = 9437184;
    NFS_Protocols = 3,4;
    RPC_Max_Connections = 10000;
    Bind_Addr = 10.252.2.63;
    NFS_Port = 2049;
}

RGW
{
    conf_path = "/etc/ceph/ceph.conf";
    name = "client.radosgw.nfs-gateway-10.252.2.63-2049-y4zyl1x";
    cluster = "ceph";
    init_args = "";
}

EXPORT
{
    Export_Id = 1;
    Path = "/bucket-1";
    Pseudo = "/bucket-1";
    Squash = No_Root_Squash;
    Protocols = 3,4;
    Transports = TCP;
    FSAL
    {
        Name = CEPH_RGWFS;
        User = "me";
        Access_Key = "MAGL61YK3ZBR7RU1EZMH";
        Secret_Key = "d7GP9e3N5HE2AXAONaqUpVpFVYdKKlfuQviPixv0";
        Root_Bucket = "bucket-1";
    }
}

**Comment by malahal** [comment]
What is your NOFILE in /etc/sysconfig/ganesha? Or what is the maximum
number of open files you can have for the ganesha process? The latter
should be there in /proc/<PID>/limits

**Comment by fantastic2085** [comment]
cat limits : below

Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             256013               256013               processes 
Max open files            1048576              1048576              files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       256013               256013               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

**Comment by malahal** [comment]
>> Max open files 1048576 1048576 files

That is good. You need to make sure that Ganesha does indeed have this setting by looking at lru_state.fds_hard_limit. I don't think there is any tracing for this in older code, so you may want to run gdb on the live daemon ("gdb /usr/bin/ganesha.nfsd <PID>) and print lru_state ("p  lru_state"). lru_state.fds_hiwat is what is needed though

**Comment by fantastic2085** [comment]
> That is good. You need to make sure that Ganesha does indeed have this setting by looking at lru_state.fds_hard_limit. I don't think there is any tracing for this in older code, so you may want to run gdb on the live daemon ("gdb /usr/bin/ganesha.nfsd ) and print lru_state ("p lru_state"). lru_state.fds_hiwat is what is needed though

Thank you very much!

**Comment by dang** [comment]
Also note that 2.6.2 is extremely old.  There have been a number of FD leak fixes, and I'm not sure all of them have been backported to 2.6.  Please try 2.8.x

**Comment by fantastic2085** [comment]
Can I know the place where FD leak was modified?

**Comment by fantastic2085** [comment]
is about this variable open_fd_count?

**Comment by dang** [comment]
It's primarily about open_fd_count, yes.  A quick scan finds these changes:

d4b3079f1efdfc501a71bd2a9b9e426ed5a273ba
a08cbf65b626aa3e1ecf4de78a7586204a7eeb02
500c754df3a46d77f88036e922424e49af1f9b65
5de90cd33eff307ef8778733726429565868e8ff
114c38ce9fcf20878ffce3b454e106089a34ab5d
062c6a7e2e5ab87c89a9b28b5dfde50d0427c9f5
2d9c8e70eeb596d04ed0b5168422a5ce35fc0c7d

This was just a quick scan, so I may have missed some.

**Comment by yangruifeng** [comment]
@dang 
https://github.com/nfs-ganesha/nfs-ganesha/blob/c087e3718c0ef314d56306a74409d97e706ee862/src/FSAL/FSAL_RGW/handle.c#L1102-L1106

maybe 
handle->openflags = FSAL_O_NFS_FLAGS(openflags); 
change to
obj->openflags = FSAL_O_NFS_FLAGS(openflags);

**Comment by dang** [comment]
No, FSAL_RGW consistently uses handle->openflags for all it's global state flag tracking.

**Comment by yangruifeng** [comment]
this handle is parent dir handle, It confuses me

**Comment by dang** [comment]
Hmm, you're right, I was looking at the open-by-handle case.  For the create case, that is the parent, and obj should be used.

**Comment by dang** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/467976

**Comment by ffilz** [comment]
Closed as resolved.
