### ISSUE TITLE
What's the difference between gtest and test folders?

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#469]
What's the difference between gtest and test folders?

**Comment by dang** [comment]
test is ad-hoc tests.  gtest is tests using the Google G-Test framework, with is C++ (and therefore builds differently).

**Comment by ffilz** [comment]
There used to be more unit test code, but that grew stale and was removed. I'm not sure why we still have a few bits left around, the gtest mechanism is a much better test harness for unit tests.

**Comment by ffilz** [comment]
Closed as resolved.
