### ISSUE TITLE
GlusterFS async R/W

### ISSUE THREAD

**Issue by xuyuqingfeng** [nfs-ganesha/nfs-ganesha#471]
GFAPI implements glfs_preadv_async and glfs_writev_async async IO interfaces . 
Why does the NFS-Ganesha gluster async IO interface use glfs_preadv and glfs_pwritev instead of glfs_preadv_async** and glfs_pwritev_async?

**Comment by dang** [comment]
The full async codework in Ganesha is not yet complete.  The goal is to use those codepaths once it's done.

**Comment by ffilz** [comment]
Are you interested in taking this on? If so, reopen and we will track it as an active development activity.

Closing for now due to age.
