### ISSUE TITLE
2.8.2 PROXY multiple exports results in SEQ_MISORDERED error on only some exports

### ISSUE THREAD

**Issue by adefewings** [nfs-ganesha/nfs-ganesha#475]
I'm trying to use 2.8.2 to proxy 7 file systems from one server, all 7 being like this in config:
EXPORT {
        Export_Id = 2;
        Path = "/nfshome/store01";
        Pseudo = "/proxy/store01";
        Access_Type = RW;
        Squash = root_squash;
        Sectype = sys;
        FSAL {
                Name = PROXY;
                Srv_Addr = 10.0.0.1;
                #Use_Privileged_Client_Port = true;
        }
}

When I startup, I find that one or two (not fixed, usually the first and second, sometimes the first and third) work OK, but the others fail like this:

ganesha.nfsd-237391[main] init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=2 Path=/nfshome/store01 FSAL_ERROR=(Invalid object type,10063)

I see that 10063 is NFS4ERR_SEQ_MISORDERED, so I was wondering if this could possible be related to the deployment of multiple exports from the same source NFS server?

Many thanks

**Comment by dang** [comment]
That's an interesting possibility.  I've never tried to run multiple PROXY exports.  There are comments in the code indicating that PROXY is not yet ready to handle multiple exports, but I don't know if they're out of date or not.  I'll poke the PROXY devs to comment.

**Comment by martinetd** [comment]
I don't know off hand, wouldn't surprise me that there are some shared variables we need to move to make this work, especially given the error
@patlucas might know better, will poke him on Monday (he should get a mail from being named here anyway)

**Comment by patlucas** [comment]
The FSAL_PROXY in V2.8.2 was using only ganesha IP adress and PID to build client id name to connect to the backend NFS server. In your use case, that is not enough to separate all the exports. They are sharing same sessions that leads to a bad mix.

To solve this problem, I submit today a new patch : 
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/467862 .

This patchs adds the export_id to build the clientid_name.

If you want to try it on 2.8.2, you can simply backport and apply this patch to a V2.8.2 Ganesha.

Regards,
Patrice LUCAS
CEA DAM/DIF/DSSI
patrice.lucas@cea.fr

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/467862

**Comment by adefewings** [comment]
Confirmed to resolve the issue when back-ported to 2.8.2.  
I've had some other trouble with the current 'next' with PROXY, can provide feedback if useful.
Cheers
Ade

**Comment by patlucas** [comment]
Hi Ade,

It is good to read that this patch solves your problem.

To test over the 'next' version, I guess you need to apply the following patch that I also developed and post yesterday during the debugging of your issue :

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/467856 .

If you're facing new trouble with the current 'next' version of Ganesha, feel free to provide feedback on it. We are always happy to know that the FSAL_PROXY is fulfilling the requirements of new users. However, we currently have not much time free to invest in debugging and developping new FSAL_PROXY features. We can't guarantee to answer quickly to your demand.

Cheers,
Patrice

**Comment by ffilz** [comment]
Closed as resolved
