### ISSUE TITLE
next branch:performs make RPM something wrong with python?

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#476]
not find，glob: /root/rpmbuild/BUILDROOT/nfs-ganesha-2.9-dev.7.el7.centos.x86_64/usr/lib/python2.7/site-packages/Ganesha/*
 not find , glob: /root/rpmbuild/BUILDROOT/nfs-ganesha-2.9-dev.7.el7.centos.x86_64/usr/lib/python2.7/site-packages/ganeshactl-*-info

![image](https://user-images.githubusercontent.com/4116773/64600288-724efd80-d3ed-11e9-998e-419de2605b04.png)

**why?**

**Comment by dang** [comment]
So, "make rpm" works for me.  What distro/version?  What cmake command are you using?

**Comment by ffilz** [comment]
Closed due to age.
