### ISSUE TITLE
about nfs-ganesha tools

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#478]
With three clients, execute the following three commands
Nfsvers = 4
Mount -o soft,intr,timeo=600,nodev,noexec,retrans=1,nfsvers=4 10.252.2.61:/bucket-10 /mnt/1
Nfsvers = 3
Mount -o soft,intr,timeo=600,nodev,noexec,retrans=1,nfsvers=3 10.252.2.61:/bucket-10 /mnt/2
Nfsvers = 4.1
Mount -o soft,intr,timeo=600,nodev,noexec,retrans=1,nfsvers=4.1 10.252.2.61:/bucket-10 /mnt/3

Does nfs-ganesha have any tools to find out which NFS version has how many clients mounted below it?

**Comment by soumyakoduri** [comment]
you may use dbus command "ShowClients" - https://github.com/nfs-ganesha/nfs-ganesha/wiki/Dbusinterface#orgganeshanfsdClientMgr

**Comment by ffilz** [comment]
Closed as resolved.
