### ISSUE TITLE
Whether to limit the number of Clients for a single Export?

### ISSUE THREAD

**Issue by xuyuqingfeng** [nfs-ganesha/nfs-ganesha#480]
EXPORT {
    CLIENT {
        Clients = 192.168.66.100;
        Access_type = RW;
    }
    SecType = sys;
    Tag = "\"..."";
    FSAL {   }
    ......
}

**Comment by dang** [comment]
I'm sorry, I don't understand the question.  Are you asking if you can limit the number of clients on an export?  Or are you asking whether we should add that feature?

We don't currently support a client limit on a per-export basis.  We have a global connection limit, but that's it.  You can implicitly limit the number of clients on an export with the CLIENT section, by specifying a CLIENT section for each set of clients you want to allow.

**Comment by ffilz** [comment]
Closing due to age. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org

**Comment by LLVIC** [comment]
> I'm sorry, I don't understand the question. Are you asking if you can limit the number of clients on an export? Or are you asking whether we should add that feature?
> 
> We don't currently support a client limit on a per-export basis. We have a global connection limit, but that's it. You can implicitly limit the number of clients on an export with the CLIENT section, by specifying a CLIENT section for each set of clients you want to allow.

Hi, you mentioned that there is  a global connection limit. Could you please introduce the limit in detail ?  Which parameter is it? Can we set it dynamically? 
Thank you!

**Comment by dang** [comment]
RPC_Max_Connections in the NFS_CORE_PARAM block.  See the ganesha-core-config man page for more.

**Comment by ffilz** [comment]
The connection limit can not be reset dynamically (without restarting Ganesha).

Note that another limit on the number of connections is the number of file descriptors allowed for the Ganesha process, and those fds may be shared with other things (like actual open files for FSAL_VFS).

**Comment by LLVIC** [comment]
> RPC_Max_Connections in the NFS_CORE_PARAM block. See the ganesha-core-config man page for more.

Thank you for the answer!

**Comment by LLVIC** [comment]
> The connection limit can not be reset dynamically (without restarting Ganesha).
> 
> Note that another limit on the number of connections is the number of file descriptors allowed for the Ganesha process, and those fds may be shared with other things (like actual open files for FSAL_VFS).

Thank you for your answer! 
Besides, I'm not sure whether I understand it exactly or not. Do you mean that RPC_Max_Connections limits the number of file descriptors allowed for the Ganesha process as well？ 
Actually, I just want to limit the number of connecting clients. Is it possible to realize?

**Comment by ffilz** [comment]
No,  RPC_Max_Connections just limits the number of file descriptors that will be used for RPC connections. Ideally we would track ALL the file descriptor use so we could assure any configured limits could actually be attained, but of course there's know way to know ALL the uses of file descriptors since a library might use file descriptors for something Ganesha has no way of tracking.

**Comment by LLVIC** [comment]
> No, RPC_Max_Connections just limits the number of file descriptors that will be used for RPC connections. Ideally we would track ALL the file descriptor use so we could assure any configured limits could actually be attained, but of course there's know way to know ALL the uses of file descriptors since a library might use file descriptors for something Ganesha has no way of tracking.

Is there any way to limit the number of  client connections？

**Comment by dang** [comment]
RPC_Max_Connections is the limit to the number of client connections.

**Comment by ffilz** [comment]
Bump to keep on page 1

**Comment by ffilz** [comment]
I'm not sure there's anything more to be done here. Closing for now.

Please re-open if you have further questions in this area.
