### ISSUE TITLE
migrate from qt4 to qt5

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#482]
qt4 is end of life and will be removed from Debian bullseye.
The same might happen in other distros.
The python scripts and corresponding dependencies in the distros should be fixed.

ganeshactl has explicit qt4 dependencies

**Comment by ffilz** [comment]
Closed as resolved with commit sha 904d6429d9e1b446a7a3a0ad70e3c2e2d0554c10
