### ISSUE TITLE
nfs-ganesha crashing too frequently

### ISSUE THREAD

**Issue by MaxDiOrio** [nfs-ganesha/nfs-ganesha#484]
Using nfs-ganesha 2.7.6-1.el7 installed on CentOS Linux release 7.7.1908 (Core)

Got nfs-ganesha configured on top of a Gluster filesystem with CTDB for IP management.

I'm getting somewhat frequent crashes leaving me without nfs on this server. I have the crashlog files generated by abrt in our Spacewalk server if they'd help at all. Just let me know what you'd like to see.

Component:	nfs-ganesha
Package:	
Crash Count:	1
Path:	/var/spool/abrt/Python-2019-09-30-11:53:03-32748
Crash UUID:	6583e0e22e3457ff068a6f2307d014b740a09858
Analyzer:	Python
Command Line:	/usr/bin/python /usr/bin/ganesha_mgr display_export 2
Executable:	/usr/bin/ganesha_mgr
Kernel:	3.10.0-1062.1.1.el7.x86_64
Reason:	ganesha_mgr_utils.py:185:DisplayExport:ValueError: too many values to unpack
Username:	root
Storage Path:	/var/satellite/systems/1/1000010222/crashes/Python-2019-09-30-11:53:03-32748
Last Modified:	2019-09-30 11:53:16.02359

ganesha_mgr_utils.py:185:DisplayExport:ValueError: too many values to unpack

Traceback (most recent call last):
  File "/usr/bin/ganesha_mgr", line 303, in <module>
    exportmgr.displayexport(sys.argv[2])
  File "/usr/bin/ganesha_mgr", line 114, in displayexport
    status, msg, reply = self.exportmgr.DisplayExport(exp_id)
  File "/usr/lib/python2.7/site-packages/Ganesha/ganesha_mgr_utils.py", line 185, in DisplayExport
    id, fullpath, pseudopath, tag = display_export_method(int(exp_id))
ValueError: too many values to unpack

Local variables in innermost frame:
display_export_method: <dbus.proxies._DeferredMethod instance at 0x7fbc31322dd0>
exp_id: '2'
self: <Ganesha.ganesha_mgr_utils.ExportMgr instance at 0x7fbc31322b48>

Component: | nfs-ganesha
-- | --
 
1
/var/spool/abrt/Python-2019-10-01-10:28:30-3928
9fbb8cd8ecd1669d2f4b894ff3c6331290bd4311
Python
/usr/bin/python /usr/bin/grace_period
/usr/bin/grace_period
3.10.0-1062.1.1.el7.x86_64
grace_period:12:<module>:IndexError: list index out of range
root
/var/satellite/systems/1/1000010222/crashes/Python-2019-10-01-10:28:30-3928
2019-10-01 10:28:37.113104

grace_period:12:<module>:IndexError: list index out of range

Traceback (most recent call last):
  File "/usr/bin/grace_period", line 12, in <module>
    ipaddr=sys.argv[1]
IndexError: list index out of range

Local variables in innermost frame:
__builtins__: <module '__builtin__' (built-in)>
__file__: '/usr/bin/grace_period'
__package__: None
sys: <module 'sys' (built-in)>
gobject: <module 'gobject' from '/usr/lib64/python2.7/site-packages/gobject/__init__.pyc'>
__name__: '__main__'
__doc__: None
print_function: _Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)

**Comment by dang** [comment]
I'm confused.  This is a crash in ganesha_mgr.py, which is not part of Ganesha itself, but is a convenience script for managing Ganesha.  It should have no effect on Ganesha, and Ganesha should be running fine.  (The issue with the script is a bug, and should be fixed, but it shouldn't be causing a failure in Ganesha)

**Comment by malahal** [comment]
We did fix few python3/2 related issues in upstream, but not sure there are
there in Ganesha2.7.6. As Dan said that is just a script crash, not a
daemon crash though.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
