### ISSUE TITLE
Update online docs

### ISSUE THREAD

**Issue by djasa** [nfs-ganesha/nfs-ganesha#488]
Hi. Docs on https://github.com/nfs-ganesha/nfs-ganesha/wiki/Docs say:
> == Version 2.0 ==
> This version is in active development and is not considered stable enough for
> production use.  Its documentation is still incomplete.

with all the docs there probably still relevant to 1.5

Page at https://nfs-ganesha.github.io/ is somewhat more recent:
> NEWS
> 
> NFS-Ganesha V 2.1 is now available. Check out the nfs-ganesha project page for more details details including the Release Notes.

While the actual latest version is 2.8.

I get that keeping docs up-to-date is a challenge but if it is impossible to do so, you could at least cut the woefully outdated content and link to e.g. manual pages (provided they're better maintained than the web…).

**Comment by kalebskeithley** [comment]
fixed
