### ISSUE TITLE
Stale file handle on HA setup

### ISSUE THREAD

**Issue by xelexin** [nfs-ganesha/nfs-ganesha#490]
Hi,
I set up HA nfs-ganesha environment with 2.7.6 version. I am using rados as recovery backend to enable active/passive configuration. When I mount the share and then change active ganesha (move virtual ip address) I get stale file handle error.
`root@test-ha-rw:/home/ubuntu# ls /mnt
ls: cannot access '/mnt': Stale file handle`

ganesha.conf
`NFS_Core_Param
{
    NFS_Port = 2049;
    MNT_Port = 23750;
    NLM_Port = 23751;
    Enable_NLM = false;
    Enable_RQUOTA = false;
    Protocols = 4;
}
NFSv4
{
    RecoveryBackend = rados_cluster;
    Minor_Versions = 1,2;
}
CACHEINODE {
    Dir_Chunk = 0;
    NParts = 1;
    Cache_Size = 1;
}
RADOS_KV
{
    pool = "cephfs_metadata";
    namespace = "ganesha";
    nodeid = "control01";
    userud = "gcontrol01";
}`

`root@control03:/home/rwadolowski# ganesha-rados-grace --ns ganesha --pool cephfs_metadata 
cur=2 rec=1
control01	 E
control02	NE
control03	 E`

I moved IP from control02 to control01 by disabling nfs-ganesha ( set up with keepalived).
Logs from control01, when I execute `ls` on root of mount [logs](https://pastebin.com/ueSEzagg)

In this setup, the nfs-ganesha should work on 3 nodes and just waiting for IP or it should be started with keepalived? What causes the file stale handle in this case? Maybe nfs-ganesha has problems with using rados recovery backend?

**Comment by malahal** [comment]
Export definitions should match at all nodes. In particular, the export-id should be same on all nodes for the export as export-id becomes part of the file handle.

**Comment by xelexin** [comment]
Okey, but where the export-id is stored? On RADOS KV ? On ceph I see strange key value for host
`6746052350974099457
value (57 bytes) :
00000000  3a 3a 66 66 66 66 3a 31  30 2e 31 33 31 2e 36 36  |::ffff:10.131.66|
00000010  2e 31 35 35 2d 28 33 31  3a 4c 69 6e 75 78 20 4e  |.155-(31:Linux N|
00000020  46 53 76 34 2e 31 20 74  65 73 74 2d 6d 61 6e 69  |FSv4.1 test-mani|
00000030  6c 61 2d 68 61 2d 72 77  29                       |la-ha-rw)|
00000039
`
What does value 6746052350974099457 mean? I can't find code responsible for that

**Comment by malahal** [comment]
Look at your Ganesha process. "-f" option takes Ganesha config file. Usually it is /etc/ganesha/ganesha.conf. This may have some include files which need to be looked into too.

For example on my system, for export "/gpfs/gpfsA/A2"

export {
        **export_id = 22;**
        path = /gpfs/gpfsA/A2;
        pseudo = /gpfs/gpfsA/A2;
        FSAL {
                name = GPFS;
        }
        CLIENT {
                clients = *;
                access_type = RW;
        }
}

**Comment by ffilz** [comment]
Closing due to age. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
