### ISSUE TITLE
about fsal_pseudo

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#491]
How do you understand fsal_pseudo?

**Comment by dang** [comment]
FSAL_PSEUDO implements the NFSv3 Pseudo filesystem.  NFSv3 used the Mount protocol to specify which export to mount; NFSv4, on the other had, has a single real export at / that is a virtual filesystem, and exports are mounted at various paths in that filesystem.  This filesystem is called the Pseudo filesystem, and is implemented in Ganesha via FSAL_PSEUDO.  It's not a real FSAL, in that you can't use it for exports (use FSAL_MEM for memory based exports).

**Comment by dang** [comment]
Sorry, NFSv4 pseudo filesystem

**Comment by fantastic2085** [comment]
thank you very much
