### ISSUE TITLE
how to specify file system mount？

### ISSUE THREAD

**Issue by Mr-Chengcheng** [nfs-ganesha/nfs-ganesha#493]
Currently ceph already supports multi-file system generation.but，how does ganesha export the specified file system?Currently ganesha exports the first file system by default.

**Comment by dang** [comment]
There's a Filesystem config option in the FSAL_CEPH block in the export.  See the man page:
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-ceph-config.rst

**Comment by Mr-Chengcheng** [comment]
Sorry, I don’t understand the manual.can I set /etc/ganesha/ceph.conf like:
EXPORT
{
        FSAL{
                Name(string,"Ceph");
                Filesystem(string,testcephfs1);
        }
}

I used the "strace" tool to find that the file "/etc/ganesha/ceph.conf" is not open.

ganesha.nfsd /etc/ganesha/ganesha.conf  -L /var/log/nfs-ganesha.logganesha.log -N NIV_DEBUG

**Comment by Mr-Chengcheng** [comment]
First of all, thank you for your answer.but，
sorry, I don’t understand the manual.can I set /etc/ganesha/ceph.conf like:
EXPORT
{
FSAL{
Name(string,"Ceph");
Filesystem(string,testcephfs1);
}
}

I used the "strace" tool to find that the file "/etc/ganesha/ceph.conf" is not open.

ganesha.nfsd /etc/ganesha/ganesha.conf -L /var/log/nfs-ganesha.logganesha.log -N NIV_DEBUG

**Comment by dang** [comment]
Ganesha's config goes in /etc/ganesha/ganesha.conf by default.  You can override this on the ganesha command line, or %include other files in that file.

**Comment by Mr-Chengcheng** [comment]
First of all, thank you for your answer.
My ceph cluster mount can not be read or written after ganesha export, the prompt is not enough permissions. 
but,read and write permissions have been added
[root@ceph-node1 testcephfs]# mount |grep ceph
192.168.56.102:/ on /mnt/testcephfs type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.56.102,local_lock=none,addr=192.168.56.102)

Have you encountered this situation? Can you give me some tips?

best wishes to you！

**Comment by Mr-Chengcheng** [comment]
First of all, thank you for your answer.but，
nfs-ganesha/src/config_samples/ceph.conf doesn‘t contain %include or %url line. Is it not supported to insert other files? And，ganesha export failed after I manually added it

**Comment by dang** [comment]
Ganesha does not read /etc/ganesha/ceph.conf.  It only reads /etc/ganesha/ganesha.conf.  You need to either put all your config in that file, or put a %include in that file pointing to another file.

**Comment by ffilz** [comment]
Closing as resolved. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
