### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mwang911** [nfs-ganesha/nfs-ganesha#495]
1.
![1](https://user-images.githubusercontent.com/15031375/67231734-80734d80-f472-11e9-8b93-9087dba518bc.png)

shouldn't this be dir_fh ? 

2. In function mdcache_unexport, when it executes mdcache_lru_ref and unlock mdc_exp_lock. Is there the possibility that the entry is cleaning by function mdc_clean_entry ?  And then the locks will be destroyed, mdcache_unexport will ruin the process when get wrlock of entry attr_lock.

**Comment by dang** [comment]
1. Yes, you're probably right.
2. No, the LRU_REQ_INITIAL takes the lane lock, protecting it against a race with the LRU thread, and the refcount then protects against cleanup.

**Comment by mwang911** [comment]
> 1. Yes, you're probably right.
> 2. No, the LRU_REQ_INITIAL takes the lane lock, protecting it against a race with the LRU thread, and the refcount then protects against cleanup.

Imagine this, one thread is executing lru_try_reap_entry and successfully find an entry to recycle. After  unlock qlane, the ref is 1 and the entry not in cih and not in any queue. Then it start to execute mdcache_lru_clean which will unpack the mappping between export and entry. It needs entry->attr_lock and export->mdc_exp_lock to finish it. Meantime, another thread is executing mdcache_unexport, it gets mdc_exp_lock and ref this entry(which I think ref has no use left), then unlock mdc_exp_lock to get entry->attr_lock, the ref is 2 now. 
At this time, the  first thread get mdc_exp_lock and successfully unpack this entry with export, then it starts to destroy locks of this entry. After this, the second thread will  get a bad entry attr_lock.

**Comment by ffilz** [comment]
Closing due to age. Note that as a code question rather than a bug report, this might have been a better subject for the development mailing list, devel@lists.nfs-ganesha.org
