### ISSUE TITLE
keytab verification fails

### ISSUE THREAD

**Issue by xingyong** [nfs-ganesha/nfs-ganesha#496]
Branch: V2.8-stable

I have deployed kerberos and verified it works. I can use the test account to login as follows.
        kinit -kt  /root/test.keytab  test@HOME.CN

Now, I want ganesha server to use this account. The configuration file has a section:
        NFS_KRB5 {
              PrincipalName = "test";
              KeytabPath = "/root/test.keytab";
              CCacheDir = "/var/run/ganesha";
              Active_krb5 = true;
        }

But, when the ganesha server starts, it fails to verify the account because this krb5 api return 2.
          code = krb5_kt_get_entry(context, kt, princ, 0, 0, kte);
          (The function find_keytab_entry() in RPCAL/gss_credcache.c)
code 2 means "No such file or directory".

Is there something I have missed to deploy?

**Comment by sachinpunadikar** [comment]
Below patch should help.
https://github.com/nfs-ganesha/nfs-ganesha/commit/b4b95e73ec6ea73bba980d8b31e840fb0f85f4a6

**Comment by malahal** [comment]
Yes, just ganesha3.0 has the fix. Request a back to V2.8 if you need it.

**Comment by ffilz** [comment]
Is this still an issue? V2.8 is close to end of life, can you upgrade to V3.0?

Proactively closing as unlikely to fix in V2.8 but is fixed in V3.x
