### ISSUE TITLE
NFSv3 in udp mode hungs on close

### ISSUE THREAD

**Issue by kvaps** [nfs-ganesha/nfs-ganesha#498]
Hi,

My share is mounted with `vers=3,udp,nolock,noatime` options:
```
cat /proc/mounts | grep log
10.102.69.203:/export/pvc-496514c8-4d8b-459e-81d4-1d8bfc82e30c/log /var/log/one nfs rw,noatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=10.102.69.203,mountvers=3,mountport=20048,mountproto=udp,local_lock=all,addr=10.102.69.203 0 0
```

When I start application it hangs forever on close operation:

```
openat(AT_FDCWD, "/var/log/one/oned.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
close(3)                                = 0
openat(AT_FDCWD, "/var/log/one/oned.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 3
lseek(3, 0, SEEK_END)                   = 0
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
writev(3, [{iov_base="Fri Oct 25 22:53:15 2019 [Z0][ON"..., iov_len=39}, {iov_base="Starting OpenNebula 5.8.5\n------"..., iov_len=12453}], 2) = 12492
write(3, "\n", 1)                       = 1
close(3
```

Ganesha log says:
```
25/10/2019 22:53:15 : epoch 5db37b91 : opennebula-temp-nfs-server-provisioner-0 : nfs-ganesha-20[svc_5] nfs_dupreq_put_drc :DUPREQ :CRIT :drc 0x7f51a303daa8 refcnt will underrun refcnt=0
```

The weird thing that other non-c written applications are working fine with this share.

Any ideas?

**Comment by malahal** [comment]
udp DRC refcounts were broken in some versions. What version are you using? Your ganesha.log message is related to the following commit, but if I recall, that was just an annoying but harmless message without any actual hang. You need to collect tcpdump and analyse. If it is easy to recreate, we can recreate and fix it but please tell us the exact version.

commit 92f2b7e289c7002429647af93392ee6f97f1170f
Author: Malahal Naineni <malahal@us.ibm.com>
Date:   Fri Aug 2 18:38:21 2019 +0530

    Fix refcnt on shared UDP DRC

**Comment by kvaps** [comment]
Hi, thanks for the quick response!

I was  using 2.8.2 in part of nfs-server-provisioner project:

https://github.com/kubernetes-incubator/external-storage/blob/478f87a98af979218f8de706b303c4e79dadf5ea/nfs/deploy/docker/Dockerfile#L21-L34


I was able to reproduce it on 3.0-rc4, but there were another error.

My configuration includes static ports for nfs-ganesha and IPVS balancer on the client side.
Today I'll collect more details and tcpdump.

**Comment by kvaps** [comment]
Hi, I made three captures, nfs-server is `10.112.4.98`

First two is running command:
```bash
for i in `seq 1 100`; do echo "Hello World $i!" >> oned.log; done
```
1.pcap
![image](https://user-images.githubusercontent.com/7556217/67627132-f3a40780-f856-11e9-9767-48d4c623b120.png)

2.pcap
![image](https://user-images.githubusercontent.com/7556217/67627143-2817c380-f857-11e9-9ec8-50adb0f33610.png)

Third one is running c-written application from the first post:

3.pcap
![image](https://user-images.githubusercontent.com/7556217/67627171-847ae300-f857-11e9-96b9-c5e2aa3266e1.png)

All captures in attachment:
[1.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/3775345/1.zip)

Version information
```bash
# ganesha.nfsd -v
NFS-Ganesha Release = V2.8.2
# uname -r
4.15.18-18-pve
```

And I still not understand why nfs-client is not trying to reestablish connection, it just stucks and does not trying to send any packets anymore.

**UPD**: I have the same problem on  `2.7.6` and `2.6.3` versions.

**Comment by dang** [comment]
That log indicates that there's definitely a bug in DRC somewhere.  Interestingly enough, all three traces end with a GETATTR reply, so the reply is sent correctly, and the client never sends anything else.

So the log indicates a ganesha bug, but the pcaps indicate a client bug.  There may be two separate issues here. 
Is there any way you could switch to TCP?  UDP is rarely used, and therefore not well tested.  In fact, the community is considering deprecating it entirely.  Switching to TCP would get you to a different implementation of DRC, which should get you past that error.

**Comment by kvaps** [comment]
OK I understood.

I was try using udp as workaround to avoid another bug kubernetes/kubernetes#84322 but probably it wasn't good idea due its deprecation.

Thanks!

**Comment by ffilz** [comment]
Closed as resolved.
