### ISSUE TITLE
Ganesha V2.0: Export with missing path leads to segfault in mnt_Mnt()

### ISSUE THREAD

**Issue by ExaTad** [nfs-ganesha/nfs-ganesha#50]
With Ganesha V2.0, I have an export config that refers to a path that does not exist.

During initialization, the share config parsing spits out the error:

`07/08/2014 10:33:42 : epoch 53e3b876 : oneblox-0062 : ganesha.nfsd-5219[main] nfs_export_get_root_entry :NFS STARTUP :CRIT :Lookup failed on path, ExportId=1 Path=/exports/Public FSAL_ERROR=(No such file or directory,2)
`

When mounting by tag (I haven't verified if this is a problem when mounting by path), there is an indirection through `p_current_item->exp_root_cache_inode` which as it turns out is a `NULL` pointer.  This results in a Ganesha Segfault.

Unfortunately we are not in a position to move to Ganesha V2.1 currently, so I can't verify if this is also a problem there.

The patch here fixes the Ganesha V2.0 crash:
```diff
diff --git a/src/Protocols/NFS/mnt_Mnt.c b/src/Protocols/NFS/mnt_Mnt.c
index a408de6..3cf75aa 100644
--- a/src/Protocols/NFS/mnt_Mnt.c
+++ b/src/Protocols/NFS/mnt_Mnt.c
@@ -116,6 +116,7 @@ int mnt_Mnt(nfs_arg_t *arg, exportlist_t *export,
        LogEvent(COMPONENT_NFSPROTO,
                 "MOUNT: Export entry for %s not found", arg->arg_mnt);
 
+ notfound:
        /* entry not found. */
        /* @todo : not MNT3ERR_NOENT => ok */
        switch (req->rq_vers) {
@@ -163,6 +164,13 @@ int mnt_Mnt(nfs_arg_t *arg, exportlist_t *export,
         * retrieve the associated NFS handle
         */
        if (!ispath || !strcmp(arg->arg_mnt, p_current_item->fullpath)) {
+               if (p_current_item->exp_root_cache_inode == NULL) {
+                       LogCrit(COMPONENT_NFSPROTO,
+                               "MOUNT: Export entry %s has no root cache inode (path missing?)",
+                                p_current_item->fullpath);
+                       goto notfound;
+               }
+       
                pfsal_handle = p_current_item->exp_root_cache_inode->obj_handle;
        } else {
                exp_hdl = p_current_item->export_hdl;
```

**Comment by ffilz** [comment]
Do you still see this issue with V2.2.0 or later? I think this has been fixed.

If there is still an issue, please open a Red Hat Bugzilla:

https://bugzilla.redhat.com/enter_bug.cgi?product=nfs-ganesha
