### ISSUE TITLE
Not able to install nfs-ganesha-utils-2.8.2-2.el7.x86_64 is missing  gpfs.nfs-ganesha

### ISSUE THREAD

**Issue by borisbardak** [nfs-ganesha/nfs-ganesha#500]
I am not able to install  nfs-ganesha-utils-2.8.2-2.el7.x86_64. I get this error.

Error: Package: nfs-ganesha-utils-2.8.2-2.el7.x86_64 (/nfs-ganesha-utils-2.8.2-2.el7.x86_64)
           Requires: gpfs.nfs-ganesha = 2.8.2-2.el7

What provides this gpfs.nfs-ganesha = 2.8.2-2.el7 ?!?

I already have installed

[root@ganesha-server1 opt]# rpm -qa |grep gane
nfs-ganesha-ceph-2.8.2-2.el7.x86_64
nfs-ganesha-2.8.2-2.el7.x86_64

**Comment by dang** [comment]
nfs-ganesha-gpfs should provide that.

**Comment by kalebskeithley** [comment]
nfs-ganesha-gpfs does provide it, but there's a mistake in the
nfs-ganesha.spec used to build the CentOS Storage SIG packages and it wants
a package named gpfs.nfs-ganesha, which doesn't exist (outside of IBM's
product.)

Over in Fedora I've even removed the Requires on nfs-ganesha-gpfs (or
gpfs.nfs-ganesha) as the utils can be used without gpfs installed and
there's no real reason to have required it in the first place.

**Comment by malahal** [comment]
Looks like we need to backport
commit a28a854c94eea5ea3f6a0ed0cfbf28782d5d19f7 to 2.8 stream. You can also
remove "gpfs." in all occurrences of "gpfs.nfs-ganesha"
in src/nfs-ganesha.spec-in.cmake.

**Comment by dang** [comment]
I'm planning on doing another 2.8 once 3.0 is finalized.

**Comment by kalebskeithley** [comment]
In the mean time I've respun the packages in the Storage SIG.  New packages will be in the testing repos by tomorrow and on the mirrors when they sync (probably next monday)

**Comment by borisbardak** [comment]
Ok, TNX!

**Comment by kalebskeithley** [comment]
I respun the packages. They updated packages are on the CentOS mirrors now.
