### ISSUE TITLE
Changed Graceperiod from 60 to 90 sec does not happen in the ibm2.7 branch

### ISSUE THREAD

**Issue by ps20renar** [nfs-ganesha/nfs-ganesha#502]
Hallo All,
the Change in https://github.com/ganltc/nfs-ganesha/commit/df2c20aab995fcdb2a00308982f06d915ddfe741 was not pushed to the ganesha log.
we are using now this with scale release 5.0.4. But in the ganesha-log this Change doesn't happend in the log.
29/10/2019 15:19:10 : epoch 000500a2 : gpfs.ganesha.nfsd-12116[main] main :MAIN :EVENT :gpfs.ganesha.nfsd Starting: Ganesha Version /home/ppsbld/workspace/SS_5.0.4_tac/Build_Prod/Ganesha_5.0.4_ProdBuild/label/BLDLNX79_X86_64_REDHAT_7.0.0/ganesha-rpmdir/BUILD/nfs-ganesha-2.7.5-ibm053.00, built at Oct 7 2019 13:40:00 on bldlnx79
..
2019-10-29 15:19:11 : epoch 000500a2 :  : gpfs.ganesha.nfsd-12120[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 60
Regards Renar

**Comment by malahal** [comment]
That is most likely due to your config overwriting the default 90 seconds then. Make sure you don't set grace period explicitly in your config (check /var/mmfs/ces/nfs-config/gpfs.ganesha.main.conf).

**Comment by malahal** [comment]
This should go to https://github.com/ganltc/nfs-ganesha/issues though.

**Comment by ps20renar** [comment]
Hallo malahal,
you are Right. The ganesha config has it override. Thanks for the hint.
Regards Renar
