### ISSUE TITLE
segment fault: chunk is null in mdcache_readdir_chunked 

### ISSUE THREAD

**Issue by yangruifeng** [nfs-ganesha/nfs-ganesha#504]
#0  0x00007f5543ff549b in raise () from /lib64/libpthread.so.0
#1  0x00007f55309f6fc3 in handle_fatal_signal_base(int, bool) () from /lib64/librgw.so.2
#2  <signal handler called>
#3  0x00007f5545e3eb7d in lru_bump_chunk (chunk=0x0) at /usr/src/debug/nfs-ganesha-3.0-rc3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:2092
#4  0x00007f5545e357f3 in mdcache_readdir_chunked (directory=0x6966d00, whence=4119696775366012901, dir_state=0x7f550be9db40, cb=0x7f5545d1c1d4 <populate_dirent>, attrmask=122830, eod_met=0x7f550be9dfcb)
    at /usr/src/debug/nfs-ganesha-3.0-rc3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3113
#5  0x00007f5545e1eb6f in mdcache_readdir (dir_hdl=0x6966d38, whence=0x7f550be9db20, dir_state=0x7f550be9db40, cb=0x7f5545d1c1d4 <populate_dirent>, attrmask=122830, eod_met=0x7f550be9dfcb)
    at /usr/src/debug/nfs-ganesha-3.0-rc3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:559
#6  0x00007f5545d1cbac in fsal_readdir (directory=0x6966d38, cookie=4119696775366012901, nbfound=0x7f550be9dfcc, eod_met=0x7f550be9dfcb, attrmask=122830, cb=0x7f5545e0a01a <nfs3_readdirplus_callback>,
    opaque=0x7f550be9df20) at /usr/src/debug/nfs-ganesha-3.0-rc3/FSAL/fsal_helper.c:1166
#7  0x00007f5545e09c88 in nfs3_readdirplus (arg=0x2338bd8, req=0x2338400, res=0x72f4780) at /usr/src/debug/nfs-ganesha-3.0-rc3/Protocols/NFS/nfs3_readdirplus.c:297
#8  0x00007f5545cf4372 in nfs_rpc_process_request (reqdata=0x2338400) at /usr/src/debug/nfs-ganesha-3.0-rc3/MainNFSD/nfs_worker_thread.c:1492
#9  0x00007f5545cf46bf in nfs_rpc_valid_NFS (req=0x2338400) at /usr/src/debug/nfs-ganesha-3.0-rc3/MainNFSD/nfs_worker_thread.c:1617
#10 0x00007f5545a9cb41 in svc_vc_decode (req=0x2338400) at /usr/src/debug/nfs-ganesha-3.0-rc3/libntirpc/src/svc_vc.c:901
#11 0x00007f5545a98a8e in svc_request (xprt=0x54c0d00, xdrs=0x1086dc80) at /usr/src/debug/nfs-ganesha-3.0-rc3/libntirpc/src/svc_rqst.c:1205
#12 0x00007f5545a9ca52 in svc_vc_recv (xprt=0x54c0d00) at /usr/src/debug/nfs-ganesha-3.0-rc3/libntirpc/src/svc_vc.c:874
#13 0x00007f5545a98a0f in svc_rqst_xprt_task_recv (wpe=0x54c0f30) at /usr/src/debug/nfs-ganesha-3.0-rc3/libntirpc/src/svc_rqst.c:1186
#14 0x00007f5545a99590 in svc_rqst_epoll_loop (wpe=0x237a698) at /usr/src/debug/nfs-ganesha-3.0-rc3/libntirpc/src/svc_rqst.c:1570
#15 0x00007f5545aa3d4b in work_pool_thread (arg=0x34431b440) at /usr/src/debug/nfs-ganesha-3.0-rc3/libntirpc/src/work_pool.c:184
#16 0x00007f5543feddd5 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f55433b4ead in clone () from /lib64/libc.so.6

**Comment by ffilz** [comment]
Is this still an issue? Which version of Ganesha? It may have been resolved.

Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
