### ISSUE TITLE
FSAL_RGW write issue

### ISSUE THREAD

**Issue by fanzi2009** [nfs-ganesha/nfs-ganesha#507]
@mattbenjamin 
I tried to write files through FSAL_RGW and it's successful. But after a little while,
I found all the file size become 0. I just follow the writing logic for FSAL_RGW. I found
the `RGW_OPEN_FLAG_V3` is only set when state (which is a parameter rgw_fsal_open2() in )
is NULL. However, it seems that the `state` is always NOT NULL. When I changed the code
to transfer RGW_OPEN_FLAG_V3 into rgw_open, the issue is gone.

```
rc = rgw_open(export->rgw_fs, handle->rgw_fh, posix_flags,
(!state) ? RGW_OPEN_FLAG_V3 : RGW_OPEN_FLAG_NONE);
```
My test envirnment is nfs-ganesha 2.7 + ceph 13.2

**Comment by dang** [comment]
We think mimic (13.x) is broken right now, and needs more fixes backported.  Can you try the latest Nautilus (14.2.4)?  That should have all the fixes.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
