### ISSUE TITLE
FSAL_RGW showmount -e nfs does not show buckets

### ISSUE THREAD

**Issue by f1-outsourcing** [nfs-ganesha/nfs-ganesha#508]
`showmount -e nfs `

only shows me the cephfs mounts.

**Comment by dang** [comment]
Can you post your config?

**Comment by f1-outsourcing** [comment]
EXPORT {
        Export_ID=303;
        Path = "/test";
        Pseudo = "/rgwtest";
        Protocols = 4;
        FSAL { Name = RGW; User_Id = "xxxx"; Access_Key_Id = "TESTER"; Secret_Access_Key = "xxx"; }
        Disable_ACL = TRUE;
        CLIENT { Clients = x.x.x.0/24; access_type = "RW"; }
}

**Comment by dang** [comment]
It's set to "Protocols = 4".  This means it's not exported via NFSv3, and the MNT protocol (used by showmounts) is only part of NFSv3.  You can mount "/" via NFSv4, and list the directory, and it will show all exports that are using NFSv4.

**Comment by malahal** [comment]
To list all exports, you can run ganesha command:

ganesha_mgr show exports or ganesha_mgr show_exports

**Comment by malahal** [comment]
showmount (NFSv3) or (mount and look into dirs for NFSv4) can only list exports that the client can see.

**Comment by f1-outsourcing** [comment]
> 
> 
> showmount (NFSv3) or (mount and look into dirs for NFSv4) can only list exports that the client can see.

That is not correct, or ganesha did not correclty implement this.

```
[@ ganesha]# showmount -e nfs| grep scripts
/cblr-scripts   192.168.10.2/32
[@ ganesha]# ifconfig | grep 192.168.10
        inet 192.168.10.111  netmask 255.255.255.0  broadcast 192.168.10.255
        inet 192.168.10.202  netmask 255.255.255.0  broadcast 192.168.10.255
        inet 192.168.10.58  netmask 255.255.255.0  broadcast 192.168.10.255
[@ ganesha]#
```

**Comment by f1-outsourcing** [comment]
> 
> 
> It's set to "Protocols = 4". This means it's not exported via NFSv3, and the MNT protocol (used by showmounts) is only part of NFSv3. You can mount "/" via NFSv4, and list the directory, and it will show all exports that are using NFSv4.

Yes indeed cephfs exports include v.3, when I enable this on the rgw, it is shown

**Comment by malahal** [comment]
> > showmount (NFSv3) or (mount and look into dirs for NFSv4) can only list exports that the client can see.
> 
> That is not correct, or ganesha did not correclty implement this.
> 
> ```
> [@ ganesha]# showmount -e nfs| grep scripts
> /cblr-scripts   192.168.10.2/32
> [@ ganesha]# ifconfig | grep 192.168.10
>         inet 192.168.10.111  netmask 255.255.255.0  broadcast 192.168.10.255
>         inet 192.168.10.202  netmask 255.255.255.0  broadcast 192.168.10.255
>         inet 192.168.10.58  netmask 255.255.255.0  broadcast 192.168.10.255
> [@ ganesha]#
> ```

If you can't mount /cblr-scripts  from server "nfs" using NFSv3 but the export  is shown in "showmount" output, then this is a bug. It is hard to see if the client can mount or not using the simple showmount output there though.

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by xiaoluo260** [comment]
> It's set to "Protocols = 4". This means it's not exported via NFSv3, and the MNT protocol (used by showmounts) is only part of NFSv3. You can mount "/" via NFSv4, and list the directory, and it will show all exports that are using NFSv4.

if set to "protocols = 3,4" , showmount -e can list  ganesha export, but nfs-server can't list(/etc/exports) ,if nfs-client based on nfsv3, it can't mounted ;Is there any way to solve this problem？

**Comment by dang** [comment]
I'm confused.  /etc/exports has nothing to do with Ganesha, it's for knfsd.  Are you saying that if you set "Protocols = 3,4" then you can't mount at all?

**Comment by ffilz** [comment]
Maybe we need a complete restatement of the issue. It would also help to have the config file.

**Comment by ffilz** [comment]
With no action on this in nearly 30 days, I am going to close this as resolved. Please re-open if it is still an issue on a currently supported version of Ganesha.
