### ISSUE TITLE
FSAL_RGW mount vs s3cmd speed

### ISSUE THREAD

**Issue by f1-outsourcing** [nfs-ganesha/nfs-ganesha#509]
I always under the impression that copying files with nfs-ganesha would be faster than the s3cmd using rados gateway (tested here with beast) .  I am not sure if this actually true, I did some primitive tests, trying not to use caches and there seems to be a significant difference eg. when reading.

```
[@~]$ s3cmd -c .s3cfg.tester1 get s3://test/test.bin /dev/null --continue
download: 's3://test/test.bin' -> '/dev/null'  [1 of 1]
  5960368128 of 10557568372    56% in   66s    85.35 MB/s^CSee ya!
```
When I copy with mc a file from the nfs share to /dev/null I am dropping quickly to 35MB/s

Does ganesha require some tuning to speed up transfers? Maybe the beast radosgw http is getting better objects in parallel?

**Comment by mattbenjamin** [comment]
I don't really know the expected perf delta.  Recent versions are faster than S3 for -listing-, but we've not tested NFS vs S3 upload.  (That said, S3 streaming upload, esp. multipart, has potential to be faster than NFS.  Ensure that NFS is using a read-write size of at least 1M.)

Matt

**Comment by ffilz** [comment]
Closing as resolved.
