### ISSUE TITLE
Questions regarding PROXY fsal and nfsv3

### ISSUE THREAD

**Issue by ghost** [nfs-ganesha/nfs-ganesha#512]
Hi, I need to setup a server that will act as an NFS proxy between the real NFS server and the clients. The "real" server is exporting as NFSv3. The clients will also use NFSv3. How should I setup my proxy server to connect and serve as NFSv3? Already tried but got errors like "Export entry / does not support NFS v3 for client" etc.
nfs_server_v3 <--> nfs-ganesha <--> clients_v3

Thanks

**Comment by dang** [comment]
FSAL_PROXY will currently only talk to an NFSv4 server, not an NFSv3 server.

**Comment by ghost** [comment]
Ok thanks for the reply!
