### ISSUE TITLE
Partial dir list or triplicated entries on 2.8.1.2 and FSAL RGW

### ISSUE THREAD

**Issue by quizac-** [nfs-ganesha/nfs-ganesha#513]
Hi,

Symptoms are similar to https://github.com/nfs-ganesha/nfs-ganesha/issues/341, although, directory listing is limited to either 50 entries(50 unique filenames) or 150 entries with 50 unique filenames. Ceph is running Nautilus v14.2.4 with libcephfs2-14.2.4-0.el7.x86_64

/etc/ganesha/ganesha.conf:
```
NFS_CORE_PARAM {
    Bind_Addr = 10.10.0.54; # keepalived vmac interface
    NFS_Port = 2049;
    MNT_Port = 20048;
    Enable_NLM = false;
    Enable_RQUOTA = false;
}

EXPORT_DEFAULTS {
    Attr_Expiration_Time = 0;
    Access_Type = RW;
    Protocols = 3,4; # v3 and UDP are enabled in order for showmount work but mounted as v4.1/TCP
    SecType = sys;
    Squash = No_Root_Squash;
}

MDCACHE {
    Cache_Size = 1;
    Dir_Chunk = 0;
    NParts = 1;
}

NFSv4 {
    Allow_Numeric_Owners = true;
    Delegations = true;
    Grace_Period = 20;
    Lease_Lifetime = 10;
    Minor_Versions =  1,2;
    RecoveryBackend = rados_ng;
}

NFS_KRB5
{
    Active_krb5 = no;
}

RADOS_KV {
    ceph_conf = '/etc/ganesha/ceph.conf';
    userid = "admin";
    pool = "ganesha";
}

RGW {
    ceph_conf = "/etc/ganesha/ceph.conf";
    cluster = "ceph";
    name = "client.rgw.ecmds1";
}

LOG {
    Components {
        ALL = FULL_DEBUG;
     }
    Facility {
        name = FILE;
        destination = "/var/log/ganesha/ganesha.log";
        enable = active;
    }
    Format {
        CLIENTIP = true;
        HOSTNAME = false;
        PROGNAME = false;
    }
}


# RGW exports
EXPORT
{
    Export_id=1943;
    Path = "/";
    Pseudo = /;

    FSAL {
        Name = RGW;
        User_Id = "benchmark";
        Access_Key_Id = "YTCWP6YSERKJ273ZYCRL";
        Secret_Access_Key = "qFAbMd0UEvquvB18zn9RtbFdI8N3BAK3FHb4hm1Y";
    }
}
```

# mount -t nfs -o nfsvers=4.1,soft,sync,proto=tcp cephnfs:/ benchmark
# ll benchmark/benchmark/xeur
total 322917
-rw-rw---- 1 root root  8866964 Sep  6 16:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.144_59000-00000000.pcap.xz
-rw-rw---- 1 root root  1343620 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.144_59000-00000001.pcap.xz
-rw-rw---- 1 root root 19021928 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.145_59001-00000000.pcap.xz
-rw-rw---- 1 root root  3036592 Sep  6 16:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.148_59032-00000000.pcap.xz
-rw-rw---- 1 root root  1442680 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.148_59032-00000001.pcap.xz
-rw-rw---- 1 root root    96384 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.149_59033-00000000.pcap.xz
-rw-rw---- 1 root root  4231496 Sep  6 16:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.152_59032-00000000.pcap.xz
-rw-rw---- 1 root root  1675620 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.152_59032-00000001.pcap.xz
-rw-rw---- 1 root root  4471232 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.153_59033-00000000.pcap.xz
-rw-rw---- 1 root root  6238136 Sep  6 12:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.32_59000-00000000.pcap.xz
-rw-rw---- 1 root root  6274768 Sep  6 15:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.32_59000-00000001.pcap.xz
-rw-rw---- 1 root root  6077640 Sep  6 19:00 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.32_59000-00000002.pcap.xz
-rw-rw---- 1 root root  2600932 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.32_59000-00000003.pcap.xz
-rw-rw---- 1 root root  3230884 Sep  6 16:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.32_59032-00000000.pcap.xz
-rw-rw---- 1 root root  1508472 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.32_59032-00000001.pcap.xz
-rw-rw---- 1 root root  3126924 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.33_59001-00000000.pcap.xz
-rw-rw---- 1 root root   316372 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.33_59033-00000000.pcap.xz
-rw-rw---- 1 root root 10525348 Sep  6 11:12 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000000.pcap.xz
-rw-rw---- 1 root root  9407344 Sep  6 12:25 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000001.pcap.xz
-rw-rw---- 1 root root 11768436 Sep  6 13:39 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000002.pcap.xz
-rw-rw---- 1 root root 10456512 Sep  6 14:52 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000003.pcap.xz
-rw-rw---- 1 root root  9316964 Sep  6 16:09 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000004.pcap.xz
-rw-rw---- 1 root root  7039176 Sep  6 17:20 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000005.pcap.xz
-rw-rw---- 1 root root  5095404 Sep  6 18:35 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000006.pcap.xz
-rw-rw---- 1 root root  4737956 Sep  6 19:50 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000007.pcap.xz
-rw-rw---- 1 root root  1694704 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.34_59000-00000008.pcap.xz
-rw-rw---- 1 root root 45224572 Sep  6 13:58 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.35_59001-00000000.pcap.xz
-rw-rw---- 1 root root 21229756 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.35_59001-00000001.pcap.xz
-rw-rw---- 1 root root  5591104 Sep  6 11:25 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000000.pcap.xz
-rw-rw---- 1 root root  5742704 Sep  6 12:54 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000001.pcap.xz
-rw-rw---- 1 root root  5527396 Sep  6 14:22 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000002.pcap.xz
-rw-rw---- 1 root root  5218448 Sep  6 15:54 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000003.pcap.xz
-rw-rw---- 1 root root  4324700 Sep  6 17:20 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000004.pcap.xz
-rw-rw---- 1 root root  3523660 Sep  6 18:50 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000005.pcap.xz
-rw-rw---- 1 root root  3847640 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.36_59000-00000006.pcap.xz
-rw-rw---- 1 root root 13177764 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.37_59001-00000000.pcap.xz
-rw-rw---- 1 root root  5683552 Sep  6 12:07 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.38_59000-00000000.pcap.xz
-rw-rw---- 1 root root  6332864 Sep  6 14:16 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.38_59000-00000001.pcap.xz
-rw-rw---- 1 root root  5327180 Sep  6 16:30 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.38_59000-00000002.pcap.xz
-rw-rw---- 1 root root  3859268 Sep  6 18:40 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.38_59000-00000003.pcap.xz
-rw-rw---- 1 root root  2676600 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.38_59000-00000004.pcap.xz
-rw-rw---- 1 root root  7938648 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.39_59001-00000000.pcap.xz
-rw-rw---- 1 root root  3801352 Sep  6 16:59 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.40_59000-00000000.pcap.xz
-rw-rw---- 1 root root  1648784 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.40_59000-00000001.pcap.xz
-rw-rw---- 1 root root  1188316 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.41_59001-00000000.pcap.xz
-rw-rw---- 1 root root 10008428 Sep  6 14:44 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.42_59000-00000000.pcap.xz
-rw-rw---- 1 root root  7292216 Sep  6 19:30 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.42_59000-00000001.pcap.xz
-rw-rw---- 1 root root   998500 Sep  6 20:15 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.42_59000-00000002.pcap.xz
-rw-rw---- 1 root root  8071756 Sep  6 12:17 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.42_59032-00000000.pcap.xz
-rw-rw---- 1 root root  8842756 Sep  6 14:37 1567724102043516194_xeur_delta-s1p2-udp_0.0.0.0_0-224.0.114.42_59032-00000001.pcap.xz

ls should show roughly 400 entries here instead of just 50

**Comment by quizac-** [comment]
I have FULL_DEBUG ganesha log and strace. How can I attach them?
Briefly speaking strace shows read syscall from what appears to be one of Ceph OSD servers and all dir entries delivered to Ganesha but only 50 are sent to client.
ganesha.log only mentions 50 file entries which is going to send to client.

**Comment by quizac-** [comment]
The same issue present on latest 2.8 branch build as well.

**Comment by mattbenjamin** [comment]
thanks, @quizac- -- I don't recall this behavior in any development or testing scenario, but I will attempt to reproduce with the versions you listed.  Nautilus/14.2.4 might be missing an important commit, I'm not sure (e.g, there were commits which addressed dir EOF conditions).

**Comment by quizac-** [comment]
Hi Matt,

Thanks for the reply. In the meantime, which version of Ceph have you tested 2.8 against?

**Comment by mattbenjamin** [comment]
@quizac- my most recent testing was a couple of months ago, and was against 1) then master and 2) direct backports to our downstream luminous branch;  Nautilus backport was done upstream and probably not explicitly tested, which opens a potential path for missing something.

**Comment by quizac-** [comment]
Hi Matt,

Have you had a chance to run tests on Nautilus?

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by ffilz** [comment]
With no action on this in nearly 30 days, I am going to close this as resolved. Please re-open if it is still an issue on a currently supported version of Ganesha.
