### ISSUE TITLE
Disable ID Mapping 

### ISSUE THREAD

**Issue by koehn** [nfs-ganesha/nfs-ganesha#514]
I'm running under Kubernetes, and it would be much better if I could disable ID mapping altogether and just persist UIDs from my containers inside NFS PVs. I say this because it's impossible to know at the time of creation of the NFS server pod what users and groups there would be in the client pods. 

Is there a way to do this with Ganesha? I'm currently using 2.7.1 as that's what's included in the standard nfs-provisioner pod.

**Comment by dang** [comment]
This should be the "Only_Numeric_Owners" option in the NFSv4 block.  So something like this:
```
NFSv4 {
    Only_Numeric_Owners = true;
}
```
