### ISSUE TITLE
FSAL CEPH destroys files on separate cephfs mount (latest 2.8 branch)

### ISSUE THREAD

**Issue by quizac-** [nfs-ganesha/nfs-ganesha#515]
```
/etc/auto.cephfs:
shared    -fstype=ceph,rw,noatime,nodiratime,nodev,nosuid,name=admin,secretfile=/etc/ceph/ceph.client.admin.key,_netdev     10.10.0.51,10.10.0.52,10.10.0.53:/shared
```
mounted as /mnt/ceph/shared

NFS Ganesha(FSAL CEPH) /shared export is mounted at the same time as /net/cephnfs/shared

Any file copied to kernel mount /mnt/ceph/shared is presented with 0B size in NFS mount /net/cephnfs/shared. After unspecified time their size drops to 0B in /mnt/ceph/shared as well. This causes irreversible changes and file content is gone. 
Files have correct size and content if copied to Ganesha mount instead.

ganesha.conf:
```
NFS_CORE_PARAM {
    Bind_Addr = 10.10.0.54;
    NFS_Port = 2049;
    MNT_Port = 20048;
    # NLM_Port = 38468;
    # Rquota_Port = 875;
    # Ganesha can lift the NFS grace period early if NLM is disabled.
    Enable_NLM = false;

    # rquotad doesn't add any value here. CephFS doesn't support per-uid
    # quotas anyway.
    Enable_RQUOTA = false;
}

EXPORT_DEFAULTS {
    Attr_Expiration_Time = 0;
    Access_Type = RW;
    Protocols = 3,4;
    SecType = sys;
    Squash = No_Root_Squash;
}

MDCACHE {
    Cache_Size = 1;
    Dir_Chunk = 0;
    NParts = 1;
}

CACHEINODE {
    Cache_Size = 1;
    Dir_Chunk = 0;
    NParts = 1;
}

NFSv4 {
    Allow_Numeric_Owners = true;
    Delegations = true;
    Grace_Period = 20;
    Lease_Lifetime = 10;
    Minor_Versions =  1,2;
    RecoveryBackend = rados_ng;
}

NFS_KRB5
{
    Active_krb5 = no;
}

RADOS_KV {
    ceph_conf = '/etc/ganesha/ceph.conf';
    userid = "admin";
    pool = "ganesha";
}

RGW {
    ceph_conf = "/etc/ganesha/ceph.conf";
    cluster = "ceph";
    name = "client.rgw.ecmds1";
}

RADOS_URLS {
    ceph_conf = '/etc/ganesha/ceph.conf';
    userid = "admin";
}
%url rados://ganesha/ganesha-export-index

LOG {
    Components {
        ALL = INFO;
     }
    Facility {
        name = FILE;
        destination = "/var/log/ganesha/ganesha.log";
        enable = active;
    }
    Format {
        CLIENTIP = true;
        HOSTNAME = false;
        PROGNAME = false;
    }
}

# CephFS exports
EXPORT
{
    Export_id=1746;
    Path = "/shared";
    Pseudo = /shared;
    Delegations = R;

    FSAL {
        Name = CEPH;
        Filesystem = "cephfs";
        User_Id = "admin";
    }
}

```

**Comment by dang** [comment]
@jtlayton Any ideas?  This seems very strange, as Ganesha shouldn't be writing anything (and attributes caching is disabled anyway).

**Comment by jtlayton** [comment]
That does sound odd. What versions of ceph and ganesha are you using here?

**Comment by quizac-** [comment]
Ceph is Nautilus 14.2.4
Ganesha is latest 2.8 branch built recently from git. Also tested on 2.8.1 and 2.8.3. I can't build 3.0 against libcephfs/librados from Nautilus(14.2.4) due to rgw_lookup function argument list changes in ceph includes.

**Comment by jtlayton** [comment]
Those versions should be ok. I'm at a loss -- you'll probably need to crank up some debugging in ganesha and the ceph client and see if you can discern the cause.

One more q -- when you write the files on the ceph mount, I assume they show up as being the correct size. If you unmount and mount cephfs again (without any ganesha accessing it in between), are the sizes and contents still correct?

**Comment by quizac-** [comment]
All files written to mount type ceph change their size to 0B if the same NFS export is mounted at the same time. All is managed by 10m timeout in autofs and it happened un-/mount both of them on many occasions. The sizes turn to 0B permanently.

**Comment by jtlayton** [comment]
Right. I get that. My question is whether you've validated that the files are ever being flushed out from the ceph client in the first place.

Are they just showing the correct size due to having just written them to the local cache, or does that information get persisted in the MDS/OSDs? Unmounting and mounting again should tell us that either way.

**Comment by quizac-** [comment]
I'm investigating it further and it seems that something else is causing it. It was a coincidence that NFS was mounted at the same time. There is something weird going on with either caching as you mentioned or apps. I will close the ticket now.
