### ISSUE TITLE
NFS v3 hardlink: nfs3_verify_exportid integer overflow bug

### ISSUE THREAD

**Issue by jimhuaang** [nfs-ganesha/nfs-ganesha#520]
The export_id has a uint16_t data type, range from 0 to 65535, while short has a range of [−32,767, +32,767]. The overflow will happen when export_id is bigger than 32767.
```c
	const short to_exportid = nfs3_FhandleToExportId(&l3_arg->link.dir);
	const short from_exportid = nfs3_FhandleToExportId(&l3_arg->file);
```

https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs3_link.c#L58

**Comment by malahal** [comment]
It should be "int" instead of "short", will post a patch.

**Comment by malahal** [comment]
Why is this not reported by scanning tools?

**Comment by malahal** [comment]
Patch for review: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/478289
