### ISSUE TITLE
cache do not release, nfs-ganesha version is 3.1

### ISSUE THREAD

**Issue by yangruifeng** [nfs-ganesha/nfs-ganesha#522]
this issue can be reproduced by following steps
1、mount
2、create some directories and wirte some files
3、umount and systemctl restart nfs-ganesha
4、mount
5、find . -name "*" in mount point
6、gdb attch nfs-ganesha，print lru_state, entries_used > entries_hiwat 

```
(gdb) p lru_state
$5 = {entries_hiwat = 1024, entries_used = 270818, chunks_hiwat = 50, chunks_used = 1046, fds_system_imposed = 1024, fds_hard_limit = 1013, fds_hiwat = 614, fds_lowat = 409, futility = 0, per_lane_work = 100,
  biggest_window = 409, prev_fd_count = 0, prev_time = 1577089874, fd_state = 0}
(gdb) p open_fd_count
$6 = 0
```

**Comment by yangruifeng** [comment]
nfs-ganesha 2.6.2 is ok

**Comment by malahal** [comment]
Looks like a very simple test, time to add such a test to Ganesha auto tests or release tests!

**Comment by yangruifeng** [comment]
the fsal is rgw, rgw_fsal_readdir can return 1000+ dentries at once, which is more than rpc buffer size. 
if fsal is vfs，it is ok

**Comment by ffilz** [comment]
This one may need re-examination.

**Comment by ffilz** [comment]
Could you explain the issue in more detail? Also, could you check if it's still an issue in V3.3 and even better check V4-dev.28?

**Comment by ffilz** [comment]
Closing due to age. Please re-open if it still occurs on the most recent Ganesha (V3.3 as of this comment).
