### ISSUE TITLE
make rpm report errors on Ganesha V2.8 stable

### ISSUE THREAD

**Issue by zs0723** [nfs-ganesha/nfs-ganesha#528]
OS: CentOS Linux release 7.6.1810 (Core)
Provides: libntirpc = 1.8.0-0.1.el7 libntirpc(x86-64) = 1.8.0-0.1.el7 libntirpc.so.1.8()(64bit) libntirpc.so.1.8(NTIRPC_1.8.0)(64bit) libntirpc.so.1.8(NTIRPC_PRIVATE)(64bit)
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: libblkid.so.1()(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit) libc.so.6(GLIBC_2.9)(64bit) libcap.so.2()(64bit) libcom_err.so.2()(64bit) libdbus-1.so.3()(64bit) libgssapi_krb5.so.2()(64bit) libgssapi_krb5.so.2(gssapi_krb5_2_MIT)(64bit) libjemalloc.so.1()(64bit) libk5crypto.so.3()(64bit) libkrb5.so.3()(64bit) libnfsidmap.so.0()(64bit) libnsl.so.1()(64bit) libntirpc.so.1.8()(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit) libpthread.so.0(GLIBC_2.3.2)(64bit) librt.so.1()(64bit) librt.so.1(GLIBC_2.2.5)(64bit) liburcu-bp.so.1()(64bit) libuuid.so.1()(64bit) rtld(GNU_HASH)
Processing files: libntirpc-devel-1.8.0-0.1.el7.x86_64
Provides: libntirpc-devel = 1.8.0-0.1.el7 libntirpc-devel(x86-64) = 1.8.0-0.1.el7 pkgconfig(libntirpc) = 1.8.0
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /usr/bin/pkg-config
Processing files: nfs-ganesha-debuginfo-2.8.3-0.1.el7.x86_64
Provides: nfs-ganesha-debuginfo = 2.8.3-0.1.el7 nfs-ganesha-debuginfo(x86-64) = 2.8.3-0.1.el7
Requires(rpmlib): rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(CompressedFileNames) <= 3.0.4-1
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/test/nfs-ganesha/build/rpmbuild/BUILDROOT/nfs-ganesha-2.8.3-0.1.el7.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib/python3.6/site-packages/__init__.py
   /usr/lib/python3.6/site-packages/__pycache__/__init__.cpython-36.opt-1.pyc
   /usr/lib/python3.6/site-packages/__pycache__/__init__.cpython-36.pyc
   /usr/lib/python3.6/site-packages/__pycache__/gpfs-epoch.cpython-36.opt-1.pyc
   /usr/lib/python3.6/site-packages/__pycache__/gpfs-epoch.cpython-36.pyc
   /usr/lib/python3.6/site-packages/gpfs-2.8.3-py3.6.egg-info
   /usr/lib/python3.6/site-packages/gpfs-epoch.py

**Comment by zs0723** [comment]
make config:
cmake -DCMAKE_BUILD_TYPE=Release  -DUSE_FSAL_RGW=ON  -DUSE_FSAL_CEPH=ON  -DBUILD_CONFIG=rpmbuild ../src

**Comment by ffilz** [comment]
Daniel, Kaleb, have we fixed something in V2.8-stable that might have resolved this?

**Comment by dang** [comment]
You can't currently build Ganesha with python on centos 7 if you have python3 installed.  The python3 packages in centos 7 are not sufficient, and CMake chooses python3 over python2 if both are available.  Fixing this is a non-trivial amount of work, but it is on my list.

**Comment by r-deshmukh** [comment]
Adding -DUSE_FSAL_GPFS=OFF while doing cmake solves this problem (as workaround). But off course one do not want/using gpfs fsal.

**Comment by ffilz** [comment]
Closing this as specific to V2.8 which is long out of support.
