### ISSUE TITLE
how does nfs-ganesha support ipv6

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#531]
>EXPORT
{
        Export_Id = 128;
        Path = /data;
        Pseudo = /data;
        Access_Type = RW;
        V6disable=false;
        Squash = No_root_squash;
        # Exporting FSAL
        FSAL {
                Name = VFS;
        }
}

I config /etc/ganesha/ganesha.conf with V6diable=false;  In the local machine, I ping6 fe80::5053:ff:feef:a1fb%eth1 and receive ok, But I run the cammand:
> sudo mount -t nfs -o vers=4 [fe80::5053:ff:feef:a1fb%eth1]:/data ./mnt

An Error happend：
> zsh: no matches found: [fe80::5054:ff:feef:a0fb%eth1]:/data/jojoliang/ganesha/data 

then my question is how does nfs-ganesha support ipv6， thank you ~

**Comment by agin719** [comment]
It is zsh's responsibility, It is ok when I change to use bash

**Comment by dang** [comment]
[] is usually a shell glob.  Try escaping it with \ (or leaving it off entirely, and just using the bare IPv6 address).

**Comment by ffilz** [comment]
Closing as resolved. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
