### ISSUE TITLE
ganesha_stats v4_full fails

### ISSUE THREAD

**Issue by wyllys66** [nfs-ganesha/nfs-ganesha#532]
Running nfs-ganesha 3.2, trying to get "v4_full" stats from ganesha_stats, but it throws an exception because its trying to "ljust" on a dbus.Struct object, I think the code expects a string here.

```
# ganesha_stats v4_full
Traceback (most recent call last):
  File "/usr/bin/ganesha_stats", line 125, in <module>
    print(exp_interface.v4_full_stats())
  File "/usr/lib/python2.7/dist-packages/Ganesha/glib_dbus_stats.py", line 836, in __str__
    output += "\n" + (self.stats[3][i+0]).ljust(23)
AttributeError: 'dbus.Struct' object has no attribute 'ljust'
```

**Comment by sachinpunadikar** [comment]
String object is expected and to be precise its the NFS operation name which will be displayed.
So far I have not faced this kind of issue. But our code is Ganesha 2.7. Will try with Ganesha 3.2.
Is it happening every time ?

**Comment by wyllys66** [comment]
I see it all the time with 2.8.2, I havent upgraded to the 3.X branch yet.

**Comment by ffilz** [comment]
Closed as resolved.
