### ISSUE TITLE
XFS FSAL missing in official RPMs

### ISSUE THREAD

**Issue by kaazoo** [nfs-ganesha/nfs-ganesha#534]
There is no XFS FSAL package at https://download.nfs-ganesha.org/3/3.2/CentOS/el-8/x86_64/, although the https://download.nfs-ganesha.org/NFS-Ganesha.README mentions that XFS should be enabled on Fedora, CentOS, Ubuntu, and Debian.

**Comment by kalebskeithley** [comment]
It's not missing. Use FSAL_VFS. README has been updated
