### ISSUE TITLE
Dbusinterface: ShowClients - When is it refreshed ?

### ISSUE THREAD

**Issue by gold-roger** [nfs-ganesha/nfs-ganesha#535]
Wiki : https://github.com/nfs-ganesha/nfs-ganesha/wiki/Dbusinterface#orgganeshanfsdclientmgr

I was playing around with the ShowClients method and it provides list of IpAddress connected. However after I unmounted the client, the table still shows it. I added couple of new clients from different machines and unmounted bunch of times. But the Clients are just updated and never removed. I restarted the server and then the table was reset accordingly.

My question is does ShowClients method show all clients connected while it was active ? When does it get refreshed (only on restart ?)

Is there any way to find active connections based on NFS versions ?

**Comment by dang** [comment]
Client entries are never removed automatically.  You can remove them explicitly with RemoveClient, but they won't go away by themselves.  This is because NFSv4 doesn't have an explicit unmount.  The client just stops accessing the mount.  We could eventually time the client out, but we don't currently.

**Comment by malahal** [comment]
Protocol doesn't have a way to find all mounted/active NFSv3 clients. Of course, you can always use network connections to find it out. NFSv4 does provide a way as inactive clients lose lease and will be removed from the hashtable. The statistics code might not be freeing whenever a client's lease expires. Lease expiry is command with failover/failback, so not sure if removing expired clients from the stats list is a good idea.

It is possible to have a timestamp in the stats structure and remove entries after some configured time like 1 hour or so of inactivity.

**Comment by ffilz** [comment]
Closed as won't fix.
