### ISSUE TITLE
Does Ganesha support worker threads for NFSv4?

### ISSUE THREAD

**Issue by darwinTtito** [nfs-ganesha/nfs-ganesha#537]
Hi,

I saw that the `Nb_Worker `parameter was moved from `NFS_CORE_PARAM `to `_9P`, does it mean that NFSv4 does not support any more worker threads?

https://gerrithub.io/c/ffilz/nfs-ganesha/+/429066/8

**Comment by dang** [comment]
Ganesha switched to using worker threads from ntirpc for NFS.  So worker threads are definitely still used.  (9P doesn't use ntirpc, so it still needs it's own worker threads)

**Comment by darwinTtito** [comment]
Hi @dang, thank you so much for your quick answer.

So, can I set the number of worker threads that I want to use? If so, what is the parameter?

**Comment by dang** [comment]
The thread pool is dynamic.  The max is set with RPC_Ioq_ThrdMax in NFS_Core_Param, and defaults to 200.

**Comment by darwinTtito** [comment]
got it. Thank you @dang!!
