### ISSUE TITLE
Ganesha doesnt respond

### ISSUE THREAD

**Issue by rvelasquezsos** [nfs-ganesha/nfs-ganesha#539]
Hi, I'm using Ganesha server like NFS gateway with cluster CEPH.
This weekend the exports wasn't available, the output of showmount -e ip_addr_ganesha showed RPC error and timeout.
Logs from that moment:
14/02/2020 11:39:47 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 10247879, old: 10247878; deq new: 10247792, old: 10247792
14/02/2020 11:40:43 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_260] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f097c0e4910 fd 335 recv errno 104 (will set dead)
14/02/2020 11:40:43 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_276] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f09943cae90 fd 336 recv errno 104 (will set dead)
14/02/2020 12:35:58 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 10251213, old: 10251212; deq new: 10251118, old: 10251118
14/02/2020 18:00:52 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_317] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f0a244da860 fd 360 recv errno 104 (will set dead)
14/02/2020 18:00:52 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_326] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f0a5417c710 fd 359 recv errno 104 (will set dead)
14/02/2020 22:01:13 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_349] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f0884048cf0 fd 373 recv errno 104 (will set dead)
14/02/2020 22:01:13 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_344] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f087431ae20 fd 374 recv errno 104 (will set dead)
15/02/2020 02:01:14 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_355] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f0980059450 fd 387 recv errno 104 (will set dead)
15/02/2020 02:01:14 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_372] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f0898189c40 fd 389 recv errno 104 (will set dead)
15/02/2020 03:02:59 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 10301606, old: 10301605; deq new: 10301417, old: 10301417
15/02/2020 05:35:38 : epoch 5e4559d4 : gw : ganesha.nfsd-1684[svc_376] rpc :TIRPC :EVENT :svc_ioq_flushv() writev failed (104)

Could you help me with this problem? I don't know what is the cause in that moment I restarted the gateway and the NFS service started with no problems

Thanks in advance

**Comment by yangruifeng** [comment]
oh, i saw this problem a few days ago.
mybe a daedlock.
you can look at the stack (pstack $pid)

**Comment by rvelasquezsos** [comment]
> oh, i saw this problem a few days ago.
> mybe a daedlock.
> you can look at the stack (pstack $pid)

Thanks for your response @yangruifeng 
the output of  "**# cat /proc/1681/stack**" is
[<ffffffffa7117711>] futex_wait_queue_me+0xc1/0x120
[<ffffffffa71180bc>] futex_wait+0xdc/0x220
[<ffffffffa711aaac>] do_futex+0x2fc/0x530
[<ffffffffa711adfd>] SyS_futex+0x11d/0x150
[<ffffffffa7003ae4>] do_syscall_64+0x74/0x150
[<ffffffffa780009a>] entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[<ffffffffffffffff>] 0xffffffffffffffff

**Comment by yangruifeng** [comment]
it is **pstack**, which can output all threads stack.

**Comment by rvelasquezsos** [comment]
I think the equivalent in SUSE is gstack from gdb package. Here is the output

[gstack.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/4219515/gstack.txt)

Thanks,

**Comment by yangruifeng** [comment]
Thread 482 (Thread 0x7f86942f5700 (LWP 3944)):
#0  0x00007f871ada989d in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f86f857103a in ?? () from /usr/lib64/libcephfs.so.2
#2  0x00007f86f852f853 in ?? () from /usr/lib64/libcephfs.so.2
#3  0x00007f86f85304f2 in ?? () from /usr/lib64/libcephfs.so.2
#4  0x00007f86f8545e0d in ?? () from /usr/lib64/libcephfs.so.2
#5  0x00007f8708222cc9 in ?? () from /usr/lib64/ganesha/libfsalceph.so
#6  0x00007f871b0e0956 in ?? () from /usr/lib64/libganesha_nfsd.so.2.8
#7  0x00007f871b0c9ad3 in ?? () from /usr/lib64/libganesha_nfsd.so.2.8
#8  0x00007f871afefd1c in ?? () from /usr/lib64/libganesha_nfsd.so.2.8
#9  0x00007f871a5bb3c1 in ?? () from /usr/lib64/libntirpc.so.1.8
#10 0x00007f871a5b97bd in ?? () from /usr/lib64/libntirpc.so.1.8
#11 0x00007f871a5b9de2 in ?? () from /usr/lib64/libntirpc.so.1.8
#12 0x00007f871a5c24b2 in ?? () from /usr/lib64/libntirpc.so.1.8
#13 0x00007f871ada34f9 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f871a8d3eef in clone () from /lib64/libc.so.6

That's a little bit suspect

**Comment by rvelasquezsos** [comment]
What does it mean? It seems like duplicate process??
The 403 is suspect for you too?
Thread 403 (Thread 0x7f852f6fe700 (LWP 3737)):
#0  0x00007f871a8c969b in poll () from /lib64/libc.so.6
#1  0x00007f871a16e16f in ?? () from /usr/lib64/libdbus-1.so.3
#2  0x00007f871a16ce1d in ?? () from /usr/lib64/libdbus-1.so.3
#3  0x00007f871a15549c in ?? () from /usr/lib64/libdbus-1.so.3
#4  0x00007f871a15794a in ?? () from /usr/lib64/libdbus-1.so.3
#5  0x00007f871b0f9d22 in ?? () from /usr/lib64/libganesha_nfsd.so.2.8
#6  0x00007f871ada34f9 in start_thread () from /lib64/libpthread.so.0
#7  0x00007f871a8d3eef in clone () from /lib64/libc.so.6

What can I do?

**Comment by ffilz** [comment]
Could you do this with debug info available so we can actually see what functions are involved?

**Comment by rvelasquezsos** [comment]
> Could you do this with debug info available so we can actually see what functions are involved?

I put the option  NIV_FULL_DEBUG in /etc/sysconfig/nfs-ganesha but I don't see any difference in the output of stack trace.
What is the way to show the debug info?

**Comment by ffilz** [comment]
You may need to install a debug info package

**Comment by kalebskeithley** [comment]
For RHEL, CentOS, Fedora, and SUSE.  Install the corresponding -debuginfo packages for the ganesha, libntirpc, and ganesha-ceph packages.

For Debian and Ubuntu install the corresponding -dbgsym packages.

Installing the -debuginfo or -dbgsym package for (gnu)libc might be helpful too.

**Comment by rvelasquezsos** [comment]
Thanks @kalebskeithley 
When I was searching the debuginfo packages I realized that there are two versions of libntirpc installed
zypper search libntirpc
S | Name         | Summary                                                       | Type
--+--------------+---------------------------------------------------------------+--------
i | libntirpc1_7 | NFS-Ganesha transport-independent RPC (TI-RPC) shared library | package
i | libntirpc1_8 | NFS-Ganesha transport-independent RPC (TI-RPC) shared library | package

Is there any problem with that?

**Comment by ffilz** [comment]
Closing due to age. If this issue is still of interest, please reopen.
