### ISSUE TITLE
3.2 fails to build with USE_DBUS enabled and _HAVE_GSSAPI disabled

### ISSUE THREAD

**Issue by joshtriplett** [nfs-ganesha/nfs-ganesha#540]
If `USE_DBUS` is enabled, and `_HAVE_GSSAPI` is disabled (not an uncommon or unreasonable combination), then `src/idmapper/idmapper.c` doesn't compile in the `auth_statistics` structure or corresponding function at all, but `src/support/export_mgr.c` references it unconditionally.

This results in a linking error:
```
/usr/bin/ld: ../support/CMakeFiles/support.dir/export_mgr.c.o:(.data.rel+0x80): undefined reference to `auth_statistics'
```

I think `export_mgr.c` needs an `#ifdef _HAVE_GSSAPI` around its use of `auth_statistics`.

**Comment by dang** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/485679

**Comment by joshtriplett** [comment]
That looks great, thanks!

**Comment by ffilz** [comment]
Please close the issue if the patch resolves your problem

**Comment by ffilz** [comment]
Closing as resolved.

**Comment by supriti** [comment]
I see this issue with V2.8-stable as well. The patch was not backported to V2.8-stable. 
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/485679

**Comment by dang** [comment]
It'll get into the next 2.8

**Comment by ffilz** [comment]
I'm not sure we will do another V2.8. I have marked it for back port in https://docs.google.com/document/d/1vRrk-JFtUdU4b234hnv0npVqnKI8BTqUWGz5IHcxt0g/edit?usp=sharing Closing
