### ISSUE TITLE
Please support systems without /etc/netconfig

### ISSUE THREAD

**Issue by joshtriplett** [nfs-ganesha/nfs-ganesha#541]
I'm using ganesha as a standalone userspace NFS daemon, and don't want to install any system files. I would like to avoid installing `/etc/netconfig`. Please consider either providing a built-in default (containing the standard values which really shouldn't vary by system) or allowing the configuration of an alternate path (which would at least allow pointing it somewhere other than `/etc`).

**Comment by dang** [comment]
I think allowing to run without netconfig would be quite complicated.  You can create a minimal /etc/netconfig yourself, if you want.  It's not a hugely complicated file.  We can't install it ourselves, since that would conflict with other packages (which distro's don't allow).

**Comment by joshtriplett** [comment]
I'm not suggesting installing it. I'm suggesting that libntirpc could have compiled-in defaults and an option to use those defaults if there's no `/etc/netconfig` file, and ganesha could enable that option by default.

**Comment by dang** [comment]
It's certainly not impossible.  I suspect it will be a fair amount of work.

**Comment by ffilz** [comment]
Closing as will not fix.
