### ISSUE TITLE
Listens for MNT even with NFSv3 compiled out, unless `Protocols = 4`

### ISSUE THREAD

**Issue by joshtriplett** [nfs-ganesha/nfs-ganesha#542]
I built Ganesha with `USE_NFS3` disabled, but it still listens for the MNT protocol (with no option to disable that) unless I also set `NFS_Core_Param { Protocols = 4; }` in the configuration file.

If Ganesha is built with USE_NFS3 disabled, it should default to `Protocols = 4;`.

**Comment by malahal** [comment]
Contributions welcome Josh! Yes, no point in enabling NLM without NFSv3, but technically they are separate protocols. I haven't seen any NFS client using NFSv4 with NLM.

**Comment by dang** [comment]
You should also disable USE_NLM if you're disabling USE_NFS3.  They should probably be tied together, but that makes for some complicate logic in cmake.  Feel free to take a look and make suggestions.

**Comment by ffilz** [comment]
It's MNT not NLM. I'm not sure if it's an oversight, or related to an issue where older Linux clients would issue the NFSv2 version of UMNT when unmounting (though I think that must have ONLY been for NFSv3 mounts).

**Comment by malahal** [comment]
Sorry, my fault. Josh did say 'MNT' or MOUNT protocol. Certainly it is NOT needed (NLM is also not needed too). Which version are you using? The version I have has that code compiled out, so can't happen unless there is some cmake goofup!

```
#ifdef _USE_NFS3
        if (NFS_options & CORE_OPTION_NFSV3) {
                Register_program(P_NFS, CORE_OPTION_NFSV3, NFS_V3);
                Register_program(P_MNT, CORE_OPTION_NFSV3, MOUNT_V1);
                Register_program(P_MNT, CORE_OPTION_NFSV3, MOUNT_V3);
        }
#endif /* _USE_NFS3 */
```

**Comment by joshtriplett** [comment]
I was working with V3.2, which I had the impression was the latest stable release.

It isn't the "register" call that's the problem. Several places, including `bind_sockets_V6` and `bind_sockets_V4`, loop over all protocols and check `nfs_protocol_enabled`. `nfs_protocol_enabled(P_MNT)` returns true if `NFS_options & CORE_OPTION_NFSV3`. That in turn is determined by the default enabled protocols, and the default enabled protocols always include both NFSV3 and NFSV4 even if NFSV3 is compiled out.

Hence my suggestion that the default enabled protocols should only include NFSV3 if it's enabled.

**Comment by ffilz** [comment]
Ok, I see that the code is missing some #ifdef _USE_NFS3 conditional blocks, feel free to submit a patch adding them. I see also that src/Protocols/NFS/mnt_*.c are not conditional compiled out.

**Comment by ffilz** [comment]
This could be addressed.

**Comment by ffilz** [comment]
It looks like it needs some work, but I have a patch under review that should address this (and more):
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/498968

**Comment by ffilz** [comment]
Patch merged. Closing as resolved.
