### ISSUE TITLE
Where is the calling process of ganesha  SM_MON ？

### ISSUE THREAD

**Issue by zanglinjie** [nfs-ganesha/nfs-ganesha#544]
In nfs-utils-1.3.0,
 /*
 * Services SM_MON requests.
 */
struct sm_stat_res *
sm_mon_1_svc(struct mon *argp, struct svc_req *rqstp)

when I use ganesha service，client add file lock，nsm_caller_name=true，nsm_monitor err，in sm_mon_1_svc err “No canonical hostname found for client1；STAT_FAIL to sever1 for SM_MON of client1”(system logs)

I would like to know ganesha  where to call sm_mon_1_svc？ clnt_vc_call?in ntirpc?

**Comment by dang** [comment]
In nsm_monitor() in src/Protocols/NLM/nsm.c

**Comment by ffilz** [comment]
Closing due to age.
