### ISSUE TITLE
libraries should not directly in /usr/lib

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#546]
The Debian package nfs-ganesha and nfs-ganesha-rados-grace from version install their libraries

libganesha_nfsd.so         
libganesha_nfsd.so.3.2     
libganesha_rados_recov.so  
libganesha_rados_urls.so

directly in /usr/lib/.
They should be either in 

/usr/lib/${DEB_HOST_MULTIARCH}/

or

/usr/lib/${DEB_HOST_MULTIARCH}/ganesha

The LIB_INSTALL_DIR variable in src/CMakeList.txt should be changed to this place for Debian.

**Comment by christmart** [comment]
On further look into this it seams actually ok to have the libganesha*so private libraries in /usr/lib/ganesha/ . So the ${DEB_HOST_MULTIARCH} part is not needed.

See https://wiki.debian.org/RpathIssue

**Comment by kalebskeithley** [comment]
The right/better place to report this is in https://github.com/nfs-ganesha/nfs-ganesha-debian/issues.

/usr/lib/ganesha/... is where the FSALs are installed and they are opened with dlopen(). But libganesha_nfsd.so* and libganesha_rados*.so are _not_ FSALs and are not opened with dlopen() and should, as you note, be installed in /usr/lib/${DEB_HOST_MULTIARCH}/

Although it seems I changed the FSAL directory to  /usr/lib/${DEB_HOST_MULTIARCH}/ganesha in ganesha-3

**Comment by kalebskeithley** [comment]
I've respun the .debs with the libs in the correct location. amd64 packages are there now. arm64 packages will be there in a bit.
