### ISSUE TITLE
/lib/systemd/system/nfs-ganesha-lock.service uses .include which is deprecated

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#547]
systemd produces the following log message after installing nfs-ganesha:
/lib/systemd/system/nfs-ganesha-lock.service:2: .include directives are deprecated, and support for them will be removed in a future version of systemd. Please use drop-in files instead.

Corresponding Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952406

**Comment by kalebskeithley** [comment]
Any hints about what the drop-in file should look like? systemd docs aren't very helpful.

**Comment by kalebskeithley** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/486938

I will update the debian packaging files accordingly once this change has been merged into 2.8 and 3
