### ISSUE TITLE
compile error with lttng on of tag V3.2

### ISSUE THREAD

**Issue by AresChen1** [nfs-ganesha/nfs-ganesha#550]
env:
lttng-tools-2.4.1-5.el7.x86_64
lttng-ust-2.4.1-4.el7.x86_64
lttng-ust-devel-2.4.1-4.el7.x86_64
lttng-tools-devel-2.4.1-5.el7.x86_64

error:
/usr/bin/ld: ganesha-rados-grace: hidden symbol `tracepoint_dlopen' in libntirpc/src/lttng/libntirpc_lttng.a(main.c.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value

Can anyone help me?

**Comment by dang** [comment]
This is a problem with old versions of lttng.  You can't have LTTng enabled on both Ganesha and ntirpc at the same time, or you get these errors.  It happens for me on 2.6 and older, but not on 2.8 or newer.

If you want to keep the old lttng, you'll have to patch out setting USE_LTTNG when processing the libntirpc subdir.  Something like this:
[no-lttng.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/4287515/no-lttng.txt)
(That's a patch file, but it's not a supported file type for some reason)

**Comment by AresChen1** [comment]
Ok，thanks very much！
