### ISSUE TITLE
This is the log I started. The client can't hang up

### ISSUE THREAD

**Issue by yinxiulong** [nfs-ganesha/nfs-ganesha#552]
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3381[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.7.1
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :FileSystem info for FSAL PSEUDO {
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxfilesize  = 200    
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxlink  = 0
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxnamelen  = 255
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxpathlen  = 4096
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  no_trunc  = 1 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  chown_restricted  = 1 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  case_insensitive  = 0 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  case_preserving  = 1 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  link_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  symlink_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  lock_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  lock_support_async_block  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  named_attr  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  unique_handles  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  acl_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  cansettime  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  homogenous  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  supported_attrs  = 15DFCE
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxread  = 67108864
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxwrite  = 67108864
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  umask  = 0 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  auth_exportpath_xdev  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  delegations = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  pnfs_mds = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  pnfs_ds = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  fsal_trace = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  fsal_grace = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :}
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_config :FSAL :DEBUG :FSAL INIT: Supported attributes mask = 0x15dfce
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_fds_limit :INODE LRU :INFO :Attempting to increase soft limit from 1024 to hard limit of 4096
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_fds_limit :INODE LRU :INFO :Setting the system-imposed limit on FDs to 4096.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[chunk_lru] chunk_lru_run :INODE LRU :DEBUG :After work, threadwait=90 totalwork=0
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[cache_lru] lru_run :INODE LRU :DEBUG :FD count is 0 and low water mark is 2048: not reaping.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[cache_lru] lru_run :INODE LRU :DEBUG :After work, open_fd_count:0  count:0 fdrate:1 new_thread_wait=90
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_server_pkgs :NFS STARTUP :INFO :State lock layer successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_server_pkgs :NFS STARTUP :DEBUG :Now building IP/name cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_server_pkgs :NFS STARTUP :INFO :IP/name cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_recovery_load_clids :STATE :DEBUG :Load recovery cli (nil)
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] load_fsal :NFS STARTUP :DEBUG :Loading FSAL RGW with /usr/lib64/ganesha/libfsalrgw.so
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init :FSAL :DEBUG :RGW module registering.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_config :FSAL :DEBUG :RGW module setup.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :FileSystem info for FSAL RGW {
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxfilesize  = 7FFFFFFFFFFFFFFF    
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxlink  = 8
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxnamelen  = 1024
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxpathlen  = 1024
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  no_trunc  = 1 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  chown_restricted  = 0 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  case_insensitive  = 0 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  case_preserving  = 1 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  link_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  symlink_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  lock_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  lock_support_async_block  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  named_attr  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  unique_handles  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  acl_support  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  cansettime  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  homogenous  = 1  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  supported_attrs  = 15DFCE
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxread  = 67108864
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  maxwrite  = 67108864
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  umask  = 0 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  auth_exportpath_xdev  = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  delegations = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  pnfs_mds = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  pnfs_ds = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  fsal_trace = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :  fsal_grace = 0  
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] display_fsinfo :FSAL :DEBUG :}
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] create_export :FSAL :DEBUG :RGW module export /.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] export_commit_common :CONFIG :INFO :Export 1 created at pseudo (/) with path (/) and tag ((null)) perms (options=022031e2/077001e0               , RWrw, -4-, ---, TCP, ----,               ,         ,                ,                ,                )
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] export_commit_common :CONFIG :INFO :Export 1 has 0 defined clients
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] build_default_root :CONFIG :DEBUG :Pseudo root already exists
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,35,36+ep
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] gsh_dbus_pkginit :DBUS :DEBUG :init
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] gsh_dbus_register_path :DBUS :DEBUG :registered handler for /org/ganesha/nfsd/ExportMgr
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] gsh_dbus_register_path :DBUS :DEBUG :registered handler for /org/ganesha/nfsd/ClientMgr
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NFSv4 ACL cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_init :NFS4 ACL :DEBUG :Initialize NFSv4 ACLs
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_init :NFS4 ACL :DEBUG :sizeof(fsal_ace_t)=20, sizeof(fsal_acl_t)=80
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_test :NFS4 ACL :DEBUG :acldata.aces = 0x164d020
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_test :NFS4 ACL :DEBUG :acl = 0x1654bf0, ref = 1, status = 0
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_test :NFS4 ACL :DEBUG :acldata2.aces = 0x1654c50
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_ace_free :NFS4 ACL :DEBUG :free ace 0x1654c50
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acl_entry_inc_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x1654bf0, 2)
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_test :NFS4 ACL :DEBUG :re-access: acl = 0x1654bf0, ref = 2, status = 2
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acl_entry_dec_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x1654bf0, 1)
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acls_test :NFS4 ACL :DEBUG :release: acl = 0x1654bf0, ref = 1, status = 0
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acl_release_entry :NFS4 ACL :DEBUG :Free ACL 0x1654bf0
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_acl_entry_dec_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x1654bf0, 0)
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs4_ace_free :NFS4 ACL :DEBUG :free ace 0x164d020
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NFSv4 ACL cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_export_root :EXPORT :DEBUG :About to lookup_path for ExportId=1 Path=/
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] cih_get_by_key_latch :HT CACHE :DEBUG :fdcache MISS
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] cih_get_by_key_latch :HT CACHE :DEBUG :fdcache MISS
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] mdcache_new_entry :NFS READDIR :DEBUG :NFS READDIR: DEBUG: Adding a DIRECTORY, entry=0x1650320 setting MDCACHE_TRUST_CONTENT clearing MDCACHE_DIR_POPULATED
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] mdcache_new_entry :INODE :DEBUG :New entry 0x1650320 added
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] init_export_root :EXPORT :DEBUG :Added root obj 0x1650358 FSAL MDCACHE for path / on export_id=1
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :krb5 keytab path successfully set to 
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :gss principal "nfs" successfully set
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NFSv4 clientid cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NFSv4 clientid cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :duplicate request hash table cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NFSv4 State Id cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NFSv4 State Id cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NFSv4 Owner cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NFSv4 Open Owner cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NLM Owner cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NLM Owner cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NLM State cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NLM State cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building 9P Owner cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :9P Owner cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building NFSv4 Session Id cache
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NFSv4 Session Id cache successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building 9P resources
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :9P resources successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :DEBUG :Now building pseudo fs
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init :NFS STARTUP :INFO :NFSv4 pseudo file system successfully initialized
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] fsal_save_ganesha_credentials :FSAL :INFO :Ganesha uid=0 gid=0 ngroups=1 (0)
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init_svc :DISP :DEBUG :NFS INIT: Core options = 31
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init_svc :DISP :INFO :NFS INIT: using TIRPC
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] nfs_Init_svc :DISP :INFO :NFS INIT: Using IPv6
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] Allocate_sockets :DISP :DEBUG :Socket numbers are: NFS tcp=37 udp=36
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] Allocate_sockets :DISP :DEBUG :Socket numbers are: MNT tcp=39 udp=38
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] Allocate_sockets :DISP :DEBUG :Socket numbers are: NLM tcp=41 udp=40
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] Allocate_sockets :DISP :DEBUG :Socket numbers are: RQUOTA tcp=43 udp=42
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] Bind_sockets_V6 :DISP :WARN :Cannot bind NFS udp6 socket, error 98 (Address already in use)
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] Bind_sockets :DISP :FATAL :Error binding to V6 interface. Cannot continue.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] finish :FSAL :DEBUG :RGW module finishing.
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] unregister_fsal :FSAL :CRIT :Unregister FSAL RGW with non-zero refcount=1
07/03/2020 23:39:28 : epoch 5e63c030 : ceph-node-1 : nfs-ganesha-3384[main] finish :FSAL :CRIT :RGW: unregister_fsal failed (16)

**Comment by dang** [comment]
Bind_sockets_V6 :DISP :WARN :Cannot bind NFS udp6 socket, error 98 (Address already in use)

It looks like NFS is already running on the server.  Is knfsd running?  Or another Ganesha?

**Comment by ffilz** [comment]
Closing due to age. If this issue is still of interest, please reopen.
