### ISSUE TITLE
ganesha seems to loose fs_location entries

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#557]
beginning with version 2.7 including version 3.2 ganesha starts to deliver empty referrals after some time of running.

In the debug log you see the message:

15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4354] encode_fs_locations :FSAL :DEBUG :NULL fs_locations

Looking through the debug log, you can see when storage is allocated and populated some time before:

14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1434] nfs4_fs_locations_new :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 1)
14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1434] populate_fs_locations :NFS4 :DEBUG :location = fsinet.zdv.uni-mainz.de:/wwwuser/stud
14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1434] populate_fs_locations :NFS4 :DEBUG :fsid.major = 14370739946443486984, fsid.minor = 14370739946443486984

On later usage the reference count is increased and decreased:

14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1434] nfs4_fs_locations_get_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 2)
14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1423] nfs4_fs_locations_get_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 3)
14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1423] nfs4_fs_locations_put_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 3)
14/03/2020 06:26:26 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_1424] nfs4_fs_locations_get_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 4)

The last time this address is logged is:

15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] nfs4_fs_locations_put_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 3)

At this time checking the referral leads to the NULL reply:

15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9448005aa0, valid_mask: 11dfce, request_mask: 800000000011dfce, supported: 91dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] is_sticky_bit_set :NFS4 :DEBUG :sticky bit is set on 1725142
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_common_is_referral :FSAL :DEBUG :Referral found for handle: 0x7f9448005aa0

I tried to debug the code for some days now and did not find the error. it might be somewhere in memory management or in the mdcache node.

Including some more log commands, it looks like the fs_location gets lost while trying to refresh the attributes:

15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] find_fd :FSAL :F_DBG :Opened fd=32 for file 0x7f9448005aa0 of type DIRECTORY
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] vfs_getattr2 :FSAL :F_DBG :Got fd 32 closefd = true
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] vfs_getattr2 :FSAL :F_DBG :before fsal_prepare_attrs attrs->request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fetch_attrs :FSAL :F_DBG :before posix2fsal_attributes_all attrs->request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fetch_attrs :FSAL :F_DBG :after posix2fsal_attributes_all attrs->request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fetch_attrs :FSAL :F_DBG :before getattrs attrs->request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] vfs_sub_getattrs :FSAL :F_DBG :request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fetch_attrs :FSAL :F_DBG :after getattrs attrs->request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] vfs_getattr2 :FSAL :F_DBG :before fsal_prepare_attrs attrs->request_mask = 800000000011dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] vfs_getattr2 :FSAL :F_DBG :Closing Opened fd 32
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :before update attr entry->attrs->fs_locations = 0x7f9448005220
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :before update attr attrs->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :after update attr entry->attrs->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :after update attr attrs->fs_locations = 0x7f9448005220
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :before copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :before copy_attrs attrs->fs_locations = 0x7f9448005220
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :after copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdc_update_attr_cache :INODE :F_DBG :after copy_attrs attrs->fs_locations = 0x7f9448005220
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_refresh_attrs :INODE :F_DBG :before fsal_release_attrs attrs.fs_locations = 0x7f9448005220
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] nfs4_fs_locations_release :NFS4 :F_DBG :begin (fs_locations, ref) = (0x7f9448005220, 4)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] nfs4_fs_locations_put_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f9448005220, 3)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_refresh_attrs :INODE :F_DBG :after fsal_release_attrs attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_refresh_attrs :INODE :F_DBG :attrs  obj attributes Request Mask=0011dfce Valid Mask=0011dfce Supported Mask=0091dfce DIRECTORY numlinks=0x2 size=0x1000 mode=01644 owner=0x0 group=0x0 atime=14/03/2020 06:48:13 mtime=17/04/2015 17:02:41
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :before fsal_copy_attrs attrs_out->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :before fsal_copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :after fsal_copy_attrs attrs_out->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :after fsal_copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=0001dfce Valid Mask=0011dfce Supported Mask=0091dfce DIRECTORY numlinks=0x2 size=0x1000 mode=01644 owner=0x0 group=0x0 atime=14/03/2020 06:48:13 mtime=17/04/2015 17:02:41
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_test_access :FSAL :F_DBG :before fsal_prepare_attrs attrs.request_mask = 7f94e47f7f31
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_test_access :FSAL :F_DBG :before getattrs attrs.request_mask = 680
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :begin
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :before fsal_copy_attrs attrs_out->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :before fsal_copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :after fsal_copy_attrs attrs_out->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :after fsal_copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=00000680 Valid Mask=0011dfce Supported Mask=0091dfce DIRECTORY numlinks=0x2 size=0x1000 mode=01644 owner=0x0 group=0x0 atime=14/03/2020 06:48:13 mtime=17/04/2015 17:02:41
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_test_access :FSAL :F_DBG :after getattrs attrs.request_mask = 680
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_is_referral :INODE :F_DBG :begin
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_is_referral :INODE :F_DBG :before fsal_copy_attrs attrs->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_is_referral :INODE :F_DBG :before fsal_copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_is_referral :INODE :F_DBG :after fsal_copy_attrs attrs->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] mdcache_is_referral :INODE :F_DBG :after fsal_copy_attrs entry->attrs.fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9448005aa0, valid_mask: 11dfce, request_mask: 800000000011dfce, supported: 91dfce
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_common_is_referral :FSAL :F_DBG :begin attrs->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] is_sticky_bit_set :NFS4 :DEBUG :sticky bit is set on 1725142
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_common_is_referral :FSAL :F_DBG :begin attrs->fs_locations = (nil)
15/03/2020 06:26:16 : epoch 5e6bc5be : linux-test : ganesha.nfsd-21300[svc_4348] fsal_common_is_referral :FSAL :DEBUG :Referral found for handle: 0x7f9448005aa0

Any idea?

**Comment by christmart** [comment]
My impression is that the problem is in src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c line 882 in function mdcache_refresh_attrs:

	/* Done with the attrs (we didn't need to call this since the
	 * fsal_copy_attrs preceding consumed all the references, but we
	 * release them anyway to make it easy to scan the code for correctness.
	 */
	fsal_release_attrs(&attrs);

The comment says that the call to fsal_release_attrs is not necessary, but debugging it shows, that afterwards fs_locatations is always NULL and gets never filled again. I'll try with commenting this statement.

**Comment by ffilz** [comment]
Ah, someplace the fs_locations attribute isn't being managed the same way the ACL is managed (well, hopefully we also don't lose ACLs...).

The idea is we are supposed to have granular trust of different parts of the attributes: the main attributes, the acl, and fs_locations.

The fs_locations were added on later so there might be something missing.

**Comment by christmart** [comment]
I think the error is in fsal_copy_attrs in fsal.h .
If dest has populated fs_locations (or acl ..) and src has not, the first statement in the function

	*dest = *src;

effectively deletes the pointerns to the fs_locations.
The if statements after the copy also don't fix the situation because fs_locations is already NULL at that time.

**Comment by dang** [comment]
dest should not have anything defined when calling that function.  Do you know what call might have something defined in dest?

**Comment by christmart** [comment]
I see this in calls from mdcache_is_referral, mdcache_getattrs and mdc_update_attr_cache called from mdcache_refresh_attrs
It is always 06:26:19 in the morning where I see a call to mdcache_refresh_attrs  from mdc_update_attr_cache :

22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] fsal_copy_attrs :FSAL :F_DBG :dest = 0x7f77dc00c3d8, src = 0x7f77ebd65430, pass_refs = 1

In this call dest->fs_locations is NULL and request_mask has also not set the fs_location bit. At the end of the call dest has still no fs_location set but the src had it:

22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] fsal_copy_attrs :FSAL :F_DBG :end src->fs_locations = 0x7f77dc000a90
22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] fsal_copy_attrs :FSAL :F_DBG :end dest->fs_locations = (nil)

This is the last time, where I see a reference to this memory segment:

22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] mdc_update_attr_cache :INODE :F_DBG :after copy_attrs entry->attrs.fs_locations = (nil)
22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] mdc_update_attr_cache :INODE :F_DBG :after copy_attrs attrs->fs_locations = 0x7f77dc000a90
22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] mdcache_refresh_attrs :INODE :F_DBG :before fsal_release_attrs attrs.fs_locations = 0x7f77dc000a90
22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] mdcache_refresh_attrs :INODE :F_DBG :before fsal_release_attrs entry->attrs.fs_locations = (nil)
22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] nfs4_fs_locations_release :NFS4 :F_DBG :begin (fs_locations, ref) = (0x7f77dc000a90, 4)
22/03/2020 06:26:19 : epoch 5e7503eb : linux-test : ganesha.nfsd-94981[svc_5351] nfs4_fs_locations_put_ref :NFS4 :F_DBG :(fs_locations, ref) = (0x7f77dc000a90, 3)

So what happens every moring at 06:26 ?
Is it some mdcache cleanup or refresh cycle?
If so, might it be a problem, that FS_LOCATIONS is not set in the request_mask during the call to fsal_copy_attrs?

mdcache_refresh_attrs is called from mdcache_getattrs. There attrs_out->request_mask has not set FS_LOCATIONS flag but the cached object has the information filled in:

mdcache_getattrs :INODE :F_DBG :begin attrs_out->request_mask = 1dfce entry->attrs.request_mask = 800000000091dfce

This results in need_fslocations = false in mdcache_refresh_attrs, where The FS_LOCATIONS bit in attrs.request_mask gets cleared. This leads to the problem in fsal_copy_attrs.

I am not shure if this analysis is correct. Please have a look.

**Comment by christmart** [comment]
I tried the following patch. This might fix the problem. At least I did not see "NULL fslocations" since about a day. 

Please have a look.

        --- a/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c
        +++ b/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c
        @@ -938,8 +938,8 @@ static fsal_status_t mdcache_getattrs(struct fsal_obj_handle *obj_hdl,
        }
 
        status = mdcache_refresh_attrs(
        -                       entry, (attrs_out->request_mask & ATTR_ACL) != 0,
        -                       (attrs_out->request_mask & ATTR4_FS_LOCATIONS) != 0,
        +                       entry, (entry->attrs.request_mask & ATTR_ACL) != 0,
        +                       (entry->attrs.request_mask & ATTR4_FS_LOCATIONS) != 0,
                                true);
         
        if (FSAL_IS_ERROR(status)) {

**Comment by ffilz** [comment]
I think that looks good. And I think ACLs could disappear also, which would be bad because once there's an ACL on an object, we need to keep it refreshed because we use it for permission checking...

**Comment by christmart** [comment]
Do you plan to include this patch?

**Comment by ffilz** [comment]
Sorry, I should have also requested a patch submission via gerrithub as described in src/CONTRIBUTING_HOWTO.txt

**Comment by christmart** [comment]
Ah ok. I pushed it as:
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/495903

**Comment by ffilz** [comment]
Patch needs more work.

**Comment by ffilz** [comment]
Are you still interested in pursuing a fix for this? I think it should be fixed and there is a patch that needs work. If you aren't interested in pursuing, I will try taking over the patch and completing it.

**Comment by christmart** [comment]
The fix I posted is working with my production server for some months now.
Which work do you think is needed?

**Comment by ffilz** [comment]
See the comment in the patch:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/495903/1/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c#949

**Comment by christmart** [comment]
You know the code better than I. Please go ahead.

**Comment by ffilz** [comment]
Ok, I'll look into my concerns and make any changes that look relevant. I may be able to make them as a separate patch which would fully retain history of contribution.

**Comment by ffilz** [comment]
Bump, with Ganesha V4.0 releasing soon, rc1 this week, let's revisit this issue.

**Comment by ffilz** [comment]
There is a fix for this in https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/525891

**Comment by ffilz** [comment]
Closing as verified per comment in gerritub.
