### ISSUE TITLE
Does the ganesha.conf  support uppercase and lowercase letters?

### ISSUE THREAD

**Issue by zanglinjie** [nfs-ganesha/nfs-ganesha#560]
like this:
EXPORT {
    Export_Id = 3;
    Path = /NFS;
    Pseudo = /NFS
    Protocols = 3;
 ....
}
when I add new export :
EXPORT {
    Export_Id = 4;
    Path = /nfs;
    Pseudo = /nfs;
    Protocols = 3;
 ....
}
Pseudo path(/nfs) is a duplicate
duplicate   export Id = 4

**Comment by dang** [comment]
Keywords are for sure case insensitive, but I would have thought that paths were case sensitive.  Can you try quoting them?

**Comment by zanglinjie** [comment]
Still fail，when“the first set Export_Id = 3;Path = /NFS;”，in get_gsh_export_by_pseudo_locked，Comparing NFS to NFS. then Pseudo path(/NFS) is a duplicate
 when“the first set Export_Id = 3;Path = /nfs;”，in get_gsh_export_by_pseudo_locked，Comparing nfs to nfs. then Pseudo path(/nfs) is a duplicate

**Comment by ffilz** [comment]
get_gsh_export_by_pseudo_locked does case sensitive comparison. It's possible the parser is recognizing nfs as a token, but then quoting the string should have worked. You may need to enable some debug so we can better understand what's going wrong.

**Comment by zanglinjie** [comment]
when set only one "EXPORT,Path = /NFS;",then set another EXPORT like "Path = /nfs;" 
debug like this:
proc_block
lookup_node
do_block_load in this function the new add path is "NFS" ,however，not “nfs”，
then call get_gsh_export_by_pseudo_locked  Comparing NFS to NFS. then Pseudo path(/NFS) is a duplicate。
In do_block_load，
	term_node = glist_first_entry(&node->u.nterm.sub_nodes,
						      struct config_node,
						      node);
It's weird，get the path value is NFS.

**Comment by zanglinjie** [comment]
thanks for your kindly help,@ffilz and @dang
when set only one "EXPORT,Path = /NFS;",then set another EXPORT like "Path = /nfs;" 
debug like this:
proc_block
lookup_node
do_block_load in this function the new add path is "NFS" ,however，not “nfs”，
then call get_gsh_export_by_pseudo_locked  Comparing NFS to NFS. then Pseudo path(/NFS) is a duplicate。
In do_block_load，
	term_node = glist_first_entry(&node->u.nterm.sub_nodes,
						      struct config_node,
						      node);
It's weird，get the path value is NFS.

**Comment by zanglinjie** [comment]
if add the path like "Path = /nfs/;"  Add one more "/" ,that will be ok.
showmount -e :
/NFS
/nfs

**Comment by dang** [comment]
I think the parser is recognizing NFS as a keyword.  It makes all keywords caps, so that they match the config settings.  Fortunately, that workaround works fine.

**Comment by zanglinjie** [comment]
thanks for your kindly help,@ffilz and @dang
There may be errors in this matching method.where the parser is recognizing NFS as a keyword?Why not reference the actual path(nfs),however use the old one(NFS).

**Comment by malahal** [comment]
I think the parser is matching an existing entry. I tried "/A2" and "/a2" and ran into same issue. Will have to debug where this matching occurs.

**Comment by zanglinjie** [comment]
thanks for your kindly help,@malahal 
lookup_node -->do_block_load，
in term_node, it is already use an existing entry.
---------------------
term_node = glist_first_entry(&node->u.nterm.sub_nodes,
 struct config_node)
in term_node ,path use an existing entry.

**Comment by malahal** [comment]
save_token() seems to be a culprit, will let you know soon.

**Comment by malahal** [comment]
See if this fixes your issue: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/488612

**Comment by zanglinjie** [comment]
Thanks for your kindly help,@malahal
Thanks for your support in advance.

Although hills ’n rills set us apart,
The moon and wind share our kind heart.

**Comment by zanglinjie** [comment]
Thanks for your kindly help,@malahal
Thanks for your support in advance.

Although hills ’n rills set us apart,
The moon and wind share our kind heart.
