### ISSUE TITLE
nfs4 proxy trouble

### ISSUE THREAD

**Issue by wuchenzh** [nfs-ganesha/nfs-ganesha#564]
when i use proxy, it seems ganesha can't connect to the nfs server

**Comment by wuchenzh** [comment]
this is the log, always repeat this:
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
07/04/2020 16:22:50 : epoch 5e8c3840 : nfs-proxy-server-212 : ganesha.nfsd-2053[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server

**Comment by wuchenzh** [comment]
this is my config:
EXPORT
{
       Export_Id = 123;
       Path = /opt/nfs;
       Pseudo = /proxy-nfs;
       Protocols = 4;
       Access_Type = RW;
       Squash = No_Root_Squash;
       Sectype = sys;

       FSAL {
               Name = PROXY;
               Srv_Addr = 172.16.90.199;
       }
}

**Comment by wuchenzh** [comment]
the version is 3.2, is there something wrong with my config?

**Comment by dang** [comment]
Can you either turn on FULL_DEBUG for FSAL or do a packet dump?

**Comment by wuchenzh** [comment]
this is the FASL FULL_DEBUG log, repeat


08/04/2020 09:44:45 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_clientid_renewer] pxy_setclientid :FSAL :DEBUG :Compound setclientid res request returned 10021
08/04/2020 09:44:45 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_clientid_renewer] pxy_clientid_renewer :FSAL :DEBUG :Need -1 new client id
08/04/2020 09:44:45 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
08/04/2020 09:44:45 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_clientid_renewer] pxy_compoundv4_call :FSAL :DEBUG :First attempt to send XID 1586331817 with 172 bytes
08/04/2020 09:44:45 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_rcv_thread] pxy_rpc_read_reply :FSAL :DEBUG :Recmark 80000024, xid 1586331817

**Comment by wuchenzh** [comment]
```bash
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] log_conf_commit :CONFIG :EVENT :Switching to new component log levels
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :FileSystem info for FSAL PSEUDO {
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxfilesize  = 200
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxlink  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxnamelen  = 255
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxpathlen  = 4096
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  no_trunc  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  chown_restricted  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  case_insensitive  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  case_preserving  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  link_support  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  symlink_support  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  lock_support  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  lock_support_async_block  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  named_attr  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  unique_handles  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  acl_support  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  cansettime  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  homogenous  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  supported_attrs  = 11DFCE
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxread  = 67108864
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxwrite  = 67108864
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  umask  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  auth_exportpath_xdev  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  delegations = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  pnfs_mds = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  pnfs_ds = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  fsal_trace = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  fsal_grace = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  expire_time_parent = -1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :}
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] init_config :FSAL :DEBUG :FSAL INIT: Supported attributes mask = 0x11dfce
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] load_fsal :FSAL :F_DBG :FSAL PROXY refcount 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :FileSystem info for FSAL PROXY {
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxfilesize  = 7FFFFFFFFFFFFFFF
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxlink  = 8
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxnamelen  = 1024
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxpathlen  = 1024
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  no_trunc  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  chown_restricted  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  case_insensitive  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  case_preserving  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  link_support  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  symlink_support  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  lock_support  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  lock_support_async_block  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  named_attr  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  unique_handles  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  acl_support  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  cansettime  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  homogenous  = 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  supported_attrs  = 11DFCE
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxread  = 1048576
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  maxwrite  = 1048576
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  umask  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  auth_exportpath_xdev  = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  delegations = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  pnfs_mds = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  pnfs_ds = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  fsal_trace = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  fsal_grace = 0
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :  expire_time_parent = -1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] display_fsinfo :FSAL :DEBUG :}
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] mdcache_fsal_create_export :FSAL :F_DBG :FSAL MDCACHE refcount 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] lookup_fsal :FSAL :F_DBG :FSAL PSEUDO refcount 1
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] pseudofs_create_export :FSAL :DEBUG :Created exp 0x11977c0 - /
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[main] mdcache_fsal_create_export :FSAL :F_DBG :FSAL MDCACHE refcount 2
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_rcv_thread] pxy_rpc_recv :FSAL :DEBUG :Connected after 0 sleeps, resending outstanding calls
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_clientid_renewer] pxy_clientid_renewer :FSAL :DEBUG :Need 1 new client id
08/04/2020 09:44:38 : epoch 5e8d2c86 : nfs-proxy-server-212 : ganesha.nfsd-25732[pxy_clientid_renewer] pxy_setclientid :FSAL :EVENT :Negotiating a new ClientId with the remote server
```

**Comment by dang** [comment]
Okay, 10021 is NFS4ERR_MINOR_VERS_MISMATCH.  This means that the client (ganesha) and the server don't agree on the minor version that's being used.  FSAL_PROXY is using v4.1, your server seems to have this disabled, maybe?

**Comment by wuchenzh** [comment]
yes, the server is using 4.0, but i can't change this, can i change the FSAL_PROXY version?

**Comment by dang** [comment]
No, 4.1 is hard coded in the FSAL.  4.0 and 4.1 have significant differences, so it's not trivial to switch between them.

**Comment by ffilz** [comment]
And in fact, NFS v4.1 is necessary for Proxy. An NFS server needs to be able to "open" files by handle. NFS v4.0 OPEN does not have a way to originate an open by handle, only by parent directory handle and file name.

If you desperately need NFS v4.0, it would be possible to copy and modify FSAL_PROXY, however, there will be things it won't be able to do because it can't do open by handle (it would have to do all I/O using the special stateids). That also means it would not be able to do any byte range locking (though Ganesha WILL provide byte range locking to it's clients). On the other hand, propagating state up to the proxied server is problematical for a couple reasons:

1. If there is any other access to the proxied server's files from other than a single Ganesha instance, you have just created a clustered file system. FSAL_PROXY is not prepared to be pare of a clustered file system.

2. The way the NFS protocol handles state (open/share reservations and byte range locks) after client and server crashes means that if the Ganesha proxy crashes, it looks to the proxied server like a client crashed, and it will dump all state.

**Comment by wuchenzh** [comment]
thanks!
