### ISSUE TITLE
fail to handle relese ip event for NFSv4 clients

### ISSUE THREAD

**Issue by zs0723** [nfs-ganesha/nfs-ganesha#566]
nfs_release_v4_clients(char* ip) // the ip is server ip
{
cp = (nfs_client_id_t *) pdata->val.addr;
			PTHREAD_MUTEX_lock(&cp->cid_mutex);
			if ((cp->cid_confirmed == CONFIRMED_CLIENT_ID)
			     && ip_match(ip, cp)) {
....
     }
}

static int ip_match(char *ip, nfs_client_id_t *cid)
{
char *value = cid->cid_client_record->cr_client_val;
LogDebug(COMPONENT_STATE, "NFS Server V4 match ip %s with (%.*s)",
		 ip, len, value);
if (strstr(haystack, ip) != NULL)
		return 1;
}

```
It seems cr_client_val didn't contain server ip which the client connected to.

14/04/2020 23:11:16 : epoch 5e967a67 : node3 : ganesha.nfsd-14092[dbus_heartbeat] nfs_release_v4_clients :STATE :EVENT :NFS Server V4 recovery release ip 192.168.56.132
14/04/2020 23:11:16 : epoch 5e967a67 : node3 : ganesha.nfsd-14092[dbus_heartbeat] ip_match :STATE :DEBUG :NFS Server V4 match ip 192.168.56.132 with (Linux NFSv4.1 plana125.seal.com)
```

**Comment by malahal** [comment]
client id will have server IP address in NFSv4.0. I don't they will have server IP addresses in NFSv4.1 . This function should work with NFSv4.0 only based on its implementation. Try NFS4.0 and see if that works (it should).

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by ffilz** [comment]
With no action on this in nearly 30 days, I am going to close this as resolved. Please re-open if it is still an issue on a currently supported version of Ganesha.
