### ISSUE TITLE
upgrade from nfs-ganesha 2.8.3 to 3.2 leads to [abrt] nfs-ganesha: ganesha.nfsd killed by SIGSEGV

### ISSUE THREAD

**Issue by toddpfaff** [nfs-ganesha/nfs-ganesha#571]
Environment:
- nfs-ganesha-2.8.3-4.el7.x86_64
-  CentOS Linux release 7.7.1908 (Core)

Attempted upgrade from nfs-ganesha-2.8.3-4.el7.x86_64 to nfs-ganesha-3.2-6.el7.x86_64:
```
systemctl stop nfs-ganesha
yum install centos-release-nfs-ganesha30
yum update
systemctl start nfs-ganesha
```
Upon startup, ganesha.nfsd crashed with these log entries:

```
  Apr 13 22:48:17 ganesha systemd: Started NFS-Ganesha file server.
  Apr 13 22:48:17 ganesha rpc.statd[30746]: Received SM_UNMON_ALL request
  from ganesha while not monitoring any hosts
  Apr 13 22:48:52 ganesha kernel: ganesha.nfsd[30820]: segfault at
  7f561b35d26f ip 00007f561b35d26f sp 00007f561b35bc18 error 15
  Apr 13 22:48:52 ganesha systemd: nfs-ganesha.service: main process
  exited, code=killed, status=11/SEGV
```

The associated abrtd report: [abrt-report.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/4510447/abrt-report.txt).

**Comment by soumyakoduri** [comment]
Could you paste backtrace from the core or from backtrace file. Also are there any shared exported or clients still connected to server during this upgrade?

**Comment by toddpfaff** [comment]
On Wed, 22 Apr 2020, Soumya Koduri wrote:

> Could you paste backtrace from the core or from backtrace file.

Do you want something more than what was included in the CentOS 7 abrtd 
report that I already included when I opened this issue?  I thought the 
abrtd dump would include all the bits needed.


> Also are there any shared exported or clients still connected to server 
> during this upgrade?

There are certainly nfs client that could be connected or trying to 
connect but, as I wrote, I stopped the nfs-ganesha service on the server 
before doing the upgrade, then did the upgrade, then re-started the 
server.

Are you suggesting that we would also need to check and stop *every* nfs 
client?  That's not feasible.

Thanks,
Todd

**Comment by soumyakoduri** [comment]
> Do you want something more than what was included in the CentOS 7 abrtd report that I already included when I opened this issue? I thought the abrtd dump would include all the bits needed.

yes.. as you can see in abrtd.txt, there is no stack trace printed.. In CentOS atleast, there will be another file generated called 'backtrace' which contains the stack trace of the thread which crashed. I suggest to install nfs-ganesha-debuginfo package as well to capture all stack symbols. This is to quickly check which code path the crash happened.


> There are certainly nfs client that could be connected or trying to connect but, as I wrote, I stopped the nfs-ganesha service on the server before doing the upgrade, then did the upgrade, then re-started the server. Are you suggesting that we would also need to check and stop *every* nfs client? That's not feasible. Thanks, Todd

No. Its not mandatory to stop NFS client during upgrade. But typically HA cluster are recommended  for rolling upgrade scenarios where client gets failed over to another NFS server in the cluster while the original server is getting upgraded and then failed back later.

Which FSAL are you using? and do you hit this issue only after upgrade or does even simple service stop and start results in crash?

**Comment by toddpfaff** [comment]
Ok, thanks, Soumya, I'll do as you suggest at next earliest opportunity.

I understand what you say about an HA case.  In this case there is no HA clustering in place yet.  That's the eventual goal but for now it just a single nfs-ganesha server and the PROXY FSAL being used to access storage from another CentOS 7 NFS server.

So that answers your question about the FSAL.

As for the question about upgrade versus simple stop-start: we only see this crash after the upgrade from 2.8 to 3.2.  I've tried it twice now with the same result.  I will try it again asap in order to gather another core and backtrace with the debug package installed as you suggested.

Silly question perhaps but where do I get the debuginfo packages corresponding to the nfs-ganesha packages that I'm using in CentOS 7?  Is there a repo I can add?

**Comment by soumyakoduri** [comment]
https://github.com/nfs-ganesha/nfs-ganesha/issues/571#issuecomment-619267261 has debuginfo pacakges of nfs-ganesha. Please install the 3.2 version post upgrade before starting the nfs-ganesha service.

Also if you are going to reproduce, please enable FULL DEBUG logging  by adding below option in ganesha.conf. 

LOG {
        COMPONENTS {
                ALL =  FULL_DEBUG;
        }
}
If space is not an issue, turn on debugging for all components as stated above or at least turn on FSAL level logging by setting "FSAL = FULL_DEBUG;"

I think some changes were done in FSAL_PROXY recently. I am not much aware of them but the bt and logs may help some one to look into this.

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by toddpfaff** [comment]
I have not been able to revisit this myself and likely never will.  I no 
longer have any systems running nfs-ganesha 2.8.3 since they have all been 
moved to 4-dev after I wasn't able to use 3.2 because of this issue.

My motivation for trying to upgrade to 3.2 and then moving to 4-dev was an 
attempt to find solution to the issue in ticket #580, which is also still 
open and which you also asked me about yesterday.  I will follow up on 
that ticket next.

As far as I'm concerned, you may close this ticket (#571).

I'm sorry that I couldn't be of more help with this case.

**Comment by ffilz** [comment]
Thanks for the update, I will close this then. If someone down the road has an upgrade issue, we can revisit then.
