### ISSUE TITLE
Cephfs Ganesha Permission denied

### ISSUE THREAD

**Issue by mberzig** [nfs-ganesha/nfs-ganesha#572]
**Possible Bug**

We use ceph-ansible to deploy Ceph cluster docker version with Cephfs and Ganesha in order to create NFS share.
We can mount cephfs and we can create directory and file in this file system without problems.
We can mount NFS but it is impossible to create directory or files in this share, we get this error:

**mkdir: cannot create directory ‘/mnt/test’: Permission denied**

**Our Ganesha Configuration:**

`NFS_Core_Param`
`{`
`}`
`EXPORT_DEFAULTS {`
`	Attr_Expiration_Time = 0;`
`}`
`CACHEINODE {`
`	Dir_Chunk = 0;`
`	NParts = 1;`
`	Cache_Size = 1;`
`}`
`EXPORT`
`{`
`	Export_id=20133;`
`	Path = "/";`
`	Pseudo = /cephfile;`
`	Access_Type = RW;`
`	Protocols = 3,4;`
`	Transports = TCP;`
`	SecType = sys,krb5,krb5i,krb5p;`
`	Squash = Root_Squash;`
`	Attr_Expiration_Time = 0;`
`	FSAL {`
`		Name = CEPH;`
`		User_Id = "admin";`
`	}`     
`}`
`EXPORT`
`{`
`	Export_id=20134;`
`	Path = "/";`
`	Pseudo = /cephobject;`
`	Access_Type = RW;`
`	Protocols = 3,4;`
`	Transports = TCP;`
`	SecType = sys,krb5,krb5i,krb5p;`
`	Squash = Root_Squash;`
`	FSAL {`
`		Name = RGW;`
`		User_Id = "cephnfs";`
`		Access_Key_Id ="8YNWCSB66ANLDVWOCT3T";`
`		Secret_Access_Key = "b2zL5BzgMGdtA3FLbFSlzkoPgBtLfdHLeYsWMVQI";`
`	}`
`}`
`RGW {`
`        ceph_conf = "/etc/ceph/ceph.conf";`
`        cluster = "ceph";`
`        name = "client.rgw.ceph01";`      
`}`
`LOG {`
`        Facility {`
`                name = FILE;`
`                destination = "/var/log/ganesha/ganesha.log";`
`                enable = active;`
`        }`
`}`

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 3.10.0-1062.9.1.el7.x86_64
* Docker version if applicable (e.g. `docker version`): 1.13.1
* Ansible version (e.g. `ansible-playbook --version`): 2.8.10
* ceph-ansible version (e.g. `git head or tag or stable branch`): 4.0.20 
* Ceph version (e.g. `ceph -v`): 14.2.9

**Comment by dang** [comment]
Just to be clear, the export you're testing is /cephfile, not /cephobject? 
What version of Ganesha are you using?  Is there anything useful in the Ganesha logs?  If not, can you raise the log level to NIV_FULL_DEBUG and post the log with the failure in it?

**Comment by mberzig** [comment]
`NFS-Ganesha Release = V2.8.1.2`
Now it work properly when I change Root_Squash to No_Root_Squash in ganesha.conf:
`Squash = No_Root_Squash`
But RedHat recommend using  Root_Squash instead No_Root_Squash

**Comment by dang** [comment]
Okay, that means that the anonymous UID (4294967293 by default, and you appear to not have set it) does not have permission to write to that directory.  If you want to write as root, you'll need to give that UID (and/or the anonymous GID, which is the same number) read/write permissions to directories.  It works when you don't squash root because root has permission to write anywhere.

This also holds for any other user you want to be able to read/write: it needs to have permissions.

**Comment by ffilz** [comment]
Closing as resolved. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
