### ISSUE TITLE
Looping syslogging FSAL :EVENT :Socket is closed - enum compared with int

### ISSUE THREAD

**Issue by pjb1008** [nfs-ganesha/nfs-ganesha#574]
Hi,

I'm using FSAL_PROXY_V4. In the syslog it printed 3 lines of "Other end has closed connection, reconnecting..." and then looped as fast as it could syslogging "Socket is closed".

In FSAL_PROXY_V4/handle.c proxyv4_rpc_recv(), the return value from proxyv4_rpc_read_reply() is read into an enum clnt_stat, an enumeration that has small non-negative values. gcc choses an unsigned type where possible, so the success/failure test, if (rc >= 0), is always true.

As far as I can see, the declaration of rc in proxyv4_rpc_recv() should be an int - the value is either the rpc packet length or a negative errno, and nothing to do with clnt_stat.

I also noticed an issue waiting to catch someone in proxyv4_rpc_read_reply(). 
If a signal is received during read(), it will return a short value, which is handled correctly in the case where some data has been read into buf already. If no data has been read yet, read can't return 0 so it returns -1 and sets errno to EAGAIN. To handle this case, just after calling read, could you add  something iike:
if (bc == -1 && errno==EAGAIN) continue.

Thanks,

Peter

**Comment by dang** [comment]
It looks like rc is just the wrong type.  it should just be int.  That's what proxyv4_rpc_read_reply() is returning.

**Comment by ffilz** [comment]
Looks like something to fix.

**Comment by ffilz** [comment]
Simon, could you take a look at this one?

**Comment by ffilz** [comment]
Bump - lets take a look at this one before we release V4.0

**Comment by ffilz** [comment]
Maybe I'll have a look at this one and see if it's a simple fix.

**Comment by ffilz** [comment]
I'm going to fix the return type issue, If EINTR is really a problem for Ganesha, we really need to audit ALL the system calls for EINTR...

**Comment by ffilz** [comment]
Fixed the return value in https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/526323

If we want to audit all system calls for EINTR handling, let's open a separate github issue.
