### ISSUE TITLE
Compiling error on Suse SLES15SP1

### ISSUE THREAD

**Issue by dspisla** [nfs-ganesha/nfs-ganesha#579]
Hello,
I've tried out compiling ganesha v.2.6.7 on a SLES15SP1 machine. My steps are like follows:

Source code preparation:
$ cd nfs-ganesha
$ git submodule update --init
$ git checkout affd5942c
$ git checkout -b v2.7.6

Build Path:
$ mkdir ganesha-build && cd ganesha-build
$ cmake ../nfs-ganesha/src

Now I got the error:
_-- found krb5-config here KRB5_C_CONFIG-NOTFOUND
-- KRB5 was not found. Make sure the entries KRB5_* are set.
-- Looking for include file gssapi.h
-- Looking for include file gssapi.h - found
CMake Error at CMakeLists.txt:492 (message):
  Cannot find kerberos libraries_

I am wondering myself because the gssapi.h header is installed and also the krb5 packages:
$ find / -name gssapi.h
_/usr/include/gssapi/gssapi.h
/usr/include/gssapi.h_
$ rpm -qa | grep krb5*
_libndr-krb5pac0-4.7.11+git.153.b36ceaf2235-4.27.1.x86_64
krb5-1.15.2-6.9.1.x86_64
krb5-devel-1.15.2-6.9.1.x86_64_

I know that there is a flag -DUSE_GSS=NO but this is not a option because kerberos is part of our feature stack

What can be the reason for the error?

**Comment by dang** [comment]
You're missing /usr/bin/krb5-config  On Fedora, this is provided by krb5-devel

**Comment by kalebskeithley** [comment]
looks to me like he does have krb5-devel installed:
>  $ rpm -qa | grep krb5*
>  krb5-1.15.2-6.9.1.x86_64
>  krb5-devel-1.15.2-6.9.1.x86_64

I've never built 2.7.6 on SLES15SP1 — the 2.7.x series reached EOL before SLES15SP1 was released. But I did build it in on SLES15 in OBS at [1], complete build log at [2].

And the 2.8.x series is building just fine on SLES15SP1, e.g. the recent 2.8.4 build at [3] and build log at [4].

I can't say why your SLES15SP1 doesn't appear to have the krb5-config app. Maybe it's not in the path somehow when you do your builds?  SUSE used to give me an eval licence for SLES so that I could debug these sorts of things, but not any more; not for many many years.

What does `which krb5-config` tell you.  Or `rpm -ql krb5-devel` say about the location of krb5-config?



 
[1] https://build.opensuse.org/package/show/home:glusterfs:SLES15-nfs-ganesha-2.7/NFS-Ganesha-2.7.6
[2] https://build.opensuse.org/build/home:glusterfs:SLES15-nfs-ganesha-2.7/SLE_15/x86_64/NFS-Ganesha-2.7.6/_log
[3] https://build.opensuse.org/package/show/home:nfs-ganesha:SLES15SP1-nfs-ganesha-2.8/nfs-ganesha-2.8.4
[4] https://build.opensuse.org/build/home:nfs-ganesha:SLES15SP1-nfs-ganesha-2.8/SLE_15_SP1/x86_64/nfs-ganesha-2.8.4/_log

**Comment by dspisla** [comment]
Good morning from germany,
`which krb5-config` tells me that the krb5 config is in
_/usr/lib/mit/bin/krb5-config_

Should I change the path to that file in the ganesha source? Where I can do it?
@kalebskeithley  Thank you for the information. I will talk with my colleagues whether we can upgrade to v2.8.x

**Comment by dspisla** [comment]
Thank you for the help!
I could resolve the issue. The machine was *not* SLES15SP1 (wrong assumption), it was a SLES15 machine. The OS hasn't been updated for a long time. The machine is now up-do-date and after resolving some more dependencies the compilation by simple doing `make`  is running completely without error.

Next step would be building the packages for SLES15 including gluster FSAL.

I tried out doing cmake with
`cmake ../nfs-ganesha/src -DUSE_FSAL_GLUSTER=YES`

This leads to some other errors:

```
`-- Looking for llapi_hsm_state_get_fd in lustreapi
-- Looking for llapi_hsm_state_get_fd in lustreapi - not found
CMake Warning at CMakeLists.txt:581 (message):
  Cannot find lustreapi.  We will only build a dummy lustre fsal.


-- 
-- Looking for ceph_ll_lookup in cephfs
-- Looking for ceph_ll_lookup in cephfs - not found
-- Found cephfs libraries: CEPHFS_LIBRARY-NOTFOUND
-- Could NOT find CEPHFS (missing:  CEPHFS_INCLUDE_DIR CEPHFS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:591 (message):
  Cannot find CEPH runtime.  Disabling CEPH fsal build


-- Looking for open_by_handle in handle
-- Looking for open_by_handle in handle - not found
-- Looking for include file xfs/xfs.h
-- Looking for include file xfs/xfs.h - not found
CMake Warning at CMakeLists.txt:614 (message):
  Cannot find XFS runtime.  Disabling XFS build


-- checking for module 'glusterfs-api>=7.3.10.7'
--   package 'glusterfs-api>=7.3.10.7' not found
CMake Error at CMakeLists.txt:633 (message):
  Cannot find GLUSTER GFAPI runtime but requested on command line
`
```

But there is no glusterfs-api package for SUSE distributions. For SUSE we have glusterfs-devel package.

@kalebskeithley  In one of the link above there is dedicated *.spec file which can be used to build the packages for v2.7.6 on SLES15. How can I integrate it in the cmake progress?
I think cmake process executing `cmake ../nfs-ganesha/src -DUSE_FSAL_GLUSTER=YES` should not search for glusterfs-api.

Regards
David

**Comment by dang** [comment]
glusterfs-api is a pkgconfig file provided by Gluster, not a package name.  We never check for package name, because distros have different packaging, but instead we check for installed files (libraries, headers, and pkgconfig files).  This should be provided by some package on Suse.

**Comment by kalebskeithley** [comment]
the glusterfs-api pkgconfig file comes from the glusterfs-api-devel rpm. Both in the community packages GlusterFS provides in OBS at https://build.opensuse.org/users/glusterfs and I'm fairly certain in SLES's own packages.

But if you're not building FSAL_GLUSTER (because you're not using Gluster) then I would disable building FSAL_GLUSTER in your build.

**Comment by dspisla** [comment]
I have installed the gluster packages, especially glusterfs-devel, from the SUSE packages and indeed, this package provides the glusterfs-api pkgconfig file. The spec file was autogenerated by cmake and I had to do a little change to it in line 410:
`BuildRequires:        glusterfs-api-devel >= 3.8`
change to: `BuildRequires:        glusterfs-devel >= 3.8`

No other changes were necessary to built the packages. When I try to install the packages, I had to deal with a **package dependency issue**. Let me explain:

On our system we have the `libntirpc1_7-1.7.4-2.1.x86_64` packages from this ganesha repo installed: http://download.opensuse.org/repositories/home:/glusterfs:/SLES15-nfs-ganesha-2.7/SLE_15/x86_64/

Checking the dependencies with `rpm -qpR` I can see that `libtirpc3` is needed, which is both an my test system and my build server. So everything is fine with this.

But the name for my own libntirpc package differ a little bit: `libntirpc-1.7.4-2.1.x86_64` --> the **1_7** is missing. And with `rpm -qpR `I can see that `libtirpc` is needed --> the **3** is missing.
Trying to install my own libntirpc package results in dependency problem because the package manager tells me that "nothing provides libtirpc" because libtirpc3 is installed on my system.
The same problem with the nfs-ganesha packages.

Why does my own libntirpc packages don't have that **1_7** in the package name and that **3** in the dependency definition? As mentione above, I am using the autogenerated spec file created locally with cmake. Maybe thats the clue.

Well, anyway I installed my own packages breaking that mysterious dependency issue and ganesha is still running. Everything seems to be OK, but I think this is not a good solution at all. I want to clarify this.

**Comment by kalebskeithley** [comment]
with ganesha-3.8.x you _must_ use libntirpc-1.8.x.  Ganesha packages were unbundled from the glusterfs project in OBS and moved to their own project at https://build.opensuse.org/users/nfs-ganesha. You can find libntirpc-1.8.x packages there.

I couldn't tell you why SUSE decided to rename the glusterfs-api-devel package to glusterfs-devel.  That's not what the gluster community decided. It would have been nice if they had consulted with the gluster community and followed the community lead.

**Comment by dspisla** [comment]
Hello Kaleb,

> with ganesha-3.8.x you must use libntirpc-1.8.x. Ganesha packages were unbundled from the glusterfs project in OBS and moved to their own project at https://build.opensuse.org/users/nfs-ganesha. You can find libntirpc-1.8.x packages there.

I need libntirpc v1.7.4 because I built packages for ganesha v2.7.6 . The problem I have like mentioned above, is the naming of the packages and build dependencies.

> I couldn't tell you why SUSE decided to rename the glusterfs-api-devel package to glusterfs-devel. That's not what the gluster community decided. It would have been nice if they had consulted with the gluster community and followed the community lead.

Yes, SUSE should follow the community conventions. I don't know why they want to do there own naming. This leads to irritations.

**Comment by dang** [comment]
That is, with ganesha 2.8.x.  Ganesha 3.x needs ntirpc 3.x.  (in general, ganesha X.* needs ntirpc X.*, where X was 1.5, 1.6, 1.7, 1.8, and now 3)

I'm not sure where the 1_8 stuff is coming from.  Here's what rpm -qpR says on my system for ganesha 2.8.4:
libntirpc.so.1.8()(64bit)
libntirpc.so.1.8(NTIRPC_1.8.1)(64bit)

**Comment by dspisla** [comment]
> I'm not sure where the 1_8 stuff is coming from

Ok, I think this is really strange. Do you think it can be a risk to ignore the warning of the package manager and just install the own packages?

**Comment by dang** [comment]
As long as the library versions are correct, it should be okay.

**Comment by kalebskeithley** [comment]
I saw the (gluster) 3.8 and mentally translated that to ganesha 2.8. Sorry for the confusion. Yes, ganesha 2.7.x needs (lib)ntirpc 1.7.x

**Comment by dspisla** [comment]
Good news, I could resolve all issues with that dependencies. One has to edit this lines in the spec file template

```
vim src/nfs-ganesha.spec-in.cmake

Line 199:
Requires(pre): shadow-utils
change to: Requires(pre): shadow

Line 457:
Requires:       libtirpc
change to: Requires:       libtirpc3
```

The created RPMs could be installed without error and my system is running stable

**Comment by dspisla** [comment]
So I think I can close the issue for this time. 

Thank you @dang and @kalebskeithley for your help

**Comment by malahal** [comment]
We actually need  /usr/sbin/useradd binary from shadow or shadow-utils package, so we have this line in spec file. I will post upstream:

-Requires(pre): shadow-utils
+Requires(pre): /usr/sbin/useradd
