### ISSUE TITLE
mount error on windows client

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#584]
I use windows server 2016 to mount nfs-ganesha, sometime it is normal, but sometime it failed. The error mesage is “Network Error - 53", but when I run "showmount-e <ip>", it can show the nfs export path successfully. I search the problem on the Internet, some one say that configuring the /etc/export with insesure, such as
/tmp *(rw,insecure,no_root_squash)
So I want to ask, how to set insecure mode in nfs-ganesha.
Or the problem is cause by other reason, thank you~

**Comment by dang** [comment]
The equivalent is PrivilegedPort in the ExportDefaults block, but this is off by default, so unless you've changed it, Ganesha is already running "insecure".

(Note that this setting doesn't actually have anything to do with security unless you are running in a locked-down network where every machine is controlled by IT.  Anyone with a laptop or a phone can originate a connection from a "secure" port.)

**Comment by agin719** [comment]
thank you
