### ISSUE TITLE
nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE

### ISSUE THREAD

**Issue by tracymacding** [nfs-ganesha/nfs-ganesha#585]
what does this mean??????

**Comment by dang** [comment]
It means that Ganesha has exited the GRACE mode on startup, and is ready to handle normal operations.  GRACE is how NFS handles a crashed and restarted or failed-over NFS server.

**Comment by ffilz** [comment]
Closing due to age. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
