### ISSUE TITLE
Failed to enable the feature "ENABLE_VFS_DEBUG_ACL"

### ISSUE THREAD

**Issue by ColinHyu** [nfs-ganesha/nfs-ganesha#587]
Hi,

I wanted to use nfs-ganesha with ACL in my linux server .
I found that ganesha only supports nfsv4acl right now and only some FSAL types support nfsv4acl <-> posixACL mapping.
I chose VFS as my FSAL type and reference to https://github.com/nfs-ganesha/nfs-ganesha/issues/518,
I added "-DENABLE_VFS_DEBUG_ACL" flag in cmake command when I built ganesha, and there were some errors in build logs

```
[ 95%] Building C object FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/llapi_check_hsm.c.o

Linking C shared module libfsaldummylustre.so

CMakeFiles/fsaldummylustre.dir/__/handle.c.o: In function `makedir':

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/handle.c:571: undefined reference to `fsal_inherit_acls'

CMakeFiles/fsaldummylustre.dir/__/handle.c.o: In function `makenode':

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/handle.c:748: undefined reference to `fsal_inherit_acls'

CMakeFiles/fsaldummylustre.dir/__/handle.c.o: In function `makesymlink':

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/handle.c:978: undefined reference to `fsal_inherit_acls'

CMakeFiles/fsaldummylustre.dir/__/file.c.o: In function `vfs_open2':

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/file.c:678: undefined reference to `fsal_inherit_acls'

CMakeFiles/fsaldummylustre.dir/attrs.c.o: In function `vfs_sub_getattrs':

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/vfs/attrs.c:183: undefined reference to `fsal_print_acl_int'

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/vfs/attrs.c:193: undefined reference to `fsal_print_acl_int'

CMakeFiles/fsaldummylustre.dir/attrs.c.o: In function `vfs_sub_setattrs':

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/vfs/attrs.c:212: undefined reference to `fsal_print_acl_int'

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/vfs/attrs.c:214: undefined reference to `nfs4_ace_free'

/root/share/NasX86_QTSFW_4.5.x.git/NasX86/DataService/NFS/nfs-ganesha/src/FSAL/FSAL_VFS/vfs/attrs.c:219: undefined reference to `fsal_print_acl_int'

collect2: error: ld returned 1 exit status

FSAL/FSAL_VFS/vfs/CMakeFiles/fsaldummylustre.dir/build.make:348: recipe for target 'FSAL/FSAL_VFS/vfs/libfsaldummylustre.so.4.2.0' failed
```

I was sure about that there are correct .h file in handle.c, file.c and attrs.c, so I tried to edit. CMakeList.txt

In **MainNFSD CMakeList.txt**, I added two lines

`add_library(FsalCore_VFS_ACLS SHARED ${fsal_CORE_SRCS})`
`install(TARGETS FsalCore_VFS_ACLS LIBRARY DESTINATION ${FSAL_DESTINATION} )`

In **support CMakeList.txt**, I added two lines

`add_library(support_VFS_ACLS SHARED ${support_STAT_SRCS})`
`install(TARGETS support_VFS_ACLS LIBRARY DESTINATION ${FSAL_DESTINATION} )`

In **FSAL_VFS CMakeList.txt**, I modified two lines

`target_link_libraries(fsalvfs
      ganesha_nfsd
      FsalCore_VFS_ACLS
      support_VFS_ACLS
      ${fsalvfs_TGT_LINK_LIB}
      "-Wl,--no-undefined")`

`target_link_libraries(fsaldummylustre
      ganesha_nfsd
      FsalCore_VFS_ACLS
      support_VFS_ACLS
      ${fsalvfs_TGT_LINK_LIB}
      "-Wl,--no-undefined")`

All variables above are default.
In the end, the building completed successfully without any error.
But when I installed ganesha into my linux server and started it, it still showed some "**undefined symbol**" errors in ganesha.log (such as "hashtable_setlatched"、"mdcache_fsal_update_export").
I have also uploaded the new generated **libFsalCore_VFS_ACLS.so** and **libsupport_VFS_ACLS.so** to my linux server
I have tried ganesha **2.8.3** and **2.8.4**, but the results are same.

my questions are

1. How to enable "ENABLE_VFS_DEBUG_ACL" feature successfully?
2. I am a beginner in CMake, if I need to modify CMakeList, What am I missing?

Many thanks!

Attached is the building log before I modified CMakeList
[build_log.log](https://github.com/nfs-ganesha/nfs-ganesha/files/4715856/build_log.log)

**Comment by dang** [comment]
Looks like some symbols needed to be exported.  Fixed here:
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/494841

Keep in mind, the DEBUG_ACL code does not store ACLs in the filesystem, but only in memory.  This means they will be lost when Ganesha restarts for any reason.

**Comment by ColinHyu** [comment]
It works !!
Thanks you so much!!
Also, I really appreciate your warning, I will keep it mind !!

**Comment by ColinHyu** [comment]
Hi, Dang
I just enabled "ENABLE_RFC_ACL" feature and I found that two symbols "fsal_mode_to_acl" and "fsal_acl_to_mode" were also missing in libganesha_nfsd.ver, they are necessary to enable "ENABLE_RFC_ACL" feature.

**Comment by dang** [comment]
I've updated the PR with these changes.

**Comment by ColinHyu** [comment]
Hi, Dang
Thanks for your reply !
I also have a question about FSAL_VFS.
Is there any further plan to implement complete ACL function for FSAL_VFS in the future?
Just like FSAL_CEPH in  branch V4-dev.

**Comment by dang** [comment]
I'm not aware of anyone working on it, at the moment, but patches are welcome.

**Comment by ffilz** [comment]
Closing as resolved. We have it under general advisement that there is non-zero interest in full ACL implementation for FSAL_VFS however without resources to do so, we are unlikely to implement anything. Contributions and more people investing in the nfs-ganesha project are always welcome.
