### ISSUE TITLE
Whether NFS -ganesha supports docking with k8s?

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#588]
Whether NFS -ganesha supports docking with k8s?

**Comment by dang** [comment]
It does work.  We don't provide container builds, but several companies (for example Red Hat in it's Red Hat Ceph Storage product) do ship containerized versions that work with k8s.

**Comment by ffilz** [comment]
Closing as answered. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org

**Comment by ffilz** [comment]
Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
