### ISSUE TITLE
Which version of nfs-ganesha supports nfs4.1 protocol

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#590]
hello~, I want to ask which version of nfs-ganesha supports nfs4.1 protocol? I used nfs-ganesha 2.5, But it doesn't seem to support nfs4.1. Thank you ~

**Comment by kalebskeithley** [comment]
I'm pretty sure  2.5.x supported NFSv4.1, but 2.5 has been EOL for a long time and there are likely bugs.

The current supported versions are 2.8.x and 3.x. I suggest trying one of those. There are packages for the more popular linux distributions on download.nfs-ganesha.org.
