### ISSUE TITLE
pNFS with VFS not working

### ISSUE THREAD

**Issue by oparkins** [nfs-ganesha/nfs-ganesha#592]
I'm trying to setup ganesha to use pNFS. My ganesha version is:
```
# ganesha.nfsd -v
NFS-Ganesha Release = V3.0.3
```

My configuration file is:
```
EXPORT
{
        Export_Id = 22552;

        Path = /storage;
        Pseudo = /storage;
        Protocols = 4, NFSv4;
        Access_Type = RW;
        Squash = no_root_squash;
        FSAL {
                Name = vfs;
                pnfs = true;
        }
}
```

And when I run `systemctl restart nfs-ganesha`, I receive the following error in the logs:
```
ganesha.nfsd-1681[main] config_errs_to_log :CONFIG :WARN :Config File (/etc/ganesha/ganesha.conf:62): Unknown parameter (pnfs)
```

The man page for `ganesha-vfs-config` shows:
```
   EXPORT { FSAL {} }
       Name(string, vfs )
              Name of FSAL should always be vfs.

       pnfs(bool, default false)
```

So it should be possible. Is there something that has gone missing from the ganesha or I'm I just missing something?

**Comment by oparkins** [comment]
Well, I found the problem. In `src/FSAL/FSAL_VFS/vfs/main-c.in.cmake`, the config items array does not include `pnfs`. Is there a reason it was removed or not included there even though the change log says that it is possible?

**Comment by ffilz** [comment]
pNFS was only ever supported for the PANFS version of FSAL_VFS, built for Panasas storage. Panasas has abandoned Ganesha.

I'm not sure what the state of pNFS support is for Ganesha. FSAL_GPFS did have a functional pNFS implementation but I don't think IBM supports it anymore. FSAL_GLUSTER has some degree of pNFS support, but I'm not sure it's complete let alone supported.

**Comment by oparkins** [comment]
Okay. That is a bummer. Thanks for the insight though.

**Comment by dang** [comment]
One additional note: VFS can't support pNFS, because it's not a clustered filesystem. Ganesha doesn't provide clustering, it depends on the backing filesystem to provide clustering, and VFS is just a local filesystem, so it can't support pNFS.

You'd need a real clustered FS, such as Gluster, Ceph, or GPFS, or you'd need to write clustering for local filesystems (which is effectively what Gluster does).
