### ISSUE TITLE
How can I get librgw.so v1.1.7(or above) in ubuntu18.0.4?

### ISSUE THREAD

**Issue by neohope** [nfs-ganesha/nfs-ganesha#594]
I am trying to build nfs-ganesha v3.2 in ubuntu18.0.4. Everything goes well except librgw.so. The librgw.so in Ubuntu18.0.4 is 1.1.6, while nef-ganesha nees 1.1.7. How can I get librgw.so v1.1.7(or above)? Thanks!

In CMakeLists.txt:
```
find_package(RGW 1.1.7 ${USE_FSAL_RGW_REQUIRED})
```

In /nfs-ganesha/src/FSAL/FSAL_RGW/internal.h
```
#if ((LIBRGW_FILE_VER_MAJOR != 1) || (LIBRGW_FILE_VER_MINOR < 1) || \
        (LIBRGW_FILE_VER_EXTRA < 7))
#error rados/rgw_file.h version unsupported (require >= 1.1.1)
#endif
```

**Comment by dang** [comment]
Upstream Ceph provides packages for many distros and versions:
https://docs.ceph.com/docs/mimic/install/get-packages/
I think you need at least nautilus.

**Comment by neohope** [comment]
Thanks! 

I tried to build both ceph(v15.2.3) and nfs-ganesha(V3.3) last night. It turns out that mount rgw works (readonly, do not know why) while mount cephfs does not work. 

I will try it this weekend.

**Comment by neohope** [comment]
It works!

```
wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
sudo apt-add-repository 'deb https://download.ceph.com/debian-octopus/ bionic main'
sudo apt-get update

apt-get install gcc git cmake autoconf libtool bison flex
apt-get install libssl-dev  libnfs-dev doxygen libgssglue-dev libkrb5-dev liburcu-dev libntirpc-dev
apt-get install libnfsidmap-dev uuid-dev libblkid-dev
apt-get install librados-dev librgw-dev libcephfs-dev nfs-ganesha-ceph
snap install cmake  --classic

git clone https://github.com/nfs-ganesha/nfs-ganesha.git
git checkout V3.2
git submodule update --init --recursive

mkdir build
cd build
ccmake ../src

make
make install
```
