### ISSUE TITLE
About NFS-Ganesha data synchronization

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#596]
Three are on different physical machines and connected to the same CEPHFS cluster. If one of the three nfs-ganesha has read and write traffic, do I need to restart nfs-ganesha for the other two if I want data synchronization?

**Comment by dang** [comment]
No, it works fine.  CephFS is fully clustered, and Ganesha is a fully clustered client, to it's okay.

**Comment by fantastic2085** [comment]
@dang 
How is NFS-Ganesha clustered?Can't nfs-Ganesha synchronize data?Has clustering been supported since 2.8

**Comment by malahal** [comment]
Ganesha doesn't have its own clustering. You can use an existing clustering mechanism with Ganesha.

**Comment by dang** [comment]
(Sorry, I meant that FSAL_CEPH is a proper client of the Ceph cluster, not that Ganesha is clustered itself)

**Comment by ffilz** [comment]
Closing as answered. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
