### ISSUE TITLE
Which version fixes this problem

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#602]
I meet this problem too.
https://github.com/nfs-ganesha/nfs-ganesha/issues/342

has nfs-ganesha 2.5 fixed this problem?  
It fixed in nfs-ganesha2.6 or higher version?

**Comment by dang** [comment]
No, 2.5 does not have a fix.  2.6 does, but that's also very out-of-date.  Use 2.8 or 3.x.
