### ISSUE TITLE
How does Ganesha specify an IP that cannot mount, or that mount failed with that IP client

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#604]
How does Ganesha specify an IP that cannot mount, or that mount failed with that IP client?
NFS version is V4

**Comment by dang** [comment]
Create a CLIENT{} block in the relevant export, with the correct set of IPs, and Access_Type = None

**Comment by ffilz** [comment]
Note that the CLIENT blocks form an ordered ACL, so put your "deny" entries first.

Also, we recommend using the support@lists.nfs-ganesha.org  mailing list for asking questions.

Closing this as answered, re-open if you have more questions on this subject.
