### ISSUE TITLE
About NFS-Ganesha and Ceph RBD

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#607]
Does NFs-Ganesha not support ceph RBD export?

**Comment by dang** [comment]
No, sorry.  Just CephFS and RGW.  We can't really export RBD, since it's a block device, not a filesystem.  You could mount the RBD on the local system, and export it via FSAL_VFS, however.

**Comment by fantastic2085** [comment]
Mount the RBD on the local System, and export it via FSAL_VFS, which can then be used externally over the NFS protocol?

**Comment by kalebskeithley** [comment]
Requires:         %{name}-

On Mon, Jul 6, 2020 at 10:09 PM fuzhiyu <notifications@github.com> wrote:

> Mount the RBD on the local System, and export it via FSAL_VFS, which can
> then be used externally over the NFS protocol?
>

Yes, just like you would mount any other block device — containing a file
system presumably — and then export it.

--

Kaleb

**Comment by ffilz** [comment]
Closing as answered. This is a question that would have been better asked on the support mailing list support@lists.nfs-ganesha.org.
