### ISSUE TITLE
Questions about NFS3 NLM，NSM lock error

### ISSUE THREAD

**Issue by zanglinjie** [nfs-ganesha/nfs-ganesha#611]
Questions about NFS3 NLM，NSM lock error：
Client：
in nfs-ganesha mount point：
 touch f1；
exec 200>f1;
flock -xn 200
### **[error: on lock available ]**

Server nfs-ganesha log:
nsm_monitor :Can not monitor ::ffff:10.10.10.102 SM_MON ret 5 : RPC: Timed out

client rpcdebug log :
Jul 13 15:28:51 cu09 kernel: lockd: get host 10.10.10.212
Jul 13 15:28:51 cu09 kernel: lockd: get host 10.10.10.212
Jul 13 15:28:51 cu09 kernel: lockd: nsm_monitor(10.10.10.212)
Jul 13 15:28:51 cu09 kernel: lockd: call procedure 2 on 10.10.10.212
Jul 13 15:28:51 cu09 kernel: lockd: nlm_bind_host 10.10.10.212 (10.10.10.212)
Jul 13 15:28:51 cu09 kernel: lockd: next rebind in 60000 jiffies
Jul 13 15:29:16 cu09 kernel: lockd: server returns status 2
Jul 13 15:29:16 cu09 kernel: lockd: release client host 10.10.10.212
Jul 13 15:29:16 cu09 kernel: lockd: release client host 10.10.10.212
Jul 13 15:29:16 cu09 kernel: lockd: clnt proc returns -37

What is the cause of the above?

【Client】
[root@fat01 ~]# uname -a
Linux fat01 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@fat01 ~]# 
[root@fat01 ~]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

root@fat01 ~]# rpm -qa|grep nfs
texlive-psnfss-svn23394.9.2a-38.el7.noarch
libnfsidmap-0.25-19.el7.x86_64
nfs-utils-1.3.0-0.54.el7.x86_64
texlive-mfnfss-svn19410.0-38.el7.noarch
nfs4-acl-tools-0.3.3-17.el7.x86_64
[root@fat01 ~]# rpm -qa|grep rpc
xmlrpc-c-client-1.32.5-1905.svn2451.el7.x86_64
xmlrpc-c-1.32.5-1905.svn2451.el7.x86_64
rpcbind-0.2.0-44.el7.x86_64
libtirpc-0.2.4-0.10.el7.x86_64
kdepimlibs-kxmlrpcclient-4.10.5-4.el7.x86_64
【server】
ganesha:NFS-Ganesha Release = V2.7.3

**Comment by ffilz** [comment]
This kind of question is best asked on our support mailing list support@lists.nfs-ganesha.org  rather than in an issue, however:

Check and make sure your have rpc.statd running on the server.

**Comment by zanglinjie** [comment]
Thanks for your help @ffilz
rpc.statd  and rcpbind running

**Comment by ffilz** [comment]
Is nfs-ganesha running as root? The error is clearly indicating that nfs-ganesha can not register the client with rpc.statd.

**Comment by ffilz** [comment]
Closing, this issue has been taken to the mailing list.
