### ISSUE TITLE
nfs-ganesha process dont start

### ISSUE THREAD

**Issue by rvelasquezsos** [nfs-ganesha/nfs-ganesha#616]
Hi, I have two Ganesha gateways in active-passive configuration with backend Cephfs.
I moved the configuration files from a pool Ceph to another and made re-deployment of stage 4 of Ceph.
And now one Ganesha gateway doesn't start, the other works fine.
The ganesha.log shows:

> 18/07/2020 15:36:04 : epoch 5f134f24 : ganesha01 : ganesha.nfsd-1603743[main] main :NFS STARTUP :CRIT :Error (token scan, parser rule) while parsing (/etc/ganesha/ganesha.conf)
> 18/07/2020 15:36:04 : epoch 5f134f24 : ganesha01 : ganesha.nfsd-1603743[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:48): Unexpected character (r)
> 18/07/2020 15:36:04 : epoch 5f134f24 : ganesha01 : ganesha.nfsd-1603743[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:0): Configuration syntax errors found
> 18/07/2020 15:36:04 : epoch 5f134f24 : ganesha01 : ganesha.nfsd-1603743[main] main :NFS STARTUP :FATAL :Fatal errors.  Server exiting...

and status of service show:

> ganesha01:/ # systemctl status nfs-ganesha
> ● nfs-ganesha.service - NFS-Ganesha file server
>    Loaded: loaded (/usr/lib/systemd/system/nfs-ganesha.service; disabled; vendor preset: disabled)
>    Active: inactive (dead) since Sat 2020-07-18 18:37:53 -04; 7s ago
>      Docs: http://github.com/nfs-ganesha/nfs-ganesha/wiki
>   Process: 1690835 ExecStop=/bin/dbus-send --system --dest=org.ganesha.nfsd --type=method_call /org/ganesha/nfsd/admin org.ganesha.nfsd.admin.shutdown (code=exited, status=0/SUCCESS)
>   Process: 1690833 ExecStartPost=/bin/bash -c /usr/bin/sleep 2 && /bin/dbus-send --system   --dest=org.ganesha.nfsd --type=method_call /org/ganesha/nfsd/admin  org.ganesha.nfsd.admin.init_fds_limit (code=exited, status=0>
>   Process: 1690832 ExecStartPost=/bin/bash -c prlimit --pid $MAINPID --nofile=$NOFILE:$NOFILE (code=exited, status=1/FAILURE)
>   Process: 1690830 ExecStart=/bin/bash -c ${NUMACTL} ${NUMAOPTS} /usr/bin/ganesha.nfsd ${OPTIONS} ${EPOCH} (code=exited, status=0/SUCCESS)
> 
> Jul 18 18:37:51 ganesha01 systemd[1]: Starting NFS-Ganesha file server...
> Jul 18 18:37:51 ganesha01 bash[1690832]: prlimit: invalid PID argument: '--nofile=1048576:1048576'
> Jul 18 18:37:53 ganesha01 systemd[1]: Started NFS-Ganesha file server.

the /etc/ganesha/ganesha.conf

> 
> RADOS_URLS {
>   # Path to a ceph.conf file for this cluster.
>   Ceph_Conf = /etc/ceph/ceph.conf;
> 
>   # RADOS_URLS use their own ceph client too. Authenticated access
>   # requires a cephx keyring file.
>   UserId = "ganesha.ganesha01";
>   watch_url = "rados://('cephfs_data', 'ganesha_config')/ganesha/conf-ganesha01";
> }
> 
> 
> 
> # The libcephfs client will aggressively cache information while it
> # can, so there is little benefit to ganesha actively caching the same
> # objects. Doing so can also hurt cache coherency. Here, we disable
> # as much attribute and directory caching as we can.
> 
> CACHEINODE {
>     # Size the dirent cache down as small as possible.
>     Dir_Chunk = 0;
> 
>     # size the inode cache as small as possible
>     NParts = 1;
>     Cache_Size = 1;
> }
> 
> 
> 
> 
> 
> RGW {
>     ceph_conf = "/etc/ceph/ceph.conf";
>     name = "client.rgw.ganesha.ganesha01";
>     cluster = "ceph";
> }
> 
> 
> 
> 
> #NFS-Ganesha is compiled with kerberos support.
> #Set this value to true to use kerberos support.
> #Refer to man page "ganesha-core-config"
> NFS_KRB5
> {
>     Active_krb5 = false;
> }
> 
> %url rados://('cephfs_data', 'ganesha_config')/ganesha/conf-ganesha01
> 

This is the ganesha installed

> ganesha01:/ # rpm -q nfs-ganesha
> nfs-ganesha-2.8.3+git0.d504d374e-3.3.1.x86_64

any ideas? thanks in advance.

**Comment by dang** [comment]
Sounds like you don't have the rados-urls package installed.

**Comment by rvelasquezsos** [comment]
> Sounds like you don't have the rados-urls package installed.

Hi @dang yes I have it.
I could fix the problem modifying the following lines

> watch_url = "rados://('cephfs_data', 'ganesha_config')/ganesha/conf-ganesha01";
with
> watch_url = "rados://ganesha_config/ganesha/conf-ganesha01";
and
> %url rados://('cephfs_data', 'ganesha_config')/ganesha/conf-ganesha01
with
> %url rados://ganesha_config/ganesha/conf-ganesha01

ganesha_config is the new pool with the configuration and exports of ganesha
and cephfs_data is the pool with the data and the old configuration.
The syntax of rados address was incorrect? It was automatically generated by Ceph deployment.
I don't know why that's wrong.

**Comment by supriti** [comment]
@rvelasquezsos how did you deploy nfs-ganesha? It seems like deployment is doing something wrong while creating the config file.

**Comment by rvelasquezsos** [comment]
> @rvelasquezsos how did you deploy nfs-ganesha? It seems like deployment is doing something wrong while creating the config file.

@supriti the deployment was made trough "salt", the cluster is SUSE Enterprise Storage. The Ceph product supported by SUSE. The deployment is made with 4 stages with salt orchestrator.

Thanks

**Comment by supriti** [comment]
@rvelasquezsos Are you using Deepsea? https://github.com/SUSE/DeepSea If yes then can you create a issue there?

**Comment by rvelasquezsos** [comment]
> @rvelasquezsos Are you using Deepsea? https://github.com/SUSE/DeepSea If yes then can you create a issue there?

Yes, I'm going to create an issue for deepsea.

Thanks
