### ISSUE TITLE
Some references to master and blacklist remain in nfs-ganesha project

### ISSUE THREAD

**Issue by ffilz** [nfs-ganesha/nfs-ganesha#617]
[root@localhost src]# egrep -in 'whitelist|blacklist|master|slave' `find . -type f | grep -v libntirpc`
./doc/man/conf.py:46:master_doc = 'index'
./FSAL/FSAL_LIZARDFS/lzfs_internal.h:36:#define SPECIAL_INODE_MASTERINFO		(SPECIAL_INODE_BASE + 0xFU)
./FSAL/FSAL_LIZARDFS/lzfs_internal.h:46:#define SPECIAL_FILE_NAME_MASTERINFO		".masterinfo"
./FSAL/FSAL_PROXY_V4/handle_mapping/handle_mapping_db.c:347:			       "SELECT name FROM sqlite_master WHERE type = 'table' AND name = '"
./FSAL/FSAL_CEPH/main.c:199:		 * (ganesha) being blacklisted in the cluster. Fixing that can
./FSAL/FSAL_GPFS/include/gpfs.h:3840: *              Master Encryption Key (MEK) with the new key provided as
./FSAL/FSAL_GPFS/include/gpfs.h:3891: *              length, Master Encryption Key(s) ID, and wrapping and combining
./cmake/modules/FindSanitizers.cmake:45:function(sanitizer_add_blacklist_file FILE)
./cmake/modules/FindSanitizers.cmake:51:    sanitizer_check_compiler_flags("-fsanitize-blacklist=${FILE}"
./cmake/modules/FindSanitizers.cmake:52:        "SanitizerBlacklist" "SanBlist")
./Doxyfile.in:1014:# it should be included in the master .chm file (NO).

**Comment by dang** [comment]
That's shockingly few, and only 2 might cause issues.

**Comment by ffilz** [comment]
Well, there were a lot in tools/multilock, though those should have been eliminated much earlier when the "master" became the "console" because it never made sense to call the "clients" slaves (you can run the client standalone).

NFS in general doesn't have the type of superior and subordinate structure that was historically labeled master/slave (and we don't actually do clustering in nfs-ganesha itself) and it doesn't do filtering in the way to encourage use of blacklist/whitelist (instead, for example, if any restrictions are placed on which clients are mounted, NFS exports simply specify what kind of access each client has with the default being none).

Which two would cause trouble? Several seemed to be references outside of Ganesha, though some just as comments like "Master Encryption Key" but can we change something like that without confusion? (Plus those two are in a GPFS file actually inherited from GPFS so we shouldn't change it).

**Comment by malahal** [comment]
GPFS comment can easily be changed to 'Main', I imagine.  Dan was probably referring to -fsanitize-blasklist and an sqlite one. Those are outside of ganesha though.

**Comment by dang** [comment]
Yep, the sanitizer (which is a compiler option, and so even if a new one is available, we'll have to keep the old one for a long time), and the sqlite DB, where it's a database key, and would require a schema change.

**Comment by ffilz** [comment]
We did our best to clean stuff up, what remains isn't really in the capacity of the general Ganesha community to fix.
