### ISSUE TITLE
NFSv3 MOUNT:  access authentication does not take affect 

### ISSUE THREAD

**Issue by jimhuaang** [nfs-ganesha/nfs-ganesha#618]
- Nfs-Ganesha versoin: 2.6.3

- Protocol: NFSv3/MOUNT

- Problem Description
mnt_Mnt count on the export_check_access to do acl auth, but for a client out of the export acl list,  it seems a default export permission is used. so MOUNT seems fail to do authentication.
[https://github.com/nfs-ganesha/nfs-ganesha/blob/f1b9ee8e2f6a76daff78bbec92030a863d3f7364/src/Protocols/NFS/mnt_Mnt.c#L128](url)

- Some Tests
Following is some test for a client with IP out of the export ACL list, 

|client| server | MOUNT reply| FSINFO reply |  mount result|
|-------|----------|-------------------|--------------------|-------------------|
|linux   |   nfs-kernel|    AUTH_ERR|  (no req)   |     fail (access denied)|
|window10|  nfs-kernel|  AUTH_ERR |      (no req)          |    fail (errno 53)|
|linux|     nfs-ganesha   |   AUTH_OK    |            AUTH_ERR   |      fail (access denied)|
|windows10 |                   nfs-ganesha|       AUTH_OK   |             AUTH_ERR   |  NO error|

Windows10 client mount just success if the MOUNT response is ok. It then ignores the response's AUTH_ERR of following NFS FSINFO, GetAttr requests. As a result, windows client keep retrying GetAttr(mount_point) again and again. About hundreds of thousands request is sent in a second.

As a compare, linux client will error out when FSINFO response with AUTH_ERR. 

- Not test with the newest NFS-ganesha version. But it seems the mnt_Mnt access check logic is the same as V2.6.3.

**Comment by ffilz** [comment]
What is your export configuration?

**Comment by jimhuaang** [comment]
For example, a client has a IP of 172.10.20.2, trying to mount export of 'test_acl' with following configuration,

```
EXPORT
{
    Export_Id = 2;
    Path = /test_acl;
    Pseudo = /test_acl;
    
    CLIENT {
        Clients = 172.10.20.6;
        Squash = None;
        Access_type = RW;
    }
    
    FSAL {
        Name = VFS;
    }
}
```

**Comment by jimhuaang** [comment]
> mnt_Mnt count on the export_check_access to do acl auth, but for a client out of the export acl list, it seems a default export permission is used. so MOUNT seems fail to do authentication.

My previous comment is not correct. In this situation, the export permission check is no the issue. The problem is the client is not in the export's client list, and mnt_Mnt doesn't handle this.
All the access check in mnt_Mnt is about the opt_ctx->export_perms.

Also the tests in previous comment has been updated; when used kernl-nfs server, the client mount fail after get AUTH_ERR response for MOUNT req, there is no more FSINFO request.

**Comment by ffilz** [comment]
BUMP I'll take another look at this....

**Comment by ffilz** [comment]
Ok, the client should not have been able to actually mount or do anything, however, we indeed did not make the proper checks to return an error on the MOUNT request. The following patch fixes that:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/505850

**Comment by ffilz** [comment]
Note that V2.6.x is no longer supported so this fix may be back ported to V3.x and possibly V2.8.x but not V2.6.x or V2.7.x

**Comment by jimhuaang** [comment]
thanks for the response.

**Comment by ffilz** [comment]
I'm re-opening this since it has the "should_be_backported" label.

I've removed the needs_verification label.

**Comment by ffilz** [comment]
This has been back ported to V3.4 closing.
