### ISSUE TITLE
export ganesha-nfs failed by openstack manila

### ISSUE THREAD

**Issue by mslovy** [nfs-ganesha/nfs-ganesha#619]
We use ganesha-nfs 2.7.x and 2.8.x and openstack stable/train manila.

The manila nfs allow access rule sometimes are created failed, but not awlays; when failed, we find that manila got errors from ganesha like below:

2020-07-30 08:24:13.772 32 DEBUG oslo_concurrency.processutils [req-2b9c6040-7506-4233-a8e5-b86a8a7762a6 627e5c874cac49ec80350f9300b5c0da c339d984b3094a0cb57e93a118729ad3 - - -] Running cmd (subprocess): sudo manila-rootwrap /etc/manila/rootwrap.conf sh -c echo 'EXPORT {
    CLIENT {
        Clients = 10.0.6.173;
        Access_Type = "rw";
    }

    SecType = "sys";
    Pseudo = "/volumes/_nogroup/f729895e-cb11-4c30-93af-bf79c3ca1d27";
    Squash = "None";
    FSAL {
        User_Id = "ganesha-f729895e-cb11-4c30-93af-bf79c3ca1d27";
        Secret_Access_Key = "AQAsEyJfUmlAHBAAoxxC67LAo96TtP+37JIxvw==";
        Name = "Ceph";
    }
    Tag = "share-f729895e-cb11-4c30-93af-bf79c3ca1d27";
    Path = "/volumes/_nogroup/f729895e-cb11-4c30-93af-bf79c3ca1d27";
    Export_Id = 101;
}

command: sudo manila-rootwrap /etc/manila/rootwrap.conf dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/export.d/share-f729895e-cb11-4c30-93af-bf79c3ca1d27.conf string:EXPORT(Export_Id=101)
Exit code: 1
Stdout: u''
Stderr: u'Error org.freedesktop.DBus.Error.InvalidFileContent: 0 export entries in /etc/ganesha/export.d/share-f729895e-cb11-4c30-93af-bf79c3ca1d27.conf added because (export create, block validation) errors. Details:\nConfig File (/etc/ganesha/export.d/share-f729895e-cb11-4c30-93af-bf79c3ca1d27.conf:10): 1 validation errors in block FSAL\nConfig File (/etc/ganesha/export.d/share-f729895e-cb11-4c30-93af-bf79c3ca1d27.conf:10): Errors processing block (FSAL)\nConfig File (/etc/ganesha/export.d/share-f729895e-cb11-4c30-93af-bf79c3ca1d27.conf:1): 1 validation errors in block EXPORT\nConfig File (/etc/ganesha/export.d/share-f729895e-cb11-4c30-93af-bf79c3ca1d27.conf:1): Errors found in configuration block EXPORT\n\n'

**Then we find out the error in ganesha log below:** 

30/07/2020 17:53:33 : epoch 5f22814f : control2 : ganesha.nfsd-533861[dbus_heartbeat] create_export :FSAL :CRIT :Unable to mount Ceph cluster for /volumes/_nogroup/eda1e8af-75c9-4973-a4b5-47c4ac84a693.
30/07/2020 17:53:33 : epoch 5f22814f : control2 : ganesha.nfsd-533861[dbus_heartbeat] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL Ceph
30/07/2020 17:53:33 : epoch 5f22814f : control2 : ganesha.nfsd-533861[dbus_heartbeat] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/volumes/_nogroup/eda1e8af-75c9-4973-a4b5-47c4ac84a693) to (/volumes/_nogroup/eda1e8af-75c9-4973-a4b5-47c4ac84a693)
30/07/2020 17:53:33 : epoch 5f22814f : control2 : ganesha.nfsd-533861[dbus_heartbeat] gsh_export_addexport :EXPORT :CRIT :0 export entries in /etc/ganesha/export.d/share-eda1e8af-75c9-4973-a4b5-47c4ac84a693.conf added because (export create, block validation) errors
30/07/2020 17:53:33 : epoch 5f22814f : control2 : ganesha.nfsd-533861[dbus_heartbeat] dbus_message_entrypoint :DBUS :MAJ :Method (AddExport) on (org.ganesha.nfsd.exportmgr) failed: name = (org.freedesktop.DBus.Error.InvalidFileContent), message = (0 export entries in /etc/ganesha/export.d/share-eda1e8af-75c9-4973-a4b5-47c4ac84a693.conf added because (export create, block validation) errors. Details:
Config File (/etc/ganesha/export.d/share-eda1e8af-75c9-4973-a4b5-47c4ac84a693.conf:10): 1 validation errors in block FSAL
Config File (/etc/ganesha/export.d/share-eda1e8af-75c9-4973-a4b5-47c4ac84a693.conf:10): Errors processing block (FSAL)
Config File (/etc/ganesha/export.d/share-eda1e8af-75c9-4973-a4b5-47c4ac84a693.conf:1): 1 validation errors in block EXPORT

**Comment by dang** [comment]
ceph_mount() failed.  This is part of the Ceph code.  Something is wrong with the CephFS path that's being mounted.  Likely either it doesn't exist, or the user/creds aren't valid for that path.

**Comment by ffilz** [comment]
Closing since this hasn't seen any response in months. Reopen if this is still an issue.

**Comment by jacolex** [comment]
Hello
I'm trying to deploy cephfs nfs on Openstack Xena and still have the same issue.

[...] Command: sudo manila-rootwrap /etc/manila/rootwrap.conf dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/export.d/share-xxxxxxx.conf string:EXPORT(Export_Id=yyy)

Stderr: 'Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.ganesha.nfsd was not provided by any .service files\n'
[...]

**Comment by ffilz** [comment]
What version of Ganesha?

**Comment by dang** [comment]
This is a different issue.  Your openstack didn't install the proper files to enable dbus on Ganesha.  org.ganesha.nfsd.conf needs to be installed in /etc/dbus-1/system.d/.

**Comment by jacolex** [comment]
So my case is not related. It's related to kolla-ansible.

**Comment by ffilz** [comment]
> So my case is not related. It's related to kolla-ansible.

Could you open a new issue then if you still need help with your issue?

**Comment by jacolex** [comment]
OK, thanks.

**Comment by ffilz** [comment]
Looks like this one can be closed as the recent activity is a different issue.
