### ISSUE TITLE
Windows 7 NFS client, FSAL_LUSTRE : "dir" returns only 48 entries, all files available

### ISSUE THREAD

**Issue by rdynes** [nfs-ganesha/nfs-ganesha#62]
Setup: Windows 7 client connecting to a NFS-Ganesha ('next' branch) on a Lustre client a 'dir' in a command shell on Windows returns 48 only entries.   A Linux client operates correctly.

The invisible files are available: with the correct file name they can be 'dir'd.   A separate issue is that they might not be able to be read.

.tgz of config, log file, pcap and text tshark outputs:

http://pastebin.com/gMq198Gv

**Comment by ffilz** [comment]
Is this still an issue? If not, can this issue be closed? I will close it next week if there is no response otherwise.
