### ISSUE TITLE
threre is no nfs-ganesha-ceph 3.3 with ubuntu bionic in ppa

### ISSUE THREAD

**Issue by zhangheng028** [nfs-ganesha/nfs-ganesha#622]
threre is no nfs-ganesha-ceph 3.3 with ubuntu bionic in ppa

**Comment by kalebskeithley** [comment]
bionic only has ceph-12, which is too old to build FSAL_CEPH (i.e. nfs-ganesha-ceph)

ubuntu eoan and later have ceph-14 (or later) and do build FSAL_CEPH.
