### ISSUE TITLE
LRU lane not making progress - quick fix

### ISSUE THREAD

**Issue by dang** [nfs-ganesha/nfs-ganesha#623]
It can happen that lru_run_lane() doesn't make progress, because all the entries at the LRU of L1 are ref'd, and so can't be demoted.

Quick and dirty fix:  The L1 to L2 demotion is about closing the global FD; so demote entries with no global FD open even if they're ref'd.

**Comment by ffilz** [comment]
The LRU has been reworked. Closing this. New issues will be raised if we find problems after the rework.
