### ISSUE TITLE
LRU lane not making progress - big fix

### ISSUE THREAD

**Issue by dang** [nfs-ganesha/nfs-ganesha#624]
It can happen that lru_run_lane() doesn't make progress because all the entries at the LRU of L1 are ref'd.

The complicate fix is to have two different refcounts: one for state, and one for everything else.  Both ref's keep the entry from being reaped, but the state ref doesn't block the level transition, allowing the global FD to be closed.  This allows closing the global FD on entries with file locks.

**Comment by ffilz** [comment]
This has been resolved and completed. Closing.
