### ISSUE TITLE
Threre is no nfs-ganesha-rgw 2.8.X or 3.3 with ubuntu xenial in ppa

### ISSUE THREAD

**Issue by Palollo** [nfs-ganesha/nfs-ganesha#628]
Threre is no deb package for nfs-ganesha-rgw 2.8.X or 3.3 with ubuntu **xenial** in ppa.
http://ppa.launchpad.net/nfs-ganesha/nfs-ganesha-2.8/ubuntu/pool/main/n/nfs-ganesha/
http://ppa.launchpad.net/nfs-ganesha/nfs-ganesha-3.0/ubuntu/pool/main/n/nfs-ganesha/
Why? Is there any problem or missing dependency?

**Comment by dang** [comment]
Yeah, xenial doesn't have a new enough ceph version.
