### ISSUE TITLE
Not all files listed in Ganesha 2.1 and 2.2

### ISSUE THREAD

**Issue by ACiDGRiM** [nfs-ganesha/nfs-ganesha#63]
I've run into a strange issue where, while verified on the exporting system, not all files (or folders) are listed via ls. When this occurs, the missing file(s) can be listed directly by path, and fail to appear in the find command.

Renaming the file causes it to appear, however, naming it back causes the rename to appear as the old name and new name.

This occurs with or with out InodeCaching

EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 77;

        # Exported path (mandatory)
        Path = /mnt/storage/content;
SecType = sys;
Disable_ACL = TRUE;
Squash = No_root_squash;
Access_type = RW;

        # Pseudo Path (required for NFS v4)
        Pseudo = /content;

        # Exporting FSAL
        FSAL {
                Name = VFS;
                pnfs = true;
        }
}

CacheInode
{
Directory_Expiration_Time = 0;
Attr_Expiration_Time = 0;
Symlink_Expiration_Time = 0;
}

**Comment by phdeniel** [comment]
Which version are you running ? What you describe looks like a metadata cache misbehaviour on the server handside, or a local FS badly managed by FSAL_VFS (what kind of FS do you export ?).
I suggest that you run cthon04 test suite ( git clone git://fedorapeople.org/~steved/cthon04
cd cthon04 to get it), basic/test6 will probably fail but other may be too. This will provide a good image of the issue.
I also suggest that you post to nfs-ganesha-devel@lists.sourceforge.net, which is the natural way of communicating with Ganesha community.

**Comment by ACiDGRiM** [comment]
I posted there after here once I realized it might not be a bug but in implementation.

I'm exporting a mounted glusterfs volume. I know ganesha has gluster support, however my need for NFS is to a specific directory not the whole gluster volume. I'll reply to my userlist post with the cthon04 test result soon.

Oddly, the files are currently showing, so I'll continue testing.

**Comment by phdeniel** [comment]
Hum... I am not sure how GlusterFS supports open_by_handle_at() which is the core of FSAL_VFS. I think you should use FSAL_GLUSTER (you may use it and continue in exporting a subtree). I can tell more, I am not familiar with GlusterFS and its interaction with Ganesha.
Anand (from RedHat) will help you on this. Post on the devel list, he'll see your message. He is a very nice guy and will clearly reply (or another redhat people will).

**Comment by ACiDGRiM** [comment]
Thank you for the advice, I'll try a direct gluster FSAL too.
