### ISSUE TITLE
Permission denied when binary has only execute permissions and no read permission

### ISSUE THREAD

**Issue by kthommandra** [nfs-ganesha/nfs-ganesha#634]
When using NFSv4, if a binary has only execute bit and no read bits then the binary cannot be executed.
This works fine on local filesystems.
> ls -l 
total 196
---x--x--x 1 root root 199304 Sep 18 10:08 find
> ./find -h
-bash: ./find: Permission denied

NFS4 ACL :F_DBG :file Mode=0111, file uid=0, file gid= 0, user uid=10000, user gid= 10000, access_type=0X4000000            NFS4 ACL :F_DBG :Mask=0X1000000, Access Type=0X4000000 Allowed=0X0 Denied=0X4000000 DENIED

We first ran into this with the "sudo" binary.

The Linux kernel based NFS server, has a fix which allows this. IMO a similar fix is needed in FSAL. Comments?

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/833300
https://bugzilla.linux-nfs.org/show_bug.cgi?id=201

**Comment by ffilz** [comment]
Could you get a tcpdump/wireshark trace? I'm wondering exactly where the permission is failing.

Ganesha does allow open for read of execute only files, but it might not be in all the right places.

**Comment by kthommandra** [comment]
sure, will post the wireshark trace.

FYI, following "dirty" patch unblocked me.

```
diff --git a/src/FSAL/access_check.c b/src/FSAL/access_check.c
index 37891b7af..d6bea4880 100644
--- a/src/FSAL/access_check.c
+++ b/src/FSAL/access_check.c
@@ -795,6 +795,11 @@ fsal_check_access_no_acl(struct user_cred *creds,
                     (mask & access_type) == access_type ?
                        "ALLOWED" : "DENIED");
 
+       /* If mode has execute permissions then it implies read */
+       if ((mask & FSAL_X_OK) != 0) {
+               mask |= FSAL_R_OK;
+       }
+
        if (allowed != NULL)
                *allowed = mask & access_type;
 ```

**Comment by ffilz** [comment]
That change would break permission checking for the ACCESS operation, which would allow cat an execute only file.

nfs3_read.c, nfs4_op_read.c, and check_open_permission all check for execute access if open for read fails.

So the question is why aren't one of those re-checks allowing the read access?

**Comment by kthommandra** [comment]
Yes, thats why I termed it a dirty hack. In my current experiments, there is no need to worry about "cat an execute only file" so   to get unblocked I did the hack.

Using your note, I looked further and found that check_open_permission does an early exit when the test_access returns status.major == ERR_FSAL_ACCESS. 

Not sure if the check is wrong or status code is wrong. See below


```

static fsal_status_t check_open_permission(struct fsal_obj_handle *obj,
                                           fsal_openflags_t openflags,
                                           bool exclusive_create,
                                           char **reason)
{
...
        /* If non-permission error, return it. */
        if (status.major != ERR_FSAL_PERM) {
                *reason = "fsal_access failed - ";
                return status; <==== early exit here
        }
...

   status = fsal_access(obj, FSAL_EXECUTE_ACCESS);
.....
}

static fsal_status_t
fsal_check_access_no_acl(struct user_cred *creds,
                         fsal_accessflags_t access_type,
                         fsal_accessflags_t *allowed,
                         fsal_accessflags_t *denied,
                         struct attrlist *p_object_attributes)
{
....
        /* Success if mask covers all the requested bits */
        return (mask & access_type) == access_type ? fsalstat(ERR_FSAL_NO_ERROR,
                                                              0) :
            fsalstat(ERR_FSAL_ACCESS, 0);
}
```

**Comment by ffilz** [comment]
Ah, that probably should be:

if (status.major != ERR_FSAL_PERM && status.major != ERR_FSAL_ACCESS) {

It maybe even should just be checking for ERR_FSAL_ACCESS. Unfortunately there's always been some confusion between EPERM and EACCESS, there are probably other places we have the wrong one...

I see READ (v3 and v4) do check for ERR_FSAL_ACCESS.

If you could test, and if it works and you're willing, submit a patch via Gerrithub.

**Comment by ffilz** [comment]
This should be resolved with this patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/504062

**Comment by ffilz** [comment]
Closing as resolved.
