### ISSUE TITLE
When I turn on lttng, there is no trace point output

### ISSUE THREAD

**Issue by Roay** [nfs-ganesha/nfs-ganesha#635]
The environment is as follows
```
ganesha v3.3
centos7.4
ceph v14.2
lttng v2.10.7
```
Command as follow：
```
# cmake -DUSE_FSAL_RGW=ON -DUSE_LTTNG=ON -DRGW_PREFIX=/build/ ../../src/
# make && make install
# LD_PRELOAD=./libganesha_trace.so LD_PRELOAD=liblttng-ust-fork.so ./ganesha.nfsd -f /etc/ganesha/ganesha.conf
# lttng list -u
PID: 369811 - Name: ./ganesha.nfsd
      lttng_ust_tracelog:TRACE_DEBUG (loglevel: TRACE_DEBUG (14)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_LINE (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_FUNCTION (loglevel: TRACE_DEBUG_FUNCTION (12)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_UNIT (loglevel: TRACE_DEBUG_UNIT (11)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_MODULE (loglevel: TRACE_DEBUG_MODULE (10)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_PROCESS (loglevel: TRACE_DEBUG_PROCESS (9)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_PROGRAM (loglevel: TRACE_DEBUG_PROGRAM (8)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_SYSTEM (loglevel: TRACE_DEBUG_SYSTEM (7)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_INFO (loglevel: TRACE_INFO (6)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_NOTICE (loglevel: TRACE_NOTICE (5)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_WARNING (loglevel: TRACE_WARNING (4)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_ERR (loglevel: TRACE_ERR (3)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_CRIT (loglevel: TRACE_CRIT (2)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_ALERT (loglevel: TRACE_ALERT (1)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_EMERG (loglevel: TRACE_EMERG (0)) (type: tracepoint)
      lttng_ust_tracef:event (loglevel: TRACE_DEBUG (14)) (type: tracepoint)
      lttng_ust_lib:unload (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_lib:debug_link (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_lib:build_id (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_lib:load (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:end (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:debug_link (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:build_id (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:bin_info (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:start (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
```
**How to output trace points of mdcache layer, like in the FSAL_MDCACHE/mdcache_helpers.c ?** 
```
#ifdef USE_LTTNG
tracepoint(mdcache, mdc_readdir_populate,
		   __func__, __LINE__, &directory->obj_handle,
		   directory->sub_handle, whence);
#endif
```

**Comment by dang** [comment]
When I do that, I get:

`
UST events:                                                 
-------------                                                   
                                                                                                                                        
PID: 30614 - Name: /home/dang/src/ganesha/next/clean/install/bin/ganesha.nfsd                 
      fsalgl:gl_handle (loglevel: TRACE_INFO (6)) (type: tracepoint)                                  
      fsalgl:close_fd (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                     
      fsalgl:open_fd (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                      
      state:delete (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                        
      state:add (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                           
      nfs_rpc:valid (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                       
      nfs_rpc:before_recv (loglevel: TRACE_INFO (6)) (type: tracepoint)          
      nfs_rpc:before_reply (loglevel: TRACE_INFO (6)) (type: tracepoint)             
      nfs_rpc:v4op_end (loglevel: TRACE_INFO (6)) (type: tracepoint)                   
      nfs_rpc:v4op_start (loglevel: TRACE_INFO (6)) (type: tracepoint)         
      nfs_rpc:op_end (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                      
      nfs_rpc:op_start (loglevel: TRACE_INFO (6)) (type: tracepoint)               
      nfs_rpc:end (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                         
      nfs_rpc:start (loglevel: TRACE_INFO (6)) (type: tracepoint)                                                                       
      nfs4:session_unref (loglevel: TRACE_INFO (6)) (type: tracepoint)         
      nfs4:session_ref (loglevel: TRACE_INFO (6)) (type: tracepoint)               
      mdcache:mdc_lookup (loglevel: TRACE_INFO (6)) (type: tracepoint)           
      mdcache:mdc_readdir_cb (loglevel: TRACE_INFO (6)) (type: tracepoint)   
      mdcache:mdc_readdir (loglevel: TRACE_INFO (6)) (type: tracepoint)           
      mdcache:mdc_readdir_populate (loglevel: TRACE_INFO (6)) (type: tracepoint)         
      mdcache:mdc_kill_entry (loglevel: TRACE_INFO (6)) (type: tracepoint)             
      mdcache:mdc_lru_remove (loglevel: TRACE_INFO (6)) (type: tracepoint)             
      mdcache:mdc_lru_insert (loglevel: TRACE_INFO (6)) (type: tracepoint)          
      mdcache:mdc_lru_reap_chunk (loglevel: TRACE_INFO (6)) (type: tracepoint)
      mdcache:mdc_lru_get (loglevel: TRACE_INFO (6)) (type: tracepoint)
      mdcache:mdc_lru_reap (loglevel: TRACE_INFO (6)) (type: tracepoint)
      mdcache:qunlock (loglevel: TRACE_INFO (6)) (type: tracepoint)
      mdcache:qlock (loglevel: TRACE_INFO (6)) (type: tracepoint)
      mdcache:mdc_lru_unref (loglevel: TRACE_INFO (6)) (type: tracepoint)
      mdcache:mdc_lru_ref (loglevel: TRACE_INFO (6)) (type: tracepoint)
      ganesha_logger:log (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_mkdir (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_readdir (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_put_ref (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_get_ref (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_unlink (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_link (loglevel: TRACE_INFO (6)) (type: tracepoint) 
      fsalmem:mem_rename (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_alloc_state (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_create_handle (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_close (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_open (loglevel: TRACE_INFO (6)) (type: tracepoint) 
      fsalmem:mem_read (loglevel: TRACE_INFO (6)) (type: tracepoint) 
      fsalmem:mem_write (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_setattrs (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_getattrs (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_inuse (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_lookup (loglevel: TRACE_INFO (6)) (type: tracepoint)
      fsalmem:mem_free (loglevel: TRACE_INFO (6)) (type: tracepoint) 
      fsalmem:mem_alloc (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:recv_exit (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:recv_bytes (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:recv_frag (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:funcin (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:mutex (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:sendmsg (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:write_complete (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:write_blocked (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:send (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:recv (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:event (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:hook (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:rearm (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:unhook (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:destroy (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:unref (loglevel: TRACE_INFO (6)) (type: tracepoint)
      xprt:ref (loglevel: TRACE_INFO (6)) (type: tracepoint)
      rpcping:test (loglevel: TRACE_INFO (6)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG (loglevel: TRACE_DEBUG (14)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_LINE (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_FUNCTION (loglevel: TRACE_DEBUG_FUNCTION (12)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_UNIT (loglevel: TRACE_DEBUG_UNIT (11)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_MODULE (loglevel: TRACE_DEBUG_MODULE (10)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_PROCESS (loglevel: TRACE_DEBUG_PROCESS (9)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_PROGRAM (loglevel: TRACE_DEBUG_PROGRAM (8)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_DEBUG_SYSTEM (loglevel: TRACE_DEBUG_SYSTEM (7)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_INFO (loglevel: TRACE_INFO (6)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_NOTICE (loglevel: TRACE_NOTICE (5)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_WARNING (loglevel: TRACE_WARNING (4)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_ERR (loglevel: TRACE_ERR (3)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_CRIT (loglevel: TRACE_CRIT (2)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_ALERT (loglevel: TRACE_ALERT (1)) (type: tracepoint)
      lttng_ust_tracelog:TRACE_EMERG (loglevel: TRACE_EMERG (0)) (type: tracepoint)
      lttng_ust_tracef:event (loglevel: TRACE_DEBUG (14)) (type: tracepoint)
      lttng_ust_lib:unload (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_lib:debug_link (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_lib:build_id (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_lib:load (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:end (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:debug_link (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:build_id (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:bin_info (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
      lttng_ust_statedump:start (loglevel: TRACE_DEBUG_LINE (13)) (type: tracepoint)
`

I did have to run that command (and all lttng stuff) as root, but it looks like you did that.  I also to not use liblttng-ust-fork.so, instead I run Ganesha with -F to keep it in the foreground.  I don't know if that makes a difference.

**Comment by Roay** [comment]
Yeah，I got the trace point with the -F command，like：
`LD_PRELOAD=./tracing/libganesha_trace.so ./ganesha.nfsd -F -f /etc/ganesha/ganesha.conf`
