### ISSUE TITLE
GPFS issues

### ISSUE THREAD

**Issue by Phhere** [nfs-ganesha/nfs-ganesha#642]
Hello,
i am currently trying to use the latest version (next branch) but i have also an issue with V3-stable

> 26/10/2020 08:05:43 : epoch 5f967547 : hpc-storage-14k-1 : ganesha.nfsd-1687[main] fsal_internal_version :FSAL :MAJ :OPENHANDLE_GET_VERSION failed: 95
> 26/10/2020 08:05:43 : epoch 5f967547 : hpc-storage-14k-1 : ganesha.nfsd-1687[main] gpfs_create_export :FSAL :INFO :GPFS get version is 95 options 0x771F1E0 id 1

What can be the problem? GPFS is version 4.2.3.22

**Comment by malahal** [comment]
GPFS has 3 different APIs with Ganesha. #1 The original one V1, #2 Version V2 and #3 Version V3. V2 and  V3 add some additional fields in interface structures, so technically you can't use some  GPFS versions with some Ganesha versions. Generally, newer versions of Ganesha should be ok (GPFS knows Ganesha versions with this call and accesses some fields based on version with newer GPFS code).

Recently I added V3 code and started logging this error if GPFS doesn't understand V2 or V3 versions. GPFS4.2.3 assumes V1 without this call implicitly, that is why you are seeing that message. You should be ok but I want to let you know that we never tested Ganesha 2.5 and up on GPFS4.2.3.

**Comment by Phhere** [comment]
Hi, thanks for the response.
This explains why 2.3 works. Because i have strange issues with newer versions
NFS works on client for root user but not for other users. 

Most of the time it looks like this when a user tries to access a file on the nfs

> 
> 26/10/2020 00:11:50 : epoch 5f9605d9 : hpc-storage-14k-1 : ganesha.nfsd-26703[svc_14] process_one_op :NFS4 :DEBUG :Request 2: opcode 6 is OP_CREATE
> 26/10/2020 00:11:50 : epoch 5f9605d9 : hpc-storage-14k-1 : ganesha.nfsd-26703[svc_14] mdcache_mkdir :INODE :DEBUG :mkdir spoolers failed with Forbidden action
> 26/10/2020 00:11:50 : epoch 5f9605d9 : hpc-storage-14k-1 : ganesha.nfsd-26703[svc_14] complete_op :NFS4 :DEBUG :Status of OP_CREATE in position 2 = NFS4ERR_PERM, op response size is 4 total respo
> nse size is 92
> 26/10/2020 00:11:50 : epoch 5f9605d9 : hpc-storage-14k-1 : ganesha.nfsd-26703[svc_14] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_PERM lastindex = 3

a little longer example:

> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] complete_op :NFS4 :DEBUG :Status of OP_GETATTR in position 2 = NFS4_OK, op response size is 132 total response size is 220
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] free_nfs_request :DISP :DEBUG :SVC_DECODE on 0x2ba554000c00 fd 24 (::ffff:10.28.1.30:971) xid=4259557751 returned XPRT_IDLE
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] alloc_nfs_request :DISP :DEBUG :0x2ba554000c00 fd 24 context 0x2ba5540082b0
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 24585
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:10.28.1.30 for Program 100003, Version 4, Function 1 has xid=4276334967
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 6 operations, res = 0x2ba554008b60, tag = NO TAG
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_op_sequence :SESSIONS :DEBUG :SEQUENCE session=0x2ba554008f90
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] complete_op :NFS4 :DEBUG :Status of OP_SEQUENCE in position 0 = NFS4_OK, op response size is 40 total response size is 76
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] process_one_op :NFS4 :DEBUG :Request 1: opcode 22 is OP_PUTFH
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 2
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 15558
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] complete_op :NFS4 :DEBUG :Status of OP_PUTFH in position 1 = NFS4_OK, op response size is 4 total response size is 84
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] process_one_op :NFS4 :DEBUG :Request 2: opcode 18 is OP_OPEN
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_op_open :STATE :DEBUG :Entering NFS v4 OPEN handler -----------------------------
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_op_open :STATE :DEBUG :OPEN Client id = 5f96a6df00000001
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_acl_entry_inc_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x2ba57c003070, 2)
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_acl_entry_dec_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x2ba57c003070, 1)
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] mdc_lookup :NFS READDIR :DEBUG :Cache Miss detected for rehs_new
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] mdc_lookup_uncached :NFS READDIR :DEBUG :lookup rehs_new failed with No such file or directory
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_acl_entry_inc_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x2ba57c003070, 2)
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_acl_entry_dec_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x2ba57c003070, 1)
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] mdcache_open2 :INODE :DEBUG :open2 rehs_new failed with Forbidden action
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] nfs4_op_open :STATE :DEBUG :failed with status NFS4ERR_PERM
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] complete_op :NFS4 :DEBUG :Status of OP_OPEN in position 2 = NFS4ERR_PERM, op response size is 4 total response size is 92
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_PERM lastindex = 3
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_2] free_nfs_request :DISP :DEBUG :SVC_DECODE on 0x2ba554000c00 fd 24 (::ffff:10.28.1.30:971) xid=4276334967 returned XPRT_IDLE
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] alloc_nfs_request :DISP :DEBUG :0x2ba554000c00 fd 24 context 0x2ba57c0023b0
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] get_gsh_client :HT CACHE :DEBUG :client_mgr cache hit slot 24585
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] nfs_rpc_process_request :DISP :DEBUG :Request from ::ffff:10.28.1.30 for Program 100003, Version 4, Function 1 has xid=4293112183
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 5 operations, res = 0x2ba57c0014c0, tag = NO TAG
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] nfs4_op_sequence :SESSIONS :DEBUG :SEQUENCE session=0x2ba554008f90
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] complete_op :NFS4 :DEBUG :Status of OP_SEQUENCE in position 0 = NFS4_OK, op response size is 40 total response size is 76
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] process_one_op :NFS4 :DEBUG :Request 1: opcode 22 is OP_PUTFH
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] get_gsh_export :HT CACHE :DEBUG :export_mgr cache hit slot 2
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 15558
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] complete_op :NFS4 :DEBUG :Status of OP_PUTFH in position 1 = NFS4_OK, op response size is 4 total response size is 84
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] process_one_op :NFS4 :DEBUG :Request 2: opcode 15 is OP_LOOKUP
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] nfs4_op_lookup :NFS4 :DEBUG :name=rehs_new
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] nfs4_acl_entry_inc_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x2ba57c003070, 2)
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] nfs4_acl_entry_dec_ref :NFS4 ACL :DEBUG :(acl, ref) = (0x2ba57c003070, 1)
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] mdc_lookup :NFS READDIR :DEBUG :Cache Miss detected for rehs_new
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] mdc_lookup_uncached :NFS READDIR :DEBUG :lookup rehs_new failed with No such file or directory
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] complete_op :NFS4 :DEBUG :Status of OP_LOOKUP in position 2 = NFS4ERR_NOENT, op response size is 4 total response size is 92
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_NOENT lastindex = 3
> Okt 26 11:43:08 hilbert12 nfs-ganesha[30296]: [svc_14] free_nfs_request :DISP :DEBUG :SVC_DECODE on 0x2ba554000c00 fd 24 (::ffff:10.28.1.30:971) xid=4293112183 returned XPRT_IDLE
> Okt 26 11:43:09 hilbert12 nfs-ganesha[30296]: [reaper] reaper_run :CLIENT ID :DEBUG :Now checking NFS4 clients for expiration

I think it is somehow related toe the caching right ?

**Comment by malahal** [comment]
mdcache_open2() failed with EPERM, not sure why. This looks similar to commit a20fe0673, but that commit exists in V3.3-stable as well next. Can you enable COMPONENT_FSAL FULL_DEBUG see and what comes up? Maybe, COMPONENT_ALL should be even better!

**Comment by Phhere** [comment]
I will generate some logs with COMPONENT_ALL. I hope we can fix this issue

**Comment by Phhere** [comment]
Hi,
i have attached a logfile from a new build of v4
NFS-Ganesha Release = V4-dev.39
nfs-ganesha compiled on Oct 26 2020 at 11:34:31
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = 1124f97e43dfec64df5ee53b872ee192639172ca
Git Describe = V4-dev.39-0-g1124f97

first there is a request by user root to touch a file, which works
afterwards there is a request by a different user to touch a file which fails

[log_full_debug_v4.log](https://github.com/nfs-ganesha/nfs-ganesha/files/5446151/log_full_debug_v4.log)

**Comment by malahal** [comment]
mdcache_open2() has a message at the very beginning in the code, but I don't see it in your log file. I expect a log message from this line. Do you know why we didn't see this in your log file?

        LogAttrlist(COMPONENT_CACHE_INODE, NIV_FULL_DEBUG,
                    "attrs_in ", attrs_in, false);

There were couple ACL messages prior to the mdcache_open2 failure message, and not sure if that caused user requests to fail.

**Comment by Phhere** [comment]
I have generated a new logfile which includes these log lines

If you look for "test_phreh100" you find the problematic file access

[log_full_attr.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/5447644/log_full_attr.zip)

One line was also printed to console instead of logfile
27/10/2020 20:18:33 : epoch 5f987228 : hilbert12 : nfs-ganesha-18664[svc_11] fsal_internal_create :FSAL :F_DBG :OPENHANDLE_CREATE_BY_NAME returned errno=1

**Comment by malahal** [comment]
Very interesting. In the success case, GPFSFSAL_create2() calls out fsal_internal_create() to create the file and then gets the file attributes. This is seen from the log messages. In the failure case, GPFSFSAL_create2() should call fsal_internal_create() and if that calls fails, fsal_internal_create() logs a message. Since I don't see any log message from fsal_internal_create() function there in the failure case, I will have to assume that the file actually got created but something bad happened later on?? 

Even though you got failure over NFS, but do you see the actual file in the file system when you look at the file system directly? Running gdb with suitable break points should help identify the failed code path...

**Comment by Phhere** [comment]
Hello,
the file is not created on the gpfs. But i can write as normal user to the gpfs so i think the issue is in ganesha.
Do you have some instructions who i can debug it in gdb ?

**Comment by ntrishal** [comment]
@yogendra-t Pls. look into this as discussed.

**Comment by ntrishal** [comment]
@yogendra-t I am not able to assign this to you, but do take a look.

**Comment by Phhere** [comment]
Any progress?

**Comment by ffilz** [comment]
We need someone from the IBM GPFS team to take a look at this one.

**Comment by yogendra-t** [comment]
started looking into.

**Comment by Phhere** [comment]
Any update? @yogendra-t

**Comment by Phhere** [comment]
Any update? Anything i can provide? @yogendra-t @ffilz

**Comment by Phhere** [comment]
Any update? @yogendra-t 
Do you need further informations/logs?

**Comment by ffilz** [comment]
This might be better handled via IBM support channels. Note that GPFS is a proprietary filesystem and thus can not be supported by the general Ganesha community.

**Comment by ffilz** [comment]
Closing this, the Ganesha community really isn't able to support FSAL_GPFS.
