### ISSUE TITLE
"mount_path_pseudo" is not working without restart ganesha

### ISSUE THREAD

**Issue by ColinHyu** [nfs-ganesha/nfs-ganesha#647]
Hi,

This is the issue for "mount_path_pseudo"

We use "kill -HUP `pidof ganesha.nfsd` to reload config

and our config is like
```
EXPORT
{
    SecType = sys;
    Anonymous_gid = 65534;
    Pseudo = /nfs_share;
    Squash = None;
    Access_Type = RW;
    FSAL
    {
        User_Id = cluster01;
        Name = CEPH;
    }
    Anonymous_uid = 65534;
    Path = /QSGW/cluster01/nfs_share;
    Export_Id = 1001;
    Transports = UDP,TCP;
    Protocols = 3,4;
}

NFSV4
{
    Only_Numeric_Owners = true;
}

NFS_KRB5
{
    KeytabPath = /etc/krb5.keytab;
    Active_krb5 = YES;
}

NFS_CORE_PARAM
{
    mount_path_pseudo = true;
}
```
This problem only happens when we add exports and reload first time

if we restart ganesha it will works correctly

For example, we start ganesha without any export, then we add the first export "nfs_share" and reload

When reload is finish, the "showmount -e" result in nfs client is
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/QSGW/cluster01/nfs_share  (everyone)
```
if we add another new export "nfs_share2" and reload
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/QSGW/cluster01/nfs_share  (everyone)
/QSGW/cluster01/nfs_share2 (everyone)
```
but if we "restart" ganesha.nfsd the result becomes
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/nfs_share  (everyone)
/nfs_share2 (everyone)
```
then we add the third export "nfs_share3" and reload
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/nfs_share  (everyone)
/nfs_share2 (everyone)
/nfs_share3 (everyone)
```
It looks like "mount_path_pseudo" not working without restarting ganesha?

**Comment by ffilz** [comment]
Can you run with the following logging:

LOG {
    COMPONENTS {
        EXPORT = FULL_DEBUG;
    }
}

Something weird is going on. From the code, it looks like it should be working right.

What version of Ganesha?

**Comment by ColinHyu** [comment]
Hi,

Our environment is the same as https://github.com/nfs-ganesha/nfs-ganesha/issues/644

We use nfs-ganesha V4-dev.39 with FSAL_CEPH (CEPH version is 13.2.4 mimic)

We have already patched https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/505453

There are 3 logs for 3 steps one by one

1. First, add first nfs_share and reload
[log before restart.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/5514772/log.before.restart.txt)
and `showmount -e` in client is
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/QSGW/cluster01/nfs_share (everyone)
```
2. Then restart ganesha
[log restart.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/5514773/log.restart.txt)
and `showmount -e` in client is
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/nfs_share (everyone)
```
3. Add nfs_share2 and reload
[log after restart.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/5514771/log.after.restart.txt)
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/nfs_share (everyone)
/nfs_share2 (everyone)
```
Although `showmount -e` shows the full path in step 1, it can't mount full path
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/QSGW/cluster01/nfs_share (everyone)
root@NFS-CLIENT:/mnt# mount -o vers=4.0,sec=sys 10.19.60.65:/QSGW/cluster01/nfs_share /mnt/nfs_mount/ -vvv
mount.nfs: timeout set for Tue Nov 10 16:17:49 2020
mount.nfs: trying text-based options 'vers=4.0,sec=sys,addr=10.19.60.65,clientaddr=10.19.60.12'
mount.nfs: mount(2): No such file or directory
mount.nfs: mounting 10.19.60.65:/QSGW/cluster01/nfs_share failed, reason given by server: No such file or directory
```
But, pseudo path works....
```
root@NFS-CLIENT:/mnt# showmount -e 10.19.60.65
Export list for 10.19.60.65:
/QSGW/cluster01/nfs_share (everyone)
root@NFS-CLIENT:/mnt# mount -o vers=4.0,sec=sys 10.19.60.65:/nfs_share /mnt/nfs_mount/ -vvv
mount.nfs: timeout set for Tue Nov 10 16:19:55 2020
mount.nfs: trying text-based options 'vers=4.0,sec=sys,addr=10.19.60.65,clientaddr=10.19.60.12'
```

**Comment by ffilz** [comment]
Could you capture log while you do the failing showmount -e? That will help identify why it's picking the wrong path.

We may also need to add some additional debug logging to see the problem. Hopefully what's already there is enough...

**Comment by ColinHyu** [comment]
These are logs about two parts

1. add share config=> reload => client showmount (show wrong path)
[showmount before restart.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/5521516/showmount.before.restart.txt)
2. restart ganesha => client showmount (show right path)
[showmount after restart.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/5521517/showmount.after.restart.txt)

BTW, this issue also happened in my environment with nfs-ganesha-v2.8 (but no SIGHUP problem)

**Comment by ColinHyu** [comment]
Hi, 

After some tests, we find a solution to this problem

Originally, in our default config setting,
we add "include" item into /etc/ganesha/ganesha.conf only if we add new share, like
```
%include /etc/ganesha/ganesha.conf.d/nfs_share.conf
```
and every share.conf includes all setting like EXPOET、NFS_CORE_PARAM、NFSV4

which means if we have multiple confs, then some SECTIONs will be set repeatedly

So, we put some GLOBAL sections into ganesha.conf and only leave EXPORT section for share.conf

like this
```
## This is GANEHSA GLOBAL SECTION
NFSV4
{
        Only_Numeric_Owners = true;
}
NFS_KRB5
{
        KeytabPath = /etc/krb5.keytab;
        Active_krb5 = YES;
}
NFS_CORE_PARAM
{
        mount_path_pseudo = true;
}
## This include each export.conf path
%include /share/CACHEDEV1_DATA/.config/nfs/ganesha.conf.d/nfs_share.conf
```
and share.conf is
```
EXPORT
{
        Export_Id = 1001;
        Path = /QSGW/cluster01/nfs_share;
        Pseudo = /nfs_share;
        Protocols = 3,4;
        Access_Type = RW;
        Transports = UDP,TCP;
        SecType = sys;
        anonymous_uid = 65534;
        anonymous_gid = 65534;
        Squash = None;

        FSAL {
                Name = CEPH;
                User_Id = "cluster01";
        }
}
```
then we reload and showmount shows the right path...

But we not sure why....
We think this is because when we first start ganesha, ganesha.conf is empty.
and default mount_path_pseudo is false....
It looks like some config settings need to be set before starting ganesha because maybe they can not be set with SIGHUP...

**Comment by dang** [comment]
Many chunks cannot be changed during a re-config, and can only be set at startup.  I think NFS_CORE_PARAM is one of these, so that makes sense.  It was never being applied.

**Comment by dang** [comment]
@ffilz we should probably document in the man pages which chunks can be changed on reconfig.

**Comment by ffilz** [comment]
Yes, the reloadable parameters are limited to EXPORT (but not every single parameter), EXPORT_DEFAULTS, and LOG.

Further, other than EXPORT, blocks should not be duplicated. I'm actually not quite sure what the behavior is. If all duplicates have the same values things will be OK but I don't think two duplicate blocks are cumulative, so it probably takes the values from the last block loaded.

I will look at properly documenting all of this in the man pages (and I guess we should do it in the wiki too...)

**Comment by ffilz** [comment]
I have submitted a patch to update some man pages to clarify this. Additionally, I have pointed the wiki at the man pages from the next branch.
