### ISSUE TITLE
Inconsistency in mdcache entry reference count

### ISSUE THREAD

**Issue by matvore** [nfs-ganesha/nfs-ganesha#649]
I added the following assert:

```
@@ -2098,20 +2098,22 @@ _mdcache_lru_unref(mdcache_entry_t *entry, uint32_t flags, const char *func,
 
                /* we MUST recheck that refcount is still 0 */
                QLOCK(qlane);
                refcnt = atomic_fetch_int32_t(&entry->lru.refcnt);
 
                if (unlikely(refcnt > 0)) {
                        QUNLOCK(qlane);
                        goto out;
                }
 
+               assert(!entry->fh_hk.inavl);
+
                /* Really zero.  Remove entry and mark it as dead. */
                q = lru_queue_of(entry);
                if (q) {
                        /* as of now, entries leaving the cleanup queue
                         * are LRU_ENTRY_NONE */
                        LRU_DQ_SAFE(&entry->lru, q);
                }
 
                QUNLOCK(qlane);
```

And used this config:

```
NFS_CORE_PARAM {
  Plugins_Dir = /Users/matvore/ganesha_build/FSAL/FSAL_MEM;
  Bind_Addr = 127.0.0.1;
}

EXPORT {
  Export_ID=1234;
  Path = "/Users/matvore/git";
  Pseudo = "/hello_pseudo";
  Access_Type = RW;
  Disable_ACL = TRUE;
  RW_Access = TRUE;

  FSAL {
    name = MEM;
  }
}

MEM {
  Inode_Size = 1114112;
}
```

Then mounted the FSAL_MEM export and in the hello_pseudo directory, ran `echo foo >bar`. The assertion failed. Some background is in the discussion at https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/505607

**Comment by dang** [comment]
Okay, so I've tested this on Next with that patch applied, with both FSAL_MEM and FSAL_VFS, and I don't get any assert.  The way I would go about debugging this if I could reproduce would be to use LTTng to get refcount traces.  Is this something you can do?

**Comment by matvore** [comment]
Now I realize I can repro this with either a Linux or macOS server, but it requires using the macOS client. Without using the macOS native NFS client, the assert won't fail. Do you have a macOS machine?

I tried building a LTTNG-enabled binary but I'm seeing this when I try to build:

```
...
[100%] Built target fsalnull
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___recv'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___ref'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___rearm'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___recv_frag'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___destroy'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___unhook'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___send'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___write_blocked'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___mutex'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___recv_exit'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___unref'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___hook'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___recv_bytes'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___funcin'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___write_complete'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___event'
/usr/bin/ld: libntirpc/src/libntirpc.so.3.2: undefined reference to `__tracepoint_xprt___sendmsg'
collect2: error: ld returned 1 exit status
...
```

**Comment by ffilz** [comment]
Sadly we don't have easy access to a MacOS client. I wish we did, it does enough things enough differently that it would be good to regularly test with it.

Perhaps you can tease out what it's doing differently from the Linux client and maybe we can even make a pynfs test case or something, at least if it's NFS v4.

**Comment by matvore** [comment]
One option we have is that you set up a public-facing FSAL_MEM server with the assert instrumented into it, and I connect to it with my own machine to repro the problem. If you're comfortable with that, send me a personal e-mail and we can coordinate.

I am currently working on getting a non-lttng-based trace (just a backtrace of every refcnt modification) with a corresponding wireshark capture. I will share that once I have it.

**Comment by matvore** [comment]
Uploading wireshark capture log and backtrace of all refcnt modifications.

This was repro'd using a modified NFS-Ganesha at https://github.com/matvore/nfs-ganesha/tree/darwin_hacks

[repro.tar.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/5533833/repro.tar.gz)

Edit: re-uploaded verbose log. The first version of the log would have been hard to analyze since it didn't indicate what the refcnt of the object was changing to, nor the identity of the object.

**Comment by matvore** [comment]
I think what's going on is that the client does a compound operation that looks like this:

```
PUTFH, SAVEFH, OPEN, GETATTR, RESTOREFH, GETATTR
```

The PUTFH is for the containing directory, and the OPEN is a CLAIM_NULL to create the `bar` file, but the catch is that the `bar` file is already open by the same client (it seems unusual that it's doing this for a file that's already open. Maybe this is why only macOS clients repro). Once the OPEN call is complete, there should be 3 references AFAIU, but the ref count is only 2.

The 3 references to the mdcache object should be:
 a) the current file handle of the operation
 b) the open state of the file
 c) the file in the cih_ cache

**Comment by matvore** [comment]
I think I see the problem.

`open4_create_fh` implicitly reduces the reference count of the fsal_obj_handle for which it is creating a fh. So in `nfs4_op_open.c` on line 997 and 1016 an extra ref is grabbed to accomodate that. However, if the file is not being reopened (for upgraded open flags) the extra ref is not grabbed. I think the fix is as simple as:

```
diff --git a/src/Protocols/NFS/nfs4_op_open.c b/src/Protocols/NFS/nfs4_op_open.c
index 3431bfa9a..13b669bb0 100644
--- a/src/Protocols/NFS/nfs4_op_open.c
+++ b/src/Protocols/NFS/nfs4_op_open.c
@@ -1013,8 +1013,8 @@ static void open4_ex(OPEN4args *arg,
                                goto out;
                        }
-
-                       /* We need an extra reference below. */
-                       file_obj->obj_ops->get_ref(file_obj);
                }
+
+               /* We need an extra reference below. */
+               file_obj->obj_ops->get_ref(file_obj);
        }
```

This will grab the ref so it can be released by `open4_create_fh` when it is called on line 1087. What do you think?

**Comment by matvore** [comment]
Pushed patch described above to Gerrit: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/505966

**Comment by ffilz** [comment]
Closing as resolved.
