### ISSUE TITLE
mdcache_lru_release_entries crash due to op_ctx not established

### ISSUE THREAD

**Issue by jimhuaang** [nfs-ganesha/nfs-ganesha#657]
The fridgethr lru thread will invoke mdcache_lru_release_entries to  reap entries when Entries_HWMark get hit. In mdcache_lru_release_entries, the correct op_ctx could been not established,  which will fire a crash. 

Attached is a backtrace:
![crash-lru-run](https://user-images.githubusercontent.com/28775329/100198307-a05b2780-2f36-11eb-9268-c15e3f2ce21b.jpg)

**Comment by dang** [comment]
What version of Ganesha is this?

**Comment by jimhuaang** [comment]
The Ganesha version is 2.6.3, and applied with the commit  b91fe031ab1ba17181dfaf50668227b15c9eb3d5.

**Comment by ffilz** [comment]
> 
> 
> The Ganesha version is 2.6.3, and applied with the commit [b91fe03](https://github.com/nfs-ganesha/nfs-ganesha/commit/b91fe031ab1ba17181dfaf50668227b15c9eb3d5).

2.6.3 is pretty old and that commit is an enhancement in V4 that sits on top of a lot of op_ctx cleanup, both in prior releases an V4 itself. Almost certainly that enhancement is dependent on some of the other op_ctx work.

Can you move to V3.3? That patch might be more successful backported to V3.3.

**Comment by jimhuaang** [comment]
Thanks for the suggestion.

I have read the code in the main line,  mdcache_lru_release_entries probably will never touch the op_ctx even though it doesn't try to establish a correct op_ctx before call mdcache_lru_unref. 

The mentioned crash in my case got fired when reap a directory with chunks, as following:
       mdc_clean_entry->mdcache_dirent_invalidate_all->mdcache_clean_dirent_chunks-> ... -> mdcache_avl_remove->mdcache_find_keyed->mdc_check_mapping->mdc_cur_export

This commit f682cd9d4 changed these logic, mdcache_avl_remove doesn't invoke mdc_cur_export anymore. So the above crash will not happen in the main line code.

For safety, I think it's better to initialize the op_ctx in mdcache_lru_release_entries just like lru_run_lane does.

**Comment by ffilz** [comment]
Does this issue show in V2.8.4 or V3.3? We no longer support V2.6.x.

**Comment by jimhuaang** [comment]
I haven't test it, the crash is not easily to reproduced.
