### ISSUE TITLE
_9p_socket_thread :9P :CRIT :Message size too big!

### ISSUE THREAD

**Issue by toddpfaff** [nfs-ganesha/nfs-ganesha#666]
I'm running nfs-ganesha V4-dev.44 on CentOS 7.8, using FSALs PROXY_V3 and PROXY_V4.
It's working ok for the most part but my log has a bunch of these:

```
09/12/2020 07:55:55 : epoch 5fd020aa : redacted : ganesha.nfsd-2172[9p_sock_mgr#fd=35] _9p_socket_thread :9P :CRIT :Message size too big! got 66326, max = 65536
```

It doesn't seem to be related to any observed problems but I'm just curious if this is anything to be concerned about.

**Comment by martinetd** [comment]
What client are you using? if linux, could you enable debug (make sure the kernel is compiled with CONFIG_9P_DEBUG and mount with -o debug=5 (or anything as long as bits 1 and 3 are set), then check in dmesg logs for `">>> size=66326` to make sure the client tries to send that?

If it does it's a client bug, it shouldn't try to send anything bigger than msize.
If it doesn't something is screwed up and we parse as size field something that isn't (once the stream has been corrupted there's no way to "resync" properly)

Either way it's not good: the request is dropped and 9p has no replay mechanism so something will hang, or something is just plain corrupted, it'd help to take a closer look at what is going on - logs on either/both sides and/or a reproducer.

**Comment by toddpfaff** [comment]
I'm not using it intentionally from any client.  I have no idea what 
client would be triggering 9P code in my nfs-ganesha server.

Would a better idea in my case be to rebuild with something like
"-DUSE_9P=OFF" or whatever the correct -D option is?  I did not specify
USE_9P=ON so I assume that it is on by default.

**Comment by ffilz** [comment]
If you aren't using 9P definitely worth turning it off, on the other hand, it would be really nice to understand why Ganesha is getting into 9P code if you aren't using 9P...

**Comment by martinetd** [comment]
Some network scan perhaps? Something that'd connect and start transmitting anything on the accepted connection would trigger it.
In that case I agree it shouldn't cause any problem other than errors in logs sporadically, but I agree turning 9p off is probably sound.

To be fair I think 9p should be off by default given the number of known users, what do you think Frank?

**Comment by ffilz** [comment]
> Some network scan perhaps? Something that'd connect and start transmitting anything on the accepted connection would trigger it.
> In that case I agree it shouldn't cause any problem other than errors in logs sporadically, but I agree turning 9p off is probably sound.
> 
> To be fair I think 9p should be off by default given the number of known users, what do you think Frank?

Hmm, that's an interesting thought. It would be nice to know what that tool is since it could disrupt legitimate 9P use.

In the meantime, disabling 9P by default does probably make sense. Could you submit a patch for that?

**Comment by toddpfaff** [comment]
On Fri, 11 Dec 2020, Frank Filz wrote:

> Hmm, that's an interesting thought. It would be nice to know what that tool
> is since it could disrupt legitimate 9P use.

I can't say for certain who the culprit is but I know that our IT Security 
folks have used Tenable and Rumble so either of those could be responsible 
I suppose.

**Comment by ffilz** [comment]
Oh, yea, vulnerability probes make sense. And they may well push invalid data in part trying to expose a vulnerability.

And yea, given that, we should disable 9P by default. No one wants ports open that don't need to be open.

**Comment by toddpfaff** [comment]
On Fri, 11 Dec 2020, Frank Filz wrote:

> Oh, yea, vulnerability probes make sense. And they may well push invalid
> data in part trying to expose a vulnerability.

Right and, sorry, I wrote "Rumble" but that's yet another scanner for 
another purpose (although it could potentially also trigger unexpected 
behaviour I suppose).  What I meant was FireEye (yeah, they made the news 
recently).


> And yea, given that, we should disable 9P by default. No one wants ports
> open that don't need to be open.

As I'm planning to disable 9P, I decided to see what else is ON by 
default.  Since I'm only interested in FSAL_PROXY_V* at this time, I'm 
going to disable as much as I can while still getting a successful build.

grep USE_ typescript | grep ON
-- USE_GSS = ON
-- USE_FSAL_PROXY_V4 = ON
-- USE_FSAL_PROXY_V3 = ON
-- USE_FSAL_VFS = ON
-- USE_FSAL_LUSTRE = ON
-- USE_FSAL_CEPH_LL_DELEGATION =
-- USE_FSAL_CEPH_ABORT_CONN =
-- USE_FSAL_GPFS = ON
-- USE_FSAL_NULL = ON
-- USE_FSAL_MEM = ON
-- USE_DBUS = ON
-- USE_NFSIDMAP = ON
-- USE_CAPS = ON
-- USE_BLKID = ON
-- USE_GSS = ON
-- USE_9P = ON
-- _USE_9P = ON
-- USE_NFS3 = ON
-- USE_NLM = ON
-- USE_GUI_ADMIN_TOOLS = ON

**Comment by ffilz** [comment]
If you're not using NFSv3 locks, turn off NLM

I think you can turn off RQUOTA.

If you don't use DBUS, turn it off.

You obviously can turn of FSALs you don't use, but they only load if you export with one, so they won't cause vulnerabilities.

I think that covers everything that would be opening ports.

**Comment by ffilz** [comment]
I think this can be resolved by turning stuff off so closing. If there really is something where we can't turn things off to satisfy vulnerability scans, please reopen with specifics.
