### ISSUE TITLE
Unable to start up ganesha.nfsd

### ISSUE THREAD

**Issue by zhangzujian** [nfs-ganesha/nfs-ganesha#67]
Environment:
CentOS 6.4 x86_64,  Ganesha V2.2 Stable.

Build command:
cmake -DUSE_9P=OFF -DCMAKE_BUILD_TYPE=Maintainer /root/nfs-ganesha/src/

When I launched ganesha.nfsd, an error occurred:

localhost nfs-ganesha[17545]: [main] nfs_Init_svc :DISP :FATAL :Cannot get udp netconfig, cannot get an entry for udp in netconfig file. Check file /etc/netconfig...

In CentOS, there is no such file: "/etc/netconfig" .

How can I solve the problem?

**Comment by ffilz** [comment]
I’m not sure how we can resolve this.

 

Matt, do you have any ideas? Is there a different way this stuff is handled on CentOS?

 

Frank

**Comment by ffilz** [comment]
Hi,

I think this would be resolved by installing the distribution libtirpc, which, IIRC,
provides /etc/netconfig.

Matt

----- "Frank Filz" <ffilzlnx@mindspring.com> wrote:

> I’m not sure how we can resolve this.
> 
> 
> 
> Matt, do you have any ideas? Is there a different way this stuff is
> handled on CentOS?
> 
> 
> 
> Frank
> 
> 
> 
> 
> 
> 
> From: zhangzujian [mailto:notifications@github.com]
> Sent: Thursday, June 25, 2015 4:16 AM
> To: nfs-ganesha/nfs-ganesha
> Subject: [nfs-ganesha] Unable to start up ganesha.nfsd (#67)
> 
> 
> 
> Environment:
> CentOS 6.4 x86_64, Ganesha V2.2 Stable.
> 
> Build command:
> cmake -DUSE_9P=OFF -DCMAKE_BUILD_TYPE=Maintainer
> /root/nfs-ganesha/src/
> 
> When I launched ganesha.nfsd, an error occurred:
> 
> localhost nfs-ganesha[17545]: [main] nfs_Init_svc :DISP :FATAL :Cannot
> get udp netconfig, cannot get an entry for udp in netconfig file.
> Check file /etc/netconfig...
> 
> In CentOS, there is no such file: "/etc/netconfig" .
> 
> How can I solve the problem?
> 
> —
> Reply to this email directly or view it on GitHub .

-- 
Matt Benjamin
CohortFS, LLC.
315 West Huron Street, Suite 140A
Ann Arbor, Michigan 48103

http://cohortfs.com

tel.  734-761-4689734-761-4689 
fax.  734-769-8938 
cel.  734-216-5309734-216-5309

**Comment by zhangzujian** [comment]
Hi,

Thanks a lot, it works.
