### ISSUE TITLE
does nfs-ganesha support No_All_Squash?

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#670]
Hello,
No_All_Squash：The visitors will match the local users first,  and then map to anonymous users if failed. 

In support/exports.c, I found that:
static struct config_item_list squash_types[] = {
    CONFIG_LIST_TOK("Root", EXPORT_OPTION_ROOT_SQUASH),
    CONFIG_LIST_TOK("Root_Squash", EXPORT_OPTION_ROOT_SQUASH),
    CONFIG_LIST_TOK("RootSquash", EXPORT_OPTION_ROOT_SQUASH),
    CONFIG_LIST_TOK("All", EXPORT_OPTION_ALL_ANONYMOUS),
    CONFIG_LIST_TOK("All_Squash", EXPORT_OPTION_ALL_ANONYMOUS),
    CONFIG_LIST_TOK("AllSquash", EXPORT_OPTION_ALL_ANONYMOUS),
    CONFIG_LIST_TOK("All_Anonymous", EXPORT_OPTION_ALL_ANONYMOUS),
    CONFIG_LIST_TOK("AllAnonymous", EXPORT_OPTION_ALL_ANONYMOUS),
    CONFIG_LIST_TOK("No_Root_Squash", EXPORT_OPTION_ROOT),
    CONFIG_LIST_TOK("None", EXPORT_OPTION_ROOT),
    CONFIG_LIST_TOK("NoIdSquash", EXPORT_OPTION_ROOT),
    CONFIG_LIST_TOK("RootId", EXPORT_OPTION_ROOT_ID_SQUASH),
    CONFIG_LIST_TOK("Root_Id_Squash", EXPORT_OPTION_ROOT_ID_SQUASH),
    CONFIG_LIST_TOK("RootIdSquash", EXPORT_OPTION_ROOT_ID_SQUASH),
    CONFIG_LIST_EOL
};

But I test in FSAL_MEM, It seems the No_All_Squash can work.  Does nfs-ganesha support No_All_Squash?

**Comment by dang** [comment]
no_all_squash is not a ganesha option.  Where are you finding documentation about it?

**Comment by ffilz** [comment]
Yes, I was confused about your question.

Ganesha's squashing corresponds to that for knfsd.

no_squash - take all credentials as is
root_squash - replace root with anonymous uid/gid
all_squash - replace all credentials with anonymous uid/gid

**Comment by agin719** [comment]
OK, I have known. And I have other question. 
I use the No_Root_Squash. 
In Client, there is a user, whose uid is 1000, gid is 1000, username is client_user. 
In Ganesha Server, there is a user, whose uid is 1000, gid is 1000, username is server_user.
Now client_user creates a file  A.   
command ls -l , We can see: 
-rw-rw-r-- 1 nobody nobody    0 Jan  1  1970  A
But I expect is:
-rw-rw-r-- 1 client_user client_user 0 Jan  1  1970  A

And I capture the network package, I find that if there is a user in server whose uid is the same with the user in client, the nfs getattr protocol returns the username to client in stead of uid.  such as:
the server returns:
fattr4_owner:  server_user@localdomain
fattr4_owner_group: server_user@localdomain
But client can't recognize the server_user and display the nobody.
when I delete user server_user in server, It becomes:
fattr4_owner:  1000
fattr4_owner_group: 1000
And client displays correctly.

So My question is:
is this the feature of the nfs protocol? And Can I turn off this feature  in nfs-ganesha? I want to the server only return uid/gid  to the client.  
Thank you very much.

**Comment by ffilz** [comment]
You are seeing idmapper issues.

One option is you fully set up idmapper, in which case user 1000 would be the same across all hosts. I suspect you don't want that, so you need to make NFSv4 not use user and group names in communication.

The bits you need are:

In your Ganesha config, in the NFSV4 {} block, set Only_Numeric_Users = true; This will make Ganesha send the string "1000" as the user instead of "server_user@domain"

On the client you need to make sure:

cat /sys/module/nfs/parameters/nfs4_disable_idmapping

shows "Y", if not:

echo 'Y' > /sys/module/nfs/parameters/nfs4_disable_idmapping

All of that SHOULD resolve your issue.

**Comment by agin719** [comment]
Thank you very much~
According to your method, I have solved it !

**Comment by Vortexdude** [comment]
If I want to access the nfs by root as well non-root users what options need to specify in the nfs-ganesha conf file
I use nfs-ganesha over the glusterfs 

I mount the nfs in the pod and its says permission denied to create a file or modified it.

![image](https://user-images.githubusercontent.com/25547102/170183989-c92014a3-899c-413d-ae01-ade975c9f3c9.png)

**Comment by shuhaiwen** [comment]
> You are seeing idmapper issues.
> 
> One option is you fully set up idmapper, in which case user 1000 would be the same across all hosts. I suspect you don't want that, so you need to make NFSv4 not use user and group names in communication.
> 
> The bits you need are:
> 
> In your Ganesha config, in the NFSV4 {} block, set Only_Numeric_Users = true; This will make Ganesha send the string "1000" as the user instead of "server_user@domain"
> 
> On the client you need to make sure:
> 
> cat /sys/module/nfs/parameters/nfs4_disable_idmapping
> 
> shows "Y", if not:
> 
> echo 'Y' > /sys/module/nfs/parameters/nfs4_disable_idmapping
> 
> All of that SHOULD resolve your issue.

in new version, Only_Numeric_Users is no longer used . instead, use Only_Numeric_Owners = true;
