### ISSUE TITLE
v2.3.3  NFS/RDMA mount point write error 

### ISSUE THREAD

**Issue by leven-del** [nfs-ganesha/nfs-ganesha#672]
Hi,
	I mount a point use rdma protol ,ls and touch operations can be successful ,when i writing 400bytes data to a file is successful ,but write more than 1k data ,client has seized up .
	Analysis ：when wrting more than 1k data,On the nfs-ganesha server side, ibv_poll_cq() get the write request packet length is only 172 bytes,so xdr_ioq_getbytes() return false, The server does not respond to the client.
	Analyzing TCP packets,The length of the  nfs write packet sent by the client   is 230 .
	
        mount :    -o vers=3,proto=rdma,port=20049
	
        Could someone have some clues about this? Or do I need provide more information?
	
Thanks.

**Comment by dang** [comment]
Unfortunately, RDMA doesn't work right now.  It was never fully completed (nfsv3 only), and has bitrotted for many years at this point.

**Comment by ffilz** [comment]
I an closing this as wontfix since we don't remotely have any resources to work on RDMA.
