### ISSUE TITLE
RDMA support

### ISSUE THREAD

**Issue by perrynzhou** [nfs-ganesha/nfs-ganesha#674]
is rdma support for nfs-ganesha ?how to config  to support rdma for nfs-ganesha ?

**Comment by dang** [comment]
Ganehsa does not currently have RDMA support.  Some work was done on RDMA a number of years ago, but the person who was  doing the work moved on and never finished it.   We're happy to have someone work on completing it, though.

**Comment by ffilz** [comment]
Closing this, if you are interested in working on RDMA support we would welcome the effort but the community has no plans to continue working on or supporting RDMA.
