### ISSUE TITLE
Please do not use '-' (minus sign) in version numbers (Debian compliance)

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/nfs-ganesha#68]
In [Debian](http://debian.org) "`-`" (minus) character is used to separate Debian package revision number from upstream version number.
It would be helpful if you avoid using minus(es) and use only dots `.` to separate numbers in release versions (and tags).

Please read more in [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide).

Thanks.

**Comment by ffilz** [comment]
We do not use - signs in "releases", only during development. Is this still an issue? If not, can this issue be closed? I will close it next week if there is no response otherwise.
