### ISSUE TITLE
nfs-ganesha I/O performance

### ISSUE THREAD

**Issue by neelkanths** [nfs-ganesha/nfs-ganesha#681]
I'm using top-of-the trunk (next) nfs-ganesha and libntirpc in my test environment.

I have exported a local xfs file system created on an NVMe drive with the following EXPORT params and mounted it on a CentOS 7.x Client over NFS 3.0 protocol.

The client is running vdbench test with the following configuration:
- Sequentially writes 30GB file
- Random Read with 4KB as the I/O size.
- 64 client threads.

> *SD:	Storage Definitions
> sd=sd1,lun=/mnt/xfs1/testfile3-flat.vmdk,size=30G,threads=64,openflags=o_direct
> 
> *WD:	Workload Definitions
> wd=fill,sd=sd1,rdpct=0,seekpct=-1,xfersize=256k
> wd=WD_4K_100,sd=sd1,rdpct=100,seekpct=100,xfersize=4k
> 
> *RD: Run Definitions
> rd=run_4K_1001,wd=fill,iorate=max,elapsed=72000,interval=1,pause=60
> rd=run_4K_1002,wd=WD_4K_100,iorate=max,elapsed=600,interval=1,pause=10

The command latency for read operation is 0.14 ms (as reported by dbus command which dumps NFS v3 I/O stats), however client reports an average of 2.7 ms latency. 

I have measured svc_vc_reply() latency which is insignificant (in the order of 10's of us), svc_vc_recv which takes 20 us, and we have 0.3 ms network/ping latency. As you can see there is still up to additional overhead of 2.2 ms unaccounted for. I wouldn't expect 2.2 ms is spent in the kernel.

Another observation is that when the threads parameter is set to a lower value -- for example when threads=4, threads=16 is set --  the latency at the client is close to what is seen on ganesha-nfsd server.

I was wondering if anyone seen similar behavior and are there any ganesha/libntirpc config settings that I can use which helps here.

**Test Environment:**

ganesha version: next (top of the trunk) installed on a Cent OS 7.9 server with kernel 3.10.0-1160.11.1.el7.x86_64.
NFS Protocol: 3.0
FSAL : XFS file system backed by NVMe drive
Environment: VMware ESXi 6.7
ganesha nfs server : 4 vCPUs/8GB

**Export**

EXPORT
{
  Export_Id = 64 ;
  Path = "/share/flachecache/xfs1";
  Squash = None;
  Pseudo = "/share/flachecache/xfs1";
  Anonymous_Uid = -2 ;
  Anonymous_Gid = -3 ;
  Protocols = 3,4;
  Transports = "TCP" ;
  SecType = "sys";
  Filesystem_id = 192.168 ;
  MaxWrite = 524288;
  MaxRead = 262144;
  PrefWrite = 524288;
  PrefRead = 262144;
  Access_Type = RW;
  Tag = "64";
  FSAL
  {
     Name = XFS;
  }
}

**Comment by dang** [comment]
This isn't something I've seen before, but I haven't done any latency testing recently.  A couple of things you can do:
1. Run a packet capture on the network, preferably on the client machine.  This will give you an idea of the client<->client round-trip time of individual READ ops.  You'll be able to see if the latency is on the client, or between the client and the server.
2. If the latency isn't on the client, run the packet capture on the server.  This will rule out the network, somehow.  (Note, ping, being ICMP and not TCP/UDP, is sometimes treated differently by switches than normal traffic is.  Unlikely, but possible).
3. If the latency is on the server, you can enable LTTng on Ganesha.  This will give you fine-granularity, low-latency timestamps for a number of events within Ganesha, which we should be able to use to find the bottleneck.

**Comment by neelkanths** [comment]
Thanks Daniel.

Yes, I have run packet capture and I noticed majority of the latency is coming from the server

As you recommended I'll set up LTTng on Ganesha. I have the following link which discusses LTTng setup, let me know if this is current or if there is a more up-to-date documentation that you want me to refer.

https://review.gerrithub.io/plugins/gitiles/ffilz/nfs-ganesha/+/4c36324b877300bea2f74b6a6095a0cbd23805fe/src/tracing/

**Comment by dang** [comment]
That doc should be fine.

**Comment by ffilz** [comment]
You are running more client threads than the server has threads. How many threads does the client have? It looks like your using vdbench in raw disk mode. I am doing some testing with file mode and I have found that running more threads than the client CPU capacity results in trouble.

**Comment by neelkanths** [comment]
Hi Frank - I have 64 I/O threads on the server - RPC_Ioq_ThrdMax = 64 and vdbench client also uses 64 threads. Yes, the test is opening the file with O_DIRECT this is to bypass client file system cache which helps in measuring true server performance.

**Comment by neelkanths** [comment]
I was able to enable LTTng on Ganesha, but I don't see function traces for any of the libntirpc functions.

While building Ganesha with LTTng on,  I ran into an error and I worked around it by using "struct tracepoint_dlopen tracepoint_dlopen". Could that be the reason?

> /home/neelkanths/git/0127/nfs-ganesha/src/libntirpc/src/lttng/main.c:62:36: error: conflicting types for ‘tracepoint_dlopen’
>  struct lttng_ust_tracepoint_dlopen tracepoint_dlopen
>                                     ^
> In file included from /home/neelkanths/git/0127/nfs-ganesha/src/libntirpc/ntirpc/lttng/rpcping.h:40:0,
>                  from /home/neelkanths/git/0127/nfs-ganesha/src/libntirpc/src/lttng/main.c:52:
> /usr/include/lttng/tracepoint.h:233:26: note: previous declaration of ‘tracepoint_dlopen’ was here
>  struct tracepoint_dlopen tracepoint_dlopen

I have installed these packages on my CentOS 7.x build box

> lttng-tools-2.4.1-5.el7.x86_64
> lttng-tools-debuginfo-2.4.1-5.el7.x86_64
> lttng-tools-devel-2.4.1-5.el7.x86_64
> lttng-ust-2.4.1-4.el7.x86_64
> lttng-ust-debuginfo-2.4.1-4.el7.x86_64
> lttng-ust-devel-2.4.1-4.el7.x86_64

I don't see "struct lttng_ust_tracepoint_dlopen" in any of the header files in /usr/include/lttng, but https://github.com/lttng/lttng-ust/blob/master/include/lttng/tracepoint.h does have this symbol. However, it appears to be a very different version.

Do I need to build and install everything from https://github.com/lttng?

**Comment by neelkanths** [comment]
Fixed it. I'm able to get the function traces for both ganesha and libntirpc now.

**Comment by neelkanths** [comment]
I have enabled LTTng on Ganesha.

With tracing on, typically overall time it takes to process a request is 0.4 to 0.6 ms and client latency is 5 - 6 ms. Most of the latency is on the server. Event processing is taking 30 us to 70 us and NFS RPC req/response is up to 0.6 ms. 

You can access the lttng trace file at 
https://drive.google.com/file/d/1IufFfZ3vs2XVJiCAmFOgohsU4ZS9FLzh/view?usp=sharing

Could you please take a look at it.

> [14:44:**19.844845617**] (+0.000003524) cvm-esxi67a xprt:ref: { cpu_id = 3 }, { fnc = "svc_xprt_lookup", line = 201, xprt = 0x7F75940008C0, count = 7 }
> [14:44:19.844850631] (+0.000004371) cvm-esxi67a xprt:event: { cpu_id = 3 }, { fnc = "svc_rqst_epoll_event", line = 1425, xprt = 0x7F75940008C0, xp_flags = 0x19, ev_flag = 0x1 }
> [14:44:19.844879972] (+0.000016618) cvm-esxi67a xprt:recv: { cpu_id = 3 }, { fnc = "svc_rqst_xprt_task_recv", line = 1173, xprt = 0x7F75940008C0, destroyed = 0, count = 4 }
> [14:44:19.844901117] (+0.000021145) cvm-esxi67a xprt:funcin: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 677, xprt = 0x7F75940008C0 }
> [14:44:19.844921920] (+0.000020803) cvm-esxi67a xprt:recv_frag: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 765, xprt = 0x7F75940008C0, frag_len = 0x8C }
> [14:44:19.844938440] (+0.000016520) cvm-esxi67a xprt:recv_bytes: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 825, xprt = 0x7F75940008C0, frag_remain = 0x8C, bytes = 0x8C }
> [14:44:19.844953495] (+0.000015055) cvm-esxi67a xprt:rearm: { cpu_id = 3 }, { fnc = "svc_rqst_rearm_events_locked", line = 644, xprt = 0x7F75940008C0, flags = 0x1 }
> [14:44:19.844977258] (+0.000023763) cvm-esxi67a xprt:recv_exit: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 875, xprt = 0x7F75940008C0, reason = "CALLING svc_request", code = 0 }
> [14:44:19.844991904] (+0.000014646) cvm-esxi67a nfs_rpc:valid: { cpu_id = 3 }, { fnc = "nfs_rpc_valid_NFS", line = 1610, xprt = 0x7F75940008C0, prog = 100003, vers = 3, proc = 6 }
> [14:44:19.844999138] (+0.000007234) cvm-esxi67a nfs_rpc:start: { cpu_id = 3 }, { req = 0x7F756C049EA0 }
> [14:44:19.845032309] (+0.000033171) cvm-esxi67a nfs_rpc:op_start: { cpu_id = 3 }, { req = 0x7F756C049EA0, op_name = "NFS3_READ", export_id = 64 }
> [14:44:19.845041438] (+0.000001798) cvm-esxi67a mdcache:mdc_lru_ref: { cpu_id = 3 }, { function = "mdcache_find_keyed_reason", line = 989, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 4 }
> [14:44:19.845045976] (+0.000001046) cvm-esxi67a mdcache:qlock: { cpu_id = 3 }, { function = "adjust_lru", line = 466, qlane = 0x7F75D256FB20 }
> [14:44:19.845054131] (+0.000000578) cvm-esxi67a mdcache:qunlock: { cpu_id = 3 }, { function = "adjust_lru", line = 486, qlane = 0x7F75D256FB20 }
> [14:44:19.845291458] (+0.000007303) cvm-esxi67a mdcache:mdc_lru_ref: { cpu_id = 3 }, { function = "mdcache_get", line = 168, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 4 }
> [14:44:19.845297707] (+0.000000912) cvm-esxi67a mdcache:qlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2036, qlane = 0x7F75D256FB20 }
> [14:44:19.845302007] (+0.000000285) cvm-esxi67a mdcache:qunlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2043, qlane = 0x7F75D256FB20 }
> [14:44:19.845306014] (+0.000004007) cvm-esxi67a mdcache:mdc_lru_unref: { cpu_id = 3 }, { function = "mdcache_put", line = 189, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 3 }
> [14:44:19.845344714] (+0.000004014) cvm-esxi67a mdcache:qlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2036, qlane = 0x7F75D256FB20 }
> [14:44:19.845352210] (+0.000003193) cvm-esxi67a mdcache:qunlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2043, qlane = 0x7F75D256FB20 }
> [14:44:19.845359080] (+0.000006870) cvm-esxi67a mdcache:mdc_lru_unref: { cpu_id = 3 }, { function = "mdcache_put", line = 189, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 2 }
> [14:44:19.845369350] (+0.000010270) cvm-esxi67a nfs_rpc:op_end: { cpu_id = 3 }, { req = 0x7F756C049EA0 }
> [14:44:19.845380136] (+0.000008873) cvm-esxi67a nfs_rpc:before_reply: { cpu_id = 3 }, { fnc = "complete_request", line = 782, xprt = 0x7F75940008C0 }
> [14:44:19.845412085] (+0.000002853) cvm-esxi67a xprt:ref: { cpu_id = 3 }, { fnc = "svc_ioq_write_now", line = 419, xprt = 0x7F75940008C0, count = 7 }
> [14:44:19.845416387] (+0.000000000) cvm-esxi67a xprt:mutex: { cpu_id = 3 }, { fnc = "svc_ioq_write_now", line = 422, xprt = 0x7F75940008C0 }
> [14:44:19.845420585] (+0.000004198) cvm-esxi67a xprt:mutex: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 320, xprt = 0x7F75940008C0 }
> [14:44:19.845425883] (+0.000005298) cvm-esxi67a xprt:sendmsg: { cpu_id = 3 }, { fnc = "svc_ioq_flushv", line = 226, xprt = 0x7F75940008C0, remaining = 4224, frag_needed = 1, iov_count = 2 }
> [14:44:19.845470560] (+0.000004155) cvm-esxi67a xprt:mutex: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 343, xprt = 0x7F75940008C0 }
> [14:44:19.845475096] (+0.000004536) cvm-esxi67a xprt:write_complete: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 385, xprt = 0x7F75940008C0, has_blocked = 0 }
> [14:44:19.845479463] (+0.000004197) cvm-esxi67a xprt:unref: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 399, xprt = 0x7F75940008C0, count = 7 }
> [14:44:19.845490308] (+0.000007728) cvm-esxi67a nfs_rpc:end: { cpu_id = 3 }, { req = 0x7F756C049EA0 }
> [14:44:**19.845495686**] (+0.000005378) cvm-esxi67a xprt:unref: { cpu_id = 3 }, { fnc = "svc_rqst_xprt_task_recv", line = 1187, xprt = 0x7F75940008C0, count = 5 }

**Comment by dang** [comment]
I've started downloading, it'll take a bit.  However, the snippet you posted above takes a total of 0.6 ms, so it's fine, right?

**Comment by neelkanths** [comment]
I have enabled LTTng on Ganesha.

With tracing on, typically overall time it takes to process a request is 0.4 to 0.6 ms and client latency is 5 ms. Most of the latency is on the server. Event processing is taking 30 us to 70 us and NFS RPC req/response is up to 0.6 ms.

You can access the lttng trace file at 
https://drive.google.com/file/d/1IufFfZ3vs2XVJiCAmFOgohsU4ZS9FLzh/view?usp=sharing

Could you please take a look at it.

> [14:44:**19.844845617**] (+0.000003524) cvm-esxi67a xprt:ref: { cpu_id = 3 }, { fnc = "svc_xprt_lookup", line = 201, xprt = 0x7F75940008C0, count = 7 }
> [14:44:19.844850631] (+0.000004371) cvm-esxi67a xprt:event: { cpu_id = 3 }, { fnc = "svc_rqst_epoll_event", line = 1425, xprt = 0x7F75940008C0, xp_flags = 0x19, ev_flag = 0x1 }
> [14:44:19.844879972] (+0.000016618) cvm-esxi67a xprt:recv: { cpu_id = 3 }, { fnc = "svc_rqst_xprt_task_recv", line = 1173, xprt = 0x7F75940008C0, destroyed = 0, count = 4 }
> [14:44:19.844901117] (+0.000021145) cvm-esxi67a xprt:funcin: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 677, xprt = 0x7F75940008C0 }
> [14:44:19.844921920] (+0.000020803) cvm-esxi67a xprt:recv_frag: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 765, xprt = 0x7F75940008C0, frag_len = 0x8C }
> [14:44:19.844938440] (+0.000016520) cvm-esxi67a xprt:recv_bytes: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 825, xprt = 0x7F75940008C0, frag_remain = 0x8C, bytes = 0x8C }
> [14:44:19.844953495] (+0.000015055) cvm-esxi67a xprt:rearm: { cpu_id = 3 }, { fnc = "svc_rqst_rearm_events_locked", line = 644, xprt = 0x7F75940008C0, flags = 0x1 }
> [14:44:19.844977258] (+0.000023763) cvm-esxi67a xprt:recv_exit: { cpu_id = 3 }, { fnc = "svc_vc_recv", line = 875, xprt = 0x7F75940008C0, reason = "CALLING svc_request", code = 0 }
> [14:44:19.844991904] (+0.000014646) cvm-esxi67a nfs_rpc:valid: { cpu_id = 3 }, { fnc = "nfs_rpc_valid_NFS", line = 1610, xprt = 0x7F75940008C0, prog = 100003, vers = 3, proc = 6 }
> [14:44:19.844999138] (+0.000007234) cvm-esxi67a nfs_rpc:start: { cpu_id = 3 }, { req = 0x7F756C049EA0 }
> [14:44:19.845032309] (+0.000033171) cvm-esxi67a nfs_rpc:op_start: { cpu_id = 3 }, { req = 0x7F756C049EA0, op_name = "NFS3_READ", export_id = 64 }
> [14:44:19.845041438] (+0.000001798) cvm-esxi67a mdcache:mdc_lru_ref: { cpu_id = 3 }, { function = "mdcache_find_keyed_reason", line = 989, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 4 }
> [14:44:19.845045976] (+0.000001046) cvm-esxi67a mdcache:qlock: { cpu_id = 3 }, { function = "adjust_lru", line = 466, qlane = 0x7F75D256FB20 }
> [14:44:19.845054131] (+0.000000578) cvm-esxi67a mdcache:qunlock: { cpu_id = 3 }, { function = "adjust_lru", line = 486, qlane = 0x7F75D256FB20 }
> [14:44:19.845291458] (+0.000007303) cvm-esxi67a mdcache:mdc_lru_ref: { cpu_id = 3 }, { function = "mdcache_get", line = 168, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 4 }
> [14:44:19.845297707] (+0.000000912) cvm-esxi67a mdcache:qlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2036, qlane = 0x7F75D256FB20 }
> [14:44:19.845302007] (+0.000000285) cvm-esxi67a mdcache:qunlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2043, qlane = 0x7F75D256FB20 }
> [14:44:19.845306014] (+0.000004007) cvm-esxi67a mdcache:mdc_lru_unref: { cpu_id = 3 }, { function = "mdcache_put", line = 189, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 3 }
> [14:44:19.845344714] (+0.000004014) cvm-esxi67a mdcache:qlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2036, qlane = 0x7F75D256FB20 }
> [14:44:19.845352210] (+0.000003193) cvm-esxi67a mdcache:qunlock: { cpu_id = 3 }, { function = "_mdcache_lru_unref", line = 2043, qlane = 0x7F75D256FB20 }
> [14:44:19.845359080] (+0.000006870) cvm-esxi67a mdcache:mdc_lru_unref: { cpu_id = 3 }, { function = "mdcache_put", line = 189, obj_handle = 0x7F7594009308, sub_handle = 0x7F7594009170, refcnt = 2 }
> [14:44:19.845369350] (+0.000010270) cvm-esxi67a nfs_rpc:op_end: { cpu_id = 3 }, { req = 0x7F756C049EA0 }
> [14:44:19.845380136] (+0.000008873) cvm-esxi67a nfs_rpc:before_reply: { cpu_id = 3 }, { fnc = "complete_request", line = 782, xprt = 0x7F75940008C0 }
> [14:44:19.845412085] (+0.000002853) cvm-esxi67a xprt:ref: { cpu_id = 3 }, { fnc = "svc_ioq_write_now", line = 419, xprt = 0x7F75940008C0, count = 7 }
> [14:44:19.845416387] (+0.000000000) cvm-esxi67a xprt:mutex: { cpu_id = 3 }, { fnc = "svc_ioq_write_now", line = 422, xprt = 0x7F75940008C0 }
> [14:44:19.845420585] (+0.000004198) cvm-esxi67a xprt:mutex: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 320, xprt = 0x7F75940008C0 }
> [14:44:19.845425883] (+0.000005298) cvm-esxi67a xprt:sendmsg: { cpu_id = 3 }, { fnc = "svc_ioq_flushv", line = 226, xprt = 0x7F75940008C0, remaining = 4224, frag_needed = 1, iov_count = 2 }
> [14:44:19.845470560] (+0.000004155) cvm-esxi67a xprt:mutex: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 343, xprt = 0x7F75940008C0 }
> [14:44:19.845475096] (+0.000004536) cvm-esxi67a xprt:write_complete: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 385, xprt = 0x7F75940008C0, has_blocked = 0 }
> [14:44:19.845479463] (+0.000004197) cvm-esxi67a xprt:unref: { cpu_id = 3 }, { fnc = "svc_ioq_write", line = 399, xprt = 0x7F75940008C0, count = 7 }
> [14:44:19.845490308] (+0.000007728) cvm-esxi67a nfs_rpc:end: { cpu_id = 3 }, { req = 0x7F756C049EA0 }
> [14:44:**19.845495686**] (+0.000005378) cvm-esxi67a xprt:unref: { cpu_id = 3 }, { fnc = "svc_rqst_xprt_task_recv", line = 1187, xprt = 0x7F75940008C0, count = 5 }

**Comment by neelkanths** [comment]
> I've started downloading, it'll take a bit. However, the snippet you posted above takes a total of 0.6 ms, so it's fine, right?
Yes, but client sees 5 ms and most of it is server latency.

**Comment by dang** [comment]
Hmm... I believe that leaves out latency in Ganesha itself, and means the latency must be in the kernel after we've written to the socket.  @ffilz any ideas?

**Comment by ffilz** [comment]
So I'm confused about the different latencies here... What has been broken down so far as to where time is spent?

**Comment by neelkanths** [comment]
For comparison: I ran the same test in the test setup but replaced Ganesha with kernel nfs server.

IOPS: 48400
client latency: 1.320 ms

With lttng enabled, throughput dropped and latency increased significantly but even without lttng, the IOPS is ~24K and latency is 2.7 ms which is off by 50%.

**Comment by neelkanths** [comment]
@ffilz  @dang Here is the breakdown of latencies observed on the Ganesha NFS server and on the client without LTTng tracing. 

As you can see majority of the latency (up to 3ms) is coming from server while total Ganesha/ntirpc/FSAL processing is just around 0.25 ms. Remaining ~2.4 ms is lost.

**Summary:**
1. - Ganesha RPC processing 150 us (command latency as reported by dbus v3stats)
2. - libntirpc event processing is ~50us -- from epoll_wait wakeup to svc_vc_recv processing
3. - libntirpc client response processing - 20us -- svc_vc_reply->svc_ioq_write_now/flushv 
4. - Overall average server latency is up to 3 ms
5. - Average Client latency is 2.7 ms

As per @dang's recommendation I collected lttng traces which can be accessed from the link provided in one of the previous reply. Please let me know if you need any further information or have any questions.

**Details:**
1) Server latency
=============
a) Ganesha RPC Processing latency:
-----------------------------------
                dbus.Struct((dbus.UInt64(9053016064L), 
                        dbus.UInt64(9053016064L), 
                        dbus.UInt64(**2210209L**), 
                        dbus.UInt64(0L), 
                        dbus.UInt64(**332739429287L**),   => 332739429287/2210209  => 150 us
                        dbus.UInt64(0L)), signature=None),
         
b) Total Ganesha server latency for read operation (3 ms):
READ            150300   0.000098   0.028077   0.003001
FSSTAT               1   0.000790   0.000790   0.000790

2) Client IOPS/latency
================
Jan 28, 2021    interval        i/o       MB/sec   bytes   read     resp     read    write      read    write     resp  queue  cpu%  cpu%
                                              rate  1024**2     i/o          pct     time     resp     resp      max      max   stddev  depth sys+u   sys
23:06:01.008     70    **23627.0**    92.29    4096 100.00    **2.709**    2.709    0.000     9.85     0.00    0.414   64.0  18.7  15.4

**Comment by neelkanths** [comment]
Hi Daniel/Frank - Did you get a chance to look at it? Any ideas/recommendations to track the missing 2+ ms?

**Comment by ffilz** [comment]
This really needs more investigation but I'm not sure where the resources are to do it.

**Comment by ffilz** [comment]
Bump so the live issues are on the first page

**Comment by ffilz** [comment]
I'm not sure where to go on this one. There is almost assuredly performance work that could be done but we don't have the resources. I will leave this open for now, but it will likely get closed sometime in the new year if no progress is made.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.

**Comment by JYang1986** [comment]
@neelkanths 
try nfs-client mount use nconnect， need newer linux kernel version
like mount -t nfs -o vers=3,nconnect=8  11.241.202.133:/ufs /mnt/ufs_nfs/

**Comment by yuanguohuo** [comment]
> oth ganesha and libntirpc n

how did you fix it? I got the same issue.

**Comment by yuanguohuo** [comment]
> Fixed it. I'm able to get the function traces for both ganesha and libntirpc now.

/home/neelkanths/git/0127/nfs-ganesha/src/libntirpc/src/lttng/main.c:62:36: error: conflicting types for ‘tracepoint_dlopen’
struct lttng_ust_tracepoint_dlopen tracepoint_dlopen
^
In file included from /home/neelkanths/git/0127/nfs-ganesha/src/libntirpc/ntirpc/lttng/rpcping.h:40:0,
from /home/neelkanths/git/0127/nfs-ganesha/src/libntirpc/src/lttng/main.c:52:
/usr/include/lttng/tracepoint.h:233:26: note: previous declaration of ‘tracepoint_dlopen’ was here
struct tracepoint_dlopen tracepoint_dlopen

how did you fix it? I got the same issue.

**Comment by ffilz** [comment]
could you open a new issue? Commenting in very old closed issues is not helpful.

Also, please let us know in the new issue which version of Ganesha you are using

**Comment by MyPrivateAccount** [comment]
> Fixed it. I'm able to get the function traces for both ganesha and libntirpc now.

How do it? Can you tell me?

**Comment by ffilz** [comment]
Please open a new issue, continuing to post in a closed issue just adds confusion.
