### ISSUE TITLE
NFS Ganesha 3.4 fails to start 

### ISSUE THREAD

**Issue by etha7** [nfs-ganesha/nfs-ganesha#682]
I'm attempting mount a ceph 14 rgw bucket using nfs in a docker container but the command
```bash
/usr/bin/ganesha.nfsd -L /tmp/ganesha.log -N NIV_FULL_DEBUG -F
```
seems to get stuck in ```fridgethr``` where it repeats the following forever:

```c
02/02/2021 20:29:43 : epoch 6019b5fb : <my docker container> : ganesha.nfsd-14751[lk_poll] LogBlockedList :STATE :F_DBG :Blocked Lock List is empty
02/02/2021 20:29:43 : epoch 6019b5fb : <my docker container> : ganesha.nfsd-14751[lk_poll] blocked_lock_polling :RW LOCK :F_DBG :Released mutex 0x7f8f7203a020 (&blocked_locks_mutex) at /builddir/build/BUILD/nfs-ganesha-3.4/src/SAL/state_lock.c:3391
02/02/2021 20:29:43 : epoch 6019b5fb : <my docker container> : ganesha.nfsd-14751[lk_poll] fridgethr_freeze :RW LOCK :F_DBG :Acquired mutex 0x5579aa587e40 (&fr->mtx) at /builddir/build/BUILD/nfs-ganesha-3.4/src/support/fridgethr.c:363
02/02/2021 20:29:43 : epoch 6019b5fb : <my docker container> : ganesha.nfsd-14751[lk_poll] fridgethr_freeze :RW LOCK :F_DBG :Acquired mutex 0x5579aa588030 (&fe->ctx.mtx) at /builddir/build/BUILD/nfs-ganesha-3.4/src/support/fridgethr.c:403
02/02/2021 20:29:43 : epoch 6019b5fb : <my docker container> : ganesha.nfsd-14751[lk_poll] fridgethr_freeze :RW LOCK :F_DBG :Released mutex 0x5579aa587e40 (&fr->mtx) at /builddir/build/BUILD/nfs-ganesha-3.4/src/support/fridgethr.c:411
```
```
bash-4.2# cat /etc/ganesha/ganesha.conf
EXPORT
{
    Export_Id = 77;

    Path = "/";
    Pseudo = "/";

    Access_Type = RW;
    Protocols = 3,4;
    Transports = UDP,TCP;
    SecType = sys;
    Squash = No_Root_Squash;

    FSAL {
        Name = RGW;
        User_Id = testuser;
        Access_Key_Id = "<my access key>";
        Secret_Access_Key = "<my secret access key>";
    }

}

RGW {
   name = "client.< my ceph-radosgw client>";
   cluster = "ceph";
   ceph_conf = "/etc/ceph/ceph.conf";
   init_args = "";
 }

```
The startup log, with the repeating ```fridgethr``` entries removed:
[ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/5914386/ganesha.log)

**Comment by Vicente-Cheng** [comment]
I checked your log.
It looks like rgw_lookup fail then mdcache lookup path (`..`) failure.

Maybe you could check your rgw client log to see what happened?

**Comment by etha7** [comment]
> I checked your log.
> It looks like rgw_lookup fail then mdcache lookup path (`..`) failure.
> 
> Maybe you could check your rgw client log to see what happened?

What am I looking for in the rgw client logs? I can confirm that rgw is working (can CRUD objects etc).

**Comment by etha7** [comment]
setting
```
RGW {
   name = "client.admin";
   cluster = "ceph";
   ceph_conf = "/etc/ceph/ceph.conf";
   init_args = "";
 }
```
and putting the admin keyring in the default placed fixed it and nfs started working fine.

**Comment by ffilz** [comment]
Sounds like this is resolved, closing.

**Comment by Vicente-Cheng** [comment]
> > I checked your log.
> > It looks like rgw_lookup fail then mdcache lookup path (`..`) failure.
> > Maybe you could check your rgw client log to see what happened?
> 
> What am I looking for in the rgw client logs? I can confirm that rgw is working (can CRUD objects etc).

hi @etha7, sorry for the late reply.
I know you already resolve this issue.

For your information that you could setup `debug_rgw` (FSAL_RGW would call rgw_files to do the operations) to your
radosgw client section in ceph config when you need to figure out what happens with rgw.

**Comment by etha7** [comment]
Appreciate it, thank you.
