### ISSUE TITLE
Transient NFS4ERR_NOENT / Empty directory listing

### ISSUE THREAD

**Issue by danfoster** [nfs-ganesha/nfs-ganesha#683]
Hi,

I'm trying to debug an issue where performing a `READDIR` sometimes returns `NFS4ERR_NOENT` intermittently.

As you can see in the following screenshot from wireshark, I my client is always using the same FH, sometimes it returns a valid result, othertimes it return `NFS4ERR_NOENT`

![NFS4ERR_NOENT_v2](https://user-images.githubusercontent.com/4570306/107242567-062e5a00-6a24-11eb-8a30-6c76e4d490df.png)

I have `DEBUG` log level set, and see nothing when the server is returning `NFS4ERR_NOENT`. When it successfully returns a directory listing, I see the following, but I believe it's unrelated:
```
GPFSFSAL_lookup :FSAL :EVENT :Lookup of DOTDOT failed in dirinode: 5001241
```
(I can confirm inode 5001241 matches the directory I'm listing)

Ganesha is running in a container, that `bind` mounts a GPFS filesystem into the container.

I have a few questions to help me understand the problem:
 * Does ganesha always issue Persistent filehandles? Or is it possible it could be issuing  Volatile filehandles?
 * How does ganesha calculate the filehandles to issue? What sources of data does it use?

Any other hints on where to look would be appreciated.

**Comment by ffilz** [comment]
Ganesha's handles are persistent. For FSAL_GPFS they come from the kernel exportfs interface via an fcntl call (this is effectively the same as the name_to_handle_at system call, but the GPFS code predates the availability of the system call, so it accesses it via an fcntl call to the GPFS kernel module which can make the requisite exportfs kernel call, GPFS also includes an fcntl for the open_by_handle_at system call functionality).

You may want to enable limited FULL_DEBUG via the config file:

LOG {
    COMPONENTS {
        FSAL=FULL_DEBUG;
        READDIR=FULL_DEBUG;
        CACHE_INODE=FULL_DEBUG;
    }
}

That may show more of what's going on.

**Comment by danfoster** [comment]
Thanks. I'll turn up the logging even more. In the mean time I just wanted to mention something I find odd:

In the usual operation pattern, I see:
 1) LOOKUP the subdir and get the FH
 2) Perform a ACCESS against that FH
 3) Perform a GETATTR against the FH
 4) Perform a READDIR against the FH


![image](https://user-images.githubusercontent.com/4570306/107260819-73e38180-6a36-11eb-9b32-06da88edd01e.png)

the ACCESS and GETATTR operations succeed, it's only the READDIR operation that fails.

**Comment by dang** [comment]
Which version of Ganesha?  The readdir code can be quite different for different versions.

**Comment by danfoster** [comment]
Version: 2.7.5

**Comment by danfoster** [comment]
Here is the debug log of a failed READDIR.

[ganesha.filtered.log](https://github.com/nfs-ganesha/nfs-ganesha/files/5945937/ganesha.filtered.log)

**Comment by ffilz** [comment]
It looks like the readdir contained a file "7QMwM1ta7mCjbs223gHjqWon4UkfQQWh" but it wasn't in cache and lookup by name failed for it.

**Comment by danfoster** [comment]
Reading https://github.com/nfs-ganesha/nfs-ganesha/issues/256 makes it sound similar.

In my situation, I have multiple nodes running ganesha. So from a single instances perspective, there are changes being made to the filesystem from outside ganesha. Should GPFS up-calls invalidate the dirent as well as the cached file? Is there some logging I can enable to see this?

As a short-term work-around, I'm considering disabling dirent caching. What's the correct way in 2.7.5 to do this? Is it:
```
MDCACHE {
    Dir_Chunk = 0;
}
```

Also, for the opposite, with the intention of making it easier to reproduce in an isolated lab environment, what's the best method to keep dirent caching enabled but disable file caching?

**Comment by ffilz** [comment]
We can't disable the handle cache, though you could shrink it.

Yes, Dir_Chunk=0; will disable dirent caching.

**Comment by ffilz** [comment]
One option is that GPFS should force invalidate the directory if it hits something like this. A better option might be to skip the entry, but do something that will force directory invalidation sooner than later.

**Comment by dang** [comment]
GPFS does have up-calls, and you should see messages like:
inode update: rc %d reason %d update ino %
at the DEBUG level.  The invalidate call itself logs at the MID_DEBUG level, and logs like this:
inode invalidate: flags:%x update ino %

Those should be called for the removed inode and for the parent directory.

**Comment by danfoster** [comment]
I can't see the invalidate in format you suggested. I have `FULL_DEBUG` on the `FSAL` and `CACHE_INODE` components. But I do see the following that's interesting.

If I make sure a dirent is cached by listing the directory on 2 clients (each one mounting each instance of ganesha). Then I touch a file in that directory from one of the NFS servers, I see the following in the ganesha logs:

From the node that the performed the write:
```
2021-02-18 17:22:41 : epoch 00000008 : pxc_cluster1_node1 : gpfs.ganesha.nfsd-574[fsal_up_0.89] mdcache_find_keyed_reason :INODE :F_DBG :Looking for hk=821ac05b2336b938 fsal=0x7fbcc2a16540 key=0x30000a00020028000a6400015f1f02e202000002000000000007010000000000000000007e0e6e6b
2021-02-18 17:22:41 : epoch 00000008 : pxc_cluster1_node1 : gpfs.ganesha.nfsd-574[fsal_up_0.89] mdcache_find_keyed_reason :INODE :F_DBG :Found entry 0xac75b0
2021-02-18 17:22:41 : epoch 00000008 : pxc_cluster1_node1 : gpfs.ganesha.nfsd-574[fsal_up_0.89] mdc_up_update :INODE :F_DBG :Entry 0xac75b0 Clearing MDCACHE_TRUST_CONTENT, MDCACHE_DIR_POPULATED
```

From the other node:
```
2021-02-18 17:22:41 : epoch 0001000b : pxc_cluster1_node2 : gpfs.ganesha.nfsd-35120[Gen_Fridge] mdcache_find_keyed_reason :INODE :F_DBG :Looking for hk=821ac05b2336b938 fsal=0x7fee30d96540 key=0x30000a00020028000a6400015f1f02e202000002000000000007010000000000000000007e0e6e6b
2021-02-18 17:22:41 : epoch 0001000b : pxc_cluster1_node2 : gpfs.ganesha.nfsd-35120[Gen_Fridge] mdcache_find_keyed_reason :INODE :F_DBG :Found entry 0xc955b0
2021-02-18 17:22:41 : epoch 0001000b : pxc_cluster1_node2 : gpfs.ganesha.nfsd-35120[Gen_Fridge] mdcache_find_keyed_reason :INODE :F_DBG :Looking for hk=821ac05b2336b938 fsal=0x7fee30d96540 key=0x30000a00020028000a6400015f1f02e202000002000000000007010000000000000000007e0e6e6b
2021-02-18 17:22:41 : epoch 0001000b : pxc_cluster1_node2 : gpfs.ganesha.nfsd-35120[Gen_Fridge] mdcache_find_keyed_reason :INODE :F_DBG :Found entry 0xc955b0
```

So, I'm only seeing the `Clearing MDCACHE_TRUST_CONTENT, MDCACHE_DIR_POPULATED` message on one ganesha instance and not this other. Should I expect to see this message on both instances?

**Comment by dang** [comment]
I would think so, yes, but I don't know anything about the internals of GPFS itself, so I can't say for sure.  Maybe there's some setting you need to make to have notifications propagated across the cluster?  @ffilz knows a bit more about GPFS than I do.

**Comment by ffilz** [comment]
Since this is a GPFS issue and the Ganesha community really is not in a position to support FSAL_GPFS, I am closing this.
