### ISSUE TITLE
3.3 and next: cmake fails with USE_BLKIN =ON

### ISSUE THREAD

**Issue by liufeng-49** [nfs-ganesha/nfs-ganesha#684]
[root@node1 build]# cmake ../src/
-- cmake version 3.11
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected an UNKNOWN Linux machine
-- toolchain options processed
CMake Warning at cmake/maintainer_mode.cmake:45 (message):
  CMAKE_BUILD_TYPE is not set, defaulting to Debug
Call Stack (most recent call first):
  CMakeLists.txt:130 (include)

-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Outside a git repository, use saved data
-- Looking for lttng executable...
-- Found LTTng: /usr/include  
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- Looking for include file gssapi.h
-- Looking for include file gssapi.h - found
-- Looking for llapi_hsm_state_get_fd in lustreapi
-- Looking for llapi_hsm_state_get_fd in lustreapi - not found
CMake Warning at CMakeLists.txt:626 (message):
  Cannot find lustreapi.  We will only build a dummy lustre fsal.

CMake Warning at CMakeLists.txt:637 (message):
  Cannot find LizardFS client lib.  Disabling lizardfs fsal

CMake Warning at CMakeLists.txt:648 (message):
  Cannot find libkvsns.  Disabling KVSNS fsal

-- 
-- Looking for ceph_ll_lookup in cephfs
-- Looking for ceph_ll_lookup in cephfs - found
-- Looking for ceph_ll_mknod in cephfs
-- Looking for ceph_ll_mknod in cephfs - found
-- Looking for ceph_ll_setlk in cephfs
-- Looking for ceph_ll_setlk in cephfs - found
-- Looking for ceph_ll_lookup_root in cephfs
-- Looking for ceph_ll_lookup_root in cephfs - found
-- Looking for ceph_ll_delegation in cephfs
-- Looking for ceph_ll_delegation in cephfs - found
-- Looking for ceph_ll_sync_inode in cephfs
-- Looking for ceph_ll_sync_inode in cephfs - found
-- Looking for ceph_ll_fallocate in cephfs
-- Looking for ceph_ll_fallocate in cephfs - found
-- Looking for ceph_abort_conn in cephfs
-- Looking for ceph_abort_conn in cephfs - found
-- Looking for ceph_start_reclaim in cephfs
-- Looking for ceph_start_reclaim in cephfs - found
-- Looking for ceph_select_filesystem in cephfs
-- Looking for ceph_select_filesystem in cephfs - found
-- Looking for ceph_ll_register_callbacks in cephfs
-- Looking for ceph_ll_register_callbacks in cephfs - found
-- Looking for CEPH_STATX_INO
-- Looking for CEPH_STATX_INO - found
-- Found cephfs libraries: /usr/local/lib64/libcephfs.so
-- Found CEPHFS: /usr/local/include  
-- Looking for include file acl/libacl.h
-- Looking for include file acl/libacl.h - not found
-- Could not find libacl, disabling CephFS POSIX ACL
-- Could not find libacl, disabling USE_NFSACL3
-- Looking for open_by_handle in handle
-- Looking for open_by_handle in handle - found
-- Looking for include file xfs/xfs.h
-- Looking for include file xfs/xfs.h - found
-- checking for module 'glusterfs-api>=7.6.6'
--   package 'glusterfs-api>=7.6.6' not found
CMake Warning at CMakeLists.txt:725 (message):
  Cannot find GLUSTER GFAPI runtime.  Disabling GLUSTER fsal build

-- Looking for rgw_mount in rgw
-- Looking for rgw_mount in rgw - found
-- Looking for rgw_mount2 in rgw
-- Looking for rgw_mount2 in rgw - found
-- Found rgw libraries: /usr/lib64/librgw.so
-- Found RGW: /usr/local (found suitable version "1.2.0", minimum required is "1.1.7") 
-- Could NOT find JeMalloc (missing:  JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:819 (message):
  jemalloc not found, falling back to libc

-- checking for module 'dbus-1'
--   package 'dbus-1' not found
CMake Warning at CMakeLists.txt:872 (message):
  Cannot find DBUS libs.  Disabling DBUS support

CMake Warning at CMakeLists.txt:888 (message):
  libnfsidmap not found, disabling USE_NFSIDMAP

-- Looking for wbcLookupSids in wbclient
-- Looking for wbcLookupSids in wbclient - not found
-- Winbind4 client not found /lib
CMake Warning at CMakeLists.txt:915 (message):
  Samba 4 wbclient not found.  Disabling MSPAC_SUPPORT

-- Looking for rados_read_op_omap_get_vals2 in rados
-- Looking for rados_read_op_omap_get_vals2 in rados - found
-- Found rados libraries: /usr/local/lib64/librados.so
-- Found RADOS: /usr/local/include  
-- Found rados libraries: /usr/local/lib64/librados.so
-- Looking for cap_set_proc in cap
-- Looking for cap_set_proc in cap - not found
-- Could NOT find Caps (missing:  CAPS_LIBRARIES CAPS_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:1009 (message):
  Capability libraries not found.  Disabling USE_CAPS

-- Looking for include file blkid/blkid.h
-- Looking for include file blkid/blkid.h - found
-- Looking for blkid_devno_to_devname in blkid
-- Looking for blkid_devno_to_devname in blkid - found
-- Looking for include file uuid/uuid.h
-- Looking for include file uuid/uuid.h - found
-- Looking for uuid_parse in uuid
-- Looking for uuid_parse in uuid - found
-- Looking for daemon in c
-- Looking for daemon in c - found
-- OVERRIDE_INSTALL_PREFIX = 
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so;/usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file sys/epoll.h
-- Looking for include file sys/epoll.h - found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Found EPOLL: 1  
-- Found NSL: /usr/lib64/libnsl.so  
-- 
-- -------------------------------------------------------
-- TIRPC_EPOLL = TRUE
-- USE_RPC_RDMA = OFF
-- USE_GSS = ON
-- USE_PROFILE = OFF
-- USE_LTTNG_NTIRPC = OFF
-- Using ntirpc submodule
/root/yao/nfs-ganesha-next/src/libntirpc/ntirpc/
-- Looking for urcu_ref_get_unless_zero
-- Looking for urcu_ref_get_unless_zero - found
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.1") 
RGW_INCLUDE_DIR /usr/local
-- 
-- -------------------------------------------------------
-- PLATFORM = LINUX
-- ARCH = x86_64
-- VERSION = 4-dev.50
-- BUILD HOST = node1
-- -------------------------------------------------------
-- USE_FSAL_PROXY_V4 = ON
-- USE_FSAL_PROXY_V3 = DEFAULT_ON
-- USE_FSAL_VFS = ON
-- USE_FSAL_LUSTRE = ON
-- USE_FSAL_LIZARDFS = OFF
-- USE_FSAL_KVSFS = OFF
-- USE_FSAL_CEPH = ON
-- USE_FSAL_CEPH_MKNOD = ON
-- USE_FSAL_CEPH_SETLK = ON
-- USE_FSAL_CEPH_LL_LOOKUP_ROOT = ON
-- USE_FSAL_CEPH_STATX = ON
-- USE_FSAL_CEPH_LL_DELEGATION = ON
-- USE_FSAL_CEPH_LL_SYNC_INODE = ON
-- USE_FSAL_CEPH_ABORT_CONN = ON
-- USE_FSAL_CEPH_RECLAIM_RESET = ON
-- USE_FSAL_CEPH_GET_FS_CID = ON
-- USE_FSAL_RGW = ON
-- USE_FSAL_XFS = ON
-- USE_FSAL_PANFS = OFF
-- USE_FSAL_GPFS = ON
-- USE_FSAL_GLUSTER = OFF
-- USE_FSAL_NULL = ON
-- USE_FSAL_MEM = ON
-- USE_SYSTEM_NTIRPC = OFF
-- USE_DBUS = OFF
-- USE_CB_SIMULATOR = OFF
-- USE_NFSIDMAP = OFF
-- ENABLE_ERROR_INJECTION = OFF
-- ENABLE_VFS_DEBUG_ACL = OFF
-- ENABLE_RFC_ACL = OFF
-- CEPHFS_POSIX_ACL = OFF
-- USE_CAPS = OFF
-- USE_BLKID = ON
-- DISTNAME_HAS_GIT_DATA = OFF
-- _MSPAC_SUPPORT = OFF
-- USE_EFENCE = OFF
-- _NO_TCP_REGISTER = OFF
-- RPCBIND = ON
-- DEBUG_SAL = OFF
-- _VALGRIND_MEMCHECK = OFF
-- ENABLE_LOCKTRACE = OFF
-- PROXYV4_HANDLE_MAPPING = OFF
-- DEBUG_MDCACHE = OFF
-- DEBUG_SYMS = OFF
-- COVERAGE = OFF
-- ENFORCE_GCC = OFF
-- USE_GTEST = OFF
-- USE_GSS = ON
-- TIRPC_EPOLL = TRUE
-- USE_9P = ON
-- _USE_9P = ON
-- _USE_9P_RDMA = OFF
-- USE_NFS_RDMA = OFF
-- USE_NFS3 = ON
-- USE_NLM = ON
-- USE_NFSACL3 = OFF
-- USE_ACL_MAPPING = OFF
-- KRB5_PREFIX = 
-- CEPH_PREFIX = 
-- RGW_PREFIX = 
-- GLUSTER_PREFIX = /usr
-- CMAKE_PREFIX_PATH = 
-- _GIT_HEAD_COMMIT = /bin/sh: /root/yao/nfs-ganesha-next/src/cmake/githead_from_path.sh: Permission denied
-- _GIT_HEAD_COMMIT_ABBREV = /bin/sh
-- _GIT_DESCRIBE = /bin/sh: /root/yao/nfs-ganesha-next/src/cmake/gitdesc_from_path.sh: Permission denied
-- ALLOCATOR = libc
-- GOLD_LINKER = 
-- CMAKE_INSTALL_PREFIX = /usr
-- FSAL_DESTINATION = /usr/lib64/ganesha
-- USE_ADMIN_TOOLS = OFF
-- USE_GUI_ADMIN_TOOLS = ON
-- MODULES_PATH = 
-- USE_LTTNG = ON
-- USE_BLKIN = ON
-- USE_VSOCK = OFF
-- USE_TOOL_MULTILOCK = OFF
-- USE_MAN_PAGE = OFF
-- USE_RADOS_RECOV = ON
-- RADOS_URLS = ON
-- USE_CUNIT = OFF
-- SANITIZE_ADDRESS = OFF
-- Found LSB_RELEASE: /usr/bin/lsb_release  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BLKIN
    linked by target "ganesha.nfsd" in directory /root/yao/nfs-ganesha-next/src
    linked by target "sm_notify.ganesha" in directory /root/yao/nfs-ganesha-next/src
    linked by target "test_parsing" in directory /root/yao/nfs-ganesha-next/src
    linked by target "verif_syntax" in directory /root/yao/nfs-ganesha-next/src
    linked by target "ntirpc" in directory /root/yao/nfs-ganesha-next/src/libntirpc/src
    linked by target "ganesha_rados_urls" in directory /root/yao/nfs-ganesha-next/src/config_parsing
    linked by target "ganesha_rados_recov" in directory /root/yao/nfs-ganesha-next/src/SAL
    linked by target "fsalproxy_v4" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_PROXY_V4
    linked by target "fsalproxy_v3" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_PROXY_V3
    linked by target "fsalceph" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_CEPH
    linked by target "fsalrgw" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_RGW
    linked by target "fsalgpfs" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_GPFS
    linked by target "fsaldummylustre" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_VFS/vfs
    linked by target "fsalvfs" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_VFS/vfs
    linked by target "fsalxfs" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_VFS/xfs
    linked by target "fsalmem" in directory /root/yao/nfs-ganesha-next/src/FSAL/FSAL_MEM
    linked by target "ganesha_nfsd" in directory /root/yao/nfs-ganesha-next/src/MainNFSD

-- Configuring incomplete, errors occurred!
See also "/root/yao/nfs-ganesha-next/build/CMakeFiles/CMakeOutput.log".
See also "/root/yao/nfs-ganesha-next/build/CMakeFiles/CMakeError.log".

**Comment by liufeng-49** [comment]
Can anyone help me?

**Comment by dang** [comment]
I don't think anyone has tried to build with BLKN in years, and I wouldn't be surprised if it's broken.  Try using LTTng instead, it's used regularly and works well.

**Comment by ffilz** [comment]
Should we remove BLKIN support? It doesn't seem like it got traction and maybe is just bitrot at this point.

**Comment by ffilz** [comment]
Since BLKIN has really not been supported, the following patch removes it from nfs-ganesha: 

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/511665
