### ISSUE TITLE
compile error with lttng on of tag V3.3 and next

### ISSUE THREAD

**Issue by liufeng-49** [nfs-ganesha/nfs-ganesha#685]
env: 
centos8.2
lttng-ust-2.8.1-11.el8.x86_64
lttng-ust-devel-2.8.1-11.el8.x86_64
lttng-tools from https://lttng.org/files/lttng-tools/ ，lttng-tools-2.8.1.tar.bz2

error:
/usr/bin/ld: ganesha.nfsd: hidden symbol `tracepoint_dlopen_ptr' in CMakeFiles/ganesha.nfsd.dir/MainNFSD/nfs_main.c.o is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ganesha.nfsd.dir/build.make:99: ganesha.nfsd] Error 1
make[1]: *** [CMakeFiles/Makefile2:262: CMakeFiles/ganesha.nfsd.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Can anyone help me?

**Comment by dang** [comment]
I've seen this before, and it was fixed by upgrading to lttng 2.10 or later.  Can you try that?

**Comment by dang** [comment]
Oh, and what version of Ganesha?  I'm assuming next (or 3.x)

**Comment by liufeng-49** [comment]
yes, next  and  3.3

**Comment by ffilz** [comment]
Have you tried upgrading lttng?

**Comment by ffilz** [comment]
Closing this for lack or any response. With V4.0 due out soon (rc1 this week) there will be some attention on compiling and testing on more platforms. If there is an issue relevant to the platforms we generally support, it will arise and be addressed.
