### ISSUE TITLE
*blocking* nfs ganesha server crashes when accessing gluster share

### ISSUE THREAD

**Issue by ezplanet** [nfs-ganesha/nfs-ganesha#686]
OS: Ubuntu Server 20.04

When trying to access a share configured as follows:
EXPORT
{
    # Export Id (mandatory, each EXPORT must have a unique Export_Id)
    Export_Id = 70;

    # Exported path (mandatory)
    Path = "/home";

    # Pseudo Path (required for NFS v4)
    Pseudo = "/home";

    # Allow root access
    Squash = No_Root_Squash;

    # Security flavor supported
    SecType = "sys";

    # Exporting FSAL
    FSAL {
        Name = "GLUSTER";
        Hostname = localhost;
        Volume = "gv_home";
        #enable_upcall = true;
        Transports = "UDP", "TCP" ; # tcp or rdma
        Protocols = "3", "4" ;
    }

    CLIENT {
        Clients = *.ezplanet.org;
        Access_Type = RW;
    }
}

nfs ganesha crashes and stops serving further requests. A restart does not help because it will crash again, thus making this a blocking issue.

LOGS:
19/02/2021 15:11:57 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
19/02/2021 15:11:59 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[svc_9] glusterfs_lock_op2 :FSAL :CRIT :After failing a lock request, I couldn't even get the details of who owns the lock.
19/02/2021 15:12:06 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[State_Async] glusterfs_lock_op2 :FSAL :CRIT :After failing a lock request, I couldn't even get the details of who owns the lock.
19/02/2021 15:12:16 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[State_Async] glusterfs_lock_op2 :FSAL :CRIT :After failing a lock request, I couldn't even get the details of who owns the lock.
19/02/2021 15:12:26 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[State_Async] glusterfs_lock_op2 :FSAL :CRIT :After failing a lock request, I couldn't even get the details of who owns the lock.
19/02/2021 15:12:29 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[svc_8] glusterfs_close_my_fd :FSAL :CRIT :Error : close returns with Permission denied
19/02/2021 15:12:29 : epoch 602fd4e2 : gemini : ganesha.nfsd-8563[svc_5] glusterfs_lock_op2 :FSAL :CRIT :After failing a lock request, I couldn't even get the details of who owns the lock.

**Comment by dang** [comment]
So, that's not a fatal error, so it's not directly causing the crash.  Which version of Ganesha?  Can you get a backtrace from the crash?

**Comment by ezplanet** [comment]
Here are the packages installed, coming with Ubuntu Server 20.04 distribution:
nfs-ganesha-gluster/focal,now 3.0.3-0ubuntu3 amd64 [installed]
nfs-ganesha-vfs/focal,now 3.0.3-0ubuntu3 amd64 [installed]
nfs-ganesha/focal,now 3.0.3-0ubuntu3 amd64 [installed]

It may not be a fatal error, but when that happens, nfs stops responding on the server for every share, not just the one above, therefore from my end user perspective, that is pretty much fatal. At this point nfs-ganesha needs a restart, but when users access that gluster share, it crashes again. Other disk shares are OK apparently (I have been using nfs ganesha only for a few days and only so that I can share gluster fs volumes via nfs).
If you could guide me to get the backtrace I will provide it for you. But I will be reverting soon to nfs kernel server because nfs ganesha does not work.

I was hoping this might be a configuration error, but I checked and doubled checked and copied examples I found googling.

**Comment by ezplanet** [comment]
Here are more logs after trying to access the gluster share above. Following this nfs-ganesha exits:

SYSTEMCTL nfs-ganesha status:
● nfs-ganesha.service - NFS-Ganesha file server
     Loaded: loaded (/lib/systemd/system/nfs-ganesha.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Sat 2021-02-20 13:52:09 GMT; 4min 17s ago
       Docs: http://github.com/nfs-ganesha/nfs-ganesha/wiki
    Process: 48576 ExecStart=/bin/bash -c ${NUMACTL} ${NUMAOPTS} /usr/bin/ganesha.nfsd ${OPTIONS} ${EPOCH} (code=exited, status=0/S>   Main PID: 48580 (code=killed, signal=SEGV)

Feb 20 03:47:37 gemini systemd[1]: Starting NFS-Ganesha file server...
Feb 20 03:47:37 gemini systemd[1]: Started NFS-Ganesha file server.
Feb 20 13:52:09 gemini systemd[1]: nfs-ganesha.service: Main process exited, code=killed, status=11/SEGV
Feb 20 13:52:09 gemini systemd[1]: nfs-ganesha.service: Failed with result 'signal'.20/02/2021 03:49:10 : epoch 

LOG:
60308659 : gemini : ganesha.nfsd-48580[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
20/02/2021 05:52:49 : epoch 60308659 : gemini : ganesha.nfsd-48580[svc_23] rpc :TIRPC :EVENT :svc_vc_wait: 0x7f0fa40087a0 fd 44 recv errno 104 (will set dead)
20/02/2021 13:52:07 : epoch 60308659 : gemini : ganesha.nfsd-48580[svc_26] fsal_find_fd :FSAL :CRIT :Open for locking failed for access Read/Write
20/02/2021 13:52:07 : epoch 60308659 : gemini : ganesha.nfsd-48580[svc_26] glusterfs_lock_op2 :FSAL :CRIT :Unable to find fd for lock operation

**Comment by dang** [comment]
Okay, that one is a crash, for sure.  I don't use ubuntu much, but it looks like they have a backtrace collection system similar to what RHEL/Centos/Fedora uses named Apport.  See here for more info:
https://wiki.ubuntu.com/Apport

A configuration error should not be able to cause a crash (although it could cause Ganesha to exit on startup, if it's bad enough). This is more likely a bug in either Ganesha or Gluster.  The Gluster FSAL is fairly well tested, since Red Hat has a product based on it, so it's not a simple issue.

The first error you got (the TIRPC one) is ECONNRESET, so for that, the nfs client closed it's socket.  Not much we can do about that, and it's not a fatal error.

The lock errors should not result in a crash, either.  This means that, to find out what actually caused the crash, we need to see the backtrace.

**Comment by ffilz** [comment]
Could you upgrade to Ganesha V3.4? I don't see anything Gluster specific there, but it would be worth at least eliminating the possibility of an already fixed bug.

**Comment by ezplanet** [comment]
I run Ubuntu Server 20.04, I am taking upgrades from the distribution, so it depends on whether Ubuntu provides  the upgrade you suggested.

Further to my last message I noticed that the issue happened when one user was trying to access files that the user did not have permission to access. I have since deleted and re-created those files and I have not been able to reproduce the issue since. However I would not expect this or any other user condition to cause a complete ganesha nfs server crash. This means that this package isn't yet ready for production use.

My recommendation is that thorough regression-tests are implemented and run.

I have since reverted to nfs-kernel-server

**Comment by ffilz** [comment]
Latest Ubuntu packages can be downloaded here:

https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-3.0

Please try Ganesha V3.4 and see if that resolves the issue.

**Comment by pdefert** [comment]
Upgrade with launchpad fail, it's seem missing some deps  like libntirpc3 >=3.4 missining

**Comment by ffilz** [comment]
Kaleb, could you take a look at this one?

**Comment by kalebskeithley** [comment]
libntirpc-3.x packages are in the libntirpc ppa at the same location.

https://launchpad.net/~nfs-ganesha/+archive/ubuntu/libntirpc-3.0

**Comment by ffilz** [comment]
Is this still an issue or can we close it?

**Comment by ffilz** [comment]
Closing since there has been no response in more than 30 days.
