### ISSUE TITLE
using wrong protocol for IPv4 bind_addr 

### ISSUE THREAD

**Issue by 0x0203** [nfs-ganesha/nfs-ganesha#689]
**src/MainNFSD/nfs_rpc_dispatcher_thread.c** :753 - `Bind_sockets_V4(void)`

When setting up the bind_addr from `core_param.bind_addr`, it's being set into `pdatap->sinaddr_udp` instead of `pdatap->sinaddr_tcp` which will result in using the default ip address (0.0.0.0) instead of what's configured in `nfs_param.core_param.bind_addr`. 

I'm not currently set up to file a pull request, but the fix should be pretty trivial.

**Comment by 0x0203** [comment]
Here's the patch. This fixes it for when it's trying to use tcp. The udp case and the IPv6 tcp/udp cases all look correct. 

[bind_addr.patch.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/6070225/bind_addr.patch.txt)

**Comment by 0x0203** [comment]
Here's the patch. This fixes the IPv4 tcp case. The udp and IPv6 tcp/udp cases all look correct. 

[bind_addr.patch.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/6070252/bind_addr.patch.txt)

**Comment by ffilz** [comment]
Patch submitted: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/511663

**Comment by ffilz** [comment]
@0x0203 could you verify this as fixed and close the issue?

**Comment by 0x0203** [comment]
That fixed it, thank you.
