### ISSUE TITLE
GTEST cannot work

### ISSUE THREAD

**Issue by YaqiZhang-UESTC** [nfs-ganesha/nfs-ganesha#691]
hi，ganesha version is 3.5，CentOS Linux release 8.2.2004，here are the imformation about cmake ../src：
-- cmake version 3.11
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected an UNKNOWN Linux machine
-- toolchain options processed
-- Outside a git repository, use saved data
-- Looking for lttng executable...
-- Boost 1.34.0 found.
-- Found Boost components:
   filesystem;program_options
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
CMake Warning at CMakeLists.txt:598 (message):
  Cannot find lustreapi.  We will only build a dummy lustre fsal.

CMake Warning at CMakeLists.txt:609 (message):
  Cannot find LizardFS client lib.  Disabling lizardfs fsal

-- 
-- Found cephfs libraries: CEPHFS_LIBRARY-NOTFOUND
-- Could NOT find CEPHFS (missing:  CEPHFS_INCLUDE_DIR CEPHFS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:619 (message):
  Cannot find CEPH runtime.  Disabling CEPH fsal build

CMake Warning at CMakeLists.txt:642 (message):
  Cannot find XFS runtime.  Disabling XFS build

-- checking for module 'glusterfs-api>=7.6.6'
--   package 'glusterfs-api>=7.6.6' not found
CMake Warning at CMakeLists.txt:663 (message):
  Cannot find GLUSTER GFAPI runtime.  Disabling GLUSTER fsal build

-- Found rgw libraries: RGW_LIBRARY-NOTFOUND
-- Could NOT find RGW: Found unsuitable version "0.0.0", but required is at least "1.1.7" (found )
CMake Warning at CMakeLists.txt:743 (message):
  Cannot find supported RGW runtime.  Disabling RGW fsal build

-- Could NOT find JeMalloc (missing:  JEMALLOC_LIBRARY JEMALLOC_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:757 (message):
  jemalloc not found, falling back to libc

-- checking for module 'dbus-1'
--   package 'dbus-1' not found
CMake Warning at CMakeLists.txt:810 (message):
  Cannot find DBUS libs.  Disabling DBUS support

CMake Warning at CMakeLists.txt:826 (message):
  libnfsidmap not found, disabling USE_NFSIDMAP

-- Found rados libraries: RADOS_LIBRARY-NOTFOUND
-- Could NOT find RADOS (missing:  RADOS_INCLUDE_DIR RADOS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:875 (message):
  Rados libraries not found.  Disabling USE_RADOS_RECOV

-- Found rados libraries: RADOS_LIBRARY-NOTFOUND
-- Could NOT find RADOS (missing:  RADOS_INCLUDE_DIR RADOS_LIBRARY_DIR) 
CMake Warning at CMakeLists.txt:884 (message):
  Rados libraries not found.  Disabling RADOS_URLS

-- Could NOT find Caps (missing:  CAPS_LIBRARIES CAPS_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:946 (message):
  Capability libraries not found.  Disabling USE_CAPS

-- Could not find blkid library, disabling USE_BLKID
-- OVERRIDE_INSTALL_PREFIX = 
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so;/usr/lib64/libkrb5.so;/usr/lib64/libk5crypto.so;/usr/lib64/libcom_err.so;/usr/lib64/libgssapi_krb5.so
-- 
-- -------------------------------------------------------
-- TIRPC_EPOLL = TRUE
-- USE_RPC_RDMA = OFF
-- USE_GSS = ON
-- USE_PROFILE = OFF
-- USE_LTTNG_NTIRPC = OFF
-- Using ntirpc submodule
/root/zhangyq/nfs-ganesha-3.5/src/libntirpc/ntirpc/
-- 
-- -------------------------------------------------------
-- PLATFORM = LINUX
-- ARCH = x86_64
-- VERSION = 3.5
-- BUILD HOST = node2
-- -------------------------------------------------------
-- USE_FSAL_PROXY = ON
-- USE_FSAL_VFS = ON
-- USE_FSAL_LUSTRE = ON
-- USE_FSAL_LIZARDFS = OFF
-- USE_FSAL_CEPH = OFF
-- USE_FSAL_CEPH_MKNOD = 
-- USE_FSAL_CEPH_SETLK = 
-- USE_FSAL_CEPH_LL_LOOKUP_ROOT = 
-- USE_FSAL_CEPH_STATX = 
-- USE_FSAL_CEPH_LL_DELEGATION = 
-- USE_FSAL_CEPH_LL_SYNC_INODE = 
-- USE_FSAL_CEPH_ABORT_CONN = 
-- USE_FSAL_CEPH_RECLAIM_RESET = 
-- USE_FSAL_CEPH_GET_FS_CID = 
-- USE_FSAL_RGW = OFF
-- USE_FSAL_XFS = OFF
-- USE_FSAL_PANFS = OFF
-- USE_FSAL_GPFS = ON
-- USE_FSAL_GLUSTER = OFF
-- USE_FSAL_NULL = ON
-- USE_FSAL_MEM = ON
-- USE_SYSTEM_NTIRPC = OFF
-- USE_DBUS = OFF
-- USE_CB_SIMULATOR = OFF
-- USE_NFSIDMAP = OFF
-- ENABLE_ERROR_INJECTION = OFF
-- ENABLE_VFS_DEBUG_ACL = OFF
-- ENABLE_RFC_ACL = OFF
-- USE_CAPS = OFF
-- USE_BLKID = OFF
-- DISTNAME_HAS_GIT_DATA = OFF
-- _MSPAC_SUPPORT = OFF
-- USE_EFENCE = OFF
-- _NO_TCP_REGISTER = OFF
-- RPCBIND = ON
-- DEBUG_SAL = OFF
-- _VALGRIND_MEMCHECK = OFF
-- ENABLE_LOCKTRACE = OFF
-- PROXY_HANDLE_MAPPING = OFF
-- DEBUG_MDCACHE = OFF
-- DEBUG_SYMS = OFF
-- COVERAGE = OFF
-- ENFORCE_GCC = OFF
-- USE_GTEST = ON
-- USE_GSS = ON
-- TIRPC_EPOLL = TRUE
-- USE_9P = ON
-- _USE_9P = ON
-- _USE_9P_RDMA = OFF
-- USE_NFS_RDMA = OFF
-- USE_NFS3 = ON
-- USE_NLM = ON
-- USE_ACL_MAPPING = OFF
-- KRB5_PREFIX = 
-- CEPH_PREFIX = 
-- RGW_PREFIX = 
-- GLUSTER_PREFIX = /usr
-- CMAKE_PREFIX_PATH = /usr
-- _GIT_HEAD_COMMIT = NOT-GIT
-- _GIT_HEAD_COMMIT_ABBREV = NOT-GIT
-- _GIT_DESCRIBE = /root/zhangyq/nfs-ganesha-3.5/src
-- ALLOCATOR = libc
-- GOLD_LINKER = 
-- CMAKE_INSTALL_PREFIX = /usr
-- FSAL_DESTINATION = /usr/lib64/ganesha
-- USE_ADMIN_TOOLS = OFF
-- USE_GUI_ADMIN_TOOLS = ON
-- MODULES_PATH = 
-- USE_LTTNG = OFF
-- USE_BLKIN = OFF
-- USE_VSOCK = OFF
-- USE_TOOL_MULTILOCK = OFF
-- USE_MAN_PAGE = OFF
-- USE_RADOS_RECOV = OFF
-- RADOS_URLS = OFF
-- USE_CUNIT = OFF
-- SANITIZE_ADDRESS = OFF
-- Could NOT find LSB_RELEASE (missing:  LSB_RELEASE_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/zhangyq/nfs-ganesha-3.5/build

make && make install is ok,but GTEST resault is here:
[root@node2 gtest]# ./test_ci_hash_dist1 
VFS module failed to unregister[root@node2 gtest]# 
[root@node2 gtest]# 
[root@node2 gtest]# 
[root@node2 gtest]# ./test_rbt 
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from RBTLatency1
[ RUN      ] RBTLatency1.RUN1
total run time: 709941947 (lu reqs 1408565 reqs/s) 
[       OK ] RBTLatency1.RUN1 (8379 ms)
[----------] 1 test from RBTLatency1 (8379 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (8379 ms total)
[  PASSED  ] 1 test.
/etc/gaanesha/ganesha.conf:
NFS_CORE_PARAM {
    Enable_Fast_Stats = true;
    Protocols = 3,4;
    RQUOTA_PORT = 8750;
}

MDCACHE {
    Entries_HWMark = 200000;
}

EXPORT {
    Export_Id = 77;
    Path = /dir1;
    Pseudo = /dir1;
    Access_Type = RW;
    Squash = no_root_squash;
    NFS_Commit = false;
    FSAL {
	Name = VFS;
    }
}

any suggestions will be thankful.

**Comment by YaqiZhang-UESTC** [comment]
hi,i figured that out,here are the results:
[root@node2 gtest]# ./test_ci_hash_dist1 
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from CI_HASH_DIST1
[ RUN      ] CI_HASH_DIST1.INIT
[       OK ] CI_HASH_DIST1.INIT (0 ms)
[ RUN      ] CI_HASH_DIST1.CREATE_ROOT
/root/zhangyq/nfs-ganesha-3.5/src/gtest/test_ci_hash_dist1.cc:123: Failure
Expected: (test_root) != (nullptr), actual: NULL vs (nullptr)
[  FAILED  ] CI_HASH_DIST1.CREATE_ROOT (1 ms)
[----------] 2 tests from CI_HASH_DIST1 (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CI_HASH_DIST1.CREATE_ROOT

meanwhile,some tests still cannot work 

[root@node2 fsal_api]# ./test_write2_latency 
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from Write2EmptyLatencyTest
[ RUN      ] Write2EmptyLatencyTest.SIMPLE
/root/zhangyq/nfs-ganesha-3.5/src/gtest/gtest.hh:218: Failure
Expected: (a_export) != (nullptr), actual: NULL vs (nullptr)
Segmentation fault (core dumped)

any ideas?thanks

**Comment by ffilz** [comment]
gtest is unit test code, there is no assurance it works in the stable branches.

Could you try on next?

**Comment by YaqiZhang-UESTC** [comment]
the results are here on next,
[root@localhost gtest]# ./test_ci_hash_dist1 
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from CI_HASH_DIST1
[ RUN      ] CI_HASH_DIST1.INIT
/root/gtest/ganesha-next/nfs-ganesha-next/src/gtest/test_ci_hash_dist1.cc:87: Failure
Expected: (a_export) != (nullptr), actual: NULL vs (nullptr)
[  FAILED  ] CI_HASH_DIST1.INIT (0 ms)
[ RUN      ] CI_HASH_DIST1.CREATE_ROOT
Segmentation fault (core dumped)
[root@localhost gtest]# ./test_rbt 
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from RBTLatency1
[ RUN      ] RBTLatency1.RUN1
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in SetUp().
[  FAILED  ] RBTLatency1.RUN1 (0 ms)
[----------] 1 test from RBTLatency1 (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RBTLatency1.RUN1

 1 FAILED TEST
[root@localhost gtest]# ./fsal_api/test_write2_latency 
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from Write2EmptyLatencyTest
[ RUN      ] Write2EmptyLatencyTest.SIMPLE
/root/gtest/ganesha-next/nfs-ganesha-next/src/gtest/gtest.hh:218: Failure
Expected: (a_export) != (nullptr), actual: NULL vs (nullptr)
Segmentation fault (core dumped)

**Comment by ffilz** [comment]
Daniel, could you take a look at this one?

**Comment by dang** [comment]
Tests run fine for me with FSAL_MEM, but not FSAL_VFS.  Since they were designed to run with FSAL_MEM, and never tested with any other FSAL, I think this is okay for now.
