### ISSUE TITLE
(feature?) is it possible to export an file that contains an filesystem?

### ISSUE THREAD

**Issue by f1-outsourcing** [nfs-ganesha/nfs-ganesha#692]
Export something like:

```
dd if=/dev/zero of=test-nfs-export.img bs=1M count=100
mkfs.xfs test-nfs-export.img
```

with
```
EXPORT {
        Export_Id = 2;
        Path = /mnt/test/test-nfs-export.img;
        Pseudo = /test;
        Protocols = 4;
        FSAL { Name = VFS; }
        Disable_ACL = FALSE;
        CLIENT { Clients = 192.168.122.22;  Access_type = "Rw"; }
        CLIENT { Clients = *; Access_Type = NONE; }
}
```

**Comment by dang** [comment]
No.  You would have to loop-mount the image, and then export the mountpoint.

**Comment by f1-outsourcing** [comment]
> 
> 
> No. You would have to loop-mount the image, and then export the mountpoint.

I did that, and got some issues with stalls, unable to unmount etc. That is why I thought maybe it is safer to have ganesha access the file directly

**Comment by ffilz** [comment]
Ganesha has no way to export a file as a filesystem. I suppose it could export the directory containing the file and the client could mount the filesystem but I would not trust NFS to properly handle all the block I/O for filesystem operations, though you might get away with it if only a single client was mounting the filesystem.

**Comment by dang** [comment]
RBD would be a much better solution if you want to export a file and mount it on the client.

**Comment by ffilz** [comment]
This is best resolved by resolving the issue with loop mounting. In order for Ganesha to expose the filesystem in a file to export it would have to implement the whole filesystem. Closing as wontfix.
