### ISSUE TITLE
Multiple ganesha instances and strays objects in CephFS

### ISSUE THREAD

**Issue by FATruden** [nfs-ganesha/nfs-ganesha#693]
Hi!

We have one CephFS and two standalone ganesha instances on different hosts which export the same directory.
We don't use any HA solution for ganesha and we don't need any HA.
Our nfs-clients are centos 7.5. Clients can mount any of our ganesha servers (DNS round-robin). Clients can't work with same file in same time. Clients don't overwrite files and we can't have any race. Everything works fine, but we have problem with file removing.

Problem:
```
mount nfs-server1
create file1
umount nfs-server1
---
mount nfs-server2
rm -rf file1
umount nfs-server2
```

After this we can't see file1 in directory any more.
But, on active Ceph MDS we can see increased **strays** count:
```
ceph daemon mds.c perf dump | grep num_strays
        "num_strays": 1,
        "num_strays_delayed": 0,
        "num_strays_enqueuing": 0,
```

Usual stray objects are purged after 10-20 secs. But not in this case. In this case stray object will be purget **only after** restart nfs-server1!

I can't see this behavior when i use two different native CephFS clients. It reproduced 100% only on ganesha instances.

I have seen this behavior on Ceph 12.2.12 and ganesha 2.7.1.
And i can see this behavior on Ceph 14.2.15 and ganesha 2.8.1.

ganesha.conf:
```
NFS_CORE_PARAM {
    Enable_NLM = false;
    Enable_RQUOTA = false;
    Protocols = 4;
    NFS_Port = 2049;
    MaxRPCSendBufferSize = 9437184;
    MaxRPCRecvBufferSize = 9437184;
}

NFSv4 {
    Minor_Versions =  0,1,2;
    Grace_Period = 10;
    Lease_Lifetime = 10;
}

CACHEINODE {
    Dir_Chunk = 0;
    Dir_Max = 1;
    NParts = 1;
    Cache_FDs = false;
    Cache_Size = 1;
}

EXPORT_DEFAULTS {
    Access_Type = RW;
    Attr_Expiration_Time = 0;
    Transports = TCP;
}

EXPORT {
    Export_ID=100;
    Path = /nfs;
    Pseudo = /;
    Squash = Root_Squash;

    FSAL {
        Name = CEPH;
        User_Id = ngw.b;
        Secret_Access_Key = "key";
    }
}

LOG {
    Components {
        ALL = INFO;
    }
}
```

mount params:
`mount -t nfs -o "lookupcache=positive,vers=4.1,soft,timeo=250,retrans=2" nfs-server:/ /mnt`

**Comment by dang** [comment]
Hmm...  With NFSv4, it's unlikely to be Ganesha holding an FD open (which might be the case with NFSv3).  It's possible it's somehow the libcephfs cache holding a ref on the object?  @jtlayton any ideas?

**Comment by jtlayton** [comment]
Neither of those ganesha versions have the work that we did to add the ino_release_cb, so it may just be the handle cache holding onto inode references...or any of a number of other potential bugs. @FATruden: you may want to try a newer release of ganesha, and possibly of libcephfs.

**Comment by FATruden** [comment]
@jtlayton: do you speak about versions which included this commit https://github.com/nfs-ganesha/nfs-ganesha/commit/382966c1ce0298347d26a3d22a7c8988fdcdf1da ?
As i understand it started from v4 which isn't stable today.

**Comment by FATruden** [comment]
@jtlayton Do we need this https://tracker.ceph.com/issues/12334 from ceph part?

**Comment by ffilz** [comment]
Ganesha V2.7 is definitely no longer supported, V2.8 is basically end of life. Could you try V3.5?

**Comment by FATruden** [comment]
@ffilz I will try to build v3.5.

**Comment by FATruden** [comment]
I have tryed v3.5.
```
/usr/bin/ganesha.nfsd -v
NFS-Ganesha Release = V3.5
```

I used build https://cbs.centos.org/koji/buildinfo?buildID=31933 which was made with my version of libcephfs (14.2.16).

The problem is still here.
Stray objects will be purget only after restart ganesha instance (v3.5) which was used for file creating.

**Comment by ffilz** [comment]
We will be releasing Ganesha V4.0 soon with rc1 this week. Is this still an issue? Can we try V4-dev?

**Comment by jtlayton** [comment]
> @jtlayton: do you speak about versions which included this commit [382966c](https://github.com/nfs-ganesha/nfs-ganesha/commit/382966c1ce0298347d26a3d22a7c8988fdcdf1da) ? As i understand it started from v4 which isn't stable today.

Yeah, I think you want that commit, and you'll also need a new enough libcephfs to support it. That should allow the normal mds cap/inode culling mechanisms to work.

On a related note, I wonder too if ganesha ought to attempt to more aggressively release handles that have been unlinked but that aren't open. Basically make it do what mdc_up_try_release does after those calls complete?

**Comment by ffilz** [comment]
OK, it sort of sounds like this needs to be checked on V4-rc1 (or later) and a recent libcephfs. I'm going to mark this as needs verification since we believe a fix is in V4.

**Comment by FATruden** [comment]
Hi,

> Is this still an issue?

Yes, but we use workaround like periodic restart all nfs-ganesha instances to release used space.

> Can we try V4-dev?

Yes, i can. But it will take some time.
