### ISSUE TITLE
Ownership is changed to nobody on restart.

### ISSUE THREAD

**Issue by darkl0rd** [nfs-ganesha/nfs-ganesha#695]
I just noticed that after the last update (3.5-ubuntu1~bionic1) all my files are reset to 'nobody:nogroup' upon restart of the daemon. The export is set with Squash = None;

I can change the ownership back to the correct uid:gid, but after a restart of the daemon everything is reset to nobody:nogroup again. The client seems relevant in this case, as I can see the ownership change only on the client. On the server the files are always owned by 101:102. 

As far as I know, the "previous" package did not have this problem (I've been running nfs-ganesha for some time without ever running into this issue).

**Comment by darkl0rd** [comment]
Worth noting, when the ownership is reset after a restart of 'ganesha-nfs', attempting to perform a chown on a client results in:

chown 101:102 directory-name
chown: changing ownership of 'directory-name': Operation not permitted

When listing the directory afterwards, you will notice that -all- files (not just the single file on which I attempted a chown!) and directories are (slowly) returning to the previously set correct ownership (101:102).

I hope someone can shed some light on this, currently my production NFS servers are affected and at this point I am unable to come up with a workaround.

**Comment by darkl0rd** [comment]
Server (post-restart):
```
$ ls -lan
drwxr-xr-x  7 101 102   98 Mar  8  2020 postgres
-rw-------  1 101 102    4 Mar 15 12:00 .postgres-archive-wal.lock
-rw-------  1 101 102    5 Mar 15 08:02 .postgres-backup.lock
-rw-------  1 101 102    4 Mar 15 12:00 .postgres-cron.lock
-rw-------  1 101 102    3 Mar 15 11:52 .postgres-receive-wal.lock
-rw-------  1 101 102    3 Mar 15 11:56 .postgres-xlogdb.lock
drwxr-xr-x  2 101 102  102 Mar 14 22:13 .ssh
```
Client (post-restart):
```
$ ls -lan
drwxr-xr-x  7 65534 4294967294   98 Mar  8  2020 postgres
-rw-------  1 65534 4294967294    4 Mar 15 12:00 .postgres-archive-wal.lock
-rw-------  1 65534 4294967294    5 Mar 15 08:02 .postgres-backup.lock
-rw-------  1 65534 4294967294    4 Mar 15 12:00 .postgres-cron.lock
-rw-------  1 65534 4294967294    3 Mar 15 11:52 .postgres-receive-wal.lock
-rw-------  1 65534 4294967294    3 Mar 15 11:56 .postgres-xlogdb.lock
drwxr-xr-x  2 65534 4294967294  102 Mar 14 22:13 .ssh
```
```
$ sudo chown 101:102 .ssh
$ ls -lan
drwxr-xr-x  7 101 102   98 Mar  8  2020 postgres
-rw-------  1 101 102    4 Mar 15 12:00 .postgres-archive-wal.lock
-rw-------  1 101 102    5 Mar 15 08:02 .postgres-backup.lock
-rw-------  1 101 102    4 Mar 15 12:00 .postgres-cron.lock
-rw-------  1 101 102    3 Mar 15 11:52 .postgres-receive-wal.lock
-rw-------  1 101 102    3 Mar 15 11:56 .postgres-xlogdb.lock
drwxr-xr-x  2 101 102  102 Mar 14 22:13 .ssh
```

mount options:
```
rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=yy.yy.yy.yy,local_lock=none,addr=xx.xx.xx.xx
```

**Comment by darkl0rd** [comment]
The workaround I have discovered is switching to NFS v3 which does not show this behaviour.

**Comment by ffilz** [comment]
NFSv4 uses ID mapping. The owner and group attributes are normally domain qualified owner names in string form. The client and server must both have idmapper properly configured with the same domain in /etc/idmap.conf

The protocol does allow these strings to hold numeric ids, and Ganesha defaults to allowing such numeric ID strings on SETATTR (and creates) and at least the Linux client (and probably others) default to sending such numeric ID strings, however Ganesha does not default to sending such numeric ID strings on GETATTR and READDIR. There is an option in the NFSv4 config block in Ganesha's config file to enable this behavior which should allow operation without idmapper configured:

NFSV4 { Only_Numeric_Owners = true; }

**Comment by darkl0rd** [comment]
I understand, how does it explain the "lazy correction" of ID's as soon as I attempt to perform a chown? And why didn't I ever see this before with Ganesha 3.4?

**Comment by darkl0rd** [comment]
I can confirm that by settings this option, it does indeed work as intended. I'd still be curious to get an answer on the 'chown' behaviour though.

**Comment by ffilz** [comment]
It may be an artifact of client side caching. There must be some other reason for the change in behavior since the difference between V3.4 and V3.5 is a single patch that deals with RGW version check...

A tcpdump would probably shed light on the flow that led to the chown failing. If you wanted to share a tcpdump, I would take a look at it. tcpdump -s0 -w /tmp/trace.nfs

**Comment by ffilz** [comment]
Is this still an issue? If so, please post a wireshark trace to help debug the issue.

**Comment by darkl0rd** [comment]
I'm satisfied with the solution you provided (using numeric id's). If you would like to get to the bottom of this, I can reproduce and provide a dump - let me know, otherwise feel free to close.

**Comment by ffilz** [comment]
If you can re-create and provide a tcpdump, I would be interested in understanding what is going on, if only to document it if it's something expected.
