### ISSUE TITLE
Several DIR issues using ganesha v2.7.6 

### ISSUE THREAD

**Issue by dspisla** [nfs-ganesha/nfs-ganesha#697]
Dear ganesha community,
at the moment we are struggling with several DIR issues that arises on a system with 
nfs-ganesha v2.7.6
glusterfs 5.11

Client is CentOS7 using this nfs mount options:
<server-ip>:/aif_audit /AIF/aif_audit nfs   rw,hard,sync,intr,nodev,nosuid,nfsvers=3  0 0

The issues are the follows when mounting the share on the client:
1. Sometimes deleting an empty directory failes. E.g. rm -rf <some-empty-folder> results in a "Not such file or directory" but listing shows that the folder exists

2. Rsync fails after a while and throws the error:
`rsync: recv_generator: mkdir "/AIF/aif_audit/AuditData/2021-01-TEST3/2021-01/test09/345467" failed: No such file or directory (2)`

The rsync command is as follows:
rsync -a -v --progress --inplace <Source> <Destination>

Destination is the path to the mount point on the client.

3. After rsync fails there are some strange effects when listing the destination dir tree e.g. an simple "ls" shows that some subfolders exists multiple times and there is an error message: 
`ls: reading directory .: Too many levels of symbolic links`

4. /var/log/messages from the client shows the following entries:
`Mar 16 11:04:40 hn02 kernel: NFS: directory 2021-01/test09 contains a readdir loop.Please contact your server vendor.  The file: 4526362 has duplicate cookie 180`
The folder "4526362" is one of the folders which appears multiple times in a dir listing, see item 3.

At all I don't know if there is any relationship between this issues. But searching for the error message in item 4 leads me to this bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1701016

**Do you think there is maybe a relationsship between Dir_Chunk enabled and the above issues?** 

We never set this parameter explicitly in the past. So we are using the default value 128:
`Dir_Chunk(uint32, range 0 to UINT32_MAX, default 128)`

Regards
David

**Comment by dang** [comment]
There have been quite a few readdir fixes since 2.7.x, which is no longer supported.  Please try a newer version.  I'd recommend 3.5, although 2.8.4 should have all the fixes as well.  However, we're unlikely to release another 2.8.x, so 3.x is a better version to switch to.

**Comment by dspisla** [comment]
Thank you for the quick response. We are currently working on a migration to a newer version.
Until that, do you think that setting that Dir_Chunk to 0 might be a temp workaround ???

**Comment by dang** [comment]
It likely would, but that turns off readdir caching entirely, causing every dirent to call into the FSAL, so it's likely to be slow.

**Comment by dspisla** [comment]
Thank you. Good to know

**Comment by dspisla** [comment]
Above you recommend to update to a newer ganesha version. You know if ganesha 2.8.x and (even better) 3.x is compatible with GlusterFS v5.11?

Updating GlusterFS would be not an shortterm option for us

**Comment by ffilz** [comment]
Kaleb, could you answer this question? Hmm, should we have a general support matrix on the wiki?

**Comment by dspisla** [comment]
@kalebskeithley  answered in the gluster slack channel as follows:

> AFAICT ganesha-2.8 will work with glusterfs-5. The easy way to tell is try to compile it with glusterfs-5. ganesha-3 requires at least glusterfs-6.4. (needs glfs_h_creat_open() in gfapi)  FWIW, I don't think skoduri is on slack and I don't know think Sowmya is her.

**Comment by dspisla** [comment]
Just for clarification.
Ganesha 2.8.4 needs at least Gluster 6.0 . @kalebskeithley corrected his statement from above

**Comment by ffilz** [comment]
Closing as resolved

**Comment by dspisla** [comment]
Hello Ganesha Community, its me again.
One more question to this issue:

> There have been quite a few readdir fixes since 2.7.x, which is no longer supported. Please try a newer version. I'd recommend 3.5, although 2.8.4 should have all the fixes as well. However, we're unlikely to release another 2.8.x, so 3.x is a better version to switch to.

Does anybody of you know what are the related fixes e.g. having a list of them or something else?
We consider to backport them to ganesha 2.7.6 and build own custom RPMs

**Comment by dang** [comment]
We don't keep lists of commits by feature, sorry.  You'd have to go through the commit logs.  All the relevant commits would have changes in src/FSAL/Stackable_FSALs/FSAL_MDCACHE/, and they all should have "readdir" or "dirent" somewhere in the commit message.

**Comment by ffilz** [comment]
What may be of some help the documents I maintain that track what has been back ported:

Backports to V2.7.x: https://docs.google.com/document/d/16AlBZbKyFysydq5qxnLpRhQJ4nSO8pFu56DDFfsRoM4/edit?usp=sharing
Backports to V2.8.x: https://docs.google.com/document/d/1vRrk-JFtUdU4b234hnv0npVqnKI8BTqUWGz5IHcxt0g/edit?usp=sharing
Backports to V3.x: https://docs.google.com/document/d/1WfyuJYajW3ECAUEuwXcNen8cn0mRyX2Krgr5KWp_iPc/edit?usp=sharing

**Comment by ffilz** [comment]
re-opening since ongoing discussion...

**Comment by dspisla** [comment]
Thanks for the hints. It makes it easier to search

**Comment by dspisla** [comment]
After doing some researches and discussions we decided to switch to the latest **ganesha version (v3.5)**.
But unfortunatly for SLES15SP2 there are no such RPMs available, only v3.0 Community packages available for SLES15SP1:
https://download.opensuse.org/repositories/home:/nfs-ganesha:/SLES15SP1-nfs-ganesha-3/SLE_15_SP1/x86_64/

Is there a way to get the proper community packages? If not, we would build our own packages

**Comment by dspisla** [comment]
I have contacted @kalebskeithley  . In the next few days the update of the packages in OBS will happen

**Comment by dspisla** [comment]
@kalebskeithley  Thanks for the RPM packages. 

For us this solves the issues here
