### ISSUE TITLE
BSD-4-clause: src/os/freebsd/mntent_compat.c

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/nfs-ganesha#70]
File `src/os/freebsd/mntent_compat.c` is licensed under "BSD-4-clause" (old BSD) license. Unfortunately this GPL-incompatible license is universally deprecated.
It is not recognised as DFSG-compatible license hence this file can not be included to [Debian](http://debian.org) etc.

See more
- https://www.gnu.org/licenses/license-list.html#OriginalBSD
- https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_.28original_.22BSD_License.22.2

Please consider removing this file or re-license it under "new" BSD (aka BSD-3-clause) license if all copyright holders agree to that:
- Stanislav Sedov ssedov@mbsd.msk.ru
- David Rufino daverufino@btinternet.com

**Comment by ffilz** [comment]
This file is only used for building on FreeBSD. It may safely be removed from any other distribution. If we find a way to re-license this, or replace it we will, but currently the priority to do so is low.

**Comment by ffilz** [comment]
Is this still an issue? If not, can this issue be closed? I will close it next week if there is no response otherwise.
