### ISSUE TITLE
How to uncache the files' attributes in nfs-ganesha

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#700]
I have implemented FSAL. In my FSAL level, the files can be updated automatically.  But client can't know the change of files immediately.

I use the mount command is as follows:
mount -t nfs -o vers=4,noac,sync,actimeo=1,lookupcache=none 。。。。

But the client still can't perceive the change of the file immediately, for example:

I use command:
ls -lh fileA
-rwx---- 1M fileA

When fileA changed to 2MB in FSAL Level.

It is still displayed on the client side.
-rwx---- 1M file

After capturing the packet, I found that the length of the file returned by the server is still the 1M, so I doubt whether nfs-ganesha will cache the attributes of the file, and how can Ganesha not cache the attributes of the file.

Thank you.

**Comment by dang** [comment]
You need to implement the correct UP call, in this case the invalidate() call.  This will let MDCACHE know that a file has changed behind it's back, and it can handle it properly.

You can see mem_invalidate() in FSAL/FSAL_MEM/mem_up.c for a very simple example, or up_process_event_object() in FSAL/FSAL_GLUSTER/fsal_up.c for a more complicated example.

If you want the invalidate to happen inline, you call the invalidate() UP call, if you want it invalidated asynchronously, you call the invalidate_close() up call.

**Comment by lpstudy** [comment]
@agin719 In ganesha.conf, there is a config called `Attr_Expiration_Time = 0, maybe you can try it?
`

**Comment by lpstudy** [comment]
for ls cache, set `Dir_Chunk = 0`, do not cache the `ls` results in dir_chunk structs.

**Comment by agin719** [comment]
Thank you, I have set Attr_Expiration_Time = 0, and it work for me.
