### ISSUE TITLE
The client mount point disappears after the quota is set for the cephfs export directory

### ISSUE THREAD

**Issue by lnsyyj** [nfs-ganesha/nfs-ganesha#701]
nfs-ganesha version :3.4GA
ceph version: 14.2.15

cat /etc/ceph/ceph.conf
```
[client]
client quota df = true
fuse_default_permission=0
client_acl_type=posix_acl
```

cat /etc/ganesha/ganesha.conf
```
LOG {
    components {
        ALL = DEBUG;
    }
}

NFS_CORE_PARAM
{
	# Ganesha can lift the NFS grace period early if NLM is disabled.
	Enable_NLM = false;

	# rquotad doesn't add any value here. CephFS doesn't support per-uid
	# quotas anyway.
	Enable_RQUOTA = true;

	# In this configuration, we're just exporting NFSv4. In practice, it's
	# best to use NFSv4.1+ to get the benefit of sessions.
	Protocols = 4;
}

EXPORT
{
	Export_ID = 1;
	Path = "testbucket";
	Pseudo = "/testbucket";
	Access_Type = RW;
	Protocols = "3","4";
	Transports = TCP;
	FSAL {
		Name = RGW;
		User_Id = "yujiang";
		Access_Key_Id ="3DNM7Z57L4UXGDPMG3FU";
		Secret_Access_Key = "rWsCjB0u7GF4uPXTTaE0BU4rfNP33OE2WufJBJEt";
	}
}

EXPORT
{
        Export_ID = 2;
        Path = "/nfstest";    
        Pseudo = /nfstest;    #ceph-fuse mount point on nfs-ganesha server
        Access_Type = RW;
	Protocols = "3","4";
	Transports = TCP;
        FSAL {
                Name = CEPH;
        }
}

RGW {
	ceph_conf = "/etc/ceph/ceph.conf";
	# for vstart cluster, name = "client.admin"
	name = "client.rgw.yujiang-dev";
	cluster = "ceph";
	# init_args = "-d --debug-rgw=16";
}

CEPH
{
	# Path to a ceph.conf file for this ceph cluster.
	ceph_conf = /etc/ceph/ceph.conf;

	# User file-creation mask. These bits will be masked off from the unix
	# permissions on newly-created inodes.
	umask = 0;
}
```

client
```
root@yujiang-dev:~# mount -t nfs -o nfsvers=4.1,proto=tcp 192.168.3.162:/nfstest /root/nfstest/
root@yujiang-dev:~# df -Th
192.168.3.162:/nfstest nfs4             54G  128M   54G   1% /root/nfstest
```

nfs-ganesha server
```
setfattr -n ceph.quota.max_bytes -v 40960 /ceph-fuse/nfstest/
```

client view again (df mountpoint disappeared)
```
root@yujiang-dev:~# df -Th
```

**Comment by ffilz** [comment]
Did df hang or simply show nothing? df doesn't normally stop showing a mounted filesystem, if the server isn't available, df may hang depending on how the NFS mount was done (hard/soft/intr settings) so maybe something else umounted the NFS mount?

**Comment by lnsyyj** [comment]
> Did df hang or simply show nothing? df doesn't normally stop showing a mounted filesystem, if the server isn't available, df may hang depending on how the NFS mount was done (hard/soft/intr settings) so maybe something else umounted the NFS mount?

Use df to view but the mount point is not displayed, and then the nfs mount point cannot write data.

When I set `setfattr -n ceph.quota.max_bytes -v 0 /ceph-fuse/nfstest/`  , df looks at the mount point and it is normal. Can nfs-ganesha support ceph.quota.max_bytes?

**Comment by lnsyyj** [comment]
When I use strace tracking system call `strace df -Th`

Set `setfattr -n ceph.quota.max_bytes -v 0 /ceph-fuse/nfstest/`
```
statfs("/root/nfstest", {f_type=NFS_SUPER_MAGIC, f_bsize=1048576, f_blocks=54868, f_bfree=54740, f_bavail=54740, f_files=1, f_ffree=18446744073709551615, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=1048576, f_flags=ST_VALID|ST_RELATIME}) = 0
```

Set `setfattr -n ceph.quota.max_bytes -v 40960 /ceph-fuse/nfstest/`
```
statfs("/root/nfstest", {f_type=NFS_SUPER_MAGIC, f_bsize=1048576, f_blocks=0, f_bfree=0, f_bavail=0, f_files=1, f_ffree=18446744073709551615, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=1048576, f_flags=ST_VALID|ST_RELATIME}) = 0
```

f_blocks, f_bfree, f_bavail return differently, will it be related to this?

In nfs-ganesha `static fsal_status_t get_fs_dynamic_info`, this value vfs_st is returned by ceph, `rc = ceph_ll_statfs(export->cmount, export->root->i, &vfs_st);`
If I want to use cephfs' quota, are there other options?

This is the problem of `int Client::statfs(const char *path, struct statvfs *stbuf, const UserPerm& perms) in the ceph code. When I set `client_quota_df = false` in ceph.conf, df can display the nfs mount point normally.

Does this require joint consultation between the nfs-ganesha community and the ceph community?

**Comment by lnsyyj** [comment]
Thank you, the problem has been solved. The value I set is too small, and the quota must be greater than 4M.

**Comment by ffilz** [comment]
Closing as resolved.
