### ISSUE TITLE
Export of BTRFS subvolumes not possible

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [nfs-ganesha/nfs-ganesha#703]
**SUMMERY**
I try to get NFS-Ganesha running on BTRFS. I can't export a BTRFS subvolumes via NFS.

**ISSUE TYPE**
* Bug Report

**OS**

1.  Debian 10, kernel: 4.19.0, nfs-ganesha 3.3-4
2. Ubuntu 20.4, kernel: 5.4.0, nfs-ganesha 3.5-ubuntu1~focal1 from a [ppa](https://launchpad.net/~nfs-ganesha)

**STEPS TO REPRODUCE**

_On the server with the name files, was  this small test setup made_

```
sudo dd if=/dev/zero of=/tmp/btrfs.img bs=1024k count=1024  
sudo mkfs -t btrfs /tmp/btrfs.img 
mkdir -m555 /tmp/btrfs 
sudo mount /tmp/btrfs.img /tmp/btrfs 
sudo mkdir /tmp/btrfs/dir  # just a dir
sudo btrfs subvolume create /tmp/btrfs/sub # create a subvolume
```

Use this [ganesha.conf](https://github.com/nfs-ganesha/nfs-ganesha/files/6236743/ganesha_conf.log)
and start  NFS-Ganesha.

The attached [ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/6236736/ganesha.log) provided all logs during the tests.

_On my desktop_
I just created a new directory at `/mnt/tmp`. 
`$ sudo mount files:/btrfs /mnt/tmp -t nfs -o vers=4`
```
$ ls -l /mnt/tmp/dir 
total 1
-rw-r--r-- 1 root root 0 Mär 31 14:27 test1.txt
```
`$ ls -l /mnt/tmp` → Invalid link across device boundaries

```
$ sudo mount files:/btrfs/sub /mnt/tmp -t nfs -o vers=4    
mount.nfs: Invalid cross-device link
```

```
$ sudo mount files:/btrfs/dir /mnt/tmp -t nfs -o vers=4
$ ls -l /mnt/tmp/ 
-rw-r--r-- 1 root root 0 Mär 31 14:27 test1.txt
total 1
$ ls -l /mnt/tmp/dir
No such file or directory error
```

```
$ sudo mount files:/btrfs /mnt/tmp/dir -t nfs -o vers=4
mount.nfs: mount point /mnt/tmp/dir does not exist
```

**Comment by kalebskeithley** [comment]
I have no problem exporting btrfs volumes:

On my hirsute box (don't know why I picked hirsute, for some reason I was thinking it was zfs, not btrfs :-))
%mount
...
/dev/sda1 on /btrfs type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
...

my /etc/ganesha/ganesha.conf:
EXPORT
{
	# Export Id (mandatory, each EXPORT must have a unique Export_Id)
	Export_Id = 99;

	# Exported path (mandatory)
	Path = /btrfs;

	# Pseudo Path (required for NFS v4)
	Pseudo = /btrfs_pseudo;

	# Required for access (default is None)
	# Could use CLIENT blocks instead
	Access_Type = RW;

	# Exporting FSAL
	FSAL {
		Name = VFS;
	}
}

%mount localhost:/btrfs /mnt

%mount
...
(rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=127.0.0.1,mountvers=3,mountport=41638,mountproto=udp,local_lock=none,addr=127.0.0.1)
...

% touch /mnt/kalebwashere
% ls /mnt
kalebwashere

Also works if I use the loopback mount of a btrfs .img file system.

I'm not really up on btrfs subvolume does, or what implications it would have on ganesha. When I try and export a btrfs subvol I get:
...
31/03/2021 14:38:55 : epoch 6064897f : hirsute : ganesha.nfsd-7364[main] vfs_create_export :FSAL :CRIT :resolve_posix_filesystem(/btrfs/sub) returned Resource temporarily unavailable (11)
31/03/2021 14:38:55 : epoch 6064897f : hirsute : ganesha.nfsd-7364[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL VFS
31/03/2021 14:38:55 : epoch 6064897f : hirsute : ganesha.nfsd-7364[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/btrfs_sub_pseudo) to (/btrfs/sub)
31/03/2021 14:38:55 : epoch 6064897f : hirsute : ganesha.nfsd-7364[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
...

in the log file. Is that what you're seeing?

Maybe one of the other devs knows more.

**Comment by ffilz** [comment]
What is in the Ganesha log? I suspect the problem is that Ganesha is expecting the subvolume to show up in the mount list. If it doesn't then Ganesha (with current code) is stuck. It knows there is a filesystem boundary because st_dev has changed, but if it can't find a mount entry it gets confused. Even without debug logging, there should be INFO and CRIT messages that highlight the issue.

If this is the case, I don't think it will be to hard to fix and would map well into work I'm currently in progress on.

I will have to consider subvolumes being moved...

**Comment by ffilz** [comment]
BTW, I have recreated this, now to try and fix it...

I already had a btrfs filesystem and export (just not activated)...

**Comment by Unterstrichmoepunterstrich** [comment]
I was reading your discussion in IRC about creating a `BTRFS_FSAL` and want to give  you some hints.
The idea is, to create  each 15 minutes a snapshot, so I can do easy rollback, when it's nessecary. The problem with BTRFS and Ganesha is, that everything is a subvolume. So when I want to  mount via nfs {my last,a} snapshot, I have to extend the `ganesha.conf`:

```
EXPORT {
    Export_id = 4;
    Path = /tmp/btrfs/.snapshots;
    Pseudo = /btrfs/.snapshots;

    FSAL {
        Name = VFS;
    }

EXPORT {
    Export_id = 5;
    Path = /tmp/btrfs/.snapshots/test_2021-04-01_13:27:00;
    Pseudo = /btrfs/.snapshots/test_2021-04-01_13:27:00;

    FSAL {
        Name = VFS;
    }
```

Maybe Ganesha should generate a way to build the Exports for `.snapshots`, because we know that everthing inside is a subvolume.

**Comment by ffilz** [comment]
We won't actually need to generate an export, we just need to populate discovered filesystems without relying on the mount table. It actually shouldn't be too hard. My recreate showed the messages I was expecting based on the code, so my understanding looks good.

I think we can actually make things more responsive because instead of scanning the mount table when we discover a new filesystem we will just create it. I need to check how badly we actually need to have the mount path of the discovered filesystem but we can always do lookup parent in the mounted on filesystem until we get to that filesystem's root (or even an export root).

Ganesha already supports nested filesystems within an export, it was just relying on the mount table to find them. I am almost done with a work effort that will improve Ganesha's capability with dynamically changing exports and filesystems, so this is a small incremental piece of work on that.

At the point I'm at, I don't believe we will need a FSAL_BTRFS

**Comment by ffilz** [comment]
I'm looking at how to use libbtrfsutil to scan for subvols at the time we scan the mount table which should make subvols then work the same as mounted filesystems including being able to be "discovered" after creation.

**Comment by ffilz** [comment]
I have added support for btrfs subvols in this patch:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/514026

That may also depend on:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/514025

So probably best to take both.

Basically we add "filesystem" entries for each subvol.

And this is done without the need for FSAL_BTRFS.

To use this, btrfsutils must be installed so libbtrfsutil is available to provide the subvol API

**Comment by Unterstrichmoepunterstrich** [comment]
> I have added support for btrfs subvols in this patch:
> 
> https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/514026
> 
> That may also depend on:
> 
> https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/514025

@ffilz thank you for the fast reply.
I want to build a test package to verify, if the problem is solved.

I started with package Version 3.3-4 from the nfs-ganesha repository and used nfs-ganesha Version 3.4-1~bpo10+2 from Buster Backports. Basicly my idea was, to put the patches below into `/debian/patches` directory and build a new package.
To verify, if its possible to use these patch on these package Version, I tried:

```
patch -p1 CMakelists.txt /path/to/add_btrfs_subvol_support.patch
patch p1 /src/FSAL/FSAL_GPFS/export.c /path/to/Rework_fsal_filesystem_handling.patch
```
The output at the backport package looks like that:

```
patching file CMakeLists.txt
Hunk #1 FAILED at 585.
Hunk #2 FAILED at 1181.
2 out of 2 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
patching file CMakeLists.txt
Hunk #1 FAILED at 87.
Hunk #2 FAILED at 1012.
Hunk #3 FAILED at 1114.
3 out of 3 hunks FAILED -- saving rejects to file CMakeLists.txt.rej
patching file CMakeLists.txt
Hunk #1 FAILED at 78.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
```

So I assume, that I need older patches, too. But I don't know which are nessecary and which not.

**Comment by Unterstrichmoepunterstrich** [comment]
Hello @ffilz and @kalebskeithley 

I build a package from the latest patch and installed only the packages `nfs-ganesha` and `nfs-ganesha-vfs:amd64` on my test VM. I attach the file from `debian/control`(see [file here](https://gist.github.com/Unterstrichmoepunterstrich/bc6eaa9275db9d434ca27195dd1268d9) I just removed `libntirpc3` and replaced it with `libntirpc3.4`.
On my test VM is a segfault and it's possible not fixed.

```
Apr 26 15:05:16 debian-vm systemd[1]: Started NFS-Ganesha file server.
Apr 26 15:05:16 debian-vm systemd[1]: nfs-ganesha.service: Main process exited, code=killed, status=11/SEGV
Apr 26 15:05:16 debian-vm systemd[1]: nfs-ganesha.service: Failed with result 'signal'.
Apr 26 15:05:16 debian-vm kernel: [ 4381.807306] ganesha.nfsd[3685]: segfault at 441f0f67013f ip 00007f57cf6d230a sp 00007ffe9fb5d050 error 4 in libganesha_nfsd.so.4[7f57cf6c9000+133000]
Apr 26 15:05:16 debian-vm kernel: [ 4381.807315] Code: 60 49 89 c4 49 89 f5 48 89 5c 24 68 4c 89 f3 49 89 c6 66 0f 1f 44 00 00 48 8d 6b e0 48 3b 6b e0 0f 84 b3 00 00 00 48 8b 43 d0 <48> 8b 80 40 01 00 00 4c 8b b8 d0 00 00 00 49 8b 17 eb 06 0f 1f 00
Apr 26 15:05:33 debian-vm systemd[1]: Starting Process NFS-Ganesha configuration...
Apr 26 15:05:33 debian-vm systemd[1]: nfs-ganesha-config.service: Succeeded.
Apr 26 15:05:33 debian-vm systemd[1]: Started Process NFS-Ganesha configuration.
Apr 26 15:05:33 debian-vm systemd[1]: Starting NFS-Ganesha file server...
Apr 26 15:05:33 debian-vm systemd[1]: Started NFS-Ganesha file server.
Apr 26 15:05:33 debian-vm kernel: [ 4398.721913] ganesha.nfsd[3697]: segfault at 441f0f67013f ip 00007faf9b4b630a sp 00007ffda6ff18c0 error 4 in libganesha_nfsd.so.4[7faf9b4ad000+133000]
Apr 26 15:05:33 debian-vm kernel: [ 4398.721917] Code: 60 49 89 c4 49 89 f5 48 89 5c 24 68 4c 89 f3 49 89 c6 66 0f 1f 44 00 00 48 8d 6b e0 48 3b 6b e0 0f 84 b3 00 00 00 48 8b 43 d0 <48> 8b 80 40 01 00 00 4c 8b b8 d0 00 00 00 49 8b 17 eb 06 0f 1f 00
Apr 26 15:05:33 debian-vm systemd[1]: nfs-ganesha.service: Main process exited, code=killed, status=11/SEGV
Apr 26 15:05:33 debian-vm systemd[1]: nfs-ganesha.service: Failed with result 'signal'.
```

**Comment by ffilz** [comment]
Do you have a back trace for the segfault?

**Comment by Unterstrichmoepunterstrich** [comment]
> Do you have a back trace for the segfault?

how can i trigger it to give you the information you need?

**Comment by ffilz** [comment]
Run Ganesha under gdb, either attaching to an already running process or starting Ganesha from gdb. Make sure to install the debug package so the back trace has symbols. Then when the segfault hits, issue the "bt" command and post the result.

**Comment by Unterstrichmoepunterstrich** [comment]
@ffilz see here the [backtrace with gdb](https://gist.github.com/Unterstrichmoepunterstrich/1462f375b9845a728e4c8a1603439c09) and the output from [strace](https://gist.github.com/Unterstrichmoepunterstrich/0f2ecc45a0c38ff3a6d46fc9ea8b1102). The dbgsym package for nfs-ganesha-vfs is installed.

**Comment by ffilz** [comment]
Hmm, can you get a back trace with line numbers? Not sure if you need the source installed or what. Or maybe you need to build Ganesha with more debug.

Thanks

Frank

**Comment by Unterstrichmoepunterstrich** [comment]
I can try it @ffilz, but tbo I'm not very experienced with CMake/cc flags. Can you give me a pointer, where I have to add some debug flags?

moep

**Comment by ffilz** [comment]
This is the script I use to do builds:

cmake ./ -DDEBUG_SYMS=ON -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_BUILD_TYPE=Maintainer \
	-DDEBUG_SAL=ON -DUSE_GUI_ADMIN_TOOLS=OFF -DPROXY_HANDLE_MAPPING=ON \
	-DSANITIZE_ADDRESS=ON -DUSE_DBUS=ON -DUSE_FSAL_XFS=ON \
	-DUSE_TOOL_MULTILOCK=ON -DUSE_CB_SIMULATOR=ON -DUSE_SYSTEM_NTIRPC=yes && \
make install

You probably only need:

cmake ./ -DDEBUG_SYMS=ON -DCMAKE_PREFIX_PATH=/usr/ -DCMAKE_BUILD_TYPE=Maintainer -DUSE_SYSTEM_NTIRPC=yes
