### ISSUE TITLE
Unexpected value when tested with nfstest

### ISSUE THREAD

**Issue by xuxlz** [nfs-ganesha/nfs-ganesha#708]
When I use nfstest to test mounted folder,  I get some unexpected results. They make me confused.             
             
My environment:               
CentOS Linux release 7.4                  
nfs-ganesha version V4-dev.54              
nfs-ganesha(with MEM/VFS config) runs on a machine and mounted on another machine                    
             
Test 1:           
Set Squash = None, use root identity. Test write without write access. Unexpected write success. Look up in fsal_check_access_no_acl function(FSAL/access_check.c), I found superuser is granted read and write. Why is it designed?                
![image](https://user-images.githubusercontent.com/59353885/114846830-a4b5ad80-9e0f-11eb-80d1-f07eea9717a3.png)               
![image](https://user-images.githubusercontent.com/59353885/114850001-eb58d700-9e12-11eb-85b2-0bf435dc1527.png)
                  
Test 2:                
Use user identity. Create file/folder then use stat command. Unexpected shows uid=nobody and gid=nobody. Look up in     xdr_encode_nfs4_princ function(idmapper/idmapper.c), I found use_getpwnam=true. Nfs-ganesha encoded with local user name (which id is same as remote machine user id). Is there a problem with my configuration? Or Is it a feature?              
![image](https://user-images.githubusercontent.com/59353885/114852643-89e63780-9e15-11eb-9d64-9048a8c9811e.png)                  
               
Looking forward to hearing from you! Thank you!

**Comment by dang** [comment]
For test 1, this is how permissions work in the POSIX and POSIX-like world.  Root has read/write access to everything.  If you want to be able to restrict root access, you need to use something like SELinux.

For test 2, this likely means that your idmapd is not configured correctly on the client and server.  You need to have the same domain configured in both, and DNS has to resolve to that domain for both.
