### ISSUE TITLE
ls command slow under high workload

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#709]
ls slow/stuck while running the fio workload on nfs mount.

Steps:
1. Create 32k files in a nfs mount. (used defalut flags to mount using nfsv3 on RHEL client)
2. Run fio workload on the nfs mount from one terminal (fio command used: fio -filename=./test_randread -rw=write -direct=1 -bs=512K -size=32G -numjobs=15 -runtime=6000 -group_reporting -name=mytest)
3.  From different termianl run ls command. This will hang/ takes long time to return.
Mount flags:
rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.11.56,mountvers=3,mountport=40415,mountproto=udp,local_lock=none,addr=192.168.11.56

ganesha branch: 2.7.5

This issue is not observed when sync option used for mount.

On analysis of the logs, found reason for ls slow/stuck for longtime is lock contention. READDIR thread waiting to get lock  (&orig_hdl>obj_lock) ( at  PTHREAD_RWLOCK_wrlock(&orig_hdl->obj_lock); )which is being held by threads doing write operation.
After I stopped fio workload, the blocked thread proceeded   and acquired the lock and ls returned.

fsal_status_t gpfs_merge(struct fsal_obj_handle *orig_hdl,
             struct fsal_obj_handle *dupe_hdl)
{
... 
        /* This can block over an I/O operation. */
        PTHREAD_RWLOCK_wrlock(&orig_hdl->obj_lock);

        status = merge_share(&orig->u.file.share, &dupe->u.file.share);

        PTHREAD_RWLOCK_unlock(&orig_hdl->obj_lock);
...
}

**Comment by ffilz** [comment]
Fix posted for review: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/514964
