### ISSUE TITLE
wrong install target

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [nfs-ganesha/nfs-ganesha#710]
**OS**

Debian Buster + Backports

**ISSUE TYPE**
- improvement

**STEPS TO REPRODUCE**

1. download the source package for NFS Ganesha 3.5. You need the `debian` directory and all dependencies.
2. replace `src` with the content of V4-dev.58
3. start to build a Debian package with `dpkg-buildpackage -rfakeroot -b`

**WHAT HAPPEND**

After compiling the install target fails. `nfs-ganesha-proxy.install` contains `usr/lib/*-linux-gnu*/ganesha/libfsalproxy.so*` 
```
~/nfs-ganesha-4-dev.58/debian/tmp$ find -name *libfsalproxy*
./usr/lib/x86_64-linux-gnu/ganesha/libfsalproxy_v4.so
./usr/lib/x86_64-linux-gnu/ganesha/libfsalproxy_v3.so
```
**HOW TO FIX**

1. Change content of `nfs-ganesha-proxy.install` to `usr/lib/*-linux-gnu*/ganesha/libfsalproxy_v*.so`

**Comment by dang** [comment]
Yeah, not surprising.  V4 splits FSAL_PROXY into two separate FSALs, one for V3 and one for V4, so packaging needs to be updated.

**Comment by kalebskeithley** [comment]
Noted for when we release V4.

(The correct place for this is really https://github.com/nfs-ganesha/nfs-ganesha-debian/issues)

**Comment by ffilz** [comment]
With V4-rc1 on the horizon, this will need to be addressed. Opening an https://github.com/nfs-ganesha/nfs-ganesha-debian/issues/40
