### ISSUE TITLE
FD Hard Limit Exceeded，lru_run canot close any fd，return 10008 to all client open op 

### ISSUE THREAD

**Issue by waterdyg** [nfs-ganesha/nfs-ganesha#712]
Hi!

run vdbench a few seconds, IO is 0,  only restart ganesha can come back to normal.

----------analysis---------
1.modify ulimit to 65536 or per_lane_work to 200 , only cloud run longer before return 10008 error, then also exceed Hard Limit.
2.after exceed hard limit, gdb attach ganesha, see all LRU L1 lane q is empty.
3.only shared=yes take error. when share=yes and only one dir for vdbench, two clients send 2 create ops with same file name  to ganesha in same time for lot of files.
4.ganesha canot close any fd, must restart ganesha.

-------env-------
ganesha version：3.2-3.el8

FSAL: ceph
OS：centos8.1
mount vers: v3

vdbench config:
hd=default,vdbench=/home/vdbench,user=root,shell=ssh
hd=hd1,system=host1
hd=hd2,system=host1

fsd=fsd1,anchor=/mnt/nfs/test1,depth=1,width=1,files=100000,size=4k,shared=yes

fwd=format,threads=64
fwd=default,xfersize=4k,fileio=random,fileselect=random,rdpct=0,threads=64
fwd=fwd1,fsd=fsd1,host=hd1
fwd=fwd2,fsd=fsd1,host=hd2
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=10,interval=1

mdcache config:
_**MDCACHE {
        # Size the dirent cache down as small as possible.
        Dir_Chunk = 1;

        # size the inode cache as small as possible
        NParts = 1;
        Cache_Size = 1;
}**_

ganesha log:
mdcache_lru_fds_available :INODE LRU :CRIT :FD Hard Limit (4055) Exceeded (open_fd_count = 4055), waking LRU thread

**Comment by dang** [comment]
Please upgrade to 3.5.  There have been several fixes to LRU processing that should help with these issues.

**Comment by waterdyg** [comment]
> Please upgrade to 3.5. There have been several fixes to LRU processing that should help with these issues.

Thanks， but issues still exist after upgrade to 3.5.

**Comment by ffilz** [comment]
Can you verify on V4-devel? Ganesha V4.0 will be released soon with rc1 this week. In the community call today we discussed that one of the features of V4 is more aggressive LRU pruning which should help this issue.

**Comment by hnkboy** [comment]
verify on V4-devel  same problem occurred.

**Comment by ffilz** [comment]
> verify on V4-devel same problem occurred.

Since we now have V6 as a stable release, and V7 is well into development, we would need this to be replicated at least on V6.5 if not on V7-dev.14 or newer in order to reconsider the issue.
