### ISSUE TITLE
dbus ShowExports still broken in V4-dev.59

### ISSUE THREAD

**Issue by bjorn-fischer** [nfs-ganesha/nfs-ganesha#713]
Even after 086f45cc6740e48b7f269836670a017d723bc137 _dbus/export: fix ShowExports not work_ __ShowExports__ still does not work in my case:
```
#define _USE_9P 1
#define _USE_NFS3 1
#define _USE_NLM 1
#define _USE_RQUOTA 1
```
I use Perl __Net::DBus__ to access the dbus interface, and I always get this decoding error:
```
Calling exportMgr->ShowExports()
Use of uninitialized value in string eq at /usr/lib/x86_64-linux-gnu/perl5/5.30/Net/DBus/Binding/Introspector.pm line 814.
unexpected end of struct at /usr/lib/x86_64-linux-gnu/perl5/5.30/Net/DBus/Binding/Introspector.pm line 814.
```
V4-dev.46 does not have this issue.

**Comment by dang** [comment]
Looks it was broken with NFSv3 off, and now it's broken with it on.  This change did it:
086f45cc6740e48b7f269836670a017d723bc137

**Comment by bjorn-fischer** [comment]
Well yes, I already referenced that commit.

Seems like `export_show_exports.args` lacks the _NLM status_ resulting in one `b` gone missing. And the buffer `char export_contents[16];` is one byte too small.

**Comment by bjorn-fischer** [comment]
I tried this:
```
diff --git a/src/support/export_mgr.c b/src/support/export_mgr.c
index bcfb00cd8..80b8fe69a 100644
--- a/src/support/export_mgr.c
+++ b/src/support/export_mgr.c
@@ -1626,7 +1626,7 @@ static bool gsh_export_showexports(DBusMessageIter *args,
 {
        DBusMessageIter iter;
        struct showexports_state iter_state;
-       char export_contents[16];
+       char export_contents[17];
 
        /* create a reply from the message */
        dbus_message_iter_init_append(reply, &iter);
@@ -1668,6 +1668,12 @@ static struct gsh_dbus_method export_show_exports = {
                 .type = "b",
                 .direction = "out"},
 #endif
+#ifdef _USE_NLM
+               {
+                .name = "nlm_st",
+                .type = "b",
+                .direction = "out"},
+#endif
 #ifdef _USE_RQUOTA
                {
                 .name = "rquota_st",
```
...but it still does not work.

But if I replace the introspection struct with an opaque single arg ```.type = "a(qsbbbbbbbb(tt))"``` it works for _my case_. Seems like something is wrong with the assembly of the introspection structure.

BTW: While looking into this, I asked myself: Is it wise to have a changing dbus API across different compile time options? Shouldn't the dbus API be stable and non-existing stats (e.g. due to ```#undef _USE_NFS3```) always be _false_ (or tri-state undefined)?

**Comment by bjorn-fischer** [comment]
<ins>Digging deeper:</ins> Using the dbus introspection interface, one can see what ```/org/ganesha/nfsd/ExportMgr``` replies to ```org.freedesktop.DBus.Introspectable.Introspect```...

This was prior to 086f45cc6740e48b7f269836670a017d723bc137:
```
    <method name="ShowExports">
      <arg name="time" direction="out" type="(tt)"/>
      <arg name="exports" direction="out" type="a(qsbbbbbbbb(tt))"/>
    </method>
```
And this is how it looks after 086f45cc6740e48b7f269836670a017d723bc137:
```
    <method name="ShowExports">
      <arg name="time" direction="out" type="(tt)"/>
      <arg name="exports_start_array" direction="out" type="a"/>
      <arg name="_struct_bgn" direction="out" type="("/>
      <arg name="id_and_path" direction="out" type="qs"/>
      <arg name="nfsv3_st" direction="out" type="b"/>
      <arg name="mnt_st" direction="out" type="b"/>
      <arg name="nlm_st" direction="out" type="b"/>
      <arg name="rquota_st" direction="out" type="b"/>
      <arg name="nfsv40_st" direction="out" type="b"/>
      <arg name="nfsv41_st" direction="out" type="b"/>
      <arg name="nfsv42_st" direction="out" type="b"/>
      <arg name="9p_st" direction="out" type="b"/>
      <arg name="timestamp" direction="out" type="(tt)"/>
      <arg name="_struct_end" direction="out" type=")"/>
    </method>
```
While the concatenated type sequences are the same, ```(``` and ```)``` are no valid single complete types as [the spec](https://dbus.freedesktop.org/doc/dbus-specification.html#type-system) defines. The [introspection data format](https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format) does not state explicitly that types may be split up to multiple fragments, so it is safe to assume that only single complete types are allowed.
To fix the problem, we should generate a type string ```a(qsbbbbbbbb(tt))``` with just as many booleans as needed...
...or to have a stable dbus API across different sets of compile time options, simply set a stat to _false_ in ```server_stats_summary()``` if a protocol is not included in the build.

I definitely would prefer the latter.

**Comment by ffilz** [comment]
Hmm, so two thoughts. One, the format being always the same has appeal, on the other hand, we are starting to see more and more NFSv4 only setups which ideally shouldn't see any reference to v3...

Let's get it working correctly with the conditional compile differences and then give some more thought.

Could you submit a patch?

**Comment by bjorn-fischer** [comment]
Well, ok then. I'd like to move the type string assembly into the cpp phase as compile time options should not evoke runtime computation unless really necessary. The diff is barely readable, so here is the plain code. If this looks ok, I'll prepare a gerrithub submission.
```
#ifdef _USE_NFS3
#define STAT_TYPE_NFS3 "bb"
#else
#define STAT_TYPE_NFS3 ""
#endif

#ifdef _USE_NLM
#define STAT_TYPE_NLM "b"
#else
#define STAT_TYPE_NLM ""
#endif

#ifdef _USE_RQUOTA
#define STAT_TYPE_RQUOTA "b"
#else
#define STAT_TYPE_RQUOTA ""
#endif

#ifdef _USE_9P
#define STAT_TYPE_9P "b"
#else
#define STAT_TYPE_9P ""
#endif

#define EXPORT_CONTAINER \
        "(qs" STAT_TYPE_NFS3 STAT_TYPE_NLM \
        STAT_TYPE_RQUOTA "bbb" STAT_TYPE_9P "(tt))"

static bool gsh_export_showexports(DBusMessageIter *args,
                                   DBusMessage *reply,
                                   DBusError *error)
{
        DBusMessageIter iter;
        struct showexports_state iter_state;

        /* create a reply from the message */
        dbus_message_iter_init_append(reply, &iter);
        gsh_dbus_append_timestamp(&iter, &nfs_stats_time);
        dbus_message_iter_open_container(&iter, DBUS_TYPE_ARRAY,
                                         EXPORT_CONTAINER,
                                         &iter_state.export_iter);

        (void)foreach_gsh_export(export_to_dbus, false, (void *)&iter_state);

        dbus_message_iter_close_container(&iter, &iter_state.export_iter);
        return true;
}

static struct gsh_dbus_method export_show_exports = {
        .name = "ShowExports",
        .method = gsh_export_showexports,
        .args = {TIMESTAMP_REPLY,
                {
                .name = "exports",
                .type = "a" EXPORT_CONTAINER,
                .direction = "out"},
                 END_ARG_LIST}
};
```

**Comment by ffilz** [comment]
Yea, that looks good.

**Comment by bjorn-fischer** [comment]
Ok, commit 1e5449d2e917e5fc8424876887dd26871a5dcd05 is on gerrithub. A build with 9P support disabled seems to work fine.

PS: github has freaked me out again, referencing a gerrithub commit by its SHA just works...

**Comment by bjorn-fischer** [comment]
Fixed in __V4-dev.61__. Tested with feature sets
```
#define _USE_9P 1
#define _USE_NFS3 1
#define _USE_NLM 1
#define _USE_RQUOTA 1
```
and
```
#define _USE_9P 0
#define _USE_NFS3 1
#define _USE_NLM 1
#define _USE_RQUOTA 1
```
