### ISSUE TITLE
readdir got slower in 3.5

### ISSUE THREAD

**Issue by rakesh-roshan** [nfs-ganesha/nfs-ganesha#714]
I am upgrading my NFS Ganesha server from 2.7.6 to 3.5. I am using a custom FSAL.
After the upgrade, the `readdir` command is very slow. For the test setup, I am listing a directory with 1 million files.

The results are,
| NFS Version | Ganesha 2.7.6 | Ganesha 3.5 |
| ----------- | ------------- | ----------- |
| 3           | 2m 43s        | 4m 52s      |
| 4           | 5m 33s        | 29m 30s     |

As it can be seen above, the performance in NFS4 is worse.

I tried to look through the logs. I found one interesting thing in the OP_READDIR response sizes.

| | 3.5 | 2.7.6   |
| ------- | --- | ------- |
| Average | 20  | 2485.17 |
| Max     | 20  | 9404    |
| Min     | 20  | 240     |

I don't know the unit of the above values. But it seems something very different behavior from 2.7.6. Is there any configuration that is controlling the response sizes?

I also pulled this patch [Fix stall when readdir races with I/O and a new mdcache entry created](https://github.com/nfs-ganesha/nfs-ganesha/commit/aadb9cf27d8846a51cddd4d88f8ebb3ae20a5248). But it didn't help.

**Comment by ffilz** [comment]
Where did you get those response sizes from?

**Comment by rakesh-roshan** [comment]
I get that information from the log that is coming from the [nfs4_Compound.c#L724](https://github.com/nfs-ganesha/nfs-ganesha/blob/ff0401165d7fcdccb494431effc007be657ac68c/src/Protocols/NFS/nfs4_Compound.c#L724)

**Comment by ffilz** [comment]
OK, we might need to enable debug logging for READDIR:

LOG {
    COMPONENTS {
        READDIR = FULL_DEBUG;
    }
}

And then do a readdir of a a modest sized directory. Let's see what's going on.

**Comment by rakesh-roshan** [comment]
Do you want the full log? Or is there something that I should look for in the log?

**Comment by rakesh-roshan** [comment]
From the log what I found different from the 2.7.6 is the value of `whence`. In 2.7.6 if the readdir call is returning last cookie as 100, then, the next whence is 98. Only 2 entries behind. While in 3.5, the whence call goes back by almost 60.  E.g. in my case, a readdir read to value 100172 but, next call by client was with whence 100106. So for 66 entries the information was read again. Another thing I observed is that each whence value increases by exactly 102. So the values of whence are,

100106
100208
100310
100412
...
...

**Comment by rakesh-roshan** [comment]
Actual the issue was in the custom FSAL that I am using. It has ATTR_ACL in the support attributes list but it was not being set. The  bug was always there, it got exposed by the commit https://github.com/nfs-ganesha/nfs-ganesha/commit/97da49bda9adb23e1c0c081c417e2ad959ebafb0. In the commit, a validation was added. So this mismatch between the supported attributes and attributes being set by the FSAL was causing the test to always fail. This was invalidating the cache causing delays.

**Comment by ffilz** [comment]
Glad you were able to resolve the issue.
