### ISSUE TITLE
Coverity and Klocwork scan security problem

### ISSUE THREAD

**Issue by chenxi10273450** [nfs-ganesha/nfs-ganesha#715]
I did klocwork and coverity scan for nfs-ganesha,the attach files are the scan result.the version is 2.7.6,i hope there is someone to help solve these problem
[nfs-ganesha-2.7.6.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/6605320/nfs-ganesha-2.7.6.zip)

**Comment by dang** [comment]
2.7 is end of life, so we're not accepting fixes to it.
