### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by chenxi10273450** [nfs-ganesha/nfs-ganesha#716]
I did klocwork and coverity scan for nfs-ganesha,the attach files are the scan result.the version is 3.3,i hope there is someone to help solve these problem
[nfs-ganesha-3.3.zip](https://github.com/nfs-ganesha/nfs-ganesha/files/6605355/nfs-ganesha-3.3.zip)

**Comment by ffilz** [comment]
Could you describe the security problem in some detail? I'm not exactly thrilled about opening an unknown zip file.

**Comment by ffilz** [comment]
Closing this for lack of response. Plus the scan is of old code.
