### ISSUE TITLE
readdir stuck for NFS3 UDP  in 3.5

### ISSUE THREAD

**Issue by rakesh-roshan** [nfs-ganesha/nfs-ganesha#718]
The `readdir` command is stuck for ganesha 3.5 

Ganesha Version: 3.5

Steps:
1. Mounted a path using options `proto=udp,vers=3,nolock,hard`.
2. Ran `ls` command to list a directory on the mount.
3. The `ls` command gets stuck.

Reading a file works well. If I don't list a directory and directory reads a file using its path, it works.

Listing a directory in TCP mode works fine. 

From server log, I found this error message

```
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] /src/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3319 :mdcache_readdir_chunked :NFS READDIR :F_DBG :dirent = 0xd875e0 filegw3.5.test.5, cb_result = DIR_CONTINUE, eod = false
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] /src/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3272 :mdcache_readdir_chunked :NFS READDIR :F_DBG :Setting next_ck=271c
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] /src/src/Protocols/NFS/nfs3_readdirplus.c:451 :nfs3_readdirplus_callback :NFS READDIR :DEBUG :Callback for file1 cookie 10012
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] /src/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3319 :mdcache_readdir_chunked :NFS READDIR :F_DBG :dirent = 0xd87c80 file1, cb_result = DIR_CONTINUE, eod = true
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] /src/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3362 :mdcache_readdir_chunked :NFS READDIR :DEBUG :readdir completed, eod = true
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :xdr_reply_encode:93 ACCEPTED INLINE
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :xdr_reply_encode:109 SUCCESS
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :svc_dg_reply: 0xea7d60 fd 13 SVCAUTH_WRAP failed (will set dead)
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :svc_destroy_it() 0xea7d60 fd 13 xp_refcnt 3 af 10 port 733 @complete_request:781
Fri Jun 11 14:24:40 2021 UTC 17290[::ffff:10.10.1.155] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :svc_release_it() 0xea7d60 fd 13 xp_refcnt 2 af 10 port 733 @complete_request:781
Fri Jun 11 14:24:40 2021 UTC 17290[none] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :svc_release_it() 0xea7d60 fd 13 xp_refcnt 1 af 10 port 733 @free_nfs_request:1402
Fri Jun 11 14:24:40 2021 UTC 17290[none] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :svc_release_it() 0xcf6b20 fd 13 xp_refcnt 9 af 0 port 4294967295 @svc_rqst_xprt_task_recv:1182
Fri Jun 11 14:24:40 2021 UTC 17290[none] [svc_7] <no-file>:0 :rpc :TIRPC :F_DBG :work_pool_thread() svc_7 waiting

```

**Comment by boulos** [comment]
There are a couple of UDP / ntirpc fixes that I saw on the mailing list a
little while ago.

Both:


https://github.com/nfs-ganesha/ntirpc/commit/9e1b0c091ce4e6c8f7738797cc83930d4c048943

and:


https://github.com/nfs-ganesha/ntirpc/commit/137fde282212d8725808dd8d9f4da6f8ea163d76

might be relevant here.

How are you building Ganesha? Can you try with an up-to-date libntirpc?

**Comment by rakesh-roshan** [comment]
I am building Ganesha with libntirpc version 3.4. I also tried picking up the above two commits but it didn't help. From the log it seems for TCP version it is creating `ioq_xdr` for the `readdir` response while for UDP it is not. So at the check, in [svc_dg:svc_dg_reply](https://github.com/nfs-ganesha/ntirpc/blob/v3.4/src/svc_dg.c#L406) is failing causing the transport failure. The reason for the failure of the above condition is it is getting `false` from this [noop](https://github.com/nfs-ganesha/ntirpc/blob/v3.4/src/xdr_mem.c#L173) method. It seems something wrong here. 


I suspect the the change made in commit 
https://github.com/nfs-ganesha/nfs-ganesha/commit/ca84db5015ba3939d5e3372a906c788c0aa2440d#diff-700e0bc128b0b730914f1834629a85d65bed6d4d973887222bfa293c84f25dbcR1561 which now uses putbufs. This change seems to have caused the issue.

**Comment by rakesh-roshan** [comment]
The commit message of the above commit is 

```
Encode all the directory entries into an xdrmem buffer that can then
be added to the ioq via xdr_putbufs.
```

So it seems the change targets only `xdr_ioq` that is supposed to be used for only TCP transport. That is not supposed to be for UDP transport. That is causing this issue. Either similar to `xdr_ioq`, a `putbufs` method should be defined in the `xdr_mem` or, While reading directory, the response should be created based on the transport so that old behavior can be preserved for the UDP transport.

**Comment by ffilz** [comment]
Oops...

OK, we need to find a solution.

One option is to implement iovec for xdrmem/UDP, that may not be feasible

Another option is for xdrmem putbufs to copy the data so it basically is the same as putbytes

**Comment by ffilz** [comment]
See https://github.com/nfs-ganesha/ntirpc/issues/236 for anchor for ntirpc portion of this fix.

**Comment by ffilz** [comment]
I just submitted ntirpc pull request https://github.com/nfs-ganesha/ntirpc/pull/237 that should resolve this issue by adding xdr_putbufs to xdrmem.

**Comment by rakesh-roshan** [comment]
I verified with the fix that readdir is working fine after the fix. Thanks for fixing it quickly.

**Comment by rakesh-roshan** [comment]
I am sorry the readdir is working fine, but file read is failing 


```sh
[ec2-user@ip-10-10-1-155 release]$ cat !$
cat /mnt/tests3/file1
cat: /mnt/tests3/file1: Input/output error
```

Write is working fine.

**Comment by ffilz** [comment]
Could you debug more? reading is working for me on next for a v3 UDP mount

**Comment by rakesh-roshan** [comment]
Yeah I am trying to debug more. Did you write then read or directly read the file? For me when I wrote a file and then read it , it was working fine. I think due to caching. When I unmounted the share and remounted, I wasn't able to read the same file anymore.

**Comment by ffilz** [comment]
At first I did a write then a read, and then considering possible caching, I did unmount and mount again and was able to cat the file.

Could you try on next?

**Comment by rakesh-roshan** [comment]
I am seeing this difference between the packets for success using 2.7.6 ganesha server and for failure using 3.5 ganesha server with the UDP patch applied.  In case of failure the reply is 2 bytes shorter. 

The contents of the file is simple text `hello`

```
#### SUCCESS
22:57:17.335873 IP (tos 0x0, ttl 255, id 6716, offset 0, flags [DF], proto UDP (17), length 164)
    ip-10-10-1-235.corp.rosrake.com.nfs > 10.10.1.155.885: NFS reply xid 2718295850 reply ok 136 read REG 664 ids 1000/1000 sz 6 nlink 1 rdev 0/0 fsid 0 fileid 7534 a/m/ctime 1623792780.311000000 1623792780.311000000 1623792780.311000000 6 bytes EOF 
        0x0000:  4500 00a4 1a3c 4000 ff11 4973 0a0a 01eb  E....<@...Is....
        0x0010:  0a0a 019b 0801 0375 0090 183b a205 e72a  .......u...;...*
        0x0020:  0000 0001 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000 0000 0000 0000 0000 0001 0000 0001  ................
        0x0040:  0000 01b4 0000 0001 0000 03e8 0000 03e8  ................
        0x0050:  0000 0000 0000 0006 0000 0000 0000 0006  ................
        0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0070:  0000 0000 0000 7534 60c9 1c8c 1289 7bc0  ......u4`.....{.
        0x0080:  60c9 1c8c 1289 7bc0 60c9 1c8c 1289 7bc0  `.....{.`.....{.
        0x0090:  0000 0006 0000 0001 0000 0006 6865 6c6c  ............hell
        0x00a0:  6f0a 0000 0000 0000 0000 0000 0000 0000  o...............
        0x00b0:  0000 0000                                ....


#### FAILURE
22:54:45.208084 IP (tos 0x0, ttl 255, id 54143, offset 0, flags [DF], proto UDP (17), length 162)
    ip-10-10-1-235.corp.rosrake.com.nfs > 10.10.1.155.885: NFS reply xid 2667964202 reply ok 134 read REG 664 ids 1000/1000 sz 6 nlink 1 rdev 0/0 fsid 0 fileid 7534 a/m/ctime 1623792780.311000000 1623792780.311000000 1623792780.311000000 6 bytes EOF 
        0x0000:  4500 00a2 d37f 4000 ff11 9031 0a0a 01eb  E.....@....1....
        0x0010:  0a0a 019b 0801 0375 008e 1839 9f05 e72a  .......u...9...*
        0x0020:  0000 0001 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000 0000 0000 0000 0000 0001 0000 0001  ................
        0x0040:  0000 01b4 0000 0001 0000 03e8 0000 03e8  ................
        0x0050:  0000 0000 0000 0006 0000 0000 0000 0006  ................
        0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0070:  0000 0000 0000 7534 60c9 1c8c 1289 7bc0  ......u4`.....{.
        0x0080:  60c9 1c8c 1289 7bc0 60c9 1c8c 1289 7bc0  `.....{.`.....{.
        0x0090:  0000 0006 0000 0001 0000 0006 6865 6c6c  ............hell
        0x00a0:  6f0a 0000 0000 0000 0000 0000 0000 0000  o...............
        0x00b0:  0000                                     ..
```

**Comment by rakesh-roshan** [comment]
I think I found the issue, 

The issue is at [xdr_nfs23.c](https://github.com/nfs-ganesha/nfs-ganesha/blob/V3.5/src/Protocols/XDR/xdr_nfs23.c#L807). 

The code

```c
struct xdr_uio *xdr_READ3res_uio_setup(struct READ3resok *objp)
{
	struct xdr_uio *uio;
	u_int size = objp->data.data_len;
	/* The size to actually be written must be a multiple of
	 * BYTES_PER_XDR_UNIT
	 */
	u_int size2 = RNDUP(size);
	int i;

	if (size2 != size) {
		/* Must zero out extra bytes */
		for (i = size; i < size2; i++)
			objp->data.data_val[i] = 0;
	}

	uio = gsh_calloc(1, sizeof(struct xdr_uio) + sizeof(struct xdr_vio));
	uio->uio_release = xdr_READ3res_uio_release;
	uio->uio_count = 1;
	uio->uio_vio[0].vio_base = objp->data.data_val;
	uio->uio_vio[0].vio_head = objp->data.data_val;
	uio->uio_vio[0].vio_tail = objp->data.data_val + size2;
	uio->uio_vio[0].vio_wrap = objp->data.data_val + size2;
	uio->uio_vio[0].vio_length = objp->data.data_len;
	uio->uio_vio[0].vio_type = VIO_DATA;

	/* Take over read data buffer */
	objp->data.data_val = NULL;
	objp->data.data_len = 0;

	LogFullDebug(COMPONENT_NFS_V4,
		     "Allocated %p, references %"PRIi32", count %d",
		     uio, uio->uio_references, (int) uio->uio_count);

	return uio;
}
```

The statement `uio->uio_vio[0].vio_length = objp->data.data_len;` seems to be the issue. `size2` is being computed to follow the rule `The size to actually be written must be a multiple of BYTES_PER_XDR_UNIT`. Even the `tail` and `wrap` is being computed based on `size2`. 

When I changed the statement to `uio->uio_vio[0].vio_length = size2;`, it fixed the read issue.

Can you please verify if that is a correct fix or not?

**Comment by boulos** [comment]
Good catch!

**Comment by ffilz** [comment]
Oops... My read must have happened to be a multiple of 4 bytes...

Here's the fix on gerrithub: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/519302

**Comment by agin719** [comment]
I have the same problem in nfs-ganesha 3.3-stable, how to fix this problem?
