### ISSUE TITLE
The nfs-ganesha server cannot be accessed for 5 minutes?

### ISSUE THREAD

**Issue by Liam-program** [nfs-ganesha/nfs-ganesha#719]
testing scenarios:
There is a ceph cluster to provide file storage services.
There are two storage nodes with nfs service enabled on the ceph cluster. 
FSAL {
        Name = CEPH;
     }

The ceph cluster file system has an export directory: /ly5/
The export directory /ly5 is mounted on two clients through different nfs servers.

client 1(101.101.5.103)  --> nfs-ganesha server 1 (101.101.5.26) --> /ly5/
client 2(101.101.8.101)  --> nfs-ganesha server 2 (101.101.5.27) --> /ly5/

www.test26.com:/ly5 on /subway/shiyi1 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=101.101.8.101,local_lock=none,addr=101.101.5.27)
www.test26.com:/ly5 on /mnt/ly1 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=101.101.5.103,local_lock=none,addr=101.101.5.26)

question:
Stop the nfs service on nfs-ganesha server 2 when two clients are reading and writing files through vdbench, the client 2 cannot write and read. 
But client 1 can't read and write files either, recover in five minutes.
So I want to know why client 1 will be affected and no related logs can be found. How can i analyze this problem?

The nfs-ganesha version is 3.3

**Comment by dang** [comment]
CephFS is a clustered filesystem, and Ganesha is a CephFS client, so the two Ganesha instances are affecting each other through CephFS.  I'm not an expert on CephFS, but I know there are CAPs that clients get that allow read and/or write access to files, and the MDS communicates with the clients to give and take these CAPs.  If the Ganesha that goes down has a CAP that the other Ganesha needs, it can't give it up, because it's down, so it has to wait for the MDS to time it out.  This timeout has to be longer than the NFS Grace period, so that the Ganesha can be restarted, and recover it's NFS clients before the CAPs time out.

I would imagine that the client timeout for CephFS is configurable.

**Comment by Liam-program** [comment]
> CephFS is a clustered filesystem, and Ganesha is a CephFS client, so the two Ganesha instances are affecting each other through CephFS. I'm not an expert on CephFS, but I know there are CAPs that clients get that allow read and/or write access to files, and the MDS communicates with the clients to give and take these CAPs. If the Ganesha that goes down has a CAP that the other Ganesha needs, it can't give it up, because it's down, so it has to wait for the MDS to time it out. This timeout has to be longer than the NFS Grace period, so that the Ganesha can be restarted, and recover it's NFS clients before the CAPs time out.
> 
> I would imagine that the client timeout for CephFS is configurable.

Thank you for your reply. I found the code for this time setting from the reclaim_reset function.
ceph_set_session_timeout(export->cmount, 300);
This time is 300s, and it can not be configured.
How can I flexibly set this time?

**Comment by dang** [comment]
I don't know, sorry.  I don't know cephfs code well.  @jtlayton ?  Ideas?

**Comment by jtlayton** [comment]
That is not intended to be modifiable, as it's governing how long the MDS will wait before giving up on the Ceph client that has gone away. The rados_cluster solution is predicated on the idea that a replacement server for any of the heads will quickly be resurrected. If your node goes down and doesn't come back, then this is behaving as expected.

EDIT: If you're doing a planned takedown of one of the nodes, you should take it out of the cluster just before you shut down (using ganesha-rados-grace command).

**Comment by Liam-program** [comment]
> That is not intended to be modifiable, as it's governing how long the MDS will wait before giving up on the Ceph client that has gone away. The rados_cluster solution is predicated on the idea that a replacement server for any of the heads will quickly be resurrected. If your node goes down and doesn't come back, then this is behaving as expected.
> 
> EDIT: If you're doing a planned takedown of one of the nodes, you should take it out of the cluster just before you shut down (using ganesha-rados-grace command).

Thank you so much, I haven't used this ganesha-rados-grace command. Is there any documentation about the related commands?

**Comment by jtlayton** [comment]
There are manpages that document the commands, including ganesha-rados-grace, and a sample config in the distribution with comments documenting the settings you'll want for a typical cluster. There are also some blog posts here that describe some of this:

https://jtlayton.wordpress.com/2018/12/10/deploying-an-active-active-nfs-cluster-over-cephfs/

**Comment by Liam-program** [comment]
> CephFS is a clustered filesystem, and Ganesha is a CephFS client, so the two Ganesha instances are affecting each other through CephFS. I'm not an expert on CephFS, but I know there are CAPs that clients get that allow read and/or write access to files, and the MDS communicates with the clients to give and take these CAPs. If the Ganesha that goes down has a CAP that the other Ganesha needs, it can't give it up, because it's down, so it has to wait for the MDS to time it out. This timeout has to be longer than the NFS Grace period, so that the Ganesha can be restarted, and recover it's NFS clients before the CAPs time out.
> 
> I would imagine that the client timeout for CephFS is configurable.

I learned about the code for exiting the ganesha service normally, the code has already called the function release().
The function ceph_shutdown(export->cmount) in 'release()' will release CAPS.
So why can't another node get caps?

**Comment by ffilz** [comment]
Closing for lack of response and it seems like it's actually a question for how Ceph works and is thus outside the scope of the nfs-ganesha project.
