### ISSUE TITLE
source-less PDF files (please convert to Markdown)

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/nfs-ganesha#72]
The following PDF files are generated from unknown sources which are missing from the source tree:

  * src/Docs/ganesha_logging.pdf
  * src/Docs/nfs-ganesha-adminguide.pdf

Since there are no graphics or images in those files I suggest converting 'em to _markdown_ format.

File `src/Docs/nfs-ganesha-userguide.pdf` apparently generated from `src/Docs/nfs-ganesha-userguide.rtf` but perhaps both of them could benefit from conversion to Markdown as well.

FYI pre-built source-less binaries are non-DFSG-compliant and therefore non-distributable in Debian...

**Comment by ffilz** [comment]
These are obsolete and have been removed.
