### ISSUE TITLE
rgw_readdir stuck in V3.4

### ISSUE THREAD

**Issue by Hearzzhen** [nfs-ganesha/nfs-ganesha#723]
Ganesha Version: 3.4

Steps: 
      

1. Mount to ceph cluster by using FSAL_RGW.  mount -t nfs4 10.4.128.46:/mnt/cephfs /home/cephfs
2. Creating 10000 files by vdbench, the structure is as follows(Bucket1 is mount bucket):   anchor=/home/cephfs/Bucket1/single4KTest_Ganesha_rgwnfs_2,depth=2,width=10,files=100,size=64K,openflags=o_direct 
3. When Step2 complete, run 'ls', in /home/cephfs/Bucket1/single4KTest_Ganesha_rgwnfs_2, there was a stuck situation. 

- My opinion:
     Ganesha log shows when readdir reaches vdb.1_8.dir, it enters an endless loop. I checked the ceph-rgw log and code，I found when ganesha‘s readdir request arrives, ceph-rgw read 1000 files at a time, read up to 9 times and return the results to ganesha, and ganesha sends the request again. But vdb.1_8.dir was returned to ganesha the first time, and the ganesha has added into the avltree, when the second request, vdb.1_8.dir was returned again, because the contents of this directory were not completely read at last time. Ganesha think it's a collision old chunk, mark it as DIR_TERMINATE, and rescan, so resend readdir request to ceph-rgw, caused an endless loop.
    When I add the following code :
+                       return DIR_CONTINUE;
in function src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c::mdc_readdir_chunk_object, in this situation:
    `if (new_dir_entry->ck == state->cookie) {
			/* This is the cookie we were looking for, but we want
			 * the next dirent */
			state->first_hit = true;
                     +   return DIR_CONTINUE;
     } `
     This problem is disappeared. And It looks like there is no problem anymore. But I am not sure if this modification is feasible.

Ganesha configured as follows:
`NFS_CORE_PARAM {
        mount_path_pseudo = true;
        Protocols = 3,4;
}

EXPORT_DEFAULTS {
        Access_Type = RW;
}

MDCACHE {
        Dir_Chunk = 512;
}

EXPORT {
        Export_Id = 1234;

        Path = /;

        Pseudo = /mnt/cephfs;

        Protocols = 3,4;

        Access_Type = RW;

        Squash = No_Root_Squash;

        FSAL {
                Name = RGW;
                User_id = "test1";
                Access_Key_Id = "XZPIQ796DHLSS2T5F2G2";
                Secret_Access_Key = "bTRAozbHjjHeecDAYWB9gwPgkr7Ppq4PYhiq00Be";
        }
}

RGW {
        ceph_conf = /etc/ceph/ceph.conf;
        cluster = ceph;
        name = client.rgw.ceph2.rgw0;
}

LOG {
        Default_Log_Level = WARN;

        Facility {
                name = FILE;
                destination = "/var/log/ganesha.log";
                enable = active;
        }
}`

**Comment by ffilz** [comment]
Is this still an issue we need to look at?

**Comment by Hearzzhen** [comment]
Yes, this issue still exist. But I modified the code as follows:

In src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:

`
--- a/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c
+++ b/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c
@@ -2289,6 +2289,7 @@ mdc_readdir_chunk_object(const char *name, struct fsal_obj_handle *sub_handle,
                        /* This is the cookie we were looking for, but we want
                         * the next dirent */
                        state->first_hit = true;
+                       return DIR_CONTINUE;
                } else if (state->first_hit) {
                        /* We have found the dirent the caller wanted */
                        LogFullDebugAlt(COMPONENT_NFS_READDIR,
`
The issue seems to be solved. 
Please review this code.

**Comment by ffilz** [comment]
Could you submit a patch via gerrithub as described in src/CONTRIBUTING_HOWTO.txt

**Comment by Hearzzhen** [comment]
OK. I have submitted the patch in following link:
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/526076
Please review, thanks!

**Comment by ffilz** [comment]
Thanks, we'll review that and we should be able to get it into rc2 next week.

**Comment by ffilz** [comment]
Looks good, that will go into rc2. Thanks for the submission.
