### ISSUE TITLE
High memory consumption while using gluster with ganesha 3.5.11

### ISSUE THREAD

**Issue by rafikc30** [nfs-ganesha/nfs-ganesha#724]
We are running NFS-Ganesha's latest version 3.5.11 with gluster vfs. We are experiencing high memory usage with mainly write fops, our file size ranges from 1-64k. 3 Client machine is accessing the share and the application writes the data with 4 threads.

>  PID|USER|PR|NI|VIRT|RES|SHR|S|%CPU|%MEM|TIME+|COMMAND
>  ----|------|---|--|-----|----|-----|--|------|--------|-------|-------------
>  3431|root|20|0|10.489g|5.555g|13804|S|0.680|35.50|58:37.08|/usr/bin/ganesha.nfsd 

The RES memory consumption is around 5.5g, among them, 296MB is used by gluster. I have verified the gluster memory consumption using the gluster [state dump](https://gluster.readthedocs.io/en/latest/Troubleshooting/statedump/) 

So, I'm wondering if there is any memory leak in the Ganesha process. Please guide me in case if I can help in any way to debug the memory leak if any. We are using the following binary's from upstream and our operating system is openSUSE

> nfs-ganesha-vfs-3.5-11.1.x86_64
>nfs-ganesha-gluster-3.5-11.1.x86_64
>nfs-ganesha-3.5-11.1.x86_64

Any help is much appreciated.

**Comment by ffilz** [comment]
If you can run Ganesha with valgrind/massif that can help determine where the memory is going.

We have in the past had issues where any attempt to understand the memory use suggested there wasn't that much memory in use, which made it seem like unused pages weren't being released (so they still count against the process). I don't know if there's fragmentation so all the pages are utilized even though each has plenty of space or if the sub-allocator isn't returning them to the kernel.

**Comment by rafikc30** [comment]
Thanks, @ffilz . I will run the process against Valgrind and will share the details

**Comment by Mr-Chengcheng** [comment]
@ffilz hello , Is my command correct ?:
valgrind  --leak-check=full --show-leak-kinds=all  /usr/bin/ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /etc/ganesha/ganesha.conf -N NIV_EVENT

result:
![9cd663afd652ecf5665d27076438fcc](https://user-images.githubusercontent.com/54385902/124913265-82ec5100-e021-11eb-99ce-812cd1bcc8cd.png)

**Comment by Mr-Chengcheng** [comment]
@ffilz       ganesha.nfsd -v
NFS-Ganesha Release = V3.4

![image](https://user-images.githubusercontent.com/54385902/124913553-d52d7200-e021-11eb-9bf6-9e731767a73d.png)

**Comment by rafikc30** [comment]
@Mr-Chengcheng Are you using Ganesha with glusterfs?

**Comment by Mr-Chengcheng** [comment]
> @Mr-Chengcheng Are you using Ganesha with glusterfs?

YES

**Comment by ffilz** [comment]
What is your config? It looks like you may have a lot of mdcache entries with ACLs.

It would also be worth looking into the massif tool which can capture memory use at a point in time while Ganesha is still running, and will break out the largest users.

From the output above though, looks like various hash tables are huge.

Are there any details on the possibly lost memory? All the still reachable memory looks fine.

**Comment by rafikc30** [comment]
@ffilz I tried to capture the massif output. I'm not sure I did it right, please let me know if I need to capture it again.
[massif.tar.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/6820970/massif.tar.gz)

**Comment by ffilz** [comment]
Looks like you're missing nfs-ganesha debug information which makes the Ganesha part of the massif stack dumps less useful.

Looks like huge amounts of Gluster memory allocations, but not quite sure what they're associated with yet.

**Comment by Mr-Chengcheng** [comment]
[mass-output.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/6829677/mass-output.txt)
@ffilz this is massif out，but from these proofs, it is difficult to analyze how glusterfs causes high memory usage in Ganesha

**Comment by ffilz** [comment]
mass-output.txt just seems to show during initialization time. I'm not quite sure why the ACL hash table is allocating so much, but what will be more useful is to see the memory growth as Ganesha is running and serving up files.

**Comment by rafikc30** [comment]
@ffilz I again tried after installing debug packages from Ganesha. But still, the output does not have the complete backtrace. Should I do something more, like enabling some options?

Do you have any kind of documentation for capturing massif output with Ganesha?
I can also do a source installation if that helps. Please share any doc to source install the Ganesha in case if you have it handy.

**Comment by Mr-Chengcheng** [comment]
> @ffilz I again tried after installing debug packages from Ganesha. But still, the output does not have the complete backtrace. Should I do something more, like enabling some options?
> 
> Do you have any kind of documentation for capturing massif output with Ganesha?
> I can also do a source installation if that helps. Please share any doc to source install the Ganesha in case if you have it handy.

https://www.valgrind.org/docs/manual/ms-manual.html    //It can be used as a reference for massif

**Comment by Mr-Chengcheng** [comment]
@ffilz hello， when ganesha is running and serving up files，the results show that it is also very difficult to analyze where the memory problem is
[massif.out.24852.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/6854602/massif.out.24852.txt)

**Comment by ffilz** [comment]
> 
> 
> @ffilz hello, vargrind execution result display ，the initial part of the space is not released, although it is small

We should clean those up, but those aren't leaks that impact running, they are just a few bits that aren't properly cleaned up on exit.

**Comment by rafikc30** [comment]
@Mr-Chengcheng  I'm still chasing the problem with the memory leak. Do you have any luck figuring out the problem?

**Comment by rafikc30** [comment]
@ffilz When I test a simple file create, read and delete in a loop for the same number of files with same filename, the memory keep constants. But if I use just file create with different names without delete, the memory keeps on increasing. Do you see any probably issues with Ganesha caching or something?

**Comment by rafikc30** [comment]
@ffilz 
I reproduced again, but this time with proper symbols and a more detailed massif output. I even used an output visualizer to read. These tools suggested some memory consumption. I'm looking from gluster perspective, and I found that the memory utilization from the gluster stacks is constant across snapshots.  But the a leak from ganesha is increasing from snapshot to snapshot. On the final snapshot 11.2 GB out of 15GB is from a backtrace leading to an opendir call.

Looking at the ganesha code, I suspect a readdir dirents from the function `fs_rm_revoked_handles`, they doesn't seems to be deallocating. But the tool is suggesting the leak from opendir.
[massif-test.log](https://github.com/nfs-ganesha/nfs-ganesha/files/7186114/massif-test.log)


The suspected leak from the visualizer looks like
![Screenshot from 2021-09-17 18-08-56](https://user-images.githubusercontent.com/3429960/133793204-02987186-02d6-4d1f-af1a-2792d9219ec7.png)

The backtrace of the leak is

n3: 16620220416 (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
 n4: 16416108544 0x5514973: mmap (in /lib64/libc-2.26.so)
  n2: 9932111872 0x54A0DA8: new_heap (in /lib64/libc-2.26.so)
   n1: 7784628224 0x54A376C: sysmalloc (in /lib64/libc-2.26.so)
    n1: 7784628224 0x54A4697: _int_malloc (in /lib64/libc-2.26.so)
     n1: 7784628224 0x54A5EF6: malloc (in /lib64/libc-2.26.so)
      n1: 7784628224 0x54E267B: __alloc_dir (in /lib64/libc-2.26.so)
       n1: 7784628224 0x54E278C: opendir_tail (in /lib64/libc-2.26.so)
        n1: 7784628224 0x4CC0F2B: fs_rm_revoked_handles (recovery_fs.c:311)
         n1: 7784628224 0x4CC121F: fs_rm_clid_impl (recovery_fs.c:382)
          n1: 7784628224 0x4CC1386: fs_rm_clid (recovery_fs.c:405)
           n1: 7784628224 0x4CBBE8B: nfs4_rm_clid (nfs4_recovery.c:629)
            n1: 7784628224 0x4CB2807: nfs_client_id_expire (nfs4_clientid.c:1116)
             n1: 7784628224 0x4CF8C48: nfs4_op_create_session (nfs4_op_create_session.c:444)
              n1: 7784628224 0x4CF3A95: process_one_op (nfs4_Compound.c:920)
               n1: 7784628224 0x4CF4DD3: nfs4_Compound (nfs4_Compound.c:1327)
                n1: 7784628224 0x4C77DA2: nfs_rpc_process_request (nfs_worker_thread.c:1508)
                 n1: 7784628224 0x57FCDDB: svc_request (in /usr/lib64/libntirpc.so.3.4)
                  n2: 7784628224 0x57FA0D0: svc_rqst_xprt_task_recv (in /usr/lib64/libntirpc.so.3.4)
                   n1: 7449083904 0x57FAC17: svc_rqst_epoll_loop (in /usr/lib64/libntirpc.so.3.4)
                    n1: 7449083904 0x580562E: work_pool_thread (in /usr/lib64/libntirpc.so.3.4)
                     n1: 7449083904 0x4FFF4F8: start_thread (in /lib64/libpthread-2.26.so)
                      n0: 7449083904 0x5519ECE: clone (in /lib64/libc-2.26.so)
                   n1: 335544320 0x580562E: work_pool_thread (in /usr/lib64/libntirpc.so.3.4)
                    n1: 335544320 0x4FFF4F8: start_thread (in /lib64/libpthread-2.26.so)
                     n0: 335544320 0x5519ECE: clone (in /lib64/libc-2.26.so)

@ffilz  Can you please take a look at the massif output and the backtrace? I'm happy to support you in whatever way possible.

**Comment by rafikc30** [comment]
I ran the work load over the weekend where the memory footprint increased to 57GB [massif-test-second-run.log](https://github.com/nfs-ganesha/nfs-ganesha/files/7193832/massif-test-second-run.log). As you can see on the massif output the same backtrace consuming 52.6GB memory
![Screenshot from 2021-09-20 11-36-54](https://user-images.githubusercontent.com/3429960/133962312-ba366e19-50c2-4400-a657-f20d29faf6bd.png)
.

**Comment by Mr-Chengcheng** [comment]
> I ran the work load over the weekend where the memory footprint increased to 57GB [massif-test-second-run.log](https://github.com/nfs-ganesha/nfs-ganesha/files/7193832/massif-test-second-run.log). As you can see on the massif output the same backtrace consuming 52.6GB memory
> ![Screenshot from 2021-09-20 11-36-54](https://user-images.githubusercontent.com/3429960/133962312-ba366e19-50c2-4400-a657-f20d29faf6bd.png)
> .

What tool do you use for the memory map of IO stack?

**Comment by Mr-Chengcheng** [comment]
> I ran the work load over the weekend where the memory footprint increased to 57GB [massif-test-second-run.log](https://github.com/nfs-ganesha/nfs-ganesha/files/7193832/massif-test-second-run.log). As you can see on the massif output the same backtrace consuming 52.6GB memory
> ![Screenshot from 2021-09-20 11-36-54](https://user-images.githubusercontent.com/3429960/133962312-ba366e19-50c2-4400-a657-f20d29faf6bd.png)
> .

@rafikc30 hi， What tool do you use for the memory map of IO stack?

**Comment by Mr-Chengcheng** [comment]
> @Mr-Chengcheng I'm still chasing the problem with the memory leak. Do you have any luck figuring out the problem?

@rafikc30 ，close  gluster open-behind xlator，can control the rapid growth of memory leakage

**Comment by rafikc30** [comment]
@Mr-Chengcheng Thanks for your suggestion, I'm testing it. I will report my status.
Regarding the tools and command, 
Command used `valgrind --tool=massif --pages-as-heap=yes --time-unit=B --smc-check=all --trace-children=yes --massif-out-file=/var/log/massif-test1.out --max-stackframe=1201018400000 /usr/bin/ganesha.nfsd -F`

visualizer : https://github.com/KDE/massif-visualizer . You may need to source install it.

Please make sure that you installed the debugpackages and sourceinfo package for getting the backtrace. If you can share the output file, that would be great.

**Comment by rafikc30** [comment]
@Mr-Chengcheng  I repeated my testing with the open-behind xlater turned off. It didn't help. I ran the workload over the weekend and the memory reached 87GB. Here is the massif file as well as the backtrace by the virtualization tool.
[massif-test-without-openbehind.log](https://github.com/nfs-ganesha/nfs-ganesha/files/7234405/massif-test-without-openbehind.log)
![Screenshot from 2021-09-27 13-12-11](https://user-images.githubusercontent.com/3429960/134868160-51c1d248-3238-4be9-b86a-707a1e7ee9d0.png)

**Comment by ffilz** [comment]
Where is your NFSv4 recovery directory located? It looks like something wonky is going on with accessing that.

**Comment by rafikc30** [comment]
We are using shared storage hosted by a gluster.

**Comment by ffilz** [comment]
So which FSAL are you using? FSAL_GLUSTER or FSAL_VFS?

**Comment by rafikc30** [comment]
@ffilz We use Gluster FSAL. And for the HA we use ctdb along with the shared storage backed by gluster(an exclusive shared storage) volume mounted via fuse.

**Comment by ffilz** [comment]
I'm at a loss. Red Hat's HA solution for Gluster is based on Pacemaker (and all the bits should be in the upstream repo).

Do you have a recovery directory for each node or virtual IP? I haven't paid attention to exactly how that is accomplished, but the recovery directory code is not prepared to handle multiple nodes worth of data.

**Comment by rafikc30** [comment]
@ffilz We don't have a VIP for each node, We only have one VIP across the cluster. That will be moved when one node is unavailable. Do you think this ctdb + Ganesha config cause problems in terms of memory leak? If you suspect it, I can maybe test it with the physical IP without HA, do you think that is worth trying?

**Comment by ffilz** [comment]
OK, so active/passive setup?

Yes, it would be good to verify everything without HA first, then use the VIP but without failover. Also make sure after failover the directory is accessible from the new node.

**Comment by rafikc30** [comment]
Ok, I will do the testing without HA.  The tests that I have reproduced the memory leak do not have any tests to do the failover. It was just that I was using VIP, but there wasn't any IP failover during the testing.

**Comment by ffilz** [comment]
Bumping to keep this ahead of inactive issues. Also adding need info.

**Comment by ffilz** [comment]
This has lingered in over a year. V4.3 has some improvements that might help, and new LRU management that is expected to help high memory utilization is slated for V5.0 which will be tagged pretty soon. Further, there are newer issues relating to memory utilization.

Closing as a duplicate and indicating try on latest release.
