### ISSUE TITLE
Does Windows 10 upload files to NFS at a maximum speed of 15M/s?

### ISSUE THREAD

**Issue by ZhangErling** [nfs-ganesha/nfs-ganesha#725]
Hello, I'm glad you took the time to look at this issue ! 
This article is a machine translation, may cause dyslexia, please forgive

I have been building a GlusterFS cluster for more than one month. The client uses NFS-Ganesha, but the maximum upload speed on Windows is always 10-15 M/s, which can be full speed on Linux. I can't find relevant instructions online, only some netizens who have built NAS. Indicates that their Windows mount is also around 10M/s, so I left a comment here hoping to get some clarification  

Thanks again for reading, and here's a brief introduction to the GlusterFS cluster 

```
Linux OS：     CentOS Linux release 8.3.2011  
nfs-ganesha：  3.5
glusterfs：    9.2
LAN：          1000Mbps

```
Tomorrow I will try Samba and verify how fast Windows is uploading to it. If it is available at full speed and someone answers this question and confirms that there is no data to prove the Windows NFS upload speed limit, or compatibility issues, I will append more detailed data and logs

**Comment by ffilz** [comment]
Have you compared Linux clients and Windows clients on the same server?

Can you compare Windows clients against a Linux kernel NFS server (maybe just serving a local filesystem)?

**Comment by ZhangErling** [comment]
> Have you compared Linux clients and Windows clients on the same server?
> 
> Can you compare Windows clients against a Linux kernel NFS server (maybe just serving a local filesystem)?



Hello, I'm not using another Linux to access NFS because I don't have any extra machines (just two PCs, Win10 and Centos8).
File system in Linux Docker, NFS in Linux, I use Linux local mount or use Docker mount NFS access can be full speed.

I built an FTP in Linux, Windows access to FTP can be full speed.
Also, I can use iPerf3 bi-directional access to achieve full speed.
Two PCs on the same network segment, with only one gigabit switch between them.
I can't confirm if it was my configuration error or Windows, but I plan to move Linux to my office and use a colleague's Linux to access NFS.

What do you think the probable causes would be that I would examine closely?
thank you

**Comment by ZhangErling** [comment]
I have full-speed access to Samba on Windows, and so far I haven't been able to fix the slow Windows access to NFS-Ganesha  
Since most of my scenarios were accessing glusterfs clusters on Windows, I think my problem has been resolved, thanks for your patience
