### ISSUE TITLE
Does nfs-ganesha 3.3 support file ACL?

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#727]
Does nfs-ganesha support file ACL?  
how about nfs-ganesha 3.3 ?

**Comment by dang** [comment]
Depends on the FSAL you're using.  VFS, GLUSTER, GPFS, LIZARDFS, and PROXY do support ACLs,  and KVSFS, MEM, and RGW do not.  CEPH may or may not, depending on the compile-time options (which depend on the version of Ceph you built against).

**Comment by agin719** [comment]
I use FSAL VFS, and I compile the nfs-ganesha with ENABLE_VFS_DEBUG_ACL, But setfacl is also failed.
compile:
mkdir build; cd build
cmake -DENABLE_VFS_DEBUG_ACL=ON ..
make

setfacl operation:
setfacl -m u:user:rw- test

output is:
setfacl: test: Operation not supported

my ganesha.conf is like that:
EXPORT
{
        Export_Id=2;
        Path = /mnt/vfs;
        Pseudo = /mnt/vfs;
        Squash = No_Root_Squash;
        FSAL {
                Name = VFS;
        }
        CLIENT {
                Access_Type = RW;
                Clients = *;
        }
}

**Comment by dang** [comment]
Keep in mind, the VFS ACL support is for debugging, and is in-memory only (that is, the ACLs are not written to disk, and you will lose them all when Ganesha is restarted).  That said, I haven't use the VFS debug ACLs in a while, and they may have been broken.  I don't see any reason in the code why it would fail with "not supported".  I'd need to see a packet dump to help.  I'll take a look when I get a chance.

**Comment by ffilz** [comment]
Is your client using NFSv3 or NFSv4?

If NFSv3, we don't support the NFSv3 side-band ACL protocol added in the Linux kernel server,

If NFSv4 you need to use nfs4_editfacl, nfs4_getfacl, or nfs4_setfacl from nsf4-acl-tools package

**Comment by ffilz** [comment]
FSAL_VFS doesn't have persistent ACL support, it can be compiled to use in-memory ACLs.

Also, we do not support the NFSv3 side-band protocol for ACLs that Linux knfsd provides

FSAL_GPFS supports NFSv4 ACLs on disk
FSAL_GLUSTER and FSAL_CEPH support POSIX ACLs on disk, converted between POSIX and NFSv4 ACLs by Ganesha
FSAL_LIZARDFS supports ACLs, I don't know enough to know what kind they are
FSAL_PROXY_V4 looks like it supports ACLS
FSAL_PROXT_V3 does not support ACLs unless I'm missing something

**Comment by fangtaozc** [comment]
Under what conditions will the cephfs  exported by NFS Ganesha support nfs4_getfacl.
Thanks.

ceph version 14.2.4.2
NFS-Ganesha Release = V2.8.1.2

[root@u1 mnt]# nfs4_getfacl rook
Operation to request attribute not supported: rook

192.168.170.1:/fs_test01 on /mnt/rook type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.170.1,local_lock=none,addr=192.168.170.1)

**Comment by dang** [comment]
It looks like Ganesha needs to be built with CEPHFS_POSIX_ACL on, and libacl needs to be installed.  There no longer appears to be a Ceph version requirement, which means all supported versions of Ceph have the capability.

**Comment by ffilz** [comment]
FSAL_CEPH will require Ganesha V4.0 to use ACLs. V4.0 is due out soon with rc1 coming this week.

**Comment by ffilz** [comment]
I've added some documentation on ACL support to the wiki but it needs a few more bits filled in before I close this.

**Comment by ffilz** [comment]
OK, ACL documentation is updated. I think this is now clear.
