### ISSUE TITLE
create请求

### ISSUE THREAD

**Issue by DX1268** [nfs-ganesha/nfs-ganesha#728]
NFS client requests NFS-Ganesha service to convert the data into large-endian data, but NFS-Ganesha service receives the data based on the system (in small-endian case), resulting in an inaccurate value, as follows:
（1）NFS client
data->arg.create.createmode = NFS3_CREATE_UNCHECKED;
	if (flags & O_EXCL) {
		data->arg.create.createmode  = NFS3_CREATE_EXCLUSIVE;
		data->arg.create.verifier[0] = cpu_to_be32(jiffies);
		data->arg.create.verifier[1] = cpu_to_be32(current->pid);
	}
（2）NFS-ganesha
void set_common_verifier(struct fsal_attrlist *attrs, fsal_verifier_t verifier)
{
	uint32_t verf_hi = 0, verf_lo = 0;

	memcpy(&verf_hi,
	       verifier,
	       sizeof(uint32_t));
	memcpy(&verf_lo,
	       verifier + sizeof(uint32_t),
	       sizeof(uint32_t));

	LogFullDebug(COMPONENT_FSAL,
		     "Passed verifier %"PRIx32" %"PRIx32,
		     verf_hi, verf_lo);

	if (isDebug(COMPONENT_FSAL) &&
	    (FSAL_TEST_MASK(attrs->valid_mask, ATTR_ATIME) ||
	    (FSAL_TEST_MASK(attrs->valid_mask, ATTR_MTIME)))) {
		LogWarn(COMPONENT_FSAL,
			"atime or mtime was already set in attributes%"
			PRIx32" %"PRIx32,
			(uint32_t) attrs->atime.tv_sec,
			(uint32_t) attrs->mtime.tv_sec);
	}

	attrs->atime.tv_sec = verf_hi;
	attrs->mtime.tv_sec = verf_lo;

	FSAL_SET_MASK(attrs->valid_mask, ATTR_ATIME | ATTR_MTIME);
}

**Comment by ffilz** [comment]
Verifier is opaque so the way Ganesha stores it shouldn't matter. And it only is ever sent by client to be consumed by server, the server never sends the verifier back to the client, so it should always get used by Ganesha in the same byte order.

**Comment by DX1268** [comment]
It may be related to the CPU type of the system, and Crete then calls the setattr file attribute;Create a file on an x86 server and set the atime value of the file setattr to a very large value.Whether can modify like this:
bool check_beorle()  //Determine whether the system is big-endian or small-endian
{
    int a=0x0110;
    char b=*(char*)&a;
    if(b==0x10) {
		return true;
	} 
    return false;
}
void set_common_verifier(struct attrlist *attrs, fsal_verifier_t verifier)
{
	uint32_t verf_hi = 0, verf_lo = 0;
	
	memcpy(&verf_hi,
	       verifier,
	       sizeof(uint32_t));
	memcpy(&verf_lo,
	       verifier + sizeof(uint32_t),
	       sizeof(uint32_t));

	if (isDebug(COMPONENT_FSAL) &&
	    (FSAL_TEST_MASK(attrs->valid_mask, ATTR_ATIME) ||
	    (FSAL_TEST_MASK(attrs->valid_mask, ATTR_MTIME)))) {
		LogWarn(COMPONENT_FSAL,
			"atime or mtime was already set in attributes%"
			PRIx32" %"PRIx32,
			(uint32_t) attrs->atime.tv_sec,
			(uint32_t) attrs->mtime.tv_sec);
	}
	if (check_beorle()) {
		attrs->atime.tv_sec = __be32_to_cpu(verf_hi);
		attrs->mtime.tv_sec = __be32_to_cpu(verf_lo);
	} else {
		attrs->atime.tv_sec = verf_hi;
		attrs->mtime.tv_sec = verf_lo;
	}

	FSAL_SET_MASK(attrs->valid_mask, ATTR_ATIME | ATTR_MTIME);
}

**Comment by ffilz** [comment]
Endianness shouldn't matter.

check_verifier (stat or attrlist) does the same memcpy into verf_hi and verf_lo, and then compares to atime and mtime

Since the same memcopy into a uint32_t from the request is being done, that uint32_t value should ultimately compare identical to what was assigned

**Comment by ffilz** [comment]
The only way for endianess to matter is if the value was set on a machine of one endianess and checked on a machine of the other.

**Comment by DX1268** [comment]
Thank you very much
