### ISSUE TITLE
Error: Read-only file system

### ISSUE THREAD

**Issue by devopswise** [nfs-ganesha/nfs-ganesha#734]
Hi there,

Thanks for this good piece of software.
I am suffering from a mount problem for a couple of days.
I can mount NFS share served by nfs-ganesha but it is always read-only. I am getting:

```
srvprex03:/var/tmp# touch mnt/sample_file
touch: mnt/sample_file: Read-only file system
```

**Here is my setup:**
I am using nfs-ganesha v3.2. All commands on this issue has run by root user unless specified.
I have put nfs-ganesha on docker container: here is my [Dockerfile](https://github.com/devopswise/nfs-ganesha/blob/master/Dockerfile), here is my [docker-compose.yml](https://github.com/devopswise/nfs-ganesha/blob/master/docker-compose.yml)

here is my ganesha.conf: I've tried many other options with no lock

```
EXPORT
{
		# Export Id (mandatory, each EXPORT must have a unique Export_Id)
		Export_Id = 77;

		# Exported path (mandatory)
		Path = /export;

		# Pseudo Path (for NFS v4)
		Pseudo = /;

		# Access control options
		Access_Type = RW;
		#Squash = No_Root_Squash;
		Root_Access = "*";
		Access = "*";

		# NFS protocol options
		Transports = "UDP,TCP";
		Protocols = "3,4";

		SecType = "none";

		# Exporting FSAL
		FSAL {
			Name = VFS;
		}
}
```
It is worth adding my I am on Alpine Linux, an it is aarch64. (I have tried same config/docker image on ubuntu/x86_64 as well)

I am mounting with following command:
```
srvprex03:~# mount.nfs 127.0.0.1:/ mnt -o nfsvers=4,proto=tcp,rw,noatime,sync
srvprex03:~# cat /proc/mounts | grep nfs
127.0.0.1:/ /var/tmp/mnt nfs4 rw,sync,noatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1 0 0

```

nfs-ganesha command line and other processes running inside container:
```
root@2e32a472be09:/# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 22:16 ?        00:00:14 /usr/bin/ganesha.nfsd -F -L /dev/stdout -f /etc/ganesha/ganesha
_rpc        10     1  0 22:16 ?        00:00:00 rpcbind
statd       12     1  0 22:16 ?        00:00:00 rpc.statd -L
message+    19     1  0 22:16 ?        00:00:00 dbus-daemon --system --fork
root       373     0  6 22:56 pts/0    00:00:00 bash
root       381   373  0 22:56 pts/0    00:00:00 ps -ef
```

container's status:
```
srvprex03:/var/source/nfs-ganesha# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED             STATUS             PORTS                                                                                                                            NAMES
2e32a472be09   devopswise/nfs-ganesha:latest   "/start.sh"              About an hour ago   Up About an hour   0.0.0.0:111->111/tcp, 0.0.0.0:662->662/tcp, 0.0.0.0:2049->2049/tcp, 0.0.0.0:38465-38467->38465-38467/tcp, 0.0.0.0:111->111/udp   nfs-ganesha
```

I have collected some logs as well:

[My nfs-ganesha startup logs](https://gist.github.com/devopswise/b6cf2cb6771f70f53742eb2bdcbc8dc8)
[Logs when I try to create file](https://gist.github.com/devopswise/de9fd21c09bc1e89988df0ff8c9f1cf9) (touch)

Many Thanks, in advance
Onur

**Comment by dang** [comment]
So, the export doesn't have write permissions, so write attempts are failing.  I'm not seeing how the write permissions are being disabled in the code.  Frank is the expert on this portion of the code, but he's off this week, so if I can't figure this out, he might be able to when he gets back.

My best guess is that it's related to permissions of the container.  Could you make the container privileged as a test, and see if that fixes the problem?

**Comment by devopswise** [comment]
Hello @dang 
Many thanks it is working now. 
Running container in privileged mode is not an issue for my setup.

**Comment by dang** [comment]
Good to know, glad it's working.
