### ISSUE TITLE
nfs-ganesha hung 

### ISSUE THREAD

**Issue by guol-fnst** [nfs-ganesha/nfs-ganesha#735]
Environmen:
Centos7.2 glusterfs5.13+nfs-ganesha2.7 
This log are the same to issue(https://github.com/nfs-ganesha/nfs-ganesha/issues/463)

My mountpoint was hung. And the only way is to restart ganesha.
I think these warnings are not only warning ,but also error.

Can anyone figure out this problem?

**Comment by ffilz** [comment]
These warnings are probably just one of the symptoms of your hang.

We need more information, a tcpdump trace might help, enabling some debug might help, but it would help to start with any information you can give as to what activity led to the hang. Also, how repeatable is the hang?

**Comment by ffilz** [comment]
I just noticed this is very old Ganesha. Please try on V3.5 or V4-rc1.

**Comment by ffilz** [comment]
Closing since there has been no response in more than 30 days.
