### ISSUE TITLE
nfs-ganesha crash after glfs segfault

### ISSUE THREAD

**Issue by Volemon** [nfs-ganesha/nfs-ganesha#737]
**Background information**
nfs-ganesha: 3.4
glusterfs: 9.3
system: Debian 10 

**Description**
We are running nfs-ganesha 3.4 with glusterfs 9.3 and get ganesha crashes with following errors in journal.
In ganesha log there are only standard initalizing informations -> ganesha is automaticaly started after crash by pacemaker. 

**steps to reproduce**
Unfortunately issue seems to be rather random so I can't provide any reproduction steps. 

**related logs**

journal:
```
Aug 27 18:15:36 storage2 kernel: glfs_epoll00b[48927]: segfault at 28 ip 00007fcea3fef489 sp 00007fce8b7fcef0 error 4 in shard.so[7fcea3fcf000+24000]
Aug 27 18:15:36 storage2 kernel: Code: 00 48 89 44 24 38 31 c0 48 8b 85 d8 01 00 00 48 c7 44 24 20 00 00 00 00 48 c7 44 24 28 00 00 00 00 48 c7 44 24 30 00 00 00 00 <4c> 8b 78 28 8b 45 00 85 c0 0f 88 87 00 00 00 4c 8b 25 11 eb 00 00
Aug 27 18:15:36 storage2 systemd[1]: nfs-ganesha.service: Main process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit nfs-ganesha.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 11.
Aug 27 18:15:36 storage2 systemd[1]: nfs-ganesha.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit nfs-ganesha.service has entered the 'failed' state with result 'signal'.
```
ganesha.log
```
27/08/2021 08:46:08 : epoch 612889d6 : storage2 : ganesha.nfsd-48880[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
27/08/2021 18:15:42 : epoch 61290fae : storage2 : ganesha.nfsd-23247[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 3.4
27/08/2021 18:15:42 : epoch 61290fae : storage2 : ganesha.nfsd-23248[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
27/08/2021 18:15:42 : epoch 61290fae : storage2 : ganesha.nfsd-23248[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
27/08/2021 18:15:42 : epoch 61290fae : storage2 : ganesha.nfsd-23248[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
```

**Comment by dang** [comment]
Unfortunately, there's not enough information here for us to do anything.  Can you get a backtrace, with debuginfo installed?  I don't know how to do this on Debian (I'm a Fedora user), but there should be easy docs to follow.

**Comment by Volemon** [comment]
Thanks, I will provide backtrace after getting next SEGV.

**Comment by Volemon** [comment]
I used coredump with dbgsym packages installed and this is what i got:
```
[New LWP 28090]
[New LWP 28451]
Cannot access memory at address 0x7f60c5a1b168
Cannot access memory at address 0x7f60c5a1b160
Failed to read a valid object file image from memory.
Core was generated by `/usr/bin/ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /etc/ganesha/ganesha.c'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f60b79fdae4 in ?? ()
[Current thread is 1 (LWP 27922)]
```
I have never used gbd before so i'm not sure if it's proper output.

**Comment by dang** [comment]
If the proper debug symbols are installed, then the line "#0 ??" will have a function name and arguments.  At that point, you can issue the "bt" command (or "backtrace", which is the full command name) and it will print a list #0 function, #1 function, and so on, listing the callpath of function names that got us to the crash point.  It should also include line numbers.

**Comment by ffilz** [comment]
We are in the final stages of V4.0 release candidate. It would be nice to address this in the next week or two, otherwise it will be held for potential inclusion in V4.1 or later depending on when we are able to come to a resolution.

Unfortunately currently there is nothing for us to go on, we need at a minimum a stack back trace with proper debug information so we can determine where the error occurs.

**Comment by ffilz** [comment]
Since we have had no response in over 30 days and we have nothing to go on, I will close this. Please re-open if you can respond with more information.
