### ISSUE TITLE
Different return codes

### ISSUE THREAD

**Issue by BobocIonutGabriel** [nfs-ganesha/nfs-ganesha#738]
https://github.com/nfs-ganesha/nfs-ganesha/blob/be092f7e5ea7f17d3f17dc0ee5020243845c44b9/src/scripts/ganeshactl/ganesha_mgr.py#L41

Hi,

Shouldn't the tool `ganesha_mgr` return different codes based on the operation success/failure ?

Ex:
Right now it doesn't matter if an export was added/removed successfully the tool returns with exit code 0.

**Comment by ffilz** [comment]
I don't know if we have anyone who really understands the dbus stuff anymore. I'm really not clear how the error reporting for dbus commands works.

**Comment by ffilz** [comment]
Bump to keep live issues on first page

**Comment by ffilz** [comment]
With no response on this in over 30 days and no one actively participating in the community who really understands ganesha_mgr, I am going to close this.
