### ISSUE TITLE
Stale file handle error 

### ISSUE THREAD

**Issue by itfanr** [nfs-ganesha/nfs-ganesha#74]
```
	i = ceph_ll_get_inode(export->cmount, *vi);
	if (!i)
		return ceph2fsal_error(-ESTALE);
```

The function `ceph_ll_get_inode `gets Inode from inodemap , that is , cache of ceph. However , the nfs client may encounter a Stale file hanle error .

You'd  better call  `ceph_ll_lookup_inode`  before return ESTALE.

**Comment by mattbenjamin** [comment]
Yes, I agree.  Thanks for reporting it.
