### ISSUE TITLE
systemctl reload nfs-ganesha doesnt work

### ISSUE THREAD

**Issue by yocalebo** [nfs-ganesha/nfs-ganesha#747]
Running debian 11 using kernel `5.10.70` and with nfs-ganesha version `3.4-1`. 

Using a simple config:
```
EXPORT {
    Export_Id = 1;
    Path = /mnt/cargo/nfstest01;
    Tag = mnt/cargo/nfstest01;
    Pseudo = /nfstest01;
    Protocols = 3, 4;
    Transports = TCP;
    Access_Type = RW;
    Squash = None;
    FSAL {
        Name = VFS;
    }
}
```

Changing the `Pseudo` entry to `/mnt/cargo/nfstest01` and then `systemctl reload nfs-ganesha` produces the following errors in the log file:
```
11/10/2021 09:13:20 : epoch 61646285 : scale01.home.net : ganesha.nfsd-20519[sigmgr] sigmgr_thread :MAIN :EVENT :SIGHUP_HANDLER: Received SIGHUP.... initiating export list reload
11/10/2021 09:13:20 : epoch 61646285 : scale01.home.net : ganesha.nfsd-20519[sigmgr] export_commit_common :CONFIG :CRIT :Pseudo for export update 1 /mnt/cargo/nfstest01 doesn't match /nfstest01
11/10/2021 09:13:20 : epoch 61646285 : scale01.home.net : ganesha.nfsd-20519[sigmgr] release_posix_file_system :FSAL :WARN :Filesystem /mnt/cargo/nfstest01 is still claimed
11/10/2021 09:13:20 : epoch 61646285 : scale01.home.net : ganesha.nfsd-20519[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:14): 1 validation errors in block EXPORT
11/10/2021 09:13:20 : epoch 61646285 : scale01.home.net : ganesha.nfsd-20519[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:14): Errors processing block (EXPORT)
```

The underlying filesystem is ZFS, if that makes any difference.
```
NAME                   USED  AVAIL     REFER  MOUNTPOINT
cargo/nfstest01        96K   5.98G     96K    /mnt/cargo/nfstest01
```

This doesn't seem to be related to the `Pseudo` parameter either. Here is me trying to remove the `Tag` entry and then doing `systemctl reload nfs-ganesha`
```
11/10/2021 09:17:13 : epoch 6164636b : scale01.home.net : ganesha.nfsd-21939[sigmgr] sigmgr_thread :MAIN :EVENT :SIGHUP_HANDLER: Received SIGHUP.... initiating export list reload
11/10/2021 09:17:13 : epoch 6164636b : scale01.home.net : ganesha.nfsd-21939[sigmgr] export_commit_common :CONFIG :CRIT :Tag for export update 1 (null) doesn't match mnt/cargo/nfstest01
11/10/2021 09:17:13 : epoch 6164636b : scale01.home.net : ganesha.nfsd-21939[sigmgr] release_posix_file_system :FSAL :WARN :Filesystem /mnt/cargo/nfstest01 is still claimed
```

The only way to make this work is to `systemctl restart nfs-ganesha` which is unfortunate. I'm hoping I'm missing something obvious or there is a more proper way of doing the above.

**Comment by dang** [comment]
In 3.x, you cannot change the pseudo path of an export, you need to restart Ganesha for that.  This has been changed in next, and it's now allowed.  That feature will be available in 4.0.

The unclaimed warning isn't causing an error, because Ganesha just unclaims the FS after emitting that warning.  I'm not sure why the FS is still claimed, Frank is the expert in that code. However that's not a fatal error, the reconfig should have succeeded.

**Comment by yocalebo** [comment]
> In 3.x, you cannot change the pseudo path of an export, you need to restart Ganesha for that. This has been changed in next, and it's now allowed. That feature will be available in 4.0.
> 
> The unclaimed warning isn't causing an error, because Ganesha just unclaims the FS after emitting that warning. I'm not sure why the FS is still claimed, Frank is the expert in that code. However that's not a fatal error, the reconfig should have succeeded.

Brilliant, thanks for the information. Unfortunately, when changing this and issuing a `systemctl reload nfs-ganesha` I'm unable to mount the export anymore. I have to revert `ganesha.conf` to what it was before I made any changes and then issue  a `systemctl restart nfs-ganesha` before I'm able to mount again on the client.

**Comment by ffilz** [comment]
I think there were some bugs in the file system claiming. I'd have to do some debugging on Ganesha V3 to see what the exact issue is and if a reasonable fix can be made. Tag also can not be changed in V3 (I'm actually not sure it will be changeable in V4, but actually no one really needs to use Tag, it's for a specific use case that was never fully realized - we should deprecate it...).

**Comment by yocalebo** [comment]
Thanks for the explanation, this is expected behavior for the version we're using so I'll close this out.
