### ISSUE TITLE
Stale file handle when using nfs-ganesha with BeeGFS (FSAL_VFS)

### ISSUE THREAD

**Issue by PopiBrossard** [nfs-ganesha/nfs-ganesha#748]
Dear maintainer,

When using nfs-ganesha to export in NFSv4 a beegfs mount, I (randomly ?) get errors about "Stale File Handle". I don't think it's the same as #479 because I'm facing this error when accessing some directories, not during the mount process.

It's not immediatly after starting the NFS server, but when trying to access some files or directories the NFS client get a "Stale File handle" error. A reboot of the NFS server seems to temporary fix the issue.

Here are some logs, if needed I can attach the full log file:
```
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] encode_fsid :NFS4 :DEBUG :fsid.major = 0, fsid.minor = 52
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7df005af90
, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] encode_fsid :NFS4 :DEBUG :fsid.major = 0, fsid.minor = 52
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7e682bd6d0
, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] encode_fsid :NFS4 :DEBUG :fsid.major = 0, fsid.minor = 52
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7d88110650
, valid_mask: 11dfce, request_mask: 91dfce, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] free_vfs_fsal_obj_handle :FSAL :DEBUG :Releasing obj_hdl=0x7f7e387f69e0, myself=0x7f7e387
f69e0
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7d88110650
, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] encode_fsid :NFS4 :DEBUG :fsid.major = 0, fsid.minor = 52
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7e682bdd90
, valid_mask: 11dfce, request_mask: 91dfce, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] free_vfs_fsal_obj_handle :FSAL :DEBUG :Releasing obj_hdl=0x7f7e789565f0, myself=0x7f7e789
565f0
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7e682bdd90
, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] encode_fsid :NFS4 :DEBUG :fsid.major = 0, fsid.minor = 52
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] fsal_reopen_obj :FSAL :DEBUG :Open in FSAL_O_ANY mode failed, just open temporary file de
scriptor.
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] vfs_open_by_handle :FSAL :DEBUG :Failed with Stale file handle openflags 0x00000000
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] free_vfs_fsal_obj_handle :FSAL :DEBUG :Releasing obj_hdl=0x7f7e3407bdc0, myself=0x7f7e3407bdc0
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] complete_op :NFS4 :DEBUG :Status of OP_READDIR in position 2 = NFS4ERR_STALE, op response size is 4 total response size is 92
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14039] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_STALE lastindex = 3
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7d881108b0, valid_mask: 11dfce, request_mask: 91dfce, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f7d881108b0, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14042] encode_fsid :NFS4 :DEBUG :fsid.major = 0, fsid.minor = 52
11/10/2021 16:10:02 : epoch 615dad4b : someNfsServer : ganesha.nfsd-10437[svc_14032] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 3 operations, res = 0x7f7e5032c8f0, tag = NO TAG
```
> We can see the "NFS4ERR_STALE" error.

I was using the following logs parameters:
```
Components {
		NFS4 = DEBUG;
		FILEHANDLE = DEBUG;
		FSAL = DEBUG;
}
```
> All the other parameters are using default values

### NFS-GANESHA VERSION
```
$ ganesha.nfsd -v
NFS-Ganesha Release = V3.4
```

### Distribution
Debian buster (10)

### NFS version
NFSv4.1

### FSAL
FSAL_VFS

### Is nfs-kernel-server working when exporting BeeGFS volumes ?

Yes, without any issue (no "Stale file handle"). But nfs-ganesha is faster, so I would preffer to use nfs-ganesha if possible.

### Export configuration
```
EXPORT {
	Export_Id = 3;
	Path = /beegfs/myexport;
	Pseudo = /myexport;
	Access_Type = RW;
	FSAL {
		Name = VFS;
		link_support =  false;
	}
}
```
> BeeGFS isn't supporting hard link, but I don't think the `link_support` is really important here.

# My question

Do you have any idea what's going on, and what can I do to avoid this error ? Is this a bug, or a configuration issue ?

Thanks for your help.

**Comment by ffilz** [comment]
How easy is this to recreate? We could crank up the debug, but if it takes a while to recreate, it could be an enormous debug log.

Instead of the debug you have above, I would look for FSAL=FULL_DEBUG; READDIR = FULL_DEBUG;

What does BeeGFS do that other filesystems don't? That might be a clue as to why a handle is going stale.

Another point that may be worth some investigation is running with the latest development code from the next branch. It does have mdcache and readdir fixes that haven't been backported.

**Comment by PopiBrossard** [comment]
Hi,

The most difficult step, I think, is to deploy a BeeGFS. Then, install NFS-ganesha and export the beegfs mount. On a client, try to access the export regularly, and after some time you should see a "Stale File Handle".

I forgot to say something, but when a directory is in "Stale file handle" in the NFS mount, the BeeGFS mount don't have any issues to access the same directory. 
```
nfs_client:~$ ls /nfsmount/path/to/directory
# ==> Stale File Handle
nfs_server:~$ ls /beegfs_mountpoint/path/to/directory
# ==> OK
```

> Note: I've about 33To and 5 million files. I think it matters.

## The test I'm doing

First, I mount and try to access "many" files:
```
nfs_client:~$ ls /nfs_mount/*/*/* >/dev/null
```

Then, from the NFS server, i'm accessing the same files:
```
nfs_server:~$ du -s --inodes /beegfs_mountpoint
```
> beegfs_mountpoint is the folder exported by the NFS server using NFSv4.

Then, try again accessing files from the client:
```
nfs_client:~$ ls /nfs_mount/*/*/* >/dev/null
directory: Stale file handle
...
```

## Some extra logs

I found some extra logs. The BeeGFS client (which is responsible of the beefs mountpoint) is logging informations. Let's say I have the error *Stale File handle* on the nfs client when accessing */nfs_mount/directory*, and */nfs_mount/directory* is accessible using */beegfs_mountpoint/directory* on the server.

```
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [NFS-handle-to-dentry] >> called. Path: n/a (no dentry); EntryID: n/a (no inode)
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [NFS-decode-handle-to-dentry] >> result dentry inode id: 1-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_lookupIntent] >> called. Path: /beegfs_mountpoint/directory/file; EntryID: n/a (no inode)
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_getattr] >> called. Path: /beegfs_mountpoint/directory/file; EntryID: 18-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_revalidateIntent] >> called. Path: /beegfs_mountpoint/directory/file; EntryID: 18-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [__FhgfsOps_revalidateIntent] >> called. Path: /beegfs_mountpoint/directory/file; EntryID: 18-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [NFS-handle-to-dentry] >> called. Path: n/a (no dentry); EntryID: n/a (no inode)
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [NFS-decode-handle-to-dentry] >> result dentry inode id: B-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [Export_getParentDentry] >> Find inode for ID: 1-6103D680-1 inodeHash: 18397459153076553350
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOpsExport_readdirFindName] >> called. Path: /beegfs_mountpoint/directory; EntryID: 1-6103D680-1; dir-id: %s searchID: %sdir-id: 1-6103D680-1 searchID: B-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_lookupIntent] >> called. Path: /beegfs_mountpoint/directory/other_file; EntryID: n/a (no inode)
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_opendirIncremental] >> called. Path: /beegfs_mountpoint/directory/other_file; EntryID: B-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_getattr] >> called. Path: /beegfs_mountpoint/directory/other_file; EntryID: B-6103D680-1
(5) Oct18 10:53:38 *ganesha.nfsd(28467) [FhgfsOps_releasedir] >> called. Path: /beegfs_mountpoint/directory/other_file; EntryID: B-6103D680-1
```
> */nfs_mount/directory* contain about 25 files, but the beegfs client only talks about 1-3 files. Sometimes only one, sometimes more.

Is it usefull for you ?

## Some technical details about Beegfs:

I'm using BeeGFS 7.2.1. There's a new 7.2.4, but nothing special in the changelogs is corrrelated to NFS.
- (7.2.2)[https://doc.beegfs.io/7.2.2/release_notes.html]
- (7.2.3)[https://doc.beegfs.io/7.2.3/release_notes.html]
- (7.2.4)[https://doc.beegfs.io/7.2.4/release_notes.html]

I'm just using BeeGFS, and not a developer. I don't really know how BeeGFS FS works exactly, but here some good initial points for you I guess:
- https://www.beegfs.io/c/home/how-beegfs-works/
- https://doc.beegfs.io/latest/architecture/overview.html#overview

To summarize, BeeGFS separates Metadata and Data. Metadata service is using an ext4 filesystem to store informations about files, and Storage service is using one (or more) XFS filesystems to store data. The redudancy is handle by hardware RAID (in my case). The BeeGFS is mounted using a kernel module (included in `beegfs-client` package).

## FULL_DEBUG logs

I'm trying on the nfs client to access a directory with "Stale File Handle":

```
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_106] vfs_extract_fsid :FSAL :M_DBG :Handle len 46 0x44: fsid=0x0000003500000000.0x0000000000000035, type 0xf3, opaque: (36:0x000000001549436101000000544943610200000002000000000000006400000001010000)
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_106] vfs_check_handle :FSAL :DEBUG :Found filesystem /beegfs for handle for FSAL VFS
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_106] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9d900cc840, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_112] vfs_extract_fsid :FSAL :M_DBG :Handle len 46 0x44: fsid=0x0000003500000000.0x0000000000000035, type 0xf3, opaque: (36:0x000000001549436101000000544943610200000002000000000000006400000001010000)
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_112] vfs_check_handle :FSAL :DEBUG :Found filesystem /beegfs for handle for FSAL VFS
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_112] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9d900cc840, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_extract_fsid :FSAL :M_DBG :Handle len 46 0x44: fsid=0x0000003500000000.0x0000000000000035, type 0xf3, opaque: (36:0x000000001549436101000000544943610200000002000000000000006400000001010000)
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_check_handle :FSAL :DEBUG :Found filesystem /beegfs for handle for FSAL VFS
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9d90767350, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_by_handle :FSAL :F_DBG :vfs_fs = /beegfs root_fd = 3
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_by_handle :FSAL :M_DBG :Handle len 46 0x44: fsid=0x0000003500000000.0x0000000000000035, type 0xf3, opaque: (36:0x000000001549436101000000544943610200000002000000000000006400000001010000)
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_by_handle :FSAL :F_DBG :Opened fd 32
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_map_name_to_handle_at :FSAL :M_DBG :Handle len 46 0x44: fsid=0x0000003500000000.0x0000000000000035, type 0xf3, opaque: (36:0x010000005449436122000000934943610200000002000000000000006400000002010000)
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] alloc_handle :FSAL :F_DBG :Creating object 0x7f9d5c986c40 for file run.log.2574677 of type REGULAR_FILE
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9d5c986c40, valid_mask: 11dfce, request_mask: 91dfce, supported: 91dfce
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] fsal_common_is_referral :FSAL :DEBUG :Checking attrs for referral, handle: 0x7f9d5c986c40, valid_mask: 11dfce, request_mask: 82, supported: 91dfce
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_getattr2 :FSAL :F_DBG :Calling find_fd, state = NULL
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] fsal_find_fd :FSAL :F_DBG :Use global fd openflags = 20
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] fsal_reopen_obj :FSAL :F_DBG :Open mode = 0, desired mode = 20
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] fsal_reopen_obj :FSAL :DEBUG :Open in FSAL_O_ANY mode failed, just open temporary file descriptor.
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_my_fd :FSAL :F_DBG :my_fd->fd = -1 openflags = 20, posix_flags = 0
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_my_fd :FSAL :F_DBG :openflags = 20, posix_flags = 0
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_by_handle :FSAL :F_DBG :vfs_fs = /beegfs root_fd = 3
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_by_handle :FSAL :M_DBG :Handle len 46 0x44: fsid=0x0000003500000000.0x0000000000000035, type 0xf3, opaque: (36:0x0100000054494361050000002c4268610200000002000000000000006400000002010000)
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_open_by_handle :FSAL :DEBUG :Failed with Stale file handle openflags 0x00000000
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] find_fd :FSAL :F_DBG :Found fd=-1 for file 0x7f9d844d6de0 of type REGULAR_FILE
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] vfs_getattr2 :FSAL :F_DBG :Got fd -1 closefd = false
18/10/2021 11:43:21 : epoch 616d38ec : someNfsServer : ganesha.nfsd-29000[svc_95] free_vfs_fsal_obj_handle :FSAL :DEBUG :Releasing obj_hdl=0x7f9d844d6de0, myself=0x7f9d844d6de0
```

**Comment by ffilz** [comment]
Are you following the guidelines here: https://doc.beegfs.io/latest/advanced_topics/nfs_export.html All of that will apply to Ganesha also (well no worry about the file lease bit, Ganesha will close files when the NFSv4 client closes, on the other hand, we may keep a global file descriptor open for getattr and stuff, that might cause problems.

Can you try using the kernel NFS server? Do you see the same issue?

I don't really have the bandwidth to try and set up BeeGeeFS and try this out.

But the ESTALE is clearly coming from BeeGeeFS so Ganesha can only report it along.

Oh, wait, I wonder if the problem IS handle size? FSAL_VFS tries to use a handle size that will fit in an NFSv3 handle... We would need a bit of work to make FSAL_VFS work only with NFSv4 so it can use larger handles.

**Comment by PopiBrossard** [comment]
Yes I'm following the guidelines (Delegations disabled using the ganesha parameter, only NFSv4, tuneRefreshOnGetAttr is true).

The NFS-kernel-server works without any issues (I was using it before trying ganesha. 1 month without any "Stale File Handle").

> But the ESTALE is clearly coming from BeeGeeFS so Ganesha can only report it along.

Shouldn't this create an issue when accessing the BeeGFS mount directly ? Because, on the NFS server, I can access normally all my files:
```
### On the client
nfs_client~:$ ls /nfs/directory
directory: Stale File Handle

### On the server
nfs_server~:$ ls /beegfs/directory
# directory content is displayed
```

**Comment by ffilz** [comment]
If the problem is a handle that is too big for Ganesha to use with FSAL_VFS (which is any handle too big for NFSv3) then Ganesha will be giving the client handles that can't be resolved back to an inode by BeeGFS and thus the ESTALE. The BeeGFS local mount won't have the same issue because it's prepared to use the full handle size or doesn't depend on the handles.

Now there is partly a problem with BeeGFS. If Ganesha is passing it too small a handle buffer, it should report an error and the actual handle buffer size required. I have seen other filesystems that don't properly report errors here.

From what I see, FSAL_VFS as currently implemented simply is not compatible with BeeGFS, even when using NFSv4 only.

We could modify Ganesha to allow larger handles for NFSv4 only exports, but that would be an enhancement.

**Comment by PopiBrossard** [comment]
Shouldn't this be re-qualified as a bug, because FSAL_VFS should work the same as the nfs-kernel-server ?

Do you know if there is a way to avoid this issue with some nfs mount arguments ? I mean, for example, adding "mount -t nfs4 -o noac,...".

**Comment by ffilz** [comment]
Ganesha doesn't guarantee it can always work the same as Kernel NFS. When FSAL_VFS was written, no Kernel filesystem known to us used such a large handle so we just assumed all handles would fit in both NFSv3 and NFSv4 handles so we didn't make accounting for a FSAL_VFS export only being able to work with NFSv4 clients. Since then, there are Kernel file systems that have larger handles so we will need feature level work to enhance Ganesha to use them. In theory, Ganesha COULD re-export a Kernel NFS mount (though using FSAL_PROXY would be a better solution) which would also run into the handle size issue. PROXY actually has the capability of using a handle mapping database so it can work with larger handles on the backend than the NFS protocol the client is using can support. I don't know how well that actually works.

So we will take into consideration doing this work to allow BeeGFS to work, but it needs a more extensive process than a bug fix and there is no sure timeline as to when we can do the work (none of the people actively contributing patches to Ganesha work for companies that are using FSAL_VFS, so all such support is gratis). However, we always welcome new contributors so if this is something you are passionate about getting working, we can work with you to help you get patches submitted.

**Comment by PopiBrossard** [comment]
I wasn't aware of the amount of work my issue was responsible of. Thanks for the complete answer and the time you spent on this issue.

I don't think I have enough competences in development to help you here, I'm sorry.

Have a nice week-end.

**Comment by jwongz** [comment]
> Ganesha doesn't guarantee it can always work the same as Kernel NFS. When FSAL_VFS was written, no Kernel filesystem known to us used such a large handle so we just assumed all handles would fit in both NFSv3 and NFSv4 handles so we didn't make accounting for a FSAL_VFS export only being able to work with NFSv4 clients. Since then, there are Kernel file systems that have larger handles so we will need feature level work to enhance Ganesha to use them. In theory, Ganesha COULD re-export a Kernel NFS mount (though using FSAL_PROXY would be a better solution) which would also run into the handle size issue. PROXY actually has the capability of using a handle mapping database so it can work with larger handles on the backend than the NFS protocol the client is using can support. I don't know how well that actually works.
> 
> So we will take into consideration doing this work to allow BeeGFS to work, but it needs a more extensive process than a bug fix and there is no sure timeline as to when we can do the work (none of the people actively contributing patches to Ganesha work for companies that are using FSAL_VFS, so all such support is gratis). However, we always welcome new contributors so if this is something you are passionate about getting working, we can work with you to help you get patches submitted.

I find the var ‘NFS4_FHSIZE’ eq 128.
How can I fix it if my env support nfs v4  only?

**Comment by ffilz** [comment]
> > Ganesha doesn't guarantee it can always work the same as Kernel NFS. When FSAL_VFS was written, no Kernel filesystem known to us used such a large handle so we just assumed all handles would fit in both NFSv3 and NFSv4 handles so we didn't make accounting for a FSAL_VFS export only being able to work with NFSv4 clients. Since then, there are Kernel file systems that have larger handles so we will need feature level work to enhance Ganesha to use them. In theory, Ganesha COULD re-export a Kernel NFS mount (though using FSAL_PROXY would be a better solution) which would also run into the handle size issue. PROXY actually has the capability of using a handle mapping database so it can work with larger handles on the backend than the NFS protocol the client is using can support. I don't know how well that actually works.
> > So we will take into consideration doing this work to allow BeeGFS to work, but it needs a more extensive process than a bug fix and there is no sure timeline as to when we can do the work (none of the people actively contributing patches to Ganesha work for companies that are using FSAL_VFS, so all such support is gratis). However, we always welcome new contributors so if this is something you are passionate about getting working, we can work with you to help you get patches submitted.
> 
> I find the var ‘NFS4_FHSIZE’ eq 128. How can I fix it if my env support nfs v4 only?

See my comment from October 19 for some description of the actual issue.

**Comment by ffilz** [comment]
This is unlikely to ever be worked on.
