### ISSUE TITLE
nfs4_getfacl empty

### ISSUE THREAD

**Issue by LordFPL** [nfs-ganesha/nfs-ganesha#75]
Hello,

I'm trying to setup a simple nfs4 server. I'm using centos distribution and modify only /etc/ganesha/ganesha.conf with a modified path.
/etc/idmap.conf is configured.

After starting server, i can mount the share with nfs v4.

But when i'm trying to get acl with nfs4_getface, il's empty.

The only error i see in logs is "nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs"

Do you have any idea of a place to check or missing parameter for nfs4 acl support ?

**Comment by LordFPL** [comment]
A little addition : 
``````
ganesha.nfsd -v
nfs-ganesha compiled on Jul 20 2015 at 14:35:09
Release = V2.2.0
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = NOT-GIT
Git Describe = /builddir/build/BUILD/nfs-ganesha-2.2.0/src
`````

**Comment by soumyakoduri** [comment]
Which FSAL have you been using? Are you able to set  the ACL?

**Comment by LordFPL** [comment]
I have try vfs & xfs.

Getfacl & setfacl are working on the exported fs.

Nfs4_setfacl is not returning any error... but nfs4_getfacl return... nothing... strange :-/

**Comment by ffilz** [comment]
Ganesha only supports translation between POSIX and NFS4 ACLs in FSAL_GLUSTER.

We are watching the RichACL project and will eventually support RichACLs from FSAL_VFS.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by LordFPL** [comment]
Hello, 

I don't see news about RichACLs support,  not planned so ?  (you can close this issue)

**Comment by ffilz** [comment]
RichACL support will eventually come, it is on both Ceph and Gluster's wish list.

I'll close this issue then.

Thanks
