### ISSUE TITLE
Broken link in github organization description

### ISSUE THREAD

**Issue by qwazer** [nfs-ganesha/nfs-ganesha#750]
http://nfs-ganesha.github.com is not available, should be https://nfs-ganesha.github.io

![image](https://user-images.githubusercontent.com/3875925/138061585-0ef0da42-a691-4933-bbce-25aa42913e53.png)

**Comment by ffilz** [comment]
Sorry where is this link that needs to be fixed?

**Comment by qwazer** [comment]
At https://github.com/nfs-ganesha page

**Comment by ffilz** [comment]
Oh, OK, got it. I think that's supposed to link to an external project page which we really don't have... Fixed it up.
