### ISSUE TITLE
Question - Hello, I don't understand how to install "nfs-ganesha" on debian 9 (Stretch).

### ISSUE THREAD

**Issue by DagothDeer** [nfs-ganesha/nfs-ganesha#752]
Hello, I don't understand how to install "nfs-ganesha" on debian 9 (Stretch).
I download package "nfs-ganesha_3.5-1_amd64" from "https://download.nfs-ganesha.org/3/LATEST/Debian/9/amd64/apt/pool/main/n/nfs-ganesha/", and I tried install it: "dpkg -i nfs-ganesha_3.5-1_amd64". Result on screen.
![1](https://user-images.githubusercontent.com/33806067/138453627-fcc2e56d-4d1e-4e64-8b12-a933a86124c1.png)

I also used the command: "apt-get install nfs-ganesha", but no such package was found.

Pls, help me install nfs-ganesha on clear system debian 9.

P.S. I have been using Linux not long ago, so please do not judge strictly...

**Comment by christmart** [comment]
To fix these errors and install the needed dependencies use
`apt install -f`
The better way is to not use dpkg but apt. You can call apt with path names for local files:
`apt install ./nfs-ganesha_3.5-1_amd64.deb`
Keep in mind that you need more packages from the download directory depending on your usage.

**Comment by DagothDeer** [comment]
Thx for the answer.

**Comment by kalebskeithley** [comment]
I'll interpret this as "why are the README.txt files missing in the 3.5/* directories."  (They were there in the 3.4/* directories.)

I have added the README.txt files to all the 3.5/* directories.
