### ISSUE TITLE
Ganesha can not run continually when open asan

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#755]
@ffilz @martinetd @dang 

Hi, excuse me, when I open asan by set `option(SANITIZE_ADDRESS "Enable AddressSanitizer for sanitized targets." ON)`,
the ganesha cost 100% cpu, and hang, then I perf ganesha and find asan cost 100% cpu. Is it normal  ? 
![image](https://user-images.githubusercontent.com/92144382/139361414-13849248-aa9e-4fcf-8c4e-b76f9615ffa4.png)

The ganesha only print the following log and can not continue. I want the ganesha can continue to run, to detect the memory leak.

```
29/10/2021 T09:48:38.770056+0800 [main] nfs_init.c:481 :nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
29/10/2021 T09:48:38.770215+0800 [main] mdcache_lru.c:1735 :init_fds_limit :INODE LRU :INFO :Setting the system-imposed limit on FDs to 1048576.
29/10/2021 T09:48:38.770979+0800 [main] nfs_init.c:512 :init_server_pkgs :NFS STARTUP :INFO :State lock layer successfully initialized
29/10/2021 T09:48:38.770992+0800 [main] nfs_init.c:521 :init_server_pkgs :NFS STARTUP :INFO :IP/name cache successfully initialized
29/10/2021 T09:48:38.770997+0800 [main] nfs_init.c:523 :init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
29/10/2021 T09:48:38.771589+0800 [main] nfs_init.c:528 :init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
29/10/2021 T09:48:38.771603+0800 [main] nfs4_recovery.c:783 :nfs4_recovery_init :CLIENT ID :INFO :Recovery Backend Init for fs
29/10/2021 T09:48:38.771626+0800 [main] nfs4_recovery.c:250 :nfs_start_grace :STATE :EVENT :NFS Server skipping GRACE (Graceless is true)
```

**Comment by dang** [comment]
This is not normal.  I run with ASAN on in almost every run I do, and it works fine.

**Comment by ffilz** [comment]
What version of Ganesha? What FSAL?

**Comment by liyinshubyte** [comment]
@dang @ffilz Thanks the reply, I use ganesha with version [V4-dev.18](https://github.com/nfs-ganesha/nfs-ganesha/commit/64f0146c0c30a5fa9b7f34324d9238d7fbfc2624), we use the FSAL implemented by ourselves.  So is there other config to open ASAN except `option(SANITIZE_ADDRESS "Enable AddressSanitizer for sanitized targets." ON)`, or am I need to make some settings in my own FSAL ?

**Comment by dang** [comment]
SANITIZE_ADDRESS is all that's necessary at build time.  FSALs need to have ASAN enabled in their CMakeLists.txt like this:

add_sanitizers(fsalmem)

(That example is from src/FSAL/FSAL_MEM/CmakeLists.txt)

**Comment by liyinshubyte** [comment]
@dang Thanks the reply, I think it's related to `pthread_create` load order in dynamic library. My phenomenon just like this question [How to combine AddressSanitizer with dynamically linked Pthreads library](https://stackoverflow.com/questions/57544599/how-to-combine-addresssanitizer-with-dynamically-linked-pthreads-library).  

My fsal library is libfsalnas.so, and libfsalnas.so will load nasclient.so, nasclient.so will create thread by pthread_create, but libasan.so also define pthread_create, then the main thread stuck in pthread_create from libasan.so.
I think if use pthread_create from libpthread.so rather than libasan.so can resolve this problem. 

![image](https://user-images.githubusercontent.com/92144382/139691413-27fd4a26-40f8-4ed0-aa72-29b786518c85.png)

**Comment by ffilz** [comment]
Hmm, how does ASAN deal with threads that aren't created with its pthread_create but might run ASAN enabled code?
