### ISSUE TITLE
NFS clients failover take ~ 300sec

### ISSUE THREAD

**Issue by happycouak** [nfs-ganesha/nfs-ganesha#758]
Context: 2 nodes in active/passive failover (keepalived) running ganesha, exporting a single cephfs namespace (following [1] [2]).

When the active node is powered off, clients IO takes ~300sec to resumes.

Network does not seems an issue as keepalived send GARP, arp table update on NFS clients are almost instant.

Lease_Lifetime and Grace_Period as been reducted to 5 sec, without effect.

I am trying to understand why the failover take approximativly 300sec and how it can be reduced.

Side question: did the use of keepalived is recommended for active/passive setup or better to go with corosync/pacemaker 3 nodes cluster.

[1] https://docs.ceph.com/en/octopus/cephfs/nfs/
[2] https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/config_samples/ceph.conf

---
Versions:
Ganesha 3.4, libcephfs2 16.2.6 (Ubuntu 21.04)
Ceph 15.2.14

Mount options: ```(rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.140.5.180,local_lock=none,addr=10.140.7.200)```

ganesha.conf:

```
NFS_CORE_PARAM
{
	Enable_NLM = false;
	Enable_RQUOTA = false;
	Protocols = 4;
}
NFSv4
{
	RecoveryBackend = rados_ng;
	Minor_Versions =  1;
	Lease_Lifetime = 5;
	Grace_Period = 5;
}
MDCACHE {
	Dir_Chunk = 0;
}
EXPORT
{
	Export_ID=100;
	Protocols = 4;
	Transports = TCP;
	Path = /;
	Pseudo = /cephfs/;
	Access_Type = RW;
	Attr_Expiration_Time = 0;
	FSAL {
		Name = CEPH;
		Secret_Access_Key = "*******************";
	}
}
CEPH
{
	Ceph_Conf = /etc/ceph/ceph.conf;
}
RADOS_KV
{
	UserId = "admin";
	pool = "nfs-ganesha";
}
RADOS_URLS
{
	Ceph_Conf = /etc/ceph/ceph.conf;
	UserId = "admin";
}
LOG {
        Default_Log_Level = DEBUG;
        Facility {
                name = FILE;
                destination = "/var/log/ganesha.log";
                enable = active;
        }
}
```

**Comment by jtlayton** [comment]
The 300s timeout suggests that the ceph MDS is eventually timing out the old ceph client.

For an active/passive setup, you can probably fix this by setting the "nodeid" field in the RADOS_KV block on both machines to be the same. When the new server takes over, it'll ask the MDS to release the state held by the old client, and that will allow reclaim to proceed properly.

See: https://github.com/nfs-ganesha/nfs-ganesha/blob/ef07e96e25e2b8521311d594b6bdfb600c05c2f0/src/config_samples/ceph.conf#L187

**Comment by happycouak** [comment]
I will give it at try, but this means only one ganesha server can run at a time, which is not the actual setup: ganesha is running on both active and passive node, the failover only concerns the VIP that use the NFS clients to access the service (this is why I wonder if this setup is correct).

**Comment by jtlayton** [comment]
That's not an active/passive setup then. You have an active/active setup where (you hope) that only one is actively serving clients at the time. The setup you're describing is not supported.

To be clear, the startup of the daemon is what triggers the grace period to start and allow the clients to reclaim. Without that, your deployment won't work correctly.

**Comment by happycouak** [comment]
Make sens, thanks for the confirmation that only failover a VIP between 2 running instances of ganesha wont works.

So I tested with a *real* failover (only one running instance of ganesha at a time), with the same nodeid on both node and the result is the same, failover take exactly 300s.

**Comment by jtlayton** [comment]
You'll probably need to do a bit of detective work then. It's possible that your ganesha build doesn't support the reclaim_reset facility properly. You may want to crank up the debugging level to NIV_DEBUG and see whether this message shows up:

```LogDebug(COMPONENT_FSAL, "Issuing reclaim reset for %s", uuid);```

When you say it takes 300s, how are you measuring it?


As a side note, these two things are definitely not recommended:

Lease_Lifetime and Grace_Period as been reducted to 5 sec, without effect.

Reducing those that low will likely break the ability for clients to reclaim.

**Comment by happycouak** [comment]
Nice catch, below the log that show up on the node that handles the fail-over:
```
02/11/2021 21:59:19 : epoch 6181b4b7 : node2 : ganesha.nfsd-3581[main] reclaim_reset :FSAL :EVENT :start_reclaim failed: -2
```

The fail-over delay is measured in a very primitive way: date diff between the fail-over and when the network bandwidth rise back on the test client, where 2 dd read and write random data.

Thanks for the hint on Lease_Lifetime and Grace_Period, I set them back to default, without noticable effect on the fail-over delay.

Also (and maybe not related), "ganesha-rados-grace" report "Failure: -2", but if my understanding is good this is only used for the rados_cluster recovery backend.

**Comment by ffilz** [comment]
Did this resolve your issue?

**Comment by happycouak** [comment]
No unfortunately it does not.

**Comment by jtlayton** [comment]
-2 == -ENOENT, which is what the MDS sends back if it doesn't find a session with the same uuid as the current one. That suggests that your old server was using a different nodeid or export id number.

Can you attach the ganesha.conf from both hosts?

**Comment by happycouak** [comment]
FYI ganesha has been upgraded to 3.5 from https://launchpad.net/~nfs-ganesha since.

Below the configuration which is the same on all 3 nodes:

```
NFS_CORE_PARAM
{
	Enable_NLM = false;
	Enable_RQUOTA = false;
	Protocols = 4;
}
NFSv4
{
	RecoveryBackend = rados_ng;
	Minor_Versions =  1;
}
MDCACHE {
	Dir_Chunk = 0;
}
EXPORT
{
	Export_ID=100;
	Protocols = 4;
	Transports = TCP;
	Path = /;
	Pseudo = /cephfs/;
	Access_Type = RW;
	Attr_Expiration_Time = 0;
	FSAL {
		Name = CEPH;
		Secret_Access_Key = "********************************";
	}
}
CEPH
{
	Ceph_Conf = /etc/ceph/ceph.conf;
}
RADOS_KV
{
	Ceph_Conf = /etc/ceph/ceph.conf;
	UserId = "admin";
	pool = "nfs-ganesha";
	nodeid = "supernfs";
}
RADOS_URLS
{
	Ceph_Conf = /etc/ceph/ceph.conf;
	UserId = "admin";
}
LOG
{
	Default_log_level = EVENT;
	COMPONENTS
	{
		FSAL = DEBUG;
		NFS4 = INFO;
	}
	FACILITY
	{
		name = FILE;
		destination = "/var/log/ganesha.log";
		enable = active;
	}
}
```

Even if the "nodeid" is set to be the same, there are FSAL logs that seams to indicate that the hostname is stil in use:
Logs on node1:

```
03/11/2021 17:13:53 : epoch 6182c351 : node-5 : ganesha.nfsd-1851[main] reclaim_reset :FSAL :DEBUG :Issuing reclaim reset for ganesha-node-5-0064
```

Log on a second node after a failover:

```
03/11/2021 17:17:02 : epoch 6182c40e : node-4 : ganesha.nfsd-2076[main] reclaim_reset :FSAL :DEBUG :Issuing reclaim reset for ganesha-node-4-0064
03/11/2021 17:17:02 : epoch 6182c40e : node-4 : ganesha.nfsd-2076[main] reclaim_reset :FSAL :EVENT :start_reclaim failed: -2
```



Hope it helps

**Comment by jtlayton** [comment]
Ok, that's the issue. The "issuing reclaim reset" message gives us the uuid for the mount session and it's different in the two cases (ganesha-node-5-0064 vs. ganesha-node-4-0064 on the second node). Those need to be the same.

You said you're running V3.5, but that doesn't have this patch: https://github.com/nfs-ganesha/nfs-ganesha/commit/a126b80767024127e79e9c3241ea93c706779752

You'll need that since you're using rados_ng.

@ffilz , @dang : it might be good to pull the above patch into V3.X series.

**Comment by ffilz** [comment]
We have just released V4-rc2. At this point, we do not plan to release a V3.6, V4.0 will be ready just about as soon as we could get a V3.6 out. V4-rc2 should be stable enough for non-production use to verify the solution.

**Comment by happycouak** [comment]
To go further, do I need to compile the V4-rc2 or a PPA will land soon ?

**Comment by ffilz** [comment]
You would need to compile it yourself for the time being. We might package up an rc soon though, we have sometimes packaged release candidates.

**Comment by ffilz** [comment]
Adding needs verification since either the specified patch needs to be back ported to V3.5 and tested or V4-rc2 (or later) needs to be built and tested.

**Comment by happycouak** [comment]
I am facing a compilation error where libcephfs is not found (branch 'next' / tag: V4-rc2 ):

```
cmake  src/
-- cmake version 3.18
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected a Linux Debian base machine
-- toolchain options processed
-- Compilation from within a git repository. Using git rev-parse HEAD
CMake Warning at CMakeLists.txt:664 (message):
  Cannot find LizardFS client lib.  Disabling lizardfs fsal


-- REQUIRED
-- Found cephfs libraries: /usr/lib/x86_64-linux-gnu/libcephfs.so
CMake Error at cmake/modules/FindPackageHandleStandardArgs.cmake:109 (message):
  Could NOT find CEPHFS (missing: CEPHFS_INCLUDE_DIR CEPHFS_LIBRARY_DIR)
Call Stack (most recent call first):
  cmake/modules/FindPackageHandleStandardArgs.cmake:317 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindCEPHFS.cmake:164 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:683 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/nfs-ganesha/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/nfs-ganesha/CMakeFiles/CMakeError.log".
```
Note that CMakeOutput.log and CMakeError.log files are empty.
However  libcephfs2 and libcephfs-dev are installed (Ubuntu 21.04): 

```
dpkg -l |grep cephfs
ii  libcephfs-dev                         16.2.6-0ubuntu0.21.04.2                                              amd64        Ceph distributed file system client library (development files)
ii  libcephfs-java                        16.2.6-0ubuntu0.21.04.2                                              all          Java library for the Ceph File System
ii  libcephfs-jni                         16.2.6-0ubuntu0.21.04.2                                              amd64        Java Native Interface library for CephFS Java bindings
ii  libcephfs2                            16.2.6-0ubuntu0.21.04.2                                              amd64        Ceph distributed file system client library
ii  python3-cephfs                        16.2.6-0ubuntu0.21.04.2                                              amd64        Python 3 libraries for the Ceph libcephfs library
```
Maybe libcephfs2-dev is missing ? The last thing I compiled were a kernel 2.4, so any guidance will be greatly appreciated !

**Comment by jtlayton** [comment]
The other thing you could do is use the rados_cluster backend instead of rados_ng. You'd need to use ganesha-rados-grace and add the nodeid to the db, but a single-node rados_cluster "cluster" should function pretty much like rados_ng.

**Comment by happycouak** [comment]
Thanks Jeff, the rados_cluster recovery backend works pretty well.
From the client point of view, the failover takes now ~25 sec and is mainly about the re-convergence of the corosyn/pacemaker cluster, thats great.

My understanding is not clear about there difference between these 2 recovery backend, what are the underneath  and pros/cons ?

**Comment by jtlayton** [comment]
In a nutshell: rados_cluster is more of a scale-out solution than something built for redundancy, and allows for an active/active. rados_ng is an active/passive solution that predates rados_cluster. In your case, you're just running a cluster that has only one active node, so it'll end up doing a little more processing than is necessary, but should effectively work the same way.

@ffilz : Maybe for one of the upcoming releases, we should deprecate rados_ng, since it's effectively a subset of rados_cluster's functionality at this point?

**Comment by ffilz** [comment]
@jlayton If that makes sense, should we deprecate it for 4.0 so we can remove the code in 5.0?

**Comment by runguyenhuu** [comment]
Hi happycouak !
I am deploying two ganesha-server to failover. I update ganesha to last version ( tested on 4.3 and 4.9), but still faiover very slow, about 5 minutes. 
Can you help me some note to config to nfs faiover faster ? NFS client will be stuck when failover more 5 minutes ?
Thank you very much !

**Comment by ffilz** [comment]
Please open a new issue with more detail on your configuration and the issues you are seeing. Also, which version of Ganesha you are using.
