### ISSUE TITLE
Bind_addr not working in 3.5.2 (and I think 3.3.1)

### ISSUE THREAD

**Issue by seanfulton** [nfs-ganesha/nfs-ganesha#760]
I am trying to set up ganesha/gluster/keepalived/haproxy like this:
https://www.loadbalancer.org/blog/highly-available-shared-nfs-server/

I actually had it working except it kept failing and now I know why:

Two servers, chi-nfs01-cl01, chi-nfs02-cl01, and floating IP of chi-nfs-cl01.

If ganesha launches BEFORE chi-nfs-cl01 is assigned to the host, it works. Ganesha binds to the only valid IP which is chi-nfs01-cl01.

If ganesha launched AFTER chi-nfs-cl01 is assigned to the host, Ganesha binds to both IPs (chi-nfs01-cl01 and chi-nfs-cl01).

If haproxy launches before ganesha, haproxy binds to port 2049 on chi-nfs-cl01, and Ganesha will not load because it can't bind to that IP on tcp6! I am not using IPV6.

Config is here:
NFS_Core_Param {
        Bind_addr = 10.10.20.123; #chi-nfs01-cl01
        NFS_Port = 2049;
        MNT_Port = 20048;
        NLM_Port = 38468;
        Rquota_Port = 4501;
	# mount_path_pseudo = true;
}

The problem seems to be that although I am not using IPV6, ganesha still wants to bind to port 2049 on tcp6 for chi-nfs-cl01, even though haproxy is already bound to the IP.

There are only two ways to make it work, both sketchy: 1) change the NFS port to 20049, or 2) tear the IP down, leave Haproxy up, load ganesha, then load the IP.

09/11/2021 09:52:27 : epoch 618a89a4 : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28458[main] nfs_start :MAIN :EVENT :NFS EXIT: regular exit
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28940[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 3.5
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] load_rados_config :CONFIG :WARN :Missing RADOS URLs backend library
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] glusterfs_create_export :FSAL :EVENT :Volume onecount exported at : '/'
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,35,36+ep
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] Bind_sockets_V6 :DISP :WARN :Cannot bind NFS tcp6 socket, error 98 (Address already in use)
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] Bind_sockets :DISP :FATAL :Error binding to V6 interface. Cannot continue.
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] unregister_fsal :FSAL :CRIT :Unregister FSAL GLUSTER with non-zero refcount=1
09/11/2021 09:52:27 : epoch 618a8b2b : chi-nfs01-cl01.onecount.net : ganesha.nfsd-28941[main] glusterfs_unload :FSAL :CRIT :FSAL Gluster unable to unload.  Dying ...

**Comment by ffilz** [comment]
Yep Bind_Addr is the one place we don't have proper IPv6 support...

I guess it's time to fix that...

**Comment by seanfulton** [comment]
Is there a way to turn it off? I have it off on the server

**Comment by ffilz** [comment]
There isn't a way to turn off IPv6.

Also, looking, Bind_Addr does support IPv6 and encapsulates an IPv4 address into IPv6.

I'm not quite sure how you're configuring and I'm not familiar with haproxy

**Comment by seanfulton** [comment]
I'm not trying to use ipv6. I am using ipv4 and what is happening is that ganesha is correctly binding to the IP I specify for ipv4, but trying to bind on all ips at tcp6. Since the shared IP is already bound, it won't load

**Comment by ffilz** [comment]
Can you try V4-rc2? I see https://github.com/nfs-ganesha/nfs-ganesha/issues/689 may resolve the issue with the TCP binding.

I've got a patch that adds some INFO log messages indicating what is being bound.

I just did a netstat -ap | egrep 'Proto|ganesha' on rc2+ and it looks like it's properly bound.

**Comment by MyqueWooMiddo** [comment]
> I'm not trying to use ipv6. I am using ipv4 and what is happening is that ganesha is correctly binding to the IP I specify for ipv4, but trying to bind on all ips at tcp6. Since the shared IP is already bound, it won't load

I meet same problem ,  I found tcp6 and ipv4 address  with a netstat command
