### ISSUE TITLE
Can we use a thread pool for each mounted volume ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#763]
we use ganesha to mount volume in our filesystem. Ganesha use a thread pool for requests of all mounted volumes, such as volume1, volume2, volume3. If volume1 has some problem, and the request hang on the volume1, then ganesha will exhaust all the threads on volume1. Then ganesha has no threads to visit volume2 and volume3. So can we allocate a thread pool for each volume ?

**Comment by ffilz** [comment]
No because the worker thread is assigned when an RPC request is started to be processed. The RPC layer doesn't know what file systems are involved. PLUS a request CAN span file systems. And really, the thread is assigned before the RPC layer has even read a request from the socket.

**Comment by ffilz** [comment]
One solution for this if you have your own FSAL is to make it async...

**Comment by liyinshubyte** [comment]
@ffilz Thanks the explanation. Got it.
