### ISSUE TITLE
SELinux: Failed to resolve roletype statement at /var/lib/selinux/targeted/tmp/modules/200/ganesha/cil:2

### ISSUE THREAD

**Issue by phpfs** [nfs-ganesha/nfs-ganesha#765]
Dear ganesha team,

when trying to install (or later on use) the SELinux module of nfs-ganesha from the CentOS SIG repository, I receive the following error:
```
Failed to resolve roletype statement at /var/lib/selinux/targeted/tmp/modules/200/ganesha/cil:2
/usr/sbin/semodule:  Failed!
```

This already occurs as part of installation:
```
  Running scriptlet: nfs-ganesha-selinux-3.5-3.el8.noarch                 45/47 
  Installing       : nfs-ganesha-selinux-3.5-3.el8.noarch                 45/47 
  Running scriptlet: nfs-ganesha-selinux-3.5-3.el8.noarch                 45/47 
Failed to resolve roletype statement at /var/lib/selinux/targeted/tmp/modules/200/ganesha/cil:2
/usr/sbin/semodule:  Failed!

  Running scriptlet: nfs-ganesha-3.5-3.el8.x86_64                         46/47
```

To reproduce, use either the latest CentOS 8 or Alma Linux 8.5 Docker container from DockerHub.
Then, execute the following commands:
```bash
dnf update
dnf install -y centos-release-nfs-ganesha30
dnf install -y nfs-ganesha nfs-ganesha-vfs nfs-ganesha-selinux
```

Ideally, I'd want to be able to work with the SELinux module, e.g. via:
```bash
semanage permissive -a ganesha_t
```

If I can be from further assistance, please let me know!

Thank you in advance :)

**Comment by kalebskeithley** [comment]
> 

I've never seen that error before now, and when I tried it just now on my up to date c8/c8s systems the install worked without error. Even with --verbose.

If you know of some way to dump selinux data to see what that roletype statement is that would be a good start.

**Comment by ffilz** [comment]
With more than 30 days without a response and V4.0 out, I am going to close this. If more information can be provided, please re-open.

**Comment by ffilz** [comment]
Also, with V4.0 out, V3.x is technically no longer supported so marking this as try on latest version.

**Comment by Haroldll** [comment]
@ffilz 
I had the same problem updating ganesha, on ceontos 8.2.

Updating / installing...
   1:libntirpc-4.0-.3.el8             ################################# [  7%]
   2:nfs-ganesha-selinux-4.0-.3.el8   ################################# [ 14%]
Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/200/ganesha/cil:61
/usr/sbin/semodule:  Failed!
   3:nfs-ganesha-4.0-.3.el8           warning: /etc/ganesha/ganesha.conf created as /etc/ganesha/ganesha.conf.rpmnew
warning: /etc/logrotate.d/ganesha created as /etc/logrotate.d/ganesha.rpmnew
################################# [ 21%]
   4:nfs-ganesha-debuginfo-4.0-.3.el8 ################################# [ 29%]
   5:nfs-ganesha-ceph-debuginfo-4.0-.3################################# [ 36%]
   6:nfs-ganesha-ceph-4.0-.3.el8      ################################# [ 43%]
   7:nfs-ganesha-rados-grace-4.0-.3.el################################# [ 50%]
   8:nfs-ganesha-rados-urls-4.0-.3.el8################################# [ 57%]
