### ISSUE TITLE
SIGHUP does not update Exports

### ISSUE THREAD

**Issue by doj** [nfs-ganesha/nfs-ganesha#77]
When the NFS-Ganesha server handles a SIGHUP, it should reload the configuration file and add new Exports and remove Exports no longer found in the new configuration file. However sending SIGHUP to NFS-Ganesha does not result in any changes to the Exports. I've tested this with version 2.2, but I think this behavior is not fixed on the "next" branch.

Looking at the source code, from the signal handler in sigmgr_thread(), handling a SIGHUP calls the admin_replace_exports() function. In admin_replace_exports() a command for the admin thread is issued, which is the same as the current command, typically admin_none_pending. In the admin thread function admin_thread(), the while loop waits for new commands via the condition variable admin_control_cv, but the only command that leads to any action is admin_shutdown.

Thus calling admin_replace_exports() results in no further action done on the admin thread.

I also did not find any function that would actually re-load the configuration file, re-parse the EXPORT blocks and add/remove anything new. Does such a function exist and just needs to be called from the admin thread?

**Comment by ffilz** [comment]
There once was a capability to reload exports with SIGHUP. Unfortunately is was problematical.

There are currently dbus methods to add and remove exports. Updating an export is currently not supported.

**Comment by itfanr** [comment]
@ffilz  Is the dbus model already implemented and how can I test it ?
Thanks.

**Comment by ffilz** [comment]
There is now a dynamic export update that does indeed allow SIGHUP.

Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by doj** [comment]
we can close it.

**Comment by wyllys66** [comment]
Is the dbus reload method supported or only SIGHUP?

**Comment by ffilz** [comment]
There is a dbus update also. It allows updating a single export or a group of exports (specified in the same way you can add a set of exports with dbus). Both methods will also add exports if the "updated" export doesn't exist, SIGHUP of course processing the entire config file - though note that tricks with include files can be used, you could put each export in it's own config file, then %include them from the top config file. Then when you want to update a single export with SIGHUP, comment out all but the one %include. Of course remember to uncomment them so the next restart gets the complete config...
