### ISSUE TITLE
ganesha large queue accumulation

### ISSUE THREAD

**Issue by Mr-Chengcheng** [nfs-ganesha/nfs-ganesha#771]
hi, i use nfs-ganesha 2.5 + glusterfs 3.12 There is often a large number of queue accumulation，Using the pstack tool, a large number of getattr requests were found：
![image](https://user-images.githubusercontent.com/54385902/146219088-3ed8760e-a9fb-420b-b703-e491c421e120.png)
![image](https://user-images.githubusercontent.com/54385902/146219266-49eaeb39-d261-4b6a-b139-17f933f2cfbf.png)
Have you ever experienced this situation? Thank you very much。

**Comment by ffilz** [comment]
Under what workload? Note that V2.5 is quite old and long not supported by the Ganesha community (last update was 4 years ago). Current supported release is V3.5 with V4.0 coming out real soon (V4-rc6 was just posted last week).

**Comment by Mr-Chengcheng** [comment]
i have used some clients mount， and do a lot of write and mkdir operations,  Can you provide some ideas to avoid this ？ Thank you very much。

**Comment by Mr-Chengcheng** [comment]
@ffilz @dang

**Comment by WelldoneIT** [comment]
hello @ffilz @dang,  i have upgrate nfs-ganesha to V3.5,but also have this problem. and use "netstat" could found lot queue bcaklog.

**Comment by ffilz** [comment]
I just looked at the V4 release notes, and I don't see anything that might be a fix there, but could you try with V4.0? Also, curious if all the stacks are working on the same obj_handle. If you can dump all the stacks and grep for mdcache_getattrs we can see if it's all the same obj_handle, or several. The two stacks you show are the same obj_handle.

**Comment by ffilz** [comment]
We technically no longer support V3.5, any fixes would definitely just go into V4.

**Comment by WelldoneIT** [comment]
> 

YES，all threads are the same obj_handle.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
