### ISSUE TITLE
Does ganesha want to change to c++ project ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#774]
Do we want to change ganesha to c++ project ? Maybe it's easy to use STL, gflags, glog and so on. Just an open question.

**Comment by ffilz** [comment]
What would be the benefit? There would be a lot of code change to gain any real benefit.

**Comment by mattbenjamin** [comment]
modern c++ is great, but nfs-ganesha is mature enough and complete enough that I don't think we'd get any benefit, personally

**Comment by liyinshubyte** [comment]
@ffilz @mattbenjamin Thanks, I see.
