### ISSUE TITLE
How to achieve load balance of ganesha? 

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#775]
Currently we use ganesha by the following model, and we want to adjust the connected ganesha of client dynamicly, according to ganesha's workload. 

For example, client1 and client2 connected to ganesha1, and client3 and client4 connected to ganesha2. Workload of client1 is 300MB/s, and workload of client2, client3, client4 is 100MB/s. So workload of ganesha1 is 400MB/s, and workload of ganesha2 is 200MB/s. To achieve load balance of ganesha, we want client2 can connect to ganesha2, then workload of ganesha1 and ganesha2 both are 300MB/s. 

But we do not know how to ask client2 to change it's connection from ganesha1 to ganesha2. Currently we achieve this by ask ganesha1 to close socket with client2, and client2 will retry connection, LoadBalance service will allocate the connection among ganesha1 and ganesha2, but we can not make sure LoadBalance service will allocate the connection on ganesha2, the connection maybe still allocated on ganesha1. So this method is rude and random. Do you have any suggestion ?

![image](https://user-images.githubusercontent.com/92144382/147201303-0446101b-1eb8-4ad8-8e5e-d9642f4cc2d6.png)

**Comment by hit1943** [comment]
This is a difficult thing, because the nfs protocol connection between client and server is long connection. you can’t do load balancing based on bandwidth when you establish a connection.

**Comment by dang** [comment]
If you know ahead of time what bandwidth will be used by a client, then you can do it, but otherwise you can't really, for the reason stated above.  NFS works poorly with load balancing, because it uses long-lived, stateful connections between clients and servers. As the bandwidth used by a give client changes, there's no good way to move clients around between servers to balance the bandwidth.

**Comment by liyinshubyte** [comment]
@hit1943 @dang Thanks the reply. Got it.
