### ISSUE TITLE
is mutli exports sharing one ceph client a good idea

### ISSUE THREAD

**Issue by hit1943** [nfs-ganesha/nfs-ganesha#777]
hi，everyone
in my project，i use nfs-ganesha as nas gateway in front of cephfs. 
as we know, "For each NFS-Ganesha export, FSAL_CEPH uses a libcephfs client to mount the CephFS path that NFS-Ganesha exports". 
i found if i create 100 exports，it will increase 100 ceph clients - than more than 500 threads will be created by libcephfs client, another thing is that i should create 100 ceph users for the exports.
so wo want to know whather mutli exports sharing one ceph client is a good idea? @jtlayton and @dang

**Comment by jtlayton** [comment]
On Tue, 2022-01-04 at 02:14 -0800, Kevin Chen wrote:
> hi，everyone
> in my project，i use nfs-ganesha as nas gateway in front of cephfs.
> as we know, "For each NFS-Ganesha export, FSAL_CEPH uses a libcephfs
> client to mount the CephFS path that NFS-Ganesha exports".
> i found if i create 100 exports，it will increase 100 ceph clients -
> than more than 500 threads will be created by libcephfs client,
> another thing is that i should create 100 ceph users for the exports.
> so wo want to know whather mutli exports sharing one ceph client is a
> good idea? @jtlayton and @dang


Sure, sharing clients between exports would be a great thing to do. It's
just not trivial to implement, unfortunately.

You can't share the same client between different named ceph
filesystems, at least not with libcephfs structured as it is today. You
probably could make it share clients between different exports from the
same named cephfs though if you're looking to tackle that project.

**Comment by hit1943** [comment]
> On Tue, 2022-01-04 at 02:14 -0800, Kevin Chen wrote: hi，everyone in my project，i use nfs-ganesha as nas gateway in front of cephfs. as we know, "For each NFS-Ganesha export, FSAL_CEPH uses a libcephfs client to mount the CephFS path that NFS-Ganesha exports". i found if i create 100 exports，it will increase 100 ceph clients - than more than 500 threads will be created by libcephfs client, another thing is that i should create 100 ceph users for the exports. so wo want to know whather mutli exports sharing one ceph client is a good idea? @jtlayton and @dang
> Sure, sharing clients between exports would be a great thing to do. It's just not trivial to implement, unfortunately. You can't share the same client between different named ceph filesystems, at least not with libcephfs structured as it is today. You probably could make it share clients between different exports from the same named cephfs though if you're looking to tackle that project. -- Jeff Layton ***@***.***>

thanks for your advice, @jtlayton ，i will try share clients between different exports if they use the same ceph user and same named cephfs

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
