### ISSUE TITLE
Fix crash of ganesha because out-of-bounds access

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#779]
When we run ganesha, it crashes because of out-of-bounds access.

The reason is when segment_len = NAME_MAX; the last character of path may not be '\0'.

![image](https://user-images.githubusercontent.com/92144382/148913997-16a4bbfc-10ba-45dc-80f2-7ca382e9c66c.png)

The fix as follows:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/530853

@ffilz Could you help review it.

**Comment by ffilz** [comment]
Yep, good catch, comments on your fix.
