### ISSUE TITLE
Why not overwrite attr in mdcache_new_entry ? 

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#780]
@ffilz 
Hi, when I set Dir_Chunk = 0, and nfs-client call readdir, I found nfs-client can not get the newest attr such as uid, gid, though fsal return the newest attr. The reason is `mdcache_new_entry` did not use `attrs_in` to overwrite attr of entry which found by `mdcache_find_keyed`.

The stack is:
nfs4_op_readdir -> fsal_readdir -> mdcache_readdir_uncached -> {our fsal}_readdir -> mdc_readdir_uncached_cb -> mdcache_new_entry

To reproduce this problem:
1. there are 2 ganesha mount the same filesystem
2. client1 connect ganesha1, client2 connect ganesha2,
    when mount,set actimeo=30, such as: `mount -t nfs4 -o minorversion=1,soft,port={ganesha port},actimeo=30 {ganesha ip}:/ /mnt`
3. create dir /mnt/tmp
4. client1: touch /mnt/tmp/file1
5. client2: ls -l  /mnt/tmp/
6. client1: rm -rf f10000 && chown user1:group1 f1 && touch f10000
7. client2: ls -l /mnt/tmp/, client2 will send readdir request to ganesha2, but you will find f1's user and group change to user1:group1 until actimeo(30 s) timeout, even though the readdir of fsal return user1:group1 in advance.

**Comment by ffilz** [comment]
Interesting and definitely a bug. Will add this to the "todo" for V4.1.

**Comment by liyinshubyte** [comment]
@ffilz Can I fix this ? Is it enough to use attrs_in  to overwrite entry's attr ?

**Comment by ffilz** [comment]
I think so, you need to make sure you have the appropriate lock to change the attr.

**Comment by liyinshubyte** [comment]
@ffilz Hi, I submit the patch, could you help review it ? Thanks a lot. 

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/532938
