### ISSUE TITLE
Session Trunking

### ISSUE THREAD

**Issue by crispyduck00** [nfs-ganesha/nfs-ganesha#784]
Is nfs ganesha supporting session trunking? Can not find anything about it. Only that it should be part of nfs 4.1.
I have some issues with ESXi 6.7-7u2. 

I had this runnig for some years with FreeBSD as NFS4.1 server and several ESXi 6.5-6.7 hosts.
All with 4x 1G in different VLANs and on different subnets.

I am now trying to switch to Linux and nfs ganesha as NFS server. Can muont the share as datastore via 4.1, but have ongoing errors in the esx kernel log and looking on the network it seems only one uplink is utilized.

Should this be supported? If so, I can provide logs and traces.

Br

**Comment by ffilz** [comment]
No we don't support it, see https://github.com/nfs-ganesha/nfs-ganesha/issues/398

Closing as a duplicate
