### ISSUE TITLE
I/O ERROR (error 5) occurs when the client open the file

### ISSUE THREAD

**Issue by betainc** [nfs-ganesha/nfs-ganesha#785]
1 Software version
centos：8.2
nfs-gaensha：3.3
nfs client：nfs-utils-2.3.3-31
ceph：14.2.19
ctdb：4.13.5

2 Cluster information
A three node ceph cluster with nfs-ganesha enabled on each node. 
CTDB is used to implement HA, configure virtual IP, and manage nfs.
An NFS client that mounts NFS via virtual IP.
The time between the client and the server is out of sync, with a gap of ten minutes.

RADOS_URLS {
        ceph_conf = "/etc/ceph/ceph.conf";
        userid = "admin";
}

NFSV4 {
        Grace_Period = 30;
        Lease_Lifetime = 10;
        RecoveryBackend = rados_kv;
}

RADOS_KV {
        pool = "pool_meta";
}

EXPORT {
        Export_Id = 1;
        Path = /test;
        Protocols = 3,4;
        Access_Type = RW;
        Squash = no_root_squash;
        Pseudo = /test1;
        Attr_Expiration_Time = 0;
        FSAL {
                Name = CEPH;
        }
}

3 testing scenarios
1) An nfs client mounts the ceph file directory shared by nfs-ganesha through a virtual IP(For example, 101.101.8.202 on node2 host-192-168-138-102).
   101.101.8.202:/test on /mnt type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=101.101.8.101,local_lock=none,addr=101.101.8.202)

2) The client runs vdbench to write files to the nfs export directory.
3) On the nfs-ganesha node2, ifdown the network card where the virtual IP(101.101.8.202) is located，recovery after 20s.
4) There is a small probability that vdbench will exit abnormally, indicating that the file failed to open, I/O error.

4 problem analysis
1) vdbench log
logfile.html
19:45:54.049       2986    0.0  0.000   5.9 1.10   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
19:45:55.047       2987    0.0  0.000   3.5 0.85   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
19:45:56.046       2988    0.0  0.000   5.8 1.22   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
19:45:57.044       2989    0.0  0.000   1.2 0.56   0.0    0.0  0.000    0.0  0.000  0.00  0.00   0.00       0   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000   0.0  0.000
19:45:57.924 *
19:45:57.924 ************************************************************************************
19:45:57.924 * Slave hd1-0 aborting: open failed for /mnt/vdb.1_37.dir/vdb_f1318.file *
19:45:57.924 ************************************************************************************
19:45:57.924 *
19:46:58.001 SocketException from aborting slave. That's OK.
19:46:58.429 
19:46:58.429 Slave hd1-0 prematurely terminated. 
19:46:58.429 
19:46:58.429 Slave aborted. Abort message received: 
19:46:58.429 open failed for /mnt/vdb.1_37.dir/vdb_f1318.file
19:46:58.429 
19:46:58.429 Look at file hd1-0.stdout.html for more information.
19:46:58.429 HTML link: hd1-0.stdout.html
19:46:58.430 SocketException from aborting slave. That's OK.
19:46:58.945 SocketException from aborting slave. That's OK.
19:46:58.945 
19:46:58.945 Slave hd1-0 prematurely terminated. 
19:46:58.945 
java.lang.RuntimeException: Slave hd1-0 prematurely terminated. 
	at Vdb.common.failure(common.java:335)
	at Vdb.SlaveStarter.startSlave(SlaveStarter.java:198)
	at Vdb.SlaveStarter.run(SlaveStarter.java:47)

hd1-0.stdout.html
19:44:17.719 19:44:17.718 Message to master: anchor=/mnt: Created 175000 of 2500000 files (7.00%)
19:45:57.880 19:45:57.879 error: 5
19:45:57.880 19:45:57.879 file_open(), open /mnt/vdb.1_37.dir/vdb_f1318.file failed
19:45:57.880 19:45:57.880 Maximum native memory allocation:    1,048,576; Current allocation:    1,048,576
19:45:57.880 19:45:57.880 
19:45:57.880 19:45:57.880 open failed for /mnt/vdb.1_37.dir/vdb_f1318.file
19:45:57.880 19:45:57.880 
19:45:57.881 java.lang.RuntimeException: open failed for /mnt/vdb.1_37.dir/vdb_f1318.file
19:45:57.881 	at Vdb.common.failure(common.java:335)
19:45:57.881 	at Vdb.ActiveFile.openFile(ActiveFile.java:172)
19:45:57.881 	at Vdb.FwgThread.openForWrite(FwgThread.java:435)
19:45:57.881 	at Vdb.OpCreate.doOperation(OpCreate.java:53)
19:45:57.881 	at Vdb.OpFormat.doOperation(OpFormat.java:100)
19:45:57.881 	at Vdb.FwgThread.run(FwgThread.java:205)

vdbench test script:
messagescan=no
hd=default,vdbench=/home/tecs/vdbench50406,user=root,shell=ssh
hd=hd1,system=localhost
fsd=fsd1,anchor=/mnt/,depth=1,width=500,files=5000,size=1M,shared=yes
fwd=fwd1,fsd=fsd1,fileio=random,fileselect=sequential,rdpct=30,threads=32
rd=rd1,fwd=fwd1,fwdrate=max,format=(restart,only),elapsed=120000,interval=1

2) nfs-ganesha
Every time this error occurs, just when the network card is ifdown, or other failover scenarios.
ctdb will migrate the IP(101.101.8.202) to node 1(host-192-168-138-101) from node2, node1 take over the IP,
ctdb notifies ganesha to enter the grace process.

nfs-ganesha is in the grace process, Client's lease expired, then there is the normal grace process.
No other error messages are seen in the ganesha log.

09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip 101.101.8.202
09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] nfs_release_nlm_state :STATE :DEBUG :Release all NLM locks
09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] cancel_all_nlm_blocked :STATE :DEBUG :Cancel all blocked locks
09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] cancel_all_nlm_blocked :STATE :F_DBG :No blocked locks
09/12/2021 19:59:30 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[dbus_heartbeat] nfs4_recovery_load_clids :STATE :DEBUG :Load recovery cli 0x7f3315113fe0
09/12/2021 19:59:31 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_267] rpc :TIRPC :EVENT :svc_vc_wait: 0xbb9c300 fd 23 recv errno 104 (will set dead)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] export_check_access :EXPORT :M_DBG :EXPORT_DEFAULTS (options=00000000/00000000               ,     ,    ,               ,               ,         ,                ,                ,                )
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] export_check_access :EXPORT :M_DBG :default options (options=03303002/ffffffff root_squash   , ----, 34-, UDP, TCP, ----, No Manage_Gids, -- Deleg, anon_uid=    -2, anon_gid=    -2, expire=      60, none, sys)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] export_check_access :EXPORT :M_DBG :Final options   (options=03303002/ffffffff root_squash   , ----, 34-, UDP, TCP, ----, No Manage_Gids, -- Deleg, anon_uid=    -2, anon_gid=    -2, expire=      60, none, sys)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 1 operations, res = 0xd904500, tag = NO TAG
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] nfs41_Session_Get_Pointer :SESSIONS :F_DBG :Get Session sessionid=(16:0x160000002be3b1611700000000000000)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] nfs41_Session_Get_Pointer :SESSIONS :F_DBG :Session sessionid=(16:0x160000002be3b1611700000000000000) Found
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] nfs4_op_sequence :SESSIONS :DEBUG :SEQUENCE session=0x33a41e00
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] reserve_lease :CLIENT ID :F_DBG :Reserve Lease 0xbb9af00 ClientID={Epoch=0x61b1e32b Counter=0x00000016} CONFIRMED Client={0x1b1b0a0 name=(32:Linux NFSv4.2 host-192-168-8-101) refcount=1} t_delta=10 reservations=0 refcount=4 (Valid=NO 0 seconds left)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] nfs4_op_sequence :SESSIONS :DEBUG :SEQUENCE returning status NFS4ERR_EXPIRED
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] complete_op :NFS4 :F_DBG :Current FH  Len=0 (EMPTY)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] complete_op :NFS4 :F_DBG :Saved FH    Len=0 (EMPTY)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] complete_op :NFS4 :DEBUG :Status of OP_SEQUENCE in position 0 = NFS4ERR_EXPIRED, op response size is 4 total response size is 40
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_EXPIRED lastindex = 1
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_273] release_nfs4_res_compound :NFS4 :F_DBG :Compound Free 0x38e609c0 (resarraylen=1)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_306] export_check_access :EXPORT :M_DBG :EXPORT_DEFAULTS (options=00000000/00000000               ,     ,    ,               ,               ,         ,                ,                ,                )
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_306] export_check_access :EXPORT :M_DBG :default options (options=03303002/ffffffff root_squash   , ----, 34-, UDP, TCP, ----, No Manage_Gids, -- Deleg, anon_uid=    -2, anon_gid=    -2, expire=      60, none, sys)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_306] export_check_access :EXPORT :M_DBG :Final options   (options=03303002/ffffffff root_squash   , ----, 34-, UDP, TCP, ----, No Manage_Gids, -- Deleg, anon_uid=    -2, anon_gid=    -2, expire=      60, none, sys)
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_306] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 4 operations, res = 0xbcb0f00, tag = NO TAG
09/12/2021 19:59:38 : epoch 61b1e32b : host-192-168-138-101 : ganesha.nfsd-2376830[svc_306] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE

3) nfs client
The NFS client did not see any obvious error at this time, only saw the lease expiration information returned by ganesha.

19:45:57 host-192-168-8-101 kernel: [810584.080294] nfs41_sequence_process: Error -10011 free the slot
19:45:57 host-192-168-8-101 kernel: [810584.080297] nfs4_free_slot: slotid 3 highest_used_slotid 2
19:45:57 host-192-168-8-101 kernel: [810584.080298] nfs41_sequence_call_done ERROR -10011
19:45:57 host-192-168-8-101 kernel: [810584.080299] nfs4_schedule_lease_recovery: scheduling lease recovery for server test.com
19:45:57 host-192-168-8-101 kernel: [810584.080334] nfs41_sequence_call_done rpc_cred 00000000b2f169b8
19:45:57 host-192-168-8-101 kernel: [810584.080335] <-- nfs41_sequence_call_done
19:45:57 host-192-168-8-101 kernel: [810584.080340] nfs4_schedule_state_renewal: requeueing work. Lease period = 5
19:45:57 host-192-168-8-101 kernel: [810584.080348] --> nfs4_alloc_slot used_slots=0007 highest_used=2 max_slots=64
19:45:57 host-192-168-8-101 kernel: [810584.080351] <-- nfs4_alloc_slot used_slots=000f highest_used=3 slotid=3
19:45:57 host-192-168-8-101 kernel: [810584.080361] encode_sequence: sessionid=22:1639047979:23:0 seqid=5010 slotid=3 max_slotid=3 cache_this=0
19:45:57 host-192-168-8-101 kernel: [810584.081197] nfs: server test.com OK
19:45:57 host-192-168-8-101 kernel: [810584.081200] NFS: nfs_pgio_result:  4648, (status -10011)
19:45:57 host-192-168-8-101 kernel: [810584.081202] nfs41_sequence_process: Error -10011 free the slot 
19:45:57 host-192-168-8-101 kernel: [810584.081206] nfs4_free_slot: slotid 2 highest_used_slotid 3
19:45:57 host-192-168-8-101 kernel: [810584.081829] nfs41_sequence_process: Error -10011 free the slot
19:45:57 host-192-168-8-101 kernel: [810584.081830] nfs4_free_slot: slotid 3 highest_used_slotid 1
19:45:57 host-192-168-8-101 kernel: [810584.081831] nfs41_sequence_call_done ERROR -10011 
19:45:57 host-192-168-8-101 kernel: [810584.081831] nfs4_schedule_lease_recovery: scheduling lease recovery for server test.com
19:45:57 host-192-168-8-101 kernel: [810584.081832] nfs41_sequence_call_done rpc_cred 00000000b2f169b8
19:45:57 host-192-168-8-101 kernel: [810584.081833] <-- nfs41_sequence_call_done
19:45:57 host-192-168-8-101 kernel: [810584.081839] nfs4_schedule_state_renewal: requeueing work. Lease period = 5
19:45:57 host-192-168-8-101 kernel: [810584.081842] <-- nfs4_proc_sequence status=-10011 
19:45:57 host-192-168-8-101 kernel: [810584.081844] nfs4_recovery_handle_error: handled error -10011 for server test.com 
19:45:57 host-192-168-8-101 kernel: [810584.081845] nfs: server test.com OK
19:45:57 host-192-168-8-101 kernel: [810584.081847] nfs41_sequence_process: Error -10011 free the slot
19:45:57 host-192-168-8-101 kernel: [810584.081859] nfs4_free_slot: slotid 0 highest_used_slotid 1
19:45:57 host-192-168-8-101 kernel: [810584.081863] nfs4_map_errors could not handle NFSv4 error 10011
19:45:57 host-192-168-8-101 kernel: [810584.081877] NFS: permission(0:57/1099520521976), mask=0x3, res=0
19:45:57 host-192-168-8-101 kernel: [810584.081912] nfs: server test.com OK
19:45:57 host-192-168-8-101 kernel: [810584.081914] NFS: nfs_pgio_result:  4652, (status -10011)
19:45:57 host-192-168-8-101 kernel: [810584.081915] nfs41_sequence_process: Error -10011 free the slot
19:45:57 host-192-168-8-101 kernel: [810584.081916] nfs4_free_slot: slotid 1 highest_used_slotid 4294967295
19:45:57 host-192-168-8-101 kernel: [810584.082189] --> nfs4_proc_create_session clp=000000009adabca0 session=0000000065ad2692
19:45:57 host-192-168-8-101 kernel: [810584.082192] nfs4_init_channel_attrs: Fore Channel : max_rqst_sz=1049620 max_resp_sz=1049480 max_ops=8 max_reqs=64
19:45:57 host-192-168-8-101 kernel: [810584.082193] nfs4_init_channel_attrs: Back Channel : max_rqst_sz=4096 max_resp_sz=4096 max_resp_sz_cached=0 max_ops=2 max_reqs=16
19:45:57 host-192-168-8-101 kernel: [810584.082201] NFS: atomic_open(0:57/1099520521976), vdb_f1319.file  ////Open the next file

Currently, I have no clue as to which module is causing the problem, nfs-ganesha, ceph, ctdb, nfs client or vdbench?
Any suggestions or ideas? Thanks!

**Comment by ffilz** [comment]
Jeff Layton has done some Ceph HA work, but instead of moving virtual IP from one node to another, each virtual IP is associated with one containerized Ganesha instance, so HA is accomplished by standing up a new container, possibly on a different node. At least that's how I understand it. I've asked Jeff to weigh in here.

**Comment by ffilz** [comment]
Also, we are technically no longer supporting Ganesha V3.x upstream with the release of Ganesha V4.0. I don't think there are any fixes in V4.0 that aren't in V3.5. You should at least upgrade to V3.5 which definitely has some Ceph fixes if not to V4.0.

**Comment by jtlayton** [comment]
>  A three node ceph cluster with nfs-ganesha enabled on each node.

Does this mean you're running ganesha in parallel on all three nodes? And you're just moving the IP address around to "fail over"?

If so, then the NFS4ERR_EXPIRED makes sense here. You shifted the client to a completely separate server, and it presented a stateid to the server that was unrecognized. You didn't impose a grace period, so there was no reclaim. The rados_kv backend is only built to work with a single host at a time. You may see data corruption in the client tracking db if you're running several hosts vs. the same db at the same time.

If you want to "roll your own" clustering over cephfs, you may want to read over this blog post to get a foundation:

https://jtlayton.wordpress.com/2018/12/10/deploying-an-active-active-nfs-cluster-over-cephfs/

Note that any sort of active/active clustering with NFSv3 is completely uncharted territory. YMMV.

**Comment by betainc** [comment]
@jtlayton
Thanks for your reply.
Yes, ganesha is running in parallel on all three nodes.

Ceph cluster built with three physical servers, nfs-ganesha and ctdb started on each server.
Multiple servers to export the same data in parallel.

Each nfs-ganesha provides the same file sharing service to clients in parallel.
This deployment is three independent NFS servers that are serving out the same backend filesystem. 
RADOS_KV is our recovery backend, but I'm not sure if that makes sense.

CTDB is responsible for implementing HA, managing a set of virtual IPs, each node is assigned a virtual IP.
Clients may mount NFS through any virtual IP, and different clients may mount through different virtual IPs.

When a node fails, CTDB takes care of migrating its virtual IP to other nodes, and notify nfs-ganesha to enter the grace process through dbus.
The ganesha on the node taking over this IP recovers the data from the rados backend, but it seems like the read fails. 
However, grace completed normally, and the client returned to normal after dozens of seconds.
Our HA implementation method can restore the business normally most of the time, but there is a small probability that unexpected problems will occur.
Just like here only one file fails to open, the next file is normal.

So, we moved the IP and notified ganesha to enter grace and reclaim. Is this a problem?
Seeing that your article says rados_cluster, so rados_kv is not suitable for this scenario?

**Comment by betainc** [comment]
@ffilz 
Thanks for your reply.
The version of ganesha is a bit low. I will consider upgrading the version to test it later to see if the new version has this problem.
According to Jeff Layton, there may be a problem with my configuration, and I want to figure out why the I/O Error occurs first.

**Comment by jtlayton** [comment]
> So, we moved the IP and notified ganesha to enter grace and reclaim. Is this a problem? Seeing that your article says rados_cluster, so rados_kv is not suitable for this scenario?

It isn't. You'll have all 3 machines competing to read and write from the same object, without coordinating between them. If you plan to run multiple ganesha heads in parallel, then you probably want rados-cluster.

Also, any reason you're rolling your own NFS setup here and not using the stuff built into ceph's management layer?

See: https://docs.ceph.com/en/latest/mgr/nfs/

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
