### ISSUE TITLE
CMake should not download

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/nfs-ganesha#79]
In _2.3~rc5_ I've noticed that [CMakeLists.txt](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/CMakeLists.txt#L922) may attempt to download _libntirpc_ during build. This is wrong because it fails in clean build environments without internet access (e.g. on Debian build servers, etc.).

CMake should not download anything during build. Also it is a potential security problem.

**Comment by ffilz** [comment]
Note that if you are building in a specific environment, the recommendation is that you install the specific libntirpc.

This download really isn't that much different than the previous submodule...

The option to download the latest is provided to allow those active in the development community to automatically pick up the latest libntirpc.

**Comment by dang** [comment]
A debian build server (or, indeed, any packaging system) should be packaging ntirpc separately from ganesha.  However, I'll see if I can manage to convince it to not update if it's already in place.

**Comment by dang** [comment]
Note that the build can be pointed at a local repo via -DNTIRPC_CLONE_URL=/path/to/repo

**Comment by dang** [comment]
This was reverted to a submodule.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
