### ISSUE TITLE
Useless files?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nfs-ganesha/nfs-ganesha#790]
Are these files still useful?
* [`src/ReleaseNote`](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/ReleaseNote)
* [`src/rpm_changelog`](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/ChangeLog)

**Comment by ffilz** [comment]
Hmm, I thought I had got rid of those. There's also src/ChangeLog that hasn't been updated in a long time, I think we can safely get rid of it also. At this point, ancient history is preserved in git (and all those files are preserved in stable branches).

**Comment by ffilz** [comment]
So go ahead and get rid of those files also.

**Comment by DimitriPapadopoulos** [comment]
Removed `src/ChangeLog` too.

**Comment by ffilz** [comment]
V4.3 has been tagged with a fix for this issue. Closing.
