### ISSUE TITLE
Update checkpatch.pl

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nfs-ganesha/nfs-ganesha#791]
Update to the latest version from Linux kernel source tree:
* [`scripts/checkpatch.pl`](https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl)
* [`scripts/spelling.txt`](https://github.com/torvalds/linux/blob/master/scripts/spelling.txt)

I would need to bypass commit hooks, because `checkpatch.pl` finds typos in its own `spelling.txt` file:
```
$ git commit -S -s scripts/checkpatch.pl scripts/spelling.txt 
WARNING: 'abitrary' may be misspelled - perhaps 'arbitrary'?
#3637: FILE: src/scripts/spelling.txt:12:
+abitrary||arbitrary
 ^^^^^^^^

[...]
```

Suggestions?

**Comment by ffilz** [comment]
Go ahead an submit a patch for that. I have an invocation to run checkpatch on the entire code base. Now is a good time to make a change like this before anyone starts using V4.x in production we can make sure to get all this cleanup stuff into V4.1 and push folks to use that in production. Then when we are backporting to v4-stable, we won't wind up with manual merges due to cleanup.

**Comment by DimitriPapadopoulos** [comment]
I need to modify the pre-commit hook, instructing `checkpatch.pl` to ignore itself:
```
git diff --cached  $against | $topdir/src/scripts/checkpatch.pl \
```
Will try this:
[Want to exclude file from "git diff"](https://stackoverflow.com/questions/10415100/want-to-exclude-file-from-git-diff#39943727)

**Comment by ffilz** [comment]
I ran the latest kernel checkpatch against the Ganesha source. It's asking for an SPDF license line for every file... Looking into the best way to get all those in... That will be handy since it then makes a one line you can grep for to verify licenses...

**Comment by DimitriPapadopoulos** [comment]
In the short term, it will not be asking for an SPDX licence line with `--ignore SPDX_LICENSE_TAG`.

**Comment by ffilz** [comment]
I posted a patch series that includes the latest checkpatch.pl, updates the config file, provides fixes for most of the errors and warnings reported, and a major effort to indicate licensing of files.

This is the head patch in the series:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/533010

**Comment by ffilz** [comment]
V4.3 has been tagged with a fix for this issue. Closing.
