### ISSUE TITLE
Question about design doc.

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#792]
@ffilz Hi, is there any design doc of ganesha ? I want to learn the design of mdcache and lru. Thanks a lot.

**Comment by ffilz** [comment]
Unfortunately we didn't do any design documentation... There are bits and pieces where I scratched something out on paper and discarded it. I don't know what other developers have done. We DO try to include some information about functions in the Doxygen comments ahead of the function, and we try to document tricky bits in comments in the code.

That said, you can feel free to use this issue to ask specific questions about the design and we can try to help you.
