### ISSUE TITLE
Question about node_k in cih_get_by_key_latch

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#793]
@ffilz @dang Hi, I found we use `k_entry.fh_hk.node_k` to find node in `cih_get_by_key_latch`, i.e. `node = cih_fhcache_inline_lookup(&latch->cp->t, &k_entry.fh_hk.node_k);`. But it seems we did not assign any value to k_entry.fh_hk.node_k, and I also print the fileds of node_k, i.e. left, right, parent, the fileds  actually did not has value, other than the initial value. Is it a bug ?

**Comment by dang** [comment]
In cih_set_latched(), we call avltree_insert(&entry->fh_hk.node_k, &cp->t); which sets node_k.  cih_remove_latched() also calls avltree_remove(), which will clear node_k.

**Comment by ffilz** [comment]
Does that resolve your question? If so, please close the issue.

**Comment by liyinshubyte** [comment]
@dang @ffilz sorry, but one question, k_entry is a local variable in cih_get_by_key_latch, and has no chance to set node_k by avltree_insert, so where does the value of k_entry.fh_hk.node_k comes from ?

**Comment by Vicente-Cheng** [comment]
`cih_get_by_key_latch` try to get entry from cache and avltree.
It is used for checking. You could find that on `mdcache_new_entry`/`mdcache_find_keyed_reason`.

avltree_insert is called by cih_set_latched, you could find on mdcache_new_entry.
That update mdcache lru then insert an entry to avl tree.

If you set up dir_chunk, another avltree_insert would be called on dir entry related function.

@ffilz @dang,
I am not sure what I realize from codes is 100% correct if I got something wrong, please correct me.
thanks!

**Comment by dang** [comment]
@liyinshubyte You're correct, cih_get_by_key_latch() never sets it, but cih_set_latched() does.  That operates on &entry->fh_hk.node_k

@Vicente-Cheng Your analysis is correct.

**Comment by liyinshubyte** [comment]
@Vicente-Cheng @dang Thanks the answer, got it.
