### ISSUE TITLE
cmake fails on latest (V4.0.2) with USE_GSS=ON

### ISSUE THREAD

**Issue by ctuffli** [nfs-ganesha/nfs-ganesha#794]
Running cmake from git sources (hash `4be14172541579c92a515bd92bed42a88e37b04a`) on an Ubuntu 21.04 systems fails to find `gssapi.h`

```
$ find /usr -name gssapi.h
/usr/include/mit-krb5/gssapi/gssapi.h
/usr/include/mit-krb5/gssapi.h
/usr/include/gssapi/gssapi.h
/usr/include/gssapi.h
$ cmake ../nfs-ganesha/src/
-- cmake version 3.18
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected an UNKNOWN Linux machine
-- toolchain options processed
CMake Warning at cmake/maintainer_mode.cmake:45 (message):
  CMAKE_BUILD_TYPE is not set, defaulting to Debug
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)


-- Compilation from within a git repository. Using git rev-parse HEAD
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib/x86_64-linux-gnu/mit-krb5/libkrb5.so;/usr/lib/x86_64-linux-gnu/mit-krb5/libk5crypto.so;/usr/lib/x86_64-linux-gnu/libcom_err.so;/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so
CMake Error at CMakeLists.txt:554 (message):
  Cannot find GSS libraries


-- Configuring incomplete, errors occurred!
See also "/home/ctuffli/dev/build-ganesha/CMakeFiles/CMakeOutput.log".
```
Initially did a `git clone` without the `--recursive` but followed up with an `git submodule update --init`

**Comment by Vicente-Cheng** [comment]
hi @ctuffli,
I test with 21.04 on cmake 3.18 and also installed libkrb5-dev (for krb5 and gssapi)

It looks fine to me.
Could you try to reset your build folder and run `cmake` command again?

there is my partial output for gssapi.h
```
root@nfs-ganesha-build:~/nfs-ganesha/build# cmake ../src/
-- cmake version 3.18
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- override default CMAKE_INSTALL_PREFIX = /usr
-- Detected a Linux Debian base machine
-- toolchain options processed
CMake Warning at cmake/maintainer_mode.cmake:45 (message):
  CMAKE_BUILD_TYPE is not set, defaulting to Debug
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)


-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Compilation from within a git repository. Using git rev-parse HEAD
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- found krb5-config here /usr/bin/krb5-config
-- Found kerberos 5 headers: /include
-- Found kerberos 5 libs:    /usr/lib/x86_64-linux-gnu/mit-krb5/libkrb5.so;/usr/lib/x86_64-linux-gnu/mit-krb5/libk5crypto.so;/usr/lib/x86_64-linux-gnu/libcom_err.so;/usr/lib/x86_64-linux-gnu/mit-krb5/libgssapi_krb5.so
-- Looking for include file gssapi.h
-- Looking for include file gssapi.h - found
```

**Comment by dang** [comment]
GSS libraries are frequently not installed on a base system.  On fedora-like systems, they're provided by krb5-devel, so something like that will be necessary on Ubuntu.

**Comment by ffilz** [comment]
Do we have the right package dependencies?

**Comment by kalebskeithley** [comment]
USE_GSS is enabled/on by default, no need to enable it explicitly. (Although it won't hurt.)  The cmake output confirms that USE_GSS is ON.

I was able to build HEAD of next branchon my 21.04 (hirsute) box.
The (minimum) set of dependendencies that I had to install were:
 + libkrb5-dev
 + pkgconf
 + libdbus-1-dev
 + liburcu-dev
 + bison
 + flex
 + doxygen

There may be others.


The cmake command I used was: cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DBUILD_CONFIG=rpmbuild   -DCMAKE_COLOR_MAKEFILE:BOOL=OFF    -DUSE_FSAL_NULL=ON -DUSE_FSAL_MEM=ON -DUSE_FSAL_XFS=OFF -DUSE_FSAL_LUSTRE=OFF -DUSE_FSAL_CEPH=OFF -DUSE_FSAL_RGW=OFF -DUSE_FSAL_GPFS=OFF -DUSE_FSAL_KVSFS=OFF -DUSE_FSAL_GLUSTER=OFF -DUSE_SYSTEM_NTIRPC=OFF -DUSE_9P_RDMA=OFF -DUSE_LTTNG=OFF -DUSE_ADMIN_TOOLS=OFF -DUSE_GUI_ADMIN_TOOLS=OFF -DUSE_RADOS_RECOV=OFF -DRADOS_URLS=OFF -DUSE_FSAL_VFS=OFF -DUSE_FSAL_PROXY_V4=ON -DUSE_FSAL_PROXY_V3=ON -DUSE_DBUS=ON -DUSE_9P=OFF -DDISTNAME_HAS_GIT_DATA=OFF -DUSE_MAN_PAGE=OFF -DRPCBIND=ON -D_MSPAC_SUPPORT=OFF -DSANITIZE_ADDRESS=OFF 

...
-- ENFORCE_GCC = OFF
-- USE_GTEST = OFF
-- USE_GSS = ON
-- TIRPC_EPOLL = TRUE
-- USE_9P = OFF
-- _USE_9P = OFF
...

Make sure you remove the CMakeCache.txt between invocations of cmake.

**Comment by kalebskeithley** [comment]
@dang reminds me that -DUSE_GSS is a tri-state config option and letting it take the default means it'll (silently) disable it if gssapi isn't found. It didn't.

And explicitly setting it will fail cmake if it's not found.  So I tried again, this time explicitly setting -DUSE_GSS.

And it worked that way as well.

**Comment by ctuffli** [comment]
@dang I believe the development libraries similar to what you suggested are installed:
```
$ dpkg -S /usr/include/gssapi.h
libkrb5-dev:amd64: /usr/include/gssapi.h
```
I removed the original build directory, created a new one, and re-ran ccmake. This time everything worked correctly. Thank you all for the pointers and sorry for the noise.
