### ISSUE TITLE
remove delete permission for NFS directory

### ISSUE THREAD

**Issue by koraykutanoglu** [nfs-ganesha/nfs-ganesha#795]
There is something I want to do but cannot do. After installing NFS server, I connect it to client server. But I want to set special permissions to this accessed directory. For example, I want all users (including root) on the client machine to be able to create a file in the NFS directory to which they are mounted, but not delete the file. The reason I want this is because I want to take a backup directly to the NFS mounted directory to avoid high disk usage when backing up. However, if my server is hacked, all backups in the NFS directory will be accessible. Therefore, files can be uploaded to the backup directory, but not deleted. I've looked into ACL and standard linux file permissions but without success. Is this possible?

**Comment by ffilz** [comment]
I'm not sure, the sticky bit might work here?

The only other option would be FSAL and backe nd that support NFSv4 ACLs, which at this time is pretty much just GPFS.

**Comment by koraykutanoglu** [comment]
After much research I came to the conclusion that this is not possible. Even if this is possible with ACL, you can set the file size to 0 bytes with tools like echo. In addition, directory permissions are shared instantly on NFS shares. So it is possible to change the directory permissions on the client. Maybe there is a way to prevent this. But I'd rather find an easier alternative than messing around with it.
