### ISSUE TITLE
Can NFS Client retry when OP_WRITE return error ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#802]
In our case, we hope nfs client can retry some times when OP_WRITE return error, can we achieve this ? We try some error code, for example NFS4ERR_IO, but it does not work.

If we retry in our fsal, the ganesha thread can not be released, because the thread is retrying, then ntirpc will create new thread for new request, maybe there are a lot of threads to create.

**Comment by dang** [comment]
I'm not sure I'm fully understanding the situation, but the error that means "retry" is NFS4ERR_DELAY.  I'm not sure if that's legal on a write or not.  Frank might have a better idea.  He's on vacation and will be back next week.

**Comment by liyinshubyte** [comment]
@dang Thanks the reply. Yes, I want to know which error code can make the nfs-client retry OP_WRITE.

**Comment by ffilz** [comment]
Yes, NFS4ERR_DELAY is a valid result for OP_WRITE.

Can you share any more details on what is going on that you want the client to retry? Retry of OP_WRITE is a bit expensive since the client will need to send the data again.

You could implement async I/O to retry and not block a thread.

**Comment by liyinshubyte** [comment]
Yes, this is good idea. Thanks a lot. @ffilz 
> You could implement async I/O to retry and not block a thread.

**Comment by liyinshubyte** [comment]
@ffilz The details is: we do some change to allocate a thread pool for each volume in ganesha, when some volume's thread pool was exhausted, we should not add new request into the volume's queue, otherwise the queue's memory will become too high, so in this case, we want to respond the new request with NFS4ERR_DELAY, so the client can retry the request. 

Besides, we not only want OP_WRITE to retry by client, but also all new request to retry. Is there a common error code for all request to retry ?

**Comment by ffilz** [comment]
Sorry for not responding for months...

Not quite sure what the question is, but ERR_FSAL_DELAY should translate to NFS4ERR_DELAY.

**Comment by ffilz** [comment]
Can we close this?
