### ISSUE TITLE
How to authorize nfs-client ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#804]
Currently we are using a load-balance service for automatically failover, which exports one vip to the nfs client. Nfs client builds the connection with the load-balance service, which is responsible to transfer the client request to one of backend nfs ganesha servers. For example
```
                 vip                                             one of the servers, e.g. ganesha_1
nfs client  ---->     load-balancing service              ------------------->        {ganesha_1, ganehsa_2, ganesha_3} 
```

We want to authorize some specified nfs-client can mount our filesystem.  But we can not config nfs-client ip/host in ganesha.conf, because we maybe add a lot of authorized clients dynamiclly.  How can we achieve this ?

**Comment by dang** [comment]
You can configure ganesha dynamically in two ways.  You can modify the config file, and send Ganesha a SIGHUP, or you can use the DBUS api to configure directly at runtime.

**Comment by liyinshubyte** [comment]
@dang Thanks the reply, but we may have thousands of clients, and it's hard to operation, maybe we need to add client everyday if have new user. And the config maybe too large.

**Comment by dang** [comment]
Then you can use the DBUS api, that's what it was designed for.

**Comment by liyinshubyte** [comment]
@dang I'm thinking whether kerberos can do this, give the keytab to the authorized client.

**Comment by dang** [comment]
possibly, but I think it would involve modifying ACLs on the filesystem for each new user you create.

That said, I doubt it would be easier or faster to update a kerberos server than it would be to update Ganesha with the new client info.

**Comment by ffilz** [comment]
Hmm, this is something that may need another way to handle. Since the client list is just a linked list, 1000s of clients may cause quite a slow down. Unfortunately I don't know any other way to handle it.

I'm labeling this as a question/enhancement while we discuss what a possible solution might be.

Hmm, Kerberos might work if you have a realm for the authorized clients. In that case, only an authorized client can get a valid Kerberos credential. Non-authorized clients will either get a Kerberos failure, or at best show up as "anonymous" which can be blocked from any effective access, I think with this you don't need ACLs, you just need to make sure nothing has any permissions granted to "other".

**Comment by liyinshubyte** [comment]
@ffilz Hi, thanks a lot for the reply. For example, we kinit to generate a ticket for "myuser", then mount ganesha. Can ganesha get "myuser" from request ? If yes, then we can check whether "myuser" has authority.

**Comment by ffilz** [comment]
So I think the way this would work with current code is that any client that could not get a valid Kerberos ticket would be forced to use non-Kerberos AUTH which would then be blocked from accessing any exports. You would have to play with Kerberos setup and see how it all works. Sadly, I don't do enough Kerberos to even be able to reliably set it up...

**Comment by liyinshubyte** [comment]
@ffilz  But If we use kerberos, we can not auth multi user from the same client. If use kerberos, in client, we must start rpc-gssd.service, rpc-gssd.service need the keytab, such as 1.keytab. Once rpc-gssd.service started, all the user in client must use the same keytab, i.e. 1.keytab.  So we can not auth user1 by user1.keytab.

**Comment by ffilz** [comment]
Multiple users should be able to acquire Kerberos credentials and there can be multiple users in the keytab.

**Comment by liyinshubyte** [comment]
@ffilz Hi,  can we use different keytab files in the same client ? Each user have their own keytab file. But if start rpc-gssd.service, we must use only one keytab file.

**Comment by ffilz** [comment]
A keytab can have multiple users credentials in it. Unfortunately my knowledge of Kerberos administration is somewhat limited, but I think you can have a keytab with all your users in it, and then share that among all your clients.
