### ISSUE TITLE
Free not only first entry

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#806]
Currently lru_reap_impl only check whether first entry of lq->q can be reclaimable. But sometimes, the first entry can not be reclaimed for a long time, then we have to malloc several million new mdcache_entry_t. The size of mdcache_entry_t is 1200 bytes, then the memory of mdcache_entry_t is serveral GB, which should be improved. So we check all the entries of lq_q, whether can be reclaimed, to avoid malloc so many mdcache_entry_t.

@ffilz @dang could you help review this ? thanks a lot.
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/535308

**Comment by Vicente-Cheng** [comment]
Hi @liyinshubyte,

I thought that lru_get would try to reclaim entry or allocate the new entry.
The reclaim behavior has a trade-off between performance and overhead.

The default LRU lanes are 17. The behavior now is that check 17 items (first entry of lane) from L2/L1. There is check most 17*2  times then we could create a new entry.
If we walk through the entire entry list. The overhead would be 17 * 2 * N times (N may be an average of your entries on lru).
The overhead looks more than now?

Furthermore, lru_run_lane does the similar things you want.
lru_run_lane would scan all entries and move the reclaimable item to L2.

And memory usage, lru_run do some cleanup if your mdcache_entries more than 100k, recycle 100 entries each time (100k and 100 are default value).
If the mdcache entries are not used. That would be put to L2/L1 to reclaim and also directly free from lru_run.

**Comment by liyinshubyte** [comment]
@Vicente-Cheng Thanks the reply.  Where the entries of L2 are freed.

> lru_run_lane would scan all entries and move the reclaimable item to L2.

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng Thanks the reply. Where the entries of L2 are freed.
> 
> > lru_run_lane would scan all entries and move the reclaimable item to L2.

lru_run_lane would move mdcache entries that could be released from L1 to L2.
When the entries are more than hiwater, lru_run would call `mdcache_lru_release_entries` to unref it last reference count.
When the last refcnt is decreased, the mdcache entry would be free.

**Comment by liyinshubyte** [comment]
@Vicente-Cheng Thanks the reply. I find only when [currentopen >= lru_state.fds_lowat](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c#L1371), ganesha will release  mdcache entries from L1 to L2. But in our ganesha, currentopen always be zero, so release from L1 to L2 will never happen. 

Then I check why `currentopen` always be zero, `currentopen` will increase when OP_CREATE, but when I touch file, there is OP_OPEN but no OP_CREATE,  so `currentopen` always be zero.

Besides, not sure why we need `currentopen >= lru_state.fds_lowat`, can we check the existed number of mdcache_entry_t ?


> lru_run_lane would move mdcache entries that could be released from L1 to L2.

**Comment by ffilz** [comment]
Are you only using NFSv4? If so, only COMMIT operations result in open_fd_count being incremented.

As a workaround, you could set FD_LOWAT_PERCENT to zero so that entries are always being demoted to L2.

**Comment by ffilz** [comment]
Added Matt and Daniel to the conversation.

**Comment by liyinshubyte** [comment]
> Are you only using NFSv4? If so, only COMMIT operations result in open_fd_count being incremented.

@ffilz Yes, I'm using NFSv4.1, then I know why open_fd_count always be zero, do we need to fix this ?

**Comment by liyinshubyte** [comment]
@ffilz @Vicente-Cheng @dang Just a friendly ping.

> Yes, I'm using NFSv4.1, then I know why open_fd_count always be zero, do we need to fix this ?

**Comment by Vicente-Cheng** [comment]
Hi @liyinshubyte, 

Sorry for the late reply, I am not digging too much for `open_fd_count`.
If you found some bugs on here, you could just propose a patch for it? 
That would make the maintainer (like frank, dang) know how you fix that.

For, the reclaim issue, I submit some patches to observe the reclaim ration (means reclaimed/total reclaim tries).
Also, add the parameter to make lru_get prefer to reuse entry.

I thought that we could fix `open_fd_count` and make some configurable parameters to make reclaim more efficient.
(Maybe also with some changes for `lru_run` and `lru_run_lane`)?

@ffilz and @dang are more familiar than me on `MDCACHE`. Maybe they have some suggestions for improving it :)

**Comment by ffilz** [comment]
I think we do need to look at NFSv4 only operation and consider what to do.

I think we really want to get the mdcache entries that have state (NFSv4 OPEN in particular) out of the LRU. They aren't reclaimable no matter where they are. Then what would remain is entries that are being referenced for metadata purposes only (READDIR, LOOKUP, GETATTR etc.) and NFSv3 if in use.

**Comment by liyinshubyte** [comment]
@ffilz @dang @Vicente-Cheng Hi, I submit a change at: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/536998, we can continue to discuss the fix.

**Comment by ffilz** [comment]
There is new LRU management slated for V5.0 that should alleviate most of the issues with reclaiming LRU entries if eligible.

Closing as we won't be pursuing the solution suggested in this issue.
