### ISSUE TITLE
how to use DRC ? could you give me some instruction?

### ISSUE THREAD

**Issue by megarzzy** [nfs-ganesha/nfs-ganesha#807]
https://github.com/nfs-ganesha/nfs-ganesha/wiki/Cluster-DRC
init_cmal/add_drc_entry(xid, entry)/retrieve_drc_entries(ip_address)/shutdown_cmal()
i can not find any symbols about "cmal" ,need I  to implement the four interface in which place?

**Comment by ffilz** [comment]
This proposal was never implemented.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
