### ISSUE TITLE
Question about pNFS

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#808]
Currently, we use ganesha in the following model, but the bandwidth of LoadBalance limit the throughput of cluster. For example, if the cluster throughput is 40GB, then the bandwidth of LoadBalance also should be more than 40GB, LoadBalance need a lot of machine to achieve this.
![image](https://user-images.githubusercontent.com/92144382/161010590-fb146187-001e-4154-9ed2-4abbb52c4a36.png)

So we want to eliminate the limit of LoadBalance, then we think should use pNFS in the following model, NFS client send data to DataServer directly. But this needs a lot of work,  for example, DataServer needs to support pNFS.
![image](https://user-images.githubusercontent.com/92144382/161010989-7cc6540e-551b-4c2e-8a00-78ec03b99139.png)

So we want to use the following model,  when NFS client call GETDEVICEINFO, we return ganesha address, then NFS client send data directly to ganesha, skip the LoadBalance, we can also eliminate the limit of LoadBalance bandwidth.
What do you think of this idea ? Does ganesha support this, i.e. accept data from pNFS.
![image](https://user-images.githubusercontent.com/92144382/161011251-e2216cbb-a7b9-44da-b39a-230fed380cc4.png)

**Comment by ffilz** [comment]
Ganesha can act as a DS, but I'm not sure what the state of pNFS is for Ganesha. FSAL_GPFS implements MDS and DS as an example.

**Comment by dang** [comment]
Expanding a bit: Ganesha is designed to operate as an MDS, a DS, or both, for pNFS.  When the feature was originally implemented, Ganesha was embedded into the data server (a variant on a Ceph OSD) to provide DS-only services directly from the same process as RADOS services.  This worked extremely well, with low latency and high throughput.

However, pNFS support is needed for the FSAL that is being used here.  It's not very complicated (7 ops for DS, 3 for MDS), but it does need to be done.  There's old, broken support for Ceph and Gluster, and (we believe) working support for GPFS, but nothing else.

**Comment by liyinshubyte** [comment]
@dang Thanks the reply. Why the Ceph support was broken, if pNFS works well in Ceph.

> There's old, broken support for Ceph and Gluster

**Comment by dang** [comment]
pNFS never worked in Ceph.  Ceph uses CRUSH to determine OSD/DS location, and CRUSH is not compatible with any published pNFS protocol.  What we did before was make a variation of Ceph that used a different protocol for determining OSD/DS location, and a preview to publishing a new pNFS protocol that could handle programatic layouts.  This work was never completed, as the company doing it ended.  All the work necessary to make Ganesha do MDS, MDS/DS, and DS-only, however, was completed, tested, and submitted.

**Comment by liyinshubyte** [comment]
@dang Thanks the reply. I have another question, sorry for that. In our case, such as there are 4 DataServer(each embed one ganesha), and when write 1MB file, we will split the 1MB file to 4 parts, and each DataServer write 0.25MB. For this case,  if we use pNFS, nfs-client should send 1MB to ganesha1(embedded into the data server), then ganesha1 split 1MB to 4 parts, and send 3 parts to the other 3 ganeshas(embedded into the data server). As the following image shows.

![image](https://user-images.githubusercontent.com/92144382/164581624-63f7c9ab-acb7-4363-a5a8-407600ed1398.png)

But the latency also is high, so can nfs-client respond for split 1MB to 4 parts, and send 4 parts to 4 ganeshas directly(embedded into the data server) ? As the following image shows.
![image](https://user-images.githubusercontent.com/92144382/164581632-4bbacee0-483c-4272-bee5-8a52cc90bd9b.png)

**Comment by mattbenjamin** [comment]
hi @liyinshubyte ;  what you describe in your second diagram is closer to what cohortfs did with ceph pnfs:  we returned a layout to the client that allowed the client to operate directly against all the data servers.  At a high level, that's the general approach most pNFS implementations have taken--they differ in other ways, of course.

**Comment by liyinshubyte** [comment]
@mattbenjamin Thanks the reply, do you mean current released pNFS in linux support the second diagram ?

**Comment by liyinshubyte** [comment]
@mattbenjamin  Besides, can we define how to split 1MB by ourselves ? For example, 
[0, 64KB)-> ganesha1
[64KB, 128KB) -> ganesha2
[128KB, 192KB) -> ganesha3
[192KB, 256KB) -> ganesha4
[256KB, 320KB) -> ganesha1
[320KB, 384KB) -> ganesha2
...

**Comment by mattbenjamin** [comment]
@liyinshubyte in the first instance, you need to decide what set of rules your implementation will follow.  cohortfs experimented with at least 2 different *layouts*.  First, we experimented with the nfsv4.1 files layout defined in (then) rfc5661.  Our collaborators Panasas were using the Object layout.  Some time later, Tom Haynes and other folks proposed the "Flex files" layout.  If I were starting a pNFS project today, I would try to base it on the flex files layout.  That sets some rules for how you can split the files--but you can make most of the decisions however you want.  Your data server in flex files will be accessed via the NFS protocol (which I think is preferable).  You can use nfs-ganesha ds-only setups for such data servers.  If you wanted, you could adapt the cohortfs ds driver for your layout--it used an efficient in-process version of Ceph's messenger for communications between nfs-ganesha's DS driver and the Ceph OSD data path (built on DirectMessenger).  You have other choices, it's up to you.

**Comment by mattbenjamin** [comment]
(As @dang explained earlier, our most advanced prototypes were based on our own programmable layout.  That kind of approach would require you to put custom logic in to NFSv4 clients--which obviously could be challenging to productize.)

**Comment by liyinshubyte** [comment]
@mattbenjamin Thanks the reply, in the following case, do we need to put custom logic in to NFSv4 clients ?  
[0, 64KB)-> ganesha1
[64KB, 128KB) -> ganesha2
[128KB, 192KB) -> ganesha3
[192KB, 256KB) -> ganesha4
[256KB, 320KB) -> ganesha1
[320KB, 384KB) -> ganesha2

**Comment by dang** [comment]
No, what you want to do should be easily doable in the FlexFiles layout defined in RFC 8435.

**Comment by liyinshubyte** [comment]
@dang Thanks the reply. I have another question. We will deploy ganesha in Cloud, then nfs-client and ganesha locate on different VPC(Virtual Private Cloud). Different VPC is network isolation, we need to depend on vpc1(nfs-client) -> LoadBalance -> vpc2(ganesha) to connect nfs-client and ganesha. If we use pNFS, maybe we still need LoadBalance to connect nfs-client and ganesha. So, can we skip LoadBalance when use pNFS ? i.e. nfs-client send data directly to ganesha, skip LoadBalance. Otherwise, the latency is still high.

**Comment by mattbenjamin** [comment]
The idea of going direct to the OSDs was to remove hops/proxying. It relied on the ability of Ceph or a similar scale-out storage at sub-file granularity to provide improved bw or latency to clients.  I see that you're doing something discretely different, and you'll need to model it carefully.  If you're seeking to terminate more clients than your storage servers are provisioned to handle, it seems like you could be looking at not merely load-balancers, but also caching?

**Comment by dang** [comment]
For pNFS to work, the NFS client needs network access to the Data Servers (DSs) in addition to the MetaData Server (MDS).  In normal NFS, a single Ganesha would act as both the MDS and the DS.  In pNFS, there's a single Ganesha that operates as MDS, and multiple Ganeshas that live on or very close to the storage that operate as DSs.  The client needs access to all of these.  You could, if you wanted, put a load balancer in front of the MDS, but you cannot load-balance in front of DSs, since the layout specifies particular DSs for the client to use.  The client needs direct access to the DSs.

**Comment by mattbenjamin** [comment]
> For pNFS to work, the NFS client needs network access to the Data Servers (DSs) in addition to the MetaData Server (MDS). In normal NFS, a single Ganesha would act as both the MDS and the DS. In pNFS, there's a single Ganesha that operates as MDS, and multiple Ganeshas that live on or very close to the storage that operate as DSs. The client needs access to all of these. You could, if you wanted, put a load balancer in front of the MDS, but you cannot load-balance in front of DSs, since the layout specifies particular DSs for the client to use. The client needs direct access to the DSs.

While this is true, a given DS, I believe, could be load-balanced.  (Clarifying;  in the cohortfs or panfs models, there was no reason to do that, but these folks are using pnfs for different reasons that we were.)

Matt

**Comment by MyqueWooMiddo** [comment]
Hello [liyinshubyte](https://github.com/liyinshubyte) . I also want to implement pNfs via ganesha, but I could not see EXPORT INFO in ganesha.log what I actually wrote in ganesha.conf . Can you show your config Demo for me ? ThX

**Comment by liyinshubyte** [comment]
@MyqueWooMiddo hi, sorry, I has not use pNFS, and still do not know how to use it.

**Comment by ffilz** [comment]
I'm not sure that Ganesha currently really has usable pNFS. Some FSALs are set up for it (GPFS for sure, Gluster? Others?) but I don't know of anyone who is active in our community calls and such that is using it.

**Comment by mattbenjamin** [comment]
> I'm not sure that Ganesha currently really has usable pNFS. Some FSALs are set up for it (GPFS for sure, Gluster? Others?) but I don't know of anyone who is active in our community calls and such that is using it.

It certainly has a pnfs server framework which has worked, in a couple of different modes.  Let's not discourage folks to attempt implementations. :)

Matt

**Comment by MyqueWooMiddo** [comment]
> > I'm not sure that Ganesha currently really has usable pNFS. Some FSALs are set up for it (GPFS for sure, Gluster? Others?) but I don't know of anyone who is active in our community calls and such that is using it.
> 
> It certainly has a pnfs server framework which has worked, in a couple of different modes. Let's not discourage folks to attempt implementations. :)
> 
> Matt

I've researched pNfs for a few days , kernel-Nfsv41 does not contain pNfs. Then I found ganesha which declare pNfs support .  

If you discourage user to do it with ganesha , what else you recommend ?

I our case :  
In a 10GE-LAN , there're a dozen Hadoop machines with big storage , but nearly full ; And there're a few other machines with big storage , quite empty but some services on it consume CPU & memory , which can provides big space for Hadoop storage extension . So I want let the other machines act as NfsServer , version in v4.1 .  
I do some test on the cluster , the performance could not satisfy us .  Then I supposed to try the pNfs feature .

**Comment by dang** [comment]
I'm not aware of any open-source implementation of a pNFS server that is actively used.  In Ganesha, FSAL_GLUSTER has pNFS support in Ganesha, but I don't know anyone who has used it in the past few years, so it may not work.  Certainly it used to work.

**Comment by mattbenjamin** [comment]
> I've researched pNfs for a few days , kernel-Nfsv41 does not contain pNfs. Then I found ganesha which declare pNfs support .
> 
> If you discourage user to do it with ganesha , what else you recommend ?
> 

I think nfs-ganesha is, in fact, the best available option.  We're just saying we don't know what issues you may run into.

Matt

**Comment by ffilz** [comment]
Yea, sorry, I didn't mean to imply that Ganesha wasn't usable for pNFS, just that it hasn't been actively used by folks engaged with the community, just be prepared for some bug fixing to get it working. But the basic infrastructure is all there so the effort should be modest.

What FSAL are you hoping to use pNFS with?

**Comment by MyqueWooMiddo** [comment]
> I'm not aware of any open-source implementation of a pNFS server that is actively used. In Ganesha, FSAL_GLUSTER has pNFS support in Ganesha, but I don't know anyone who has used it in the past few years, so it may not work. Certainly it used to work.

I see

**Comment by MyqueWooMiddo** [comment]
> > I've researched pNfs for a few days , kernel-Nfsv41 does not contain pNfs. Then I found ganesha which declare pNfs support .
> > If you discourage user to do it with ganesha , what else you recommend ?
> 
> I think nfs-ganesha is, in fact, the best available option. We're just saying we don't know what issues you may run into.
> 
> Matt

Thx

**Comment by MyqueWooMiddo** [comment]
> Yea, sorry, I didn't mean to imply that Ganesha wasn't usable for pNFS, just that it hasn't been actively used by folks engaged with the community, just be prepared for some bug fixing to get it working. But the basic infrastructure is all there so the effort should be modest.
> 
> What FSAL are you hoping to use pNFS with?

Whatever but prefer best throughput,  there are 5~10 big storage physical servers in my backend.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
