### ISSUE TITLE
why forking libntirpc?

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/nfs-ganesha#81]
https://github.com/nfs-ganesha/ntirpc seems to be an unnecessary fork of https://github.com/linuxbox2/ntirpc. For instance versions 1.3.0 released by both projects are binary-identical.
Please consider de-duplicating efforts and use releases of the original project.

**Comment by ffilz** [comment]
Ganesha does not fork libntirpc, it uses a git sub-module to pull libntirpc into the Ganesha tree for building.

An attempt was made to separate it, but that turned into disaster.

Red Hat (and others) have been successful with packaging libntirpc as a separate RPM, built from linuxbox2 directly.

At this point, unless someone comes up with a new scheme to attempt the separation, we have no plans to abandon the sub-module.

**Comment by onlyjob** [comment]
Directly sub-moduling libntirpc from linuxbox2 would cause less confusion. Other projects manage to sub-module without forking so can you.

**Comment by onlyjob** [comment]
Unfortunately de-facto it is a fork as there are pull requests, opened and closed... :(
Also Fedora ship forked v1.3.1 and not the original linuxbox2 project where v.1.3.1 do not exist yet.
