### ISSUE TITLE
READDIR returns SERVERFAULT when MDCACHE is disabled

### ISSUE THREAD

**Issue by assafyg** [nfs-ganesha/nfs-ganesha#812]
Using Ganesha version V4.0.3
Configuration is having PROXY_V3 FSAL mounted on an NFSv3 server while NFSv4.1 client is mounted on Ganesha export.

When having the following MDCache config:
`
MDCACHE {
        Dir_Chunk = 0;
}
`
and the directory has more than a certain amount of files (~170), the Ganesha responds with NFS4ERR_SERVERFAULT.
For filling the directory I did:
`for i in {1 .. 170}; do touch /mnt/nfs4/dircount/file$i; done`

If the MDCACHE config is removed or Dir_Chunk is set to other value than 0, the problem does not occur.
Note that the PROXY_V3 successfully calls READDIR on the backend server.

When the problem happens, the following log is printed in the ganesha log:
`03/04/2022 13:29:19 : epoch 6249a11c : r-901b26eb-a751-4606-bb6e-eacf-elfs-f6cd5779 : ganesha.nfsd-13095[svc_3] nfs4_readdir_callback :NFS READDIR :CRIT :Unexpected XDR failure processing readdir result`

P.S: The reason for configuring the MDCACHE Dir_Chunk to 0 is in order to prevent caching of dir entries and to perform always READDIR towards the backend server so changes done there won't be missed. Is there another way to achieve this?

**Comment by ffilz** [comment]
I'm not quite sure what's going on, unfortunately our support for PROXY is limited, I have never even tried to run PROXY.

If you are up for some debug, we might be able to get to the bottom of it.

I will also assign to Solomon Boulos who was working on PROXY, maybe he can take a look also.

**Comment by assafyg** [comment]
Indeed I could not reproduce this problem when using the VFS FSAL so I'll try to find out what is the difference between those two.
Yet, my final goal is to eliminate cases where there are changes to a directory that is done not through the local Ganesha node  and are missed by later NFSv4 READDIR call (this I could reproduce using the VFS FSAL).
Is there another way to prevent such case beside setting the 'Dir_Chunk' to zero?

**Comment by ffilz** [comment]
Anytime there are directory changes happening outside a Ganesha instance, any caching has potential to cause entries to be missed. You can tune the attribute timeout to make the window smaller, and the missing entries should eventually show up once the cache has been invalidated due to age (or other activity). This has been an issue for NFS forever...

If your FSAL has capability of sending some kind of notification when a directory changes, MDCACHE does provide cache invalidation up calls, but for example FSAL_PROXY would not be able to do this for directories since we don't (and maybe no one does) support directory delegations.

**Comment by boulos** [comment]
Interesting! Could you get a wireshark trace (like in #805) so we can see
the raw bytes?

**Comment by ffilz** [comment]
Is this still an issue? I'm not sure what we could do to resolve it, but just asking before I close this.

**Comment by assafyg** [comment]
We no longer use this setting.
I'll try to find time to reproduce and let you know.

**Comment by ffilz** [comment]
Bumping things that got depressed to to tagging other issues.

**Comment by ffilz** [comment]
Closing as the setting is not being used and it has been over 30 days with no response.

**Comment by assafyg** [comment]
Sorry for not reacting.
A bug in FSAL_PROXY_V3 implementation for not handling correctly the 'DIR_TERMINATE' in the proxyv3_readdir_process_entries  is the cause for this problem.

**Comment by ffilz** [comment]
OK, should I re-open this or will you be submitting a patch soon?

**Comment by assafyg** [comment]
I'm a little loaded now days so it will take me some time to reach it but I can prepare a fix.
Internally we don't use this code anymore.
