### ISSUE TITLE
crashed in nfs_dupreq_rele()

### ISSUE THREAD

**Issue by twoholes** [nfs-ganesha/nfs-ganesha#813]
hi, I have got a crashed problem like this:
![图片](https://user-images.githubusercontent.com/56353176/161887729-b486484b-269f-4c9f-a939-f5a90f88244e.png)

My version is 4.0.3. 
1、nfs_dupreq_rele() -->  dupreq_entry_put(dv)，  in dupreq_entry_put(dv), dupreq_entry_t will be released if refcnt == 0.
2、but after dupreq_entry_put be used, in line:1442 when we step into PTHREAD_MUTEX_lock(&dv->mtx), in step 1, dupreq_entry_t dv
     has been freed, so core dump will caused.

Has anyone met the preblem?

**Comment by ffilz** [comment]
I think that may be a dupe of 810. I think this also provides enough clues to find the problem, thanks for the report and details.

**Comment by ffilz** [comment]
Try this patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/535979

**Comment by twoholes** [comment]
> Try this patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/535979

thanks a lot for this patch.

**Comment by ffilz** [comment]
Does that resolve the issue?

**Comment by twoholes** [comment]
> Does that resolve the issue?

yeah .
hi, Is there any module for file cache, just like mdcache module.

**Comment by ffilz** [comment]
> > Does that resolve the issue?

Great, then we can probably close this issue (and leave the other issue open until the patch is absolutely verified and merged).

> yeah . hi, Is there any module for file cache, just like mdcache module.

Separate questions are best asked in new issues, however, the quick answer here is: No. people have contemplated a data cache module but no one has implemented one at this time.

**Comment by twoholes** [comment]
> 
I'm waitting in hope for the data module.
Thanks a lot for your answer.
