### ISSUE TITLE
Is it possible to add Link_support option to FSAL_CEPH ?

### ISSUE THREAD

**Issue by PopiBrossard** [nfs-ganesha/nfs-ganesha#814]
Dear maintainer,

I'm seeing some FSAL have the option `Link_Support` (and `Symlink_Support`). I think this option is interesting and could benefit the FSAL_CEPH. As the recommendations (https://docs.ceph.com/en/latest/cephfs/app-best-practices/#hard-links) says, hardlink are supported but users should avoid to use it.

It would be great if this option was settable in the FSAL_CEPH. If an administrator wants, he could block hardlinks creation on cephfs and avoid the extra performance cost of hardlinks. It allows administrator to have a cleaner cephfs without putting many efforts in scanning the FS and finding hardlinks to remove/replace them.

I'm aware you have limited ressources, but if you have time to implement this it would be great !

Thanks for your response.

**Comment by dang** [comment]
FSAL_CEPH has both symlink and link support enabled, with no way to disable them (at least, not in Ganesha)

**Comment by ffilz** [comment]
Closing as there is no intention to make any changes here.
