### ISSUE TITLE
Question: How to run multiple ganesha processes on one node?

### ISSUE THREAD

**Issue by Haroldll** [nfs-ganesha/nfs-ganesha#815]
My file storage backend is ceph, using libcephfs.
Recently, when I used vdbench to test ganesha performance, I found that the more ganesha, the better the performance.
For example, three NFS clients mount an export directory through three ganesha nodes, the performance of this scenario is not as good as five NFS clients and ganesha.

So I figured that increasing the number of ganeshas can increase performance when there are a lot of clients.
But if I don't have that many ganesha servers, how can I run multiple ganeshas on one server to increase performance?

Just like the nfs service in kernel mode, there will be 8 nfsd processes by default on a node server.
Any suggestion？Thanks！

**Comment by ffilz** [comment]
These days, I think the easiest way might be containers. I'm not familiar with all that you need to do to run Ganesha in a container though.

Another way to run multiple instances is to use NFSv4.0+ only and bind each process to a different IP address and don't use rpcbind.

This suggests the cephfs client is a limiting factor...

**Comment by Haroldll** [comment]
Thanks for your reply，I will try your suggestion.
