### ISSUE TITLE
mem leak in using acl_get_qualifier

### ISSUE THREAD

**Issue by mwang911** [nfs-ganesha/nfs-ganesha#819]
acl_get_qualifier will call malloc to get memory...

function find_entry and function posix_acl_2_fsal_acl use the acl_get_qualifier without freeing the memory...

not sure about other versions of libacl, but acl-2.2.53 calls the malloc in acl_get_qualifier...

why nfs-ganesha does not have the real self mem management pool...  it is also fine to directly use the talloc in samba ....

**Comment by kalebskeithley** [comment]
Not sure what you mean by "... have the real self mem management pool."

**Comment by jtlayton** [comment]
> acl_get_qualifier will call malloc to get memory...
> 
> function find_entry and function posix_acl_2_fsal_acl use the acl_get_qualifier without freeing the memory...

Huh? acl_get_qualifier(3) says _nothing_ about needing to free the memory that it returns. I don't see any sort of acl_free_qualifier function in the header, for instance. @mwang911 : Can you clarify why you believe this to be the case?

**Comment by jtlayton** [comment]
Oops, I stand corrected...you have to free the memory with acl_free(). So this sounds like it's a real bug.

**Comment by jtlayton** [comment]
> why nfs-ganesha does not have the real self mem management pool... it is also fine to directly use the talloc in samba ....

You haven't articulated why we'd need one. Note too that ganesha is heavily threaded, but talloc is not thread-safe on its own.

**Comment by ffilz** [comment]
OK, here's the fix

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/538577

**Comment by mwang911** [comment]
yep... multi threads is a problem for talloc ... 

I like the way of mem management in talloc, it is very easy to show the real mem usage in process.
While in ganesha, I am not sure where the mem is used in...  I have to handle mem leak with the help of  jemalloc or others...

Another thing... I see little madvise or munmap in strace the ganesha process  when this leak exists... 

I was thinking may be this little piece mem leak influence the whole mem block alloced by mmap... I see lots of 64MB blocks with libc... and I dont think it is all for the acl_get_qualifier...  Maybe... a own mem pool with alloc ahead will improve efficience of mem usage...  I am not sure about this...

**Comment by ffilz** [comment]
V4.3 has been tagged with a fix for this issue. Closing.
