### ISSUE TITLE
A question of rgw when mdcache has missed the FH.

### ISSUE THREAD

**Issue by twoholes** [nfs-ganesha/nfs-ganesha#821]
Hi, I have got a question for rgw. 
When mdcache miss the FH,  we need use func(create_handle()) to get the meta data.
But in rgw(ceph), fh and object info is cached in LRU(like mdcache), when rgw entry size get to hiwat, rgw will drop the fh<->object.
In that case, we can't transform fh to object, so stale handle will be meeted in NFS client?

**Comment by dang** [comment]
It looks like the FH cache in librgw isn't an LRU, but a tree that keeps every entry.

**Comment by ffilz** [comment]
Matt - do you have some thoughts on this?

I don't think this is in Ganesha code, but I'm a bit confused...

**Comment by mattbenjamin** [comment]
I'm not sure what's being said.  librgw iirc does keep every entry that nfs-ganesha thinks is an active handle, in the general case;  it can keep or discard handles that have been released;  we use invalidates only advisorily;  we rely on nfs-ganesha to manage the budget of handles

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
