### ISSUE TITLE
wrong file size on writing....

### ISSUE THREAD

**Issue by ciambellino** [nfs-ganesha/nfs-ganesha#822]
Hi all,
thsi my EXPORT:

    EXPORT
    {
            Export_Id = 222;
            Path = '/home';
            Pseudo = /home;
            Protocols = 3,4;
            Access_Type = RW;
            Disable_ACL = true;
            Squash = no_root_squash;
            Sectype = sys;
    
            FSAL {
                    Name = GLUSTER;
                    hostname="localhost";
                    volume="home";
            }
    }

Client mount: 

`mount -t nfs4 192.168.177.101:/home /home
`

when I download a file its size is wrong.

This is the correct file size

`-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2265972736 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso`

Those are a list of files downloaded:

```
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2275721216 30 mag 14.47 Rocky-8.6-x86_64-minimal.iso
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2292187136 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso_errata
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2275409920 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso_errata2
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2269118464 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso_errata3
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2277507072 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso_errata4
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2282700800 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso_errata5
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2270167040 16 mag 00.21 Rocky-8.6-x86_64-minimal.iso_errata6
-rw-rw-r--. 1 federico.fiordoliva federico.fiordoliva 2330144768 30 mag 14.36 Rocky-8.6-x86_64-minimal.iso_errata7
```

Each time it's different, each download finished without errors.
When i try to make a sha256sum, each file have different sum.

Thanks
Federico

**Comment by ffilz** [comment]
What version of Ganesha? Is the file being modified at all outside NFS? Or are you just trying to download a file that has been unchanged?

**Comment by ciambellino** [comment]
This is my version: `nfs-ganesha-4.0-1.el8s.x86_64`
The file was download from Rocky linux site, this is not the only file i tried to download.
I use a simple wget to download a file, the same issue if i get a file form scp.

If i mount the same volume with gluster client i don't have this issue, only on ganesha share on the same volume.
This is the Gluster version: `glusterfs-8.6-2.el8s.x86_64`

**Comment by ffilz** [comment]
Oh, so you are downloading the file using wget or scp onto an NFS mount?

Do you see any errors in the Ganesha log?

I'd be curious if you could set up a FSAL_VFS export and try the same thing.

We may need some debug or traces, which are always a challenge with something this big...

**Comment by ciambellino** [comment]
> Oh, so you are downloading the file using wget or scp onto an NFS mount?

yes, from client where NFS is mounted

> I'd be curious if you could set up a FSAL_VFS export and try the same thing.

if i setup VFS, the file was downloaded correctly 

> We may need some debug or traces, which are always a challenge with something this big...

I attached  the entire log debug level from start server to file download

[ganesha.log.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/8830861/ganesha.log.gz)

thanks a lot
Federico

**Comment by elehcim** [comment]
@ffilz Hello Frank, by chance any news on this? Thanks!

**Comment by ffilz** [comment]
Is this still an issue of interest? If so, we really need more analysis of what might be going wrong. Our team is pretty small and we have limited capacity to support issues outside the various products our team members work on.

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
