### ISSUE TITLE
fs_recovery_ng tries to delete files from the wrong directory when closing a session

### ISSUE THREAD

**Issue by Bog999** [nfs-ganesha/nfs-ganesha#828]
`V4.0.5`

When a client disconnects with umount, nfs-ganesha tries to delete the recovery data from the wrong path. This seems to be related to `v4_recov_dir_len` which is initialized 0, and not set to the right value when using fs_ng, but is used in `fs_rm_clid`.
```
ganesha.nfsd-51965[svc_12] fs_rm_revoked_handles :CLIENT ID :EVENT :opendir /::ffff:127.0.0.1-(24:Linux NFSv4.1 il-bogdanm) failed errno: No such file or directory (2)
```

**Comment by ffilz** [comment]
I think this is resolved in V4.3 which has recently been tagged. Closing as resolved.
