### ISSUE TITLE
GPFS lock_op: conflicting_lock->lock_type and flock.l_type aren't the same type

### ISSUE THREAD

**Issue by akiradeveloper** [nfs-ganesha/nfs-ganesha#83]
``` c
       if (conflicting_lock != NULL) {
                if (lock_op == FSAL_OP_LOCKT
                    && glock_args.flock.l_type != F_UNLCK) {
                        conflicting_lock->lock_length = glock_args.flock.l_len;
                        conflicting_lock->lock_start = glock_args.flock.l_start;
                        conflicting_lock->lock_type = glock_args.flock.l_type;
```

Hi.

I suspect this is a bug. The final line in this code fragment from `GPFSFSAL_lock_op` assigns different types badly assuming that l_type is always the same in all architectures (1,2,3 for F_RDLCK, F_WRLCK and F_UNLCK respectively). This assumption corrupts when it comes to some architecture that uses different numbers actually. (e.g. http://lxr.free-electrons.com/source/arch/alpha/include/uapi/asm/fcntl.h#L47)

I think you should convert l_type back to lock_type and then assign.

**Comment by ffilz** [comment]
This is a good catch, and affects several FSALs. Could you submit a patch to gerrithub to fix this?

**Comment by akiradeveloper** [comment]
Fine with me but I am asking my company boss if I can write you a patch. Once I get OK from him I will work on this.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
