### ISSUE TITLE
Unable to connect to v4 share on ganesha running in container from localhost or docker host

### ISSUE THREAD

**Issue by boutell** [nfs-ganesha/nfs-ganesha#830]
Ahrgh I'm so close.

I've installed the the `nfs-ganesha` and  `nfs-ganesha-vfs` ubuntu packages into a docker image based off `node-16`, which inherits from `ubuntu`. I'm using ganesha because like many useful base container images this one does not have the nfs kernel driver.

(I'm aware I could use a Docker bind mount, but this is a container for use as a portable dev environment, and filesystem performance inside the container is paramount for things like `npm install`. I wish to use an nfsv4 mount so that filesystem performance inside the container is not degraded — I'd rather have the host side of the connection be impacted, if anything. Anyway, off topic, so back to ganesha.)

Inside the container I set up `/etc/ganesha/ganesha.conf` as follows:

```
{
        Export_Id = 0;
        Path = /persistent;
        Pseudo = /persistent;
        Protocols = 4;
        Access_Type = RW;
        Squash = AllSquash;
        FSAL
        {
                Name = VFS;
        }
}
```

`/persistent` happens to be a persistent docker volume, but I also tried adding an export for an ordinary folder, with the same result.

I start up rpcbind and ganesha like this. It's weird that I need rpcbind at all since I'm only using v4, but without it, I eventually time out in my mount attempt:

```
/sbin/rpcbind
/usr/bin/ganesha.nfsd -C -N NIV_FULL_DEBUG -L /tmp/ganesha.log
```

When I launch this container I map ports like so:

```
docker create --name dev -v persistent:/persistent:delegated -p 3000:3000 -p 4049:2049 apostrophe-dev || exit 1
```

Note use of an alternate port in case the host is also an NFS server.

Now I try to mount from the Mac docker host. `/Users/boutell/persistent` is a real, empty folder on the host (a mount point):

```
sudo mount -t nfs -o port=4049 -o vers=4.0 localhost:/persistent /Users/boutell/persistent
```

I get this error message:

```
mount_nfs: can't mount /persistent from localhost onto /Users/boutell/persistent: No such file or directory
mount: /Users/boutell/persistent failed with 2
```

Things I have tried:

* If I change `4049` to `4050`, I time out, so I know the port option is being respected.
* Ditto `vers`, if I remove that I time out, probably because it's trying to connect to the rpc mapper etc. (not needed for v4).
* If I change `localhost:/persistent` to `localhost:/`, mount succeeds, but `/Users/boutell/persistent` still appears to be empty to `ls`, and it's not empty on the container. `ls -ld` produces slightly different output and it does show up in `mount`.
* If I change `Pseudo` to `/` in the ganesha config and try it from the top, mounting `/` still gives me the same "connects but appears to be empty" behavior.
* `Squash = None` and `Squash = AllSquash` give the same behavior.

If I try to make a loopback connection from inside the container, this is what I get:

```
mount -t nfs4 localhost:/persistent test
mount.nfs4: Operation not permitted
```

However since I'm in a container there's a good chance this has something to do with missing packages for the client side of NFS that I don't really want or need, so I'm not sure it's relevant here.

Here is the ganesha log file up to the point where I attempt to mount:

https://gist.github.com/boutell/f7dc1f8c3f4f6c885b11b2a9089749d8

And here is the ganesha log file *after* the point where I attempt to mount:

https://gist.github.com/boutell/daab620d084bb5be93fb28caf2282d0f

The complete repo is here, including the Dockerfile:

https://github.com/boutell/dev-container

Thank you so much for your help, and I apologize for the hefty logs. Not sure what else to do.

**Comment by boutell** [comment]
Ah, I simplified to sharing just that ordinary /test folder and looked more closely at the logs after setting up a `LOGS` block, and I found:

```
20/06/2022 20:46:22 : epoch 62b0dc9e : fb5681b5b95b : ganesha.nfsd-1958[main] vfs_map_name_to_handle_at :FSAL :DEBUG :Error Operation not permitted (1) bytes = 48
20/06/2022 20:46:22 : epoch 62b0dc9e : fb5681b5b95b : ganesha.nfsd-1958[main] vfs_lookup_path :FSAL :CRIT :Could not get handle for path /test, error Operation not permitted
```

This led me here:

https://github.com/nfs-ganesha/nfs-ganesha/issues/575

So apparently I'm just out of luck and this can't be done. Although, I will ask this person what they did to get around this, if anything:

https://github.com/NicolasT/contained-ganesha

**Comment by mattbenjamin** [comment]
hi @boutell   just for my information, are you *that* tom boutell?

**Comment by boutell** [comment]
LOL, yes.
