### ISSUE TITLE
ganesha crash at data->slot->cached_result is NULL 

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#831]
I have a ganesha core, the stack is nfs_worker_thread.c: nfs_rpc_process_request-> nfs4_Compound.c : nfs4_Compound -> nfs4_Compound.c: process_one_op -> nfs4_Compound.c: complete_op. Then I found data->slot->cached_result is NULL. But I do not know why this happen.

**Comment by ffilz** [comment]
What operations are in the compound? Are there any errors in the log?

**Comment by liyinshubyte** [comment]
@ffilz I found a case, for example, thread1:[PTHREAD_MUTEX_lock(&slot->lock)](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_sequence.c#L118)  -> [if (slot->sequence == arg_SEQUENCE4->sa_sequenceid) ](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_sequence.c#L122)(found request replay) -> [PTHREAD_MUTEX_unlock(&slot->lock)](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_sequence.c#L143) -> thread2: [PTHREAD_MUTEX_lock(&slot->lock)](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_sequence.c#L118) -> thread2: [release_slot(slot)](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_sequence.c#L188) (set cached_result to NULL) -> thread1: [data->res->res_compound4_extended = data->slot->cached_result](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_Compound.c#L689) (reference the NULL cached_result which set by thread2). Then this case happens.

**Comment by ffilz** [comment]
Where in thread2 did the release_slot call come from?

**Comment by ffilz** [comment]
Hmm, so the cached_result is refcounted....

Maybe SEQUENCE has to actually do the res_compound4_extended swap while the lock is held, then the refcount would protect the response even if the slot is released before the replay is actually sent.

**Comment by liyinshubyte** [comment]
@ffilz Hi, what do you think of this patch ?
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/541868

**Comment by liyinshubyte** [comment]
@ffilz I submit a new patch: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/542082

**Comment by ffilz** [comment]
V4.3 has been tagged with a fix for this issue. Closing.
