### ISSUE TITLE
Random mount hang for clients. (TCP issue?)

### ISSUE THREAD

**Issue by benedekmol** [nfs-ganesha/nfs-ganesha#833]
Hello!

EDIT!!!!!
Seems like this is not the issue I am facing. Sorry for the opened issue. My ganesha server just dropped every connection even though my RAM usage isn't that high.

I've been troubleshooting this for 3 weeks now when I have time. I suspected a network error somewhere, but it seems like the high RAM usage is the culprit. 
I have a ganesha server which serves Kubernetes pods with NFS storage. But at random times the Ganesha server stops responding at all for requests. I had INFO log level and nothing in logs. So I was troubleshooing it with wireshark and anything I could find to help me.
Client works fine. They send SYN requests as expected, but the ganesha server doesn't responde with anything, not even with a  reject or something. (I use NFSv4.2. And even nmap told me that port 2049 was filtered)

Yesterday I discovered that there is this setting:
![image](https://user-images.githubusercontent.com/22644581/177507707-a8eb6df7-0bbf-409d-848d-b40f2b80cc56.png)

And from this I figured to check RAM usage (kind of late but got there eventually) and in fact it was high. So I checked our Zabbix server and in fact there was correlation in RAM usage and the downtime. (I restarted the ganesha server when the available RAM jump up. After restart everything mounted properly and worked until the RAM usage wasn't that high.)
![image](https://user-images.githubusercontent.com/22644581/177507565-5fe07a9e-a738-43fd-bd64-1478c9d61096.png)

I will try to configure CACHEINODE settings for better RAM usage.

My suggestion is to create a high memory usage watermark log entry for these kind of issues. Beacuse it would have saved me a lot of time.
Thank you :)

**Comment by ffilz** [comment]
We are working on a redesign of the MDCACHE LRU and fd management that might help if memory really is the problem.

If something else is the problem, it would help to understand even if it's not a Ganesha problem so we can help others that have the same problem.

**Comment by benedekmol** [comment]
New development on the issue. When a pod can't mount it's NFS volume I execute this command on the nfs-ganesha VM:
`tcpkill -9 <IP of k8s node on which the pod runs>`

And everything works after that. (until the next hang)

I would really appreciate some help in this.
I will rename this issue for now.

**Comment by ffilz** [comment]
I'm really not sure how to help here. It seems like this is some kind of tcp stack issue and not a Ganesha issue.

**Comment by benedekmol** [comment]
Hello @ffilz !

My env so far was:
Ganesha server:
Ubuntu 20.04
nfs-ganesha/focal 3.0.3-0ubuntu3 amd64
nfs-ganesha-gluster/focal 3.0.3-0ubuntu3

NFS Clients:
Ubuntu 20.04
nfs-common/focal-updates,now 1:1.3.4-2.5ubuntu3.4 amd64

I just realized yesterday that there is a PPA for newer debian builds.
So I installed:
nfs-ganesha-gluster/focal,now 3.5-ubuntu1\~focal3 amd64
nfs-ganesha/focal,now 3.5-ubuntu1\~focal3 amd64

And now it seems to be working fine for the past 20 hours with a very basic configuration.

**Comment by ffilz** [comment]
Oh, good. Please close this when you are comfortable the issue has been resolved.

You may also want to watch for Ganesha V4.0 or the soon to be released Ganesha V4.1
