### ISSUE TITLE
Question about readdir.

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#836]
When I use NFSv3, and add option `nordirplus` in mount command. Then I execute command `ls` , I found after READDIR, there are a lot of LOOKUP. In our case, we only need filename, we do not need attribute, i.e. we only need READDIR, do not need LOOKUP. How can I improve this ? Is there any case which only need READDIR, not need LOOKUP ?
![image](https://user-images.githubusercontent.com/92144382/179388546-f04e28d2-dde1-44fd-a259-f05fe239c0c9.png)

**Comment by dang** [comment]
Linux needs information about an inode other than it's name in order to cache it.  I don't know of any way to turn this off; it's always been a feature of NFS clients that I've seen.  Maybe ask on the linux NFS mailing list?
