### ISSUE TITLE
Is There any bug in getfacl

### ISSUE THREAD

**Issue by Style980102** [nfs-ganesha/nfs-ganesha#837]
use nfsv3 to mount dir, mount -t nfs -o vers=3,mountproto=tcp ***:/ /dir0
mkdir /dir0/test1
setfacl -dm u::rx,u:65531:wx,u:0:x,g::wx,g:65532:x,g:0:rx,m::rwx,o::rx /dir0/test1
touch /dir0/test1/testfile
report error:[touch: cannot touch 'testfile': Remote I/O error]

I use tshark to capture the pcap file,
![image](https://user-images.githubusercontent.com/49463367/179912148-8a95ded7-eef7-4e40-a295-9c9cd3474cf6.png)

I found that when you create file, first to call getfacl to get /dir0 acl, and the mask is 0x0c, but the code in nfsacl_getacl

not to get the access acl ,should to get default access, but in get default access ,use acl == null to judge whether to succeed in get default access 

![image](https://user-images.githubusercontent.com/49463367/179912683-84430e43-3b3e-4c14-8e09-f9395dc2fc43.png)

**Comment by ffilz** [comment]
What version of Ganesha? Which FSAL? Is this still an issue?

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
