### ISSUE TITLE
Question: Can selinux be configured as enforcing？

### ISSUE THREAD

**Issue by Haroldll** [nfs-ganesha/nfs-ganesha#838]
My OS is centos 8.2, when I configure selinux to enforcing, ganesha doesn't start properly? Is there a workaround for this?

The description I see on the wiki is:
Here's how to collect the info necessary to resolve the AVC:
Set SELINUX to "permissive" in /etc/selinux/config and reboot.

So， must be set to permissive？

Another question, if I don't want to use root to run nfs-ganesha, can I run it with another non-root user?

Thanks.

**Comment by dang** [comment]
Ganesha has selinux policy included with it that *should* make it possible to run with enforcing.  It's in the nfs-ganesha-selinux package.  This has been tested in various environments with various FSALs, but we haven't been able to test everything, so we may have missed some condition.

**Comment by Haroldll** [comment]
@dang Thank you, it works fine now.
