### ISSUE TITLE
I want to let nfs-ganesha service listen on ipv4 address

### ISSUE THREAD

**Issue by MyqueWooMiddo** [nfs-ganesha/nfs-ganesha#840]
Hello ,  I install nfs-ganesha with v4.0.1 rpms on Centos7 , I try to set Bind_addr to 0.0.0.0/ipv4_addr/unSet in NFS_CORE_PARAM block , the service always listens on tcp6 protocol but the address is ipv4_addr.
If I set Bind_addr to :: , it will listen on :: . I just want to make it listen on ipv4 address with tcp rather than tcp6 .  I try to set net.ipv6.conf.eth.disable_ipv6 to 1 and restart the service , but it listen on :: .

I found the source code in nfs_rpc_dispatcher_thread.c  ,  with defining __FreeBSD__ it can set v6disabled  to true. But in my case , I can just install ganesha with rpms rather than compiling.
So, is there anybody facing the same issue with mine ?

**Comment by dang** [comment]
The only time Ganesha will not bind a v6 address is if the socket fails to open (if IPv6 is globally disabled on the entire system).  The only way I know to do this is to remove the ipv6 kernel module (or maybe not load it in the first place?)  The main question is: why do you want to disable IPv6 with Ganesha?

**Comment by MyqueWooMiddo** [comment]
> ain question is: why do you want to disable IPv6 with Ganesha?

It's my mistake . Though it listens on tcp6 & ipv4 address , but I can mount it from client with proto=tcp & ipv4 address. I'll close the issue
