### ISSUE TITLE
Duplicated seqid of different request which use the same slot and session.

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#841]
@ffilz Hi, in our production env, there is a very strange case: different request use the same seqid of the same slot and session, on the same client. 

No.44403 is a OPEN request, seqid: 0x9a6, slot id: 2. 
No.44417  is the OPEN reply for No.44403, seqid: 0x9a6, slot id: 2.
No.44430 is a CREATE request, seqid: 0x9a6, slot id: 2. 
No.44431 is the reply of No.44430 CREATE request, but No.44431 is a open reply, because ganesha think No.44430 CREATE request is a replay of No.44403 OPEN request. Then client report remote I/O error.

There is no other request use slot id:2 between No.44403 and No.44430. I open the client nfs log by `rpcdebug -m nfs -s all`, but did not find anything.

Do you have any suggestion for this ?

![image](https://user-images.githubusercontent.com/92144382/183857707-0c87fadd-74ed-4042-8975-71df334a61a0.png)
![image](https://user-images.githubusercontent.com/92144382/183857740-2fd9d51f-808c-4f9e-bc6d-ab21ae43cda6.png)

**Comment by liyinshubyte** [comment]
@ffilz I find it's kernel's bug. If I use a higher kernel version as client, it will not reproduce again. I think maybe we need to log some message for this case, for example, check the replay request is same to the origin request. It's hard to debug without this type message.

**Comment by ffilz** [comment]
If you want to submit a patch adding better logging for this situation that would be appreciated.

**Comment by liyinshubyte** [comment]
sure, will do it.

**Comment by liyinshubyte** [comment]
@ffilz Hi, it's the patch,  https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/542321. because this problem maybe cause client hangs forever, so I use fatal log.

**Comment by mattbenjamin** [comment]
No.

**Comment by liyinshubyte** [comment]
@mattbenjamin Thanks for review, I change to crit log.

**Comment by liyinshubyte** [comment]
This is a new case which cause client hangs forever,
No.33 is a GETATTR request, seqid 0x9b, slotid 4, xid 980110910 
No.44 is the reply of No.33, but it's the reply of SEQUENCE, mismatched with GETATTR, response is NFS4ERR_RETRY_UNCACHED_REP
No.57 is a retry GETATTR request, seqid 0x9b, slotid 4, xid 980110910 
No.67 is the reply of No.57, but it's the reply of SEQUENCE, mismatched with GETATTR, response is NFS4ERR_RETRY_UNCACHED_REP
....
client hangs forever, client always try GETATTR, ganesha always respond with NFS4ERR_RETRY_UNCACHED_REP.

![image](https://user-images.githubusercontent.com/92144382/184876530-f0924eed-6e55-4ed7-9898-64cf15b44997.png)
![image](https://user-images.githubusercontent.com/92144382/184876554-a959d3d3-f228-44db-85df-7dadae0b974d.png)

**Comment by ffilz** [comment]
Looks like we have a patch for logging here. Closing this as resolved.
