### ISSUE TITLE
Issue with ganesha 3.5 and RPC statd

### ISSUE THREAD

**Issue by dspisla** [nfs-ganesha/nfs-ganesha#844]
Hello together,

I need you help concerning this issue:

Customer gets the following error message on his client machine when accessing a NFS Share via ganesha:

> [Errno 37] No locks available

On the servers we are using:
SLES15-SP2
nfs-ganesha-3.5-11.1.x86_64
rpc-statd Version 2.1.1

The ganesha server shows the following errors:

> Aug 19 12:59:38 srvixxx ganesha.nfsd[27399]: [svc_12] rpc :TIRPC :EVENT :clnt_req_process_reply: 0x7fb3ac08deb0 fd 62 lookup failed xid 1
Aug 19 12:59:38 srvxxx ganesha.nfsd[27399]: [svc_14] rpc :TIRPC :EVENT :clnt_req_process_reply: 0x7fb3ac08deb0 fd 62 lookup failed xid 2
Aug 19 12:59:47 srvxxx ganesha.nfsd[27399]: [svc_15] rpc :TIRPC :EVENT :clnt_req_process_reply: 0x7fb3b01ce720 fd 62 lookup failed xid 1
Aug 19 12:59:55 srvxxx ganesha.nfsd[27399]: [svc_9] rpc :TIRPC :EVENT :clnt_req_process_reply: 0x7fb3cc258e50 fd 62 lookup failed xid 1
Aug 19 13:00:04 srvxxx ganesha.nfsd[27399]: [svc_12] nsm_monitor :NLM :EVENT :Monitor ::ffff:10.xxx.xx.xxx SM_MON failed: RPC: Timed out

In parallel rpc-statd shows:

> Aug 19 13:07:08 srvicas01 rpc.statd[17316]: Version 2.1.1 starting
Aug 19 13:07:08 srvicas01 rpc.statd[17316]: Flags: TI-RPC
Aug 19 13:07:08 srvicas01 rpc.statd[17316]: Running as root.  chown /var/lib/nfs/statd to choose different user
Aug 19 13:07:08 srvicas01 systemd[1]: Started NFS status monitor for NFSv2/3 locking..
Aug 19 13:13:08 srvicas01 rpc.statd[17316]: Received SM_UNMON request from srvicas01 for ::ffff:10.xxx.xx.xxx while not monitoring any hosts
Aug 19 13:13:19 srvicas01 rpc.statd[17316]: Received SM_UNMON request from srvicas01 for ::ffff:10.xxx.xx.xxx while not monitoring any hosts
Aug 19 13:13:19 srvicas01 rpc.statd[17316]: Received SM_UNMON request from srvicas01 for ::ffff:10.xxx.xx.xxx while not monitoring any hosts

Any idea about that?

**Comment by dspisla** [comment]
The last months it could be solved temporarily by restarting rpc-statd and nfs-ganesha. But now this doesn' t help anymore :-(

**Comment by ffilz** [comment]
Make sure rpc.statd IS running when Ganesha starts.

You can check with rpcinfo, first make sure it's registered:

rpcinfo -p

And then check if it's responding:

rpcinfo -t localhost status

**Comment by dspisla** [comment]
@ffilz Thank you!
I performed the command given in your comment and currently it seems to be fine. At the moment the customer doesn't complains about missing locks.

The issue arises since the customer uses the mount option "lock" which is not part of our default setup. I think for now we can close the issue.
