### ISSUE TITLE
Could not dlopen module: libfsalgluster.so for gluster 9.6.1

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#845]
` load_fsal :NFS STARTUP :FATAL :Could not dlopen module: /usr/lib64/ganesha/libfsalgluster.so Error: /usr/lib64/ganesha/libfsalgluster.so: undefined symbol: ace_count. You might want to install the nfs-ganesha-GLUSTER package`

I have already installed nfs-ganesha-gluster-2.7.6-2.el7.x86_64, Ganesha use source code of V2.7.6. Then I "ldd -r libfsalgluster.so", it reports a lot of "undefined symbol" as follows. So what I need to do to run ganesha on gluster ?
![image](https://user-images.githubusercontent.com/92144382/185922698-d4732f58-ee46-4dfc-a1be-f12640a44613.png)

**Comment by dang** [comment]
There's something wrong with the build.  libfsalgluster.so can't find symbols from ganesha itself.  I'd guess probably a version mismatch between libfsalgluster.so and the rest of Ganesha, but I can't be sure.

**Comment by liyinshubyte** [comment]
@dang Thanks the reply. Do you know which ganesha version I should use ?

**Comment by dang** [comment]
3.5 or 4.0

**Comment by liyinshubyte** [comment]
@dang I think it's caused by gluster version: 9.6.1, which does not need glusterfs-api, and is incompatible with ganesha. When I use gluster 7.7, everything is OK.

**Comment by dang** [comment]
Ah, thanks.  That makes sense.
