### ISSUE TITLE
question: is it possible to disable cache inode in nfs-ganesha?

### ISSUE THREAD

**Issue by akiradeveloper** [nfs-ganesha/nfs-ganesha#85]
Hi, all.

I am implementing FSAL for some distributed filesystem. The upcall is very difficult to implement so I am searching for a quicker way to realize multi-head.

I found a setting to disable delegation that also needs upcall impl to recall the delegation but I couldn't yet find a config to disable cache inode which also needs the impl to invalidate the stale data when some other node changed it.

Which leads to my question: is it possible to disable cache inode?

**Comment by soumyakoduri** [comment]
On 01/05/2016 07:21 AM, Akira Hayakawa wrote:
> Hi, all.
>
> I am implementing FSAL for some distributed filesystem. The upcall is
> very difficult to implement so I am searching for a quicker way to
> realize multi-head.
>
> I found a setting to disable delegation that also needs upcall impl to
> recall the delegation but I couldn't yet find a config to disable cache
> inode which also needs the impl to invalidate the stale data when some
> other node changed it.
>
> Which leads to my question: is it possible to disable cache inode?
>
One way which I know of is to set cache inode attribute expiration time 
to zero by adding the following block in your ganesha.conf file. This 
shall result in lookups/getattrs being sent to FSAL all the time instead 
of being read from the cache.

CACHEINODE {

	Attr_Expiration_Time = 0;
}

Thanks,
Soumya

**Comment by dang** [comment]
There is a major patch in the works to move cache_inode to be a stackable FSAL (called FSAL_MDCACHE) that will allow each FSAL to decide if it should be cached (and potentially on a per-export basis, although that is not tested).  This work needs to be rebased on top of Multi-FD (which should go in next week), so it's at least a couple of weeks out.  There's a branch up you can look at on my github at https://github.com/dang/nfs-ganesha/tree/napalm which passes pyNFS on FSAL_VFS.

**Comment by akiradeveloper** [comment]
Thanks guys,

So I should now go with `Attr_Expiration_Time = 0` and later after the patch included should setup mdcache stackable.

@dang I suspect the performance degradation. Did you measure the performance before and after and being sure that stackable approach makes sense?

**Comment by dang** [comment]
I haven't yet done extensive performance testing, but the performance should be largely unaffected. The code is largely the same, just re-organized (with simpler locking, to that could improve a bit), so there shouldn't be large performance hits.  The goal is for it to be faster.

If you disable caching, performance will change significantly for your FSAL, but how it changes depends on the circumstances. I've tested that with a prototype userspace FSAL and with VFS, and the userspace FSAL was faster, while VFS slowed down.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
