### ISSUE TITLE
Possible infinite loop in resolve_posix_filesystem()

### ISSUE THREAD

**Issue by skmprabhu1** [nfs-ganesha/nfs-ganesha#854]
nfs-ganesha/src/FSAL/localfs.c

int resolve_posix_filesystem(const char *path,
			     struct fsal_module *fsal,
			     struct fsal_export *exp,
			     claim_filesystem_cb claimfs,
			     unclaim_filesystem_cb unclaim,
			     struct fsal_filesystem **root_fs)
{
	int retval = EAGAIN;
	struct stat statbuf;

	while (retval == EAGAIN) {
		/* Need to retry stat on path until we don't get EAGAIN in case
		 * autofs needed to mount the file system.
		 */
		retval = stat(path, &statbuf);
		if (retval != 0) {
			retval = errno;
			LogDebug(COMPONENT_FSAL,
				 "stat returned %s (%d) while resolving export path %s %s",
				 strerror(retval), retval, path,
				 retval == EAGAIN ? "(may retry)" : "(failed)");
		}
	}

Suppose if stat() returns EAGAIN continuously due to some filesystem error, then we may go into infinite loop . I feel we should have retry count here and exit.

**Comment by ffilz** [comment]
Sure, we could implement a count. Would you like to submit a patch?

Maybe we should also implement a short delay so we don't need to retry so often?

**Comment by ffilz** [comment]
I thought about doing this, but I don't recall the parameters of why we did the retry. I'm not sure how long we have to retry.

**Comment by ffilz** [comment]
Bump - Prabhu, is this still your github ID?

**Comment by ffilz** [comment]
Here is a patch to manage this:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/552333

Please review for reasonableness of defaults and maximums.

**Comment by ffilz** [comment]
V5.0 has been released. Closing.
