### ISSUE TITLE
option to disable a unauthorized client from mounting root in NFSv4

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#855]
This issue is to know whether any option to disable a unauthorized client from mounting "/" in NFSv4.

for ex in the below scenario, an unauthorized client can mount "/" and traverse the export directroy structure till /ibm/fs1/fset2/fset21 in case of second export. 
[root@rhel79y1 ~]# mmnfs export list

Path                          Delegations  Clients    
----------------------------  -----------  ---------- 
/ibm/fs1/fset1                NONE         10.28.0.38 
/ibm/fs1/fset2/fset21/fset22  NONE         10.28.0.38 

I tried adding export entry "/" with export id 0, and added few client ips who can mount this "/", but still other unlisted clients able to mount "/" and traverse directory structure of exports which they dont have access.

**Comment by yogendra-t** [comment]
Hi Frank,

As discussed I tried with below conf changes but it seems traversal of the psed0 fs is not disabled.

I have removed access_type=none from exports_defaults.
Export_Defaults
{
        anonymous_gid=-2;
        anonymous_uid=-2;
        manage_gids=FALSE;
        nfs_commit=FALSE;
        privilegedport=FALSE;
        protocols=3,4;
        sectype=sys;
        squash=root_squash;
        transports=TCP;
}

and added below entry for "/" in gpfs.ganesha.exports.conf

EXPORT
{
        Attr_Expiration_Time=60;
        Delegations=none;
        Export_id=24;
        Filesystem_id=666.666;
        MaxOffsetRead=18446744073709551615;
        MaxOffsetWrite=18446744073709551615;
        MaxRead=1048576;
        MaxWrite=1048576;
        Path="/";
        PrefRead=1048576;
        PrefReaddir=1048576;
        PrefWrite=1048576;
        Pseudo="/";
        Tag="/";
        UseCookieVerifier=false;
        FSAL
        {
                Name=gpfs;
        }
        CLIENT
        {
                Access_Type=rw;
                Clients=10.28.0.38;
        }
}

**Comment by ffilz** [comment]
You need to add Access_Type = none; to the EXPORT.

Optionally, and a bit more clear is to add:

```
CLIENT {
    Access_Type = none;
    Clients="*";
}
```
after any other CLIENT blocks, that makes it a bit more specific that any other client that isn't specified by a previous CLIENT block has no access.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.

**Comment by ffilz** [comment]
I just realized, there might be a way to do this.

With the addition of host validation for use of the HA Proxy V2 protocol, I realized that it would be very easy to add a list of hosts that are allowed to use NFS at all. This would block any unauthorized client before it can even try and access an export, including PUTROOTFH.

Look at this patch to see how this might work:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/548334/1

**Comment by ffilz** [comment]
Is this something that would still be desired?

**Comment by ffilz** [comment]
There is another thing that may work for this. Now that EXPORT_DEFAULTS can have CLIENT blocks, those will apply to the default PseudoFS and may resolve this.

**Comment by ffilz** [comment]
On the other hand, the CLIENT blocks in EXPORT_DEFAULTS may cause problems with the default pseudo root.

We may want a way to simplify configuration of the pseudo root and add a PSEUDO_ROOT block which is like an EXPORT block but assumes the defaults of the default pseudo root (and does not allow specification of Path or Pseudo with Export_ID defaulting to 0). Thus a simple block like:

```
PSEUDO_ROOT
{
    CLIENT
    {
        Clients = 129.168.0.0/16;
        Access_Type = RW;
    }
    CLIENT
    {
        Clients = "*";
        Access_Type = NONE;
    }
```

Would restrict the clients allowed to access Pseudo Root without having to specify Export_Id, Path, Pseudo, and other options.

**Comment by ffilz** [comment]
Marking PRIORITY because the new CLIENT list in EXPORT_DEFAULTS may cause problems with Pseudo Root access. We need an easy way to specify the client access list for Pseudo Root.

**Comment by ffilz** [comment]
This patch should help this situation. https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/555099?usp=search

**Comment by ffilz** [comment]
Closing as done with 6.0 release.

If this does not resolve the issue, please open a new issue.
