### ISSUE TITLE
Unchecked return value

### ISSUE THREAD

**Issue by FloridSleeves** [nfs-ganesha/nfs-ganesha#856]
Hi, I'm a researcher using static analysis to check bugs in NFS-ganesha.  We find following return values are not checked but the function call could potentially return error code. If the error is ignored, the execution may fail silently:

|File|  Line | Column| Function|Link|
|----|------|----------|----------|---|
|FSAL/posix_acls.c|	176|	9|	acl_set_qualifier|https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/MainNFSD/nfs_rpc_callback.c#L1148|
|idmapper/idmapper_cache.c|	745	|19	|malloc |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/idmapper/idmapper_cache.c#L746|
|idmapper/idmapper_cache.c|	426	|11	|gsh_malloc| https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/idmapper/idmapper_cache.c#L427|
|idmapper/idmapper_cache.c|	320	|11	|gsh_malloc| https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/idmapper/idmapper_cache.c#L321|
|log/log_functions.c	|647	|13	|display_printf    |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/log/log_functions.c#L592|
|support/exports.c	|381	|2	|display_cat    |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/support/exports.c#L382|
|support/exports.c	|381	|2	|display_cat    |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/support/exports.c#L335|
|support/fridgethr.c	|776	|4	|clock_gettime   |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/support/fridgethr.c#L776|
|support/fridgethr.c	|420	|4	|clock_gettime   |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/support/fridgethr.c#L420|
|support/fridgethr.c	|1313	|4	|clock_gettime   |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/support/fridgethr.c#L1313|
|FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c	|3497	|4	|nfs4_acl_release_entry|https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c#L3509|
|FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_up.c	|289	|3	|nfs4_acl_release_entry  |https://github.com/nfs-ganesha/nfs-ganesha/blob/f59e00f470caa62efd42478bbc4dbc5447940d11/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_up.c#L290|

Maybe we should patch them with the return value check? Let me know if I can help with patching them. 

Thanks!

**Comment by dang** [comment]
You can ignore all the allocation calls.  As a policy, we don't check return values for allocation failure, since we cannot recover, and therefore would crash anyway.  Some of the others are probably worth investigating.

**Comment by ffilz** [comment]
Hmm, seems like some direct malloc calls have sneaked in, they probably should be calls to gsh_malloc (which can not return NULL, it aborts if we are out of memory). Resolved with: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/543749

I'm not sure why calls to gsh_malloc are being flagged. Is there someplace checking for NULL return?

clock_gettime should only fail if something is really broken. If we really wanted that to pass static analysis, then we could have a void inline function that would LogFatal if clock_gettime failed. Hmm, most of the calls do check the return value. Personally I think maybe we should have a macro that checks the return and does a LogFatal is it's non-zero. Then all the callers don't need code to handle an error that should never happen and if it does, we really can't run successfully.

Ignoring the return from a display.h function is OK, the return (and use of b_left) is only to allow bailing out of constructing a string if the string will be truncated. These are only used for logging where truncation is of little consequence. Perhaps set_const_log_str should log a message if the format string is truncated. I would be OK with a patch to resolve these if they are of great concern or annoyance with static code analysis.

nfs4_acl_release_entry should be made a void function. No caller does anything other than log an error if it returns an error. nfs4_acl_release_entry has already logged an error. Resolved with: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/543748

**Comment by FloridSleeves** [comment]
Thanks for your reply! gsh_malloc is due to our misprocessing in tools. Sorry for reporting that.
For the rest, thanks for you confirmation.

**Comment by ffilz** [comment]
Closing as resolved.
