### ISSUE TITLE
export fails due to stale dev id entry in avl tree (issue with resolve_posix_filesystem())

### ISSUE THREAD

**Issue by manishladdha** [nfs-ganesha/nfs-ganesha#857]
This is in continuation to the issue raised by Prabhu earlier: https://github.com/nfs-ganesha/nfs-ganesha/issues/847.
Please refer the above link.

We had checked the upstream code but could not find the code that can fix this issue.
Can we add 'tmpfs' to the ignore list of filessystems that will never be exported ? I was curious to know why this was not excluded before ?
if ....(strcasecmp(mnt->mnt_type, "tmpfs") == 0)

steps to recreate:
mount gpfs2
mount -t tmpfs tmpfs3 /mnt/tmpfs3
ps -eaf | grep ganesha
cat /proc/236099/mountinfo | tail -n 5
mmnfs export add  /gpfs2 --client  "*(Access_Type=RW,Squash=no_root_squash)"
umount tmpfs3
after unmounting tmpfs3, the id is not removed from the dev avl_dev.
mount gpfs3
mount -t tmpfs tmpfs3 /mnt/tmpfs3
mmnfs export add  /gpfs3 --client  "*(Access_Type=RW,Squash=no_root_squash)"

Please let me know if you need any extra information

**Comment by dang** [comment]
I would expect that we can export tmpfs.  It's just a memory-based filesystem.

**Comment by manishladdha** [comment]
Hi Daniel,
Thank you for the response. 
In such cases, how would you suggest Ganesha to re-populate the 'avl_dev' by removing the stale old entries.

**Comment by skmprabhu1** [comment]
Hi Daniel, 

I would like know what is the use case for exporting tmpfs filesystem? why nfs client would require access to tmpfs? 
  
Suppose If we allow Ganesha to export tmpfs, then which FSAL would process the client request?

In populate_posix_file_systems(), I feel we should change below if condition to keep supported FS(based on supported FSAL) rather than ignoring unsupported FS.

        while ((mnt = getmntent(fp)) != NULL) {
                if (mnt->mnt_dir == NULL)
                        continue;

                /* stat() on NFS mount points is prone to get stuck in
                 * kernel due to unavailable NFS servers. Since we don't
                 * support them anyway, check this early and avoid
                 * hangs!
                 *
                 * Also skip some other filesystem types that we would never
                 * export.
                 */
                if (strncasecmp(mnt->mnt_type, "nfs", 3) == 0 ||
                    strcasecmp(mnt->mnt_type, "autofs") == 0 ||
                    strcasecmp(mnt->mnt_type, "sysfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "proc") == 0 ||
                    strcasecmp(mnt->mnt_type, "devtmpfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "securityfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "cgroup") == 0 ||
                    strcasecmp(mnt->mnt_type, "selinuxfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "debugfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "hugetlbfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "mqueue") == 0 ||
                    strcasecmp(mnt->mnt_type, "pstore") == 0 ||
                    strcasecmp(mnt->mnt_type, "devpts") == 0 ||
                    strcasecmp(mnt->mnt_type, "configfs") == 0 ||
                    strcasecmp(mnt->mnt_type, "binfmt_misc") == 0 ||
                    strcasecmp(mnt->mnt_type, "rpc_pipefs") == 0 ||
                    strcasecmp(mnt->mnt_type, "vboxsf") == 0) {
                        LogDebug(COMPONENT_FSAL,
                                 "Ignoring %s because type %s",
                                 mnt->mnt_dir,
                                 mnt->mnt_type);
                        continue;
                }

                if (stat(mnt->mnt_dir, &st) < 0 || !S_ISDIR(st.st_mode)) {
                        continue;
                }

                posix_create_file_system(mnt);
        }


Kindly let us know your input.

Thanks,
Prabhu

**Comment by dang** [comment]
I've exported tmpfs for performance testing, to take disks out of the equation, and to get more consistent results.  I've used FSAL_VFS for this purpose.

I'm not sure how to clean up the tree, yet, but I doubt this is just a problem with tmpfs.  I'd expect btrfs to potentially have this issue as well, so we should probably have a clean fix.  @ffilz, any ideas?

**Comment by ffilz** [comment]
7541e15805ff9259f5c4d6c6fdca5c866f1cd959 in V4-dev.23 has us remove unclaimed filesystems when doing populate_posix_file_systems. That should take care of the issue., I think that patch could be back ported. It might require a few other back ports also. Or you will pick it up in V4.1.

**Comment by ffilz** [comment]
V4.3 has been tagged with a fix for this issue. Closing.
