### ISSUE TITLE
Protocols in EXPORT_DEFAULTS doesn't work as expected

### ISSUE THREAD

**Issue by ffilz** [nfs-ganesha/nfs-ganesha#858]
One would expect to be able to specify Protocols in EXPORT_DEFAULTS and have it apply to all exports. And it does for export permission checking, but not for building the pseudofs. We should look to the EXPORT_DEFAULTS to see if v4 is enabled (and that could and should go back to the code defaults and what's prescribed by NFS_CORE_PARAM if appropriate.

**Comment by sleep-walker** [comment]
Thanks for opening it.

**Comment by ffilz** [comment]
This has been fixed in V4.3. Closing as resolved.
