### ISSUE TITLE
ganesha.nfsd-1285[svc_16] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT

### ISSUE THREAD

**Issue by tomkcpr** [nfs-ganesha/nfs-ganesha#859]
Hey Folks,  

Getting the following from NFS Ganesha, updated to the latest 3.X version on CentOS 7:

30/09/2022 21:12:09 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_16] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT

Wondering if there is solution to the above?

Cheers,
Tom

[root@nfs01 ~]# tail -f /var/log/messages /var/log/ganesha/*.log
==> /var/log/messages <==
Sep 30 22:05:01 nfs01 systemd: Removed slice User Slice of root.
Sep 30 22:10:01 nfs01 systemd: Created slice User Slice of root.
Sep 30 22:10:01 nfs01 systemd: Started Session 14 of user root.
Sep 30 22:10:01 nfs01 systemd: Removed slice User Slice of root.
Sep 30 22:15:01 nfs01 systemd: Created slice User Slice of root.
Sep 30 22:15:01 nfs01 systemd: Started Session 15 of user root.
Sep 30 22:15:01 nfs01 systemd: Removed slice User Slice of root.
Sep 30 22:16:55 nfs01 systemd-logind: New session 16 of user tom@mds.xyz.
Sep 30 22:16:55 nfs01 systemd: Started Session 16 of user tom@mds.xyz.
Sep 30 22:16:58 nfs01 systemd-logind: Removed session 16.

==> /var/log/ganesha/ganesha-gfapi.log <==
[2022-10-01 01:12:16.644366] I [MSGID: 114046] [client-handshake.c:1105:client_setvolume_cbk] 0-gv01-client-3: Connected to gv01-client-3, attached to remote volume '/bricks/0/gv01'.
[2022-10-01 01:12:16.644408] I [MSGID: 108005] [afr-common.c:5195:__afr_handle_child_up_event] 0-gv01-replicate-0: Subvolume 'gv01-client-3' came back up; going online.
[2022-10-01 01:12:17.647062] I [rpc-clnt.c:2028:rpc_clnt_reconfig] 0-gv01-client-1: changing port to 49152 (from 0)
[2022-10-01 01:12:17.658854] I [MSGID: 114046] [client-handshake.c:1105:client_setvolume_cbk] 0-gv01-client-1: Connected to gv01-client-1, attached to remote volume '/bricks/0/gv01'.
[2022-10-01 01:12:17.658899] I [MSGID: 108002] [afr-common.c:5557:afr_notify] 0-gv01-replicate-0: Client-quorum is met
[2022-10-01 01:12:39.726344] I [rpc-clnt.c:2028:rpc_clnt_reconfig] 0-gv01-client-2: changing port to 49152 (from 0)
[2022-10-01 01:12:43.656942] I [rpc-clnt.c:2028:rpc_clnt_reconfig] 0-gv01-client-2: changing port to 49152 (from 0)
[2022-10-01 01:12:43.667392] I [MSGID: 114046] [client-handshake.c:1105:client_setvolume_cbk] 0-gv01-client-2: Connected to gv01-client-2, attached to remote volume '/bricks/0/gv01'.
The message "I [MSGID: 108006] [afr-common.c:5619:afr_local_init] 0-gv01-replicate-0: no subvolumes up" repeated 17 times between [2022-10-01 01:12:09.208932] and [2022-10-01 01:12:16.305884]
The message "W [MSGID: 104011] [glfs-handleops.c:1500:pub_glfs_h_create_from_handle] 0-meta-autoload: inode refresh of 3db75dc1-f095-46c1-94c0-8c9150fef106 failed: Transport endpoint is not connected [Transport endpoint is not connected]" repeated 17 times between [2022-10-01 01:12:09.209034] and [2022-10-01 01:12:16.305913]

==> /var/log/ganesha/ganesha.log <==
30/09/2022 17:46:36 : epoch 633763bc : nfs01.nix.mds.xyz : ganesha.nfsd-13583[main] SetComponentLogLevel :LOG :NULL :LOG: Changing log level of COMPONENT_FSAL_UP from NIV_EVENT to NIV_FULL_DEBUG
30/09/2022 17:46:36 : epoch 633763bc : nfs01.nix.mds.xyz : ganesha.nfsd-13583[main] SetComponentLogLevel :LOG :NULL :LOG: Changing log level of COMPONENT_DBUS from NIV_EVENT to NIV_FULL_DEBUG
30/09/2022 17:46:36 : epoch 633763bc : nfs01.nix.mds.xyz : ganesha.nfsd-13583[main] SetComponentLogLevel :LOG :NULL :LOG: Changing log level of COMPONENT_NFS_MSK from NIV_EVENT to NIV_FULL_DEBUG
30/09/2022 17:46:36 : epoch 633763bc : nfs01.nix.mds.xyz : ganesha.nfsd-13583[main] SetLevelDebug :LOG :NULL :LOG: Setting log level for all components to NIV_FULL_DEBUG
30/09/2022 17:46:36 : epoch 633763bc : nfs01.nix.mds.xyz : ganesha.nfsd-13583[main] proc_block :CONFIG :F_DBG :------ At (/etc/ganesha/ganesha.conf:13): commit LOG
30/09/2022 17:46:36 : epoch 633763bc : nfs01.nix.mds.xyz : ganesha.nfsd-13583[main] create_log_facility :LOG :INFO :Facility FILE already exists
30/09/2022 17:52:04 : epoch 63376504 : nfs01.nix.mds.xyz : ganesha.nfsd-13856[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 3.4
30/09/2022 17:52:04 : epoch 63376504 : nfs01.nix.mds.xyz : ganesha.nfsd-13857[main] load_rados_config :CONFIG :WARN :Missing RADOS URLs backend library
30/09/2022 21:10:08 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1245[main] main :MAIN :EVENT :ganesha.nfsd Starting: Ganesha Version 3.5
30/09/2022 21:10:08 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[main] load_rados_config :CONFIG :WARN :Missing RADOS URLs backend library

==> /var/log/ganesha/ganesha-rgw.log <==
30/09/2022 21:12:09 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_16] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:09 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_5] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:12 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_17] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:12 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_8] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:12 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_18] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:12 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_6] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:16 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_19] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:16 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_11] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:16 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_20] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
30/09/2022 21:12:16 : epoch 63379370 : nfs01.nix.mds.xyz : ganesha.nfsd-1285[svc_16] posix2fsal_error :FSAL :CRIT :Default case mapping Transport endpoint is not connected (107) to ERR_FSAL_SERVERFAULT
^C
[root@nfs01 ~]#
[root@nfs01 ~]#
[root@nfs01 ~]# vi /etc/ganesha/ganesha.conf
[root@nfs01 ~]# rpm -aq|grep -Ei ganesha
nfs-ganesha-gluster-3.5-2.el7.x86_64
nfs-ganesha-3.5-2.el7.x86_64
nfs-ganesha-proxy-3.5-2.el7.x86_64
nfs-ganesha-utils-3.5-2.el7.x86_64
nfs-ganesha-mount-9P-2.7.6-2.el7.x86_64
centos-release-nfs-ganesha28-1.0-3.el7.centos.noarch
centos-release-nfs-ganesha30-1.0-2.el7.centos.noarch
nfs-ganesha-vfs-3.5-2.el7.x86_64
[root@nfs01 ~]#

**Comment by dang** [comment]
Something got ENOTCONN.  What is your config?

**Comment by tomkcpr** [comment]
It's repeatable often enough so thinking I could capture a more detailed debug log between now and next Sunday.  This is a 3 node setup.  NFS Ganesha is sharing a GlusterFS volume. 

```
[root@nfs01 ganesha]# cat /etc/ganesha/ganesha.conf
###################################################

#
# EXPORT
#
# To function, all that is required is an EXPORT
#
# Define the absolute minimal export
#
###################################################

# logging directives--be careful
LOG {
        # Default_Log_Level is unknown token??
        # Default_Log_Level = NIV_FULL_DEBUG;
        Components {
##                 ALL = FULL_DEBUG;
#                MEMLEAKS = FATAL;
#                FSAL = DEBUG;
#                NFSPROTO = FATAL;
#                NFS_V4 = FULL_DEBUG;
#                EXPORT = DEBUG;
#                FILEHANDLE = FATAL;
#                DISPATCH = DEBUG;
#                CACHE_INODE = FULL_DEBUG;
#                CACHE_INODE_LRU = FATAL;
#                HASHTABLE = FATAL;
#                HASHTABLE_CACHE = FATAL;
#                DUPREQ = FATAL;
#                INIT = DEBUG;
#                MAIN = FATAL;
#                IDMAPPER = FULL_DEBUG;
#                NFS_READDIR = FULL_DEBUG;
#                NFS_V4_LOCK = FULL_DEBUG;
#                CONFIG = FULL_DEBUG;
#                CLIENTID = FULL_DEBUG;
#                SESSIONS = FATAL;
#                PNFS = FATAL;
#                RW_LOCK = FATAL;
#                NLM = FATAL;
#                RPC = FULL_DEBUG;
#                NFS_CB = FATAL;
#                THREAD = FATAL;
#                NFS_V4_ACL = FULL_DEBUG;
#                STATE = FULL_DEBUG;
##                9P = FATAL;
##                9P_DISPATCH = FATAL;
#                FSAL_UP = FATAL;
#                DBUS = FATAL;
        }

        Facility {
                name = FILE;
                destination = "/var/log/ganesha/ganesha-rgw.log";
                enable = active;
        }
}

NFSv4 {
    Lease_Lifetime = 20 ;
    IdmapConf = "/etc/idmapd.conf" ;
    DomainName = "nix.mds.xyz" ;
}

NFS_KRB5 {
        PrincipalName = "nfs/nfs01.nix.mds.xyz@NIX.MDS.XYZ" ;
        KeytabPath = /etc/krb5.keytab ;
        Active_krb5 = YES ;
}


NFS_Core_Param {
        Bind_addr=192.168.0.149;
        NFS_Port=2049;
        MNT_Port=20048;
        NLM_Port=38468;
        Rquota_Port=4501;
}

%include "/etc/ganesha/export.conf"
# %include "/etc/ganesha/export-home.conf"


[root@nfs01 ganesha]# cat "/etc/ganesha/export.conf"
EXPORT {
    Export_Id = 1 ;                             # Export ID unique to each export
    Path = "/n";                                # Path of the volume to be exported. Eg: "/test_volume"

    FSAL {
        name = GLUSTER;
        hostname = "nfs01.nix.mds.xyz";         # IP of one of the nodes in the trusted pool
        volume = "gv01";                        # Volume name. Eg: "test_volume"
    }

    Access_type = RW;                           # Access permissions
    Squash = No_root_squash;                    # To enable/disable root squashing
    Disable_ACL = FALSE;                        # To enable/disable ACL
    Pseudo = "/n";                              # NFSv4 pseudo path for this export. Eg: "/test_volume_pseudo"
    Protocols = "3", "4";                       # NFS protocols supported
    Transports = "UDP", "TCP" ;                 # Transport protocols supported
    SecType = "sys", "krb5","krb5i","krb5p";    # "sys", "krb5","krb5i","krb5p";        # Security flavors supported
}
[root@nfs01 ganesha]#
```

This page is slightly dated with many of the versions now more recent, including GlsuterFS 6.  However, the page does reflect the 3 node setup relatively well and what's there ( No longer have to compile NFS Ganesha from source either, though I did have some HAproxy issues conflicting with port setup so I disabled HAproxy.).   

https://microdevsys.com/wp/glusterfs-configuration-and-setup-w-nfs-ganesha-for-an-ha-nfs-cluster-quick-start-guide/

The setup, now that I had a few years to test drive it, is fairly good however when nodes do come up after a reboot, it's not uncommon to see autofs fail to mount NFS Ganesha quite often, mostly in the recent past.  Restarting autofs on the clients worked.  Strangely, it seems everytime I enable logging, it starts to work.  Repeated restart of autofs without logging enabled doesn't appear to work as predictably.

This is CentOS 7.

Just some general info.  Hope it helps and gives context. 

Cheers,
Tom

**Comment by tomkcpr** [comment]
Enabled full debug logging now.  I'll give it some time to hopefully, capture more.  Still have the older log files.

**Comment by ffilz** [comment]
Is this still an issue? Also, please retry on Ganesha V4.3 which was just released.

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
