### ISSUE TITLE
FSAL PROXY: Data caching 

### ISSUE THREAD

**Issue by boskuv** [nfs-ganesha/nfs-ganesha#863]
Hi everyone!
I've read here: https://github.com/nfs-ganesha/nfs-ganesha/issues/310 , that there is no data caching for proxy server - is it true for now?
If it's possible how to check data caching on proxy server?
If i try to get the same data 2 times from server to client via proxy, there won't release any traffic on server (cause it stores in cache on proxy) - am I right?

**Comment by ffilz** [comment]
We have meta-data caching in MDCACHE that should work in front of PROXY. We don't have data caching though a stackable FSAL to implement a data cache has been suggested but no one has stepped up with the resources to do such development.

**Comment by boskuv** [comment]
> We have meta-data caching in MDCACHE that should work in front of PROXY. We don't have data caching though a stackable FSAL to implement a data cache has been suggested but no one has stepped up with the resources to do such development.

thank you a lot for the answer !
