### ISSUE TITLE
FSAL_RGW xattrs code is broken

### ISSUE THREAD

**Issue by ffilz** [nfs-ganesha/nfs-ganesha#866]
This code has been disabled, it needs some work to be made functional.

**Comment by mattbenjamin** [comment]
who approved and merged, @ffilz ?

**Comment by ffilz** [comment]
This is the original patch to include:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/506239

Looking at the comment history, it looks like we wanted to get it into Ganesha V4.0 despite knowing it didn't pass pynfs testing.

I will be submitting a patch to disable it pending repair and testing of the code:

https://github.com/nfs-ganesha/nfs-ganesha/commit/f038786c508734ce464386df1a0e19a9a7308896

Hopefully it's not a lot of work to fix...

**Comment by mattbenjamin** [comment]
Thanks, @ffilz

**Comment by ffilz** [comment]
Oops, looks like maybe the code still needs to be disabled...

Really not sure how to proceed with this.

**Comment by ffilz** [comment]
Bump to keep on page 1

**Comment by ffilz** [comment]
Patch submitted: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/553107

**Comment by ffilz** [comment]
Merged, closing.
