### ISSUE TITLE
nfs-ganesha will randomly hang (gluster)

### ISSUE THREAD

**Issue by RustyBower** [nfs-ganesha/nfs-ganesha#870]
hey friends. i am running into such a strange issue and i'm not even sure where to start debugging. i have a multi node gluster setup, which is exporting nfs via nfs-ganesha. these exports are mounted by a number of different k8s pods, but randomly nfs-ganesha will go out to lunch (nothing obvious in the error logs, even with verbosity turned up), and the only fix is a restart of nfs-ganesha. i do have some logs with "nfs_health 3:49:01 PM :DBUS :WARN :Health status is unhealthy. enq new: 3017221, old: 3017206; deq new: 3017206, old: 3017206", but looking at https://github.com/nfs-ganesha/nfs-ganesha/issues/463, it looks like these are just warnings?

per a convo in irc, i've increased the logging and I have the following logs when this has hung
```
28/10/2022 11:09:39 : epoch 635b5b24 : datanode01.internal.rustybower.com : ganesha.nfsd-3129[svc_3437] rpc :TIRPC :EVENT :svc_rqst_hook_events: 0x7f57a00389e0 fd 1024 xp_refcnt 1 sr_rec 0x55be28538b98 evchan 1 ev_refcnt 201 epoll_fd 33 control fd pair (31:32) direction in hook failed (9)
28/10/2022 11:09:39 : epoch 635b5b24 : datanode01.internal.rustybower.com : ganesha.nfsd-3129[svc_3437] nsm_connect :NLM :EVENT :connect to statd failed: RPC: Unknown protocol
28/10/2022 11:09:39 : epoch 635b5b24 : datanode01.internal.rustybower.com : ganesha.nfsd-3129[svc_3437] nsm_monitor :NLM :EVENT :Monitor ::ffff:10.0.0.50 nsm_connect failed
28/10/2022 11:09:57 : epoch 635b5b24 : datanode01.internal.rustybower.com : ganesha.nfsd-3129[svc_3437] nsm_connect :NLM :EVENT :connect to statd failed: RPC: Unknown protocol
28/10/2022 11:09:57 : epoch 635b5b24 : datanode01.internal.rustybower.com : ganesha.nfsd-3129[svc_3437] nsm_monitor :NLM :EVENT :Monitor ::ffff:10.0.0.50 nsm_connect failed
```

any suggestions on what configurations settings to tinker with to try to sort this?

**Comment by RustyBower** [comment]
per the convo in IRC, it seems the rpc.statd might have crashed, although a restart of the service fixes it.

i've increased logging to debug to see if I can get a solid log before a crash (or my disk fills up)

**Comment by RustyBower** [comment]
I finally was able to capture some debug during a crash...

It looks like we're getting a CRIT error
```
02/11/2022 13:00:05 : epoch 63 [ganesha.log-2022110213.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/9923090/ganesha.log-2022110213.gz) 62b022 : datanode01.internal.rustybower.com : ganesha.nfsd-21159[svc_29] nfs_dupreq_rele :RW LOCK :CRIT :Error 22, acquiring mutex 0x7f1f28502080 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:1434
```

**Comment by RustyBower** [comment]
I've upgraded to 4.0.1 with MID_DEBUG on, so we can see if it crashes soon

**Comment by RustyBower** [comment]
Looks like we're just hanging now randomly

```
02/11/2022 14:21:30 : epoch 6362bb90 : datanode01.internal.rustybower.com : ganesha.nfsd-3863[svc_236] nfs_dupreq_rele :RW LOCK :CRIT :Error 22, acquiring mutex 0x7f3320102930 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:1434
```

**Comment by RustyBower** [comment]
And following a comment in https://lists.nfs-ganesha.org/archives/list/devel@lists.nfs-ganesha.org/thread/WXLGUMBMO7NIRNQLJK47AD43TOOYIZSP/, following the address, we get the following

```
[root@datanode01 ganesha]# grep "0x7fb724201840" ganesha.log
02/11/2022 14:38:40 : epoch 6362c73e : datanode01.internal.rustybower.com : ganesha.nfsd-16964[svc_45] nfs_dupreq_finish :RW LOCK :F_DBG :Acquired mutex 0x7fb724201840 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:1211
02/11/2022 14:38:40 : epoch 6362c73e : datanode01.internal.rustybower.com : ganesha.nfsd-16964[svc_45] nfs_dupreq_finish :RW LOCK :F_DBG :Released mutex 0x7fb724201840 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:1231
02/11/2022 14:38:40 : epoch 6362c73e : datanode01.internal.rustybower.com : ganesha.nfsd-16964[svc_45] nfs_dupreq_free_dupreq :RW LOCK :F_DBG :Destroy mutex 0x7fb724201840 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:896
02/11/2022 14:38:40 : epoch 6362c73e : datanode01.internal.rustybower.com : ganesha.nfsd-16964[svc_45] nfs_dupreq_rele :RW LOCK :CRIT :Error 22, acquiring mutex 0x7fb724201840 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:1434
```

**Comment by mhahl** [comment]
I have a pretty similar infrastructure setup, gluster + nfs-ganesha + keepalived being consumed by OpenShift using NFS4.
It seems I am also running into this exact same issue. Let me know if you require assistance troubleshooting / logs.

**Comment by ffilz** [comment]
Hmm, if rpc.statd may be an issue, a patch went into V4.1 to restart connection to rpc.statd.

Please try V4.3 which was just released.

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
