### ISSUE TITLE
Migration from Sourceforge is not complete

### ISSUE THREAD

**Issue by Neustradamus** [nfs-ganesha/nfs-ganesha#873]
Dear @nfs-ganesha team, @phdeniel, @tl-cea, 

It will be nice to remove old parts like:
- https://sourceforge.net/p/nfs-ganesha/patches/
- https://sourceforge.net/p/nfs-ganesha/news/
- https://sourceforge.net/p/nfs-ganesha/discussion/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/projects/nfs-ganesha/

To disable/delete tabs, go here: https://sourceforge.net/projects/nfs-ganesha/
To add a new tab, go here: https://sourceforge.net/projects/nfs-ganesha/
To change informations, go here: https://sourceforge.net/p/nfs-ganesha/admin/overview
To export, go here: https://sourceforge.net/p/nfs-ganesha/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/nfs-ganesha/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/nfs-ganesha/admin/overview
- A new tab, go here: https://sourceforge.net/projects/nfs-ganesha/

The description must be changed too.

The website link is not good in Sourceforge options (better to change with github.com too):
- https://github.com/nfs-ganesha

PS: The current team has management of the SF project, if not, it is the moment to add it.

Thanks in advance.

**Comment by ffilz** [comment]
I don't have the admin privileges on sourceforge to make the changes. Deniel Philippe mostly doesn't work on Ganesha. I'm really not sure what to do other than what is always possible with open source - pick up and move on with new maintainers and create a new project site.

**Comment by Neustradamus** [comment]
@ffilz: I think that @phdeniel can add you on Sourceforge, he has all rights on it.

**Comment by Neustradamus** [comment]
Attention: I do not request to create a new project site, current team must have access to SF and the project page must be up-to-date and inform that it is now here, like I have specified in my main ticket.

**Comment by ffilz** [comment]
Philippe reached out to me so maybe we can get something fixed up on sourceforge, but this kind of thing is going to start happening more and more in the open source community. Maintainers will stop being active in their project and someone else will take the project over and put up their own repo which may or may not be linked with the original project. The nature of open source licensing allows anyone to declare themselves maintainer of the project and develop their own following. They may or may not become the dominant source for that project.

**Comment by Neustradamus** [comment]
@ffilz: It is better to have a continuity.

Thanks to @phdeniel.

**Comment by ffilz** [comment]
I wish I could wave a magic wand and make the Sourceforge Ganesha project go away or just be a shell link to github with clarity that anything lingering on Sourceforge is way out of date.

I can't seem to get anything done about that. I guess I will reach out to Sourceforge support and see if anything can be done.

**Comment by ffilz** [comment]
Bump

**Comment by ffilz** [comment]
OK, I got a "project moved" notice put up. Unfortunately I have zero access to the project any more and Deniel Phillippe has not been responsive to years of attempts to change the content there, so it will live on with stale information.

Closing this now.

**Comment by Neustradamus** [comment]
@ffilz: How have you added the "project moved" box?

**Comment by ffilz** [comment]
I reached out to Sourceforge support and they added it. I was hoping they could do more, but they just said "get Deniel Philippe to do it, or make you an admin"... I've not had a lot of luck getting Philippe to do much, so here we are...
