### ISSUE TITLE
/usr/lib64/ganesha/libfsalceph.so: undefined symbol: ceph_get_fs_cid. You might want to install the nfs-ganesha-CEPH package

### ISSUE THREAD

**Issue by liangxunchang** [nfs-ganesha/nfs-ganesha#875]
os:CentOS Linux release 7.5.1804 (Core) 
ceph version:ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
nfs-nanesha version:NFS-Ganesha Release = V2.8.3
i have install  nfs-ganesha
rpm -qa|grep nfs-ganesha
nfs-ganesha-ceph-2.8.3-4.el7.x86_64
nfs-ganesha-2.8.3-4.el7.x86_64
this is my nfs-ganesha.conf

NFS_CORE_PARAM
{
        # Ganesha can lift the NFS grace period early if NLM is disabled.
        Enable_NLM = false;

        # rquotad doesn't add any value here. CephFS doesn't support per-uid
        # quotas anyway.
        Enable_RQUOTA = false;

        # In this configuration, we're just exporting NFSv4. In practice, it's
        # best to use NFSv4.1+ to get the benefit of sessions.
        Protocols = 4;
}

NFSv4
{
    
        Minor_Versions =  1,2;
}
MDCACHE {
        # Size the dirent cache down as small as possible.
        Dir_Chunk = 0;
       # size the inode cache as small as possible
       NParts = 1;
       Cache_Size = 1;
}
EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 7;

        # Exported path (mandatory)
        Path = /volumes/kubernetes;
        #Path = /;

        # Pseudo Path (required for NFS v4)
        Pseudo = /cephfs_nfs;

        # Required for access (default is None)
        Squash = No_Root_Squash;
        # Could use CLIENT blocks instead
        protocols = 4;
        Access_Type = RW;
        # Time out attribute cache entries immediately
        Attr_Expiration_Time = 0;
        Transports = TCP;
        # Exporting FSAL
        FSAL {
             Name = CEPH;
             User_Id = "xxx";
             Secret_Access_Key = "xxx";
             Filesystem = "fs_data";
        }
}
CEPH{
}
LOG {                         # 日志模块
        components {

          ALL = INFO; # this will likely kill performance
        }
        Facility {
                name = FILE;
                destination = "/var/log/ganesha/ganesha.log";
                enable = active;
        }
}

**Comment by dang** [comment]
Luminous (12.x) is too old.  You'll need at least Nautilus (14.x) to use this version of Ganesha.

**Comment by liangxunchang** [comment]
> Luminous (12.x) is too old. You'll need at least Nautilus (14.x) to use this version of Ganesha.

nfs-ganesha V2.7.6 can support Luminous (12.x) ，right?  
because I have a problem about V2.7.1, nfs-ganesha will shut down sometimes。
just see /var/log/messages
kernel: ganesha.nfsd[136236]: segfault at 1784 ip 00007f9496303940 sp 00007f9452ff9510 error 4 in libcephfs.so.2.0.0[7f9496245000+117000]
/var/log/ganesha/ganesha.log
ganesha.nfsd-174790[svc_74] xdr_encode_nfs4_princ :ID MAPPER :INFO :nfs4_gid_to_name failed with code -2.
ganesha.nfsd-174790[svc_74] xdr_encode_nfs4_princ :ID MAPPER :INFO :Lookup for 101 failed, using numeric group
ganesha.nfsd-174790[svc_156] xdr_encode_nfs4_princ :ID MAPPER :INFO :nfs4_uid_to_name failed with code -2.
ganesha.nfsd-174790[svc_156] xdr_encode_nfs4_princ :ID MAPPER :INFO :Lookup for 1001 failed, using numeric owner

i have set core file ulimit -c  unlimited, but can not get core file。I don't know what can i do,Can only upgrade nfs-ganesha version

**Comment by dang** [comment]
It looks like 2.7.x can support Luminous.  However, we can't support 2.7.x, it's too old.

**Comment by liangxunchang** [comment]
got it ,thanks
