### ISSUE TITLE
[bug feedback] i record a video to reproduct this bug!

### ISSUE THREAD

**Issue by youshandefeiyang** [nfs-ganesha/nfs-ganesha#877]
thanks again!

**Comment by youshandefeiyang** [comment]
If the resolution of the video is only 360P, please wait for a while. This is because YouTube is still transcoding shortly after uploading. The actual resolution of the video is 4K, so that you can clearly locate the problem

**Comment by youshandefeiyang** [comment]
and this is my ganesha.conf,only use vfs
![79F60579-4F35-4DF4-BD0E-1F21B9996D3B](https://user-images.githubusercontent.com/63959400/202283981-2bf453e5-13c8-4c36-9c76-882e886c2c02.png)

**Comment by ffilz** [comment]
So you are exporting cloud fs and then restarting that? Ganesha isn't going to be able to properly deal with an exported filesystem being unmounted or restarted in any way. With non-FUSE VFS exports, Ganesha will be holding an open file descriptor on each exported file system that would prevent it from being unmounted. I'm not sure how FUSE works and that guarantee may not hold.

**Comment by dang** [comment]
I think you'll have to restart Ganesha if your FUSE mount goes away from under it.  So, if you restart the cloud service, restart Ganesha too.
