### ISSUE TITLE
NFSv3 isn't working?

### ISSUE THREAD

**Issue by Lotharyx** [nfs-ganesha/nfs-ganesha#878]
I'm sure it's a stupid user trick (where user == me), but here's my config:
```
NFS_CORE_PARAM {
        mount_path_pseudo = true;
        Protocols = NFSv3,V3,3,NFS3;
}

EXPORT
{
        Export_Id = 12345;
        Path = /home;
        Pseudo = /home;
        Protocols = NFSv3,V3,3,NFS3;
        Access_Type = RW;
        Squash = root_squash;
        Sectype = none;
        Anonymous_uid = 1000;
        Anonymous_gid = 1000;
        FSAL {
                Name = VFS;
        }
}
```
I see this during startup in the log, with -N NIV_DEBUG
```
export_commit_common :CONFIG :WARN :A protocol is specified for export 12345 that is not enabled in NFS_CORE_PARAM, fixing up
```
...and then this once the client attempts to connect:
```
mnt_Mnt :NFS3 :INFO :MOUNT: Export entry /home does not support NFS v3 for client ::ffff:172.18.1.47
```
Admitted ignorance: I have no idea what I should have in the FSAL section.  That's just the value from the example config.

Why is there that warning about "protocol specified...not enabled"?  Both the NFS_CORE_PARAM and EXPORT sections specify exactly the same set of protocols.

The client is Windows 10 with Services for NFS (as instructed by https://graspingtech.com/mount-nfs-share-windows-10/)

_(Yes, I'm exporting /home and mapping anonymous to a real user.  This is a throwaway system for testing.  Don't judge me!)_

**Comment by ffilz** [comment]
Try setting Protocols = 3; The list may be confusing something.

For your export, sectype should be sys or just let it default.

Otherwise everything looks OK.

**Comment by Lotharyx** [comment]
Okay, so I'm getting closer.  I had to add a CLIENTS { } block also specifying Protocols = 3.  That gets me able to mount.

However, with sectype = sys and a valid username/password combination, I can mount but still don't have write access.  All the permissions / ownerships on the server side are correct.  Sorry for what feels like a very n00bie question, but I am a n00bie with Ganesha, so...

**Comment by ffilz** [comment]
What is your config now?

**Comment by ffilz** [comment]
Oh, and what version of Ganesha?

**Comment by Lotharyx** [comment]
This is the config now:
```
NFS_CORE_PARAM {
        mount_path_pseudo = true;
        Protocols = 3;
}

EXPORT
{
        Export_Id = 12345;
        Path = /home;
        Pseudo = /home;
        Protocols = NFSv3, V3, 3, NFS3;
        Access_Type = RW;
        Squash = root_squash;
        Sectype = sys;
        Anonymous_uid = 1000;
        Anonymous_gid = 1000;
        CLIENT {
                Clients = *;
                Protocols = 3;
        }
        FSAL {
                Name = VFS;
        }
}

EXPORT
{
        Export_Id = 54321;
        Path = /home/builder/controller_build/home/builder;
        Pseudo = /builder;
        Protocols = NFSv3, V3, 3, NFS3;
        Access_Type = RW;
        Squash = root_squash;
        Sectype = sys;
        Anonymous_uid = 1001;
        Anonymous_gid = 1002;
        CLIENT {
                Clients = *;
                Protocols = 3;
                Access_Type = RW;
        }
        FSAL {
                Name = VFS;
        }
}
```
Ganesha version:
```
NFS-Ganesha Release = V4.0.12
ganesha.nfsd compiled on Nov 17 2022 at 07:43:26
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = b08457543bb58dbfab3bfeea310a5b9e6c0b5864
Git Describe = V4.0.12-0-gb08457543
```

**Comment by ffilz** [comment]
OK, let's get some debug. Add:

```
LOG {
    COMPONENTS {
       EXPORT = FULL_DEBUG;
   }
}
```

And then attach the resulting log.

**Comment by Lotharyx** [comment]
Here's the log.  I was watching it with `tail -f` and noticed it looked like nothing was logged while Windows was trying to create a file (r-click, "New > Text Document", eventually popped up "You need permission...")

[ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/10042496/ganesha.log)

Windows message:
![image](https://user-images.githubusercontent.com/5629932/202739380-77bdce24-b99a-4d56-a2d3-2e5592c20960.png)

The space statistics are correct, at least...

**Comment by ffilz** [comment]
The windows message isn't accessible to me...

I do see some weird stuff in the log where it is doing an export permission check apparently without an export. I'm not sure where that's happening, but later in the log, there are plenty of accesses to your export that are working fine.

I wonder if there's actually a problem over on the Windows side?

If I get some time, I can try a Windows mount myself and see if I can figure anything (fortunately my personal laptop that I do all my work on came with Windows 10 Pro so it includes the NFS client).

At this point, your config looks fine, so there is something either in Windows itself or the way Windows connects, though since I have access to the Windows NFS client, I have tested with it with success.

**Comment by ffilz** [comment]
is this still an issue?

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
