### ISSUE TITLE
Dependency on `/etc/mtab` - FSAL :CRIT :Error 2 in setmntent(/etc/mtab): No such file or directory

### ISSUE THREAD

**Issue by dgloeckner** [nfs-ganesha/nfs-ganesha#880]
I'm running NFS Ganesha in Kubernetes in a Ubuntu-based container.

```
2022-11-21 10:20:44 : ganesha-deployment-6dbbdfdc87-6gpl7 : ganesha.nfsd-36 : [none] FSAL :CRIT :Error 2 in setmntent(/etc/mtab): No such file or directory
```

For some Linux distros `/etc/mtab` seems to be missing. See here:

``` 
 kubectl run tmp-shell --restart=Never -i --tty --rm --image centos -- ls -la /etc/mtab
lrwxrwxrwx 1 root root 19 Sep 15  2021 /etc/mtab -> ../proc/self/mounts

kubectl run tmp-shell --restart=Never -i --tty --rm --image ubuntu -- ls -la /etc/mtab
ls: cannot access '/etc/mtab': No such file or directory
```

I admit that haven't researched about how Ganesha depends on `/etc/mtab` and what might be ways forward :)
Maybe one of the experts here could comment first. I could also try to work on a PR, depending on the needed effort.

**Comment by ffilz** [comment]
What FSAL are you using? Ganesha uses /etc/mtab to find the mounted filesystems that can be exported with FSAL_VFS, FSAL_XFS, and FSAL_GPFS.

**Comment by dgloeckner** [comment]
I'm using FSAL_VFS.

**Comment by ffilz** [comment]
OK, what can the container use to determine which filesystems are available to it? I hadn't hear about this issue for containers before... Is it at all a consequence of the container configuration?

**Comment by dgloeckner** [comment]
For Ubuntu-based container images the workaround could be to add a symbolic link:
```
ln -s /proc/mounts /etc/mtab
```

Seems to work fine.

**Comment by ffilz** [comment]
Ah, and that is actually what my Fedora VM has, well, /proc/self/mounts but looks like that's the solution.

Can we close this now?

**Comment by dgloeckner** [comment]
Can be closed. There's a workaround as explained above.
