### ISSUE TITLE
Segfaults in lru_bump_chunk called from mdcache_readdir_chunked

### ISSUE THREAD

**Issue by koen-struyve-q** [nfs-ganesha/nfs-ganesha#881]
We are currently encountering frequent segfaults on nfsganesha version 2.8.2 (on Ubuntu 16.04, custom FSAL, serving NFS v3), including the patch from issue https://github.com/nfs-ganesha/nfs-ganesha/issues/565.

These occur in this call to lru_bump_chunk at:

https://github.com/nfs-ganesha/nfs-ganesha/blob/7af861d3d1e1266e30be93dcdfb3ae146214c4ad/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c#L2084

https://github.com/nfs-ganesha/nfs-ganesha/blob/V2.8.2/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c#L2084

And called at this location from mdcache_readdir_chunked:

https://github.com/nfs-ganesha/nfs-ganesha/blob/7af861d3d1e1266e30be93dcdfb3ae146214c4ad/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c#L3089

Looking into older issues the only related one I could find is https://github.com/nfs-ganesha/nfs-ganesha/issues/504.

**Comment by ffilz** [comment]
Can you move to the current supported stable release V4.1?

If not, you may want to at least move to V2.8.4 which has a number of directory chunking fixes. Unfortunately as a very out of date release, we can't offer much support.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
