### ISSUE TITLE
It seems that the nfs ganesh service cannot be started

### ISSUE THREAD

**Issue by Cha1ice01** [nfs-ganesha/nfs-ganesha#883]
After compiling and installing nfs ganesha, I started rpcbind.service and then started ganesha Nfsd, but using the rpcinfo - p localhost command, the ganesha service is not started, and an error is reported in the log:

Starting: Ganesha Version V4.1-0-g6a84f9532, built at Nov 25 2022 18:38:00 on nas
25/11/2022 18:45:44 : epoch 63809cd8 : nas : nfs-ganesha-5366[main] main :MAIN :FATAL :open(/var/run/ganesha/ganesha.pid, O_CREAT | O_RDWR, 0644) failed for pid file, errno was: No such file or directory (2)

I found no ganesha directory in the/var/run directory. How can I solve this problem? thank you

**Comment by dang** [comment]
It you're not installing Ganesha from packages, you're responsible for making the directories that it needs yourself.  So make /var/run/ganesha, and /var/lib/nfs/ganesha.

**Comment by Cha1ice01** [comment]
Thank you for your answer. At present, I have solved this problem, but the service still cannot be started. A new error is reported in the log：

![47ET4BAMDYKKJV$4{FJHL89](https://user-images.githubusercontent.com/119041596/204421022-3c33ba89-d857-44b9-8d49-a7283b97208c.png)

**Comment by dang** [comment]
It looks like you configured AUTH_GSS but didn't set up kerberos on the server.

**Comment by ffilz** [comment]
What is your config? It looks like you have Protocols set in your NFS_CORE_PARAM that doesn't include a protocol version in your EXPORT.

**Comment by ffilz** [comment]
I think the GSS warnings can be ignored though you may want to specify SecType for your EXPORT that doesn't include krb5, krb5i, krb5p. You should be able to just specify SecType = sys;

**Comment by Cha1ice01** [comment]
Hello, I have inquired some information at present, but it is a little difficult for me. I just contacted them and didn't understand them very well. Please tell me what I should do. Thank you very much

**Comment by Cha1ice01** [comment]
Hello, I have inquired some information at present, but it is a little difficult for me. I just contacted them and didn't understand them very well. Please tell me what I should do. Thank you very much

**Comment by dang** [comment]
Getting the config file would help

**Comment by ffilz** [comment]
Could you try with Ganesha V4.3? There were some issues with Protocols configuration that may be impacting you. They are fully resolved in V4.3.

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
