### ISSUE TITLE
NFSv4 open report NFS4ERR_BAD_SEQID

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#885]
@ffilz I use mac and NFSv4.0 to mount, sometimes when open file, ganesha log NFS4ERR_BAD_SEQID, then can never self-healing, i.e. whenever open file, ganesha always report NFS4ERR_BAD_SEQID. 

It's hard to reproduce. The related log as follows, it seems some request missed, whose seqid is 1642942. But can not sure why this happen, do you have any suggestions ? 

Do we have any solution to make ganesha can recover from this error ? maybe delete the owner ?

`Previously known owner {STATE_OPEN_OWNER_NFSV4 0x7ff00b23ea00: clientid={0x7feefcab9000 ClientID={Epoch=0x6380421f Counter=0x00000531} CONFIRMED Client={0x7ff01312b100 name=(143:0x666462643a646330313a66653a323033343a3a313a3532313931666462643a6666313a636530303a3266663a313865333a613363353a3463663a316634620000000032f912514a8b1c1ecbdf00000000fdbddc0100fe20340000000000000001000000005b666462643a646330313a66653a323033343a3a315d3a2f002f566f6c756d65732f646174612f61667000) refcount=1} t_delta=0 reservations=1 refcount=4 cb_prog=1313231683 r_addr=10.10.10.10 r_netid=tcp6} owner=(4:0x000001f6) confirmed=1 seqid=1642941 refcount=477} is being reused
`

`OPEN: Invalid seqid 1642943 in request (not replay), expected seqid for {STATE_OPEN_OWNER_NFSV4 0x7ff00b23ea00: clientid={0x7feefcab9000 ClientID={Epoch=0x6380421f Counter=0x00000531} CONFIRMED Client={0x7ff01312b100 name=(143:0x666462643a646330313a66653a323033343a3a313a3532313931666462643a6666313a636530303a3266663a313865333a613363353a3463663a316634620000000032f912514a8b1c1ecbdf00000000fdbddc0100fe20340000000000000001000000005b666462643a646330313a66653a323033343a3a315d3a2f002f566f6c756d65732f646174612f61667000) refcount=1} t_delta=0 reservations=1 refcount=4 cb_prog=1313231683 r_addr=10.10.10.10 r_netid=tcp6} owner=(4:0x000001f6) confirmed=1 seqid=1642941 refcount=477}, returning NFS4ERR_BAD_SEQID`

`open4_open_owner failed`

**Comment by dang** [comment]
I'm not sure we can just recover, since the point of seqids is security and protocol correctness.  I think we need to understand why this happens.   Is there some way you can trigger it?  If so, then running a packet dump at the same time would help.   Otherwise, maybe a FULL_DEBUG log would help, but that could get very large, depending on traffic.

**Comment by ffilz** [comment]
I know there have been client side SEQID bugs. I'm not aware of any on the Ganesha side. Are you running the latest code on the Mac?

**Comment by liyinshubyte** [comment]
@dang @ffilz 
I find some clue, the request with seqid 1642942 is a close request, but ganesha can not find state at [nfs4_state_id.c:907](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/SAL/nfs4_state_id.c#L907)(will continue to find the reason of this) , so ganesha thought it as a replay request at [nfs4_state_id.c:984](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/SAL/nfs4_state_id.c#L984), and return NFS4_OK at [nfs4_op_close.c:223](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_close.c#L223).

 So this close request did not call `Copy_nfs4_state_req`, and did not save seqid  1642942 to `owner->so_owner.so_nfs4_owner.so_seqid` which is 1642941. When next request with seqid 1642943 come, `BAD_SEQ_ID` happens, because ganesha need next request with seqid 1642942. 

Maybe we should call Copy_nfs4_state_req before return this close request ?

**Comment by ffilz** [comment]
Ah, OK, that sequence makes sense. Let me look into how to fix it, I don't think it should be too much of an issue.

There may be a client issue though. The Linux client had a few patches to resolve race between close and open and that may be why we don't see the issue with Linux clients.

**Comment by liyinshubyte** [comment]
The reason of ganesha could not find state is the state has been deleted when close file. 

> I find some clue, the request with seqid 1642942 is a close request, but ganesha can not find state at [nfs4_state_id.c:907](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/SAL/nfs4_state_id.c#L907)(will continue to find the reason of this) , so ganesha thought it as a replay request at [nfs4_state_id.c:984](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/SAL/nfs4_state_id.c#L984), and return NFS4_OK at [nfs4_op_close.c:223](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_close.c#L223).


The problem is, I log some message at [nfs4_op_close.c:180](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_close.c#L180). The log code and the log as follows. The first fileid:52917295629524609 close, then delete state:20007-25-11999-44-10320, but the second fileid:52917295629524406 with the same state:20007-25-11999-44-10320 also close, but it could not find the deleted state:20007-25-11999-44-10320. The problem is different fileid share the same `arg_CLOSE4->open_stateid.other`, is it correct? 

```
	if (data->current_obj) {
		std::string str = "";
		for (int i = 0; i < 12; i ++) {
			str += std::to_string(arg_CLOSE4->open_stateid.other[i]);
		}
	        LogInfo(COMPONENT_STATE, "liyinshu seqid %d fileid %lu other %s",
		  arg_CLOSE4->seqid, data->current_obj->fileid, str.c_str());
	}
```


2022-12-02 20:58:03.806684| liyinshu seqid 373161 fileid 52917295629524609 other 20007-25-11999-44-10320
2022-12-02 20:58:03.806998| liyinshu state del other 20007-25-11999-44-10320
2022-12-02 20:58:08.348320| liyinshu seqid 373661 fileid 52917295629524406 other 20007-25-11999-44-10320

**Comment by ffilz** [comment]
You might enable FULL_DEBUG for COMPONENT_STATE.

We should not re-use "other" values, they are created from an atomic int counter so there should be no duplicates.

We do delete the state on close.

**Comment by liyinshubyte** [comment]
@ffilz From the log, I think it's mac client's bug.  fileid 52917295629524406 should not have the state, and ganesha also did not assign state for this fileid. macos mixup the state between this two inodes. But not sure how to fix this in ganesha, at lease client can recover from this bug, not hang forever. Maybe, I have two immature suggestions.
1.  we can relax the seqid, i.e. accept bigger next_seqid, even though the next_seqid not equal to current_seqid+1 
2. even though could not find the state, we still asign 	`arg_CLOSE4->seqid` to	`open_owner->so_owner.so_nfs4_owner.so_seqid`, but the problem is `open_owner` comes from `state->state_owner`, we can not find state, the `open_owner` also is null, we can not assign the `so_seqid`.


> 2022-12-02 20:58:03.806684| liyinshu seqid 373161 fileid 52917295629524609 other 20007-25-11999-44-10320
> 2022-12-02 20:58:03.806998| liyinshu state del other 20007-25-11999-44-10320
> 2022-12-02 20:58:08.348320| liyinshu seqid 373661 fileid 52917295629524406 other 20007-25-11999-44-10320

**Comment by ffilz** [comment]
There have been some fixes that maybe address this, I'm not sure. Please try with Ganesha V4.3.

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
