### ISSUE TITLE
More than one ganesha.nfsd process and only one bus in DBUS

### ISSUE THREAD

**Issue by gchmurka123** [nfs-ganesha/nfs-ganesha#887]
I run several ganesha.nfsd  processes in one server.
I would like to be able to control or check the status for each process separately

Is it possible to add an option to be able to define a bus in DBUS during process startup (such as pidfile, config file)?
Currently the "org.ganesha.nfsd" bus looks to be compiled.

**Comment by ffilz** [comment]
That would be a reasonable option to add to the config file. If that is something you feel comfortable coding, we would accept a patch otherwise I can put it on my to-do list for V5.0.

**Comment by gchmurka123** [comment]
In: `src/doc/man/ganesha-core-config.rst`

i see options:
```

Dbus_Name_Prefix
    DBus name prefix. Required if one wants to run multiple ganesha instances on single host.
    The prefix should be different for every ganesha instance. If this is set, the dbus name will be <prefix>.org.ganesha.nfsd
```
I'll check if it works, maybe it will be enough in my case.

**Comment by taodh** [comment]
@gchmurka123  Hello,gchmurka123
How to implement “More than one ganesha.nfsd process and only one bus in DBUS”？Can you provide a detailed description

**Comment by dang** [comment]
It does not appear to be possible to have multiple processes provide a single DBUS tree.

**Comment by gchmurka123** [comment]
I had a problem with controlling Ganesha via DBUS because by default the process is stopped via dbus in systemd services.
The situation was as follows:

  - started the ganesha1 process
  - started the ganesha2 process
  - started the ganesha3 process

Stopping via defualt systemd ExecStop ganesha1 or ganesha2 process, always "killed" the last started ganesha process (in this case ganesha3), because the last started process always made a handle in the DBUS (overwriting old processes).

Prefixes solved my problem and currently, I am successfully running about 10 Ganesha processes on one machine.

Now i use Dbus_Name_Prefix
in config file:
```
NFS_CORE_PARAM {
        Bind_addr = 192.168.2.1;
        Protocols = 3,4;
        mount_path_pseudo = true;
        Clustered = false;
        Enable_NLM = false;
        Dbus_Name_Prefix = nfs2;
}
```
and in systemd service control process like:

```
ExecStop=/bin/dbus-send --system   --dest=nfs2.org.ganesha.nfsd --type=method_call /org/ganesha/nfsd/admin org.ganesha.nfsd.admin.shutdown
```

I thing that other Ganesha DBUS command like add NFS exports will work good in prefixes.

**Comment by ffilz** [comment]
It looks like the capability is already in Ganesha and it looks like you have this working now. Can we close this?

**Comment by gchmurka123** [comment]
Closing
