### ISSUE TITLE
ganesha v4.0.11 breaks something

### ISSUE THREAD

**Issue by amartel** [nfs-ganesha/nfs-ganesha#888]
Hi,

I'm using nfs-ganesha 4.0.1 on CentOS Stream release 8 with CEPH FSAL and I'm trying to update my ganesha server to the last release (4.2). I was able to build ganesha v4.2 but I think that CEPH FSAL is now broken because all my previous mount commands don't work anymore. After several tests, I found that ganesha v4.0.10 is working as expected and v4.0.11 not, so I suspect that something changed between 4.0.10 and 4.0.11 (but I don't know if there are new settings to use or if there is something wrong in the source code, or with my build process).

I used the following commands to build nfs-ganesha 4.0.1:
cd /work
git clone --recursive https://github.com/nfs-ganesha/nfs-ganesha.git
cd ganesha
git checkout 4.0.1
cd src
git clone https://github.com/nfs-ganesha/ntirpc.git libntirpc
cd libntirpc
git checkout v4.0
mkdir /work/build
cd /work/build
cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev -DUSE_9P=OFF -DUSE_FSAL_CEPH=ON -DUSE_FSAL_GLUSTER=OFF -DUSE_FSAL_LUSTRE=OFF -DUSE_FSAL_LIZARDFS=OFF -DUSE_FSAL_GPFS=OFF -DUSE_FSAL_RGW=OFF -DRADOS_URLS=ON -DUSE_RADOS_RECOV=ON -D_MSPAC_SUPPORT=OFF -DUSE_GSS=ON -DALLOCATOR=libc -DENABLE_RFC_ACL=OFF -DCMAKE_INSTALL_PREFIX=/usr ../ganesha/src
make
make install

Then, to build release 4.2, I used:
cd /work/ganesha/src/libntirpc
git checkout v4.2
cd /work/ganesha
git checkout v4.2
cmake (with the same options)
make && make install

And to build ganesha 4.0.10:
cd /work/ganesha/src/libntirpc
git checkout v4.0
cd /work/ganesha
git checkout v4.0.10
cmake (with the same options)
make && make install

do you have any suggestions ?

**Comment by ffilz** [comment]
Could you do a git-bisect between 4.0.10 and 4.0.11? I don't see anything there that jumps out as affecting FSAL_CEPH and there certainly aren't any FSAL_CEPH changes in 4.,0.11.

**Comment by ffilz** [comment]
We hit a similar problem, I think it is fixed here:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/547188

There are two patches, so if you want to check it out, download:

git fetch ssh://ffilz@review.gerrithub.io:29418/ffilz/nfs-ganesha refs/changes/88/547188/1 && git checkout FETCH_HEAD

**Comment by ajarr** [comment]
> We hit a similar problem, I think it is fixed here:
> 
> https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/547188
> 
> There are two patches, so if you want to check it out, download:
> 
> git fetch ssh://[ffilz@review.gerrithub.io](mailto:ffilz@review.gerrithub.io):29418/ffilz/nfs-ganesha refs/changes/88/547188/1 && git checkout FETCH_HEAD

This fix worked for me, and I no longer hit the issue https://tracker.ceph.com/issues/58145

**Comment by amartel** [comment]
Thank's very much for yours answers and you was right: the problem seemed to be with the EXPORT_DEFAULTS block. 

For information, V4.2.1 doesn't fix it but, now, I have a workaround: put the settings from my EXPORT_DEFAULTS block into all EXPORT blocks. 

Extract from my /etc/ganesha/ganesha.conf:
EXPORT_DEFAULTS {
        Attr_Expiration_Time = 0;
        Squash = root_squash;
        Protocols = 4;
        Manage_Gids = true;
        Delegations = r;
} 

In my situation, "Protocols" wasn't defined elsewhere and that's why I was unable to mount my CEPH exports...

**Comment by ffilz** [comment]
V4.3 has been tagged with a fix for this issue. Closing.
