### ISSUE TITLE
Unable to create file on client with nfsv3 (ganesha+gluster)

### ISSUE THREAD

**Issue by LLVIC** [nfs-ganesha/nfs-ganesha#890]
When creating a file on client node, the operation stuck. The logs are as follows:

ganesha.log:
28/12/2022 13:47:59 : epoch 639c9316 : ganesha.nfsd-14112[svc_174] glusterfs_setattr2 :FSAL :CRIT :setattrs failed with error Success

Also, I executed 'tcpdump' on server node while touching a fille on client node. Such errors have been captured: "NFS3ERR_JUKEBOX", "ERR_NOENT"

The fault has been solved by restarting nfs-ganesha, however, the reason why it happened has not been figured out.

**Comment by ffilz** [comment]
We need more info on this. What version of Ganesha? When client side operation causes this?

Oh, and crud, that's a horrible log message... The code is:

        if (FSAL_IS_ERROR(status)) {
                LogCrit(COMPONENT_FSAL,
                         "setattrs failed with error %s",
                         strerror(status.minor));
        }

It doesn't log status.major... Somewhere status.minor isn't being set...

**Comment by LLVIC** [comment]
> We need more info on this. What version of Ganesha? When client side operation causes this?
> 
> Oh, and crud, that's a horrible log message... The code is:
> 
> ```
>     if (FSAL_IS_ERROR(status)) {
>             LogCrit(COMPONENT_FSAL,
>                      "setattrs failed with error %s",
>                      strerror(status.minor));
>     }
> ```
> 
> It doesn't log status.major... Somewhere status.minor isn't being set...


The version of Ganesha we use is 3.4-2.  We don't know exactly which operation caused this, it just happened suddenly when we tried to touch a file on client side.

**Comment by ffilz** [comment]
There are a number of fixes in the latest V4.3 release. Please try that release and see if the problem still occurs.

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
