### ISSUE TITLE
[Regression] nfs-ganesha 4.2 breaks exports 

### ISSUE THREAD

**Issue by kalebskeithley** [nfs-ganesha/nfs-ganesha#893]
Description of problem:
No exports are accessible when using nfs-ganesha 4.2. Configuration works fine with 4.0.

Version-Release number of selected component (if applicable):
nfs-ganesha-4.2-1.fc37.x86_64

How reproducible:
Always.

Steps to Reproduce:
1. Upgrade nfs-ganesha to 4.2.
2. Restart, reset client automounts.
3. Attempt to use NFS mount point.

Actual results:
$ ls /nfs/home/james
ls: cannot access '/nfs/home/james': No such file or directory

Expected results:
$ ls /nfs/home/james
Archive  bin  Documents  holiday  keepass-keys  Pictures  scr  secret  src  sysadmin  Videos

**Comment by drjhe** [comment]
Note this comes from downstream https://bugzilla.redhat.com/show_bug.cgi?id=2154169 for which I'm the original reporter.

I think this is actually a manifestation of #888. (I created the downstream bug, which has workaround details, mainly for distro tracking and to help other Fedora users.)

**Comment by ffilz** [comment]
Yes, if the workaround resolves the issue, this is a dupe.

**Comment by drjhe** [comment]
Tested as fixed in 4.2.2 and 4.3.

**Comment by ffilz** [comment]
Great, I'll close this then.
