### ISSUE TITLE
LRU can not being able to reclaim, memory is going to high.

### ISSUE THREAD

**Issue by twoholes** [nfs-ganesha/nfs-ganesha#894]
Memory will be high  after serval hours of writing files.

this is massif output:
--------------------------------------------------------------------------------
  n        time(i)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
 89 388,117,541,481      275,226,032      268,474,565     6,751,467            0
 90 391,513,083,464      276,256,968      269,474,936     6,782,032            0
 91 393,677,656,463      277,084,352      270,280,141     6,804,211            0
97.54% (270,280,141B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->61.07% (169,205,760B) 0x4F96359: alloc_cache_entry (mdcache_lru.c:1901)
| ->61.07% (169,205,760B) 0x4F96408: mdcache_lru_get (mdcache_lru.c:1938)
|   ->61.07% (169,205,760B) 0x4F82A7F: _mdcache_alloc_handle (mdcache_helpers.c:174)
|     ->61.07% (169,205,760B) 0x4F84B99: mdcache_new_entry (mdcache_helpers.c:709)
|       ->61.04% (169,125,120B) 0x4F736D4: mdcache_alloc_and_check_handle (mdcache_handle.c:100)
|       | ->56.64% (156,949,632B) 0x4F7B182: mdcache_open2 (mdcache_file.c:443)
|       | | ->56.64% (156,949,632B) 0x4E5793C: open2_by_name (fsal_helper.c:443)
|       | |   ->56.64% (156,949,632B) 0x4E5A23E: fsal_open2 (fsal_helper.c:1650)
|       | |     ->56.64% (156,949,632B) 0x4F37229: open4_ex (nfs4_op_open.c:989)
|       | |       ->56.64% (156,949,632B) 0x4F38A60: nfs4_op_open (nfs4_op_open.c:1402)
|       | |         ->56.64% (156,949,632B) 0x4F1FD5C: process_one_op (nfs4_Compound.c:918)
|       | |           ->56.64% (156,949,632B) 0x4F20C2B: nfs4_Compound (nfs4_Compound.c:1324)
|       | |             ->56.64% (156,949,632B) 0x4E7A192: nfs_rpc_process_request (nfs_worker_thread.c:1499)
|       | |               ->56.64% (156,949,632B) 0x4E7A69F: nfs_rpc_valid_NFS (nfs_worker_thread.c:1714)
|       | |                 ->56.64% (156,949,632B) 0x5281B4A: svc_vc_decode (svc_vc.c:904)
|       | |                   ->56.64% (156,949,632B) 0x527DA18: svc_request (svc_rqst.c:1202)
|       | |                     ->56.64% (156,949,632B) 0x5281A53: svc_vc_recv (svc_vc.c:877)
|       | |                       ->56.64% (156,949,632B) 0x527D999: svc_rqst_xprt_task_recv (svc_rqst.c:1183)
|       | |                         ->56.62% (156,880,512B) 0x527E52D: svc_rqst_epoll_loop (svc_rqst.c:1564)
|       | |                         | ->56.62% (156,880,512B) 0x528906D: work_pool_thread (work_pool.c:183)
|       | |                         |   ->56.62% (156,880,512B) 0x601DDC3: start_thread (in /usr/lib64/libpthread-2.17.so)
|       | |                         |     ->56.62% (156,880,512B) 0x674A73B: clone (in /usr/lib64/libc-2.17.so)
|       | |                         |       
|       | |                         ->00.02% (69,120B) in 1+ places, all below ms_print's threshold (01.00%)
|       | |                         
|       | ->04.39% (12,175,488B) 0x4F7402E: mdcache_mkdir (mdcache_handle.c:254)
|       |   ->04.39% (12,175,488B) 0x4E58B08: fsal_create (fsal_helper.c:1053)
|       |     ->04.39% (12,167,424B) 0x4F24284: nfs4_op_create (nfs4_op_create.c:234)
|       |     | ->04.39% (12,167,424B) 0x4F1FD5C: process_one_op (nfs4_Compound.c:918)
|       |     |   ->04.39% (12,167,424B) 0x4F20C2B: nfs4_Compound (nfs4_Compound.c:1324)
|       |     |     ->04.39% (12,167,424B) 0x4E7A192: nfs_rpc_process_request (nfs_worker_thread.c:1499)
|       |     |       ->04.39% (12,167,424B) 0x4E7A69F: nfs_rpc_valid_NFS (nfs_worker_thread.c:1714)
|       |     |         ->04.39% (12,167,424B) 0x5281B4A: svc_vc_decode (svc_vc.c:904)
|       |     |           ->04.39% (12,167,424B) 0x527DA18: svc_request (svc_rqst.c:1202)
|       |     |             ->04.39% (12,167,424B) 0x5281A53: svc_vc_recv (svc_vc.c:877)
|       |     |               ->04.39% (12,167,424B) 0x527D999: svc_rqst_xprt_task_recv (svc_rqst.c:1183)
|       |     |                 ->04.39% (12,163,968B) 0x527E52D: svc_rqst_epoll_loop (svc_rqst.c:1564)
|       |     |                 | ->04.39% (12,163,968B) 0x528906D: work_pool_thread (work_pool.c:183)
|       |     |                 |   ->04.39% (12,163,968B) 0x601DDC3: start_thread (in /usr/lib64/libpthread-2.17.so)
|       |     |                 |     ->04.39% (12,163,968B) 0x674A73B: clone (in /usr/lib64/libc-2.17.so)
|       |     |                 |       
|       |     |                 ->00.00% (3,456B) in 1+ places, all below ms_print's threshold (01.00%)
|       |     |                 
|       |     ->00.00% (8,064B) in 1+ places, all below ms_print's threshold (01.00%)
|       |     
|       ->00.03% (80,640B) in 1+ places, all below ms_print's threshold (01.00%)
|       
->17.60% (48,757,296B) 0x4E9C68A: hashtable_init (hashtable.c:340)
| ->06.34% (17,563,112B) 0x4EEC033: nfs4_acls_init (nfs4_acls.c:251)
| | ->06.34% (17,563,112B) 0x4E802EC: nfs_Init (nfs_init.c:636)
| |   ->06.34% (17,563,112B) 0x4E80F22: nfs_start (nfs_init.c:923)
| |     ->06.34% (17,563,112B) 0x4029F7: main (in /usr/bin/ganesha.nfsd)
| |  

The lru_state.entries_hiwat = 100000, I add some log show the lru_state.entries_used.
In the log, lru_state.entries_usedis is always growing, that seems lru reap is not take effect when lru_state.entries_used>lru_state.entries_hiwat.
this is my log:
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_489] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124772 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_541] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124773 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_542] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124774 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_402] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124775 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_517] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124775 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_542] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124775 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_489] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124776 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_554] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124776 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_543] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_514] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_547] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_543] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_554] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_556] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_548] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_527] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_557] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_556] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_538] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_402] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_529] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_514] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_538] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_529] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_531] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_464] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_547] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_559] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_543] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_527] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124778 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_489] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124780 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_548] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124781 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_464] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124781 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_531] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124781 100000
06/01/2023 17:58:09 : epoch 63b7ea4f : saoss13 : ganesha.nfsd-19358[svc_541] lru_try_reap_entry :INODE :CRIT :========LRU COUNT: 124781 100000

**Comment by ffilz** [comment]
Which version of Ganesha? Which FSAL?

If you aren't already using V4.x, preferably V4.2.2, there may be some improvement.

Likely what you really need is a patch set scheduled for V5.0, this is the HEAD:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/545915/

Optionally from github:

https://github.com/nfs-ganesha/nfs-ganesha/compare/next...ffilz:nfs-ganesha:ceph-async

**Comment by twoholes** [comment]
hi, Sorry for the late reply.

My ganesha version is V4.0.3.
The LRU question above has been resolved by modify LRU_Run_Interval and Entries_Release_Size.

Then, I use VFS as the FSAL.
Test tool is vdbench, creating 100,000,000 4K files.
When I stop the testing, memory is also high, I can see LRU entris has been reaped by the log entries_used.

MEM info  by cmd: ps aux 
------------------------
[root@host102438055 ~]# ps aux | grep ganesha
root      2476  0.0  0.0 112648   964 pts/1    S+   17:25   0:00 grep --color=auto ganesha
root     33386 91.0  0.4 723476 561420 pts/0   Sl+  16:33  47:59 valgrind --tool=exp-dhat /usr/bin/ganesha.nfsd -F -L /dev/null -f /etc/ganesha/ganesha.conf
------------------------

the log by valgrind like this:
-----------------------
==33386== ======== SUMMARY STATISTICS ========
==33386== 
==33386== guest_insns:  118,647,306,980
==33386== 
==33386== max_live:     647,937,151 in 1,534,571 blocks
==33386== 
==33386== tot_alloc:    32,339,483,649 in 36,993,207 blocks
==33386== 
==33386== insns per allocated byte: 3
==33386== 
==33386== 
==33386== ======== ORDERED BY decreasing "max-bytes-live": top 10 allocators ========
==33386== 
==33386== -------------------- 1 of 10 --------------------
==33386== max-live:    438,622,848 in 380,749 blocks
==33386== tot-alloc:   438,645,888 in 380,769 blocks (avg size 1152.00)
==33386== deaths:      380,693, at avg age 58,997,098,116 (49.72% of prog lifetime)
==33386== acc-ratios:  7.28 rd, 2.44 wr  (3,196,790,778 b-read, 1,073,422,248 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4F9662D: alloc_cache_entry (mdcache_lru.c:1929)
==33386==    by 0x4F966DB: mdcache_lru_get (mdcache_lru.c:1967)
==33386==    by 0x4F82A70: _mdcache_alloc_handle (mdcache_helpers.c:174)
==33386==    by 0x4F84B8A: mdcache_new_entry (mdcache_helpers.c:709)
==33386==    by 0x4F736C5: mdcache_alloc_and_check_handle (mdcache_handle.c:100)
==33386==    by 0x4F7B173: mdcache_open2 (mdcache_file.c:443)
==33386==    by 0x4E5792D: open2_by_name (fsal_helper.c:443)
==33386==    by 0x4E5A22F: fsal_open2 (fsal_helper.c:1650)
==33386==    by 0x4F3721A: open4_ex (nfs4_op_open.c:989)
==33386==    by 0x4F38A51: nfs4_op_open (nfs4_op_open.c:1402)
==33386==    by 0x4F1FD4D: process_one_op (nfs4_Compound.c:918)
==33386== 
==33386== -------------------- 2 of 10 --------------------
==33386== max-live:    129,454,660 in 380,749 blocks
==33386== tot-alloc:   129,461,460 in 380,769 blocks (avg size 340.00)
==33386== deaths:      380,693, at avg age 58,997,098,391 (49.72% of prog lifetime)
==33386== acc-ratios:  3.32 rd, 1.38 wr  (431,064,085 b-read, 179,257,382 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x92E501B: vfs_sub_alloc_handle (subfsal_vfs.c:95)
==33386==    by 0x92D533C: alloc_handle (handle.c:140)
==33386==    by 0x92DE211: vfs_open2 (file.c:871)
==33386==    by 0x4F7AD7E: mdcache_open2 (mdcache_file.c:387)
==33386==    by 0x4E5792D: open2_by_name (fsal_helper.c:443)
==33386==    by 0x4E5A22F: fsal_open2 (fsal_helper.c:1650)
==33386==    by 0x4F3721A: open4_ex (nfs4_op_open.c:989)
==33386==    by 0x4F38A51: nfs4_op_open (nfs4_op_open.c:1402)
==33386==    by 0x4F1FD4D: process_one_op (nfs4_Compound.c:918)
==33386==    by 0x4F20C1C: nfs4_Compound (nfs4_Compound.c:1324)
==33386==    by 0x4E7A183: nfs_rpc_process_request (nfs_worker_thread.c:1499)
==33386== 
==33386== Aggregated access counts by offset:
==33386== 
==33386== [   0]  1523219 1523219 1523219 1523219 1523219 1523219 1523219 1523219 1750018 1750018 1750018 1750018 1750018 1750018 1750018 1750018 
==33386== [  16]  3046488 3046488 3046488 3046488 3046488 3046488 3046488 3046488 4949945 4949945 4949945 4949945 4949945 4949945 4949945 4949945 
==33386== [  32]  7996659 7996659 7996659 7996659 7996659 7996659 7996659 7996659 19419629 19419629 19419629 19419629 3427241 3427241 3427241 3427241 
==33386== [  48]  380769 380769 380769 380769 380769 380769 380769 380769 2284655 2284655 2284655 2284655 2665517 2665517 2665517 2665517 
==33386== [  64]  7615451 7615451 7615451 7615451 761538 761538 761538 761538 380769 380769 380769 380769 380769 380769 380769 380769 
==33386== [  80]  380769 380769 380769 380769 380769 380769 380769 380769 761538 761538 761538 761538 380769 380769 380769 380769 
==33386== [  96]  6473358 6473358 6473358 6473358 0 0 0 0 761538 761538 761538 761538 761538 761538 761538 761538 
==33386== [ 112]  761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 761538 
==33386== [ 128]  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
==33386== [ 144]  380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 
==33386== [ 160]  7235312 7235312 7235312 7235312 7235312 7235312 7235312 7235312 1523355 1523355 1523355 1523355 1523355 1523355 1523355 1523355 
==33386== [ 176]  380769 380769 380769 380769 380769 380769 380769 380769 1523236 1523236 1523236 1523236 1523236 1523236 1523236 1523236 
==33386== [ 192]  1523256 1523256 1523256 1523256 1523256 1523256 1523256 1523256 1523256 1523256 1523256 1523256 0 0 0 0 
==33386== [ 208]  1142344 1142344 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
==33386== [ 224]  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
==33386== [ 240]  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
==33386== [ 256]  1142566 1142566 1142566 1142566 1142566 1142566 1142566 1142566 0 0 0 0 0 0 0 0 
==33386== [ 272]  761462 761462 761462 761462 0 0 0 0 4188936 3808123 3427221 6473673 6473673 6473673 6473673 6473673 
==33386== [ 288]  6473673 6473673 6854575 6854575 7021526 7021526 7021526 7021526 6854575 3808123 3808123 380769 380769 380769 380769 380769 
==33386== [ 304]  380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 380769 
==33386== [ 320]  380769 380769 380769 380769 594587 594587 594587 594587 380769 380769 380769 380769 380769 380769 380769 380769 
==33386== [ 336]  380769 380769 380769 380769 
==33386== 
==33386== -------------------- 3 of 10 --------------------
==33386== max-live:    18,275,952 in 380,749 blocks
==33386== tot-alloc:   18,276,912 in 380,769 blocks (avg size 48.00)
==33386== deaths:      380,693, at avg age 58,997,095,222 (49.72% of prog lifetime)
==33386== acc-ratios:  0.99 rd, 2.09 wr  (18,273,264 b-read, 38,368,008 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4F83E36: mdc_check_mapping (mdcache_helpers.c:393)
==33386==    by 0x4F82C0F: _mdcache_alloc_handle (mdcache_helpers.c:220)
==33386==    by 0x4F84B8A: mdcache_new_entry (mdcache_helpers.c:709)
==33386==    by 0x4F736C5: mdcache_alloc_and_check_handle (mdcache_handle.c:100)
==33386==    by 0x4F7B173: mdcache_open2 (mdcache_file.c:443)
==33386==    by 0x4E5792D: open2_by_name (fsal_helper.c:443)
==33386==    by 0x4E5A22F: fsal_open2 (fsal_helper.c:1650)
==33386==    by 0x4F3721A: open4_ex (nfs4_op_open.c:989)
==33386==    by 0x4F38A51: nfs4_op_open (nfs4_op_open.c:1402)
==33386==    by 0x4F1FD4D: process_one_op (nfs4_Compound.c:918)
==33386==    by 0x4F20C1C: nfs4_Compound (nfs4_Compound.c:1324)
==33386== 
==33386== Aggregated access counts by offset:
==33386== 
==33386== [   0]  380769 380769 380769 380769 380769 380769 380769 380769 761462 761462 761462 761462 761462 761462 761462 761462 
==33386== [  16]  1749706 1749706 1749706 1749706 1749706 1749706 1749706 1749706 1523219 1523219 1523219 1523219 1523219 1523219 1523219 1523219 
==33386== [  32]  1522848 1522848 1522848 1522848 1522848 1522848 1522848 1522848 1142155 1142155 1142155 1142155 1142155 1142155 1142155 1142155 
==33386== 
==33386== -------------------- 4 of 10 --------------------
==33386== max-live:    17,563,112 in 67 blocks
==33386== tot-alloc:   17,563,112 in 67 blocks (avg size 262136.00)
==33386== deaths:      none (none of these blocks were freed)
==33386== acc-ratios:  0.00 rd, 0.00 wr  (0 b-read, 0 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4E9C67B: hashtable_init (hashtable.c:340)
==33386==    by 0x4EEC024: nfs4_acls_init (nfs4_acls.c:251)
==33386==    by 0x4E802DD: nfs_Init (nfs_init.c:636)
==33386==    by 0x4E80F13: nfs_start (nfs_init.c:923)
==33386==    by 0x4029F8: main (nfs_main.c:522)
==33386== 
==33386== -------------------- 5 of 10 --------------------
==33386== max-live:    9,654,912 in 8,381 blocks
==33386== tot-alloc:   9,700,992 in 8,421 blocks (avg size 1152.00)
==33386== deaths:      8,401, at avg age 67,682,203,176 (57.04% of prog lifetime)
==33386== acc-ratios:  192.36 rd, 37.09 wr  (1,866,130,559 b-read, 359,832,846 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4F9662D: alloc_cache_entry (mdcache_lru.c:1929)
==33386==    by 0x4F966DB: mdcache_lru_get (mdcache_lru.c:1967)
==33386==    by 0x4F82A70: _mdcache_alloc_handle (mdcache_helpers.c:174)
==33386==    by 0x4F84B8A: mdcache_new_entry (mdcache_helpers.c:709)
==33386==    by 0x4F736C5: mdcache_alloc_and_check_handle (mdcache_handle.c:100)
==33386==    by 0x4F7401F: mdcache_mkdir (mdcache_handle.c:254)
==33386==    by 0x4E58AF9: fsal_create (fsal_helper.c:1053)
==33386==    by 0x4F24275: nfs4_op_create (nfs4_op_create.c:234)
==33386==    by 0x4F1FD4D: process_one_op (nfs4_Compound.c:918)
==33386==    by 0x4F20C1C: nfs4_Compound (nfs4_Compound.c:1324)
==33386==    by 0x4E7A183: nfs_rpc_process_request (nfs_worker_thread.c:1499)
==33386== 
==33386== -------------------- 6 of 10 --------------------
==33386== max-live:    6,853,482 in 380,749 blocks
==33386== tot-alloc:   6,853,842 in 380,769 blocks (avg size 18.00)
==33386== deaths:      380,693, at avg age 58,997,095,085 (49.72% of prog lifetime)
==33386== acc-ratios:  3.00 rd, 1.77 wr  (20,565,054 b-read, 12,184,608 b-written)
==33386==    at 0x4C25FD3: malloc (vg_replace_malloc.c:299)
==33386==    by 0x4F819F3: cih_hash_key (mdcache_hash.h:209)
==33386==    by 0x4F84CF7: mdcache_new_entry (mdcache_helpers.c:754)
==33386==    by 0x4F736C5: mdcache_alloc_and_check_handle (mdcache_handle.c:100)
==33386==    by 0x4F7B173: mdcache_open2 (mdcache_file.c:443)
==33386==    by 0x4E5792D: open2_by_name (fsal_helper.c:443)
==33386==    by 0x4E5A22F: fsal_open2 (fsal_helper.c:1650)
==33386==    by 0x4F3721A: open4_ex (nfs4_op_open.c:989)
==33386==    by 0x4F38A51: nfs4_op_open (nfs4_op_open.c:1402)
==33386==    by 0x4F1FD4D: process_one_op (nfs4_Compound.c:918)
==33386==    by 0x4F20C1C: nfs4_Compound (nfs4_Compound.c:1324)
==33386==    by 0x4E7A183: nfs_rpc_process_request (nfs_worker_thread.c:1499)
==33386== 
==33386== Aggregated access counts by offset:
==33386== 
==33386== [   0]  1523272 1523272 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 1904041 
==33386== [  16]  1523272 1523272 
==33386== 
==33386== -------------------- 7 of 10 --------------------
==33386== max-live:    4,456,312 in 17 blocks
==33386== tot-alloc:   4,456,312 in 17 blocks (avg size 262136.00)
==33386== deaths:      none (none of these blocks were freed)
==33386== acc-ratios:  0.68 rd, 0.00 wr  (3,046,584 b-read, 8 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4E9C67B: hashtable_init (hashtable.c:340)
==33386==    by 0x4ECE19E: nfs_Init_client_id (nfs4_clientid.c:1778)
==33386==    by 0x4E806C1: nfs_Init (nfs_init.c:707)
==33386==    by 0x4E80F13: nfs_start (nfs_init.c:923)
==33386==    by 0x4029F8: main (nfs_main.c:522)
==33386== 
==33386== -------------------- 8 of 10 --------------------
==33386== max-live:    4,456,312 in 17 blocks
==33386== tot-alloc:   4,456,312 in 17 blocks (avg size 262136.00)
==33386== deaths:      none (none of these blocks were freed)
==33386== acc-ratios:  0.00 rd, 0.00 wr  (32 b-read, 16 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4E9C67B: hashtable_init (hashtable.c:340)
==33386==    by 0x4ECE21A: nfs_Init_client_id (nfs4_clientid.c:1787)
==33386==    by 0x4E806C1: nfs_Init (nfs_init.c:707)
==33386==    by 0x4E80F13: nfs_start (nfs_init.c:923)
==33386==    by 0x4029F8: main (nfs_main.c:522)
==33386== 
==33386== -------------------- 9 of 10 --------------------
==33386== max-live:    4,456,312 in 17 blocks
==33386== tot-alloc:   4,456,312 in 17 blocks (avg size 262136.00)
==33386== deaths:      none (none of these blocks were freed)
==33386== acc-ratios:  0.00 rd, 0.00 wr  (8 b-read, 0 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4E9C67B: hashtable_init (hashtable.c:340)
==33386==    by 0x4ECE296: nfs_Init_client_id (nfs4_clientid.c:1795)
==33386==    by 0x4E806C1: nfs_Init (nfs_init.c:707)
==33386==    by 0x4E80F13: nfs_start (nfs_init.c:923)
==33386==    by 0x4029F8: main (nfs_main.c:522)
==33386== 
==33386== -------------------- 10 of 10 --------------------
==33386== max-live:    4,456,312 in 17 blocks
==33386== tot-alloc:   4,456,312 in 17 blocks (avg size 262136.00)
==33386== deaths:      none (none of these blocks were freed)
==33386== acc-ratios:  3.41 rd, 1.36 wr  (15,232,152 b-read, 6,092,944 b-written)
==33386==    at 0x4C27D65: calloc (vg_replace_malloc.c:711)
==33386==    by 0x4E9C67B: hashtable_init (hashtable.c:340)
==33386==    by 0x4ED5966: nfs4_Init_state_id (nfs4_state_id.c:444)
==33386==    by 0x4E807E5: nfs_Init (nfs_init.c:722)
==33386==    by 0x4E80F13: nfs_start (nfs_init.c:923)
==33386==    by 0x4029F8: main (nfs_main.c:522)
==33386== 
==33386== 
==33386== 
==33386== ==============================================================
==33386== 
==33386== Some hints: (see --help for command line option details):
==33386== 
==33386== * summary stats for whole program are at the top of this output
==33386== 
==33386== * --show-top-n=  controls how many alloc points are shown.
==33386==                  You probably want to set it much higher than
==33386==                  the default value (10)
==33386== 
==33386== * --sort-by=     specifies the sort key for output.
==33386==                  See --help for details.
==33386== 
==33386== * Each allocation stack, by default 12 frames, counts as
==33386==   a separate alloc point.  This causes the data to be spread out
==33386==   over far too many alloc points.  I strongly suggest using
==33386==   --num-callers=4 or some such, to reduce the spreading.
==33386== 
-------------------------

In valgrind dhat log, we can not find mem used as high level, the LRU ENTRY has been reaped,
But why does ps aux |grep ganesha shows the high level useage of MEM.
I also use massif to test this case, high mem is not showed in massif log.
This is troubing me, why the memory is beening high when ganesha is out of high pressure test.


If I have any grammatical mistakes, please forgive me. 
Thank you.

**Comment by ffilz** [comment]
It looks like you have some 380k files open with various cache entries associated with each...

I don't see anything alarming in there.

Note that we don't have any limit on the number of open files so those can cause the LRU to blow it's high water mark.

I assume you're using NFSv4? It doesn't look like you're having "stuck" LRU entries that could be freed but aren't (since open2 is in the call path for most of the entries).

**Comment by twoholes** [comment]
Note that we don't have any limit on the number of open files so those can cause the LRU to blow it's high water mark.
---->yeah,  I know that.
It doesn't look like you're having "stuck" LRU entries that could be freed but aren't (since open2 is in the call path for most of the entries).
---->Yes, I modify the LRU_N_Q_LANES form 17 to 199, and test once more, in the log, ganesha can always reap the entry while new creating.
        or try reap more entries of every lane in fun lru_reap_impl, that maybe can imporve the chance of reaping the existing entry in LRU.

**Comment by skmprabhu** [comment]
may be problem glibc allocations.  Please give a try with https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/547891

**Comment by ffilz** [comment]
Bump to keep on page 1

**Comment by ffilz** [comment]
Please try this patch set:

https://github.com/nfs-ganesha/nfs-ganesha/compare/next...ffilz:nfs-ganesha:ceph-async

**Comment by ffilz** [comment]
Please try V5-dev.4

**Comment by ffilz** [comment]
V5.0 has been released. Closing.
