### ISSUE TITLE
Issue with Ganesha V4.2.2 /Gluster 10.3, volume error

### ISSUE THREAD

**Issue by AlexNinaber** [nfs-ganesha/nfs-ganesha#895]
Error with Ganesha / Gluster:

ganesha-gfapi.log:
[2023-01-08 15:10:11.428152 +0000] W [MSGID: 104014] [glfs-mgmt.c:227:mgmt_submit_request] 0-gfapi: failed to create XDR payload [] 
[2023-01-08 15:10:11.428254 +0000] E [MSGID: 104021] [glfs-mgmt.c:939:mgmt_rpc_notify] 0-glfs-mgmt: failed to get the volume file [{key=images}, {errno=22}, {error=Invalid argument}] 
[2023-01-08 15:10:11.428347 +0000] I [socket.c:833:__socket_shutdown] 0-gfapi: intentional socket shutdown(9)
[2023-01-08 15:10:11.428409 +0000] I [MSGID: 104024] [glfs-mgmt.c:841:mgmt_rpc_notify] 0-glfs-mgmt: Failed to connect to remote-host [{server=10.141.255.253}] 
[2023-01-08 15:10:11.428451 +0000] I [MSGID: 104025] [glfs-mgmt.c:858:mgmt_rpc_notify] 0-glfs-mgmt: Exhausted all volfile servers [{errno=107}, {error=Transport endpoint is not connected}]

Config:
NFS_CORE_PARAM {
    # possible to mount with NFSv3 to NFSv4 Pseudo path
    mount_path_pseudo = true;
    # NFS protocol
    Protocols = 3,4;
    Rquota_Port = 875;
    Enable_RQUOTA = true;

}
EXPORT_DEFAULTS {
    # default access mode
    Access_Type = RW;
}
EXPORT {
    # uniq ID
    Export_Id = 101;
     nfs4_disable_idmapping=N;
    # mount path of Gluster Volume
    Path = "/trinity";
    FSAL {
    	# any name
        name = GLUSTER;
        # hostname or IP address of this Node
        hostname="10.141.255.253";
        # Gluster volume name
        volume="trinity";
    }
    # config for root Squash
    Squash="No_root_squash";
    # NFSv4 Pseudo path
    Pseudo="/trinity";
    # allowed security options
    SecType = "sys";
}

EXPORT {
    # uniq ID
    Export_Id = 102;
    # mount path of Gluster Volume
    Path = "/mnt/images";
    FSAL {
        # any name
        name = GLUSTER;
        # hostname or IP address of this Node
        hostname="10.141.255.253";
        # Gluster volume name
        volume="images";
    }
    # config for root Squash
    Squash="No_root_squash";
    # NFSv4 Pseudo path
    Pseudo="/images";
    # allowed security options
    SecType = "sys";
}

LOG {
    # default log level
    Default_Log_Level = WARN;
}

So the above used to work with RPM based precompiled Gluster 8.x and Ganesha 3.x, however support on Centos7 has stopped so it's a manual compile now for Gluster 10.3 + Ganesha 4.4.2 with GCC9, kernel 5.x in Centos7. Gluster is healthy:

gluster volume status images
Status of volume: images
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick 10.141.255.254:/gluster/images        52974     0          Y       2411 
Brick 10.141.255.253:/gluster/images        59009     0          Y       207285
Brick 10.141.11.1:/gluster/images           53924     0          Y       4786 
Self-heal Daemon on localhost               N/A       N/A        Y       207336
Self-heal Daemon on 10.141.11.1             N/A       N/A        Y       5388 
Self-heal Daemon on balin.cluster           N/A       N/A        Y       3138 
 
Task Status of Volume images
------------------------------------------------------------------------------
There are no active volume tasks

08/01/2023 16:10:11 : epoch 63badcd3 : master02.cluster : ganesha.nfsd-1603107[main] export_defaults_commit :CONFIG :INFO :Export Defaults now (options=033031e2/0
00001e0               , RWrw,    ,               ,               ,         ,                ,                ,                )
08/01/2023 16:10:11 : epoch 63badcd3 : master02.cluster : ganesha.nfsd-1603107[main] glusterfs_create_export :FSAL :EVENT :Volume images exported at : '/'
08/01/2023 16:10:11 : epoch 63badcd3 : master02.cluster : ganesha.nfsd-1603107[main] glusterfs_get_fs :FSAL :CRIT :Unable to initialize volume. Volume: images
08/01/2023 16:10:22 : epoch 63badcd3 : master02.cluster : ganesha.nfsd-1603107[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL GLUSTER
08/01/2023 16:10:22 : epoch 63badcd3 : master02.cluster : ganesha.nfsd-1603107[main] fsal_put :FSAL :INFO :FSAL GLUSTER now unused
08/01/2023 16:10:22 : epoch 63badcd3 : master02.cluster : ganesha.nfsd-1603107[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/images) to (/mnt/images)

Any ideas?

**Comment by dang** [comment]
It sounds like maybe something changed between gluster 8.x and 10.3 that affects Ganesha's ability to connect?  Since Red Hat stopped supporting Gluster a few years ago, no on on the Ganesha project has been working with Gluster, so it may have bit-rotted a bit.

If we really can't work with current Gluster, we may have to mark FSAL_GLUSTER unmaintained, unless someone can step up to maintain it.

**Comment by kalebskeithley** [comment]
gfapi hasn't changed, but if you want "supported" (which I guess means packages are built by someone else) you could use glusterfs-9.6 and ganesha-4.x on rhel7 using packages from the CentOS Storage SIG.   ganesha-4.3 should be released in the next couple of days.  In the mean time I suggest opening in issue  https://github.com/gluster/glusterfs/issues and/or engage on one of the gluster slack channels.

**Comment by ffilz** [comment]
Please try Ganesha V4.3 though as suggested, we have very limited resources to support Gluster issues.

**Comment by AlexNinaber** [comment]
I think it was something with the building/cleaning/rebuilding of Gluster, not entirely sure, later on it was working fine on another node - tried finding the exact difference but starting from scratch it's all working now (and stable with Gluster).
