### ISSUE TITLE
problem mount share without acl

### ISSUE THREAD

**Issue by ayrtoncapo** [nfs-ganesha/nfs-ganesha#897]
Given that the acls on ganesha should be disabled.
I can create only one share which is visible if I implement the acls (Add policy rule), however if I create a second share even on a different tenant and create the acls then the first share is unmounted by the clients.

I have this configuration on ganesha.conf:

NFS_Core_Param
{
}

EXPORT
{
        Export_id=20134;

        Path = "/";

        Pseudo = "/cephobject";

        Access_Type = RW;

        Protocols = 4;

        Transports = TCP;

        SecType = "sys,krb5,krb5i,krb5p";

        Squash = Root_Squash;

        FSAL {
                Name = RGW;
                User_Id = "cephnfs";
                Access_Key_Id ="xxxxxxxxx";
                Secret_Access_Key = "xxxxxxxxxx";
        }

}

RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        cluster = "ceph";
        name = "client.rgw.cephprod1-pod7";

}

LOG {
        Facility {
                name = FILE;
                destination = "/var/log/ganesha/ganesha.log";
                enable = active;
        }

}

And:

nfs-ganesha 2.7.3
ceph 14.2.22

From the tests I do it is as if the share is visible only if the acls are enabled for the network of clients who have to mount the share.
But if I create another share and implement the acls the first share is unmounted

**Comment by ffilz** [comment]
I'm a bit unclear, what ACLs?

Also, Ganesha V2.7.3 is rather old. We just released Ganesha V4.3 which is the current supported version.

**Comment by ayrtoncapo** [comment]
I haven't described the whole environment, since we have OpenStack, the ACLs I'm talking about we set in the part of the share created with Manila (Manila is the OpenStack Shared Filesystems service)

I did a test and if in the ganesha.conf instead of :

Pseudo = "/cephobject";

I put: 

Pseudo= /;

I am able to mount the shares without setting the ACLs to Manila.

The fact is the share that I mount on client is seen from / with the whole size of Ceph, and not the size of the share created.

**Comment by ffilz** [comment]
Can you try on Ganesha V4.4.1? It's possible there are changes that have improved this.

Also, are you using a reasonably current version of Ceph?

**Comment by ffilz** [comment]
This is over 30 days old with no response. Closing.
