### ISSUE TITLE
CIDR value 0.0.0.0./0 is badly supported

### ISSUE THREAD

**Issue by phdeniel** [nfs-ganesha/nfs-ganesha#9]
If CIDR value 0.0.0.0/0 is used to configure somme Access or Root_Access, result is weird. I had a few ESTALE when invoking NFS3_FSINFO.

**Comment by ffilz** [comment]
Is this a way of stating "all clients"? If so, it is better to use *.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
