### ISSUE TITLE
Feature Request: Android/Termux support

### ISSUE THREAD

**Issue by stevenxxiu** [nfs-ganesha/nfs-ganesha#900]
Would be amazing if this supported *Termux*.

To try and get an *NFS* server working, I tried the usual route of installing `nfs-utils` on *Termux*. But *Android* doesn't have *NFS* kernel modules by default. Building them seems to be quite tricky. I haven't succeeded so far.

I looked at alternatives and discovered *NFS-Ganesha*.

To try build it, I installed:

- `autoconf`
- `automake`
- `binutils`
- `bison`
- `bsdtar`
- `cmake`
- `flex`
- `gettext`
- `git`
- `libtool`
- `proot`

Some packages that aren't in *Termux* by default that I installed/built manually:

- [Maxython/glibc-for-termux: AUR builds and compiled glibc packages for termux.](https://github.com/Maxython/glibc-for-termux)
- `libnsl`
- `liburcu`

The build dies at:

```
/data/data/com.termux/files/home/packages/nfs-ganesha-git/src/nfs-ganesha-git/src/libntirpc/ntirpc/rpc/xdr.h:656:35: error: unknown type name 'quad_t'; did you mean 'uid_t'?
extern bool xdr_longlong_t(XDR *, quad_t *);
                                  ^~~~~~
                                  uid_t
```

**Comment by ffilz** [comment]
There are several sources for a definition of quad_t. I see a definition in /usr/include/sys/types.h which bases it on __quad_t in /usr/include/bits/type.h

It's supposed to be a 64 bit quantity, so if your system doesn't provide it somehow, you just need to define it yourself.

**Comment by ffilz** [comment]
p.s. we are a very small team and don't have the resources to support a variety of platforms, however, we welcome additional contributions, so if you get something working, please submit a patch to gerrithib (see src/CONTRIBUTING_HOWTO.txt.

**Comment by NoteAfterNote** [comment]
@ffilz and @stevenxxiu, see "Testing: Termux, proot-distro, Network File System (NFS)" at https://gist.github.com/NoteAfterNote/e1719f4029b91918d996216939d5bff2 for using an Android smartphone as an NFS server without rooting the Android smartphone.

**Comment by stevenxxiu** [comment]
@NoteAfterNote This is irrelevant. The whole point is to use *NFS* on rooted *Android*, so files preserve nanosecond timestamps and ownership information.

**Comment by ffilz** [comment]
Again, if someone wants to contribute something, please do so.
