### ISSUE TITLE
How does nfs-ganesha handle kerberos authentication？

### ISSUE THREAD

**Issue by bjfhdhhaha** [nfs-ganesha/nfs-ganesha#903]
I mounted an export (krb5) in NFS client 。Then I did the following operations on the NFS client：
#su - user1
#kinit
#touch file1

The above operations are all successful，But I did not find ganesha and kdc interactive authentication message through tcpdump,
How does nfs-ganesha server handle kerberos authentication？Does nfs-ganesha need to communicate with kdc?

ganesha.conf is as follows：
NFS_KRB5
{
       PrincipalName = nfs;
       KeytabPath = /etc/krb5.keytab;
       Active_krb5 = true;
}

EXPORT
{
	Export_Id = 1;
	Path = "/nfs1";
	Protocols = 3,4;
	Pseudo = "/nfs1";

	FSAL
	{
		Name = VFS;
	}
	CLIENT
	{
		Access_Type = RW;
		Clients = *;
		Protocols = 3,4;
		Squash = No_Root_Squash,None;
	}

        SecType = "krb5";
}

**Comment by ffilz** [comment]
See the explanation on this wiki page:

https://en.wikipedia.org/wiki/Kerberos_(protocol)

Ganesha doesn't need to communicate with the KDC.

**Comment by bjfhdhhaha** [comment]
@ffilz Thanks for your reply. I have another question to ask. I used the windows Active Directory domain server as the KDC server，Like the layout below：
- 1 Centos 7 NFS server
- 1 Centos 7 NFS Client
- 1 Windows 2012 AD （KDC）

I'm going to add a service principal name(nfs/node1. example. com) to ad kdc. 
On Windows ad, I can use "setspn - A nfs/ctest.eutest.com nfs-server" to add.
Is there any command to add a service principal to ad kdc on centos?

**Comment by ffilz** [comment]
I'm sorry, I don't know Active Directory.

**Comment by ffilz** [comment]
Closing for being inactive for more than 60 days.

Please re-open if you have more questions.
