### ISSUE TITLE
How to identify NFS client causing error messages

### ISSUE THREAD

**Issue by amartel** [nfs-ganesha/nfs-ganesha#905]
Hi,

Since a couple of days, ganesha generates a huge number of messages in my log (1 message every second):
```
20/02/2023 12:12:00 : epoch 63f32c18 : fouet : ganesha.nfsd-248344[svc_2090] nfs4_Errno_verbose :NFS4 :CRIT :Error File/directory not opened in file_To_Fattr converted to NFS4ERR_IO but was set non-retryable
20/02/2023 12:12:01 : epoch 63f32c18 : fouet : ganesha.nfsd-248344[svc_2078] nfs4_Errno_verbose :NFS4 :CRIT :Error File/directory not opened in file_To_Fattr converted to NFS4ERR_IO but was set non-retryable
20/02/2023 12:12:02 : epoch 63f32c18 : fouet : ganesha.nfsd-248344[svc_2084] nfs4_Errno_verbose :NFS4 :CRIT :Error File/directory not opened in file_To_Fattr converted to NFS4ERR_IO but was set non-retryable
20/02/2023 12:12:03 : epoch 63f32c18 : fouet : ganesha.nfsd-248344[svc_2090] nfs4_Errno_verbose :NFS4 :CRIT :Error File/directory not opened in file_To_Fattr converted to NFS4ERR_IO but was set non-retryable
20/02/2023 12:12:04 : epoch 63f32c18 : fouet : ganesha.nfsd-248344[svc_2068] nfs4_Errno_verbose :NFS4 :CRIT :Error File/directory not opened in file_To_Fattr converted to NFS4ERR_IO but was set non-retryable
```

I think that it may be caused by a specific client but I dont know how to identify it as I don't have any client IP address in the log.
Do you know a tool/command/procedure to use in this situation ?

**Comment by ffilz** [comment]
You can control the log format with something like this, one thing you can turn on is CLIENTIP as shown below:
```
LOG
{
	FORMAT
	{
		DATE_FORMAT = 8601;
		#DATE = "%c";
		#DATE = 8601;
		#TIME = LOCAL;
		EPOCH = FALSE;
		HOSTNAME = FALSE;
		PROGNAME = FALSE;
		FILE_NAME = TRUE;
		LINE_NUM = TRUE;
		PID = FALSE;
		CLIENTIP = TRUE;
	}
}
```
This is mostly the log format I use (I normally have CLIENTIP=FALSE;. EPOCH, HOSTNAME, PROGNAME, and PID are often useless (less so if you have multiple Ganesha instances). Adding FILE_NAME and LINE_NUM makes it easier to find where the log message is emitted from (and can help when a function uses the same log message in several places).

**Comment by amartel** [comment]
Thank's a lot !!
Turning on CLIENTIP did the trick and, then, I was to solve my problem..
