### ISSUE TITLE
Unable to mount a export using v4

### ISSUE THREAD

**Issue by LLVIC** [nfs-ganesha/nfs-ganesha#907]
Hi everyone, here is my problem.
When I tried to mount a export using v4, error occured "reason given by server: No such file or directory".  Meanwhile, when I changed to V3 mount, it succeed. 

The export conf is as follows:
EXPORT {
        SecType = sys;
        CLIENT {
                Clients = <ips>;
                Access_type = RW;
        }
        FSAL {
                Volname = Vol01;
                Volpath = /cnp;
                Hostname = localhost;
                Name = Gluster;
        }
        Transports = TCP,UDP;
        Path = /Vol01_cnp;
        Export_ID = 10;
        Pseudo = /Vol01_cnp;
        Squash = None;
        Protocols = 3,4;
}

The error in ganesha.log are:
21/02/2023 10:39:33 : epoch 639b416e :  : ganesha.nfsd-33267[svc_184] fs_rm_revoked_handles :CLIENT ID :EVENT :opendir /var/lib/nfs/ganesha/**v4reco**/<*****> failed errno: No such file or directory (2)
21/02/2023 10:39:33 : epoch 639b416e :  : ganesha.nfsd-33267[svc_184] fs_rm_clid_impl :CLIENT ID :EVENT :Failed to remove client recovery dir (/var/lib/nfs/ganesha/**v4reco**/<*****>, errno: No such file or directory (2)

However, by checking the code, the recovery path is **v4recov** instead of **v4reco**. 
I cannot figure out why this error occured. Besides, the version of nfs-ganesha is 3.4-2.

Looking forward to your answer, thank you!

**Comment by dang** [comment]
I'm not seeing anything jump out at me, and nothing in that code has changed for years.  The two interesting bits are the one-off in v4recov, and the clientid recovery tag of <>.  It shouldn't be anything like that, as it has structured contents.   Any ideas, Frank?

**Comment by ffilz** [comment]
There have been several fixes for the recovery directory path that are available in V4.3. I'm not quite sure where the <> is coming from, I've never seen that before.

Can you try on V4.3?

**Comment by LLVIC** [comment]
> I'm not seeing anything jump out at me, and nothing in that code has changed for years. The two interesting bits are the one-off in v4recov, and the clientid recovery tag of <>. It shouldn't be anything like that, as it has structured contents. Any ideas, Frank?

Sorry about the tag “<>”,  that was a mistake. The above logs do not exactly match the actual logs. 

21/02/2023 10:39:33 : epoch 639b416e : : ganesha.nfsd-33267[svc_184] fs_rm_revoked_handles :CLIENT ID :EVENT :opendir /var/lib/nfs/ganesha/v4reco/::ffff:192.168.1.3-(17:Linux NFSv4.1 ll1) failed errno: No such file or directory (2)
21/02/2023 10:39:33 : epoch 639b416e : : ganesha.nfsd-33267[svc_184] fs_rm_clid_impl :CLIENT ID :EVENT :Failed to remove client recovery dir (/var/lib/nfs/ganesha/v4reco/::ffff:192.168.1.3-(17:Linux NFSv4.1 ll1), errno: No such file or directory (2)

The key point is why it tried to find /var/lib/nfs/ganesha/v4reco instead of /var/lib/nfs/ganesha/v4recov ?  And I guess it was the reason that caused mounting failure when using v4.

**Comment by ffilz** [comment]
Yea, you definitely want Ganesha V4.4 (now the latest stable release). In branch V4-stable.

**Comment by ffilz** [comment]
This is over 30 days old without any response. Closing.
