### ISSUE TITLE
nfs_dupreq_rele :RW LOCK :CRIT :Error 22, acquiring mutex

### ISSUE THREAD

**Issue by datamattsson** [nfs-ganesha/nfs-ganesha#917]
We got ourselves in trouble running containerized NFS Ganesha built from the 4.0.9 tag (same problem is reported to occur 4.0.10 as well). It's running on top of XFS and the host OS is Ubuntu 16.04.

We're working on setting up an environment to create a reproducible scenario (the end user is simply `dd`'ing a 10GB file to trigger this), what are the recommended steps, flags, debug options etc we can enable to provide more detailed diagnostics?

```
18/03/2023 23:03:34 : epoch 64164342 : my-nfs-server-1 : ganesha.nfsd-1[svc_14 nfs_dupreq_rele :RW LOCK :CRIT :Error 22, acquiring mutex 0x7f6254002610 (&dv->mtx) at /builddir/build/BUILD/nfs-ganesha-4.0/src/RPCAL/nfs_dupreq.c:1434
stream closed
```

**Comment by ffilz** [comment]
Definitely need more information on this.

**Comment by datamattsson** [comment]
It seem I had inaccurate data from the user. Upgrading to 4.0.10 resolved the problem.
