### ISSUE TITLE
v4.3, setfacl return Permission denied

### ISSUE THREAD

**Issue by fengyueqiao** [nfs-ganesha/nfs-ganesha#918]
Ganesha v4.0 setfacl is ok, after updaed to v4.3, setfacl return Permission denied
The error log is as follow:
` ganesha.nfsd-259732[svc_9] nfs_rpc_process_request :DISP :INFO :SVCAUTH_CHECKSUM failed for Program 100227, Version 3, Function 2, xid=509102946, SVCXPRT=0xfffba8006b60, fd=127
 ganesha.nfsd-259732[svc_9] nfs_rpc_process_request :DISP :CRIT :nfs_rpc_process_request FAILURE: Bad xdr_free for NFSACL_SETACL`

After diff the change of v4.0 to v4.3, I found the commit /c2d2aafb44be6528bbe0cecc38ed66d15cad15dd change the function xdr_posix_acl(). That add check condition as follow:
`	if (objp->count <= 0 || objp->count > 4096)
		return FALSE;`
For file setfacl，the default acl is count is 0, so decode return false.
I change check condition as follow:
`	if (objp->count < 0 || objp->count > 4096)
		return FALSE;`
The setfacl return ok.

**Comment by dang** [comment]
Seems reasonable.

**Comment by ffilz** [comment]
Yea, that commit made a bad change. Also, all the checks changed or added were for unsigned int so < 0 is impossible and no need to check for. And you're right, the count of acl entries can be zero.

Patch submitted: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/552324

**Comment by ffilz** [comment]
V5.0 has been released. Closing.
