### ISSUE TITLE
Make NFS_V4_RECOV_ROOT configurable

### ISSUE THREAD

**Issue by ralt** [nfs-ganesha/nfs-ganesha#92]
This variable: https://github.com/nfs-ganesha/nfs-ganesha/blob/master/src/include/config-h.in.cmake#L63

This may be a read-only filesystem at runtime. This should be configurable by the command-line options, like `GANESHA_PIDFILE_PATH` etc are.

**Comment by dang** [comment]
LSB requires /var (which is SYSSTATEDIR, by default) to be writable.  A read-only /var will break everything.  I don't necessarily have a problem with making this configurable, but I don't think this is a good reason to do it. 

PIDFILE is configurable in case your init system looks for PIDs somewhere else, for example.

**Comment by ralt** [comment]
I guess machines using non-LSB should just recompile?

**Comment by dang** [comment]
I'm confused.  If your distro is LSB compliant, you don't need to do anything.  If your distro is not, then  you (or your distro) need to handle that separately.  We don't currently support non-LSB compliant distros, and I believe other work than this will need to be done.

What distro are you running?  Can you hop on #ganesha on freenode to chat this out?

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
