### ISSUE TITLE
PROXY_V4: HandleMap_Init is called from create_export - can't support multiple PROXY exports

### ISSUE THREAD

**Issue by ffilz** [nfs-ganesha/nfs-ganesha#921]
I'm not sure how much intent there is to support multiple PROXY exports, but it definitely can't work right now.

**Comment by boulos** [comment]
Just `PROXY_V4`, *right*?

**Comment by ffilz** [comment]
> Just `PROXY_V4`, *right*?

Yea, just PROXY_V4. PRPXY_V3 doesn't have handle map. In theory it could need it if re-exporting from a server that had a handle longer than 59 bytes.

Hmm, this is also sort of a duplicate of issue #920

**Comment by ffilz** [comment]
Closing as duplicate
