### ISSUE TITLE
Error compiling next on Raspberry PI 4 arm8

### ISSUE THREAD

**Issue by mirino75** [nfs-ganesha/nfs-ganesha#924]
Getting the following error after a make on Ubuntu server 22.04.02 LTS 64b

[ 21%] Building C object SAL/CMakeFiles/sal.dir/state_lock.c.o
In file included from /home/ubuntu/git/nfs-ganesha/src/include/gsh_rpc.h:58,
                 from /home/ubuntu/git/nfs-ganesha/src/include/uid2grp.h:46,
                 from /home/ubuntu/git/nfs-ganesha/src/include/fsal_types.h:43,
                 from /home/ubuntu/git/nfs-ganesha/src/include/fsal_api.h:45,
                 from /home/ubuntu/git/nfs-ganesha/src/include/fsal.h:63,
                 from /home/ubuntu/git/nfs-ganesha/src/SAL/state_lock.c:47:
/home/ubuntu/git/nfs-ganesha/src/SAL/state_lock.c: In function ‘state_cleanup’:
/home/ubuntu/git/nfs-ganesha/src/SAL/state_lock.c:3647:32: error: ‘all_locks_mutex’ undeclared (first use in this function); did you mean ‘blocked_locks_mutex’?
 3647 |         PTHREAD_MUTEX_destroy(&all_locks_mutex);
      |                                ^~~~~~~~~~~~~~~
/home/ubuntu/git/nfs-ganesha/src/include/common_utils.h:626:44: note: in definition of macro ‘PTHREAD_MUTEX_destroy’
  626 |                 rc = pthread_mutex_destroy(_mtx);                       \
      |                                            ^~~~
/home/ubuntu/git/nfs-ganesha/src/SAL/state_lock.c:3647:32: note: each undeclared identifier is reported only once for each function it appears in
 3647 |         PTHREAD_MUTEX_destroy(&all_locks_mutex);
      |                                ^~~~~~~~~~~~~~~
/home/ubuntu/git/nfs-ganesha/src/include/common_utils.h:626:44: note: in definition of macro ‘PTHREAD_MUTEX_destroy’
  626 |                 rc = pthread_mutex_destroy(_mtx);                       \
      |                                            ^~~~
/home/ubuntu/git/nfs-ganesha/src/SAL/state_lock.c: In function ‘state_lock_init’:
/home/ubuntu/git/nfs-ganesha/src/SAL/state_lock.c:3683:29: error: ‘all_locks_mutex’ undeclared (first use in this function); did you mean ‘blocked_locks_mutex’?
 3683 |         PTHREAD_MUTEX_init(&all_locks_mutex, NULL);
      |                             ^~~~~~~~~~~~~~~
/home/ubuntu/git/nfs-ganesha/src/include/common_utils.h:600:41: note: in definition of macro ‘PTHREAD_MUTEX_init’
  600 |                 rc = pthread_mutex_init(_mtx, attr);                    \
      |                                         ^~~~
make[2]: *** [SAL/CMakeFiles/sal.dir/build.make:90: SAL/CMakeFiles/sal.dir/state_lock.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1276: SAL/CMakeFiles/sal.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by dang** [comment]
Can you update?  Changes have been made in this area recently, and it works (as long as SAL debug is enabled, but there's a fix for that)

**Comment by mirino75** [comment]
I downloaded the current git package but still the same error

**Comment by ffilz** [comment]
Patch submitted, not merged or packaged yet.

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/552393

**Comment by mirino75** [comment]
I downloaded the patch and 'make' continues. Thank yo for you help, Frank.
Mirino
