### ISSUE TITLE
Question about check cid_reclaim_complete when create new file 

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#926]
@ffilz hi, sorry for my question.  I encounter a very corner case, in this case, client can not create new file.

The steps to reproduce this case:
1. client open a existed file_1.
2. client and ganesha's network broken for Lease_Lifetime.
3. client reconnect to ganesha after Lease_Lifetime, and ganesha has not reaper session. ganesha respond NFS4ERR_EXPIRED
4. ganesha reaper session_1 and clientid_1. then client get NFS4ERR_BADSESSION.
5. client create new session_2 and new clientid_2, with `cid_reclaim_complete` is false
6. client create new file_2, but hang forever, because ganesha always respond NFS4ERR_GRACE at [nfs4_op_open.c:134](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_open.c#L134) for `cid_reclaim_complete` is always false , and client will always not send RECLAIM_COMPLETE

The reason of client will always not send RECLAIM_COMPLETE:
1. `set_bit(NFS4CLNT_RECLAIM_NOGRACE, &clp->cl_state)`:

ganesha respond NFS4ERR_EXPIRED in above step3, nfs-client kernel's stack: [nfs4_recovery_handle_error](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1986) -> [nfs4_state_start_reclaim_nograce](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1887) -> [nfs4_state_mark_reclaim_helper](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1867) -> [nfs4_reset_seqids](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1786) -> [mark_reclaim(clp, state)](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1771) -> [nfs4_state_mark_reclaim_nograce](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1384) -> [set_bit(NFS4CLNT_RECLAIM_NOGRACE, &clp->cl_state)](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1391)

  `mark_reclaim` is function pointer of `nfs4_state_mark_reclaim_nograce`, which assign at [nfs4_state_mark_reclaim_helper(clp, nfs4_state_mark_reclaim_nograce)](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1867).  

2. linux will not [set_bit(NFS4CLNT_RECLAIM_REBOOT, &clp->cl_state)](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L2076) when `set_bit(NFS4CLNT_RECLAIM_NOGRACE, &clp->cl_state)`, 

3. nfs-client reclaim open state of file_1 in above step5: [nfs4_do_reclaim](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L2690). 

4. nfs-client will not call reclaim complete in the following step: [nfs4_state_end_reclaim_reboot](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L2676) ->  [nfs4_reclaim_complete](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4state.c#L1858), because linux didn't set bit of NFS4CLNT_RECLAIM_REBOOT

I think maybe we should reaper session as soon as possible, so that above step3 will respond NFS4ERR_BADSESSION instead of NFS4ERR_EXPIRED. Then we can avoid this case.

**Comment by ffilz** [comment]
Try V5-dev.5

This patch I think addresses the issue: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/551789

**Comment by ffilz** [comment]
This is also similar to https://github.com/nfs-ganesha/nfs-ganesha/issues/910 which is what prompted the patch.

**Comment by liyinshubyte** [comment]
@ffilz Thanks the reply, the case is similar, but not same. #910 is nfs-client receive expired but still use old clientid. our problem is nfs-client receive expired and use new clientid, but because nfs-client has existed open file, nfs-client will clear bit of NFS_STATE_RECLAIM_REBOOT, then nfs-client will not send reclaim complete to ganesha. So ganesha new clientid's cid_reclaim_complete is always false, and nfs-client can not create new file.

**Comment by ffilz** [comment]
Yes, the scenarios are different, but when we send the NFS4ERR_EXPIRED we are also expiring all the state so it won't be there later.

**Comment by liyinshubyte** [comment]
@ffilz Yes, the old state was deleted, but the new state has problem, because the new state's `cid_reclaim_complete` is always false.

**Comment by liyinshubyte** [comment]
@ffilz actually, we only use ganesha on linux, because linux didn't care about open state,  we want to open file directly no matter whether in grace on linux, can we do this as a quick fix for ourselves?
![image](https://user-images.githubusercontent.com/92144382/232663057-10347510-43cc-410d-a0aa-b65f2f4132c8.png)

**Comment by jtlayton** [comment]
A v4.1+ client _must_ always send a RECLAIM_COMPLETE after doing its reclaim. If that isn't happening then it's a client-side bug. I don't know what client you are using, but you may be interested in this post from Trond:

https://lore.kernel.org/linux-nfs/20230321041736.664907-1-trondmy@kernel.org/

**Comment by ffilz** [comment]
Jeff pointed out that he also thinks he saw some recent patches about missing RECLAIM_COMPLETE.

**Comment by liyinshubyte** [comment]
@ffilz @jtlayton thanks the reply, but we can not fix the client, so we must avoid the case in ganesha, we want to open file directly no matter whether in grace on linux, is it feasible ？

**Comment by ffilz** [comment]
I'm not going to put a hack into Ganesha for a broken client. Especially if there are client fixes out there.

**Comment by liyinshubyte** [comment]
@ffilz yes, we did not try to put a hack in community ganesha. we just put the hack into our inner ganesha to avoid the bug.

**Comment by ffilz** [comment]
Yea, if you want to fix out of tree and it works for you, that's great.

**Comment by liyinshubyte** [comment]
@ffilz @jtlayton hi, this patch is very new, is updated at 21 Mar 2023, I think all current kernel version has this risk, once nfs-client enter state of NFS4CLNT_RECLAIM_NOGRACE, it will not send RECLAIM_COMPLETE.

https://lore.kernel.org/linux-nfs/20230321041736.664907-1-trondmy@kernel.org/ .

**Comment by jtlayton** [comment]
> @ffilz @jtlayton thanks the reply, but we can not fix the client, so we must avoid the case in ganesha, we want to open file directly no matter whether in grace on linux, is it feasible ？

No. Trying to fix this in the server is just wrong. The only fix here is to the client -- full stop. You are of course welcome to hack your own server any way you like, but NAK on putting that patch into mainline ganesha.
