### ISSUE TITLE
Return value of consume_ev_sig_nb() not handled ?

### ISSUE THREAD

**Issue by arunkumarsit** [nfs-ganesha/nfs-ganesha#93]
Hi,

In svc_rqst.c file, A socket pair is created per event channel (for UDP, TCP etc.)
But I can't really find out what is the use of this socket pair.

A new event signaled ( via **ev_sig()** function) whenever there are events for the socket epoll via **epoll_ctl()**  call. **ev_sig()** just writes the data into the socket pair (writer end).
On the other end, **consume_ev_sig_nb()** triggered whenever there are events in the socket pair's receiver end.
But the caller don't process returned value from consume_ev_sig_nb() call, It simply ignores it.

*\* (void)consume_ev_sig_nb(sr_rec->sv[1]);

So my question is what is the need for this socket pair in svc_rqst.c file, when the event/signal consumer is not doing any operation based on the event.

**Comment by arunkumarsit** [comment]
Can anyone clarify my doubt please ?

**Comment by soumyakoduri** [comment]
Hi,
Could you please send your query to NFS-Ganesha devel mailing list - "nfs-ganesha-devel@lists.sourceforge.net" ?

Thanks,
Soumya

**Comment by arunkumarsit** [comment]
Thanks Soumya ! Posted there.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
