### ISSUE TITLE
Got ERROR "Could not dlopen module: /usr/lib64/ganesha/libfsalgluster.so" while using the compiled binary

### ISSUE THREAD

**Issue by feikiss** [nfs-ganesha/nfs-ganesha#932]
Steps to reproduce:
1. git clone --recursive  https://github.com/nfs-ganesha/nfs-ganesha.git
2. checkout V3-stable branch
3.  create and enter build dir
4. cmake -DUSE_FSAL_GLUSTER=ON -DCURSES_LIBRARY=/usr/lib64 -DCURSES_INCLUDE_PATH=/usr/include/ncurses -DCMAKE_BUILD_TYPE=Maintainer -DALLOCATOR=libc /root/git/nfs-ganesha-v3stable/src/
5. make; make install

After install successfully,  I execute following command:
ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /etc/ganesha/ganesha.conf -N DEBUG

Got error " load_fsal :NFS STARTUP :FATAL :Could not dlopen module: /usr/lib64/ganesha/libfsalgluster.so Error: /usr/lib64/ganesha/libfsalgluster.so: cannot open shared object file: No such file or directory". 

Glusterfs Version in the compile env:
glusterfs 7.0

**My question is : how to fix/avoid this error so that the nfs-ganesha can run with glusterfs?**

details in ganesha.log:
`25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5748[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version V3.5-0-gff0401165, built at Apr 25 2023 19:27:31 on localhost.localdomain
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :FileSystem info for FSAL PSEUDO {
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  maxfilesize  = 200
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  maxlink  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  maxnamelen  = 255
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  maxpathlen  = 4096
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  no_trunc  = 1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  chown_restricted  = 1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  case_insensitive  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  case_preserving  = 1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  link_support  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  symlink_support  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  lock_support  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  lock_support_async_block  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  named_attr  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  unique_handles  = 1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  acl_support  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  cansettime  = 1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  homogenous  = 1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  supported_attrs  = 11DFCE
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  maxread  = 67108864
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  maxwrite  = 67108864
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  umask  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  auth_exportpath_xdev  = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  delegations = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  pnfs_mds = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  pnfs_ds = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  fsal_trace = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  fsal_grace = 0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :  expire_time_parent = -1
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] display_fsinfo :FSAL :DEBUG :}
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_config :FSAL :DEBUG :FSAL INIT: Supported attributes mask = 0x11dfce
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_fds_limit :INODE LRU :INFO :Attempting to increase soft limit from 1024 to hard limit of 524288
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_fds_limit :INODE LRU :INFO :Setting the system-imposed limit on FDs to 524288.
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_server_pkgs :NFS STARTUP :INFO :State lock layer successfully initialized
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_server_pkgs :NFS STARTUP :DEBUG :Now building IP/name cache
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_server_pkgs :NFS STARTUP :INFO :IP/name cache successfully initialized
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] nfs4_recovery_init :CLIENT ID :INFO :Recovery Backend Init for fs
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] fs_create_recov_dir :CLIENT ID :DEBUG :v4_recov_dir=/var/lib/nfs/ganesha/v4recov
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] fs_create_recov_dir :CLIENT ID :DEBUG :v4_old_dir=/var/lib/nfs/ganesha/v4old
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] fs_create_recov_dir :CLIENT ID :DEBUG :v4_recov_dir=/var/lib/nfs/ganesha/v4recov/node0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] fs_create_recov_dir :CLIENT ID :DEBUG :v4_old_dir=/var/lib/nfs/ganesha/v4old/node0
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] nfs4_recovery_load_clids :STATE :DEBUG :Load recovery cli (nil)
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] export_defaults_commit :CONFIG :INFO :Export Defaults now (options=033031e2/000001e0               , RWrw,    ,               ,               ,         ,                ,                ,                )
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] load_fsal :NFS STARTUP :DEBUG :Loading FSAL GLUSTER with /usr/lib64/ganesha/libfsalgluster.so
25/04/2023 20:05:18 : epoch 6447c1fe : localhost.localdomain : nfs-ganesha-5749[main] load_fsal :NFS STARTUP :FATAL :Could not dlopen module: /usr/lib64/ganesha/libfsalgluster.so Error: /usr/lib64/ganesha/libfsalgluster.so: cannot open shared object file: No such file or directory. You might want to install the nfs-ganesha-GLUSTER package`

**Comment by dang** [comment]
The first thing to check is whether or not gluster libraries were actually found.  This will be in the cmake output at the end where it lists all used settings, and it should look like this:

USE_FSAL_GLUSTER = ON

If it's on, it should have been built and installed into /usr/lib64/ganesha, but maybe something messed up and it's installed into /usr/lib/ganesha?  It's worth checking that.   You didn't change the prefix, so it should be installed in /usr, and it complained that libfsalgluster.so wasn't found, rather than a symbol load error, so it sounds like something broke in the install step.

**Comment by feikiss** [comment]
Hi @dang ,  thanks for the reply.
Attach the cmake logs:
-- checking for module 'glusterfs-api>=7.0'
--   found glusterfs-api, version 7.0.8
-- GFAPI_INCLUDE_DIRS=
-- GFAPI_LIBRARY_DIRS=
-- GFAPI_LIBDIR=/usr/lib64
-- checking for module 'glusterfs-api>=7.0'
--   found glusterfs-api, version 7.0.8
-- Looking for include files unistd.h, sys/xattr.h
-- Looking for include files unistd.h, sys/xattr.h - found
-- Looking for include file acl/libacl.h
-- Looking for include file acl/libacl.h - found
-- Looking for glfs_xreaddirplus_r in gfapi
-- Looking for glfs_xreaddirplus_r in gfapi - not found
-- Could not find glfs_xreaddirplus, switching to glfs_readdir_r
-- Looking for glfs_fd_set_lkowner in gfapi
-- Looking for glfs_fd_set_lkowner in gfapi - not found
-- lkowner support is needed to enable GLUSTER build
-- Looking for glfs_upcall_register in gfapi
-- Looking for glfs_upcall_register in gfapi - not found
-- Could not find glfs_upcall_register, switching to glfs_h_poll_upcall
-- Looking for glfs_upcall_lease_get_object in gfapi
-- Looking for glfs_upcall_lease_get_object in gfapi - not found
-- **Could not find glfs_upcall_lease_get_object, switching off delegations**

.....
-- USE_FSAL_RGW = OFF
-- USE_FSAL_XFS = OFF
-- USE_FSAL_PANFS = OFF
-- USE_FSAL_GPFS = ON
-- **USE_FSAL_GLUSTER = OFF**
.....

 The glusterfs has been installed in the compile env, but it seems the check for glusterfs is failed.
For now I have no any idea for fixing it ：(

**Comment by dang** [comment]
The issue is glfs_fd_set_lkowner, which is required.  If it can't be found, then gluster support is disabled.  According to google, this was added in gluster 3.12.3, do you have at least that version?

**Comment by feikiss** [comment]
The compile env is fixed finally and binary file is working well!

 Thanks so much!
