### ISSUE TITLE
'mount_path_pseudo' not working on boot until service restarted

### ISSUE THREAD

**Issue by rlaunch** [nfs-ganesha/nfs-ganesha#939]
We've found that the `mount_path_pseudo` option is not loaded correctly when the nfs-ganesha service starts up on system boot. Restarting the service fixes the issue. We have seen this on all four of the hosts in the cluster.

We found this issue because NFS mounts were failing and the logs were filled with messages similar to:
```05/05/2023 10:10:15 : epoch 643a8590 : my-share : ganesha.nfsd-2889[svc_21] mnt_Mnt :NFS3 :INFO :MOUNT: Export entry / d
s not support NFS v3 for client ::1
```

Our configuration is:
```
NFS_CORE_PARAM
{
        mount_path_pseudo = true;
        Protocols = 3,4;
}

LOG {
    ## Default log level for all components
    Default_Log_Level = INFO;

    ## Configure per-component log levels.
    Components {
        FSAL = WARN;
        NFS4 = EVENT;
    }

    ## Where to log
    Facility {
        name = FILE;
        destination = "/var/log/ganesha.log";
        enable = active;
    }
}

export {
  export_id = 1;
  path = /my-share;
  pseudo = /my-share;
  access_type = RW;

  FSAL {
    name = GLUSTER;
    hostname = "localhost";
    volume = "mcv01";
    volpath = "/data/";
  }
}
```

I saw issue #647 however this doesn't quite fit our issue as the configuration has not been modified for months and the host has been rebooted.

**Comment by ffilz** [comment]
Can you share the log from startup of ganesha on boot, and then a restart of Ganesha?

The issue may be arising because the Gluster volumes are not available when Ganesha starts up on boot. Check the startup order of things and make sure Gluster is actually up and running before Ganesha starts.

**Comment by rlaunch** [comment]
Hi @ffilz ,
Thanks for the quick response. I'm just replicating the issue in our dev environment and will get you those logs. At the moment there are no startup dependencies on the NFS service, so I will have a play and see if that prevents the issue from occurring.

Best,
Ryan

**Comment by rlaunch** [comment]
It seems that the issue was indeed caused by Gluster not being ready when nfs-ganesha started. After re-producing the issue on our dev system I can see the following log entries:
```
15/05/2023 10:47:39 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] glusterfs_get_fs :FSAL :CRIT :Unable to initialize volume. Volume: mcv01
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL GLUSTER
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/test01) to (/test01)
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] build_default_root :CONFIG :INFO :Export 0 (/) successfully created
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] main :NFS STARTUP :WARN :No export entries found in configuration file !!!
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:64): 1 validation errors in block FSAL
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:64): Errors processing block (FSAL)
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:58): 1 validation errors in block EXPORT
15/05/2023 10:47:41 : epoch 64620dc7 : dev_nas02 : ganesha.nfsd-13095[main] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:58): Errors processing block (EXPORT)

```
I'm not sure why NFSv4 clients were still able to connect on the production system after this occurred, however, I can't replicate this now. 
We've modified our boot-up sequence to ensure that the service is not started before Gluster is ready.

Many thanks,
Ryan

**Comment by ffilz** [comment]
The clients were still able to connect because Ganesha continues to start even if one or more exports fail. In Ganesha V5.0 there is a -x command line option that will cause Ganesha to abort startup if any error including export errors occurs. So in the case of an exported Gluster filesystem that isn't up yet, Ganesha would fail to start.

**Comment by rlaunch** [comment]
Much appreciated @ffilz
