### ISSUE TITLE
Client id expiration - multiple clients write same server

### ISSUE THREAD

**Issue by free11kaka22** [nfs-ganesha/nfs-ganesha#940]
the situation is similar with issue #934. the deadlock is fixed by https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/553234。the crashs also exists。I find a little issue, but not sure whether it cause the crash。It's about 'get_state_owner' in 'create_nfs4_owner'. if not find a exist open owner,this interface will calloc a new owner, new owner has serveral steps:
1、malloc owner memory, copy key info to the new owner (so_refcount is 1), 
2、call 'init_owner(init_nfs4_owner)' add the owner to client open owner list, 
3、set the new owner 'so_refcount' to 1。
4、add owner to hash table。
if  after step 2, 'nfs_client_id_expire' called by other thread, it gets owner from the open owner list, and then call 'hold_state_owner' inc the 'so_refcount' to 2, then ‘'get_state_owner’ thread step 3 excute, it sets 'so_refcount' to 1, it leads 'so_refcount' incorrect。the nfs_client_id_expire may free the owner。
 we use ganesha 4.4,and nfs4.1。
the crash log is:
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_23] hold_state_owner :STATE :MAJ : Held owner {STATE_OPEN_OWNER_NFSV4 0x615000455e00: clientid={0x61a0147fa280 ClientID={Epoch=0x6454bed6 Counter=0x00036826} EXPIRED Client={0x60c000010780 name=(35:Linux NFSv4.1 localhost.localdomain) refcount=223270} t_delta=0 reservations=5 refcount=6} owner=(24:0xbebebebebebebebebebebebebebebebebebebebebebebebe) confirmed=1 seqid=0 refcount=2}
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_23] dec_state_owner_ref :STATE :MAJ : Decrement Refcont {STATE_OPEN_OWNER_NFSV4 0x615000455e00: clientid={0x61a0147fa280 ClientID={Epoch=0x6454bed6 Counter=0x00036826} EXPIRED Client={0x60c000010780 name=(35:Linux NFSv4.1 localhost.localdomain) refcount=223270} t_delta=0 reservations=4 refcount=6} owner=(24:0x6f70656e2069643a0000002d0000000000001c07bd180ba2) confirmed=1 seqid=0 refcount=1}.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_23] free_state_owner :STATE :MAJ : Free state owner {STATE_OPEN_OWNER_NFSV4 0x615000455e00: clientid={0x61a0147fa280 ClientID={Epoch=0x6454bed6 Counter=0x00036826} EXPIRED Client={0x60c000010780 name=(35:Linux NFSv4.1 localhost.localdomain) refcount=223270} t_delta=0 reservations=3 refcount=6} owner=(24:0x6f70656e2069643a0000002d0000000000001c07bd180ba2) confirmed=1 seqid=0 refcount=0}.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] get_state_owner :STATE :MAJ : New Owner {STATE_OPEN_OWNER_NFSV4 0x615000455e00: clientid={0x61a0147fa280 ClientID={Epoch=0x6454bed6 Counter=0x00036826} EXPIRED Client={0x60c000010780 name=(35:Linux NFSv4.1 localhost.localdomain) refcount=223270} t_delta=0 reservations=3 refcount=6} owner=(24:0x6f70656e2069643a0000002d0000000000001c07bd180ba2) confirmed=1 seqid=0 refcount=0}.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_130] get_state_owner :STATE :MAJ : New Owner {STATE_OPEN_OWNER_NFSV4 0x61500026e880: clientid={0x61a0142fe080 ClientID={Epoch=0x6454bed6 Counter=0x00036827} CONFIRMED Client={0x60c000010780 name=(35:Linux NFSv4.1 localhost.localdomain) refcount=223269} t_delta=0 reservations=9 refcount=4} owner=(24:0x6f70656e2069643a000000290000000000001be6757cab5a) confirmed=1 seqid=0 refcount=1}.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_120] eyas_wire_to_host :FSAL :EVENT :wire_to_host,export id:4,inode:1
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] eyas_open2_by_name :FSAL :EVENT :Open by name, name:708772/400k.jpg.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] _eyas_alloc_handle :FSAL :EVENT :alloc handle over! id:708784, name:400k.jpg hdl:0x613002cb8d80.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] eyas_setattr2 :FSAL :EVENT :Setattr obj:400k.jpg set mask:36864
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] eyas_handle_to_key :FSAL :EVENT :handle 708784 name 400k.jpg.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] eyas_close :FSAL :EVENT :close file 1k.jpg
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] fsal_close :FSAL :CRIT :open_fd_count is negative: -247231
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] eyas_handle_to_key :FSAL :EVENT :handle 708784 name 400k.jpg.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] eyas_handle_to_key :FSAL :EVENT :handle 708784 name 400k.jpg.
05/05/2023 17:06:40 : epoch 6454bed6 : node56 : ganesha.nfsd-13333[svc_197] _state_add_impl :RW LOCK :CRIT :Error 22, acquiring mutex 0x615000455e18 (&owner_input->so_mutex) at /home/code/NFS_GIT/st-develop/common/nfs/src/nfs_ganesha/nfs-ganesha-4.4/src/SAL/nfs4_state.c:221

**Comment by ffilz** [comment]
Ah, good catch. I think if we make sure the key always has the refcount set to 1, so the refcount is 1 as soon as the owner is visible outside the thread creating it, and then we remove that explicit set after init_owner that should take care of the problem.

I need to think if there are any other implications of that race (like somehow something escapes cleanup on expire).

**Comment by free11kaka22** [comment]
Thanks for your replay. Crash happened serveral times in our device when client id expires. I ran ganesha with asan, asan outputs some error info, all is that open owner had been freed, but the open or wirte operation still holds it. I haven't found any other problems except for this. After fixed this issue,the crash doesn't appear util now.

**Comment by deepakaru** [comment]
@free11kaka22 we were hitting the same issue. This patch should fix the issue
https://gerrithub.io/c/ffilz/nfs-ganesha/+/553739

**Comment by free11kaka22** [comment]
@deepakaru Thanks, I done it , and ganesha works well.

**Comment by ffilz** [comment]
Closing as verified.
