### ISSUE TITLE
Some user's can't access Ganesha NFS  export when manage_gids=true

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#946]
Hi All,

Some user's can't access Ganesha NFS  export when manage_gids=true
Here Auth flavor is sys.
When manage_gids=true and if there is record for the UID on the ganesha server, then getpwuid_r() is failing with "No matching password record found for uid" and error is returned to nfs client.

if ((op_ctx->cred_flags & **MANAGED_GIDS**) != 0) {
        /* Fetch the group data if required */
        if (op_ctx->caller_gdata == NULL &&
            !uid2grp(op_ctx->original_creds.caller_uid,
                 &op_ctx->caller_gdata)) {
            /** [@todo](https://jazz07.rchland.ibm.com:21443/jazz/users/todo): do we really want to bail here? */
            LogInfo(COMPONENT_DISPATCH,
                "Attempt to fetch managed_gids failed");
            return NFS4ERR_ACCESS;
        }

        op_ctx->creds.caller_glen = op_ctx->caller_gdata->nbgroups;
        op_ctx->creds.caller_garray = op_ctx->caller_gdata->groups;
    }
--------------------------------------------------------------------------
retval = **getpwuid_r**(uid, &p, buff, buff_size, &pp);
    if (retval != 0) {
        LogEvent(COMPONENT_IDMAPPER,
             "getpwuid_r for uid %u failed, error %d", uid, retval);
        return gdata;
    }
    if (pp == NULL) {
        LogInfo(COMPONENT_IDMAPPER,
            "No matching password record found for uid %u", uid);
        return gdata;
    }

However, some customers expecting this user should be treated as anonymous user and proceed further.

Please suggest, how to proceed in this case like should we stick to group info from rpc request or treat this user as anonymous?
In case of krb, if prinicipal to uid is failed, anonymous uid is assigned to user.

**Comment by ffilz** [comment]
Some thoughts as I look at this a bit more...

Hmm... there's a todo after the call to uid2grp asking if bailing is the right thing...

When we call uid2grp, we are outside the switch statement that selects between AUTH_SYS and AUTH_GSS, but we could still get that information.

My thought is that if we have AUTH_SYS then we use the group information from the received credentials. If we have AUTH_GSS then we use the anonymous gid and an empty group list.

**Comment by ffilz** [comment]
See patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/556391

**Comment by ffilz** [comment]
Patch is merged.
