### ISSUE TITLE
[question]how to static compile the nfs-ganesha project

### ISSUE THREAD

**Issue by feikiss** [nfs-ganesha/nfs-ganesha#947]
I'd like to compile the project using static compile way, so that I can make one standalone binary to run in different platform,such as centOS, ubuntu, Rocky. My question is : is this way possible to make a standalne executable binary file ?  Thanks.

**Comment by dang** [comment]
Currently, no.  Ganesha makes extensive use of libraries.  For example ganesha itself is a library, dynamically linked into a tiny executable.  In addition, it uses run-time loadable modules for FSALs.  A fair amount of work would be necessary to make it statically compiled, I think.

**Comment by ffilz** [comment]
Note also that static linking would have licensing implications.

Just for reference, here are the libraries my ganesha,.nfsd utilizes:

[root@fedora src]# ldd `which ganesha.nfsd`
	linux-vdso.so.1 (0x00007ffd6ff9c000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f666100b000)
	libganesha_nfsd.so.5.1 => /lib64/libganesha_nfsd.so.5.1 (0x00007f6660d28000)
	libntirpc.so.5.0 => /lib64/libntirpc.so.5.0 (0x00007f6660cd2000)
	libnfsidmap.so.1 => /lib64/libnfsidmap.so.1 (0x00007f6660cc7000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f6660c75000)
	libacl.so.1 => /lib64/libacl.so.1 (0x00007f6660c6a000)
	libjemalloc.so.2 => /lib64/libjemalloc.so.2 (0x00007f66609d0000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f66609c6000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f6660991000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f6660988000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6660981000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f66608a4000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f666088a000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f6660883000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f666082c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f666080b000)
	liburcu-bp.so.6 => /lib64/liburcu-bp.so.6 (0x00007f6660800000)
	libnsl.so.2 => /lib64/libnsl.so.2 (0x00007f66607e4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6660613000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f6660608000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f66603e9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f66602a5000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f666028a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f66619f3000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f666026e000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f66601a9000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f66601a1000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f6660190000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f6660189000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f665fe9b000)
	liburcu-common.so.6 => /lib64/liburcu-common.so.6 (0x00007f665fe92000)
	libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007f665fe62000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f665fe36000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f665fd71000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f665fd4d000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f665fd1f000)
	libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f665fbe4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f665fbca000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f665fb33000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f665fb0d000)

**Comment by feikiss** [comment]
Hi @ffilz ，what do u mean "licensing implications"?  Could u add more details pls? Thanks.

**Comment by ffilz** [comment]
Note - I am not a lawyer, consult a lawyer about licensing issues but basically there are different licenses among the libraries Ganesha utilizes. Some licenses have more restrictive terms for static linking (viral licenses) which may violate the licenses of some of the libraries or may have some other detrimental effect. Again, consult a lawyer before doing something like static linking.

**Comment by feikiss** [comment]
Got it. Thanks @ffilz .
