### ISSUE TITLE
Inclusion of CMakeParseArguments.cmake breaks Python detection

### ISSUE THREAD

**Issue by martin-schwenke** [nfs-ganesha/nfs-ganesha#949]
With `cmake -DUSE_ADMIN_TOOLS=YES ../nfs-ganesha/src` I see:

```
-- Could NOT find Python (missing: Python_EXECUTABLE Python_INCLUDE_DIRS Python_LIBRARIES Interpreter Development Development.Module Development.Embed) 
CMake Warning at CMakeLists.txt:598 (message):
  Cannot find python.  Disablin admin tools
```
I assumed `cmake`'s Python detection is broken so I constructed a tiny `CMakeLists.txt` and it found Python, so this is specific to Ganesha.

Then it was binary search time: add `find_package (Python COMPONENTS Interpreter Development)` in `CMakeLists.txt` and include files until I find where it breaks…

If I add it in `src/cmake/modules/FindPackageHandleStandardArgs.cmake` here:
```
get_filename_component(INCLUDED_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
include(${INCLUDED_DIR}/FindPackageMessage.cmake)
find_package (Python COMPONENTS Interpreter Development)
include(${INCLUDED_DIR}/CMakeParseArguments.cmake)
```
then
```
-- Found Python: /usr/bin/python3 (found version "3.11.2") found components: Interpreter Development Development.Module Development.Embed 
```
However, if I add it here:
```
get_filename_component(INCLUDED_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
include(${INCLUDED_DIR}/FindPackageMessage.cmake)
include(${INCLUDED_DIR}/CMakeParseArguments.cmake)
find_package (Python COMPONENTS Interpreter Development)
```
then
```
-- Could NOT find Python (missing: Python_EXECUTABLE Python_INCLUDE_DIRS Python_LIBRARIES Interpreter Development Development.Module Development.Embed) 
```
It appears the single function definition in `CMakeParseArguments.cmake` is breaking Python detection.

Above was all for, `V4-stable`.  I checked `next` and found that the Python check has changed to `find_package(Python3 COMPONENTS Interpreter)`.  This makes no real difference.

So, I add a conditional definition of that function to my toy test `CMakeLists.txt` and use the `next` branch's Python check:
```
Project(test)
cmake_minimum_required(VERSION 2.8.12)

if (DEFINE_CMAKE_PARSE_ARGUMENTS)
function(CMAKE_PARSE_ARGUMENTS prefix _optionNames _singleArgNames _multiArgNames)
  # first set all result variables to empty/FALSE
  foreach(arg_name ${_singleArgNames} ${_multiArgNames})
    set(${prefix}_${arg_name})
  endforeach()

  foreach(option ${_optionNames})
    set(${prefix}_${option} FALSE)
  endforeach()

  set(${prefix}_UNPARSED_ARGUMENTS)

  set(insideValues FALSE)
  set(currentArgName)

  # now iterate over all arguments and fill the result variables
  foreach(currentArg ${ARGN})
    list(FIND _optionNames "${currentArg}" optionIndex)  # ... then this marks the end of the arguments belonging to this keyword
    list(FIND _singleArgNames "${currentArg}" singleArgIndex)  # ... then this marks the end of the arguments belonging to this keyword
    list(FIND _multiArgNames "${currentArg}" multiArgIndex)  # ... then this marks the end of the arguments belonging to this keyword

    if(${optionIndex} EQUAL -1  AND  ${singleArgIndex} EQUAL -1  AND  ${multiArgIndex} EQUAL -1)
      if(insideValues)
        if("${insideValues}" STREQUAL "SINGLE")
          set(${prefix}_${currentArgName} ${currentArg})
          set(insideValues FALSE)
        elseif("${insideValues}" STREQUAL "MULTI")
          list(APPEND ${prefix}_${currentArgName} ${currentArg})
        endif()
      else()
        list(APPEND ${prefix}_UNPARSED_ARGUMENTS ${currentArg})
      endif()
    else()
      if(NOT ${optionIndex} EQUAL -1)
        set(${prefix}_${currentArg} TRUE)
        set(insideValues FALSE)
      elseif(NOT ${singleArgIndex} EQUAL -1)
        set(currentArgName ${currentArg})
        set(${prefix}_${currentArgName})
        set(insideValues "SINGLE")
      elseif(NOT ${multiArgIndex} EQUAL -1)
        set(currentArgName ${currentArg})
        set(${prefix}_${currentArgName})
        set(insideValues "MULTI")
      endif()
    endif()

  endforeach()

  # propagate the result variables to the caller:
  foreach(arg_name ${_singleArgNames} ${_multiArgNames} ${_optionNames})
    set(${prefix}_${arg_name}  ${${prefix}_${arg_name}} PARENT_SCOPE)
  endforeach()
  set(${prefix}_UNPARSED_ARGUMENTS ${${prefix}_UNPARSED_ARGUMENTS} PARENT_SCOPE)

endfunction()
endif()

find_package(Python3 COMPONENTS Interpreter)
```
Then:
```
$ rm -rf *
$ cmake -DDEFINE_CMAKE_PARSE_ARGUMENTS=FALSE ../src
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3 (found version "3.11.2") found components: Interpreter 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/martins/tmp/cmake-test/build
$ rm -rf *
$ cmake -DDEFINE_CMAKE_PARSE_ARGUMENTS=TRUE ../src
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/martins/tmp/cmake-test/build
```
That seems to be reasonable proof.

Unfortunately, my `cmake`-fu doesn't extend any further, so I can't diagnose this any deeper.

**Comment by dang** [comment]
There's something odd with python detection.  It works fine for me in all my environments, but Kaleb had failures in some.  What distro/version are you testing with?

**Comment by martin-schwenke** [comment]
We're originally seeing the problem in a Rocky Linux 8 container.

I've tested the minimal testcase above on real Debian 12 (bookworm) and Debian 11 (bullseye) machines.  The results are as above.  I thought the problem might be the python-is-python3 package (which makes /usr/bin/python a link to python3), but it still failed when I removed that link.

I also tested in the following containers, which also showed the failure: Red Hat UBI 8/9, Rocky Linux 8/9, AlmaLinux 8/9, Debian 11.

In all cases, /usr/bin/python3 exists.  I'm careful to remove everything in the build directory between tests.

Curiously, the testcase works in a Debian 10 container.  No idea why.  Both 10 & 11 have versioned /usr/bin/python3.x files, and corresponding /usr/bin/python3 links.

The difference is probably the `cmake` version (3.13.4 in Debian 10, 3.18.4 in Debian 11).  After assuming this was a cmake bug, I found that Python detection was fixed in about `cmake` 3.18.2.  I guess that Ganesha's definition of `CMAKE_PARSE_ARGUMENTS` function breaks Python detection after some particular `cmake` version.

I guess the main question is: why does Ganesha have its own version of `CMAKE_PARSE_ARGUMENTS`?  https://cmake.org/cmake/help/v3.5/module/CMakeParseArguments.html indicates it has been implemented natively since `cmake` 3.5.  It looks like commit c43049fc42b0a1d39b48ddbf93af56223ba5f9ee introduced it 10 years ago to work around a problem detecting D-Bus on Debian systems.  It isn't clear whether there are any differences in the `cmake` modules  introduced by that commit, compared to the upstream versions at the time.  It looks like it might have been the wrong way to solve the problem and those modules should now be removed - surely the required detection is fixed upstream in `cmake` by now?

I wonder how many other files in `src/cmake/modules` contain an interesting snapshot of history?  :smile:

**Comment by martin-schwenke** [comment]
I've submitted a patch (https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/554765) to fix this (and a followup (https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/554766/2) to fix a developer warning that is introduced).

I have tested this on:

* AlmaLinux 8
* AlmaLinux 9
* CentOS 7
* Debian 10
* Debian 11
* Fedora 38
* RockyLinux 8
* RockyLinux 9
* Ubuntu 22.04

In particular, both Python and D-Bus are correctly detected.

Tests are done in podman containers by running:
```
cmake -DUSE_FSAL_VFS=ON -DUSE_DBUS=ON -DENABLE_VFS_POSIX_ACL=YES -DUSE_ADMIN_TOOLS=YES ../nfs-ganesha/src`
```
inside the containers on `next` and my `wip` branch (containing the 2 commits), and comparing the output (stdout/stderr) from the cmake commands.

The containers contain a reasonable number of (non-filesystem-related) dependencies.  I'm happy to submit the container generation stuff (ganesha-container script, Containerfile, install-packages.sh script) as a ganesha patch that puts these in the scripts/ directory or similar.

Attached is a recursive diff of the output directories for pre (`next` branch) and post (`wip` branch)  runs of a wrapper script (which I guess I could also submit if useful, but it is less generic).  It shows differences in (detection of):

* Python (good! - works in pre case on CentOS 7 & Debian 10, works in post case on all distros)
* CEPHFS (whitespace change)
* glusterfs-api (message case/wording change)
* dbus-1 (message case change)
* RADOS (whitespace change)
* git head details (expected)
* `USE_ADMIN_TOOLS` changes from `OFF` to `ON` (good!)
* `LSB_RELEASE` → `LSBRelease` module name change

[config.out.diff.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/11607315/config.out.diff.txt)

**Comment by dang** [comment]
This is a good start for a test matrix.  I've tested Fedora 35 (fails) and Fedora 37 (succeeds).  We'll also need to test centos 8 and 9, since we care more about those than 7.  @kalebskeithley what versions of Ubuntu do we care about?

**Comment by martin-schwenke** [comment]
I've added Fedora 37, Ubuntu 18.04/20.04, CentOS 8/9. Will attempt to post something tomorrow.

**Comment by martin-schwenke** [comment]
I have attached the output from:
```
$ (cd nfs-ganesha && checkout next)
$ ganesha-container all sh -c "rm -rf build/* && cd build && cmake -DUSE_FSAL_VFS=ON -DUSE_DBUS=ON -DENABLE_VFS_POSIX_ACL=YES -DUSE_ADMIN_TOOLS=YES ../nfs-ganesha/src" >out.next 2>&1
$ (cd nfs-ganesha && checkout wip)
$ ganesha-container all sh -c "rm -rf build/* && cd build && cmake -DUSE_FSAL_VFS=ON -DUSE_DBUS=ON -DENABLE_VFS_POSIX_ACL=YES -DUSE_ADMIN_TOOLS=YES ../nfs-ganesha/src" >out.wip 2>&1
$ diff -u -w out.{next,wip} >out.diff.txt
```
[out.diff.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/11669194/out.diff.txt)

The `wip` branch contains "build: Fix Python detection" and "build: Fix developer warning for LSB module".

For CentOS 8, the important differences are:
```
--- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-CMake Warning at CMakeLists.txt:598 (message):
-  Cannot find python.  Disablin admin tools
-
-
+-- Found Python3: /usr/bin/python3.6 (found version "3.6.8") found components: Interpreter 
```
and 
```
--- USE_ADMIN_TOOLS = OFF
+-- USE_ADMIN_TOOLS = ON
```
For CentOS 9:
```
--- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-CMake Warning at CMakeLists.txt:598 (message):
-  Cannot find python.  Disablin admin tools
-
-
+-- Found Python3: /usr/bin/python3.9 (found version "3.9.16") found components: Interpreter 
```
and
```
--- USE_ADMIN_TOOLS = OFF
+-- USE_ADMIN_TOOLS = ON
```
For Fedora 37:
```
--- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-CMake Warning at CMakeLists.txt:598 (message):
-  Cannot find python.  Disablin admin tools
-
-
+-- Found Python3: /usr/bin/python3.11 (found version "3.11.3") found components: Interpreter 
```
and
```
--- USE_ADMIN_TOOLS = OFF
+-- USE_ADMIN_TOOLS = ON
```
For Ubuntu 18.04 there are no important differences.

For 20.04 it now finds the versioned Python executable:
```
--- Found Python3: /usr/bin/python3 (found version "3.8.10") found components: Interpreter 
+-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
```
For Ubuntu 22.04:
```--- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-CMake Warning at CMakeLists.txt:598 (message):
-  Cannot find python.  Disablin admin tools
-
-
+-- Found Python3: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter 
```
and
```
--- USE_ADMIN_TOOLS = OFF
+-- USE_ADMIN_TOOLS = ON
```
As expected, all now have this difference:
```
--- Could NOT find LSB_RELEASE (missing:  LSB_RELEASE_EXECUTABLE) 
+-- Could NOT find LSB_release (missing: LSB_RELEASE_EXECUTABLE) 
```

**Comment by dang** [comment]
Okay, I'm happy then.
