### ISSUE TITLE
Question about the error of compile source into debian package.

### ISSUE THREAD

**Issue by Midori-ch** [nfs-ganesha/nfs-ganesha#95]
Hi all,
If this question should not ask here, please just ignore.
Try to compile source into deb package for ubuntu 14.04 by using "dpkg-buildpackage" .
But there is an error "dpkg-shlibdeps: error: no dependency information found for /usr/lib/libntirpc.so.1.3"
Should I add "ld_library_path" to file debian/rule？
Appreciate for any comments or suggestions.

Please find the attachment to check error log.

[err.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/216819/err.txt)

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by kalebskeithley** [comment]
It's nine months old. I guess you can close it.
I don't know about dpkg-buildpackage. For Ubuntu I use a Launchpad ppa to build and merely set the dependencies in Launchpad.
On Debian I use pbuilder and after building (lib)ntirpc, use HOOKDIR and OTHERMIRROR in /etc/pbuilderrc pointing at the location of my ntirpc apt repo

**Comment by dang** [comment]
Also, there's active work underway to package for Debian, so these issues should be resolved as part of that.

**Comment by ffilz** [comment]
Ok, I'll close this one. If the issue really is not resolved by the work in progress the issue can be re-opened or a new one created.
