### ISSUE TITLE
[question]How to set white list for NFS Ganesha

### ISSUE THREAD

**Issue by feikiss** [nfs-ganesha/nfs-ganesha#953]
Hi All,
   I want to set the white list for the client, but it seems the default config of nfs-ganesha is for everyone. I just need to open the connection for some specific IPs. How should I configure it?  What I have tried but not work:

`
EXPORT{

      xxxxx // other configure.
      CLIENT
        {
                Clients = 192.168.3.1;
                Access_Type = RO;
                Anonymous_uid = 123;
                Anonymous_gid = 123;
                Squash = root_squash;
        }
}`

The result is other IP (out of whitelist ) can still mount it.

Thanks.

**Comment by dang** [comment]
This is explained in the CLIENT section of this man page: https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-export-config.rst

Basically, it applies CLIENT, then EXPORT, then EXPORT_DEFAULTS.  So if you want default-deny for an export, put it in the EXPORT block, and if you want default-deny on everything put it in EXPORT_DEFAULTS.

**Comment by ffilz** [comment]
One warning, the CLIENT list in EXPORT_DEFAULTS applies to the PseudoFS, so you must either explicitly override the default pseudofs export (id 0, path/psedeudo "/") or make sure the CLIENT list in EXPORT_DEFAULTS allows all your clients.

If you use CLIENT lists in EXPORTs, you can either terminate the list with an entry for clients = "*"; Access_type = NONE" or set Access_type = NONE; in the EXPORT.

**Comment by ffilz** [comment]
Does that answer your question?
