### ISSUE TITLE
NFS-Ganesha crashes at free_client_record()

### ISSUE THREAD

**Issue by skmprabhu252** [nfs-ganesha/nfs-ganesha#961]
(gdb) p *record
$5 = {cr_refcount = 0, cr_mutex = {__data = {__lock = 1, __count = 0, __owner = 144162, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {
        __prev = 0x0, __next = 0x0}}, __size = "\001\000\000\000\000\000\000\000\"3\002\000\001", '\000' <repeats 26 times>, __align = 1},
  cr_confirmed_rec = 0x0, cr_unconfirmed_rec = 0x0, cr_server_addr = 0, cr_pnfs_flags = 0, cr_client_val_len = 48,
  cr_client_val = 0x3fff200ed17c "Linux NFSv4.0 p1901-submit.tsd.usit.no/10.3.2.30"}
(gdb) bt
#0  0x00003fffa73e52e8 in raise () from /lib64/libpthread.so.0
#1  0x00003fffa7954628 in crash_handler (signo=6, info=0x3ffefac4a468, ctx=0x3ffefac496f0)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/MainNFSD/nfs_init.c:247
#2  <signal handler called>
#3  0x00003fffa717fcb0 in raise () from /lib64/libc.so.6
#4  0x00003fffa718200c in abort () from /lib64/libc.so.6
#5  0x00003fffa79b9fd4 in free_client_record (record=0x3fff200ed130) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/SAL/nfs4_clientid.c:1381
#6  0x00003fffa79ba3d8 in dec_client_record_ref (record=0x3fff200ed130) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/SAL/nfs4_clientid.c:1461
#7  0x00003fffa79b825c in nfs_client_id_expire (clientid=0x3fff200edbd0, make_stale=false)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/SAL/nfs4_clientid.c:914
#8  0x00003fffa79c7820 in reserve_lease_or_expire (clientid=0x3fff200edbd0, update=true)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/SAL/nfs4_lease.c:181
#9  0x00003fffa7a59db4 in nfs4_op_renew (op=0x3fff029152d0, data=0x3fff0320d9c0, resp=0x3ffee960cab0)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/Protocols/NFS/nfs4_op_renew.c:91
#10 0x00003fffa7a2ed80 in process_one_op (data=0x3fff0320d9c0, status=0x3ffefac4cfd0)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/Protocols/NFS/nfs4_Compound.c:920
#11 0x00003fffa7a30010 in nfs4_Compound (arg=0x3ffeeabd84a0, req=0x3ffeeabd7c90, res=0x3ffee9854f60)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/Protocols/NFS/nfs4_Compound.c:1327
#12 0x00003fffa794dae4 in nfs_rpc_process_request (reqdata=0x3ffeeabd7c90)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/MainNFSD/nfs_worker_thread.c:1508
#13 0x00003fffa794df44 in nfs_rpc_valid_NFS (req=0x3ffeeabd7c90) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/MainNFSD/nfs_worker_thread.c:1625
#14 0x00003fffa7891fc0 in svc_vc_decode (req=0x3ffeeabd7c90) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/libntirpc/src/svc_vc.c:906
#15 0x00003fffa788bd30 in svc_request (xprt=0x3fff004bf510, xdrs=0x3fff0383d770)
    at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/libntirpc/src/svc_rqst.c:1202
#16 0x00003fffa7891e40 in svc_vc_recv (xprt=0x3fff004bf510) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/libntirpc/src/svc_vc.c:879
#17 0x00003fffa788bc68 in svc_rqst_xprt_task_recv (wpe=0x3fff004bf748) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/libntirpc/src/svc_rqst.c:1183
#18 0x00003fffa788cdbc in svc_rqst_epoll_loop (wpe=0x10005119a78) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/libntirpc/src/svc_rqst.c:1564
#19 0x00003fffa789d3c4 in work_pool_thread (arg=0x3fff8cad3ef0) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/libntirpc/src/work_pool.c:184
#20 0x00003fffa73d8cd4 in start_thread () from /lib64/libpthread.so.0
#21 0x00003fffa7267f14 in clone () from /lib64/libc.so.6

(gdb) f 5
#5  0x00003fffa79b9fd4 in free_client_record (record=0x3fff200ed130) at /usr/src/debug/nfs-ganesha-3.5-ibm071.21.308708/SAL/nfs4_clientid.c:1381
1381            PTHREAD_MUTEX_destroy(&record->cr_mutex);
(gdb) list
1376     *
1377     * @param[in] record The record to free
1378     */
1379    void free_client_record(nfs_client_record_t *record)
1380    {
1381            PTHREAD_MUTEX_destroy(&record->cr_mutex);
1382
1383            gsh_free(record);
1384    }
1385

/**
 * @brief Logging mutex destroy
 *
 * @param[in,out] _mtx The mutex to destroy
 */

#define PTHREAD_MUTEX_destroy(_mtx)                                     \
        do {                                                            \
                int rc;                                                 \
                                                                        \
                rc = pthread_mutex_destroy(_mtx);                       \
                if (rc == 0) {                                          \
                        LogFullDebug(COMPONENT_RW_LOCK,                 \
                                     "Destroy mutex %p (%s) at %s:%d",  \
                                     _mtx, #_mtx,                       \
                                     __FILE__, __LINE__);               \
                } else {                                                \
                        LogCrit(COMPONENT_RW_LOCK,                      \
                                "Error %d, Destroy mutex %p (%s) "      \
                                "at %s:%d", rc, _mtx, #_mtx,            \
                                __FILE__, __LINE__);                    \
                        abort();                                        \
                }                                                       \
        } while (0)

And, from ganesha.log
2023-06-13 11:00:47 : epoch 00040093 : p01-proto01 : gpfs.ganesha.nfsd-134968[svc_112] free_client_record :RW LOCK :CRIT :Error 16, Destroy mutex 0x3fff200ed138 (&record->cr_mutex) at /home/ppsbld/workspace/SS_5.1.7/Build_Prod/Ganesha_5.1.7_ProdBuild/label/BLDPLE301_PPC64LE_REDHAT_7.7.0/ganesha-rpmdir/rpmbuild/BUILD/nfs-ganesha-3.5-ibm071.21.308708/SAL/nfs4_clientid.c:1381

pthread_mutex_destroy() is failed with rc=16, That's EBUSY. The mutex lock is held by some threads.

(gdb) p *record
$6 = {cr_refcount = 0, cr_mutex = {__data = {__lock = 1, __count = 0, __owner = 144162, __nusers = 1, __kind = 0, __spins = 0, __elision = 0, __list = {
        __prev = 0x0, __next = 0x0}}, __size = "\001\000\000\000\000\000\000\000\"3\002\000\001", '\000' <repeats 26 times>, __align = 1},
  cr_confirmed_rec = 0x0, cr_unconfirmed_rec = 0x0, cr_server_addr = 0, cr_pnfs_flags = 0, cr_client_val_len = 48,
  cr_client_val = 0x3fff200ed17c "Linux NFSv4.0 p1901-submit.tsd.usit.no/10.3.2.30"}
  
  
  * 1    LWP 144162        0x00003fffa73e52e8 in raise () from /lib64/libpthread.so.0

The current running thread is holding mutex lock and trying to destroy the mutex.

(gdb) p clientid->cid_client_record
$3 = (nfs_client_record_t *) 0x0  ==> cid_client_record is null

in reserve_lease_or_expire(), the thread should not take mutex lock if record is null. 

made below changes to fix the issue

From 

	if (valid == 0) {
		/* Expire the lease */
		/* Get the client record. It will not be NULL. */
		nfs_client_record_t *client_rec =  clientid->cid_client_record;

		/* get a ref to client_id as we might drop the
		 * last reference with expiring. This also protects the
		 * reference to the client_record.
		 */
		inc_client_id_ref(clientid);

		PTHREAD_MUTEX_unlock(&clientid->cid_mutex);

		PTHREAD_MUTEX_lock(&client_rec->cr_mutex);

		nfs_client_id_expire(clientid, false);

		PTHREAD_MUTEX_unlock(&client_rec->cr_mutex);

		/* drop our reference to the client_id */
		dec_client_id_ref(clientid);

		return false;
	}

To 

	if (valid == 0) {
		/* Expire the lease */
		/* Get the client record. */
		nfs_client_record_t *client_rec =  clientid->cid_client_record;

		/* get a ref to client_id as we might drop the
		* last reference with expiring.
		*/
		inc_client_id_ref(clientid);
		
		/* if record is STALE, the linkage to client_record is
        * removed already. Acquire a ref on client record
		* before we drop the mutex on clientid
		*/
        if (client_rec != NULL)
			inc_client_record_ref(client_rec);

        PTHREAD_MUTEX_unlock(&clientid->cid_mutex);

        if (client_rec != NULL)
            PTHREAD_MUTEX_lock(&client_rec->cr_mutex);

		nfs_client_id_expire(clientid, false);

		if (client_rec != NULL) {
			PTHREAD_MUTEX_unlock(&client_rec->cr_mutex);
			dec_client_record_ref(client_rec);
		}

		/* drop our reference to the client_id */
		dec_client_id_ref(clientid);

		return false;
	}

PS: This is a regression defect of https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/551789.

**Comment by ffilz** [comment]
Submitted patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/555626

The patch does need some attention.

**Comment by ffilz** [comment]
Patch is merged.
