### ISSUE TITLE
What are common methods to configure Active-Active Load Balancing in NFS-Ganesha with 2 node Gateway?

### ISSUE THREAD

**Issue by Moni-V** [nfs-ganesha/nfs-ganesha#962]
Hi , we have configured 2 servers (Rocky8.4) as NFS Gateway and mounted it on Lustre File backend. We are using 1 client node. What are the steps to configure Active-Active Load Balancing in NFS-Ganesha, so that the I/O goes to both Gateway nodes. Also what happens if one Gateway goes down in Active-Active Load Balancing scenario?

**Comment by dang** [comment]
I'm not aware of anyone setting up active-active on lustre, so there may be issues.  That said, you need cluster management software, to create and manage virtual IPs, and to monitor the health of the Ganesha instances.  This can be Pacemaker/Corosync, CTDB, or kuberneties.  You need to pick and configure the appropriate recovery backend (likely fs_ng for lustre).  You need to configure lustre to allow recovery of state such as locks when a Ganesha fails over (this is the part I'm not sure anyone has done before).  Then, you point the clients at the virtual IPs. 

When a Ganesha fails, the cluster management software detects it, and fails the virtual IP over to a still-running Ganesha.  This involves putting the cluster into Grace, and allowing the clients of the failed Ganesha to re-establish state on the new one.  When the failed Ganesha is restarted, this process happens again in reverse to get the clients back to the now-running Ganesha.

Unfortunately, the only detailed docs for HA using Ganesha were in the Gluster project, and they seem to have been removed.

**Comment by ffilz** [comment]
Thanks for joining the community call. Did you have any more questions on this subject? If not, please close this issue.
