### ISSUE TITLE
HAProxy_Hosts check fails 

### ISSUE THREAD

**Issue by gouthampacha** [nfs-ganesha/nfs-ganesha#966]
I'm using NFS-Ganesha v5, and deploying it via cephadm:

Client restrictions aren't working when there's an IPv6 encapsulated IPv4 address in the client's PROXY protocol header:

Logs from the failure: https://paste.opendev.org/show/beGjSqUkK6ojtlFtYNkA/

**Comment by ffilz** [comment]
As discussed, could we get debug logs. I don't necessarily need all debug, but the following would help:

LOG {
COMPONENTS {
EXPORT=FULL_DEBUG;
DISPATCH=FULL_DEBUG;
TIRPC=FULL_DEBUG;
}
}

**Comment by gouthampacha** [comment]
Thanks @ffilz; With your explanation of how this works, I did some more debugging, and I now think the problem is elsewhere. 
 
I'm using Ceph FSAL in my setup, and OpenStack Manila to orchestrate CephFS exports over NFS; I created the NFS cluster using `cephadm`. 

Using your log configuration, I noticed the logs during a mount failure... cephadm sets the `HAProxy_Hosts` configuration; and it was incorrect. 

Some more context, and logs:

Some relevant info on OpenStack (client restrictions/ACLs and export info):
```
$ openstack share access list share_nfs
+--------------------------------------+-------------+----------------+--------------+--------+------------+----------------------------+------------+
| ID                                   | Access Type | Access To      | Access Level | State  | Access Key | Created At                 | Updated At |
+--------------------------------------+-------------+----------------+--------------+--------+------------+----------------------------+------------+
| 7657e596-770c-437b-8bd7-ed5ce701f133 | ip          | 192.168.130.28 | rw           | active | None       | 2023-06-28T21:19:51.034062 | None       |
| ea264b08-f904-4dc1-b815-28e6be2aed06 | ip          | 192.168.130.27 | rw           | active | None       | 2023-06-28T21:19:29.098042 | None       |
+--------------------------------------+-------------+----------------+--------------+--------+------------+----------------------------+------------+

$ openstack share export location list share_nfs
+--------------------------------------+------------------------------------------------------------------------------------------------------------+-----------+
| ID                                   | Path                                                                                                       | Preferred |
+--------------------------------------+------------------------------------------------------------------------------------------------------------+-----------+
| ef658bd7-8237-4fa0-83a3-42907e90ac89 | 192.168.130.21:/volumes/_nogroup/399c3d6a-b50d-4e33-87d7-8848c1680e3b/406f33bf-26ab-4e04-aa27-0be027af4d24 | False     |
+--------------------------------------+------------------------------------------------------------------------------------------------------------+-----------+
```

Mount failure on the client:
```
# mount -vvvt nfs 192.168.130.21:/volumes/_nogroup/399c3d6a-b50d-4e33-87d7-8848c1680e3b/406f33bf-26ab-4e04-aa27-0be027af4d24 /mnt
mount.nfs: timeout set for Wed Jun 28 17:29:34 2023
mount.nfs: trying text-based options 'vers=4.2,addr=192.168.130.21,clientaddr=192.168.130.28'
mount.nfs: mount(2): Input/output error
mount.nfs: mount system call failed
```

Logs from an NFS-Ganesha service when mount failed: https://paste.openstack.org/show/belF8k02E7HmmFAGhuNN/

My cluster configuration: https://paste.openstack.org/show/bXKyNHQnOt4vmy3IQ3C7/

As you can see, `ganesha.conf` had: `HAProxy_Hosts = 192.168.130.20, 10.10.10.20, 10.10.10.30;`
The first IP here was incorrect, Ganesha was seeing `10.10.10.10` as the HAProxy IP; I fixed that manually, and client restrictions worked like a charm. 


-------------

```
# podman exec ceph-4b5c8c0a-ff60-454b-a1b4-9747aa737d19-nfs-cephfs-0-0-ceph-20-nlfwls head /etc/ganesha/ganesha.conf
# This file is generated by cephadm.
NFS_CORE_PARAM {
        Enable_NLM = false;
        Enable_RQUOTA = false;
        Protocols = 4;
        NFS_Port = 12049;
        HAProxy_Hosts = 10.10.10.10, 10.10.10.20, 10.10.10.30;
}
```

Ganesha Log with the issue fixed: https://paste.openstack.org/show/bewK45ObHrZfSlQdyYH5/

**Comment by gouthampacha** [comment]
I reported the issue against ceph: https://tracker.ceph.com/issues/61852 

Closing this issue; thanks again @ffilz

**Comment by ffilz** [comment]
OK, thanks. I've marked this as an external bug (in case anyone decides to do any sort of tracking of github issues...)
