### ISSUE TITLE
[ganesha v5.1][nfsv4.1]Readdir mdcache_readdir_chunked infinitie loop

### ISSUE THREAD

**Issue by free11kaka22** [nfs-ganesha/nfs-ganesha#967]
We recently hit  one issue which is 'ls -l' command hung。We run gdb to trace it, and found that readdir operation  stuck in an infinitie loop in mdcache_readdir_chunked function.The circumstance is that there are 18 objects in one directory, its cookie rang is [25338, 25355], For unknown reason, the parent chunk only caches  three dir entries which are 25338 25339 25340。when do readdir ops, after scan over the cached three entries, the mdcache_readdir_chunked call mdcache_populate_dir_chunk to populate the chunk, the whence (next_ck) argument is always is 0.but when underly fsal excuting  readdir , mdc_readdir_chunk_object terminated when the first object whick cookie is 25338 added into the chunk, the reason is that dirent exists in avl tree and chunk isn't equal the state's curr chunk(line 2377-2387). more details in attchment deadloop.txt,it included the gdb strace steps.

```
	if (new_dir_entry->chunk != state->cur_chunk) {
		/* We have the situation where we have collided with a
		 * previously used chunk (and thus we have a partial chunk).
		 * Since dirent is pointing to the existing dirent and the one
		 * we allocated above has been freed we don't need to do any
		 * cleanup.
		 *
		 * Don't allow readahead in this case just indicate this
		 * directory is terminated.
		 */
		result = DIR_TERMINATE;
```
I doesn't find out the root cause why the chunk only have three entries。But I have a bit of confusion about mdcache_readdir_chunked funciton.
1、when reload a chunk, it always starts from reload_ck （line 3220-3238）, if above situation happened readdir terminated at the beggining ,it will stuck in a infinitie loop. can we skip the ok entries? eg:skip 25338.
```
				look_ck = dirent->ck;
				next_ck = chunk->reload_ck;
				reload_chunk = true;
```
2、when scan over a chunk, if the chunk_nex_ck is non-zero， it updates the look_ck, can we update the next_ck at the same time。In my examples chunk_nex_ck is 25341, the uncached first object, if updates next_ck it can tell underlying fsal to readdir from a new whence. (line 3401-3412).
```
	if (chunk->next_ck != 0) {
		/* If the chunk has a known chunk following it, use the first
		 * cookie in that chunk for AVL tree lookup, which will succeed
		 * rather than having to do a readdir to find the next entry.
		 *
		 * If the chunk is no longer present, the lookup will fail, in
		 * which case next_ck is the right cookie to use as the whence
		 * for the next readdir.
		 */
		look_ck = chunk->next_ck;
		LogFullDebugAlt(COMPONENT_NFS_READDIR, COMPONENT_MDCACHE,
				"Setting look_ck from next_ck=%"PRIx64,
				chunk->next_ck);
	}
```
[deadloop.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/11914095/deadloop.txt)

**Comment by ffilz** [comment]
What FSAL are you using?

Could you run with some debug log:

LOG {
COMPONENTS {
FSAL=FULL_DEBUG;
READDIR=FULL_DEBUG;
}
}

That may help me understand what's going on with the readdir.

**Comment by free11kaka22** [comment]
> What FSAL are you using?
> 
> Could you run with some debug log:
> 
> LOG { COMPONENTS { FSAL=FULL_DEBUG; READDIR=FULL_DEBUG; } }
> 
> That may help me understand what's going on with the readdir.



> What FSAL are you using?
> 
> Could you run with some debug log:
> 
> LOG { COMPONENTS { FSAL=FULL_DEBUG; READDIR=FULL_DEBUG; } }
> 
> That may help me understand what's going on with the readdir.

Ok, I'll try to reproduce it. I had run with debug log many times, But it didn't occur any more.

**Comment by free11kaka22** [comment]
Hi  @ffilz ,we reproduced this issue again with debug info.the scenario is that he have two clients,one client wirtes files, one client do "ls -l" operation constantly。when the write client wrote 133 files, the ls client hung. I analyzed the log，found that when the first chunk is full, a new chunk allocated, the new chunk's reload_ck member is prev chunk's last object cookie. do this in mdcache_get_chunk.
`mdcacke_get_chunk {
    ....
    if (prev_chunk) {
         chunk->reload_ck = glist_last_entry(&prev_chunk->dirents, mdcache_dir_entry_t, chunk_list)->ck;
    }
    ....
}`
in mdcache_readdir_chunked, when dirent->entry is NULL, will call mdcache_find_keyed_reason to get mdcache entry, but failed(maybe be eliminated), then unref chunk, reloading the chunk. the reload ck is prev chunk's last entry's cookie。when do underlying fsal readdir , the mdc_readdir_chunk_object function called with the entry, the entry has been cached in prev_chunk,and prev_chunk isn't  equal to state->cur_chunk,then terminate the underlying fasl。when continue the mdcache_readdir_chunked, scaned over prev chunk,if chunk->next_ck isn't 0, only update look_ck,not updating next_ck.this makes calls underlying fasl to look for prev chunk's last entry，the mdc_readdir_chunk_object will terminated because object exists in prev_chunk. the readdir op stuck in infinite loop.details in [attachment.](url)
[gsh_log-2023_08_16_20_31_15-2023_08_16_20_31_32.tar.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/12368723/gsh_log-2023_08_16_20_31_15-2023_08_16_20_31_32.tar.gz)

**Comment by free11kaka22** [comment]
Hi @ffilz , I found some error in underlying fsal demo about readdir. the underlying fsal demo implemention is referred to mem fsal, but it stores data in special format. when do readdir, if not from beginning , it should returns the next entry ,not the entry which whence argument represents. I'm sorry to waste your time.
