### ISSUE TITLE
Export client{} block evaluated differently between NFSv3 and NFSv4

### ISSUE THREAD

**Issue by pittburgher** [nfs-ganesha/nfs-ganesha#969]
Hello -- I have the following exports defined, along with client{} restrictions for each:

```
EXPORT {
    Export_Id = 10;
    Pseudo = "/default/subfolder1";
    Protocols = "V3,V4";
    Access_Type = "none";
    PrivilegedPort = false;
    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = 172.31.0.0/20;
        Access_Type = "RW";
        Squash = No_root_squash;
        Anonymous_Uid = 65534;
        Anonymous_Gid = 65534;
        Manage_Gids = False;
    }
}

EXPORT {
    Export_Id = 20;
    Pseudo = "/default/subfolder1/subfolder1-1";
    Protocols = "V3,V4";
    Access_Type = "none";
    PrivilegedPort = false;
    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = 172.31.8.0/24;
        Access_Type = "RW";
        Squash = No_root_squash;
        Anonymous_Uid = 65534;
        Anonymous_Gid = 65534;
        Manage_Gids = False;
    }
}
```

When a client in the 172.31.0.0/20 subnet mounts /default/subfolder1, using NFSv3, here is the view:

mount -t nfs 172.31.15.57:/default/subfolder1 -v -o v3 /mnt/nfsv4
[root@client1 subfolder1]# ls -R /mnt/nfsv4
/mnt/nfsv4:
subfolder1-1

/mnt/nfsv4/subfolder1-1:

**Of particular note, the NFSv3 mount shows subfolder1-1.**

When the same client mounts /default/subfolder1, using NFSv4, here is the view:

mount -t nfs4 172.31.15.57:/default/subfolder1 -v /mnt/nfsv4
[root@client1 ec2-user]# ls -Ral /mnt/nfsv4
/mnt/nfsv4:
total 0
drwxr-xr-x 1 root root  0 Jul  5 21:20 .
drwxr-xr-x 6 root root 56 Jun 27 13:51 ..

**Note that subfolder1-1 is no longer visible.**

==> **What accounts for the difference in the filesystem view between the NFSv3 and NFSv4 mount?**

**Comment by ffilz** [comment]
What is the Path for each export?

What are the rest of your config options, particularly NFS_CORE_PARAM { Mount_Path_Pseudo }?

**Comment by pittburgher** [comment]
> What is the Path for each export?
> 
> What are the rest of your config options, particularly NFS_CORE_PARAM { Mount_Path_Pseudo }?

```
EXPORT {
    Export_Id = 10;
    Path = "/tmp/blah/nfs_2aa401a0-ef19-2c3b-6e6d-e852c7118185_19/subfolder1";
    Pseudo = "/default/subfolder1";
    Protocols = "V4";
    Access_Type = "none";
    PrivilegedPort = false;
    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = 172.31.0.0/20;
        Access_Type = "RW";
        Squash = No_root_squash;
        Anonymous_Uid = 65534;
        Anonymous_Gid = 65534;
        Manage_Gids = False;
    }
}

EXPORT {
    Export_Id = 20;
    Path = "/tmp/blah/nfs_2aa401a0-ef19-2c3b-6e6d-e852c7118185_20/subfolder1/subfolder1-1";
    Pseudo = "/default/subfolder1/subfolder1-1";
    Protocols = "V4";
    Access_Type = "none";
    PrivilegedPort = false;
    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = 172.31.8.0/24;
        Access_Type = "RW";
        Squash = No_root_squash;
        Anonymous_Uid = 65534;
        Anonymous_Gid = 65534;
        Manage_Gids = False;
    }
}
```

```
NFS_CORE_PARAM
{
    Protocols = "V3","V4";
    mount_path_pseudo = true;
    Enable_NLM = false;
    Enable_FULLV3_Stats = true;
    Enable_RQUOTA = false;
    MNT_Port = 0;
    Enable_FULLV4_Stats = true;
    Clustered = true;
}
```

**Comment by ffilz** [comment]
So you are exporting two filesystems? To make it a bit simpler, you are exporting:

/a/subfolder1
and
/b/subfolder1/subfolder1-1

Does /a/subfolder1/subfolder1-1 exist as a directory? I think it must. That becomes an NFSv4 pseudofs mount point or junction for the 2nd export. But it isn't a special node for NFSv3. So NFSv3 will be able to access anything under /a/subfolder1. The NFSv4 mount will see this node as a junction, and then see that the client doesn't have access to the 2nd export and thus it will hide the junction and it's export from the client. Thus the different observations.

Now I also see a potential problem with your 2nd export. To get to the 2nd export via NFSv4, the 1st export must be traversed, but the clients that have access to the 2nd export don't have access to the 1st export.

**Comment by pittburgher** [comment]
> So you are exporting two filesystems? To make it a bit simpler, you are exporting:
> 
> /a/subfolder1 and /b/subfolder1/subfolder1-1
> 
> Does /a/subfolder1/subfolder1-1 exist as a directory?

Yes, both of those are correct.

I am not familiar with NFS junctions. Given the example above, if the parent path, within the path parameter, within the exports configuration, were the same, would the behavior then be the same as NFSv3? That is:

EXPORT {
    Export_Id = 10;
    Path = "**/tmp/blah/nfs_2aa401a0-ef19-2c3b-6e6d-e852c7118185_19**/subfolder1";
    Pseudo = "/default/subfolder1";

EXPORT {
    Export_Id = 20;
    Path = "**/tmp/blah/nfs_2aa401a0-ef19-2c3b-6e6d-e852c7118185_19**/subfolder1/subfolder1-1";
    Pseudo = "/default/subfolder1/subfolder1-1";

**Comment by ffilz** [comment]
That would improve things, but still, with NFSv4 there is going to be a problem if all the clients given access to the 2nd export (20) do not also have access to the 1st export (10).

**Comment by ffilz** [comment]
Can we close this?

**Comment by pittburgher** [comment]
> Can we close this?

Yes -- thank you.
