### ISSUE TITLE
ls -l on directories containing symlinks results in EIO with FSAL_VFS when built with -DENABLE_VFS_POSIX_ACL=YES

### ISSUE THREAD

**Issue by martin-schwenke** [nfs-ganesha/nfs-ganesha#978]
The ACL code in FSAL_VFS tries to get ACLs for symlinks opened with O_NOFOLLOW.  This results in bizarre directory listings full of question marks and, after that, EIO.  This doesn't seem to happen until MDCACHE expiry occurs.  After that, EIO is seen consistently.

Fix posted: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/556818

Opening this issue to increase visibility, in case anyone searches for this problem, and so I can put a Fixes: tag in the commit.

**Comment by ffilz** [comment]
Patch submitted https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/556818?usp=search
