### ISSUE TITLE
V5.4 crash during random testing

### ISSUE THREAD

**Issue by gogauravin** [nfs-ganesha/nfs-ganesha#981]
In one of our random testing received following stack trace. Not sure about the scenario to reproduce:

```
_L_unlock_13 at funlockfile.c:?
__GI_raise at :?
__GI_abort at :?
__assert_fail_base at :?
__GI___assert_fail at :?
make_inactive_lru at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:480
_mdcache_lru_unref at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1953
xdr_notify at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:1367
CityHash64 at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/include/nfs_proto_data.h:415
compound_data_Free at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/Protocols/NFS/nfs4_Compound.c:1494
CityHash64 at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/Protocols/NFS/nfs4_Compound.c:1393
admin_halt at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/MainNFSD/nfs_worker_thread.c:1517
admin_halt at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/MainNFSD/nfs_worker_thread.c:1732
svc_fd_ncreatef at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/libntirpc/src/svc_vc.c:1044
svc_request at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/libntirpc/src/svc_rqst.c:1202
svc_fd_ncreatef at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/libntirpc/src/svc_vc.c:1017
svc_rqst_xprt_task_recv at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/libntirpc/src/svc_rqst.c:1183
svc_rqst_epoll_loop at /usr/src/debug/nfs-ganesha-5.4-90666.f86835af33e1/libntirpc/src/svc_rqst.c:1564
work_pool_thread at /usr/src/debug/nf
```

**Comment by dang** [comment]
Are you sure about this backtrace?  It seems incorrect (the call path doesn't match up to real code), and the line numbers don't match up.  It seems likely that the debuginfo is from a different version of Ganesha.

**Comment by gogauravin** [comment]
Yes its from latest version (v5.4) of nfs-ganesha/next. from nfs4_Compound.c line 1393, I can follow the backtrace and the line numbers given. Attaching here the screenshot of some of the files (please read left to write). 
I think the function name written on each line seems wrong and that might be confusing you. We will check why those function names are wrong. But i think if we follow the file name and line number its matching.

<img width="2009" alt="Backtrace_code" src="https://github.com/nfs-ganesha/nfs-ganesha/assets/132249322/01973d40-5230-44ce-abfb-7da67617b9dc">

**Comment by ffilz** [comment]
Can you replicate? If so, can you test with this patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/557136?usp=search ?

There might yet be a ref leak or some other race, but I think this change should assure that only one thread moves an entry from active to inactive or frees it.

**Comment by ffilz** [comment]
I merged that patch.

**Comment by ffilz** [comment]
Over 60 days old with no verification response. Closing.
