### ISSUE TITLE
Procedure to check-in code changes in nfs-ganesha git repo.

### ISSUE THREAD

**Issue by Moni-V** [nfs-ganesha/nfs-ganesha#984]
Hi, I have made a minor code change in python file "Ganesha/glib_dbus_stats.py" in order to make command "ganesha_stats json" work. Please let me know the steps how to push that code into nfs-ganesha repo, and whom to add as reviewer?

**Comment by dang** [comment]
https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/CONTRIBUTING_HOWTO.txt
