### ISSUE TITLE
EVENT_RELEASE_IP whether it is a server IP address or a client IP?

### ISSUE THREAD

**Issue by Haroldll** [nfs-ganesha/nfs-ganesha#985]
When I'm reading the interface of nfs_release_v4_clients (GSP-> iPaddr), The interface of ip_match(ip, cp) use RELEASE_IP and cr_client_val to compare, see:
```
static int ip_match(char *ip, nfs_client_id_t *cid)
{
	char *haystack;
	char *value = cid->cid_client_record->cr_client_val;
	int len = cid->cid_client_record->cr_client_val_len;

	LogDebug(COMPONENT_STATE, "NFS Server V4 match ip %s with (%.*s)",
		 ip, len, value);

	if (strlen(ip) == 0)	/* No IP all are matching */
		return 1;

	haystack = alloca(len + 1);
	memcpy(haystack, value, len);
	haystack[len] = '\0';
	if (strstr(haystack, ip) != NULL)
		return 1;

	return 0;		/* no match */
}
```
But cr_client_val is a client-related string, consists of 'Linux NFSv4.2 hostname', ip_match() always returns 0, nfs_release_v4_clients() did not complete the client_id_expire.
From here, it seems that want to compare the client IP, but the RELEASE_IP we use is the server-side IP.
So here the comparison, I'm confused. Regardless of whether the server IP or client IP is passed in, ip_match() always returns 0.

So how to use it, is right, thanks!

**Comment by ffilz** [comment]
RELEASE_IP is used for HA setups where each node has a virtual IP (VIP). When a node fails, it's VIP is assigned to a different node and TAKE_IP is sent to let that node know. When the original node comes back up, RELEASE_IP is used to enable fail back to the original node. The intent of RELEASE_IP is that the node that assumed the VIP enters grace period (as well as all the other nodes) and then the node releases all state associated with the VIP that is failing back. That allows the clients to utilize the normal state reclaim to re-acquire the state on the original node.

It's also possible this code has gone stale is doesn't work right.

**Comment by Haroldll** [comment]
Yes, release_ip usage is the same as I thought, and the code is really doesn't work right.

Is it that no one uses it this way, so no plan to fix it?

**Comment by ffilz** [comment]
I'm not sure if anything uses it anymore.

**Comment by Haroldll** [comment]
> I'm not sure if anything uses it anymore.

Got it, thanks for reply.

**Comment by zhitaoli-6** [comment]
@Haroldll  Hi, what's your solution about this issue afterwards? I have the similar issue now.
