### ISSUE TITLE
CEPH_FS_NONBLOCKING_IO  is stuck when compiling the Linux kernel in the NFS mount directory

### ISSUE THREAD

**Issue by Haroldll** [nfs-ganesha/nfs-ganesha#988]
My ganesha version is 5.5. 
The ceph version is the latest, and NONBLOCKING_IO compilation is on.

When my client mounts the NFS directory, both reading and writing are normal.

But when I tried to compile the Linux kernel in the mount directory, or other software compilation, it quickly got stuck.

I analyzed the ganesha log and found that one client's read request was not completed.
Because of the read request, ceph_ll_nonblocking_readv_writev returned 0, but ceph client did not call the callback.
Then I analyzed from ceph client and found that the file size of this read is 0, although the requested offset is 0 and len is 8192.
In this case, ceph returns 0 directly and thinks that read is complete and will not call the callback function again.
see:
```
int Client::_read_async(Fh *f, uint64_t off, uint64_t len, bufferlist *bl,
			Context *onfinish)
{
  ceph_assert(ceph_mutex_is_locked_by_me(client_lock));

  const auto& conf = cct->_conf;
  Inode *in = f->inode.get();

  ldout(cct, 10) << __func__ << " " << *in << " " << off << "~" << len << dendl;

  // trim read based on file size?
  if (off >= in->size)
    return 0;
  if (len == 0)
    return 0;
  if (off + len > in->size) {
    len = in->size - off;    
  }
```
But the design of ganesha is that as long as it returns 0, it is considered an nonblocking read and then waits for a callback.
see:
```
        result = ceph_ll_nonblocking_readv_writev(export->cmount,
						  &cbi->io_info);

	if (result < 0) {
		/* An error occurred. */
		status = ceph2fsal_error(result);
	} else if (result == 0) {
		/* I/O will complete async, return. */
		return;
	} else {
		/* I/O actually completed... */
		read_arg->io_amount = result;
	}
```
So ceph_ll_nonblocking_readv_writev returns 0, which doesn't have to be nonblocking read, it could be something else. 
Is that a question?

**Comment by ffilz** [comment]
Hmm, I see the problem here...

I think this needs to be a fix in libcephfs. It probably should just make the callback with 0 bytes.

**Comment by ffilz** [comment]
This should also be reported in the ceph project.

**Comment by Haroldll** [comment]
Saw the patch in the ceph community, close.

**Comment by ffilz** [comment]
Actually, let's keep this open for now to track that the Ceph patch gets all of where it needs to get.

Thanks, I had forgotten who had raised the original issue.

**Comment by ffilz** [comment]
There have been some fixes in libcephfs, I think they are now merged. Could you please check?

**Comment by ffilz** [comment]
There are a lot of ceph changes.

However, the async/non-blocking support opens Ganesha to unbounded resource use as I/O requests are queued inside ceph so until we have a solution as part of QOS we discourage use of async/non-blocking I/O. That said, there is a configuration option to enable/disable it for ceph.

Closing this as we will track the unbounded resource use as part of the Quality of Service effort we are undertaking.
