### ISSUE TITLE
vector of buffers in write_arg

### ISSUE THREAD

**Issue by songmuhan** [nfs-ganesha/nfs-ganesha#998]
Hello, I have encountered a problem while examining the source code that I am unable to resolve. My question pertains to the initialization of `write_arg` within the `nfs4_op_write` function.

```	
struct fsal_io_arg *write_arg;
...
write_arg->iov_count = 1;
write_arg->iov[0].iov_len = size;
write_arg->iov[0].iov_base = arg_WRITE4->data.data_val;
```
It appears that `fsal_io_arg` is defined as a vector of buffers. However, in this particular instance, only **one** item is being used.

I am curious if there is a specific reason for this design choice that I may have overlooked.

**Comment by ffilz** [comment]
The option for vectors was introduced since many back ends can do vector I/O. We will be investigating using this capability to do zero copy writes by submitting the buffers as they are streamed in so this capability will likely be used in the future.

**Comment by songmuhan** [comment]
I got the idea. Thank for your time :)
